.TH "Loader Directory Reference" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Loader Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBTest\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBConnector\&.h\fP"
.br
.ti -1c
.RI "file \fBHdfsconnector\&.cpp\fP"
.br
.ti -1c
.RI "file \fBHdfsconnector\&.h\fP"
.br
.ti -1c
.RI "file \fBHdfsloader\&.cpp\fP"
.br
.ti -1c
.RI "file \fBHdfsloader\&.h\fP"
.br
.ti -1c
.RI "file \fBLocalDiskConnector\&.cpp\fP"
.br
.ti -1c
.RI "file \fBLocalDiskConnector\&.h\fP"
.br
.in -1c
