.TH "Catalog Directory Reference" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catalog Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBstat\fP"
.br
.ti -1c
.RI "directory \fBTest\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAttribute\&.h\fP"
.br
.ti -1c
.RI "file \fBCatalog\&.cpp\fP"
.br
.ti -1c
.RI "file \fBCatalog\&.h\fP"
.br
.ti -1c
.RI "file \fBColumn\&.cpp\fP"
.br
.ti -1c
.RI "file \fBColumn\&.h\fP"
.br
.ti -1c
.RI "file \fBPartitioner\&.cpp\fP"
.br
.ti -1c
.RI "file \fBPartitioner\&.h\fP"
.br
.ti -1c
.RI "file \fBProjectionBinding\&.cpp\fP"
.br
.ti -1c
.RI "file \fBProjectionBinding\&.h\fP"
.br
.ti -1c
.RI "file \fBtable\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtable\&.h\fP"
.br
.ti -1c
.RI "file \fBunordered_map\&.hpp\fP"
.br
.in -1c
