.TH "logical_operator Directory Reference" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logical_operator Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBlogical_aggregation\&.cpp\fP"
.br
.ti -1c
.RI "file \fBlogical_aggregation\&.h\fP"
.br
.ti -1c
.RI "file \fBlogical_cross_join\&.cpp\fP"
.br
.ti -1c
.RI "file \fBlogical_cross_join\&.h\fP"
.br
.ti -1c
.RI "file \fBlogical_equal_join\&.cpp\fP"
.br
.ti -1c
.RI "file \fBlogical_equal_join\&.h\fP"
.br
.ti -1c
.RI "file \fBlogical_filter\&.cpp\fP"
.br
.ti -1c
.RI "file \fBlogical_filter\&.h\fP"
.br
.ti -1c
.RI "file \fBlogical_limit\&.cpp\fP"
.br
.ti -1c
.RI "file \fBlogical_limit\&.h\fP"
.br
.ti -1c
.RI "file \fBlogical_operator\&.cpp\fP"
.br
.ti -1c
.RI "file \fBlogical_operator\&.h\fP"
.br
.ti -1c
.RI "file \fBlogical_project\&.cpp\fP"
.br
.ti -1c
.RI "file \fBlogical_project\&.h\fP"
.br
.ti -1c
.RI "file \fBlogical_query_plan_root\&.cpp\fP"
.br
.ti -1c
.RI "file \fBlogical_query_plan_root\&.h\fP"
.br
.ti -1c
.RI "file \fBlogical_scan\&.cpp\fP"
.br
.ti -1c
.RI "file \fBlogical_scan\&.h\fP"
.br
.ti -1c
.RI "file \fBlogical_sort\&.cpp\fP"
.br
.ti -1c
.RI "file \fBlogical_sort\&.h\fP"
.br
.ti -1c
.RI "file \fBplan_context\&.cpp\fP"
.br
.ti -1c
.RI "file \fBplan_context\&.h\fP"
.br
.ti -1c
.RI "file \fBplan_partition_info\&.cpp\fP"
.br
.ti -1c
.RI "file \fBplan_partition_info\&.h\fP"
.br
.ti -1c
.RI "file \fBplan_partitioner\&.cpp\fP"
.br
.ti -1c
.RI "file \fBplan_partitioner\&.h\fP"
.br
.ti -1c
.RI "file \fBRequirement\&.cpp\fP"
.br
.ti -1c
.RI "file \fBRequirement\&.h\fP"
.br
.in -1c
