.TH "IndexManager Directory Reference" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IndexManager Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBTest\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCSBIndexBuilding\&.cpp\fP"
.br
.ti -1c
.RI "file \fBCSBIndexBuilding\&.h\fP"
.br
.ti -1c
.RI "file \fBCSBPlusTree\&.cpp\fP"
.br
.ti -1c
.RI "file \fBCSBPlusTree\&.h\fP"
.br
.ti -1c
.RI "file \fBIndexManager\&.cpp\fP"
.br
.ti -1c
.RI "file \fBIndexManager\&.h\fP"
.br
.ti -1c
.RI "file \fBIndexScanIterator\&.cpp\fP"
.br
.ti -1c
.RI "file \fBIndexScanIterator\&.h\fP"
.br
.ti -1c
.RI "file \fBLogicalCSBIndexBuilding\&.cpp\fP"
.br
.ti -1c
.RI "file \fBLogicalCSBIndexBuilding\&.h\fP"
.br
.ti -1c
.RI "file \fBLogicalIndexFilter\&.cpp\fP"
.br
.ti -1c
.RI "file \fBLogicalIndexFilter\&.h\fP"
.br
.ti -1c
.RI "file \fBLogicalIndexScan\&.cpp\fP"
.br
.ti -1c
.RI "file \fBLogicalIndexScan\&.h\fP"
.br
.in -1c
