.TH "physical_operator/Serialization Directory Reference" 3 "Mon Oct 5 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
physical_operator/Serialization Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBRegisterDerivedClass\&.cpp\fP"
.br
.ti -1c
.RI "file \fBRegisterDerivedClass\&.h\fP"
.br
.in -1c
