.TH "Client Directory Reference" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Client Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBjson\fP"
.br
.ti -1c
.RI "directory \fBTest\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBClaimsServer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBClaimsServer\&.h\fP"
.br
.ti -1c
.RI "file \fBClient\&.cpp\fP"
.br
.ti -1c
.RI "file \fBClient\&.h\fP"
.br
.ti -1c
.RI "file \fBClientResponse\&.cpp\fP"
.br
.ti -1c
.RI "file \fBClientResponse\&.h\fP"
.br
.ti -1c
.RI "file \fBjsoncpp\&.cpp\fP"
.br
.in -1c
