.TH "physical_operator Directory Reference" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
physical_operator Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBlockStreamAggregationIterator\&.cpp\fP"
.br
.ti -1c
.RI "file \fBBlockStreamAggregationIterator\&.h\fP"
.br
.ti -1c
.RI "file \fBBlockStreamCombinedIterator\&.cpp\fP"
.br
.ti -1c
.RI "file \fBBlockStreamCombinedIterator\&.h\fP"
.br
.ti -1c
.RI "file \fBBlockStreamExchangeLowerBase\&.cpp\fP"
.br
.ti -1c
.RI "file \fBBlockStreamExchangeLowerBase\&.h\fP"
.br
.ti -1c
.RI "file \fBBlockStreamExpander\&.cpp\fP"
.br
.ti -1c
.RI "file \fBBlockStreamExpander\&.h\fP"
.br
.ti -1c
.RI "file \fBBlockStreamInIterator\&.cpp\fP"
.br
.ti -1c
.RI "file \fBBlockStreamInIterator\&.h\fP"
.br
.ti -1c
.RI "file \fBBlockStreamIteratorBase\&.cpp\fP"
.br
.ti -1c
.RI "file \fBBlockStreamIteratorBase\&.h\fP"
.br
.ti -1c
.RI "file \fBBlockStreamJoinIterator\&.cpp\fP"
.br
.ti -1c
.RI "file \fBBlockStreamJoinIterator\&.h\fP"
.br
.ti -1c
.RI "file \fBBlockStreamLimit\&.cpp\fP"
.br
.ti -1c
.RI "file \fBBlockStreamLimit\&.h\fP"
.br
.ti -1c
.RI "file \fBBlockStreamNestLoopJoinIterator\&.cpp\fP"
.br
.ti -1c
.RI "file \fBBlockStreamNestLoopJoinIterator\&.h\fP"
.br
.ti -1c
.RI "file \fBBlockStreamPerformanceMonitorTop\&.cpp\fP"
.br
.ti -1c
.RI "file \fBBlockStreamPerformanceMonitorTop\&.h\fP"
.br
.ti -1c
.RI "file \fBBlockStreamPrint\&.cpp\fP"
.br
.ti -1c
.RI "file \fBBlockStreamPrint\&.h\fP"
.br
.ti -1c
.RI "file \fBBlockStreamProjectIterator\&.cpp\fP"
.br
.ti -1c
.RI "file \fBBlockStreamProjectIterator\&.h\fP"
.br
.ti -1c
.RI "file \fBBlockStreamResultCollector\&.cpp\fP"
.br
.ti -1c
.RI "file \fBBlockStreamResultCollector\&.h\fP"
.br
.ti -1c
.RI "file \fBBlockStreamSortIterator\&.cpp\fP"
.br
.ti -1c
.RI "file \fBBlockStreamSortIterator\&.h\fP"
.br
.ti -1c
.RI "file \fBExpandableBlockStreamBuffer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBExpandableBlockStreamBuffer\&.h\fP"
.br
.ti -1c
.RI "file \fBExpandableBlockStreamExchangeEpoll\&.cpp\fP"
.br
.ti -1c
.RI "file \fBExpandableBlockStreamExchangeEpoll\&.h\fP"
.br
.ti -1c
.RI "file \fBExpandableBlockStreamExchangeLowerEfficient\&.cpp\fP"
.br
.ti -1c
.RI "file \fBExpandableBlockStreamExchangeLowerEfficient\&.h\fP"
.br
.ti -1c
.RI "file \fBExpandableBlockStreamExchangeLowerMaterialized\&.cpp\fP"
.br
.ti -1c
.RI "file \fBExpandableBlockStreamExchangeLowerMaterialized\&.h\fP"
.br
.ti -1c
.RI "file \fBExpandableBlockStreamFilter\&.cpp\fP"
.br
.ti -1c
.RI "file \fBExpandableBlockStreamFilter\&.h\fP"
.br
.ti -1c
.RI "file \fBExpandableBlockStreamHdfsScan\&.cpp\fP"
.br
.ti -1c
.RI "file \fBExpandableBlockStreamHdfsScan\&.h\fP"
.br
.ti -1c
.RI "file \fBExpandableBlockStreamProjectionScan\&.cpp\fP"
.br
.ti -1c
.RI "file \fBExpandableBlockStreamProjectionScan\&.h\fP"
.br
.ti -1c
.RI "file \fBExpandableBlockStreamRandomDiskAccess\&.cpp\fP"
.br
.ti -1c
.RI "file \fBExpandableBlockStreamRandomDiskAccess\&.h\fP"
.br
.ti -1c
.RI "file \fBExpandableBlockStreamRandomMemAccess\&.cpp\fP"
.br
.ti -1c
.RI "file \fBExpandableBlockStreamRandomMemAccess\&.h\fP"
.br
.ti -1c
.RI "file \fBExpandableBlockStreamSingleColumnScan\&.cpp\fP"
.br
.ti -1c
.RI "file \fBExpandableBlockStreamSingleColumnScan\&.h\fP"
.br
.ti -1c
.RI "file \fBExpandableBlockStreamSingleColumnScanDisk\&.cpp\fP"
.br
.ti -1c
.RI "file \fBExpandableBlockStreamSingleColumnScanDisk\&.h\fP"
.br
.ti -1c
.RI "file \fBphysical_operator\&.cpp\fP"
.br
.ti -1c
.RI "file \fBphysical_operator\&.h\fP"
.br
.in -1c
