.TH "AdaptiveEndPoint" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdaptiveEndPoint \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AdaptiveEndPoint\&.h>\fP
.PP
Inherits EndPoint\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConnectionActor\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAdaptiveEndPoint\fP (const char *name, std::string ip, std::string port)"
.br
.ti -1c
.RI "virtual \fB~AdaptiveEndPoint\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "Theron::Framework * \fBframework\fP"
.br
.ti -1c
.RI "\fBLogging\fP * \fBlogging_\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "bool \fBSayHelloToCoordinator\fP (std::string ip, std::string port)"
.br
.ti -1c
.RI "int \fBGetCoordinatorEndPointPort\fP ()"
.br
.ti -1c
.RI "bool \fBWaitForReadySignalFromCoordinator\fP ()"
.br
.ti -1c
.RI "bool \fBConnectToCoordinateEndPoint\fP (int port)"
.br
.ti -1c
.RI "bool \fBConnectToRemoteEndPoint\fP (std::string location)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Theron::Actor * \fBconnectionActor\fP"
.br
.ti -1c
.RI "int \fBsocket_coor\fP"
.br
.ti -1c
.RI "std::string \fBip_coor\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBConnectionActor\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AdaptiveEndPoint::AdaptiveEndPoint (const char *name, std::stringip, std::stringport)"

.PP
References connectionActor, ConnectionActor, ConnectToCoordinateEndPoint(), Logging::elog(), FileClose(), framework, GetCoordinatorEndPointPort(), Logging::log(), logging_, SayHelloToCoordinator(), socket_coor, and WaitForReadySignalFromCoordinator()\&.
.SS "AdaptiveEndPoint::~AdaptiveEndPoint ()\fC [virtual]\fP"

.PP
References connectionActor, and framework\&.
.SH "Member Function Documentation"
.PP 
.SS "bool AdaptiveEndPoint::ConnectToCoordinateEndPoint (intport)\fC [private]\fP"

.PP
References ConnectToRemoteEndPoint(), Logging::elog(), ip_coor, Logging::log(), and logging_\&.
.PP
Referenced by AdaptiveEndPoint()\&.
.SS "bool AdaptiveEndPoint::ConnectToRemoteEndPoint (std::stringlocation)\fC [private]\fP"

.PP
Referenced by ConnectToCoordinateEndPoint()\&.
.SS "int AdaptiveEndPoint::GetCoordinatorEndPointPort ()\fC [private]\fP"

.PP
References Logging::elog(), ip_coor, Logging::log(), logging_, and socket_coor\&.
.PP
Referenced by AdaptiveEndPoint()\&.
.SS "bool AdaptiveEndPoint::SayHelloToCoordinator (std::stringip, std::stringport)\fC [private]\fP"

.PP
References Config::config_file, Logging::elog(), ThreadSafe::gethostbyname_ts(), ip_coor, logging_, and socket_coor\&.
.PP
Referenced by AdaptiveEndPoint()\&.
.SS "bool AdaptiveEndPoint::WaitForReadySignalFromCoordinator ()\fC [private]\fP"

.PP
References Logging::elog(), Logging::log(), logging_, and socket_coor\&.
.PP
Referenced by AdaptiveEndPoint()\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBConnectionActor\fP\fC [friend]\fP"
The Actor which receive the node states from the coordinator 
.PP
Referenced by AdaptiveEndPoint()\&.
.SH "Member Data Documentation"
.PP 
.SS "Theron::Actor* AdaptiveEndPoint::connectionActor\fC [private]\fP"

.PP
Referenced by AdaptiveEndPoint(), and ~AdaptiveEndPoint()\&.
.SS "Theron::Framework* AdaptiveEndPoint::framework\fC [protected]\fP"

.PP
Referenced by AdaptiveEndPoint(), and ~AdaptiveEndPoint()\&.
.SS "std::string AdaptiveEndPoint::ip_coor\fC [private]\fP"

.PP
Referenced by ConnectToCoordinateEndPoint(), GetCoordinatorEndPointPort(), and SayHelloToCoordinator()\&.
.SS "\fBLogging\fP* AdaptiveEndPoint::logging_\fC [protected]\fP"

.PP
Referenced by AdaptiveEndPoint(), ConnectToCoordinateEndPoint(), GetCoordinatorEndPointPort(), SayHelloToCoordinator(), and WaitForReadySignalFromCoordinator()\&.
.SS "int AdaptiveEndPoint::socket_coor\fC [private]\fP"

.PP
Referenced by AdaptiveEndPoint(), GetCoordinatorEndPointPort(), SayHelloToCoordinator(), and WaitForReadySignalFromCoordinator()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
