.TH "AdaptiveEndPointLogging" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdaptiveEndPointLogging \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Logging\&.h>\fP
.PP
Inherits \fBLogging\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBlog\fP (const char *format,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBelog\fP (const char *format,\&.\&.\&.)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void AdaptiveEndPointLogging::elog (const char *format, \&.\&.\&.)\fC [virtual]\fP"
print the error information to stderr\&. 
.PP
Implements \fBLogging\fP\&.
.PP
References RawElog()\&.
.SS "void AdaptiveEndPointLogging::log (const char *format, \&.\&.\&.)\fC [virtual]\fP"

.PP
Implements \fBLogging\fP\&.
.PP
References RawLog()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
