.TH "AdaptiveEndPoint" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdaptiveEndPoint \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits EndPoint\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAdaptiveEndPoint\fP (const char *name, std::string ip, std::string port)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "Theron::Framework * \fBframework\fP"
.br
.ti -1c
.RI "\fBLogging\fP * \fBlogging_\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBConnectionActor\fP"
.br
.in -1c
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class ConnectionActor\fC [friend]\fP"
The Actor which receive the node states from the coordinator 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
