.TH "Alterdatabase_stmt" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Alterdatabase_stmt \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sql_node_struct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnodetype\fP \fBtype\fP"
.br
.ti -1c
.RI "int \fBcreatetype\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBopt\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int Alterdatabase_stmt::createtype"

.PP
Referenced by newAlterDatabaseStmt()\&.
.SS "char* Alterdatabase_stmt::name"

.PP
Referenced by newAlterDatabaseStmt()\&.
.SS "\fBNode\fP* Alterdatabase_stmt::opt"

.PP
Referenced by newAlterDatabaseStmt()\&.
.SS "\fBnodetype\fP Alterdatabase_stmt::type"

.PP
Referenced by newAlterDatabaseStmt()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
