.TH "Altertable_stmt" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Altertable_stmt \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sql_node_struct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnodetype\fP \fBtype\fP"
.br
.ti -1c
.RI "int \fBisignore\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBparameter\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int Altertable_stmt::isignore"

.PP
Referenced by newAlterTableStmt()\&.
.SS "char* Altertable_stmt::name"

.PP
Referenced by newAlterTableStmt()\&.
.SS "\fBNode\fP* Altertable_stmt::parameter"

.PP
Referenced by newAlterTableStmt()\&.
.SS "\fBnodetype\fP Altertable_stmt::type"

.PP
Referenced by newAlterTableStmt()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
