.TH "Arg" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arg \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hash_table_test\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBlockStreamBuffer\fP * \fBbuffer\fP"
.br
.ti -1c
.RI "\fBBasicHashTable\fP ** \fBhash_table\fP"
.br
.ti -1c
.RI "\fBSchema\fP * \fBschema\fP"
.br
.ti -1c
.RI "\fBPartitionFunction\fP * \fBhash\fP"
.br
.ti -1c
.RI "\fBPhysicalOperatorBase\fP * \fBiterator\fP"
.br
.ti -1c
.RI "\fBPartitionStorage::PartitionReaderItetaor\fP * \fBpartition_reader\fP"
.br
.ti -1c
.RI "\fBBarrier\fP * \fBbarrier\fP"
.br
.ti -1c
.RI "unsigned \fBtid\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBBarrier\fP* Arg::barrier"

.PP
Referenced by fill_basic_hash_table(), insert_into_hash_table(), insert_into_hash_table_from_projection(), and projection_scan()\&.
.SS "\fBBlockStreamBuffer\fP* Arg::buffer"

.PP
Referenced by fill_basic_hash_table(), and insert_into_hash_table()\&.
.SS "\fBPartitionFunction\fP* Arg::hash"

.PP
Referenced by fill_basic_hash_table(), insert_into_hash_table(), insert_into_hash_table_from_projection(), and projection_scan()\&.
.SS "\fBBasicHashTable\fP** Arg::hash_table"

.PP
Referenced by fill_basic_hash_table(), insert_into_hash_table(), insert_into_hash_table_from_projection(), and projection_scan()\&.
.SS "\fBPhysicalOperatorBase\fP* Arg::iterator"

.SS "\fBPartitionStorage::PartitionReaderItetaor\fP* Arg::partition_reader"

.PP
Referenced by insert_into_hash_table_from_projection(), and projection_scan()\&.
.SS "\fBSchema\fP* Arg::schema"

.PP
Referenced by fill_basic_hash_table(), insert_into_hash_table(), insert_into_hash_table_from_projection(), and projection_scan()\&.
.SS "unsigned Arg::tid"

.PP
Referenced by fill_basic_hash_table(), insert_into_hash_table(), insert_into_hash_table_from_projection(), and projection_scan()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
