.TH "AttributeID" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AttributeID \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ids\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAttributeID\fP (\fBTableID\fP tid, \fBAttributeOffset\fP off)"
.br
.ti -1c
.RI "\fBAttributeID\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBAttributeID\fP &r) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTableID\fP \fBtable_id\fP"
.br
.ti -1c
.RI "\fBAttributeOffset\fP \fBoffset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAttributeID\fP: an attribute in a table has an unique \fBAttributeID\fP 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AttributeID::AttributeID (\fBTableID\fPtid, \fBAttributeOffset\fPoff)\fC [inline]\fP"

.SS "AttributeID::AttributeID ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool AttributeID::operator== (const \fBAttributeID\fP &r) const\fC [inline]\fP"

.PP
References offset, and table_id\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBAttributeOffset\fP AttributeID::offset"

.PP
Referenced by Analyzer::analyse(), Analyzer::compute_attribute_stat(), Analyzer::computeHistogram(), Estimation::estEqualJoin(), Estimation::estEqualOper(), Estimation::estRangeOper(), Analyzer::getDistinctCardinality(), hash_value(), and operator==()\&.
.SS "\fBTableID\fP AttributeID::table_id"

.PP
Referenced by Analyzer::analyse(), Analyzer::compute_attribute_stat(), Analyzer::computeHistogram(), Estimation::estEqualJoin(), Estimation::estEqualOper(), Estimation::estRangeOper(), StatManager::getAttributeStatistic(), Analyzer::getDistinctCardinality(), hash_value(), and operator==()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
