.TH "AttributeID" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AttributeID \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ids\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAttributeID\fP (TableID tid, AttributeOffset off)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBAttributeID\fP &r) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TableID \fBtable_id\fP"
.br
.ti -1c
.RI "AttributeOffset \fBoffset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAttributeID\fP: an attribute in a table has an unique \fBAttributeID\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
