.TH "AttributeStatistics" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AttributeStatistics \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AttributeStatistics\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAttributeStatistics\fP ()"
.br
.ti -1c
.RI "virtual \fB~AttributeStatistics\fP ()"
.br
.ti -1c
.RI "void \fBsetDistinctCardinality\fP (unsigned long int value)"
.br
.ti -1c
.RI "void \fBsetHistogram\fP (\fBHistogram\fP *his)"
.br
.ti -1c
.RI "\fBHistogram\fP * \fBgetHistogram\fP () const "
.br
.ti -1c
.RI "void \fBprint\fP () const "
.br
.ti -1c
.RI "unsigned long \fBgetDistinctCardinality\fP () const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned long \fBdistinct_cardinality_\fP"
.br
.ti -1c
.RI "void * \fBmax_\fP"
.br
.ti -1c
.RI "void * \fBmin_\fP"
.br
.ti -1c
.RI "\fBHistogram\fP * \fBhistogram_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AttributeStatistics::AttributeStatistics ()"

.SS "AttributeStatistics::~AttributeStatistics ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "unsigned long AttributeStatistics::getDistinctCardinality () const"

.PP
References distinct_cardinality_\&.
.PP
Referenced by claims::logical_operator::LogicalAggregation::EstimateGroupByCardinality(), and claims::logical_operator::LogicalEqualJoin::PredictEqualJoinSelectivityOnSingleJoinAttributePair()\&.
.SS "\fBHistogram\fP * AttributeStatistics::getHistogram () const"

.PP
References histogram_\&.
.PP
Referenced by Estimation::estEqualJoin(), StatManager::getHistogram(), and claims::logical_operator::LogicalEqualJoin::PredictEqualJoinSelectivityOnSingleJoinAttributePair()\&.
.SS "void AttributeStatistics::print () const"

.PP
References distinct_cardinality_\&.
.PP
Referenced by Analyzer::compute_attribute_stat()\&.
.SS "void AttributeStatistics::setDistinctCardinality (unsigned long intvalue)"

.PP
References distinct_cardinality_\&.
.PP
Referenced by Analyzer::compute_attribute_stat()\&.
.SS "void AttributeStatistics::setHistogram (\fBHistogram\fP *his)"

.PP
References histogram_\&.
.PP
Referenced by Analyzer::compute_attribute_stat()\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned long AttributeStatistics::distinct_cardinality_\fC [private]\fP"

.PP
Referenced by getDistinctCardinality(), print(), and setDistinctCardinality()\&.
.SS "\fBHistogram\fP* AttributeStatistics::histogram_\fC [private]\fP"

.PP
Referenced by getHistogram(), and setHistogram()\&.
.SS "void* AttributeStatistics::max_\fC [private]\fP"

.SS "void* AttributeStatistics::min_\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
