.TH "Barrier" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Barrier \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lock\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBarrier\fP (int nThreads=0)"
.br
.ti -1c
.RI "void \fBRegisterOneThread\fP ()"
.br
.ti -1c
.RI "void \fBUnregisterOneThread\fP ()"
.br
.ti -1c
.RI "virtual \fB~Barrier\fP ()"
.br
.ti -1c
.RI "void \fBsetEmpty\fP ()"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "void \fBArrive\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBm_nThreads\fP"
.br
.ti -1c
.RI "pthread_mutex_t \fBm_l_SyncLock\fP"
.br
.ti -1c
.RI "pthread_cond_t \fBm_cv_SyncCV\fP"
.br
.ti -1c
.RI "volatile int \fBm_nSyncCount\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Barrier::Barrier (intnThreads = \fC0\fP)\fC [inline]\fP"

.PP
References m_cv_SyncCV, m_l_SyncLock, m_nSyncCount, m_nThreads, and NULL\&.
.SS "virtual Barrier::~Barrier ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
References m_cv_SyncCV, and m_l_SyncLock\&.
.SH "Member Function Documentation"
.PP 
.SS "void Barrier::Arrive ()\fC [inline]\fP"

.PP
References m_cv_SyncCV, m_l_SyncLock, m_nSyncCount, and m_nThreads\&.
.PP
Referenced by claims::physical_operator::PhysicalOperator::BarrierArrive(), insert_into_hash_table(), insert_into_hash_table_from_projection(), insert_into_insert_optimized_hash_table(), and claims::physical_operator::InOperator::Open()\&.
.SS "void Barrier::RegisterOneThread ()\fC [inline]\fP"

.PP
References m_l_SyncLock, and m_nThreads\&.
.PP
Referenced by claims::physical_operator::PhysicalOperator::RegisterExpandedThreadToAllBarriers()\&.
.SS "void Barrier::reset ()\fC [inline]\fP"

.PP
References m_nSyncCount\&.
.PP
Referenced by insert_into_hash_table()\&.
.SS "void Barrier::setEmpty ()\fC [inline]\fP"

.PP
References m_nSyncCount, and m_nThreads\&.
.PP
Referenced by claims::physical_operator::PhysicalOperator::InitExpandedStatus()\&.
.SS "void Barrier::UnregisterOneThread ()\fC [inline]\fP"

.PP
References m_cv_SyncCV, m_l_SyncLock, m_nSyncCount, and m_nThreads\&.
.PP
Referenced by claims::physical_operator::PhysicalOperator::UnregisterExpandedThreadToAllBarriers()\&.
.SH "Member Data Documentation"
.PP 
.SS "pthread_cond_t Barrier::m_cv_SyncCV\fC [private]\fP"

.PP
Referenced by Arrive(), Barrier(), UnregisterOneThread(), and ~Barrier()\&.
.SS "pthread_mutex_t Barrier::m_l_SyncLock\fC [private]\fP"

.PP
Referenced by Arrive(), Barrier(), RegisterOneThread(), UnregisterOneThread(), and ~Barrier()\&.
.SS "volatile int Barrier::m_nSyncCount\fC [private]\fP"

.PP
Referenced by Arrive(), Barrier(), reset(), setEmpty(), and UnregisterOneThread()\&.
.SS "int Barrier::m_nThreads\fC [private]\fP"

.PP
Referenced by Arrive(), Barrier(), RegisterOneThread(), setEmpty(), and UnregisterOneThread()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
