.TH "BasicHashTable::Iterator" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BasicHashTable::Iterator \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIterator\fP (const unsigned &buck_actual_size, const unsigned &tuplesize)"
.br
.ti -1c
.RI "\fBIterator\fP (const \fBIterator\fP &r)"
.br
.ti -1c
.RI "void * \fBreadnext\fP ()"
.br
.ti -1c
.RI "void * \fBreadCurrent\fP () const "
.br
.ti -1c
.RI "void \fBincrease_cur_\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBBasicHashTable\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
