.TH "bit128" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bit128 \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int64_t \fBa\fP"
.br
.ti -1c
.RI "int64_t \fBb\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int64_t bit128::a"

.SS "int64_t bit128::b"


.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
