.TH "BlockStreamNestLoopJoinIterator::remaining_block" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockStreamNestLoopJoinIterator::remaining_block \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBremaining_block\fP (\fBBlockStreamBase\fP *bsb_right, \fBBlockStreamBase::BlockStreamTraverseIterator\fP *bsti)"
.br
.ti -1c
.RI "\fBremaining_block\fP (const \fBremaining_block\fP &r)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBlockStreamBase\fP * \fBbsb_right_\fP"
.br
.ti -1c
.RI "\fBBlockStreamBase::BlockStreamTraverseIterator\fP * \fBblockstream_iterator\fP"
.br
.ti -1c
.RI "\fBDynamicBlockBuffer::Iterator\fP * \fBbuffer_iterator_\fP"
.br
.ti -1c
.RI "\fBBlockStreamBase::BlockStreamTraverseIterator\fP * \fBbuffer_stream_iterator_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
