.TH "BlockMessage" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockMessage \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BlockMessage\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlockMessage\fP ()"
.br
.ti -1c
.RI "virtual \fB~BlockMessage\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BlockMessage::BlockMessage ()"

.SS "BlockMessage::~BlockMessage ()\fC [virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
