.TH "BlockInfo" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Partitioner\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBlockID\fP \fBblock_id\fP"
.br
.ti -1c
.RI "int \fBtuple_count\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBBlockID\fP BlockInfo::block_id"

.SS "int BlockInfo::tuple_count"


.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
