.TH "BlockStreamBuffer" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockStreamBuffer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BlockStreamBuffer\&.h>\fP
.PP
Inherits \fBMonitorableBuffer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlockStreamBuffer\fP (unsigned \fBblock_size\fP, unsigned block_count, \fBSchema\fP *schema)"
.br
.ti -1c
.RI "virtual \fB~BlockStreamBuffer\fP ()"
.br
.ti -1c
.RI "void \fBinsertBlock\fP (\fBBlockStreamBase\fP *block)"
.br
.ti -1c
.RI "bool \fBgetBlock\fP (\fBBlockStreamBase\fP &block)"
.br
.ti -1c
.RI "unsigned \fBgetBlockInBuffer\fP ()"
.br
.ti -1c
.RI "bool \fBEmpty\fP ()"
.br
.ti -1c
.RI "double \fBgetBufferUsage\fP ()"
.br
.ti -1c
.RI "long \fBgetReceivedDataSizeInKbytes\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::list< \fBBlockStreamBase\fP * > \fBblock_stream_empty_list_\fP"
.br
.ti -1c
.RI "std::list< \fBBlockStreamBase\fP * > \fBblock_stream_used_list_\fP"
.br
.ti -1c
.RI "\fBsemaphore\fP \fBsema_empty_block_\fP"
.br
.ti -1c
.RI "\fBLock\fP \fBlock_\fP"
.br
.ti -1c
.RI "unsigned \fBtotal_block_count_\fP"
.br
.ti -1c
.RI "unsigned \fBblock_size_\fP"
.br
.ti -1c
.RI "unsigned long \fBreceived_block_count_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BlockStreamBuffer::BlockStreamBuffer (unsignedblock_size, unsignedblock_count, \fBSchema\fP *schema)"

.PP
References Lock::acquire(), block_stream_empty_list_, BlockStreamBase::createBlock(), semaphore::get_value(), lock_, semaphore::post(), Lock::release(), and sema_empty_block_\&.
.SS "BlockStreamBuffer::~BlockStreamBuffer ()\fC [virtual]\fP"

.PP
References block_stream_empty_list_, block_stream_used_list_, semaphore::destroy(), and sema_empty_block_\&.
.PP
Referenced by fill_basic_hash_table()\&.
.SH "Member Function Documentation"
.PP 
.SS "bool BlockStreamBuffer::Empty ()"

.PP
References Lock::acquire(), block_stream_used_list_, lock_, and Lock::release()\&.
.PP
Referenced by claims::physical_operator::Expander::ChildExhausted()\&.
.SS "bool BlockStreamBuffer::getBlock (\fBBlockStreamBase\fP &block)"

.PP
References Lock::acquire(), block_stream_empty_list_, block_stream_used_list_, lock_, semaphore::post(), Lock::release(), sema_empty_block_, and BlockStreamBase::switchBlock()\&.
.PP
Referenced by insert_into_hash_table(), claims::physical_operator::Expander::Next(), and claims::physical_operator::ExchangeMerger::Next()\&.
.SS "unsigned BlockStreamBuffer::getBlockInBuffer ()"

.PP
References Lock::acquire(), block_stream_used_list_, lock_, and Lock::release()\&.
.PP
Referenced by getBufferUsage()\&.
.SS "double BlockStreamBuffer::getBufferUsage ()\fC [virtual]\fP"

.PP
Implements \fBMonitorableBuffer\fP\&.
.PP
References getBlockInBuffer(), and total_block_count_\&.
.SS "long BlockStreamBuffer::getReceivedDataSizeInKbytes ()\fC [virtual]\fP"

.PP
Implements \fBMonitorableBuffer\fP\&.
.PP
References block_size_, and received_block_count_\&.
.PP
Referenced by claims::physical_operator::Expander::Close()\&.
.SS "void BlockStreamBuffer::insertBlock (\fBBlockStreamBase\fP *block)"

.PP
References Lock::acquire(), block_stream_empty_list_, block_stream_used_list_, BlockStreamBase::deepCopy(), Block::isIsReference(), lock_, received_block_count_, Lock::release(), sema_empty_block_, BlockStreamBase::switchBlock(), and semaphore::wait()\&.
.PP
Referenced by claims::physical_operator::Expander::ExpandedWork(), initial_input_date(), and claims::physical_operator::ExchangeMerger::Receiver()\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned BlockStreamBuffer::block_size_\fC [private]\fP"

.PP
Referenced by getReceivedDataSizeInKbytes()\&.
.SS "std::list<\fBBlockStreamBase\fP*> BlockStreamBuffer::block_stream_empty_list_\fC [private]\fP"

.PP
Referenced by BlockStreamBuffer(), getBlock(), insertBlock(), and ~BlockStreamBuffer()\&.
.SS "std::list<\fBBlockStreamBase\fP*> BlockStreamBuffer::block_stream_used_list_\fC [private]\fP"

.PP
Referenced by Empty(), getBlock(), getBlockInBuffer(), insertBlock(), and ~BlockStreamBuffer()\&.
.SS "\fBLock\fP BlockStreamBuffer::lock_\fC [private]\fP"

.PP
Referenced by BlockStreamBuffer(), Empty(), getBlock(), getBlockInBuffer(), and insertBlock()\&.
.SS "unsigned long BlockStreamBuffer::received_block_count_\fC [private]\fP"

.PP
Referenced by getReceivedDataSizeInKbytes(), and insertBlock()\&.
.SS "\fBsemaphore\fP BlockStreamBuffer::sema_empty_block_\fC [private]\fP"

.PP
Referenced by BlockStreamBuffer(), getBlock(), insertBlock(), and ~BlockStreamBuffer()\&.
.SS "unsigned BlockStreamBuffer::total_block_count_\fC [private]\fP"

.PP
Referenced by getBufferUsage()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
