.TH "BlockStreamFix" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockStreamFix \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BlockStream\&.h>\fP
.PP
Inherits \fBBlockStreamBase\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBtail_info\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlockStreamFix\fP (unsigned \fBblock_size\fP, unsigned tuple_size)"
.br
.ti -1c
.RI "\fBBlockStreamFix\fP (unsigned \fBblock_size\fP, unsigned tuple_size, void *start_addr, unsigned ntuples)"
.br
.ti -1c
.RI "virtual \fB~BlockStreamFix\fP ()"
.br
.ti -1c
.RI "void * \fBallocateTuple\fP (unsigned bytes)"
.br
.ti -1c
.RI "void \fBsetTuplesInBlock\fP (unsigned n)"
.br
.ti -1c
.RI "void \fBsetEmpty\fP ()"
.br
.ti -1c
.RI "void * \fBgetTuple\fP (unsigned offset) const "
.br
.ti -1c
.RI "bool \fBEmpty\fP () const "
.br
.ti -1c
.RI "bool \fBFull\fP () const "
.br
.ti -1c
.RI "void * \fBgetBlockDataAddress\fP ()"
.br
.ti -1c
.RI "bool \fBswitchBlock\fP (\fBBlockStreamBase\fP &block)"
.br
.ti -1c
.RI "void \fBcopyBlock\fP (void *addr, unsigned length)"
.br
.ti -1c
.RI "bool \fBinsert\fP (void *dest, void *src, unsigned bytes)"
.br
.ti -1c
.RI "void \fBdeepCopy\fP (const \fBBlock\fP *block)"
.br
.ti -1c
.RI "bool \fBserialize\fP (\fBBlock\fP &block) const "
.br
.ti -1c
.RI "bool \fBdeserialize\fP (\fBBlock\fP *block)"
.br
.ti -1c
.RI "unsigned \fBgetSerializedBlockSize\fP () const "
.br
.ti -1c
.RI "unsigned \fBgetBlockCapacityInTuples\fP () const "
.br
.ti -1c
.RI "unsigned \fBgetTuplesInBlock\fP () const "
.br
.ti -1c
.RI "void \fBconstructFromBlock\fP (const \fBBlock\fP &block)"
.br
.ti -1c
.RI "\fBBlockStreamBase\fP * \fBcreateBlockAndDeepCopy\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBtuple_size_\fP"
.br
.ti -1c
.RI "char * \fBfree_\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBBlockStreamBase\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BlockStreamFix::BlockStreamFix (unsignedblock_size, unsignedtuple_size)"

.PP
References free_, and Block::start\&.
.PP
Referenced by createBlockAndDeepCopy()\&.
.SS "BlockStreamFix::BlockStreamFix (unsignedblock_size, unsignedtuple_size, void *start_addr, unsignedntuples)"

.SS "BlockStreamFix::~BlockStreamFix ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void* BlockStreamFix::allocateTuple (unsignedbytes)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBBlockStreamBase\fP\&.
.SS "void BlockStreamFix::constructFromBlock (const \fBBlock\fP &block)\fC [virtual]\fP"
a remedy for the data loading bug\&.\&.\&.
.PP
Implements \fBBlockStreamBase\fP\&.
.PP
References Block::BlockSize, free_, Block::getBlock(), Block::getsize(), Block::start, and tuple_size_\&.
.SS "void BlockStreamFix::copyBlock (void *addr, unsignedlength)\fC [virtual]\fP"

.PP
Implements \fBBlockStreamBase\fP\&.
.PP
References Block::BlockSize, free_, and Block::start\&.
.SS "\fBBlockStreamBase\fP * BlockStreamFix::createBlockAndDeepCopy ()\fC [virtual]\fP"

.PP
Implements \fBBlockStreamBase\fP\&.
.PP
References Block::BlockSize, BlockStreamFix(), BlockStreamBase::deepCopy(), Block::getBlock(), getTuplesInBlock(), Block::isIsReference(), and tuple_size_\&.
.SS "void BlockStreamFix::deepCopy (const \fBBlock\fP *block)\fC [virtual]\fP"
deep copy from block, including block content and member variables that maintain the block status\&. the user should guarantee that rest block and desc block are of equal derived class type(e\&.g\&., both are \fBBlockStreamFix\fP), otherwise the copy may be incomplete\&. 
.PP
Implements \fBBlockStreamBase\fP\&.
.PP
References Block::BlockSize, free_, Block::getBlock(), Block::getsize(), Block::start, and tuple_size_\&.
.SS "bool BlockStreamFix::deserialize (\fBBlock\fP *block)\fC [virtual]\fP"

.PP
Implements \fBBlockStreamBase\fP\&.
.PP
References Block::BlockSize, free_, Block::getBlock(), Block::getsize(), Block::start, and tuple_size_\&.
.SS "bool BlockStreamFix::Empty () const\fC [virtual]\fP"

.PP
Implements \fBBlockStreamBase\fP\&.
.PP
References free_, and Block::start\&.
.SS "bool BlockStreamFix::Full () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBBlockStreamBase\fP\&.
.SS "unsigned BlockStreamFix::getBlockCapacityInTuples () const\fC [virtual]\fP"

.PP
Implements \fBBlockStreamBase\fP\&.
.PP
References Block::BlockSize, and tuple_size_\&.
.SS "void * BlockStreamFix::getBlockDataAddress ()\fC [virtual]\fP"

.PP
Implements \fBBlockStreamBase\fP\&.
.PP
References Block::start\&.
.SS "unsigned BlockStreamFix::getSerializedBlockSize () const\fC [virtual]\fP"

.PP
Implements \fBBlockStreamBase\fP\&.
.PP
References Block::BlockSize\&.
.SS "void* BlockStreamFix::getTuple (unsignedoffset) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBBlockStreamBase\fP\&.
.SS "unsigned BlockStreamFix::getTuplesInBlock () const\fC [virtual]\fP"

.PP
Implements \fBBlockStreamBase\fP\&.
.PP
References free_, Block::start, and tuple_size_\&.
.PP
Referenced by createBlockAndDeepCopy()\&.
.SS "bool BlockStreamFix::insert (void *dest, void *src, unsignedbytes)\fC [virtual]\fP"

.PP
Implements \fBBlockStreamBase\fP\&.
.SS "bool BlockStreamFix::serialize (\fBBlock\fP &block) const\fC [virtual]\fP"

.PP
Implements \fBBlockStreamBase\fP\&.
.PP
References Block::BlockSize, free_, Block::getBlock(), Block::getsize(), Block::start, BlockStreamFix::tail_info::tuple_count, and tuple_size_\&.
.SS "void BlockStreamFix::setEmpty ()\fC [virtual]\fP"

.PP
Implements \fBBlockStreamBase\fP\&.
.PP
References free_, and Block::start\&.
.SS "void BlockStreamFix::setTuplesInBlock (unsignedn)\fC [inline]\fP"

.SS "bool BlockStreamFix::switchBlock (\fBBlockStreamBase\fP &block)\fC [virtual]\fP"

.PP
Implements \fBBlockStreamBase\fP\&.
.PP
References Block::BlockSize, free_, and Block::start\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBBlockStreamBase\fP\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "char* BlockStreamFix::free_"

.PP
Referenced by BlockStreamFix(), constructFromBlock(), copyBlock(), deepCopy(), deserialize(), Empty(), getTuplesInBlock(), serialize(), setEmpty(), and switchBlock()\&.
.SS "unsigned BlockStreamFix::tuple_size_"

.PP
Referenced by constructFromBlock(), createBlockAndDeepCopy(), deepCopy(), deserialize(), getBlockCapacityInTuples(), getTuplesInBlock(), and serialize()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
