.TH "BlockStreamFix" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockStreamFix \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBlockStreamBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlockStreamFix\fP (unsigned block_size, unsigned tuple_size)"
.br
.ti -1c
.RI "\fBBlockStreamFix\fP (unsigned block_size, unsigned tuple_size, void *start_addr, unsigned ntuples)"
.br
.ti -1c
.RI "void * \fBallocateTuple\fP (unsigned bytes)"
.br
.ti -1c
.RI "void \fBsetTuplesInBlock\fP (unsigned n)"
.br
.ti -1c
.RI "void \fBsetEmpty\fP ()"
.br
.ti -1c
.RI "void * \fBgetTuple\fP (unsigned offset) const "
.br
.ti -1c
.RI "bool \fBEmpty\fP () const "
.br
.ti -1c
.RI "bool \fBFull\fP () const "
.br
.ti -1c
.RI "void * \fBgetBlockDataAddress\fP ()"
.br
.ti -1c
.RI "bool \fBswitchBlock\fP (\fBBlockStreamBase\fP &block)"
.br
.ti -1c
.RI "void \fBcopyBlock\fP (void *addr, unsigned length)"
.br
.ti -1c
.RI "bool \fBinsert\fP (void *dest, void *src, unsigned bytes)"
.br
.ti -1c
.RI "void \fBdeepCopy\fP (const \fBBlock\fP *block)"
.br
.ti -1c
.RI "bool \fBserialize\fP (\fBBlock\fP &block) const "
.br
.ti -1c
.RI "bool \fBdeserialize\fP (\fBBlock\fP *block)"
.br
.ti -1c
.RI "unsigned \fBgetSerializedBlockSize\fP () const "
.br
.ti -1c
.RI "unsigned \fBgetBlockCapacityInTuples\fP () const "
.br
.ti -1c
.RI "unsigned \fBgetTuplesInBlock\fP () const "
.br
.ti -1c
.RI "void \fBconstructFromBlock\fP (const \fBBlock\fP &block)"
.br
.ti -1c
.RI "\fBBlockStreamBase\fP * \fBcreateBlockAndDeepCopy\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBtuple_size_\fP"
.br
.ti -1c
.RI "char * \fBfree_\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBBlockStreamBase\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "void BlockStreamFix::constructFromBlock (const \fBBlock\fP &block)\fC [virtual]\fP"
a remedy for the data loading bug\&.\&.\&.
.PP
Implements \fBBlockStreamBase\fP\&.
.SS "void BlockStreamFix::deepCopy (const \fBBlock\fP *block)\fC [virtual]\fP"
deep copy from block, including block content and member variables that maintain the block status\&. the user should guarantee that rest block and desc block are of equal derived class type(e\&.g\&., both are \fBBlockStreamFix\fP), otherwise the copy may be incomplete\&. 
.PP
Implements \fBBlockStreamBase\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
