.TH "BlockStreamCombinedIterator::remaining_block" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockStreamCombinedIterator::remaining_block \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBremaining_block\fP (std::vector< \fBBlockStreamBase\fP * > buffer, std::vector< \fBBlockStreamBase::BlockStreamTraverseIterator\fP * > bsti_list)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBBlockStreamBase\fP * > \fBbuffer_\fP"
.br
.ti -1c
.RI "std::vector
.br
< \fBBlockStreamBase::BlockStreamTraverseIterator\fP * > \fBbsti_list_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
