.TH "BlockStreamExpander::State" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockStreamExpander::State \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBState\fP (\fBSchema\fP *schema, \fBBlockStreamIteratorBase\fP *child, unsigned thread_count, unsigned block_size, unsigned block_count_in_buffer=10)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSchema\fP * \fBschema_\fP"
.br
.ti -1c
.RI "\fBBlockStreamIteratorBase\fP * \fBchild_\fP"
.br
.ti -1c
.RI "unsigned \fBinit_thread_count_\fP"
.br
.ti -1c
.RI "unsigned \fBblock_size_\fP"
.br
.ti -1c
.RI "unsigned \fBblock_count_in_buffer_\fP"
.br
.ti -1c
.RI "PartitionOffset \fBpartition_offset\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBBlockStreamExpander\fP"
.br
.ti -1c
.RI "class \fBboost::serialization::access\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
