.TH "BlockStreamPerformanceTest::State" 3 "Mon Oct 5 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockStreamPerformanceTest::State \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBState\fP (\fBSchema\fP *schema, \fBBlockStreamIteratorBase\fP *child1, \fBBlockStreamIteratorBase\fP *child2, unsigned block_size, unsigned report_cycles)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSchema\fP * \fBschema_\fP"
.br
.ti -1c
.RI "\fBBlockStreamIteratorBase\fP * \fBchild1_\fP"
.br
.ti -1c
.RI "\fBBlockStreamIteratorBase\fP * \fBchild2_\fP"
.br
.ti -1c
.RI "unsigned \fBblock_size_\fP"
.br
.ti -1c
.RI "unsigned \fBreport_cycles_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
