.TH "BlockManager::BlockInfo" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockManager::BlockInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BlockManager\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlockInfo\fP (\fBstorageLevel\fP level)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstorageLevel\fP \fBlevel_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BlockManager::BlockInfo::BlockInfo (\fBstorageLevel\fPlevel)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBstorageLevel\fP BlockManager::BlockInfo::level_"


.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
