.TH "BlockContainer" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockContainer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BlockContainer\&.h>\fP
.PP
Inherits \fBBlock\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlockContainer\fP (unsigned size)"
.br
.ti -1c
.RI "virtual \fB~BlockContainer\fP ()"
.br
.ti -1c
.RI "unsigned \fBGetMaxSize\fP () const "
.br
.ti -1c
.RI "unsigned \fBGetCurSize\fP () const "
.br
.ti -1c
.RI "unsigned \fBGetRestSize\fP () const "
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "void \fBIncreaseActualSize\fP (unsigned size)"
.br
.ti -1c
.RI "void \fBcopy\fP (\fBBlockContainer\fP &block)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBactual_size_\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BlockContainer::BlockContainer (unsignedsize)"

.SS "BlockContainer::~BlockContainer ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void BlockContainer::copy (\fBBlockContainer\fP &block)"
Copy the block content and the acutal_size_ 
.PP
References actual_size_, Block::getBlock(), GetCurSize(), and Block::getsize()\&.
.SS "unsigned BlockContainer::GetCurSize () const"

.PP
References actual_size_\&.
.PP
Referenced by copy(), claims::physical_operator::ExchangeMerger::Receiver(), and claims::physical_operator::ExchangeSenderPipeline::Sender()\&.
.SS "unsigned BlockContainer::GetMaxSize () const"

.PP
References Block::getsize()\&.
.SS "unsigned BlockContainer::GetRestSize () const"

.PP
References actual_size_, and Block::getsize()\&.
.PP
Referenced by claims::physical_operator::ExchangeMerger::Receiver(), and claims::physical_operator::ExchangeSenderPipeline::Sender()\&.
.SS "void BlockContainer::IncreaseActualSize (unsignedsize)"

.PP
References actual_size_, and Block::getsize()\&.
.PP
Referenced by claims::physical_operator::ExchangeMerger::Receiver(), and claims::physical_operator::ExchangeSenderPipeline::Sender()\&.
.SS "void BlockContainer::reset ()"

.PP
References actual_size_\&.
.PP
Referenced by claims::physical_operator::ExchangeMerger::Receiver(), and claims::physical_operator::ExchangeSenderPipeline::Sender()\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned BlockContainer::actual_size_\fC [private]\fP"

.PP
Referenced by copy(), GetCurSize(), GetRestSize(), IncreaseActualSize(), and reset()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
