.TH "BlockManagerMaster::BlockInfo" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockManagerMaster::BlockInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BlockManagerMaster\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBblockId_\fP"
.br
.ti -1c
.RI "\fBstorageLevel\fP \fBlevel_\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "string BlockManagerMaster::BlockInfo::blockId_"

.SS "\fBstorageLevel\fP BlockManagerMaster::BlockInfo::level_"


.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
