.TH "BlockStreamBase::BlockStreamTraverseIterator" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockStreamBase::BlockStreamTraverseIterator \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlockStreamTraverseIterator\fP (\fBBlockStreamBase\fP *block_stream_base)"
.br
.ti -1c
.RI "void * \fBnextTuple\fP ()"
.br
.ti -1c
.RI "void * \fBcurrentTuple\fP () const "
.br
.ti -1c
.RI "void * \fBgetTuple\fP (unsigned tuple_off) const "
.br
.ti -1c
.RI "void \fBincrease_cur_\fP ()"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "unsigned \fBget_cur\fP () const "
.br
.ti -1c
.RI "void \fBset_cur\fP (unsigned c)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
