.TH "BlockStreamSortIterator::State" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockStreamSortIterator::State \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBState\fP (\fBSchema\fP *input, vector< unsigned > orderbyKey, \fBBlockStreamIteratorBase\fP *child, const unsigned block_size, vector< int > direction, const PartitionOffset partitoin_offset=0)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSchema\fP * \fBinput_\fP"
.br
.ti -1c
.RI "vector< unsigned > \fBorderbyKey_\fP"
.br
.ti -1c
.RI "\fBBlockStreamIteratorBase\fP * \fBchild_\fP"
.br
.ti -1c
.RI "unsigned \fBblock_size_\fP"
.br
.ti -1c
.RI "PartitionOffset \fBpartition_offset_\fP"
.br
.ti -1c
.RI "vector< int > \fBdirection_\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBBlockStreamSortIterator\fP"
.br
.ti -1c
.RI "class \fBboost::serialization::access\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
