.TH "BlockContainer" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockContainer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBlock\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlockContainer\fP (unsigned size)"
.br
.ti -1c
.RI "unsigned \fBGetMaxSize\fP () const "
.br
.ti -1c
.RI "unsigned \fBGetCurSize\fP () const "
.br
.ti -1c
.RI "unsigned \fBGetRestSize\fP () const "
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "void \fBIncreaseActualSize\fP (unsigned size)"
.br
.ti -1c
.RI "void \fBcopy\fP (\fBBlockContainer\fP &block)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "void BlockContainer::copy (\fBBlockContainer\fP &block)"
Copy the block content and the acutal_size_ 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
