.TH "BlockStreamNestLoopJoinIterator::join_thread_context" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockStreamNestLoopJoinIterator::join_thread_context \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBThreadContext\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBlockStreamBase\fP * \fBblock_for_asking_\fP"
.br
.ti -1c
.RI "\fBBlockStreamBase::BlockStreamTraverseIterator\fP * \fBblock_stream_iterator_\fP"
.br
.ti -1c
.RI "\fBDynamicBlockBuffer::Iterator\fP \fBbuffer_iterator_\fP"
.br
.ti -1c
.RI "\fBBlockStreamBase::BlockStreamTraverseIterator\fP * \fBbuffer_stream_iterator_\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
