.TH "BlockManagerId" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockManagerId \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BlockManagerId\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlockManagerId\fP ()"
.br
.ti -1c
.RI "\fBBlockManagerId\fP (string bmi)"
.br
.ti -1c
.RI "virtual \fB~BlockManagerId\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBblockManagerId\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BlockManagerId::BlockManagerId ()"

.PP
References blockManagerId, and getIpFromLocal()\&.
.SS "BlockManagerId::BlockManagerId (stringbmi)"

.PP
References blockManagerId\&.
.SS "BlockManagerId::~BlockManagerId ()\fC [virtual]\fP"

.SH "Member Data Documentation"
.PP 
.SS "string BlockManagerId::blockManagerId"

.PP
Referenced by BlockManagerId(), and BlanceMatcher::matcher()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
