.TH "BlockStreamPerformanceTest" 3 "Mon Oct 5 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockStreamPerformanceTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBlockStreamIteratorBase\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBState\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlockStreamPerformanceTest\fP (\fBState\fP state_)"
.br
.ti -1c
.RI "bool \fBOpen\fP (const PartitionOffset &partition_offset=0)"
.br
.ti -1c
.RI "bool \fBNext\fP (\fBBlockStreamBase\fP *block)"
.br
.ti -1c
.RI "bool \fBClose\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
