.TH "BlockStreamFilter::State" 3 "Mon Oct 5 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockStreamFilter::State \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBState\fP (\fBSchema\fP *s, \fBBlockStreamIteratorBase\fP *child, std::vector< \fBAttributeComparator\fP > comparator_list, unsigned block_size)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSchema\fP * \fBschema_\fP"
.br
.ti -1c
.RI "std::vector< \fBAttributeComparator\fP > \fBcomparator_list_\fP"
.br
.ti -1c
.RI "\fBBlockStreamIteratorBase\fP * \fBchild_\fP"
.br
.ti -1c
.RI "unsigned \fBblock_size_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
