.TH "BlockStreamRandomMemAccess::State" 3 "Mon Oct 5 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockStreamRandomMemAccess::State \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBState\fP (std::string file_name, \fBBlockStreamIteratorBase\fP *child, \fBSchema\fP *schema_in_, \fBSchema\fP *schema_out_, unsigned block_size)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBBlockStreamRandomMemAccess\fP"
.br
.ti -1c
.RI "class \fBboost::serialization::access\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
