.TH "BoostHashFunctin" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BoostHashFunctin \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hash\&.h>\fP
.PP
Inherits \fBPartitionFunction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBoostHashFunctin\fP ()"
.br
.ti -1c
.RI "\fBBoostHashFunctin\fP (const int &range)"
.br
.ti -1c
.RI "\fB~BoostHashFunctin\fP ()"
.br
.ti -1c
.RI "unsigned int \fBget_partition_value\fP (const int &value) const "
.br
.ti -1c
.RI "unsigned int \fBget_partition_value\fP (const unsigned long &value) const "
.br
.ti -1c
.RI "unsigned int \fBget_partition_value\fP (const double &value) const "
.br
.ti -1c
.RI "unsigned int \fBget_partition_value\fP (const long &value) const "
.br
.ti -1c
.RI "\fBPartitionStyle\fP \fBgetPartitionFashion\fP () const "
.br
.ti -1c
.RI "unsigned \fBgetNumberOfPartitions\fP () const "
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "template<class Archive > void \fBserialize\fP (Archive &ar, const unsigned int version)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned long \fBrange_\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBboost::serialization::access\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BoostHashFunctin::BoostHashFunctin ()\fC [inline]\fP"

.SS "BoostHashFunctin::BoostHashFunctin (const int &range)\fC [inline]\fP"

.SS "BoostHashFunctin::~BoostHashFunctin ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "unsigned int BoostHashFunctin::get_partition_value (const int &value) const\fC [inline]\fP, \fC [virtual]\fP"
Returns the bucket number $n\in[0,k)$ for this \fIvalue\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvalue\fP Value to hash\&. Must be within bounds\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Bucket number\&. 
.RE
.PP

.PP
Implements \fBPartitionFunction\fP\&.
.PP
References hash_value(), and range_\&.
.SS "unsigned int BoostHashFunctin::get_partition_value (const unsigned long &value) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBPartitionFunction\fP\&.
.PP
References hash_value(), and range_\&.
.SS "unsigned int BoostHashFunctin::get_partition_value (const double &value) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBPartitionFunction\fP\&.
.PP
References hash_value(), and range_\&.
.SS "unsigned int BoostHashFunctin::get_partition_value (const long &value) const\fC [inline]\fP"

.PP
References hash_value(), and range_\&.
.SS "unsigned BoostHashFunctin::getNumberOfPartitions () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBPartitionFunction\fP\&.
.PP
References range_\&.
.SS "\fBPartitionStyle\fP BoostHashFunctin::getPartitionFashion () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBPartitionFunction\fP\&.
.PP
References PartitionFunction::hash_f\&.
.SS "template<class Archive > void BoostHashFunctin::serialize (Archive &ar, const unsigned intversion)\fC [inline]\fP, \fC [private]\fP"

.PP
References range_\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class boost::serialization::access\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "unsigned long BoostHashFunctin::range_\fC [private]\fP"

.PP
Referenced by get_partition_value(), getNumberOfPartitions(), and serialize()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
