.TH "bottomLayerCollecting::remaining_block" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bottomLayerCollecting::remaining_block \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CSBIndexBuilding\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBremaining_block\fP ()"
.br
.ti -1c
.RI "\fBremaining_block\fP (\fBBlockStreamBase\fP *\fBblock\fP, \fBBlockStreamBase::BlockStreamTraverseIterator\fP *\fBiterator\fP, unsigned short \fBchunk_offset\fP, unsigned short \fBblock_offset\fP, unsigned short \fBtuple_offset\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBlockStreamBase::BlockStreamTraverseIterator\fP * \fBiterator\fP"
.br
.ti -1c
.RI "\fBBlockStreamBase\fP * \fBblock\fP"
.br
.ti -1c
.RI "\fBChunkOffset\fP \fBchunk_offset\fP"
.br
.ti -1c
.RI "unsigned short \fBblock_offset\fP"
.br
.ti -1c
.RI "unsigned short \fBtuple_offset\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "bottomLayerCollecting::remaining_block::remaining_block ()\fC [inline]\fP"

.SS "bottomLayerCollecting::remaining_block::remaining_block (\fBBlockStreamBase\fP *block, \fBBlockStreamBase::BlockStreamTraverseIterator\fP *iterator, unsigned shortchunk_offset, unsigned shortblock_offset, unsigned shorttuple_offset)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBBlockStreamBase\fP* bottomLayerCollecting::remaining_block::block"

.PP
Referenced by bottomLayerCollecting::Next()\&.
.SS "unsigned short bottomLayerCollecting::remaining_block::block_offset"

.PP
Referenced by bottomLayerCollecting::askForNextBlock(), and bottomLayerCollecting::Next()\&.
.SS "\fBChunkOffset\fP bottomLayerCollecting::remaining_block::chunk_offset"

.PP
Referenced by bottomLayerCollecting::askForNextBlock(), and bottomLayerCollecting::Next()\&.
.SS "\fBBlockStreamBase::BlockStreamTraverseIterator\fP* bottomLayerCollecting::remaining_block::iterator"

.PP
Referenced by bottomLayerCollecting::Next()\&.
.SS "unsigned short bottomLayerCollecting::remaining_block::tuple_offset"

.PP
Referenced by bottomLayerCollecting::askForNextBlock(), and bottomLayerCollecting::Next()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
