.TH "bottomLayerSorting::State" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bottomLayerSorting::State \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CSBIndexBuilding\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBState\fP ()"
.br
.ti -1c
.RI "\fBState\fP (\fBSchema\fP *schema, \fBPhysicalOperatorBase\fP *child, const unsigned \fBblock_size\fP, \fBProjectionID\fP projection_id, unsigned key_indexing, std::string index_name)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSchema\fP * \fBschema_\fP"
.br
.ti -1c
.RI "\fBPhysicalOperatorBase\fP * \fBchild_\fP"
.br
.ti -1c
.RI "unsigned \fBblock_size_\fP"
.br
.ti -1c
.RI "\fBProjectionID\fP \fBprojection_id_\fP"
.br
.ti -1c
.RI "unsigned \fBkey_indexing_\fP"
.br
.ti -1c
.RI "std::string \fBindex_name_\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "template<class Archive > void \fBserialize\fP (Archive &ar, const unsigned version)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBbottomLayerSorting\fP"
.br
.ti -1c
.RI "class \fBboost::serialization::access\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "bottomLayerSorting::State::State ()\fC [inline]\fP"

.SS "bottomLayerSorting::State::State (\fBSchema\fP *schema, \fBPhysicalOperatorBase\fP *child, const unsignedblock_size, \fBProjectionID\fPprojection_id, unsignedkey_indexing, std::stringindex_name)"

.SH "Member Function Documentation"
.PP 
.SS "template<class Archive > void bottomLayerSorting::State::serialize (Archive &ar, const unsignedversion)\fC [inline]\fP, \fC [private]\fP"

.PP
References block_size_, child_, index_name_, key_indexing_, projection_id_, and schema_\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class boost::serialization::access\fC [friend]\fP"

.SS "friend class \fBbottomLayerSorting\fP\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "unsigned bottomLayerSorting::State::block_size_"

.PP
Referenced by LogicalCSBIndexBuilding::GetPhysicalPlan(), bottomLayerSorting::Open(), and serialize()\&.
.SS "\fBPhysicalOperatorBase\fP* bottomLayerSorting::State::child_"

.PP
Referenced by bottomLayerSorting::Close(), LogicalCSBIndexBuilding::GetPhysicalPlan(), bottomLayerSorting::Open(), and serialize()\&.
.SS "std::string bottomLayerSorting::State::index_name_"

.PP
Referenced by LogicalCSBIndexBuilding::GetPhysicalPlan(), bottomLayerSorting::Next(), and serialize()\&.
.SS "unsigned bottomLayerSorting::State::key_indexing_"

.PP
Referenced by LogicalCSBIndexBuilding::GetPhysicalPlan(), bottomLayerSorting::Next(), and serialize()\&.
.SS "\fBProjectionID\fP bottomLayerSorting::State::projection_id_"

.PP
Referenced by LogicalCSBIndexBuilding::GetPhysicalPlan(), bottomLayerSorting::Open(), and serialize()\&.
.SS "\fBSchema\fP* bottomLayerSorting::State::schema_"

.PP
Referenced by bottomLayerSorting::computeVectorSchema(), LogicalCSBIndexBuilding::GetPhysicalPlan(), bottomLayerSorting::Open(), and serialize()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
