.TH "bottomLayerSorting::State" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bottomLayerSorting::State \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBState\fP (\fBSchema\fP *schema, \fBBlockStreamIteratorBase\fP *child, const unsigned block_size, \fBProjectionID\fP projection_id, unsigned key_indexing, std::string index_name)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSchema\fP * \fBschema_\fP"
.br
.ti -1c
.RI "\fBBlockStreamIteratorBase\fP * \fBchild_\fP"
.br
.ti -1c
.RI "unsigned \fBblock_size_\fP"
.br
.ti -1c
.RI "\fBProjectionID\fP \fBprojection_id_\fP"
.br
.ti -1c
.RI "unsigned \fBkey_indexing_\fP"
.br
.ti -1c
.RI "std::string \fBindex_name_\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBbottomLayerSorting\fP"
.br
.ti -1c
.RI "class \fBboost::serialization::access\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
