.TH "bottomLayerSorting::compare_node" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bottomLayerSorting::compare_node \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CSBIndexBuilding\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSchema\fP * \fBvector_schema_\fP"
.br
.ti -1c
.RI "void * \fBtuple_\fP"
.br
.ti -1c
.RI "\fBOperate\fP * \fBop_\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBOperate\fP* bottomLayerSorting::compare_node::op_"

.PP
Referenced by bottomLayerSorting::compare(), and bottomLayerSorting::Open()\&.
.SS "void* bottomLayerSorting::compare_node::tuple_"

.PP
Referenced by bottomLayerSorting::compare(), and bottomLayerSorting::Open()\&.
.SS "\fBSchema\fP* bottomLayerSorting::compare_node::vector_schema_"

.PP
Referenced by bottomLayerSorting::compare(), and bottomLayerSorting::Open()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
