.TH "bottomLayerSorting::compare_node" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bottomLayerSorting::compare_node \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSchema\fP * \fBvector_schema_\fP"
.br
.ti -1c
.RI "void * \fBtuple_\fP"
.br
.ti -1c
.RI "\fBOperate\fP * \fBop_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
