.TH "CCSBInternalNodeGroup< T >" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCSBInternalNodeGroup< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CSBPlusTree\&.h>\fP
.PP
Inherits \fBCCSBNodeGroup< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCCSBInternalNodeGroup\fP ()"
.br
.ti -1c
.RI "\fBCCSBInternalNodeGroup\fP (unsigned n)"
.br
.ti -1c
.RI "\fB~CCSBInternalNodeGroup\fP ()"
.br
.ti -1c
.RI "bool \fBsetUsedNodes\fP (unsigned n)"
.br
.ti -1c
.RI "\fBCCSBNode\fP< T > * \fBgetNode\fP (unsigned i)"
.br
.ti -1c
.RI "void \fBsetNode\fP (unsigned i, \fBCCSBNode\fP< T > *node)"
.br
.ti -1c
.RI "bool \fBInsert\fP (unsigned node_off, T key)"
.br
.ti -1c
.RI "void \fBDeleteChildren\fP ()"
.br
.ti -1c
.RI "bool \fBserialize\fP (FILE *filename)"
.br
.ti -1c
.RI "bool \fBdeserialize\fP (FILE *filename)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCCSBNode\fP< T > ** \fBinternal_nodes\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T> \fBCCSBInternalNodeGroup\fP< T >::\fBCCSBInternalNodeGroup\fP ()\fC [inline]\fP"

.SS "template<typename T > \fBCCSBInternalNodeGroup\fP< T >::\fBCCSBInternalNodeGroup\fP (unsignedn)"

.SS "template<typename T > \fBCCSBInternalNodeGroup\fP< T >::~\fBCCSBInternalNodeGroup\fP ()"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T > void \fBCCSBInternalNodeGroup\fP< T >::DeleteChildren ()\fC [virtual]\fP"

.PP
Reimplemented from \fBCCSBNodeGroup< T >\fP\&.
.SS "template<typename T > bool \fBCCSBInternalNodeGroup\fP< T >::deserialize (FILE *filename)\fC [virtual]\fP"

.PP
Reimplemented from \fBCCSBNodeGroup< T >\fP\&.
.PP
References CCSBInternalNode< T >::deserialize()\&.
.PP
Referenced by CSBPlusTree< T >::deserialize()\&.
.SS "template<typename T> \fBCCSBNode\fP<T>* \fBCCSBInternalNodeGroup\fP< T >::getNode (unsignedi)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBCCSBNodeGroup< T >\fP\&.
.PP
References NULL\&.
.PP
Referenced by CSBPlusTree< T >::BulkLoad(), and CSBPlusTree< T >::deserialize()\&.
.SS "template<typename T > bool \fBCCSBInternalNodeGroup\fP< T >::Insert (unsignednode_off, Tkey)\fC [virtual]\fP"

.PP
Reimplemented from \fBCCSBNodeGroup< T >\fP\&.
.SS "template<typename T > bool \fBCCSBInternalNodeGroup\fP< T >::serialize (FILE *filename)\fC [virtual]\fP"

.PP
Reimplemented from \fBCCSBNodeGroup< T >\fP\&.
.PP
References boost::serialization::serialize()\&.
.SS "template<typename T> void \fBCCSBInternalNodeGroup\fP< T >::setNode (unsignedi, \fBCCSBNode\fP< T > *node)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBCCSBNodeGroup< T >\fP\&.
.PP
References CCSBNode< T >::getElement(), CCSBNode< T >::getFather(), CCSBNode< T >::getPointer(), and CCSBNode< T >::getUsedKeys()\&.
.SS "template<typename T> bool \fBCCSBInternalNodeGroup\fP< T >::setUsedNodes (unsignedn)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBCCSBNodeGroup< T >\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename T> \fBCCSBNode\fP<T>** \fBCCSBInternalNodeGroup\fP< T >::internal_nodes"

.PP
Referenced by CSBPlusTree< T >::BulkLoad()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
