.TH "ChunkStorage" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChunkStorage \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ChunkStorage\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChunkStorage\fP (const \fBChunkID\fP &chunk_id, const unsigned &\fBblock_size\fP, const \fBStorageLevel\fP &desirable_level)"
.br
.ti -1c
.RI "virtual \fB~ChunkStorage\fP ()"
.br
.ti -1c
.RI "\fBChunkReaderIterator\fP * \fBcreateChunkReaderIterator\fP ()"
.br
.ti -1c
.RI "std::string \fBprintCurrentStorageLevel\fP () const "
.br
.ti -1c
.RI "\fBChunkID\fP \fBgetChunkID\fP ()"
.br
.ti -1c
.RI "void \fBsetCurrentStorageLevel\fP (const \fBStorageLevel\fP &current_level)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBblock_size_\fP"
.br
.ti -1c
.RI "unsigned \fBchunk_size_\fP"
.br
.ti -1c
.RI "\fBStorageLevel\fP \fBdesirable_storage_level_\fP"
.br
.ti -1c
.RI "\fBStorageLevel\fP \fBcurrent_storage_level_\fP"
.br
.ti -1c
.RI "\fBChunkID\fP \fBchunk_id_\fP"
.br
.ti -1c
.RI "\fBLock\fP \fBlock_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ChunkStorage::ChunkStorage (const \fBChunkID\fP &chunk_id, const unsigned &block_size, const \fBStorageLevel\fP &desirable_level)"

.SS "ChunkStorage::~ChunkStorage ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBChunkReaderIterator\fP * ChunkStorage::createChunkReaderIterator ()"

.PP
References Lock::acquire(), block_size_, chunk_id_, CHUNK_SIZE, chunk_size_, current_storage_level_, desirable_storage_level_, DISK, BlockManager::getInstance(), BlockManager::getMemoryChunkStore(), HDFS, HdfsBlock::hook, HdfsBlock::length, BlockManager::loadFromDisk(), BlockManager::loadFromHdfs(), Config::local_disk_mode, lock_, MEMORY, Lock::release(), MemoryChunkStore::returnChunk(), and MemoryChunkStore::updateChunkInfo()\&.
.SS "\fBChunkID\fP ChunkStorage::getChunkID ()\fC [inline]\fP"

.PP
References chunk_id_\&.
.SS "std::string ChunkStorage::printCurrentStorageLevel () const"

.SS "void ChunkStorage::setCurrentStorageLevel (const \fBStorageLevel\fP &current_level)\fC [inline]\fP"

.PP
References current_storage_level_\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned ChunkStorage::block_size_\fC [private]\fP"

.PP
Referenced by createChunkReaderIterator()\&.
.SS "\fBChunkID\fP ChunkStorage::chunk_id_\fC [private]\fP"

.PP
Referenced by createChunkReaderIterator(), and getChunkID()\&.
.SS "unsigned ChunkStorage::chunk_size_\fC [private]\fP"

.PP
Referenced by createChunkReaderIterator()\&.
.SS "\fBStorageLevel\fP ChunkStorage::current_storage_level_\fC [private]\fP"

.PP
Referenced by createChunkReaderIterator(), and setCurrentStorageLevel()\&.
.SS "\fBStorageLevel\fP ChunkStorage::desirable_storage_level_\fC [private]\fP"

.PP
Referenced by createChunkReaderIterator()\&.
.SS "\fBLock\fP ChunkStorage::lock_\fC [private]\fP"

.PP
Referenced by createChunkReaderIterator()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
