.TH "ChunkReaderIterator::InHDFSBlockAccessor" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChunkReaderIterator::InHDFSBlockAccessor \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBChunkReaderIterator::block_accessor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBgetBlock\fP (\fBBlockStreamBase\fP *&block) const "
.br
.ti -1c
.RI "unsigned \fBgetBlockCur\fP () const "
.br
.ti -1c
.RI "void \fBsetBlockCur\fP (unsigned blockCur)"
.br
.ti -1c
.RI "const \fBChunkID\fP & \fBgetChunkId\fP () const "
.br
.ti -1c
.RI "void \fBsetChunkId\fP (const \fBChunkID\fP &chunkId)"
.br
.ti -1c
.RI "unsigned \fBgetChunkSize\fP () const "
.br
.ti -1c
.RI "void \fBsetChunkSize\fP (unsigned chunkSize)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
