.TH "ChunkReaderIterator::InMemeryBlockAccessor" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChunkReaderIterator::InMemeryBlockAccessor \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ChunkStorage\&.h>\fP
.PP
Inherits \fBChunkReaderIterator::block_accessor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInMemeryBlockAccessor\fP ()"
.br
.ti -1c
.RI "\fB~InMemeryBlockAccessor\fP ()"
.br
.ti -1c
.RI "void \fBgetBlock\fP (\fBBlockStreamBase\fP *&block) const "
.br
.ti -1c
.RI "void * \fBgetTargetBlockStartAddress\fP () const "
.br
.ti -1c
.RI "void \fBsetTargetBlockStartAddress\fP (void *targetBlockStartAddress)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "void * \fBtarget_block_start_address\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ChunkReaderIterator::InMemeryBlockAccessor::InMemeryBlockAccessor ()\fC [inline]\fP"

.PP
References NULL, and target_block_start_address\&.
.SS "ChunkReaderIterator::InMemeryBlockAccessor::~InMemeryBlockAccessor ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void ChunkReaderIterator::InMemeryBlockAccessor::getBlock (\fBBlockStreamBase\fP *&block) const\fC [virtual]\fP"

.PP
Reimplemented from \fBChunkReaderIterator::block_accessor\fP\&.
.PP
References ChunkReaderIterator::block_accessor::block_size, BlockStreamBase::constructFromBlock(), Block::getBlock(), BlockStreamBase::getSerializedBlockSize(), Block::setBlock(), Block::setIsReference(), and target_block_start_address\&.
.SS "void* ChunkReaderIterator::InMemeryBlockAccessor::getTargetBlockStartAddress () const\fC [inline]\fP"

.PP
References target_block_start_address\&.
.SS "void ChunkReaderIterator::InMemeryBlockAccessor::setTargetBlockStartAddress (void *targetBlockStartAddress)\fC [inline]\fP"

.PP
References target_block_start_address\&.
.PP
Referenced by InMemoryChunkReaderItetaor::getNextBlockAccessor()\&.
.SH "Member Data Documentation"
.PP 
.SS "void* ChunkReaderIterator::InMemeryBlockAccessor::target_block_start_address\fC [private]\fP"

.PP
Referenced by getBlock(), getTargetBlockStartAddress(), InMemeryBlockAccessor(), and setTargetBlockStartAddress()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
