.TH "ChunkReaderIterator::block_accessor" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChunkReaderIterator::block_accessor \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ChunkStorage\&.h>\fP
.PP
Inherited by \fBChunkReaderIterator::InDiskBlockAccessor\fP, \fBChunkReaderIterator::InHDFSBlockAccessor\fP, and \fBChunkReaderIterator::InMemeryBlockAccessor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBblock_accessor\fP ()"
.br
.ti -1c
.RI "\fB~block_accessor\fP ()"
.br
.ti -1c
.RI "virtual void \fBgetBlock\fP (\fBBlockStreamBase\fP *&block) const "
.br
.ti -1c
.RI "unsigned \fBgetBlockSize\fP () const "
.br
.ti -1c
.RI "void \fBsetBlockSize\fP (unsigned blockSize)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBblock_size\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This structure maintains all the information needed to access a block in in-memory chunk, in-disk chunk, or in-hdfs chunk\&.
.PP
The underlying reason for using this structure is to\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ChunkReaderIterator::block_accessor::block_accessor ()\fC [inline]\fP"

.SS "ChunkReaderIterator::block_accessor::~block_accessor ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void ChunkReaderIterator::block_accessor::getBlock (\fBBlockStreamBase\fP *&block) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBChunkReaderIterator::InHDFSBlockAccessor\fP, \fBChunkReaderIterator::InDiskBlockAccessor\fP, and \fBChunkReaderIterator::InMemeryBlockAccessor\fP\&.
.PP
Referenced by claims::physical_operator::PhysicalProjectionScan::Next(), and PartitionStorage::AtomicPartitionReaderIterator::nextBlock()\&.
.SS "unsigned ChunkReaderIterator::block_accessor::getBlockSize () const\fC [inline]\fP"

.PP
References block_size\&.
.PP
Referenced by claims::physical_operator::PhysicalProjectionScan::Open()\&.
.SS "void ChunkReaderIterator::block_accessor::setBlockSize (unsignedblockSize)\fC [inline]\fP"

.PP
References block_size\&.
.PP
Referenced by InMemoryChunkReaderItetaor::getNextBlockAccessor(), DiskChunkReaderIteraror::getNextBlockAccessor(), and HDFSChunkReaderIterator::getNextBlockAccessor()\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned ChunkReaderIterator::block_accessor::block_size\fC [protected]\fP"

.PP
Referenced by ChunkReaderIterator::InMemeryBlockAccessor::getBlock(), getBlockSize(), and setBlockSize()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
