.TH "ChunkID" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChunkID \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChunkID\fP (\fBPartitionID\fP partition_id, ChunkOffset chunk_offset)"
.br
.ti -1c
.RI "\fBChunkID\fP (const \fBChunkID\fP &r)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBChunkID\fP &r) const "
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBChunkID\fP &r) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPartitionID\fP \fBpartition_id\fP"
.br
.ti -1c
.RI "ChunkOffset \fBchunk_off\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
