.TH "ChunkReaderIterator::InDiskBlockAccessor" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChunkReaderIterator::InDiskBlockAccessor \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ChunkStorage\&.h>\fP
.PP
Inherits \fBChunkReaderIterator::block_accessor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBgetBlock\fP (\fBBlockStreamBase\fP *&block) const "
.br
.ti -1c
.RI "unsigned \fBgetBlockCur\fP () const "
.br
.ti -1c
.RI "void \fBsetBlockCur\fP (unsigned blockCur)"
.br
.ti -1c
.RI "const \fBChunkID\fP & \fBgetChunkId\fP () const "
.br
.ti -1c
.RI "void \fBsetChunkId\fP (const \fBChunkID\fP &chunkId)"
.br
.ti -1c
.RI "unsigned \fBgetChunkSize\fP () const "
.br
.ti -1c
.RI "void \fBsetChunkSize\fP (unsigned chunkSize)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBchunk_size\fP"
.br
.ti -1c
.RI "\fBChunkID\fP \fBchunk_id\fP"
.br
.ti -1c
.RI "unsigned \fBblock_cur\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "void ChunkReaderIterator::InDiskBlockAccessor::getBlock (\fBBlockStreamBase\fP *&block) const\fC [virtual]\fP"

.PP
Reimplemented from \fBChunkReaderIterator::block_accessor\fP\&.
.SS "unsigned ChunkReaderIterator::InDiskBlockAccessor::getBlockCur () const\fC [inline]\fP"

.PP
References block_cur\&.
.SS "const \fBChunkID\fP& ChunkReaderIterator::InDiskBlockAccessor::getChunkId () const\fC [inline]\fP"

.PP
References chunk_id\&.
.SS "unsigned ChunkReaderIterator::InDiskBlockAccessor::getChunkSize () const\fC [inline]\fP"

.PP
References chunk_size\&.
.SS "void ChunkReaderIterator::InDiskBlockAccessor::setBlockCur (unsignedblockCur)\fC [inline]\fP"

.PP
References block_cur\&.
.PP
Referenced by DiskChunkReaderIteraror::getNextBlockAccessor()\&.
.SS "void ChunkReaderIterator::InDiskBlockAccessor::setChunkId (const \fBChunkID\fP &chunkId)\fC [inline]\fP"

.PP
References chunk_id\&.
.PP
Referenced by DiskChunkReaderIteraror::getNextBlockAccessor()\&.
.SS "void ChunkReaderIterator::InDiskBlockAccessor::setChunkSize (unsignedchunkSize)\fC [inline]\fP"

.PP
References chunk_size\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned ChunkReaderIterator::InDiskBlockAccessor::block_cur\fC [private]\fP"

.PP
Referenced by getBlockCur(), and setBlockCur()\&.
.SS "\fBChunkID\fP ChunkReaderIterator::InDiskBlockAccessor::chunk_id\fC [private]\fP"

.PP
Referenced by getChunkId(), and setChunkId()\&.
.SS "unsigned ChunkReaderIterator::InDiskBlockAccessor::chunk_size\fC [private]\fP"

.PP
Referenced by getChunkSize(), and setChunkSize()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
