.TH "ChunkReaderIterator::InMemeryBlockAccessor" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChunkReaderIterator::InMemeryBlockAccessor \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBChunkReaderIterator::block_accessor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBgetBlock\fP (\fBBlockStreamBase\fP *&block) const "
.br
.ti -1c
.RI "void * \fBgetTargetBlockStartAddress\fP () const "
.br
.ti -1c
.RI "void \fBsetTargetBlockStartAddress\fP (void *targetBlockStartAddress)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
