.TH "ChunkInfo" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChunkInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BlockManager\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBChunkID\fP \fBchunkId\fP"
.br
.ti -1c
.RI "void * \fBhook\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBChunkID\fP ChunkInfo::chunkId"

.SS "void* ChunkInfo::hook"

.PP
Referenced by BlockManager::getLocal(), and BlockManager::loadFromHdfs()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
