.TH "ChunkStorage" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChunkStorage \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChunkStorage\fP (const \fBChunkID\fP &chunk_id, const unsigned &block_size, const StorageLevel &desirable_level)"
.br
.ti -1c
.RI "\fBChunkReaderIterator\fP * \fBcreateChunkReaderIterator\fP ()"
.br
.ti -1c
.RI "std::string \fBprintCurrentStorageLevel\fP () const "
.br
.ti -1c
.RI "\fBChunkID\fP \fBgetChunkID\fP ()"
.br
.ti -1c
.RI "void \fBsetCurrentStorageLevel\fP (const StorageLevel &current_level)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
