.TH "claims::logical_operator::LogicalSort::OrderByAttr" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
claims::logical_operator::LogicalSort::OrderByAttr \- 
.PP
Description: \fBOrderByAttr\fP contains the table information and its sort direction\&.We use ASC as default\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <logical_sort\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOrderByAttr\fP (const char *table_name, int direction)"
.br
.ti -1c
.RI "\fBOrderByAttr\fP (const char *table_name, const char *attribute_name)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBtable_name_\fP"
.br
.ti -1c
.RI "int \fBdirection_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Description: \fBOrderByAttr\fP contains the table information and its sort direction\&.We use ASC as default\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
