.TH "claims::common::Logging" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
claims::common::Logging \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <logging\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLogging\fP (char *program)"
.br
.ti -1c
.RI "\fB~Logging\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Logging::Logging (char *program)\fC [explicit]\fP"

.PP
References claims::common::GlogSignalHandle(), LOGDIR, and MKDIR\&.
.SS "Logging::~Logging ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
