.TH "claims" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
claims \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBcommon\fP"
.br
.ti -1c
.RI "\fBlogical_operator\fP"
.br
.ti -1c
.RI "\fBphysical_operator\fP"
.br
.ti -1c
.RI "\fBstmt_handler\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class describes what properties are required to the child data flow\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
