.TH "claims" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
claims \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
This class describes what properties are required to the child data flow\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
