.TH "claims::logical_operator::LogicalEqualJoin::JoinPair" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
claims::logical_operator::LogicalEqualJoin::JoinPair \- 
.PP
The \fBJoinPair\fP contains two attributes to be joined\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <logical_equal_join\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJoinPair\fP (const \fBAttribute\fP &left_join_attr, const \fBAttribute\fP &right_join_attr)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAttribute\fP \fBleft_join_attr_\fP"
.br
.ti -1c
.RI "\fBAttribute\fP \fBright_join_attr_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBJoinPair\fP contains two attributes to be joined\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
