.TH "claims::logical_operator::PhysicalPlanDescriptor" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
claims::logical_operator::PhysicalPlanDescriptor \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPhysicalPlan\fP \fBplan\fP"
.br
.ti -1c
.RI "\fBPlanContext\fP \fBplan_context_\fP"
.br
.ti -1c
.RI "unsigned \fBcost\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
