.TH "ClientListenerLogging" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClientListenerLogging \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Logging\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBlog\fP (const char *format,\&.\&.\&.)"
.br
.ti -1c
.RI "static void \fBelog\fP (const char *format,\&.\&.\&.)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void ClientListenerLogging::elog (const char *format, \&.\&.\&.)\fC [static]\fP"

.PP
References RawElog()\&.
.SS "void ClientListenerLogging::log (const char *format, \&.\&.\&.)\fC [static]\fP"

.PP
References RawLog()\&.
.PP
Referenced by ClientListener::configure(), ClientListener::receiveHandler(), ClientListener::sendHandler(), and ClientListener::write()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
