.TH "ClientLogging" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClientLogging \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBlog\fP (const char *format,\&.\&.\&.)"
.br
.ti -1c
.RI "static void \fBelog\fP (const char *format,\&.\&.\&.)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
