.TH "CodeGenerationTest" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CodeGenerationTest \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <codegen_test\&.h>\fP
.PP
Inherits Test\&.
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static void \fBSetUpTestCase\fP ()"
.br
.ti -1c
.RI "static void \fBTearDownTestCase\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void CodeGenerationTest::SetUpTestCase ()\fC [inline]\fP, \fC [static]\fP, \fC [protected]\fP"

.PP
References CodeGenerator::getInstance(), initialize_arithmetic_type_promotion_matrix(), initialize_operator_function(), and initialize_type_cast_functions()\&.
.SS "static void CodeGenerationTest::TearDownTestCase ()\fC [inline]\fP, \fC [static]\fP, \fC [protected]\fP"

.PP
References CodeGenerator::getInstance()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
