.TH "CodeGenerator" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CodeGenerator \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const Module * \fBgetModule\fP () const "
.br
.ti -1c
.RI "llvm::IRBuilder * \fBgetBuilder\fP () const "
.br
.ti -1c
.RI "FunctionPassManager * \fBgetFunctionPassManager\fP () const "
.br
.ti -1c
.RI "ExecutionEngine * \fBgetExecutionEngine\fP () const "
.br
.ti -1c
.RI "void \fBlock\fP ()"
.br
.ti -1c
.RI "void \fBrelease\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBCodeGenerator\fP * \fBgetInstance\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
