.TH "Columns" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Columns \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sql_node_struct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnodetype\fP \fBtype\fP"
.br
.ti -1c
.RI "char * \fBparameter1\fP"
.br
.ti -1c
.RI "char * \fBparameter2\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBnext\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBNode\fP* Columns::next"

.PP
Referenced by CreateProjection(), fromlist_analysis(), InsertData(), and newColumn()\&.
.SS "char* Columns::parameter1"

.PP
Referenced by CreateProjection(), expr_to_str(), fromlist_analysis(), get_aggregation_args(), getwctable(), groupby_analysis(), having_analysis(), InsertData(), judge_expr_equalto_expr(), newColumn(), oncondition_check(), orderby_analysis(), output(), selectlist_expr_analysis(), selectlist_has_column(), transformqual(), and wherecondition_check()\&.
.SS "char* Columns::parameter2"

.PP
Referenced by CreateProjection(), expr_to_str(), get_aggregation_args(), get_expr_str(), get_orderby_column_from_selectlist(), getjoinpairlist(), getwctable(), groupby_analysis(), having_analysis(), judge_expr_equalto_expr(), newColumn(), oncondition_check(), orderby_analysis(), output(), selectlist_expr_analysis(), selectlist_has_column(), solve_insubquery(), subquery_has_column(), transformqual(), and wherecondition_check()\&.
.SS "\fBnodetype\fP Columns::type"

.PP
Referenced by groupby_analysis(), having_analysis(), newColumn(), oncondition_check(), orderby_analysis(), selectlist_expr_analysis(), and wherecondition_check()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
