.TH "Column_atts" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Column_atts \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sql_node_struct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnodetype\fP \fBtype\fP"
.br
.ti -1c
.RI "int \fBdatatype\fP"
.br
.ti -1c
.RI "int \fBnum1\fP"
.br
.ti -1c
.RI "double \fBnum2\fP"
.br
.ti -1c
.RI "char * \fBs\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBcol_list\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBNode\fP* Column_atts::col_list"

.PP
Referenced by newColumnAtts(), and yyuserAction()\&.
.SS "int Column_atts::datatype"

.PP
Referenced by CreateTable(), newColumnAtts(), and yyuserAction()\&.
.SS "int Column_atts::num1"

.PP
Referenced by newColumnAtts(), and yyuserAction()\&.
.SS "double Column_atts::num2"

.PP
Referenced by newColumnAtts(), and yyuserAction()\&.
.SS "char* Column_atts::s"

.PP
Referenced by newColumnAtts(), and yyuserAction()\&.
.SS "\fBnodetype\fP Column_atts::type"

.PP
Referenced by newColumnAtts()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
