.TH "column_metadata" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
column_metadata \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcolumn_metadata\fP (\fBcolumn_type\fP type, \fBColumnDistribution\fP *dis=0)"
.br
.ti -1c
.RI "\fBcolumn_metadata\fP (const \fBcolumn_metadata\fP &r)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcolumn_type\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBColumnDistribution\fP * \fBdis\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
