.TH "ColumnID" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ColumnID \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ids\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColumnID\fP ()"
.br
.ti -1c
.RI "\fBColumnID\fP (\fBProjectionID\fP pid, \fBColumnOffset\fP off)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBColumnID\fP &r) const "
.br
.ti -1c
.RI "template<class Archive > void \fBserialize\fP (Archive &ar, const unsigned int version)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBProjectionID\fP \fBprojection_id\fP"
.br
.ti -1c
.RI "\fBColumnOffset\fP \fBcolumn_off\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBboost::serialization::access\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBColumnID\fP: a \fBColumn\fP corresponds to an attribute and is physically stored in one projection\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ColumnID::ColumnID ()\fC [inline]\fP"

.SS "ColumnID::ColumnID (\fBProjectionID\fPpid, \fBColumnOffset\fPoff)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool ColumnID::operator== (const \fBColumnID\fP &r) const\fC [inline]\fP"

.PP
References column_off, and projection_id\&.
.SS "template<class Archive > void ColumnID::serialize (Archive &ar, const unsigned intversion)\fC [inline]\fP"

.PP
References column_off, and projection_id\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class boost::serialization::access\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBColumnOffset\fP ColumnID::column_off"

.PP
Referenced by hash_value(), operator==(), and serialize()\&.
.SS "\fBProjectionID\fP ColumnID::projection_id"

.PP
Referenced by hash_value(), operator==(), and serialize()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
