.TH "ColumnDistribution" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ColumnDistribution \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <data_distribution_generator\&.h>\fP
.PP
Inherited by \fBUniformInt\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColumnDistribution\fP ()"
.br
.ti -1c
.RI "virtual \fB~ColumnDistribution\fP ()"
.br
.ti -1c
.RI "virtual void \fBgiveRandomValue\fP (void *column_addr)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ColumnDistribution::ColumnDistribution ()"

.SS "ColumnDistribution::~ColumnDistribution ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void ColumnDistribution::giveRandomValue (void *column_addr)\fC [virtual]\fP"

.PP
Reimplemented in \fBUniformInt\fP\&.
.PP
Referenced by test_data_distribution_generator()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
