.TH "ColumnHeader" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ColumnHeader \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ClientResponse\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBadd_header\fP (std::string name)"
.br
.ti -1c
.RI "template<class Archive > void \fBserialize\fP (Archive &ar, const unsigned int version)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< std::string > \fBheader_list\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBboost::serialization::access\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void ColumnHeader::add_header (std::stringname)\fC [inline]\fP"

.PP
References header_list\&.
.PP
Referenced by ClientListener::sendHandler()\&.
.SS "template<class Archive > void ColumnHeader::serialize (Archive &ar, const unsigned intversion)\fC [inline]\fP"

.PP
References header_list\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class boost::serialization::access\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::vector<std::string> ColumnHeader::header_list"

.PP
Referenced by add_header(), serialize(), Client::submit(), and testServerClient()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
