.TH "Commit_stmt" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Commit_stmt \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sql_node_struct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnodetype\fP \fBtype\fP"
.br
.ti -1c
.RI "int \fBchain\fP"
.br
.ti -1c
.RI "int \fBrelease\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int Commit_stmt::chain"

.SS "int Commit_stmt::release"

.SS "\fBnodetype\fP Commit_stmt::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
