.TH "Connector" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Connector \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Connector\&.h>\fP
.PP
Inherited by \fBHdfsConnector\fP, and \fBLocalDiskConnector\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConnector\fP (vector< vector< string > > \fBwritepath\fP)"
.br
.ti -1c
.RI "virtual \fB~Connector\fP ()"
.br
.ti -1c
.RI "virtual bool \fBopenFiles\fP (\fBopen_flag\fP open_flag_)=0"
.br
.ti -1c
.RI "virtual bool \fBcloseFiles\fP ()=0"
.br
.ti -1c
.RI "virtual int \fBflush\fP (unsigned projection_offset, unsigned partition_offset, void *source, unsigned length)=0"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "vector< vector< string > > \fBwritepath\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Connector::Connector (vector< vector< string > >writepath)\fC [inline]\fP"

.SS "virtual Connector::~Connector ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual bool Connector::closeFiles ()\fC [pure virtual]\fP"

.PP
Implemented in \fBHdfsConnector\fP, and \fBLocalDiskConnector\fP\&.
.PP
Referenced by HdfsLoader::append(), and HdfsLoader::load()\&.
.SS "virtual int Connector::flush (unsignedprojection_offset, unsignedpartition_offset, void *source, unsignedlength)\fC [pure virtual]\fP"

.PP
Implemented in \fBHdfsConnector\fP, and \fBLocalDiskConnector\fP\&.
.PP
Referenced by HdfsLoader::append(), HdfsLoader::insertRecords(), and HdfsLoader::load()\&.
.SS "virtual bool Connector::openFiles (\fBopen_flag\fPopen_flag_)\fC [pure virtual]\fP"

.PP
Implemented in \fBHdfsConnector\fP, and \fBLocalDiskConnector\fP\&.
.PP
Referenced by HdfsLoader::append(), and HdfsLoader::load()\&.
.SH "Member Data Documentation"
.PP 
.SS "vector<vector<string> > Connector::writepath\fC [protected]\fP"

.PP
Referenced by HdfsConnector::assgin_open_file(), and LocalDiskConnector::openFiles()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
