.TH "Coordinator::CoordinateActor" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Coordinator::CoordinateActor \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Coordinator\&.h>\fP
.PP
Inherits Actor\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCoordinateActor\fP (Theron::Framework *framework, const char *Name)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Actor 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
