.TH "Coordinator" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Coordinator \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCoordinateActor\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCoordinator\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Coordinator::Coordinator ()"
swap the order of SetupTheTheron and PreparetheSocket to provide more time to Theron::EndPoint initialization before other EndPoints connect to it\&.
.PP
References Logging::elog()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
