.TH "COUNTER" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
COUNTER \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NValue\&.hpp>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBcount\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int COUNTER::count\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
