.TH "CPUResourceManager::core" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CPUResourceManager::core \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CPUResource\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBoffset\fP"
.br
.ti -1c
.RI "bool \fBavailable\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "bool CPUResourceManager::core::available"

.PP
Referenced by CPUResourceManager::socket::addCore()\&.
.SS "int CPUResourceManager::core::id"

.PP
Referenced by CPUResourceManager::socket::addCore()\&.
.SS "int CPUResourceManager::core::offset"

.PP
Referenced by CPUResourceManager::socket::addCore()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
