.TH "Create_projection_stmt" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Create_projection_stmt \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sql_node_struct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnodetype\fP \fBtype\fP"
.br
.ti -1c
.RI "char * \fBtablename\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBcolumn_list\fP"
.br
.ti -1c
.RI "int \fBpartition_num\fP"
.br
.ti -1c
.RI "char * \fBpartition_attribute_name\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBNode\fP* Create_projection_stmt::column_list"

.PP
Referenced by CreateProjection(), and newCreateProjectionStmt()\&.
.SS "char* Create_projection_stmt::partition_attribute_name"

.PP
Referenced by CreateProjection(), and newCreateProjectionStmt()\&.
.SS "int Create_projection_stmt::partition_num"

.PP
Referenced by CreateProjection(), and newCreateProjectionStmt()\&.
.SS "char* Create_projection_stmt::tablename"

.PP
Referenced by CreateProjection(), and newCreateProjectionStmt()\&.
.SS "\fBnodetype\fP Create_projection_stmt::type"

.PP
Referenced by newCreateProjectionStmt()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
