.TH "Create_table_stmt" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Create_table_stmt \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sql_node_struct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnodetype\fP \fBtype\fP"
.br
.ti -1c
.RI "int \fBcreate_type\fP"
.br
.ti -1c
.RI "int \fBcheck\fP"
.br
.ti -1c
.RI "char * \fBname1\fP"
.br
.ti -1c
.RI "char * \fBname2\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBlist\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBselect_stmt\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int Create_table_stmt::check"

.PP
Referenced by newCreateTableStmt()\&.
.SS "int Create_table_stmt::create_type"

.PP
Referenced by newCreateTableStmt()\&.
.SS "\fBNode\fP* Create_table_stmt::list"

.PP
Referenced by CreateTable(), and newCreateTableStmt()\&.
.SS "char* Create_table_stmt::name1"

.PP
Referenced by CreateTable(), and newCreateTableStmt()\&.
.SS "char* Create_table_stmt::name2"

.PP
Referenced by CreateTable(), and newCreateTableStmt()\&.
.SS "\fBNode\fP* Create_table_stmt::select_stmt"

.PP
Referenced by newCreateTableStmt()\&.
.SS "\fBnodetype\fP Create_table_stmt::type"

.PP
Referenced by newCreateTableStmt()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
