.TH "Create_select_stmt" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Create_select_stmt \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sql_node_struct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnodetype\fP \fBtype\fP"
.br
.ti -1c
.RI "int \fBignore_replace\fP"
.br
.ti -1c
.RI "int \fBtemporary\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBselect_stmt\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int Create_select_stmt::ignore_replace"

.PP
Referenced by newCreateSelectStmt()\&.
.SS "\fBNode\fP* Create_select_stmt::select_stmt"

.PP
Referenced by newCreateSelectStmt()\&.
.SS "int Create_select_stmt::temporary"

.PP
Referenced by newCreateSelectStmt()\&.
.SS "\fBnodetype\fP Create_select_stmt::type"

.PP
Referenced by newCreateSelectStmt()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
