.TH "CreateTableRespond" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CreateTableRespond \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Message\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCreateTableRespond\fP ()"
.br
.ti -1c
.RI "\fBCreateTableRespond\fP (bool \fBresult\fP)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBCreateTableRespond\fP \fBdeserialize\fP (\fBMessage256\fP message)"
.br
.ti -1c
.RI "static \fBMessage256\fP \fBserialize\fP (\fBCreateTableRespond\fP \fBinput\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBresult\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "template<class Archive > void \fBserialize\fP (Archive &ar, const unsigned int version)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBboost::serialization::access\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CreateTableRespond::CreateTableRespond ()\fC [inline]\fP"

.SS "CreateTableRespond::CreateTableRespond (boolresult)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "static \fBCreateTableRespond\fP CreateTableRespond::deserialize (\fBMessage256\fPmessage)\fC [inline]\fP, \fC [static]\fP"

.SS "static \fBMessage256\fP CreateTableRespond::serialize (\fBCreateTableRespond\fPinput)\fC [inline]\fP, \fC [static]\fP"

.PP
References input()\&.
.SS "template<class Archive > void CreateTableRespond::serialize (Archive &ar, const unsigned intversion)\fC [inline]\fP, \fC [private]\fP"

.PP
References result\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class boost::serialization::access\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "bool CreateTableRespond::result"

.PP
Referenced by serialize()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
