.TH "Create_def" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Create_def \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sql_node_struct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnodetype\fP \fBtype\fP"
.br
.ti -1c
.RI "int \fBdeftype\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBdatatype\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBcol_atts\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBcol_list\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBNode\fP* Create_def::col_atts"

.PP
Referenced by CreateTable(), and newCreateDef()\&.
.SS "\fBNode\fP* Create_def::col_list"

.PP
Referenced by newCreateDef()\&.
.SS "\fBNode\fP* Create_def::datatype"

.PP
Referenced by CreateTable(), and newCreateDef()\&.
.SS "int Create_def::deftype"

.PP
Referenced by CreateTable(), and newCreateDef()\&.
.SS "char* Create_def::name"

.PP
Referenced by CreateTable(), and newCreateDef()\&.
.SS "\fBnodetype\fP Create_def::type"

.PP
Referenced by newCreateDef()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
