.TH "Createindex_stmt" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Createindex_stmt \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sql_node_struct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnodetype\fP \fBtype\fP"
.br
.ti -1c
.RI "int \fBindex_att\fP"
.br
.ti -1c
.RI "char * \fBindex_name\fP"
.br
.ti -1c
.RI "int \fBindex_type\fP"
.br
.ti -1c
.RI "char * \fBtable_name\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBindex_col_name\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int Createindex_stmt::index_att"

.PP
Referenced by newCreateIndex()\&.
.SS "\fBNode\fP* Createindex_stmt::index_col_name"

.PP
Referenced by newCreateIndex()\&.
.SS "char* Createindex_stmt::index_name"

.PP
Referenced by newCreateIndex()\&.
.SS "int Createindex_stmt::index_type"

.PP
Referenced by newCreateIndex()\&.
.SS "char* Createindex_stmt::table_name"

.PP
Referenced by newCreateIndex()\&.
.SS "\fBnodetype\fP Createindex_stmt::type"

.PP
Referenced by newCreateIndex()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
