.TH "Create_projection_stmt" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Create_projection_stmt \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "nodetype \fBtype\fP"
.br
.ti -1c
.RI "char * \fBtablename\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBcolumn_list\fP"
.br
.ti -1c
.RI "int \fBpartition_num\fP"
.br
.ti -1c
.RI "char * \fBpartition_attribute_name\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
