.TH "CreateTableMessage" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CreateTableMessage \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCreateTableMessage\fP (unsigned table_id, std::vector< data_type > type_list)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBCreateTableMessage\fP \fBdeserializae\fP (\fBMessage256\fP message)"
.br
.ti -1c
.RI "static \fBMessage256\fP \fBserializae\fP (\fBCreateTableMessage\fP input)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBtable_id\fP"
.br
.ti -1c
.RI "std::vector< data_type > \fBtype_list\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBboost::serialization::access\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
