.TH "data__" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data__ \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ExpressionItem\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   int \fB_int\fP"
.br
.ti -1c
.RI "   float \fB_float\fP"
.br
.ti -1c
.RI "   double \fB_double\fP"
.br
.ti -1c
.RI "   unsigned long \fB_ulong\fP"
.br
.ti -1c
.RI "   bool \fB_bool\fP"
.br
.ti -1c
.RI "   short \fB_sint\fP"
.br
.ti -1c
.RI "} \fBvalue\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "bool data__::_bool"

.PP
Referenced by do_case(), and test_com_less()\&.
.SS "double data__::_double"

.PP
Referenced by compare_equal_in_same_type(), compare_great_equal_in_same_type(), compare_great_in_same_type(), compare_less_equal_in_same_type(), compare_less_in_same_type(), compare_not_equal_in_same_type(), get_boolean_expr(), and int_to_double()\&.
.SS "float data__::_float"

.PP
Referenced by add_in_same_type(), compare_equal_in_same_type(), compare_great_equal_in_same_type(), compare_great_in_same_type(), compare_less_equal_in_same_type(), compare_less_in_same_type(), compare_not_equal_in_same_type(), get_boolean_expr(), int_to_float(), mins_in_same_type(), muls_in_same_type(), and test_multiple_()\&.
.SS "int data__::_int"

.PP
Referenced by add_in_same_type(), andop(), compare_equal_in_same_type(), compare_great_equal_in_same_type(), compare_great_in_same_type(), compare_less_equal_in_same_type(), compare_less_in_same_type(), compare_not_equal_in_same_type(), get_boolean_expr(), int_to_decimal(), int_to_double(), int_to_float(), int_to_ulong(), mins_in_same_type(), muls_in_same_type(), notop(), orop(), string_to_int(), substring(), test_add_(), test_cast(), and trim()\&.
.SS "short data__::_sint"

.PP
Referenced by compare_equal_in_same_type(), compare_great_equal_in_same_type(), compare_great_in_same_type(), compare_less_equal_in_same_type(), compare_less_in_same_type(), compare_not_equal_in_same_type(), and get_boolean_expr()\&.
.SS "unsigned long data__::_ulong"

.PP
Referenced by add_in_same_type(), compare_equal_in_same_type(), compare_great_equal_in_same_type(), compare_great_in_same_type(), compare_less_equal_in_same_type(), compare_less_in_same_type(), compare_not_equal_in_same_type(), get_boolean_expr(), int_to_ulong(), mins_in_same_type(), and muls_in_same_type()\&.
.SS "union { \&.\&.\&. }  data__::value"

.PP
Referenced by add_in_same_type(), andop(), compare_equal_in_same_type(), compare_great_equal_in_same_type(), compare_great_in_same_type(), compare_less_equal_in_same_type(), compare_less_in_same_type(), compare_not_equal_in_same_type(), do_case(), get_boolean_expr(), int_to_decimal(), int_to_double(), int_to_float(), int_to_ulong(), mins_in_same_type(), muls_in_same_type(), notop(), orop(), string_to_int(), substring(), test_add_(), test_cast(), test_com_less(), test_multiple_(), and trim()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
