.TH "data_offset< T >" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data_offset< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CSBPlusTree\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdata_offset\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fB_key\fP"
.br
.ti -1c
.RI "\fBindex_offset\fP \fB_block_off\fP"
.br
.ti -1c
.RI "\fBindex_offset\fP \fB_tuple_off\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T> \fBdata_offset\fP< T >::\fBdata_offset\fP ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename T> \fBindex_offset\fP \fBdata_offset\fP< T >::_block_off"

.PP
Referenced by CCSBLeafNode< T >::CCSBLeafNode(), CCSBInternalNode< T >::getElement(), bottomLayerSorting::indexBuilding(), and CCSBLeafNode< T >::setElement()\&.
.SS "template<typename T> T \fBdata_offset\fP< T >::_key"

.PP
Referenced by CCSBLeafNode< T >::CCSBLeafNode(), CCSBInternalNode< T >::getElement(), bottomLayerSorting::indexBuilding(), CCSBLeafNode< T >::Insert(), CSBPlusTree< T >::Insert(), CSBPlusTree< T >::makeLeafNodeGroup(), CCSBLeafNode< T >::setElement(), and CCSBLeafNode< T >::SplitInsert()\&.
.SS "template<typename T> \fBindex_offset\fP \fBdata_offset\fP< T >::_tuple_off"

.PP
Referenced by CCSBLeafNode< T >::CCSBLeafNode(), CCSBInternalNode< T >::getElement(), bottomLayerSorting::indexBuilding(), and CCSBLeafNode< T >::setElement()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
