.TH "Datatype" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Datatype \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "nodetype \fBtype\fP"
.br
.ti -1c
.RI "int \fBdatatype\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBlength\fP"
.br
.ti -1c
.RI "int \fBopt_uz\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBopt_csc\fP"
.br
.ti -1c
.RI "int \fBisbinary\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBenum_list\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
