.TH "data_offset< T >" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data_offset< T > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fB_key\fP"
.br
.ti -1c
.RI "index_offset \fB_block_off\fP"
.br
.ti -1c
.RI "index_offset \fB_tuple_off\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
