.TH "decimal::ExportSerializeOutput" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
decimal::ExportSerializeOutput \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExportSerializeOutput\fP (void *buffer, size_t capacity)"
.br
.ti -1c
.RI "void \fBwriteBinaryString\fP (const void *value, size_t length)"
.br
.ti -1c
.RI "void \fBassureExpand\fP (size_t next_write)"
.br
.ti -1c
.RI "void \fBposition\fP (std::size_t pos)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBbuffer_\fP"
.br
.ti -1c
.RI "size_t \fBposition_\fP"
.br
.ti -1c
.RI "size_t \fBcapacity_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
