.TH "DiskChunkReaderIteraror" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DiskChunkReaderIteraror \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ChunkStorage\&.h>\fP
.PP
Inherits \fBChunkReaderIterator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDiskChunkReaderIteraror\fP (const \fBChunkID\fP &chunk_id, unsigned &chunk_size, const unsigned &\fBblock_size\fP)"
.br
.ti -1c
.RI "virtual \fB~DiskChunkReaderIteraror\fP ()"
.br
.ti -1c
.RI "bool \fBnextBlock\fP (\fBBlockStreamBase\fP *&block)"
.br
.ti -1c
.RI "bool \fBgetNextBlockAccessor\fP (\fBblock_accessor\fP *&ba)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBBlock\fP * \fBblock_buffer_\fP"
.br
.ti -1c
.RI "int \fBfd_\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DiskChunkReaderIteraror::DiskChunkReaderIteraror (const \fBChunkID\fP &chunk_id, unsigned &chunk_size, const unsigned &block_size)"

.PP
References block_buffer_, ChunkReaderIterator::block_size_, ChunkReaderIterator::chunk_id_, ChunkID::chunk_off, CHUNK_SIZE, fd_, FileOpen, PartitionID::getName(), PartitionID::getPathAndName(), ChunkReaderIterator::number_of_blocks_, and ChunkID::partition_id\&.
.SS "DiskChunkReaderIteraror::~DiskChunkReaderIteraror ()\fC [virtual]\fP"

.PP
References block_buffer_, fd_, FileClose(), and Block::~Block()\&.
.SH "Member Function Documentation"
.PP 
.SS "bool DiskChunkReaderIteraror::getNextBlockAccessor (\fBblock_accessor\fP *&ba)\fC [virtual]\fP"

.PP
Implements \fBChunkReaderIterator\fP\&.
.PP
References Lock::acquire(), ChunkReaderIterator::block_size_, ChunkReaderIterator::chunk_id_, ChunkReaderIterator::chunk_size_, ChunkReaderIterator::cur_block_, ChunkReaderIterator::lock_, ChunkReaderIterator::number_of_blocks_, Lock::release(), ChunkReaderIterator::InDiskBlockAccessor::setBlockCur(), ChunkReaderIterator::block_accessor::setBlockSize(), and ChunkReaderIterator::InDiskBlockAccessor::setChunkId()\&.
.SS "bool DiskChunkReaderIteraror::nextBlock (\fBBlockStreamBase\fP *&block)\fC [virtual]\fP"

.PP
Implements \fBChunkReaderIterator\fP\&.
.PP
References Lock::acquire(), block_buffer_, ChunkReaderIterator::block_size_, BlockStreamBase::constructFromBlock(), ChunkReaderIterator::cur_block_, fd_, Block::getBlock(), Block::getsize(), ChunkReaderIterator::lock_, ChunkReaderIterator::number_of_blocks_, and Lock::release()\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBlock\fP* DiskChunkReaderIteraror::block_buffer_\fC [private]\fP"

.PP
Referenced by DiskChunkReaderIteraror(), nextBlock(), and ~DiskChunkReaderIteraror()\&.
.SS "int DiskChunkReaderIteraror::fd_\fC [private]\fP"

.PP
Referenced by DiskChunkReaderIteraror(), nextBlock(), and ~DiskChunkReaderIteraror()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
