.TH "disk_info" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
disk_info \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdisk_info\fP (int allo, int used)"
.br
.ti -1c
.RI "bool \fBtake\fP (int buget)"
.br
.ti -1c
.RI "void \fBput\fP (int size)"
.br
.ti -1c
.RI "void \fBinitialize\fP (int capacity)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBallocated_capacity\fP"
.br
.ti -1c
.RI "int \fBused_capacity\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
