.TH "disk_info" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
disk_info \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ResourceInfo\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdisk_info\fP ()"
.br
.ti -1c
.RI "\fBdisk_info\fP (int allo, int used)"
.br
.ti -1c
.RI "bool \fBtake\fP (int buget)"
.br
.ti -1c
.RI "void \fBput\fP (int size)"
.br
.ti -1c
.RI "void \fBinitialize\fP (int capacity)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBallocated_capacity\fP"
.br
.ti -1c
.RI "int \fBused_capacity\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "disk_info::disk_info ()\fC [inline]\fP"

.SS "disk_info::disk_info (intallo, intused)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void disk_info::initialize (intcapacity)\fC [inline]\fP"

.PP
References allocated_capacity, and used_capacity\&.
.SS "void disk_info::put (intsize)\fC [inline]\fP"

.PP
References used_capacity\&.
.SS "bool disk_info::take (intbuget)\fC [inline]\fP"

.PP
References allocated_capacity, and used_capacity\&.
.SH "Member Data Documentation"
.PP 
.SS "int disk_info::allocated_capacity"

.PP
Referenced by initialize(), and take()\&.
.SS "int disk_info::used_capacity"

.PP
Referenced by initialize(), put(), and take()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
