.TH "DiskStore" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DiskStore \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDiskStore\fP (string rootDirs)"
.br
.ti -1c
.RI "bool \fBputValue\fP (string blockId, void *value)"
.br
.ti -1c
.RI "void * \fBgetChunk\fP (string blockId)"
.br
.ti -1c
.RI "bool \fBremove\fP (string blockId)"
.br
.ti -1c
.RI "bool \fBcontains\fP (string blockId)"
.br
.ti -1c
.RI "unsigned \fBgetSize\fP (string blockId)"
.br
.ti -1c
.RI "bool \fBgetFile\fP (string blockId)"
.br
.ti -1c
.RI "bool \fBcreateDirs\fP (string rootDirs)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
