.TH "Dropdatabase_stmt" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dropdatabase_stmt \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sql_node_struct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnodetype\fP \fBtype\fP"
.br
.ti -1c
.RI "int \fBdroptype\fP"
.br
.ti -1c
.RI "int \fBcheck\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int Dropdatabase_stmt::check"

.PP
Referenced by newDropDatabase()\&.
.SS "int Dropdatabase_stmt::droptype"

.PP
Referenced by newDropDatabase()\&.
.SS "char* Dropdatabase_stmt::name"

.PP
Referenced by newDropDatabase()\&.
.SS "\fBnodetype\fP Dropdatabase_stmt::type"

.PP
Referenced by newDropDatabase()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
