.TH "DynamicBlockBuffer::Iterator" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DynamicBlockBuffer::Iterator \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DynamicBlockBuffer\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIterator\fP (const \fBDynamicBlockBuffer\fP *dbb)"
.br
.ti -1c
.RI "\fBIterator\fP (const \fBIterator\fP &)"
.br
.ti -1c
.RI "\fBIterator\fP ()"
.br
.ti -1c
.RI "\fBBlockStreamBase\fP * \fBnextBlock\fP ()"
.br
.ti -1c
.RI "\fBBlockStreamBase\fP * \fBatomicNextBlock\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBcur_\fP"
.br
.ti -1c
.RI "const \fBDynamicBlockBuffer\fP * \fBdbb_\fP"
.br
.ti -1c
.RI "\fBLock\fP \fBlock_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DynamicBlockBuffer::Iterator::Iterator (const \fBDynamicBlockBuffer\fP *dbb)"

.SS "DynamicBlockBuffer::Iterator::Iterator (const \fBIterator\fP &it)"

.PP
References cur_, dbb_, lock_, and DynamicBlockBuffer::lock_\&.
.SS "DynamicBlockBuffer::Iterator::Iterator ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBBlockStreamBase\fP * DynamicBlockBuffer::Iterator::atomicNextBlock ()"

.PP
References Lock::acquire(), DynamicBlockBuffer::lock_, and Lock::release()\&.
.PP
Referenced by Analyzer::analyse(), Analyzer::computeHistogram(), insert_into_insert_optimized_hash_table(), query_2(), and ClientListener::sendHandler()\&.
.SS "\fBBlockStreamBase\fP * DynamicBlockBuffer::Iterator::nextBlock ()"

.PP
References Block::getBlock()\&.
.PP
Referenced by Analyzer::compute_table_stat(), DynamicBlockBuffer::destory(), Analyzer::getDistinctCardinality(), DynamicBlockBuffer::getNumberOftuples(), claims::physical_operator::ResultCollector::GetNumberOftuples(), claims::physical_operator::PhysicalNestLoopJoin::Next(), ResultSet::print(), ClientListener::sendJsonPacket(), TEST(), TEST_F(), test_multiple_scan_filter_Scalar_Aggregation(), and test_scan_filter_Scalar_Aggregation()\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned DynamicBlockBuffer::Iterator::cur_\fC [private]\fP"

.PP
Referenced by Iterator()\&.
.SS "const \fBDynamicBlockBuffer\fP* DynamicBlockBuffer::Iterator::dbb_\fC [private]\fP"

.PP
Referenced by Iterator()\&.
.SS "\fBLock\fP DynamicBlockBuffer::Iterator::lock_\fC [private]\fP"

.PP
Referenced by Iterator()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
