.TH "DynamicBlockBuffer::Iterator" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DynamicBlockBuffer::Iterator \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIterator\fP (const \fBDynamicBlockBuffer\fP *dbb)"
.br
.ti -1c
.RI "\fBIterator\fP (const \fBIterator\fP &)"
.br
.ti -1c
.RI "\fBBlockStreamBase\fP * \fBnextBlock\fP ()"
.br
.ti -1c
.RI "\fBBlockStreamBase\fP * \fBatomicNextBlock\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
