.TH "enum_list" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
enum_list \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sql_node_struct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnodetype\fP \fBtype\fP"
.br
.ti -1c
.RI "char * \fBs\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBnext\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBNode\fP* enum_list::next"

.PP
Referenced by newEnumList()\&.
.SS "char* enum_list::s"

.PP
Referenced by newEnumList()\&.
.SS "\fBnodetype\fP enum_list::type"

.PP
Referenced by newEnumList()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
