.TH "ErrorNoTest" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ErrorNoTest \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <errno_test\&.h>\fP
.PP
Inherits Test\&.
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static void \fBSetUpTestCase\fP ()"
.br
.ti -1c
.RI "static void \fBTearDownTestCase\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void ErrorNoTest::SetUpTestCase ()\fC [inline]\fP, \fC [static]\fP, \fC [protected]\fP"

.SS "static void ErrorNoTest::TearDownTestCase ()\fC [inline]\fP, \fC [static]\fP, \fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
