.TH "ExchangeID" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExchangeID \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExchangeID\fP (unsigned long long int exchange_id, unsigned partition_offset)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBExchangeID\fP &r) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned long long int \fBexchange_id\fP"
.br
.ti -1c
.RI "unsigned \fBpartition_offset\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
