.TH "ExchangeIteratorSenderMaterialized" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExchangeIteratorSenderMaterialized \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Logging\&.h>\fP
.PP
Inherits \fBLogging\fP\&.
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBlog\fP (const char *format,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBelog\fP (const char *format,\&.\&.\&.)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "void ExchangeIteratorSenderMaterialized::elog (const char *format, \&.\&.\&.)\fC [private]\fP, \fC [virtual]\fP"
print the error information to stderr\&. 
.PP
Implements \fBLogging\fP\&.
.PP
References RawElog()\&.
.SS "void ExchangeIteratorSenderMaterialized::log (const char *format, \&.\&.\&.)\fC [private]\fP, \fC [virtual]\fP"

.PP
Implements \fBLogging\fP\&.
.PP
References RawLog()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
