.TH "ExchangeID" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExchangeID \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ids\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExchangeID\fP ()"
.br
.ti -1c
.RI "\fBExchangeID\fP (unsigned long long int \fBexchange_id\fP, unsigned \fBpartition_offset\fP)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBExchangeID\fP &r) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned long long int \fBexchange_id\fP"
.br
.ti -1c
.RI "unsigned \fBpartition_offset\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ExchangeID::ExchangeID ()\fC [inline]\fP"

.SS "ExchangeID::ExchangeID (unsigned long long intexchange_id, unsignedpartition_offset)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool ExchangeID::operator== (const \fBExchangeID\fP &r) const\fC [inline]\fP"

.PP
References exchange_id, and partition_offset\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned long long int ExchangeID::exchange_id"

.PP
Referenced by ExchangeTracker::ExchangeTrackerActor::AskForConnectionInfo(), claims::physical_operator::ExchangeSender::ConnectToUpper(), hash_value(), and operator==()\&.
.SS "unsigned ExchangeID::partition_offset"

.PP
Referenced by hash_value(), and operator==()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
