.TH "ExectorFunction" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExectorFunction \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <queryfunc\&.h>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBExecFunc\fP \fBoperator_function\fP [\fBDATA_TYPE_NUM\fP][\fBOPER_TYPE_NUM\fP]"
.br
.ti -1c
.RI "static \fBAvgDivide\fP \fBavg_divide\fP [\fBDATA_TYPE_NUM\fP]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBAvgDivide\fP ExectorFunction::avg_divide\fC [static]\fP"

.PP
Referenced by InitAvgDivide()\&.
.SS "\fBExecFunc\fP ExectorFunction::operator_function\fC [static]\fP"

.PP
Referenced by InitExprAtPhysicalPlan(), and initialize_operator_function()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
