.TH "Exp_op" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Exp_op \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ExpressionCalculator\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBExpression\fP \fBexpr\fP"
.br
.ti -1c
.RI "int \fBop\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBExpression\fP Exp_op::expr"

.SS "int Exp_op::op"


.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
