.TH "ExpandedThreadTracker" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExpandedThreadTracker \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ExpandedThreadTracker\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExpandedThreadTracker\fP (\fBExpandabilityShrinkability\fP *expand_shrink)"
.br
.ti -1c
.RI "virtual \fB~ExpandedThreadTracker\fP ()"
.br
.ti -1c
.RI "\fBPerformanceInfo\fP & \fBgetPerformanceInfo\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBPerformanceInfo\fP \fBperf_info_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ExpandedThreadTracker::ExpandedThreadTracker (\fBExpandabilityShrinkability\fP *expand_shrink)"

.SS "ExpandedThreadTracker::~ExpandedThreadTracker ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBPerformanceInfo\fP& ExpandedThreadTracker::getPerformanceInfo ()\fC [inline]\fP"

.PP
References perf_info_\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPerformanceInfo\fP ExpandedThreadTracker::perf_info_\fC [private]\fP"

.PP
Referenced by getPerformanceInfo()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
