.TH "ExpandableBlockStreamSingleColumnScanDisk::State" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExpandableBlockStreamSingleColumnScanDisk::State \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBState\fP (std::string file_name, \fBSchema\fP *schema, unsigned block_size)"
.br
.ti -1c
.RI "\fBState\fP (std::string file_name, \fBSchema\fP *schema, unsigned block_size, unsigned long used_length)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBExpandableBlockStreamSingleColumnScanDisk\fP"
.br
.ti -1c
.RI "class \fBboost::serialization::access\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
