.TH "ExpandabilityShrinkability" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExpandabilityShrinkability \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBBlockStreamExpander\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBExpand\fP ()=0"
.br
.ti -1c
.RI "virtual bool \fBShrink\fP ()=0"
.br
.ti -1c
.RI "virtual unsigned \fBgetDegreeOfParallelism\fP ()=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
