.TH "ExpanderTrackerLogging" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExpanderTrackerLogging \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLogging\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBlog\fP (const char *format,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBelog\fP (const char *format,\&.\&.\&.)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void ExpanderTrackerLogging::elog (const char *format, \&.\&.\&.)\fC [virtual]\fP"
print the error information to stderr\&. 
.PP
Implements \fBLogging\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
