.TH "ExpandedThreadTracker" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExpandedThreadTracker \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExpandedThreadTracker\fP (\fBExpandabilityShrinkability\fP *expand_shrink)"
.br
.ti -1c
.RI "\fBPerformanceInfo\fP & \fBgetPerformanceInfo\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
