.TH "ExpandableBlockStreamRandomDiskAccess::remaining_block" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExpandableBlockStreamRandomDiskAccess::remaining_block \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBremaining_block\fP (\fBBlockStreamBase\fP *block, \fBBlockStreamBase::BlockStreamTraverseIterator\fP *iterator)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBlockStreamBase\fP * \fBblock\fP"
.br
.ti -1c
.RI "\fBBlockStreamBase::BlockStreamTraverseIterator\fP * \fBiterator\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
