.TH "ExpandableBlockStreamHdfsScan::current_block" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExpandableBlockStreamHdfsScan::current_block \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBfile_index\fP"
.br
.ti -1c
.RI "unsigned \fBlength\fP"
.br
.ti -1c
.RI "char * \fBbase\fP"
.br
.ti -1c
.RI "char * \fBcursor\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
