.TH "ExpandableBlockStreamRandomDiskAccess::State" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExpandableBlockStreamRandomDiskAccess::State \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBState\fP (std::string file_name, \fBBlockStreamIteratorBase\fP *child, \fBSchema\fP *f_schema, \fBSchema\fP *c_schema, unsigned block_size)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBExpandableBlockStreamRandomDiskAccess\fP"
.br
.ti -1c
.RI "class \fBboost::serialization::access\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
