.TH "ExpandabilityShrinkability" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExpandabilityShrinkability \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ExpandabilityShrinkability\&.h>\fP
.PP
Inherited by \fBclaims::physical_operator::Expander\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExpandabilityShrinkability\fP ()"
.br
.ti -1c
.RI "virtual \fB~ExpandabilityShrinkability\fP ()"
.br
.ti -1c
.RI "virtual bool \fBExpand\fP ()=0"
.br
.ti -1c
.RI "virtual bool \fBShrink\fP ()=0"
.br
.ti -1c
.RI "virtual unsigned \fBGetDegreeOfParallelism\fP ()=0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ExpandabilityShrinkability::ExpandabilityShrinkability ()"

.SS "ExpandabilityShrinkability::~ExpandabilityShrinkability ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual bool ExpandabilityShrinkability::Expand ()\fC [pure virtual]\fP"

.PP
Implemented in \fBclaims::physical_operator::Expander\fP\&.
.SS "virtual unsigned ExpandabilityShrinkability::GetDegreeOfParallelism ()\fC [pure virtual]\fP"

.PP
Implemented in \fBclaims::physical_operator::Expander\fP\&.
.PP
Referenced by PerformanceInfo::processed_one_block()\&.
.SS "virtual bool ExpandabilityShrinkability::Shrink ()\fC [pure virtual]\fP"

.PP
Implemented in \fBclaims::physical_operator::Expander\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
