.TH "ExpandableBlockStreamExchangeLowerMaterialized::State" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExpandableBlockStreamExchangeLowerMaterialized::State \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBState\fP (\fBSchema\fP *schema, \fBBlockStreamIteratorBase\fP *child, std::vector< NodeID > upper_id_list, unsigned block_size, unsigned long long int exchange_id=0, \fBpartition_schema\fP partition_key_index=partition_schema::set_hash_partition())"
.br
.ti -1c
.RI "template<class Archive > void \fBserialize\fP (Archive &ar, const unsigned int version)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSchema\fP * \fBschema_\fP"
.br
.ti -1c
.RI "\fBBlockStreamIteratorBase\fP * \fBchild_\fP"
.br
.ti -1c
.RI "unsigned long long int \fBexchange_id_\fP"
.br
.ti -1c
.RI "std::vector< NodeID > \fBupper_id_list_\fP"
.br
.ti -1c
.RI "unsigned \fBblock_size_\fP"
.br
.ti -1c
.RI "PartitionOffset \fBpartition_offset\fP"
.br
.ti -1c
.RI "\fBpartition_schema\fP \fBpartition_schema_\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBboost::serialization::access\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
