.TH "express_operator" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
express_operator \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBset\fP (op_type tp, unsigned number_of_parameter=0)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "op_type \fBop_\fP"
.br
.ti -1c
.RI "unsigned \fBnum_of_parameter\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
