.TH "Expr_list" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Expr_list \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sql_node_struct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnodetype\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBdata\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBnext\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBNode\fP* Expr_list::data"

.PP
Referenced by getwctable(), groupby_analysis(), having_analysis(), LoadData(), newExprList(), oncondition_check(), output(), solve_insubquery(), transformqual(), and wherecondition_check()\&.
.SS "\fBNode\fP* Expr_list::next"

.PP
Referenced by getwctable(), groupby_analysis(), having_analysis(), LoadData(), newExprList(), oncondition_check(), solve_insubquery(), transformqual(), and wherecondition_check()\&.
.SS "\fBnodetype\fP Expr_list::type"

.PP
Referenced by newExprList()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
