.TH "ExpressionCalculator" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExpressionCalculator \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBcalcuate\fP (Expression &exp, \fBExpressionItem\fP &result)"
.br
.ti -1c
.RI "static void \fBcalcualte\fP (Expression &exp, ExpressionItemStack &stack)"
.br
.ti -1c
.RI "static void \fBcompute\fP (\fBExpressionItem\fP operator_item, ExpressionItemStack &stack)"
.br
.ti -1c
.RI "static void \fBcomputes\fP (\fBExpressionItem\fP operator_item, ExpressionItemStack &stack)"
.br
.ti -1c
.RI "static data_type \fBgetOutputType\fP (vector< \fBExpressionItem\fP > &exp)"
.br
.ti -1c
.RI "static \fBcolumn_type\fP \fBgetOutputType_\fP (vector< \fBExpressionItem\fP > &exp)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
