.TH "Expr" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Expr \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sql_node_struct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnodetype\fP \fBtype\fP"
.br
.ti -1c
.RI "char * \fBdata\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char* Expr::data"

.PP
Referenced by CheckType(), expr_to_str(), get_orderby_column_from_selectlist(), InsertValueToStream(), LoadData(), newExpr(), output(), and transformqual()\&.
.SS "\fBnodetype\fP Expr::type"

.PP
Referenced by CheckType(), and newExpr()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
