.TH "Expr_list_header" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Expr_list_header \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sql_node_struct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnodetype\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBheader\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBtail\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBNode\fP* Expr_list_header::header"

.PP
Referenced by newExprlistheader(), output(), setocposition(), setwcposition(), and where_from2logicalplan()\&.
.SS "\fBNode\fP* Expr_list_header::tail"

.PP
Referenced by newExprlistheader(), setocposition(), and setwcposition()\&.
.SS "\fBnodetype\fP Expr_list_header::type"

.PP
Referenced by newExprlistheader()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
