.TH "From_list" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
From_list \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sql_node_struct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnodetype\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBargs\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBwhcdn\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBNode\fP* From_list::args"

.PP
Referenced by fromlist_analysis(), newFromList(), output(), setwcposition(), solve_join_condition(), and where_from2logicalplan()\&.
.SS "\fBNode\fP* From_list::next"

.PP
Referenced by fromlist_analysis(), newFromList(), setwcposition(), solve_join_condition(), and where_from2logicalplan()\&.
.SS "\fBnodetype\fP From_list::type"

.PP
Referenced by newFromList()\&.
.SS "\fBNode\fP* From_list::whcdn"

.PP
Referenced by newFromList(), output(), setwcposition(), and where_from2logicalplan()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
