.TH "Having_list" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Having_list \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sql_node_struct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnodetype\fP \fBtype\fP"
.br
.ti -1c
.RI "char * \fBhavingstring\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBnext\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char* Having_list::havingstring"

.PP
Referenced by newHavingList(), and output()\&.
.SS "\fBNode\fP* Having_list::next"

.PP
Referenced by newHavingList()\&.
.SS "\fBnodetype\fP Having_list::type"

.PP
Referenced by newHavingList()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
