.TH "HdfsConnector" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HdfsConnector \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBConnector\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHdfsConnector\fP (vector< vector< string > > hdfs_writepath)"
.br
.ti -1c
.RI "bool \fBopenFiles\fP (open_flag open_flag_)"
.br
.ti -1c
.RI "bool \fBcloseFiles\fP ()"
.br
.ti -1c
.RI "int \fBflush\fP (unsigned projection_offset, unsigned partition_offset, void *source, unsigned length)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
