.TH "HdfsBlock" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HdfsBlock \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MemoryStore\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHdfsBlock\fP ()"
.br
.ti -1c
.RI "\fBHdfsBlock\fP (void *\fBadd\fP, int \fBlength\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBhook\fP"
.br
.ti -1c
.RI "int \fBlength\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HdfsBlock::HdfsBlock ()\fC [inline]\fP"

.SS "HdfsBlock::HdfsBlock (void *add, intlength)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "void* HdfsBlock::hook"

.PP
Referenced by ChunkStorage::createChunkReaderIterator(), MemoryChunkStore::returnChunk(), and MemoryChunkStore::tryToPut()\&.
.SS "int HdfsBlock::length"

.PP
Referenced by ChunkStorage::createChunkReaderIterator(), MemoryChunkStore::returnChunk(), and MemoryChunkStore::tryToPut()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
