.TH "HDFSChunkReaderIterator" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HDFSChunkReaderIterator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBChunkReaderIterator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHDFSChunkReaderIterator\fP (const \fBChunkID\fP &chunk_id, unsigned &chunk_size, const unsigned &block_size)"
.br
.ti -1c
.RI "bool \fBnextBlock\fP (\fBBlockStreamBase\fP *&block)"
.br
.ti -1c
.RI "bool \fBgetNextBlockAccessor\fP (\fBblock_accessor\fP *&ba)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
