.TH "Histogram" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Histogram \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Statistic\&.h>\fP
.PP
Inherited by \fBStatisticOnTable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHistogram\fP ()"
.br
.ti -1c
.RI "\fBHistogram\fP (unsigned bucketCnt)"
.br
.ti -1c
.RI "void \fBsetTupleCount\fP (unsigned long tupleCount)"
.br
.ti -1c
.RI "void \fBsetValueCount\fP (unsigned long valueCount)"
.br
.ti -1c
.RI "void \fBsetMostCommonValues\fP (void **mcvList, double *seleList)"
.br
.ti -1c
.RI "void \fBsetEquithDepthBound\fP (void **boundList, unsigned long *bucketValueCount)"
.br
.ti -1c
.RI "unsigned long \fBgetTupleCount\fP () const "
.br
.ti -1c
.RI "unsigned long \fBgetValueCount\fP () const "
.br
.ti -1c
.RI "unsigned \fBgetBucketCnt\fP () const "
.br
.ti -1c
.RI "void \fBPrint\fP (\fBcolumn_type\fP type)"
.br
.ti -1c
.RI "void \fBdestory\fP ()"
.br
.ti -1c
.RI "virtual \fB~Histogram\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBm_bucketCnt\fP"
.br
.ti -1c
.RI "unsigned long \fBm_staDistinct\fP"
.br
.ti -1c
.RI "unsigned long \fBm_staCount\fP"
.br
.ti -1c
.RI "double \fBm_staNullFrac\fP"
.br
.ti -1c
.RI "\fBValuePtr\fP * \fBm_staValues1\fP"
.br
.ti -1c
.RI "\fBValuePtr\fP * \fBm_staValues2\fP"
.br
.ti -1c
.RI "unsigned long * \fBm_staNumbers1\fP"
.br
.ti -1c
.RI "double * \fBm_staNumbers2\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBEstimation\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Histogram::Histogram ()"

.PP
References m_bucketCnt, m_staNumbers1, and m_staNumbers2\&.
.SS "Histogram::Histogram (unsignedbucketCnt)"

.PP
References m_bucketCnt\&.
.SS "Histogram::~Histogram ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Histogram::destory ()"

.PP
References m_bucketCnt, m_staNumbers1, m_staNumbers2, m_staValues1, and m_staValues2\&.
.PP
Referenced by StatisticOnTable::destory()\&.
.SS "unsigned Histogram::getBucketCnt () const"

.PP
References m_bucketCnt\&.
.PP
Referenced by Analyzer::equiDepthAnalyse(), and Analyzer::mcvAnalyse()\&.
.SS "unsigned long Histogram::getTupleCount () const"

.PP
References m_staCount\&.
.PP
Referenced by Analyzer::equiDepthAnalyse(), Estimation::estEqualOper(), and Analyzer::mcvAnalyse()\&.
.SS "unsigned long Histogram::getValueCount () const"

.PP
References m_staDistinct\&.
.SS "void Histogram::Print (\fBcolumn_type\fPtype)"

.PP
References m_bucketCnt, m_staCount, m_staDistinct, m_staNumbers2, m_staValues2, column_type::operate, and Operate::toString()\&.
.PP
Referenced by Analyzer::compute_attribute_stat()\&.
.SS "void Histogram::setEquithDepthBound (void **boundList, unsigned long *bucketValueCount)"

.PP
References m_staNumbers1, and m_staValues1\&.
.PP
Referenced by Analyzer::equiDepthAnalyse()\&.
.SS "void Histogram::setMostCommonValues (void **mcvList, double *seleList)"

.PP
References m_staNumbers2, and m_staValues2\&.
.PP
Referenced by Analyzer::mcvAnalyse()\&.
.SS "void Histogram::setTupleCount (unsigned longtupleCount)"

.PP
References m_staCount\&.
.PP
Referenced by Analyzer::analyse(), and Analyzer::computeHistogram()\&.
.SS "void Histogram::setValueCount (unsigned longvalueCount)"

.PP
References m_staDistinct\&.
.PP
Referenced by Analyzer::analyse(), and Analyzer::computeHistogram()\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBEstimation\fP\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "unsigned Histogram::m_bucketCnt\fC [private]\fP"

.PP
Referenced by destory(), Estimation::estEqualJoin(), Estimation::estEqualOper(), Estimation::estRangeOper(), getBucketCnt(), Histogram(), and Print()\&.
.SS "unsigned long Histogram::m_staCount\fC [private]\fP"

.PP
Referenced by Estimation::estEqualJoin(), Estimation::estRangeOper(), getTupleCount(), Print(), and setTupleCount()\&.
.SS "unsigned long Histogram::m_staDistinct\fC [private]\fP"

.PP
Referenced by getValueCount(), Print(), and setValueCount()\&.
.SS "double Histogram::m_staNullFrac\fC [private]\fP"

.SS "unsigned long* Histogram::m_staNumbers1\fC [private]\fP"

.PP
Referenced by destory(), Estimation::estEqualJoin(), Estimation::estEqualOper(), Estimation::estRangeOper(), Histogram(), and setEquithDepthBound()\&.
.SS "double* Histogram::m_staNumbers2\fC [private]\fP"

.PP
Referenced by destory(), Estimation::estEqualOper(), Histogram(), Print(), and setMostCommonValues()\&.
.SS "\fBValuePtr\fP* Histogram::m_staValues1\fC [private]\fP"

.PP
Referenced by destory(), Estimation::estEqualJoin(), Estimation::estEqualOper(), Estimation::estRangeOper(), and setEquithDepthBound()\&.
.SS "\fBValuePtr\fP* Histogram::m_staValues2\fC [private]\fP"

.PP
Referenced by destory(), Estimation::estEqualOper(), Print(), and setMostCommonValues()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
