.TH "IndexScanIterator::State" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IndexScanIterator::State \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IndexScanIterator\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBState\fP ()"
.br
.ti -1c
.RI "\fBState\fP (\fBProjectionID\fP projection_id, \fBSchema\fP *schema, unsigned long index_id, vector< \fBquery_range\fP > query_range__, unsigned \fBblock_size\fP)"
.br
.ti -1c
.RI "template<class Archive > void \fBserialize\fP (Archive &ar, const unsigned int version)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBProjectionID\fP \fBprojection_id_\fP"
.br
.ti -1c
.RI "\fBSchema\fP * \fBschema_\fP"
.br
.ti -1c
.RI "unsigned long \fBindex_id_\fP"
.br
.ti -1c
.RI "vector< \fBquery_range\fP > \fBquery_range_\fP"
.br
.ti -1c
.RI "unsigned \fBblock_size_\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBIndexScanIterator\fP"
.br
.ti -1c
.RI "class \fBboost::serialization::access\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IndexScanIterator::State::State ()\fC [inline]\fP"

.SS "IndexScanIterator::State::State (\fBProjectionID\fPprojection_id, \fBSchema\fP *schema, unsigned longindex_id, vector< \fBquery_range\fP >query_range__, unsignedblock_size)"

.SH "Member Function Documentation"
.PP 
.SS "template<class Archive > void IndexScanIterator::State::serialize (Archive &ar, const unsigned intversion)\fC [inline]\fP"

.PP
References block_size_, index_id_, projection_id_, query_range_, and schema_\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class boost::serialization::access\fC [friend]\fP"

.SS "friend class \fBIndexScanIterator\fP\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "unsigned IndexScanIterator::State::block_size_"

.PP
Referenced by LogicalIndexScan::GetPhysicalPlan(), IndexScanIterator::Open(), and serialize()\&.
.SS "unsigned long IndexScanIterator::State::index_id_"

.PP
Referenced by IndexScanIterator::askForNextBlock(), LogicalIndexScan::GetPhysicalPlan(), IndexScanIterator::Open(), and serialize()\&.
.SS "\fBProjectionID\fP IndexScanIterator::State::projection_id_"

.PP
Referenced by LogicalIndexScan::GetPhysicalPlan(), IndexScanIterator::Open(), and serialize()\&.
.SS "vector<\fBquery_range\fP> IndexScanIterator::State::query_range_"

.PP
Referenced by IndexScanIterator::askForNextBlock(), LogicalIndexScan::GetPhysicalPlan(), and serialize()\&.
.SS "\fBSchema\fP* IndexScanIterator::State::schema_"

.PP
Referenced by LogicalIndexScan::GetPhysicalPlan(), IndexScanIterator::Next(), IndexScanIterator::Open(), and serialize()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
