.TH "IndexScanIterator::remaining_block" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IndexScanIterator::remaining_block \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBremaining_block\fP (map< index_offset, vector< index_offset > * > *result_set, map< index_offset, vector< index_offset > * >::iterator iter_result_map, vector< index_offset >::iterator iter_result_vector, unsigned short block_off, \fBBlockStreamBase\fP *block, \fBBlockStreamBase::BlockStreamTraverseIterator\fP *iterator)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "map< index_offset, vector
.br
< index_offset > * > * \fBresult_set\fP"
.br
.ti -1c
.RI "map< index_offset, vector
.br
< index_offset > * >::iterator \fBiter_result_map\fP"
.br
.ti -1c
.RI "vector< index_offset >::iterator \fBiter_result_vector\fP"
.br
.ti -1c
.RI "unsigned short \fBblock_off\fP"
.br
.ti -1c
.RI "\fBBlockStreamBase\fP * \fBblock\fP"
.br
.ti -1c
.RI "\fBBlockStreamBase::BlockStreamTraverseIterator\fP * \fBiterator\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
