.TH "IndexManager" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IndexManager \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IndexManager\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~IndexManager\fP ()"
.br
.ti -1c
.RI "bool \fBaddIndexToList\fP (unsigned key_indexing, map< \fBChunkID\fP, void * > attr_index)"
.br
.ti -1c
.RI "bool \fBinsertIndexToList\fP (std::string index_name, unsigned key_indexing, map< \fBChunkID\fP, void * > attr_index)"
.br
.ti -1c
.RI "template<typename T > std::map< \fBChunkID\fP, \fBCSBPlusTree\fP
.br
< T > * > \fBgetIndexList\fP (\fBAttribute\fP attribute)"
.br
.ti -1c
.RI "template<typename T > std::map< \fBChunkID\fP, \fBCSBPlusTree\fP
.br
< T > * > \fBgetIndexList\fP (unsigned long attr_index_id)"
.br
.ti -1c
.RI "std::map< \fBChunkID\fP, void * > \fBgetAttrIndex\fP (unsigned long attr_index_id)"
.br
.ti -1c
.RI "template<typename T > bool \fBdeleteIndexFromList\fP (unsigned long index_id)"
.br
.ti -1c
.RI "\fBdata_type\fP \fBgetIndexType\fP (unsigned long index_id)"
.br
.ti -1c
.RI "bool \fBisIndexExist\fP (\fBAttribute\fP attr)"
.br
.ti -1c
.RI "bool \fBisIndexExist\fP (unsigned long index_id)"
.br
.ti -1c
.RI "unsigned long \fBgetIndexID\fP (\fBAttribute\fP attr)"
.br
.ti -1c
.RI "bool \fBserialize\fP (std::string file_name)"
.br
.ti -1c
.RI "bool \fBdeserialize\fP (std::string file_name)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBIndexManager\fP * \fBgetInstance\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBIndexManager\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "map< unsigned long, 
.br
\fBattr_index_list\fP * > \fBcsb_index_\fP"
.br
.ti -1c
.RI "unsigned long \fBattr_index_id_\fP"
.br
.ti -1c
.RI "map< \fBAttribute\fP, unsigned long > \fBcolumn_attribute_to_id\fP"
.br
.ti -1c
.RI "map< unsigned long, \fBAttribute\fP > \fBid_to_column_attribute\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static \fBIndexManager\fP * \fBinstance_\fP = 0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IndexManager::~IndexManager ()\fC [virtual]\fP"

.SS "IndexManager::IndexManager ()\fC [private]\fP"

.PP
References attr_index_id_, column_attribute_to_id, csb_index_, and id_to_column_attribute\&.
.PP
Referenced by getInstance()\&.
.SH "Member Function Documentation"
.PP 
.SS "bool IndexManager::addIndexToList (unsignedkey_indexing, map< \fBChunkID\fP, void * >attr_index)"

.PP
References attr_index_id_, column_attribute_to_id, csb_index_, attr_index_list::csb_tree_list, Catalog::getInstance(), Catalog::getProjection(), and id_to_column_attribute\&.
.SS "template<typename T > bool IndexManager::deleteIndexFromList (unsigned longindex_id)"

.PP
References column_attribute_to_id, csb_index_, attr_index_list::csb_tree_list, and id_to_column_attribute\&.
.SS "bool IndexManager::deserialize (std::stringfile_name)"

.PP
References attr_index_id_, attr_index_list::attr_index_name, attr_index_list::attribute, Attribute::attrName, Attribute::attrType, column_attribute_to_id, csb_index_, attr_index_list::csb_tree_list, CSBPlusTree< T >::deserialize(), id_to_column_attribute, Attribute::index, NULL, t_int, Attribute::table_id_, column_type::type, and Attribute::unique\&.
.PP
Referenced by test_deserialize()\&.
.SS "std::map< \fBChunkID\fP, void * > IndexManager::getAttrIndex (unsigned longattr_index_id)"

.PP
References csb_index_\&.
.PP
Referenced by IndexScanIterator::Open()\&.
.SS "unsigned long IndexManager::getIndexID (\fBAttribute\fPattr)"

.PP
References Attribute::attrName, column_attribute_to_id, and isIndexExist()\&.
.PP
Referenced by LogicalIndexScan::GetPhysicalPlan()\&.
.SS "template<typename T > std::map< \fBChunkID\fP, \fBCSBPlusTree\fP< T > * > IndexManager::getIndexList (\fBAttribute\fPattribute)"

.PP
References Attribute::attrName, column_attribute_to_id, and csb_index_\&.
.PP
Referenced by cheak_com_index()\&.
.SS "template<typename T > std::map< \fBChunkID\fP, \fBCSBPlusTree\fP< T > * > IndexManager::getIndexList (unsigned longattr_index_id)"

.PP
References csb_index_\&.
.SS "\fBdata_type\fP IndexManager::getIndexType (unsigned longindex_id)"

.PP
References id_to_column_attribute\&.
.PP
Referenced by IndexScanIterator::askForNextBlock()\&.
.SS "\fBIndexManager\fP * IndexManager::getInstance ()\fC [static]\fP"

.PP
References IndexManager(), and instance_\&.
.PP
Referenced by IndexScanIterator::askForNextBlock(), cheak_com_index(), LogicalIndexScan::GetPhysicalPlan(), Environment::initializeIndexManager(), bottomLayerSorting::Next(), IndexScanIterator::Open(), test_deserialize(), and test_serialize()\&.
.SS "bool IndexManager::insertIndexToList (std::stringindex_name, unsignedkey_indexing, map< \fBChunkID\fP, void * >attr_index)"

.PP
References attr_index_id_, Attribute::attrName, column_attribute_to_id, csb_index_, attr_index_list::csb_tree_list, Catalog::getInstance(), Catalog::getProjection(), and id_to_column_attribute\&.
.PP
Referenced by bottomLayerSorting::Next()\&.
.SS "bool IndexManager::isIndexExist (\fBAttribute\fPattr)"

.PP
References column_attribute_to_id\&.
.PP
Referenced by getIndexID()\&.
.SS "bool IndexManager::isIndexExist (unsigned longindex_id)"

.PP
References csb_index_\&.
.SS "bool IndexManager::serialize (std::stringfile_name)"

.PP
References attr_index_id_, attr_index_list::attr_index_name, attr_index_list::attribute, Attribute::attrName, Attribute::attrType, csb_index_, attr_index_list::csb_tree_list, Attribute::index, NULL, t_int, Attribute::table_id_, column_type::type, and Attribute::unique\&.
.PP
Referenced by test_serialize()\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned long IndexManager::attr_index_id_\fC [private]\fP"

.PP
Referenced by addIndexToList(), deserialize(), IndexManager(), insertIndexToList(), and serialize()\&.
.SS "map<\fBAttribute\fP, unsigned long > IndexManager::column_attribute_to_id\fC [private]\fP"

.PP
Referenced by addIndexToList(), deleteIndexFromList(), deserialize(), getIndexID(), getIndexList(), IndexManager(), insertIndexToList(), and isIndexExist()\&.
.SS "map<unsigned long, \fBattr_index_list\fP*> IndexManager::csb_index_\fC [private]\fP"

.PP
Referenced by addIndexToList(), deleteIndexFromList(), deserialize(), getAttrIndex(), getIndexList(), IndexManager(), insertIndexToList(), isIndexExist(), and serialize()\&.
.SS "map<unsigned long, \fBAttribute\fP> IndexManager::id_to_column_attribute\fC [private]\fP"

.PP
Referenced by addIndexToList(), deleteIndexFromList(), deserialize(), getIndexType(), IndexManager(), and insertIndexToList()\&.
.SS "\fBIndexManager\fP * IndexManager::instance_ = 0\fC [static]\fP, \fC [private]\fP"

.PP
Referenced by getInstance()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
