.TH "input_struct" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
input_struct \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "bool \fBappend\fP (const char *str)"
.br
.ti -1c
.RI "bool \fBappend_til\fP (const char *str, char target, bool &target_match)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBstring\fP [string_length]"
.br
.ti -1c
.RI "int \fBindex\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
