.TH "Insert_assign_list" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Insert_assign_list \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sql_node_struct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnodetype\fP \fBtype\fP"
.br
.ti -1c
.RI "char * \fBcol_name\fP"
.br
.ti -1c
.RI "int \fBvalue_type\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBexpr\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBnext\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char* Insert_assign_list::col_name"

.PP
Referenced by newInsertAssignList()\&.
.SS "\fBNode\fP* Insert_assign_list::expr"

.PP
Referenced by newInsertAssignList()\&.
.SS "\fBNode\fP* Insert_assign_list::next"

.PP
Referenced by newInsertAssignList()\&.
.SS "\fBnodetype\fP Insert_assign_list::type"

.PP
Referenced by newInsertAssignList()\&.
.SS "int Insert_assign_list::value_type"

.PP
Referenced by newInsertAssignList()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
