.TH "InsertOptimizedHashTable::entry" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InsertOptimizedHashTable::entry \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <InsertOptimizedHashTable\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBentry\fP ()"
.br
.ti -1c
.RI "\fBentry\fP (void *p)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBpointer\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "InsertOptimizedHashTable::entry::entry ()\fC [inline]\fP"

.SS "InsertOptimizedHashTable::entry::entry (void *p)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "void* InsertOptimizedHashTable::entry::pointer"

.PP
Referenced by InsertOptimizedHashTable::BucketIterator::nextTuple()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
