.TH "Insert_stmt" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Insert_stmt \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sql_node_struct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnodetype\fP \fBtype\fP"
.br
.ti -1c
.RI "int \fBinsert_opt\fP"
.br
.ti -1c
.RI "char * \fBtablename\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBcol_list\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBinsert_val_list\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBinsert_assign_list\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBinsert_assign_list_from_set\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBselect_stmt\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBNode\fP* Insert_stmt::col_list"

.PP
Referenced by InsertData(), and newInsertStmt()\&.
.SS "\fBNode\fP* Insert_stmt::insert_assign_list"

.PP
Referenced by newInsertStmt()\&.
.SS "\fBNode\fP* Insert_stmt::insert_assign_list_from_set"

.PP
Referenced by newInsertStmt()\&.
.SS "int Insert_stmt::insert_opt"

.PP
Referenced by newInsertStmt()\&.
.SS "\fBNode\fP* Insert_stmt::insert_val_list"

.PP
Referenced by InsertData(), and newInsertStmt()\&.
.SS "\fBNode\fP* Insert_stmt::select_stmt"

.PP
Referenced by newInsertStmt()\&.
.SS "char* Insert_stmt::tablename"

.PP
Referenced by InsertData(), and newInsertStmt()\&.
.SS "\fBnodetype\fP Insert_stmt::type"

.PP
Referenced by newInsertStmt()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
