.TH "Insert_val_list" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Insert_val_list \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sql_node_struct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnodetype\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBinsert_vals\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBnext\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBNode\fP* Insert_val_list::insert_vals"

.PP
Referenced by InsertData(), and newInsertValueList()\&.
.SS "\fBNode\fP* Insert_val_list::next"

.PP
Referenced by InsertData(), and newInsertValueList()\&.
.SS "\fBnodetype\fP Insert_val_list::type"

.PP
Referenced by newInsertValueList()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
