.TH "Insert_vals" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Insert_vals \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sql_node_struct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnodetype\fP \fBtype\fP"
.br
.ti -1c
.RI "int \fBvalue_type\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBexpr\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBnext\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBNode\fP* Insert_vals::expr"

.PP
Referenced by InsertValueToStream(), and newInsertVals()\&.
.SS "\fBNode\fP* Insert_vals::next"

.PP
Referenced by InsertData(), and newInsertVals()\&.
.SS "\fBnodetype\fP Insert_vals::type"

.PP
Referenced by InsertValueToStream(), and newInsertVals()\&.
.SS "int Insert_vals::value_type"

.PP
Referenced by InsertValueToStream(), and newInsertVals()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
