.TH "InstanceResourceManager" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InstanceResourceManager \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ResourceManagerSlave\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInstanceResourceManager\fP ()"
.br
.ti -1c
.RI "virtual \fB~InstanceResourceManager\fP ()"
.br
.ti -1c
.RI "\fBNodeID\fP \fBRegister\fP ()"
.br
.ti -1c
.RI "void \fBReportStorageBudget\fP (\fBStorageBudgetMessage\fP &)"
.br
.ti -1c
.RI "void \fBsetStorageBudget\fP (unsigned long memory, unsigned long disk)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Theron::Framework * \fBframework_\fP"
.br
.ti -1c
.RI "\fBLogging\fP * \fBlogging_\fP"
.br
.ti -1c
.RI "\fBCPUResourceManager\fP \fBcpu_resource_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "InstanceResourceManager::InstanceResourceManager ()"

.PP
References framework_, Environment::getInstance(), and logging_\&.
.SS "InstanceResourceManager::~InstanceResourceManager ()\fC [virtual]\fP"

.PP
References framework_, and logging_\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBNodeID\fP InstanceResourceManager::Register ()"

.PP
References Logging::elog(), framework_, Environment::getInstance(), Environment::getIp(), Environment::getPort(), Logging::log(), logging_, and TimeOutReceiver::TimeOutWait()\&.
.PP
Referenced by Environment::initializeResourceManager()\&.
.SS "void InstanceResourceManager::ReportStorageBudget (\fBStorageBudgetMessage\fP &message)"

.PP
References framework_, and ResourceManagerMasterName\&.
.PP
Referenced by BlockManager::initialize()\&.
.SS "void InstanceResourceManager::setStorageBudget (unsigned longmemory, unsigned longdisk)"

.SH "Member Data Documentation"
.PP 
.SS "\fBCPUResourceManager\fP InstanceResourceManager::cpu_resource_\fC [private]\fP"

.SS "Theron::Framework* InstanceResourceManager::framework_\fC [private]\fP"

.PP
Referenced by InstanceResourceManager(), Register(), ReportStorageBudget(), and ~InstanceResourceManager()\&.
.SS "\fBLogging\fP* InstanceResourceManager::logging_\fC [private]\fP"

.PP
Referenced by InstanceResourceManager(), Register(), and ~InstanceResourceManager()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
