.TH "InstanceResourceManager" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InstanceResourceManager \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "NodeID \fBRegister\fP ()"
.br
.ti -1c
.RI "void \fBReportStorageBudget\fP (\fBStorageBudgetMessage\fP &)"
.br
.ti -1c
.RI "void \fBsetStorageBudget\fP (unsigned long memory, unsigned long disk)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
