.TH "InstanceResourceInfo" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InstanceResourceInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fBslave_ip_\fP"
.br
.ti -1c
.RI "\fBmemory_info\fP \fBmemory\fP"
.br
.ti -1c
.RI "\fBdisk_info\fP \fBdisk\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBResourceManagerMaster\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
