.TH "IteratorExecutorMaster" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IteratorExecutorMaster \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IteratorExecutorMaster\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIteratorExecutorMaster\fP ()"
.br
.ti -1c
.RI "virtual \fB~IteratorExecutorMaster\fP ()"
.br
.ti -1c
.RI "bool \fBExecuteBlockStreamIteratorsOnSites\fP (\fBPhysicalOperatorBase\fP *it, std::vector< std::string > ip_list)"
.br
.ti -1c
.RI "bool \fBExecuteBlockStreamIteratorsOnSite\fP (\fBPhysicalOperatorBase\fP *it, \fBNodeID\fP target_ip)"
.br
.ti -1c
.RI "bool \fBPropogation\fP (const int, std::string target)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBIteratorExecutorMaster\fP * \fBgetInstance\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Theron::EndPoint * \fBendpoint\fP"
.br
.ti -1c
.RI "Theron::Framework * \fBframework\fP"
.br
.ti -1c
.RI "\fBLogging\fP * \fBlogging_\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static \fBIteratorExecutorMaster\fP * \fB_instance\fP =0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IteratorExecutorMaster::IteratorExecutorMaster ()"

.PP
References _instance, endpoint, framework, Environment::getEndPoint(), Environment::getInstance(), and logging_\&.
.PP
Referenced by getInstance()\&.
.SS "IteratorExecutorMaster::~IteratorExecutorMaster ()\fC [virtual]\fP"

.PP
References _instance, and framework\&.
.SH "Member Function Documentation"
.PP 
.SS "bool IteratorExecutorMaster::ExecuteBlockStreamIteratorsOnSite (\fBPhysicalOperatorBase\fP *it, \fBNodeID\fPtarget_ip)"

.PP
References IteratorExecutorSlave::createNewThreadAndRun(), PhysicalQueryPlan::deserialize4K(), framework, Environment::getInstance(), Environment::getIteratorExecutorSlave(), Logging::log(), logging_, and PhysicalQueryPlan::serialize4K()\&.
.PP
Referenced by claims::physical_operator::ExchangeMerger::SerializeAndSendPlan()\&.
.SS "bool IteratorExecutorMaster::ExecuteBlockStreamIteratorsOnSites (\fBPhysicalOperatorBase\fP *it, std::vector< std::string >ip_list)"

.PP
References Logging::elog(), endpoint, framework, Logging::log(), logging_, PhysicalQueryPlan::serialize4K(), and TimeOutReceiver::TimeOutWait()\&.
.SS "\fBIteratorExecutorMaster\fP * IteratorExecutorMaster::getInstance ()\fC [static]\fP"

.PP
References _instance, and IteratorExecutorMaster()\&.
.PP
Referenced by IteratorExecutorSlave::ExecuteIteratorActor::progation(), claims::physical_operator::ExchangeMerger::SerializeAndSendPlan(), and testIteratorExecutor()\&.
.SS "bool IteratorExecutorMaster::Propogation (const intcount, std::stringtarget)"

.PP
References framework\&.
.PP
Referenced by IteratorExecutorSlave::ExecuteIteratorActor::progation(), and testIteratorExecutor()\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBIteratorExecutorMaster\fP * IteratorExecutorMaster::_instance =0\fC [static]\fP, \fC [private]\fP"

.PP
Referenced by getInstance(), IteratorExecutorMaster(), and ~IteratorExecutorMaster()\&.
.SS "Theron::EndPoint* IteratorExecutorMaster::endpoint\fC [private]\fP"

.PP
Referenced by ExecuteBlockStreamIteratorsOnSites(), and IteratorExecutorMaster()\&.
.SS "Theron::Framework* IteratorExecutorMaster::framework\fC [private]\fP"

.PP
Referenced by ExecuteBlockStreamIteratorsOnSite(), ExecuteBlockStreamIteratorsOnSites(), IteratorExecutorMaster(), Propogation(), and ~IteratorExecutorMaster()\&.
.SS "\fBLogging\fP* IteratorExecutorMaster::logging_\fC [private]\fP"

.PP
Referenced by ExecuteBlockStreamIteratorsOnSite(), ExecuteBlockStreamIteratorsOnSites(), and IteratorExecutorMaster()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
