.TH "IteratorExecutorMaster" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IteratorExecutorMaster \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBExecuteBlockStreamIteratorsOnSites\fP (\fBBlockStreamIteratorBase\fP *it, std::vector< std::string > ip_list)"
.br
.ti -1c
.RI "bool \fBExecuteBlockStreamIteratorsOnSite\fP (\fBBlockStreamIteratorBase\fP *it, NodeID target_ip)"
.br
.ti -1c
.RI "bool \fBPropogation\fP (const int, std::string target)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBIteratorExecutorMaster\fP * \fBgetInstance\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
