.TH "IteratorExecutorSlave::ExecuteIteratorActor" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IteratorExecutorSlave::ExecuteIteratorActor \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IteratorExecutorSlave\&.h>\fP
.PP
Inherits Actor\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExecuteIteratorActor\fP (\fBIteratorExecutorSlave\fP *\fBies\fP, Theron::Framework &\fBframework\fP, const char *const slaveID)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBHandler256\fP (const \fBMessage256\fP &message, const Theron::Address from)"
.br
.ti -1c
.RI "void \fBHandler4K\fP (const \fBMessage4K\fP &message, const Theron::Address from)"
.br
.ti -1c
.RI "void \fBprogation\fP (const int &message, const Theron::Address from)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBIteratorExecutorSlave\fP * \fBies\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IteratorExecutorSlave::ExecuteIteratorActor::ExecuteIteratorActor (\fBIteratorExecutorSlave\fP *ies, Theron::Framework &framework, const char *constslaveID)"

.PP
References Handler256(), Handler4K(), and progation()\&.
.SH "Member Function Documentation"
.PP 
.SS "void IteratorExecutorSlave::ExecuteIteratorActor::Handler256 (const \fBMessage256\fP &message, const Theron::Addressfrom)\fC [private]\fP"

.PP
References PhysicalQueryPlan::deserialize(), and PhysicalQueryPlan::run()\&.
.PP
Referenced by ExecuteIteratorActor()\&.
.SS "void IteratorExecutorSlave::ExecuteIteratorActor::Handler4K (const \fBMessage4K\fP &message, const Theron::Addressfrom)\fC [private]\fP"

.PP
References PhysicalQueryPlan::deserialize4K()\&.
.PP
Referenced by ExecuteIteratorActor()\&.
.SS "void IteratorExecutorSlave::ExecuteIteratorActor::progation (const int &message, const Theron::Addressfrom)\fC [private]\fP"

.PP
References IteratorExecutorMaster::getInstance(), and IteratorExecutorMaster::Propogation()\&.
.PP
Referenced by ExecuteIteratorActor()\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBIteratorExecutorSlave\fP* IteratorExecutorSlave::ExecuteIteratorActor::ies\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
