.TH "Json::ValueIteratorBase" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Json::ValueIteratorBase \- 
.PP
base class for \fBValue\fP iterators\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.h>\fP
.PP
Inherited by \fBJson::ValueConstIterator\fP, and \fBJson::ValueIterator\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef 
.br
std::bidirectional_iterator_tag \fBiterator_category\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBsize_t\fP"
.br
.ti -1c
.RI "typedef int \fBdifference_type\fP"
.br
.ti -1c
.RI "typedef \fBValueIteratorBase\fP \fBSelfType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBValueIteratorBase\fP ()"
.br
.ti -1c
.RI "\fBValueIteratorBase\fP (const Value::ObjectValues::iterator &current)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBSelfType\fP &other) const "
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBSelfType\fP &other) const "
.br
.ti -1c
.RI "\fBdifference_type\fP \fBoperator-\fP (const \fBSelfType\fP &other) const "
.br
.ti -1c
.RI "\fBValue\fP \fBkey\fP () const "
.br
.ti -1c
.RI "\fBUInt\fP \fBindex\fP () const "
.br
.RI "\fIReturn the index of the referenced \fBValue\fP\&. -1 if it is not an arrayValue\&. \fP"
.ti -1c
.RI "const char * \fBmemberName\fP () const "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBValue\fP & \fBderef\fP () const "
.br
.ti -1c
.RI "void \fBincrement\fP ()"
.br
.ti -1c
.RI "void \fBdecrement\fP ()"
.br
.ti -1c
.RI "\fBdifference_type\fP \fBcomputeDistance\fP (const \fBSelfType\fP &other) const "
.br
.ti -1c
.RI "bool \fBisEqual\fP (const \fBSelfType\fP &other) const "
.br
.ti -1c
.RI "void \fBcopy\fP (const \fBSelfType\fP &other)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Value::ObjectValues::iterator \fBcurrent_\fP"
.br
.ti -1c
.RI "bool \fBisNull_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
base class for \fBValue\fP iterators\&. 


.SH "Member Typedef Documentation"
.PP 
.SS "typedef int \fBJson::ValueIteratorBase::difference_type\fP"

.SS "typedef std::bidirectional_iterator_tag \fBJson::ValueIteratorBase::iterator_category\fP"

.SS "typedef \fBValueIteratorBase\fP \fBJson::ValueIteratorBase::SelfType\fP"

.SS "typedef unsigned int \fBJson::ValueIteratorBase::size_t\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "Json::ValueIteratorBase::ValueIteratorBase ()"

.SS "Json::ValueIteratorBase::ValueIteratorBase (const Value::ObjectValues::iterator &current)\fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBValueIteratorBase::difference_type\fP Json::ValueIteratorBase::computeDistance (const \fBSelfType\fP &other) const\fC [protected]\fP"

.PP
References current_, and isNull_\&.
.SS "void Json::ValueIteratorBase::copy (const \fBSelfType\fP &other)\fC [protected]\fP"

.PP
References current_, and isNull_\&.
.PP
Referenced by Json::ValueConstIterator::operator=(), and Json::ValueIterator::operator=()\&.
.SS "void Json::ValueIteratorBase::decrement ()\fC [protected]\fP"

.PP
References current_\&.
.SS "\fBValue\fP & Json::ValueIteratorBase::deref () const\fC [protected]\fP"

.PP
References current_\&.
.SS "void Json::ValueIteratorBase::increment ()\fC [protected]\fP"

.PP
References current_\&.
.SS "\fBUInt\fP Json::ValueIteratorBase::index () const"

.PP
Return the index of the referenced \fBValue\fP\&. -1 if it is not an arrayValue\&. 
.PP
References Json::Value::CZString::c_str(), and Json::Value::CZString::index()\&.
.SS "bool Json::ValueIteratorBase::isEqual (const \fBSelfType\fP &other) const\fC [protected]\fP"

.PP
References current_, and isNull_\&.
.SS "\fBValue\fP Json::ValueIteratorBase::key () const"
Return either the index or the member name of the referenced value as a \fBValue\fP\&. 
.PP
References Json::Value::CZString::c_str(), Json::Value::CZString::index(), Json::Value::CZString::isStaticString(), and memberName()\&.
.SS "const char * Json::ValueIteratorBase::memberName () const"
Return the member name of the referenced \fBValue\fP\&. '' if it is not an objectValue\&. 
.PP
Referenced by key()\&.
.SS "bool Json::ValueIteratorBase::operator!= (const \fBSelfType\fP &other) const\fC [inline]\fP"

.SS "\fBdifference_type\fP Json::ValueIteratorBase::operator- (const \fBSelfType\fP &other) const\fC [inline]\fP"

.SS "bool Json::ValueIteratorBase::operator== (const \fBSelfType\fP &other) const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "Value::ObjectValues::iterator Json::ValueIteratorBase::current_\fC [private]\fP"

.PP
Referenced by computeDistance(), copy(), decrement(), deref(), increment(), and isEqual()\&.
.SS "bool Json::ValueIteratorBase::isNull_\fC [private]\fP"

.PP
Referenced by computeDistance(), copy(), and isEqual()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
