.TH "Json::BatchAllocator< AllocatedType, objectPerAllocation >" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Json::BatchAllocator< AllocatedType, objectPerAllocation > \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBBatchInfo\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBatchAllocator\fP (unsigned int objectsPerPage=255)"
.br
.ti -1c
.RI "\fB~BatchAllocator\fP ()"
.br
.ti -1c
.RI "AllocatedType * \fBallocate\fP ()"
.br
.ti -1c
.RI "void \fBrelease\fP (AllocatedType *object)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBBatchAllocator\fP (const \fBBatchAllocator\fP &)"
.br
.ti -1c
.RI "void \fBoperator=\fP (const \fBBatchAllocator\fP &)"
.br
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "static \fBBatchInfo\fP * \fBallocateBatch\fP (unsigned int objectsPerPage)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBBatchInfo\fP * \fBbatches_\fP"
.br
.ti -1c
.RI "\fBBatchInfo\fP * \fBcurrentBatch_\fP"
.br
.ti -1c
.RI "AllocatedType * \fBfreeHead_\fP"
.br
.RI "\fIHead of a single linked list within the allocated space of freeed object\&. \fP"
.ti -1c
.RI "unsigned int \fBobjectsPerPage_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename AllocatedType , const unsigned int objectPerAllocation> \fBJson::BatchAllocator\fP< AllocatedType, objectPerAllocation >::\fBBatchAllocator\fP (unsigned intobjectsPerPage = \fC255\fP)\fC [inline]\fP"

.PP
References Json::BatchAllocator< AllocatedType, objectPerAllocation >::allocateBatch(), Json::BatchAllocator< AllocatedType, objectPerAllocation >::batches_, and Json::BatchAllocator< AllocatedType, objectPerAllocation >::currentBatch_\&.
.SS "template<typename AllocatedType , const unsigned int objectPerAllocation> \fBJson::BatchAllocator\fP< AllocatedType, objectPerAllocation >::~\fBBatchAllocator\fP ()\fC [inline]\fP"

.PP
References Json::BatchAllocator< AllocatedType, objectPerAllocation >::batches_, and Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchInfo::next_\&.
.SS "template<typename AllocatedType , const unsigned int objectPerAllocation> \fBJson::BatchAllocator\fP< AllocatedType, objectPerAllocation >::\fBBatchAllocator\fP (const \fBBatchAllocator\fP< AllocatedType, objectPerAllocation > &)\fC [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename AllocatedType , const unsigned int objectPerAllocation> AllocatedType* \fBJson::BatchAllocator\fP< AllocatedType, objectPerAllocation >::allocate ()\fC [inline]\fP"
allocate space for an array of objectPerAllocation object\&. 
.PP
\fBWarning:\fP
.RS 4
it is the responsability of the caller to call objects constructors\&. 
.RE
.PP

.PP
References Json::BatchAllocator< AllocatedType, objectPerAllocation >::allocateBatch(), Json::BatchAllocator< AllocatedType, objectPerAllocation >::batches_, Json::BatchAllocator< AllocatedType, objectPerAllocation >::currentBatch_, Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchInfo::end_, Json::BatchAllocator< AllocatedType, objectPerAllocation >::freeHead_, Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchInfo::next_, Json::BatchAllocator< AllocatedType, objectPerAllocation >::objectsPerPage_, and Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchInfo::used_\&.
.SS "template<typename AllocatedType , const unsigned int objectPerAllocation> static \fBBatchInfo\fP* \fBJson::BatchAllocator\fP< AllocatedType, objectPerAllocation >::allocateBatch (unsigned intobjectsPerPage)\fC [inline]\fP, \fC [static]\fP, \fC [private]\fP"

.PP
References Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchInfo::next_, and Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchInfo::used_\&.
.PP
Referenced by Json::BatchAllocator< AllocatedType, objectPerAllocation >::allocate(), and Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchAllocator()\&.
.SS "template<typename AllocatedType , const unsigned int objectPerAllocation> void \fBJson::BatchAllocator\fP< AllocatedType, objectPerAllocation >::operator= (const \fBBatchAllocator\fP< AllocatedType, objectPerAllocation > &)\fC [private]\fP"

.SS "template<typename AllocatedType , const unsigned int objectPerAllocation> void \fBJson::BatchAllocator\fP< AllocatedType, objectPerAllocation >::release (AllocatedType *object)\fC [inline]\fP"
Release the object\&. 
.PP
\fBWarning:\fP
.RS 4
it is the responsability of the caller to actually destruct the object\&. 
.RE
.PP

.PP
References Json::BatchAllocator< AllocatedType, objectPerAllocation >::freeHead_\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename AllocatedType , const unsigned int objectPerAllocation> \fBBatchInfo\fP* \fBJson::BatchAllocator\fP< AllocatedType, objectPerAllocation >::batches_\fC [private]\fP"

.PP
Referenced by Json::BatchAllocator< AllocatedType, objectPerAllocation >::allocate(), Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchAllocator(), and Json::BatchAllocator< AllocatedType, objectPerAllocation >::~BatchAllocator()\&.
.SS "template<typename AllocatedType , const unsigned int objectPerAllocation> \fBBatchInfo\fP* \fBJson::BatchAllocator\fP< AllocatedType, objectPerAllocation >::currentBatch_\fC [private]\fP"

.PP
Referenced by Json::BatchAllocator< AllocatedType, objectPerAllocation >::allocate(), and Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchAllocator()\&.
.SS "template<typename AllocatedType , const unsigned int objectPerAllocation> AllocatedType* \fBJson::BatchAllocator\fP< AllocatedType, objectPerAllocation >::freeHead_\fC [private]\fP"

.PP
Head of a single linked list within the allocated space of freeed object\&. 
.PP
Referenced by Json::BatchAllocator< AllocatedType, objectPerAllocation >::allocate(), and Json::BatchAllocator< AllocatedType, objectPerAllocation >::release()\&.
.SS "template<typename AllocatedType , const unsigned int objectPerAllocation> unsigned int \fBJson::BatchAllocator\fP< AllocatedType, objectPerAllocation >::objectsPerPage_\fC [private]\fP"

.PP
Referenced by Json::BatchAllocator< AllocatedType, objectPerAllocation >::allocate()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
