.TH "Json" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Json \- 
.PP
JSON (JavaScript Object Notation)\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFeatures\fP"
.br
.RI "\fIConfiguration passed to reader and writer\&. This configuration object can be used to force the \fBReader\fP or \fBWriter\fP to behave in a standard conforming way\&. \fP"
.ti -1c
.RI "class \fBStaticString\fP"
.br
.RI "\fILightweight wrapper to tag static string\&. \fP"
.ti -1c
.RI "class \fBValue\fP"
.br
.RI "\fIRepresents a \fCJSON\fP value\&. \fP"
.ti -1c
.RI "class \fBPathArgument\fP"
.br
.RI "\fIExperimental and untested: represents an element of the 'path' to access a node\&. \fP"
.ti -1c
.RI "class \fBPath\fP"
.br
.RI "\fIExperimental and untested: represents a 'path' to access a node\&. \fP"
.ti -1c
.RI "class \fBValueIteratorBase\fP"
.br
.RI "\fIbase class for \fBValue\fP iterators\&. \fP"
.ti -1c
.RI "class \fBValueConstIterator\fP"
.br
.RI "\fIconst iterator for object and array value\&. \fP"
.ti -1c
.RI "class \fBValueIterator\fP"
.br
.RI "\fIIterator for object and array value\&. \fP"
.ti -1c
.RI "class \fBReader\fP"
.br
.RI "\fIUnserialize a \fCJSON\fP document into a \fBValue\fP\&. \fP"
.ti -1c
.RI "class \fBWriter\fP"
.br
.RI "\fIAbstract class for writers\&. \fP"
.ti -1c
.RI "class \fBFastWriter\fP"
.br
.RI "\fIOutputs a \fBValue\fP in \fCJSON\fP format without formatting (not human friendly)\&. \fP"
.ti -1c
.RI "class \fBStyledWriter\fP"
.br
.RI "\fIWrites a \fBValue\fP in \fCJSON\fP format in a human friendly way\&. \fP"
.ti -1c
.RI "class \fBStyledStreamWriter\fP"
.br
.RI "\fIWrites a \fBValue\fP in \fCJSON\fP format in a human friendly way, to a stream rather than to a string\&. \fP"
.ti -1c
.RI "class \fBBatchAllocator\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int \fBInt\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBUInt\fP"
.br
.ti -1c
.RI "typedef long long int \fBInt64\fP"
.br
.ti -1c
.RI "typedef unsigned long long int \fBUInt64\fP"
.br
.ti -1c
.RI "typedef Int64 \fBLargestInt\fP"
.br
.ti -1c
.RI "typedef UInt64 \fBLargestUInt\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBArrayIndex\fP"
.br
.ti -1c
.RI "typedef char \fBUIntToStringBuffer\fP [\fBuintToStringBufferSize\fP]"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBValueType\fP { \fBnullValue\fP = 0, \fBintValue\fP, \fBuintValue\fP, \fBrealValue\fP, \fBstringValue\fP, \fBbooleanValue\fP, \fBarrayValue\fP, \fBobjectValue\fP }"
.br
.RI "\fIType of the value held by a Value object\&. \fP"
.ti -1c
.RI "enum \fBCommentPlacement\fP { \fBcommentBefore\fP = 0, \fBcommentAfterOnSameLine\fP, \fBcommentAfter\fP, \fBnumberOfCommentPlacement\fP }"
.br
.ti -1c
.RI "enum { \fBuintToStringBufferSize\fP = 3 * sizeof(LargestUInt) + 1 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "JSON_API std::istream & \fBoperator>>\fP (std::istream &, \fBValue\fP &)"
.br
.RI "\fIRead from 'sin' into 'root'\&. \fP"
.ti -1c
.RI "std::string JSON_API \fBvalueToString\fP (Int value)"
.br
.ti -1c
.RI "std::string JSON_API \fBvalueToString\fP (UInt value)"
.br
.ti -1c
.RI "std::string JSON_API \fBvalueToString\fP (LargestInt value)"
.br
.ti -1c
.RI "std::string JSON_API \fBvalueToString\fP (LargestUInt value)"
.br
.ti -1c
.RI "std::string JSON_API \fBvalueToString\fP (double value)"
.br
.ti -1c
.RI "std::string JSON_API \fBvalueToString\fP (bool value)"
.br
.ti -1c
.RI "std::string JSON_API \fBvalueToQuotedString\fP (const char *value)"
.br
.ti -1c
.RI "JSON_API std::ostream & \fBoperator<<\fP (std::ostream &, const \fBValue\fP &root)"
.br
.RI "\fIOutput using the \fBStyledStreamWriter\fP\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const unsigned char & \fBkNullRef\fP = kNull[0]"
.br
.in -1c
.SH "Detailed Description"
.PP 
JSON (JavaScript Object Notation)\&. 
.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIuintToStringBufferSize \fP\fP
Constant that specify the size of the buffer that must be passed to uintToString\&. 
.SS "enum \fBJson::CommentPlacement\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIcommentBefore \fP\fP
a comment placed on the line before a value 
.TP
\fB\fIcommentAfterOnSameLine \fP\fP
a comment just after a value on the same line 
.TP
\fB\fIcommentAfter \fP\fP
a comment on the line after a value (only make sense for 
.TP
\fB\fInumberOfCommentPlacement \fP\fP
root value) 
.SS "enum \fBJson::ValueType\fP"

.PP
Type of the value held by a \fBValue\fP object\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fInullValue \fP\fP
'null' value 
.TP
\fB\fIintValue \fP\fP
signed integer value 
.TP
\fB\fIuintValue \fP\fP
unsigned integer value 
.TP
\fB\fIrealValue \fP\fP
double value 
.TP
\fB\fIstringValue \fP\fP
UTF-8 string value\&. 
.TP
\fB\fIbooleanValue \fP\fP
bool value 
.TP
\fB\fIarrayValue \fP\fP
array value (ordered list) 
.TP
\fB\fIobjectValue \fP\fP
object value (collection of name/value pairs)\&. 
.SH "Function Documentation"
.PP 
.SS "std::ostream & Json::operator<< (std::ostream &sout, const Value &root)"

.PP
Output using the \fBStyledStreamWriter\fP\&. 
.PP
\fBSee Also:\fP
.RS 4
\fBJson::operator>>()\fP 
.RE
.PP

.PP
References Json::StyledStreamWriter::write()\&.
.SS "std::istream & Json::operator>> (std::istream &sin, Value &root)"

.PP
Read from 'sin' into 'root'\&. Always keep comments from the input JSON\&.
.PP
This can be used to read a file into a particular sub-object\&. For example: 
.PP
.nf
Json::Value root;
cin >> root["dir"]["file"];
cout << root;

.fi
.PP
 Result: 
.PP
.nf
{
"dir": {
    "file": {
    // The input stream JSON would be nested here.
    }
}
}

.fi
.PP
 
.PP
\fBExceptions:\fP
.RS 4
\fIstd::exception\fP on parse error\&. 
.RE
.PP
\fBSee Also:\fP
.RS 4
\fBJson::operator<<()\fP 
.RE
.PP

.PP
References Json::Reader::getFormattedErrorMessages(), and Json::Reader::parse()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
