.TH "Json::Writer" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Json::Writer \- 
.PP
Abstract class for writers\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.h>\fP
.PP
Inherited by \fBJson::FastWriter\fP, and \fBJson::StyledWriter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual std::string \fBwrite\fP (const \fBValue\fP &root)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Abstract class for writers\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
