.TH "Length" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Length \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sql_node_struct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnodetype\fP \fBtype\fP"
.br
.ti -1c
.RI "int \fBdata1\fP"
.br
.ti -1c
.RI "int \fBdata2\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int Length::data1"

.PP
Referenced by CreateTable(), and newLength()\&.
.SS "int Length::data2"

.PP
Referenced by newLength()\&.
.SS "\fBnodetype\fP Length::type"

.PP
Referenced by newLength()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
