.TH "Loadtable_stmt" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Loadtable_stmt \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sql_node_struct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnodetype\fP \fBtype\fP"
.br
.ti -1c
.RI "char * \fBtable_name\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBpath\fP"
.br
.ti -1c
.RI "char * \fBcolumn_separator\fP"
.br
.ti -1c
.RI "char * \fBtuple_separator\fP"
.br
.ti -1c
.RI "double \fBsample\fP"
.br
.ti -1c
.RI "int \fBmode\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char* Loadtable_stmt::column_separator"

.PP
Referenced by LoadData(), and newLoadTable()\&.
.SS "int Loadtable_stmt::mode"

.PP
Referenced by LoadData(), and newLoadTable()\&.
.SS "\fBNode\fP* Loadtable_stmt::path"

.PP
Referenced by LoadData(), and newLoadTable()\&.
.SS "double Loadtable_stmt::sample"

.PP
Referenced by LoadData(), and newLoadTable()\&.
.SS "char* Loadtable_stmt::table_name"

.PP
Referenced by LoadData(), and newLoadTable()\&.
.SS "char* Loadtable_stmt::tuple_separator"

.PP
Referenced by LoadData(), and newLoadTable()\&.
.SS "\fBnodetype\fP Loadtable_stmt::type"

.PP
Referenced by newLoadTable()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
