.TH "LocalStageEndPoint" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LocalStageEndPoint \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <expander_tracker\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLocalStageEndPoint\fP (\fBendpoint_type\fP tp, std::string name='Not Given', MonitorableBuffer *buffer_handle=0)"
.br
.ti -1c
.RI "\fBLocalStageEndPoint\fP ()"
.br
.ti -1c
.RI "\fBLocalStageEndPoint\fP (const \fBLocalStageEndPoint\fP &r)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBendpoint_type\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBMonitorableBuffer\fP * \fBmonitorable_buffer\fP"
.br
.ti -1c
.RI "std::string \fBend_point_name\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Local \fBlocal_stage\fP endpoint refers to the start or the end of a stage within a segment\&. It could be either exchange, state, or expander\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LocalStageEndPoint::LocalStageEndPoint (\fBendpoint_type\fPtp, std::stringname = \fC'Not Given'\fP, \fBMonitorableBuffer\fP *buffer_handle = \fC0\fP)\fC [inline]\fP"

.SS "LocalStageEndPoint::LocalStageEndPoint ()\fC [inline]\fP"

.SS "LocalStageEndPoint::LocalStageEndPoint (const \fBLocalStageEndPoint\fP &r)\fC [inline]\fP"

.PP
References end_point_name, monitorable_buffer, and type\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string LocalStageEndPoint::end_point_name"

.PP
Referenced by LocalStageEndPoint(), and local_stage::print()\&.
.SS "\fBMonitorableBuffer\fP* LocalStageEndPoint::monitorable_buffer"

.PP
Referenced by ExpanderTracker::decideExpandingOrShrinking(), ExpanderTracker::getSegmentStatus(), local_stage::local_stage(), and LocalStageEndPoint()\&.
.SS "\fBendpoint_type\fP LocalStageEndPoint::type"

.PP
Referenced by ExpanderTracker::ExpanderStatus::addNewEndpoint(), and LocalStageEndPoint()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
