.TH "LocalStageEndPoint" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LocalStageEndPoint \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ExpanderTracker\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLocalStageEndPoint\fP (endpoint_type tp, std::string name='Not Given', MonitorableBuffer *buffer_handle=0)"
.br
.ti -1c
.RI "\fBLocalStageEndPoint\fP (const \fBLocalStageEndPoint\fP &r)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "endpoint_type \fBtype\fP"
.br
.ti -1c
.RI "\fBMonitorableBuffer\fP * \fBmonitorable_buffer\fP"
.br
.ti -1c
.RI "std::string \fBend_point_name\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Local \fBlocal_stage\fP endpoint refers to the start or the end of a stage within a segment\&. It could be either exchange, state, or expander\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
