.TH "LocalDiskConnector" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LocalDiskConnector \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LocalDiskConnector\&.h>\fP
.PP
Inherits \fBConnector\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLocalDiskConnector\fP (vector< vector< string > > hdfs_writepath)"
.br
.ti -1c
.RI "virtual \fB~LocalDiskConnector\fP ()"
.br
.ti -1c
.RI "bool \fBopenFiles\fP (\fBopen_flag\fP open_flag_)"
.br
.ti -1c
.RI "bool \fBcloseFiles\fP ()"
.br
.ti -1c
.RI "int \fBflush\fP (unsigned projection_offset, unsigned partition_offset, void *source, unsigned length)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::vector< std::vector< int > > \fBfile_handles_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LocalDiskConnector::LocalDiskConnector (vector< vector< string > >hdfs_writepath)"

.SS "LocalDiskConnector::~LocalDiskConnector ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool LocalDiskConnector::closeFiles ()\fC [virtual]\fP"

.PP
Implements \fBConnector\fP\&.
.PP
References file_handles_, and FileClose()\&.
.SS "int LocalDiskConnector::flush (unsignedprojection_offset, unsignedpartition_offset, void *source, unsignedlength)\fC [virtual]\fP"

.PP
Implements \fBConnector\fP\&.
.PP
References file_handles_\&.
.SS "bool LocalDiskConnector::openFiles (\fBopen_flag\fPopen_flag_)\fC [virtual]\fP"

.PP
Implements \fBConnector\fP\&.
.PP
References APPENDD, CREATEE, file_handles_, FileOpen, and Connector::writepath\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<std::vector<int> > LocalDiskConnector::file_handles_\fC [protected]\fP"

.PP
Referenced by closeFiles(), flush(), and openFiles()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
