.TH "LogicalIndexScan" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LogicalIndexScan \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LogicalIndexScan\&.h>\fP
.PP
Inherits \fBclaims::logical_operator::LogicalOperator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLogicalIndexScan\fP ()"
.br
.ti -1c
.RI "\fBLogicalIndexScan\fP (\fBProjectionID\fP projection_id, \fBAttribute\fP index_attr, vector< \fBIndexScanIterator::query_range\fP > q_range)"
.br
.ti -1c
.RI "virtual \fB~LogicalIndexScan\fP ()"
.br
.ti -1c
.RI "\fBPlanContext\fP \fBGetPlanContext\fP ()"
.br
.ti -1c
.RI "\fBPhysicalOperatorBase\fP * \fBGetPhysicalPlan\fP (const unsigned &blocksize)"
.br
.ti -1c
.RI "bool \fBGetOptimalPhysicalPlan\fP (\fBRequirement\fP requirement, \fBPhysicalPlanDescriptor\fP &physical_plan_descriptor, const unsigned &\fBblock_size\fP=4096 *1024)"
.br
.ti -1c
.RI "void \fBPrint\fP (int level=0) const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBProjectionID\fP \fBprojection_id_\fP"
.br
.ti -1c
.RI "\fBAttribute\fP \fBindex_attr_\fP"
.br
.ti -1c
.RI "vector
.br
< \fBIndexScanIterator::query_range\fP > \fBquery_range_\fP"
.br
.ti -1c
.RI "\fBProjectionDescriptor\fP * \fBscan_projection_\fP"
.br
.ti -1c
.RI "\fBPlanContext\fP \fBdataflow_\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LogicalIndexScan::LogicalIndexScan ()"

.SS "LogicalIndexScan::LogicalIndexScan (\fBProjectionID\fPprojection_id, \fBAttribute\fPindex_attr, vector< \fBIndexScanIterator::query_range\fP >q_range)"

.PP
References Catalog::getInstance(), TableDescriptor::getProjectoin(), Catalog::getTable(), index_attr_, projection_id_, ProjectionID::projection_off, scan_projection_, and Attribute::table_id_\&.
.SS "LogicalIndexScan::~LogicalIndexScan ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool LogicalIndexScan::GetOptimalPhysicalPlan (\fBRequirement\fPrequirement, \fBPhysicalPlanDescriptor\fP &physical_plan_descriptor, const unsigned &block_size = \fC4096 * 1024\fP)\fC [virtual]\fP"
get the optimal Physical plan that meets the requirement\&. 
.PP
\fBReturns:\fP
.RS 4
true if find physical plan that meets the requirement and store the physical plan and its corresponding information in physical_plan_descriptor\&. 
.RE
.PP

.PP
Reimplemented from \fBclaims::logical_operator::LogicalOperator\fP\&.
.SS "\fBPhysicalOperatorBase\fP * LogicalIndexScan::GetPhysicalPlan (const unsigned &)\fC [virtual]\fP"
generate the iterator tree based on the computed plan_context\&. Hence, this function can only be called after the calling of \fBGetPlanContext()\fP\&. 
.PP
Implements \fBclaims::logical_operator::LogicalOperator\fP\&.
.PP
References claims::logical_operator::PlanContext::attribute_list_, IndexScanIterator::State::block_size_, dataflow_, IndexManager::getIndexID(), IndexManager::getInstance(), claims::logical_operator::LogicalOperator::GetSchema(), index_attr_, IndexScanIterator::State::index_id_, projection_id_, IndexScanIterator::State::projection_id_, query_range_, IndexScanIterator::State::query_range_, and IndexScanIterator::State::schema_\&.
.PP
Referenced by test_logical_csb_index_building()\&.
.SS "\fBPlanContext\fP LogicalIndexScan::GetPlanContext ()\fC [virtual]\fP"
get the plan context which describes the property of the data after having executed corresponding operator\&. 
.PP
Implements \fBclaims::logical_operator::LogicalOperator\fP\&.
.PP
References ProjectionDescriptor::AllPartitionBound(), claims::logical_operator::PlanContext::attribute_list_, ProjectionBinding::BindingEntireProjection(), claims::logical_operator::PlanContext::commu_cost_, dataflow_, DESIRIABLE_STORAGE_LEVEL, ProjectionDescriptor::getAttributeList(), Catalog::getBindingModele(), Catalog::getInstance(), ProjectionDescriptor::getPartitioner(), claims::logical_operator::PlanContext::plan_partitioner_, and scan_projection_\&.
.SS "void LogicalIndexScan::Print (intlevel = \fC0\fP) const\fC [virtual]\fP"

.PP
Implements \fBclaims::logical_operator::LogicalOperator\fP\&.
.PP
Referenced by test_logical_csb_index_building()\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPlanContext\fP LogicalIndexScan::dataflow_\fC [private]\fP"

.PP
Referenced by GetPhysicalPlan(), and GetPlanContext()\&.
.SS "\fBAttribute\fP LogicalIndexScan::index_attr_\fC [private]\fP"

.PP
Referenced by GetPhysicalPlan(), and LogicalIndexScan()\&.
.SS "\fBProjectionID\fP LogicalIndexScan::projection_id_\fC [private]\fP"

.PP
Referenced by GetPhysicalPlan(), and LogicalIndexScan()\&.
.SS "vector<\fBIndexScanIterator::query_range\fP> LogicalIndexScan::query_range_\fC [private]\fP"

.PP
Referenced by GetPhysicalPlan()\&.
.SS "\fBProjectionDescriptor\fP* LogicalIndexScan::scan_projection_\fC [private]\fP"

.PP
Referenced by GetPlanContext(), and LogicalIndexScan()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
