.TH "Mapping" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mapping \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBatomicPushExpressionMapping\fP (ExpressionMapping &expression_mapping)"
.br
.ti -1c
.RI "ExpressionMapping \fBatomicPopExpressionMapping\fP (int i)"
.br
.ti -1c
.RI "std::vector< ExpressionMapping > \fBgetMapping\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBboost::serialization::access\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
