.TH "MatcherMessage" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MatcherMessage \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMatcherMessage\fP (const char *const filename, const char *const bmi)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBfilenameText\fP [MATCHER_MESSAGE_FILENAME_LEN]"
.br
.ti -1c
.RI "char \fBbmiText\fP [MATCHER_MESSAGE_BMI_LEN]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
