.TH "MatcherRespond" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MatcherRespond \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Message\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMatcherRespond\fP (const char *const text)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBmText\fP [\fBMATCHER_MESSAGE_PROJECT_LEN\fP]"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MatcherRespond::MatcherRespond (const char *consttext)\fC [inline]\fP, \fC [explicit]\fP"

.PP
References MATCHER_MESSAGE_PROJECT_LEN\&.
.SH "Member Data Documentation"
.PP 
.SS "char MatcherRespond::mText[\fBMATCHER_MESSAGE_PROJECT_LEN\fP]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
