.TH "MatcherMessage" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MatcherMessage \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Message\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMatcherMessage\fP (const char *const filename, const char *const bmi)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBfilenameText\fP [\fBMATCHER_MESSAGE_FILENAME_LEN\fP]"
.br
.ti -1c
.RI "char \fBbmiText\fP [\fBMATCHER_MESSAGE_BMI_LEN\fP]"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MatcherMessage::MatcherMessage (const char *constfilename, const char *constbmi)\fC [inline]\fP, \fC [explicit]\fP"

.PP
References MATCHER_MESSAGE_BMI_LEN, and MATCHER_MESSAGE_FILENAME_LEN\&.
.SH "Member Data Documentation"
.PP 
.SS "char MatcherMessage::bmiText[\fBMATCHER_MESSAGE_BMI_LEN\fP]"

.PP
Referenced by BlockManagerMaster::BlockManagerMasterActor::matcherReceiver()\&.
.SS "char MatcherMessage::filenameText[\fBMATCHER_MESSAGE_FILENAME_LEN\fP]"

.PP
Referenced by BlockManagerMaster::BlockManagerMasterActor::matcherReceiver()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
