.TH "Message4K" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Message4K \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Message\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static unsigned \fBCapacity\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBlength\fP"
.br
.ti -1c
.RI "char \fBmessage\fP [4096 *50-sizeof(unsigned)]"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static unsigned Message4K::Capacity ()\fC [inline]\fP, \fC [static]\fP"

.PP
Referenced by Serialize4K()\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned Message4K::length"

.PP
Referenced by Deserialize(), and Serialize4K()\&.
.SS "char Message4K::message[4096 *50-sizeof(unsigned)]"

.PP
Referenced by Deserialize(), and Serialize4K()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
