.TH "ModuloHashFunction" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModuloHashFunction \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hash\&.h>\fP
.PP
Inherits \fBPartitionFunction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModuloHashFunction\fP ()"
.br
.ti -1c
.RI "\fBModuloHashFunction\fP (int min, unsigned int range, unsigned int skipbits)"
.br
.ti -1c
.RI "\fB~ModuloHashFunction\fP ()"
.br
.ti -1c
.RI "unsigned int \fBget_partition_value\fP (const int &value) const "
.br
.ti -1c
.RI "unsigned int \fBget_partition_value\fP (const double &value) const "
.br
.ti -1c
.RI "unsigned int \fBget_partition_value\fP (const unsigned long &value) const "
.br
.ti -1c
.RI "\fBPartitionStyle\fP \fBgetPartitionFashion\fP () const "
.br
.ti -1c
.RI "unsigned int \fBgetNumberOfPartitions\fP () const "
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "template<class Archive > void \fBserialize\fP (Archive &ar, const unsigned int version)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBskipbits_\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBboost::serialization::access\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ModuloHashFunction::ModuloHashFunction ()\fC [inline]\fP"
Skipbits parameter defines number of least-significant bits which will be discarded before computing the hash\&. 
.SS "ModuloHashFunction::ModuloHashFunction (intmin, unsigned intrange, unsigned intskipbits)\fC [inline]\fP"

.PP
References PartitionFunction::k_, and skipbits_\&.
.SS "ModuloHashFunction::~ModuloHashFunction ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "unsigned int ModuloHashFunction::get_partition_value (const int &value) const\fC [inline]\fP, \fC [virtual]\fP"
Return h(x) = x mod k\&. 
.PP
Implements \fBPartitionFunction\fP\&.
.PP
References PartitionFunction::k_, PartitionFunction::min_, and skipbits_\&.
.SS "unsigned int ModuloHashFunction::get_partition_value (const double &value) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBPartitionFunction\fP\&.
.PP
References PartitionFunction::k_, PartitionFunction::min_, and skipbits_\&.
.SS "unsigned int ModuloHashFunction::get_partition_value (const unsigned long &value) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBPartitionFunction\fP\&.
.PP
References PartitionFunction::k_, PartitionFunction::min_, and skipbits_\&.
.SS "unsigned int ModuloHashFunction::getNumberOfPartitions () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBPartitionFunction\fP\&.
.PP
References PartitionFunction::k_, and skipbits_\&.
.SS "\fBPartitionFunction::PartitionStyle\fP ModuloHashFunction::getPartitionFashion () const\fC [virtual]\fP"

.PP
Implements \fBPartitionFunction\fP\&.
.PP
References PartitionFunction::hash_f\&.
.SS "template<class Archive > void ModuloHashFunction::serialize (Archive &ar, const unsigned intversion)\fC [inline]\fP, \fC [private]\fP"

.PP
References skipbits_\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class boost::serialization::access\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "unsigned int ModuloHashFunction::skipbits_\fC [private]\fP"

.PP
Referenced by get_partition_value(), getNumberOfPartitions(), ModuloHashFunction(), and serialize()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
