.TH "NodeAddress" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NodeAddress \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNodeAddress\fP (std::string ip, std::string port)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBNodeAddress\fP &r) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBip\fP"
.br
.ti -1c
.RI "std::string \fBport\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
