.TH "NodeRegisterMessage" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NodeRegisterMessage \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Message\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNodeRegisterMessage\fP (std::string node_ip, unsigned node_port)"
.br
.ti -1c
.RI "void \fBset_ip\fP (std::string _ip)"
.br
.ti -1c
.RI "std::string \fBget_ip\fP () const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBip\fP"
.br
.ti -1c
.RI "unsigned \fBport\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NodeRegisterMessage::NodeRegisterMessage (std::stringnode_ip, unsignednode_port)\fC [inline]\fP, \fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "std::string NodeRegisterMessage::get_ip () const\fC [inline]\fP"

.PP
References add()\&.
.PP
Referenced by ExchangeTracker::AskForSocketConnectionInfo(), and ResourceManagerMaster::ResourceManagerMasterActor::ReceiveNewNodeRegister()\&.
.SS "void NodeRegisterMessage::set_ip (std::string_ip)\fC [inline]\fP"

.PP
Referenced by ExchangeTracker::ExchangeTrackerActor::AskForConnectionInfo()\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned NodeRegisterMessage::ip"

.PP
Referenced by ExchangeTracker::AskForSocketConnectionInfo()\&.
.SS "unsigned NodeRegisterMessage::port"

.PP
Referenced by ExchangeTracker::ExchangeTrackerActor::AskForConnectionInfo(), ExchangeTracker::AskForSocketConnectionInfo(), and ResourceManagerMaster::ResourceManagerMasterActor::ReceiveNewNodeRegister()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
