.TH "NodeConnectionMessage" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NodeConnectionMessage \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Message\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNodeConnectionMessage\fP ()"
.br
.ti -1c
.RI "\fBNodeConnectionMessage\fP (std::string \fBip\fP, std::string \fBport\fP)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBNodeConnectionMessage\fP \fBdeserialize\fP (\fBMessage256\fP message)"
.br
.ti -1c
.RI "static \fBMessage256\fP \fBserialize\fP (\fBNodeConnectionMessage\fP \fBinput\fP)"
.br
.ti -1c
.RI "static \fBNodeConnectionMessage\fP \fBdeserialize4K\fP (\fBMessage4K\fP message)"
.br
.ti -1c
.RI "static \fBMessage4K\fP \fBserialize4K\fP (\fBNodeConnectionMessage\fP \fBinput\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBip\fP"
.br
.ti -1c
.RI "std::string \fBport\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "template<class Archive > void \fBserialize\fP (Archive &ar, const unsigned int version)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBboost::serialization::access\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NodeConnectionMessage::NodeConnectionMessage ()\fC [inline]\fP"

.SS "NodeConnectionMessage::NodeConnectionMessage (std::stringip, std::stringport)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "static \fBNodeConnectionMessage\fP NodeConnectionMessage::deserialize (\fBMessage256\fPmessage)\fC [inline]\fP, \fC [static]\fP"

.PP
Referenced by AdaptiveEndPoint::ConnectionActor::ReceiveNodeStatus256()\&.
.SS "static \fBNodeConnectionMessage\fP NodeConnectionMessage::deserialize4K (\fBMessage4K\fPmessage)\fC [inline]\fP, \fC [static]\fP"

.SS "template<class Archive > void NodeConnectionMessage::serialize (Archive &ar, const unsigned intversion)\fC [inline]\fP, \fC [private]\fP"

.PP
References ip, and port\&.
.PP
Referenced by Coordinator::ListeningNewNode()\&.
.SS "static \fBMessage256\fP NodeConnectionMessage::serialize (\fBNodeConnectionMessage\fPinput)\fC [inline]\fP, \fC [static]\fP"

.PP
References input()\&.
.SS "static \fBMessage4K\fP NodeConnectionMessage::serialize4K (\fBNodeConnectionMessage\fPinput)\fC [inline]\fP, \fC [static]\fP"

.PP
References input()\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class boost::serialization::access\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::string NodeConnectionMessage::ip"

.PP
Referenced by Coordinator::ListeningNewNode(), AdaptiveEndPoint::ConnectionActor::ReceiveNodeStatus256(), and serialize()\&.
.SS "std::string NodeConnectionMessage::port"

.PP
Referenced by Coordinator::ListeningNewNode(), AdaptiveEndPoint::ConnectionActor::ReceiveNodeStatus256(), and serialize()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
