.TH "NodeAddress" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NodeAddress \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ids\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNodeAddress\fP ()"
.br
.ti -1c
.RI "\fBNodeAddress\fP (std::string \fBip\fP, std::string \fBport\fP)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBNodeAddress\fP &r) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBip\fP"
.br
.ti -1c
.RI "std::string \fBport\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NodeAddress::NodeAddress ()\fC [inline]\fP"

.SS "NodeAddress::NodeAddress (std::stringip, std::stringport)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool NodeAddress::operator== (const \fBNodeAddress\fP &r) const\fC [inline]\fP"

.PP
References ip, and port\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string NodeAddress::ip"

.PP
Referenced by ExchangeTracker::AskForSocketConnectionInfo(), claims::physical_operator::ExchangeSender::ConnectToUpper(), hash_value(), operator==(), ResourceManagerMaster::ResourceManagerMasterActor::ReceiveNewNodeRegister(), and ResourceManagerMaster::RegisterNewSlave()\&.
.SS "std::string NodeAddress::port"

.PP
Referenced by ExchangeTracker::AskForSocketConnectionInfo(), claims::physical_operator::ExchangeSender::ConnectToUpper(), hash_value(), operator==(), ResourceManagerMaster::ResourceManagerMasterActor::ReceiveNewNodeRegister(), and ResourceManagerMaster::RegisterNewSlave()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
