.TH "OperateDecimal" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OperateDecimal \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOperate\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOperateDecimal\fP (unsigned number_of_decimal_digits=12, bool _nullable=true)"
.br
.ti -1c
.RI "void \fBassignment\fP (const void *const &src, void *const &desc) const "
.br
.ti -1c
.RI "std::string \fBtoString\fP (void *value)"
.br
.ti -1c
.RI "void \fBtoValue\fP (void *target, const char *string)"
.br
.ti -1c
.RI "bool \fBequal\fP (const void *const &a, const void *const &b) const "
.br
.ti -1c
.RI "bool \fBless\fP (const void *&a, const void *&b) const "
.br
.ti -1c
.RI "bool \fBgreate\fP (const void *&a, const void *&b) const "
.br
.ti -1c
.RI "int \fBcompare\fP (const void *a, const void *b) const "
.br
.ti -1c
.RI "void \fBadd\fP (void *target, void *increment)"
.br
.ti -1c
.RI "void \fBmultiple\fP (void *target, void *increment)"
.br
.ti -1c
.RI "fun \fBGetADDFunction\fP ()"
.br
.ti -1c
.RI "fun \fBGetMINFunction\fP ()"
.br
.ti -1c
.RI "fun \fBGetMAXFunction\fP ()"
.br
.ti -1c
.RI "fun \fBGetIncreateByOneFunction\fP ()"
.br
.ti -1c
.RI "fun \fBGetAVGFunction\fP ()"
.br
.ti -1c
.RI "unsigned \fBgetPartitionValue\fP (const void *key, const \fBPartitionFunction\fP *partition_function) const "
.br
.ti -1c
.RI "unsigned \fBgetPartitionValue\fP (const void *key) const "
.br
.ti -1c
.RI "unsigned \fBgetPartitionValue\fP (const void *key, const unsigned long &mod) const "
.br
.ti -1c
.RI "\fBOperate\fP * \fBduplicateOperator\fP () const "
.br
.ti -1c
.RI "bool \fBsetNull\fP (void *value)"
.br
.ti -1c
.RI "bool \fBisNull\fP (void *value) const "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBtoString\fP (const \fBNValue\fP v, unsigned n_o_d_d=12)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBnumber_of_decimal_digits_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
