.TH "parallel_insert_args" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
parallel_insert_args \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <insert_optimized_hash_table_test\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBpid\fP"
.br
.ti -1c
.RI "\fBDynamicBlockBuffer::Iterator\fP * \fBbuffer_it\fP"
.br
.ti -1c
.RI "\fBInsertOptimizedHashTable\fP * \fBhashtable\fP"
.br
.ti -1c
.RI "unsigned \fBnbuckets\fP"
.br
.ti -1c
.RI "\fBBarrier\fP * \fBbarrier\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBBarrier\fP* parallel_insert_args::barrier"

.PP
Referenced by insert_into_insert_optimized_hash_table(), and parallel_insert_to_insert_optimized_hash()\&.
.SS "\fBDynamicBlockBuffer::Iterator\fP* parallel_insert_args::buffer_it"

.PP
Referenced by insert_into_insert_optimized_hash_table(), and parallel_insert_to_insert_optimized_hash()\&.
.SS "\fBInsertOptimizedHashTable\fP* parallel_insert_args::hashtable"

.PP
Referenced by insert_into_insert_optimized_hash_table(), and parallel_insert_to_insert_optimized_hash()\&.
.SS "unsigned parallel_insert_args::nbuckets"

.PP
Referenced by insert_into_insert_optimized_hash_table(), and parallel_insert_to_insert_optimized_hash()\&.
.SS "int32_t parallel_insert_args::pid"

.PP
Referenced by insert_into_insert_optimized_hash_table(), and parallel_insert_to_insert_optimized_hash()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
