.TH "ParseResult" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParseResult \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast_node\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fByyscan_info_\fP"
.br
.ti -1c
.RI "\fBAstNode\fP * \fBast\fP"
.br
.ti -1c
.RI "const char * \fBsql_clause\fP"
.br
.ti -1c
.RI "int \fBerror_number\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBAstNode\fP* ParseResult::ast"

.PP
Referenced by Parser::CreateRawAST(), and yyuserAction()\&.
.SS "int ParseResult::error_number"

.PP
Referenced by yyuserAction()\&.
.SS "const char* ParseResult::sql_clause"

.SS "void* ParseResult::yyscan_info_"

.PP
Referenced by Parser::CreateRawAST(), and while()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
