.TH "PartitionUnbindingMessage" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PartitionUnbindingMessage \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Message\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPartitionUnbindingMessage\fP (const \fBPartitionID\fP &pid)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPartitionID\fP \fBpartition_id\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PartitionUnbindingMessage::PartitionUnbindingMessage (const \fBPartitionID\fP &pid)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBPartitionID\fP PartitionUnbindingMessage::partition_id"

.PP
Referenced by BlockManager::BlockManagerWorkerActor::UnbindingPartition()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
