.TH "PartitionStorage" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PartitionStorage \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PartitionStorage\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAtomicPartitionReaderIterator\fP"
.br
.ti -1c
.RI "class \fBPartitionReaderItetaor\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPartitionStorage\fP (const \fBPartitionID\fP &partition_id, const unsigned &number_of_chunks, const \fBStorageLevel\fP &)"
.br
.ti -1c
.RI "virtual \fB~PartitionStorage\fP ()"
.br
.ti -1c
.RI "void \fBaddNewChunk\fP ()"
.br
.ti -1c
.RI "void \fBupdateChunksWithInsertOrAppend\fP (const \fBPartitionID\fP &partition_id, const unsigned &number_of_chunks, const \fBStorageLevel\fP &storage_level)"
.br
.ti -1c
.RI "void \fBremoveAllChunks\fP (const \fBPartitionID\fP &partition_id)"
.br
.ti -1c
.RI "\fBPartitionReaderItetaor\fP * \fBcreateReaderIterator\fP ()"
.br
.ti -1c
.RI "\fBPartitionReaderItetaor\fP * \fBcreateAtomicReaderIterator\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBPartitionID\fP \fBpartition_id_\fP"
.br
.ti -1c
.RI "unsigned \fBnumber_of_chunks_\fP"
.br
.ti -1c
.RI "std::vector< \fBChunkStorage\fP * > \fBchunk_list_\fP"
.br
.ti -1c
.RI "\fBStorageLevel\fP \fBdesirable_storage_level_\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBPartitionReaderItetaor\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PartitionStorage::PartitionStorage (const \fBPartitionID\fP &partition_id, const unsigned &number_of_chunks, const \fBStorageLevel\fP &storage_level)"

.PP
References BLOCK_SIZE, chunk_list_, desirable_storage_level_, number_of_chunks_, and partition_id_\&.
.SS "PartitionStorage::~PartitionStorage ()\fC [virtual]\fP"

.PP
References chunk_list_\&.
.SH "Member Function Documentation"
.PP 
.SS "void PartitionStorage::addNewChunk ()"

.PP
References number_of_chunks_\&.
.SS "\fBPartitionStorage::PartitionReaderItetaor\fP * PartitionStorage::createAtomicReaderIterator ()"

.PP
Referenced by bottomLayerCollecting::Open(), claims::physical_operator::PhysicalProjectionScan::Open(), IndexScanIterator::Open(), and projection_scan()\&.
.SS "\fBPartitionStorage::PartitionReaderItetaor\fP * PartitionStorage::createReaderIterator ()"

.PP
References PartitionReaderItetaor\&.
.SS "void PartitionStorage::removeAllChunks (const \fBPartitionID\fP &partition_id)"

.PP
References chunk_list_, MemoryChunkStore::getInstance(), number_of_chunks_, and MemoryChunkStore::returnChunk()\&.
.SS "void PartitionStorage::updateChunksWithInsertOrAppend (const \fBPartitionID\fP &partition_id, const unsigned &number_of_chunks, const \fBStorageLevel\fP &storage_level)"

.PP
References BLOCK_SIZE, chunk_list_, MemoryChunkStore::getInstance(), HDFS, number_of_chunks_, and MemoryChunkStore::returnChunk()\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBPartitionReaderItetaor\fP\fC [friend]\fP"

.PP
Referenced by createReaderIterator()\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBChunkStorage\fP*> PartitionStorage::chunk_list_\fC [protected]\fP"

.PP
Referenced by PartitionStorage(), removeAllChunks(), updateChunksWithInsertOrAppend(), and ~PartitionStorage()\&.
.SS "\fBStorageLevel\fP PartitionStorage::desirable_storage_level_\fC [protected]\fP"

.PP
Referenced by PartitionStorage()\&.
.SS "unsigned PartitionStorage::number_of_chunks_\fC [protected]\fP"

.PP
Referenced by addNewChunk(), PartitionStorage::PartitionReaderItetaor::nextChunk(), PartitionStorage::AtomicPartitionReaderIterator::nextChunk(), PartitionStorage(), removeAllChunks(), and updateChunksWithInsertOrAppend()\&.
.SS "\fBPartitionID\fP PartitionStorage::partition_id_\fC [protected]\fP"

.PP
Referenced by PartitionStorage()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
