.TH "PartitionFunctionFactory" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PartitionFunctionFactory \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBPartitionFunction\fP * \fBcreateGeneralModuloFunction\fP (const int &range, const int &min=0, const int &skipbits=0)"
.br
.ti -1c
.RI "static \fBPartitionFunction\fP * \fBcreateModuloFunction\fP (const int &range, const int &min=0, const int &skipbits=0)"
.br
.ti -1c
.RI "static \fBPartitionFunction\fP * \fBcreateUniformRangeHashFunction\fP (const int &range, const int &min, const int &max)"
.br
.ti -1c
.RI "static \fBPartitionFunction\fP * \fBcreateRoundRobinPartitionHashFunction\fP (int range)"
.br
.ti -1c
.RI "static \fBPartitionFunction\fP * \fBcreateBoostHashFunction\fP (const int &range)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
