.TH "PartitionBindingMessage" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PartitionBindingMessage \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPartitionBindingMessage\fP (const \fBPartitionID\fP &pid, const unsigned &num, const StorageLevel &level)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPartitionID\fP \fBpartition_id\fP"
.br
.ti -1c
.RI "unsigned \fBnumber_of_chunks\fP"
.br
.ti -1c
.RI "StorageLevel \fBstorage_level\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
