.TH "PartitionStorage::PartitionReaderItetaor" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PartitionStorage::PartitionReaderItetaor \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PartitionStorage\&.h>\fP
.PP
Inherited by \fBPartitionStorage::AtomicPartitionReaderIterator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPartitionReaderItetaor\fP (\fBPartitionStorage\fP *partition_storage)"
.br
.ti -1c
.RI "virtual \fB~PartitionReaderItetaor\fP ()"
.br
.ti -1c
.RI "virtual \fBChunkReaderIterator\fP * \fBnextChunk\fP ()"
.br
.ti -1c
.RI "virtual bool \fBnextBlock\fP (\fBBlockStreamBase\fP *&block)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBPartitionStorage\fP * \fBps\fP"
.br
.ti -1c
.RI "unsigned \fBchunk_cur_\fP"
.br
.ti -1c
.RI "\fBChunkReaderIterator\fP * \fBchunk_it_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PartitionStorage::PartitionReaderItetaor::PartitionReaderItetaor (\fBPartitionStorage\fP *partition_storage)"

.SS "PartitionStorage::PartitionReaderItetaor::~PartitionReaderItetaor ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool PartitionStorage::PartitionReaderItetaor::nextBlock (\fBBlockStreamBase\fP *&block)\fC [virtual]\fP"

.PP
Reimplemented in \fBPartitionStorage::AtomicPartitionReaderIterator\fP\&.
.PP
Referenced by insert_into_hash_table_from_projection(), and claims::physical_operator::PhysicalProjectionScan::Next()\&.
.SS "\fBChunkReaderIterator\fP * PartitionStorage::PartitionReaderItetaor::nextChunk ()\fC [virtual]\fP"

.PP
Reimplemented in \fBPartitionStorage::AtomicPartitionReaderIterator\fP\&.
.PP
References PartitionStorage::number_of_chunks_\&.
.PP
Referenced by bottomLayerCollecting::askForNextBlock(), IndexScanIterator::askForNextBlock(), PartitionStorage::AtomicPartitionReaderIterator::nextBlock(), and claims::physical_operator::PhysicalProjectionScan::Open()\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned PartitionStorage::PartitionReaderItetaor::chunk_cur_\fC [protected]\fP"

.SS "\fBChunkReaderIterator\fP* PartitionStorage::PartitionReaderItetaor::chunk_it_\fC [protected]\fP"

.SS "\fBPartitionStorage\fP* PartitionStorage::PartitionReaderItetaor::ps\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
