.TH "PartitionID" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PartitionID \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ids\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPartitionID\fP (\fBProjectionID\fP projection_id, PartitionOffset off)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBPartitionID\fP &r) const "
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBPartitionID\fP &r) const "
.br
.ti -1c
.RI "\fBPartitionID\fP (const \fBPartitionID\fP &r)"
.br
.ti -1c
.RI "std::string \fBgetName\fP () const "
.br
.ti -1c
.RI "std::string \fBgetPathAndName\fP () const "
.br
.ti -1c
.RI "template<class Archive > void \fBserialize\fP (Archive &ar, const unsigned int version)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBProjectionID\fP \fBprojection_id\fP"
.br
.ti -1c
.RI "PartitionOffset \fBpartition_off\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBboost::serialization::access\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBPartitionID\fP: a partition corresponds to one projection\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
