.TH "PartitionBindingMessage" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PartitionBindingMessage \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Message\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPartitionBindingMessage\fP (const \fBPartitionID\fP &pid, const unsigned &num, const \fBStorageLevel\fP &level)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPartitionID\fP \fBpartition_id\fP"
.br
.ti -1c
.RI "unsigned \fBnumber_of_chunks\fP"
.br
.ti -1c
.RI "\fBStorageLevel\fP \fBstorage_level\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PartitionBindingMessage::PartitionBindingMessage (const \fBPartitionID\fP &pid, const unsigned &num, const \fBStorageLevel\fP &level)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "unsigned PartitionBindingMessage::number_of_chunks"

.PP
Referenced by BlockManager::BlockManagerWorkerActor::BindingPartition()\&.
.SS "\fBPartitionID\fP PartitionBindingMessage::partition_id"

.PP
Referenced by BlockManager::BlockManagerWorkerActor::BindingPartition()\&.
.SS "\fBStorageLevel\fP PartitionBindingMessage::storage_level"

.PP
Referenced by BlockManager::BlockManagerWorkerActor::BindingPartition()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
