.TH "PartitionID" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PartitionID \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ids\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPartitionID\fP (\fBProjectionID\fP \fBprojection_id\fP, \fBPartitionOffset\fP off)"
.br
.ti -1c
.RI "\fBPartitionID\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBPartitionID\fP &r) const "
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBPartitionID\fP &r) const "
.br
.ti -1c
.RI "\fBPartitionID\fP (const \fBPartitionID\fP &r)"
.br
.ti -1c
.RI "std::string \fBgetName\fP () const "
.br
.ti -1c
.RI "std::string \fBgetPathAndName\fP () const "
.br
.ti -1c
.RI "template<class Archive > void \fBserialize\fP (Archive &ar, const unsigned int version)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBProjectionID\fP \fBprojection_id\fP"
.br
.ti -1c
.RI "\fBPartitionOffset\fP \fBpartition_off\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBboost::serialization::access\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBPartitionID\fP: a partition corresponds to one projection\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PartitionID::PartitionID (\fBProjectionID\fPprojection_id, \fBPartitionOffset\fPoff)\fC [inline]\fP"

.SS "PartitionID::PartitionID ()\fC [inline]\fP"

.SS "PartitionID::PartitionID (const \fBPartitionID\fP &r)\fC [inline]\fP"

.PP
References partition_off, and projection_id\&.
.SH "Member Function Documentation"
.PP 
.SS "std::string PartitionID::getName () const\fC [inline]\fP"

.PP
References partition_off, projection_id, ProjectionID::projection_off, and ProjectionID::table_id\&.
.PP
Referenced by BlockManager::addPartition(), DiskChunkReaderIteraror::DiskChunkReaderIteraror(), HDFSChunkReaderIterator::HDFSChunkReaderIterator(), bottomLayerCollecting::Open(), claims::physical_operator::PhysicalProjectionScan::Open(), IndexScanIterator::Open(), and BlockManager::removePartition()\&.
.SS "std::string PartitionID::getPathAndName () const"

.PP
References Config::data_dir, partition_off, projection_id, ProjectionID::projection_off, and ProjectionID::table_id\&.
.PP
Referenced by DiskChunkReaderIteraror::DiskChunkReaderIteraror(), BlockManager::loadFromDisk(), and BlockManager::loadFromHdfs()\&.
.SS "bool PartitionID::operator< (const \fBPartitionID\fP &r) const\fC [inline]\fP"

.PP
References partition_off, and projection_id\&.
.SS "bool PartitionID::operator== (const \fBPartitionID\fP &r) const\fC [inline]\fP"

.PP
References partition_off, and projection_id\&.
.SS "template<class Archive > void PartitionID::serialize (Archive &ar, const unsigned intversion)\fC [inline]\fP"

.PP
References partition_off, and projection_id\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class boost::serialization::access\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBPartitionOffset\fP PartitionID::partition_off"

.PP
Referenced by getName(), getPathAndName(), hash_value(), bottomLayerSorting::Open(), operator<(), operator==(), PartitionID(), and serialize()\&.
.SS "\fBProjectionID\fP PartitionID::projection_id"

.PP
Referenced by getName(), getPathAndName(), hash_value(), bottomLayerSorting::Open(), operator<(), operator==(), PartitionID(), and serialize()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
