.TH "PartitionedBlockBuffer" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PartitionedBlockBuffer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PartitionedBlockBuffer\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPartitionedBlockBuffer\fP (unsigned \fBnPartitions\fP, unsigned \fBblock_size\fP, unsigned \fBnBlocks\fP)"
.br
.ti -1c
.RI "\fBPartitionedBlockBuffer\fP (unsigned \fBnPartitions\fP, unsigned \fBblock_size\fP)"
.br
.ti -1c
.RI "virtual \fB~PartitionedBlockBuffer\fP ()"
.br
.ti -1c
.RI "bool \fBhasEmptyBlock\fP () const "
.br
.ti -1c
.RI "bool \fBisEmpty\fP ()"
.br
.ti -1c
.RI "bool \fBinsertBlockToPartitionedList\fP (\fBBlock\fP *src, unsigned partition_id)"
.br
.ti -1c
.RI "int \fBgetBlock\fP (\fBBlock\fP &desc)"
.br
.ti -1c
.RI "bool \fBgetBlock\fP (\fBBlock\fP &desc, unsigned partition_id)"
.br
.ti -1c
.RI "unsigned \fBgetBlockInBuffer\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBinserted\fP"
.br
.ti -1c
.RI "unsigned \fBremoved\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "bool \fBgetBlockInPartitionedBlockList\fP (\fBBlock\fP &desc, unsigned partition_id)"
.br
.ti -1c
.RI "unsigned \fBgetBlockNumberOfPartitionInBuffer\fP (unsigned partition_id)"
.br
.ti -1c
.RI "void \fBdestoryEmptyBlocks\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBnPartitions\fP"
.br
.ti -1c
.RI "unsigned \fBnBlocks\fP"
.br
.ti -1c
.RI "std::list< \fBBlock\fP * > * \fBblocks_in_partition_list\fP"
.br
.ti -1c
.RI "std::list< \fBBlock\fP * > \fBempty_block_list\fP"
.br
.ti -1c
.RI "\fBLock\fP \fBlock\fP"
.br
.ti -1c
.RI "\fBsemaphore\fP \fBempty_blocks\fP"
.br
.ti -1c
.RI "\fBsemaphore\fP \fBused_blocks\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PartitionedBlockBuffer::PartitionedBlockBuffer (unsignednPartitions, unsignedblock_size, unsignednBlocks)"

.PP
References blocks_in_partition_list, empty_block_list, empty_blocks, inserted, nBlocks, nPartitions, removed, semaphore::set_value(), and used_blocks\&.
.SS "PartitionedBlockBuffer::PartitionedBlockBuffer (unsignednPartitions, unsignedblock_size)"

.PP
References blocks_in_partition_list, empty_block_list, empty_blocks, inserted, nBlocks, nPartitions, removed, semaphore::set_value(), and used_blocks\&.
.SS "PartitionedBlockBuffer::~PartitionedBlockBuffer ()\fC [virtual]\fP"

.PP
References blocks_in_partition_list, destoryEmptyBlocks(), semaphore::get_value(), nPartitions, and used_blocks\&.
.SH "Member Function Documentation"
.PP 
.SS "void PartitionedBlockBuffer::destoryEmptyBlocks ()\fC [private]\fP"

.PP
References empty_block_list\&.
.PP
Referenced by ~PartitionedBlockBuffer()\&.
.SS "int PartitionedBlockBuffer::getBlock (\fBBlock\fP &desc)"

.PP
References Lock::acquire(), blocks_in_partition_list, empty_blocks, getBlockInPartitionedBlockList(), lock, nPartitions, semaphore::post(), Lock::release(), used_blocks, and semaphore::wait()\&.
.PP
Referenced by claims::physical_operator::ExchangeSenderMaterialized::Materialize(), and claims::physical_operator::ExchangeSenderPipeline::Sender()\&.
.SS "bool PartitionedBlockBuffer::getBlock (\fBBlock\fP &desc, unsignedpartition_id)"

.PP
References Lock::acquire(), empty_blocks, getBlockInPartitionedBlockList(), getBlockNumberOfPartitionInBuffer(), lock, semaphore::post(), Lock::release(), used_blocks, and semaphore::wait()\&.
.SS "unsigned PartitionedBlockBuffer::getBlockInBuffer ()"

.PP
References Lock::acquire(), semaphore::get_value(), lock, Lock::release(), and used_blocks\&.
.PP
Referenced by claims::physical_operator::ExchangeSenderMaterialized::debug(), and claims::physical_operator::ExchangeSenderMaterialized::Materialize()\&.
.SS "bool PartitionedBlockBuffer::getBlockInPartitionedBlockList (\fBBlock\fP &desc, unsignedpartition_id)\fC [private]\fP"

.PP
References blocks_in_partition_list, empty_block_list, Block::getBlock(), and Block::getsize()\&.
.PP
Referenced by getBlock()\&.
.SS "unsigned PartitionedBlockBuffer::getBlockNumberOfPartitionInBuffer (unsignedpartition_id)\fC [private]\fP"

.PP
References Lock::acquire(), blocks_in_partition_list, lock, and Lock::release()\&.
.PP
Referenced by getBlock()\&.
.SS "bool PartitionedBlockBuffer::hasEmptyBlock () const"

.PP
References empty_block_list\&.
.SS "bool PartitionedBlockBuffer::insertBlockToPartitionedList (\fBBlock\fP *src, unsignedpartition_id)"
'copy' a block into the corresponding partitioned block list\&. In fact, the swap of pointer is used rather than actually coping the content for performance concern\&. 
.PP
References Lock::acquire(), blocks_in_partition_list, empty_block_list, empty_blocks, Block::getBlock(), Block::getsize(), inserted, lock, nPartitions, semaphore::post(), Lock::release(), used_blocks, and semaphore::wait()\&.
.PP
Referenced by claims::physical_operator::ExchangeSenderMaterialized::Next(), and claims::physical_operator::ExchangeSenderPipeline::Next()\&.
.SS "bool PartitionedBlockBuffer::isEmpty ()"

.PP
References semaphore::get_value(), and used_blocks\&.
.PP
Referenced by claims::physical_operator::ExchangeSenderMaterialized::Next(), and claims::physical_operator::ExchangeSenderPipeline::Next()\&.
.SH "Member Data Documentation"
.PP 
.SS "std::list<\fBBlock\fP*>* PartitionedBlockBuffer::blocks_in_partition_list\fC [private]\fP"

.PP
Referenced by getBlock(), getBlockInPartitionedBlockList(), getBlockNumberOfPartitionInBuffer(), insertBlockToPartitionedList(), PartitionedBlockBuffer(), and ~PartitionedBlockBuffer()\&.
.SS "std::list<\fBBlock\fP*> PartitionedBlockBuffer::empty_block_list\fC [private]\fP"

.PP
Referenced by destoryEmptyBlocks(), getBlockInPartitionedBlockList(), hasEmptyBlock(), insertBlockToPartitionedList(), and PartitionedBlockBuffer()\&.
.SS "\fBsemaphore\fP PartitionedBlockBuffer::empty_blocks\fC [private]\fP"

.PP
Referenced by getBlock(), insertBlockToPartitionedList(), and PartitionedBlockBuffer()\&.
.SS "unsigned PartitionedBlockBuffer::inserted"

.PP
Referenced by insertBlockToPartitionedList(), and PartitionedBlockBuffer()\&.
.SS "\fBLock\fP PartitionedBlockBuffer::lock\fC [private]\fP"

.PP
Referenced by getBlock(), getBlockInBuffer(), getBlockNumberOfPartitionInBuffer(), and insertBlockToPartitionedList()\&.
.SS "unsigned PartitionedBlockBuffer::nBlocks\fC [private]\fP"

.PP
Referenced by PartitionedBlockBuffer()\&.
.SS "unsigned PartitionedBlockBuffer::nPartitions\fC [private]\fP"

.PP
Referenced by getBlock(), insertBlockToPartitionedList(), PartitionedBlockBuffer(), and ~PartitionedBlockBuffer()\&.
.SS "unsigned PartitionedBlockBuffer::removed"

.PP
Referenced by PartitionedBlockBuffer()\&.
.SS "\fBsemaphore\fP PartitionedBlockBuffer::used_blocks\fC [private]\fP"

.PP
Referenced by getBlock(), getBlockInBuffer(), insertBlockToPartitionedList(), isEmpty(), PartitionedBlockBuffer(), and ~PartitionedBlockBuffer()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
