.TH "PerformanceInfo" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PerformanceInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ExpandedThreadTracker\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBentry\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPerformanceInfo\fP ()"
.br
.ti -1c
.RI "\fBPerformanceInfo\fP (\fBExpandabilityShrinkability\fP *expand_shrink)"
.br
.ti -1c
.RI "\fB~PerformanceInfo\fP ()"
.br
.ti -1c
.RI "void \fBprocessed_one_block\fP ()"
.br
.ti -1c
.RI "double \fBreport_instance_performance_in_millibytes\fP ()"
.br
.ti -1c
.RI "void \fBinitialize\fP ()"
.br
.ti -1c
.RI "void \fBeclipseTimeSlices\fP (unsigned offset)"
.br
.ti -1c
.RI "void \fBhitCurrentSlice\fP ()"
.br
.ti -1c
.RI "void \fBupdateTimeSlicesToCurrentTicks\fP ()"
.br
.ti -1c
.RI "unsigned long \fBgetBlockSumInAllSlices\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBticks\fP \fBcurrent_time_slice_start_\fP"
.br
.ti -1c
.RI "unsigned long \fBnblocks_in_current_slice_\fP"
.br
.ti -1c
.RI "\fBSpineLock\fP \fBlock_\fP"
.br
.ti -1c
.RI "unsigned * \fBslices\fP"
.br
.ti -1c
.RI "unsigned long long int \fBinit_ticks_\fP"
.br
.ti -1c
.RI "std::vector< \fBentry\fP > \fBscalability_vector_\fP"
.br
.ti -1c
.RI "\fBExpandabilityShrinkability\fP * \fBexpand_shrink_\fP"
.br
.ti -1c
.RI "\fBtimestamp\fP \fBlast_update_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PerformanceInfo::PerformanceInfo ()\fC [inline]\fP"

.SS "PerformanceInfo::PerformanceInfo (\fBExpandabilityShrinkability\fP *expand_shrink)"

.PP
References current_time_slice_start_, curtick(), get_time_slice_start, Config::getInstance(), Config::max_degree_of_parallelism, NUMOFSLICES, scalability_vector_, and slices\&.
.SS "PerformanceInfo::~PerformanceInfo ()"

.SH "Member Function Documentation"
.PP 
.SS "void PerformanceInfo::eclipseTimeSlices (unsignedoffset)"

.PP
References NUMOFSLICES, and slices\&.
.PP
Referenced by updateTimeSlicesToCurrentTicks()\&.
.SS "unsigned long PerformanceInfo::getBlockSumInAllSlices ()"

.PP
References SpineLock::acquire(), lock_, NUMOFSLICES, SpineLock::release(), and slices\&.
.PP
Referenced by report_instance_performance_in_millibytes()\&.
.SS "void PerformanceInfo::hitCurrentSlice ()"

.PP
References NUMOFSLICES, and slices\&.
.PP
Referenced by processed_one_block()\&.
.SS "void PerformanceInfo::initialize ()"

.PP
References current_time_slice_start_, curtick(), init_ticks_, last_update_, and nblocks_in_current_slice_\&.
.PP
Referenced by claims::physical_operator::ExchangeMerger::CreatePerformanceInfo(), claims::physical_operator::PhysicalAggregation::Open(), and claims::physical_operator::PhysicalProjectionScan::Open()\&.
.SS "void PerformanceInfo::processed_one_block ()"

.PP
References SpineLock::acquire(), current_time_slice_start_, curtick(), expand_shrink_, get_time_slice_start, ExpandabilityShrinkability::GetDegreeOfParallelism(), Config::getInstance(), hitCurrentSlice(), last_update_, lock_, Config::max_degree_of_parallelism, MONITOR_FRECY, SpineLock::release(), report_instance_performance_in_millibytes(), scalability_vector_, and updateTimeSlicesToCurrentTicks()\&.
.PP
Referenced by claims::physical_operator::PhysicalAggregation::Next(), claims::physical_operator::ExchangeMerger::Next(), and claims::physical_operator::PhysicalProjectionScan::Next()\&.
.SS "double PerformanceInfo::report_instance_performance_in_millibytes ()"

.PP
References SpineLock::acquire(), BLOCK_SIZE, convertCyclesToSecond(), current_time_slice_start_, curtick(), get_time_slice_start, getBlockSumInAllSlices(), getSecond(), getSecondDuratoin(), init_ticks_, lock_, NUMOFSLICES, SpineLock::release(), TIME_SLICE, and updateTimeSlicesToCurrentTicks()\&.
.PP
Referenced by processed_one_block()\&.
.SS "void PerformanceInfo::updateTimeSlicesToCurrentTicks ()"

.PP
References current_time_slice_start_, curtick(), eclipseTimeSlices(), get_time_slice_start, and TIME_SLICE\&.
.PP
Referenced by processed_one_block(), and report_instance_performance_in_millibytes()\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBticks\fP PerformanceInfo::current_time_slice_start_"

.PP
Referenced by initialize(), PerformanceInfo(), processed_one_block(), report_instance_performance_in_millibytes(), and updateTimeSlicesToCurrentTicks()\&.
.SS "\fBExpandabilityShrinkability\fP* PerformanceInfo::expand_shrink_"

.PP
Referenced by processed_one_block()\&.
.SS "unsigned long long int PerformanceInfo::init_ticks_"

.PP
Referenced by initialize(), and report_instance_performance_in_millibytes()\&.
.SS "\fBtimestamp\fP PerformanceInfo::last_update_"

.PP
Referenced by initialize(), and processed_one_block()\&.
.SS "\fBSpineLock\fP PerformanceInfo::lock_"

.PP
Referenced by getBlockSumInAllSlices(), processed_one_block(), and report_instance_performance_in_millibytes()\&.
.SS "unsigned long PerformanceInfo::nblocks_in_current_slice_"

.PP
Referenced by initialize()\&.
.SS "std::vector<\fBentry\fP> PerformanceInfo::scalability_vector_"

.PP
Referenced by PerformanceInfo(), and processed_one_block()\&.
.SS "unsigned* PerformanceInfo::slices"

.PP
Referenced by eclipseTimeSlices(), getBlockSumInAllSlices(), hitCurrentSlice(), and PerformanceInfo()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
