.TH "PerformanceInfo::entry" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PerformanceInfo::entry \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ExpandedThreadTracker\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBentry\fP ()"
.br
.ti -1c
.RI "bool \fBisUpdateToDate\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBperformance\fP"
.br
.ti -1c
.RI "\fBtimestamp\fP \fBlast_update\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PerformanceInfo::entry::entry ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool PerformanceInfo::entry::isUpdateToDate ()"

.PP
References curtick(), last_update, and VALID_FRECY\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBtimestamp\fP PerformanceInfo::entry::last_update"

.PP
Referenced by isUpdateToDate()\&.
.SS "float PerformanceInfo::entry::performance"


.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
