.TH "PhysicalQueryPlan" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PhysicalQueryPlan \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Message\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPhysicalQueryPlan\fP (\fBPhysicalOperatorBase\fP *it)"
.br
.ti -1c
.RI "\fBPhysicalQueryPlan\fP (const \fBPhysicalQueryPlan\fP &r)"
.br
.ti -1c
.RI "\fBPhysicalQueryPlan\fP ()"
.br
.ti -1c
.RI "\fB~PhysicalQueryPlan\fP ()"
.br
.ti -1c
.RI "void \fBdestory\fP ()"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBPhysicalQueryPlan\fP \fBdeserialize\fP (\fBMessage256\fP message)"
.br
.ti -1c
.RI "static \fBMessage256\fP \fBserialize\fP (\fBPhysicalQueryPlan\fP \fBinput\fP)"
.br
.ti -1c
.RI "static \fBPhysicalQueryPlan\fP \fBdeserialize4K\fP (\fBMessage4K\fP message)"
.br
.ti -1c
.RI "static \fBMessage4K\fP \fBserialize4K\fP (\fBPhysicalQueryPlan\fP &\fBinput\fP)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "template<class Archive > void \fBserialize\fP (Archive &ar, const unsigned int version)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBPhysicalOperatorBase\fP * \fBblock_stream_iterator_root_\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBboost::serialization::access\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PhysicalQueryPlan::PhysicalQueryPlan (\fBPhysicalOperatorBase\fP *it)\fC [inline]\fP"

.SS "PhysicalQueryPlan::PhysicalQueryPlan (const \fBPhysicalQueryPlan\fP &r)\fC [inline]\fP"

.PP
References block_stream_iterator_root_\&.
.SS "PhysicalQueryPlan::PhysicalQueryPlan ()\fC [inline]\fP"

.SS "PhysicalQueryPlan::~PhysicalQueryPlan ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "static \fBPhysicalQueryPlan\fP PhysicalQueryPlan::deserialize (\fBMessage256\fPmessage)\fC [inline]\fP, \fC [static]\fP"

.PP
Referenced by IteratorExecutorSlave::ExecuteIteratorActor::Handler256()\&.
.SS "static \fBPhysicalQueryPlan\fP PhysicalQueryPlan::deserialize4K (\fBMessage4K\fPmessage)\fC [inline]\fP, \fC [static]\fP"

.PP
Referenced by IteratorExecutorMaster::ExecuteBlockStreamIteratorsOnSite(), and IteratorExecutorSlave::ExecuteIteratorActor::Handler4K()\&.
.SS "void PhysicalQueryPlan::destory ()\fC [inline]\fP"

.PP
References block_stream_iterator_root_, and claims::physical_operator::PhysicalOperatorBase::~PhysicalOperatorBase()\&.
.SS "void PhysicalQueryPlan::run ()"

.PP
Referenced by IteratorExecutorSlave::executePhysicalQueryPlan(), and IteratorExecutorSlave::ExecuteIteratorActor::Handler256()\&.
.SS "static \fBMessage256\fP PhysicalQueryPlan::serialize (\fBPhysicalQueryPlan\fPinput)\fC [inline]\fP, \fC [static]\fP"

.PP
References input()\&.
.SS "template<class Archive > void PhysicalQueryPlan::serialize (Archive &ar, const unsigned intversion)\fC [inline]\fP, \fC [private]\fP"

.PP
References block_stream_iterator_root_, Register_Block_Stream_Iterator(), and Register_Schemas()\&.
.SS "static \fBMessage4K\fP PhysicalQueryPlan::serialize4K (\fBPhysicalQueryPlan\fP &input)\fC [inline]\fP, \fC [static]\fP"

.PP
References input()\&.
.PP
Referenced by IteratorExecutorMaster::ExecuteBlockStreamIteratorsOnSite(), and IteratorExecutorMaster::ExecuteBlockStreamIteratorsOnSites()\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class boost::serialization::access\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBPhysicalOperatorBase\fP* PhysicalQueryPlan::block_stream_iterator_root_\fC [private]\fP"

.PP
Referenced by destory(), PhysicalQueryPlan(), and serialize()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
