.TH "ProjectionID" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProjectionID \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ids\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProjectionID\fP (TableID tid, ProjectionOffset off)"
.br
.ti -1c
.RI "\fBProjectionID\fP (const \fBProjectionID\fP &r)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBProjectionID\fP &r) const "
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBProjectionID\fP &r) const "
.br
.ti -1c
.RI "template<class Archive > void \fBserialize\fP (Archive &ar, const unsigned int version)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TableID \fBtable_id\fP"
.br
.ti -1c
.RI "ProjectionOffset \fBprojection_off\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBboost::serialization::access\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBProjectionID\fP: a projection has an unique \fBProjectionID\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
