.TH "QExpr_unary" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QExpr_unary \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBQNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQExpr_unary\fP (\fBQNode\fP *arg, data_type a_type, oper_type op_types, qnodetype q_type, char *t_alias)"
.br
.ti -1c
.RI "\fBQExpr_unary\fP (\fBQExpr_unary\fP *node)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "oper_type \fBop_type\fP"
.br
.ti -1c
.RI "\fBQNode\fP * \fBnext\fP"
.br
.ti -1c
.RI "ExecFunc \fBfunction_call\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBboost::serialization::access\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
