.TH "QExpr_date_add_sub" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QExpr_date_add_sub \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qnode\&.h>\fP
.PP
Inherits \fBQNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQExpr_date_add_sub\fP ()"
.br
.ti -1c
.RI "virtual \fB~QExpr_date_add_sub\fP ()"
.br
.ti -1c
.RI "\fBQExpr_date_add_sub\fP (\fBQNode\fP *l_arg, \fBQNode\fP *r_arg, \fBdata_type\fP a_type, \fBoper_type\fP op_types, \fBqnodetype\fP q_type, \fBdata_type\fP rr_type, char *t_alias)"
.br
.ti -1c
.RI "\fBQExpr_date_add_sub\fP (\fBQExpr_date_add_sub\fP *node)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBoper_type\fP \fBop_type\fP"
.br
.ti -1c
.RI "\fBQNode\fP * \fBlnext\fP"
.br
.ti -1c
.RI "\fBQNode\fP * \fBrnext\fP"
.br
.ti -1c
.RI "\fBdata_type\fP \fBrnext_type\fP"
.br
.ti -1c
.RI "\fBExecFunc\fP \fBfunction_call\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "template<class Archive > void \fBserialize\fP (Archive &ar, const unsigned int version)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBboost::serialization::access\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QExpr_date_add_sub::QExpr_date_add_sub ()\fC [inline]\fP"

.SS "virtual QExpr_date_add_sub::~QExpr_date_add_sub ()\fC [inline]\fP, \fC [virtual]\fP"

.SS "QExpr_date_add_sub::QExpr_date_add_sub (\fBQNode\fP *l_arg, \fBQNode\fP *r_arg, \fBdata_type\fPa_type, \fBoper_type\fPop_types, \fBqnodetype\fPq_type, \fBdata_type\fPrr_type, char *t_alias)"

.PP
References QNode::actual_type, QNode::alias, lnext, NULL, rnext, rnext_type, QNode::type, and QNode::value\&.
.SS "QExpr_date_add_sub::QExpr_date_add_sub (\fBQExpr_date_add_sub\fP *node)"

.PP
References QNode::actual_type, QNode::alias, QNode::isnull, QNode::length, op_type, QNode::return_type, rnext_type, and QNode::type\&.
.SH "Member Function Documentation"
.PP 
.SS "template<class Archive > void QExpr_date_add_sub::serialize (Archive &ar, const unsigned intversion)\fC [inline]\fP, \fC [private]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class boost::serialization::access\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBExecFunc\fP QExpr_date_add_sub::function_call"

.PP
Referenced by Exec_date_add_sub(), and InitExprAtPhysicalPlan()\&.
.SS "\fBQNode\fP* QExpr_date_add_sub::lnext"

.PP
Referenced by Exec_date_add_sub(), Expr_copy(), InitExprAtLogicalPlan(), InitExprAtPhysicalPlan(), and QExpr_date_add_sub()\&.
.SS "\fBoper_type\fP QExpr_date_add_sub::op_type"

.PP
Referenced by InitExprAtPhysicalPlan(), and QExpr_date_add_sub()\&.
.SS "\fBQNode\fP * QExpr_date_add_sub::rnext"

.PP
Referenced by Exec_date_add_sub(), Expr_copy(), InitExprAtLogicalPlan(), InitExprAtPhysicalPlan(), and QExpr_date_add_sub()\&.
.SS "\fBdata_type\fP QExpr_date_add_sub::rnext_type"

.PP
Referenced by InitExprAtLogicalPlan(), and QExpr_date_add_sub()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
