.TH "QExpr_ternary" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QExpr_ternary \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qnode\&.h>\fP
.PP
Inherits \fBQNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQExpr_ternary\fP ()"
.br
.ti -1c
.RI "virtual \fB~QExpr_ternary\fP ()"
.br
.ti -1c
.RI "\fBQExpr_ternary\fP (\fBQNode\fP *arg0, \fBQNode\fP *arg1, \fBQNode\fP *arg2, \fBdata_type\fP a_type, \fBoper_type\fP op_types, \fBqnodetype\fP q_type, char *t_alias)"
.br
.ti -1c
.RI "\fBQExpr_ternary\fP (\fBQExpr_ternary\fP *node)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBoper_type\fP \fBop_type\fP"
.br
.ti -1c
.RI "\fBQNode\fP * \fBnext0\fP"
.br
.ti -1c
.RI "\fBQNode\fP * \fBnext1\fP"
.br
.ti -1c
.RI "\fBQNode\fP * \fBnext2\fP"
.br
.ti -1c
.RI "\fBExecFunc\fP \fBfunction_call\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "template<class Archive > void \fBserialize\fP (Archive &ar, const unsigned int version)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBboost::serialization::access\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QExpr_ternary::QExpr_ternary ()\fC [inline]\fP"

.SS "virtual QExpr_ternary::~QExpr_ternary ()\fC [inline]\fP, \fC [virtual]\fP"

.SS "QExpr_ternary::QExpr_ternary (\fBQNode\fP *arg0, \fBQNode\fP *arg1, \fBQNode\fP *arg2, \fBdata_type\fPa_type, \fBoper_type\fPop_types, \fBqnodetype\fPq_type, char *t_alias)"

.PP
References QNode::actual_type, QNode::alias, next0, next1, next2, NULL, QNode::type, and QNode::value\&.
.SS "QExpr_ternary::QExpr_ternary (\fBQExpr_ternary\fP *node)"

.PP
References QNode::actual_type, QNode::alias, QNode::isnull, QNode::length, op_type, QNode::return_type, and QNode::type\&.
.SH "Member Function Documentation"
.PP 
.SS "template<class Archive > void QExpr_ternary::serialize (Archive &ar, const unsigned intversion)\fC [inline]\fP, \fC [private]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class boost::serialization::access\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBExecFunc\fP QExpr_ternary::function_call"

.PP
Referenced by Exec_ternary(), and InitExprAtPhysicalPlan()\&.
.SS "\fBQNode\fP* QExpr_ternary::next0"

.PP
Referenced by Exec_ternary(), Expr_copy(), InitExprAtLogicalPlan(), InitExprAtPhysicalPlan(), and QExpr_ternary()\&.
.SS "\fBQNode\fP * QExpr_ternary::next1"

.PP
Referenced by Exec_ternary(), Expr_copy(), InitExprAtLogicalPlan(), InitExprAtPhysicalPlan(), and QExpr_ternary()\&.
.SS "\fBQNode\fP * QExpr_ternary::next2"

.PP
Referenced by Exec_ternary(), Expr_copy(), InitExprAtLogicalPlan(), InitExprAtPhysicalPlan(), and QExpr_ternary()\&.
.SS "\fBoper_type\fP QExpr_ternary::op_type"

.PP
Referenced by InitExprAtPhysicalPlan(), and QExpr_ternary()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
