.TH "QExpr_case_when" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QExpr_case_when \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBQNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQExpr_case_when\fP (vector< \fBQNode\fP * > &qual_, vector< \fBQNode\fP * > &ans_, string alias_)"
.br
.ti -1c
.RI "\fBQExpr_case_when\fP (\fBQExpr_case_when\fP *node)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "vector< \fBQNode\fP * > \fBqual\fP"
.br
.ti -1c
.RI "vector< \fBQNode\fP * > \fBans\fP"
.br
.ti -1c
.RI "\fBQNode\fP * \fBresult\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBboost::serialization::access\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
