.TH "QNode" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QNode \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNode\fP\&.
.PP
Inherited by \fBQColcumns\fP, \fBQExpr\fP, \fBQExpr_binary\fP, \fBQExpr_case_when\fP, \fBQExpr_date_add_sub\fP, \fBQExpr_in\fP, \fBQExpr_ternary\fP, and \fBQExpr_unary\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "qnodetype \fBtype\fP"
.br
.ti -1c
.RI "FuncCall \fBFuncId\fP"
.br
.ti -1c
.RI "data_type \fBactual_type\fP"
.br
.ti -1c
.RI "data_type \fBreturn_type\fP"
.br
.ti -1c
.RI "void * \fBvalue\fP"
.br
.ti -1c
.RI "int \fBlength\fP"
.br
.ti -1c
.RI "bool \fBisnull\fP"
.br
.ti -1c
.RI "TypeCastF \fBtype_cast_func\fP"
.br
.ti -1c
.RI "string \fBalias\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBboost::serialization::access\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
