.TH "RegisterStorageRespond" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RegisterStorageRespond \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Message\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRegisterStorageRespond\fP (const char *const text)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBmText\fP [\fBREGISTER_MESSAGE_LEN\fP]"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RegisterStorageRespond::RegisterStorageRespond (const char *consttext)\fC [inline]\fP, \fC [explicit]\fP"

.PP
References REGISTER_MESSAGE_LEN\&.
.SH "Member Data Documentation"
.PP 
.SS "char RegisterStorageRespond::mText[\fBREGISTER_MESSAGE_LEN\fP]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
