.TH "ResourceManagerMaster::ResourceManagerMasterActor" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ResourceManagerMaster::ResourceManagerMasterActor \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Actor\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBResourceManagerMasterActor\fP (Theron::Framework *framework, \fBResourceManagerMaster\fP *rmm)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
