.TH "ResultSet" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ResultSet \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ResultSet\&.h>\fP
.PP
Inherits \fBDynamicBlockBuffer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBResultSet\fP ()"
.br
.ti -1c
.RI "\fBResultSet\fP (const \fBResultSet\fP &r)"
.br
.ti -1c
.RI "virtual \fB~ResultSet\fP ()"
.br
.ti -1c
.RI "void \fBprint\fP () const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSchema\fP * \fBschema_\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fBcolumn_header_list_\fP"
.br
.ti -1c
.RI "double \fBquery_time_\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBprintNChar\fP (int n, char c) const "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ResultSet::ResultSet ()\fC [inline]\fP"

.SS "ResultSet::ResultSet (const \fBResultSet\fP &r)"

.PP
References column_header_list_, Schema::duplicateSchema(), query_time_, and schema_\&.
.SS "ResultSet::~ResultSet ()\fC [virtual]\fP"

.PP
References schema_\&.
.SH "Member Function Documentation"
.PP 
.SS "void ResultSet::print () const"

.PP
References column_header_list_, DynamicBlockBuffer::createIterator(), BlockStreamBase::createIterator(), Schema::getcolumn(), Schema::getColumnAddess(), Schema::getncolumns(), DynamicBlockBuffer::getNumberOftuples(), DynamicBlockBuffer::Iterator::nextBlock(), BlockStreamBase::BlockStreamTraverseIterator::nextTuple(), column_type::operate, printNChar(), query_time_, schema_, Operate::toString(), and utf8_strlen()\&.
.PP
Referenced by execute_sql_test(), Query(), submit_command(), TestNewSql(), and testServerClient()\&.
.SS "void ResultSet::printNChar (intn, charc) const\fC [private]\fP"

.PP
Referenced by print()\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<std::string> ResultSet::column_header_list_"

.PP
Referenced by claims::physical_operator::ResultCollector::CollectResult(), print(), ResultSet(), ClientListener::sendHandler(), ClientListener::sendJsonPacket(), Client::submit(), and testServerClient()\&.
.SS "double ResultSet::query_time_"

.PP
Referenced by claims::physical_operator::ResultCollector::CollectResult(), lineitem_scan_aggregation(), lineitem_scan_filter(), lineitem_scan_self_join(), claims::physical_operator::ResultCollector::Open(), print(), Query(), ResultSet(), sb_scan_aggregation(), sb_scan_filter(), sb_scan_self_join(), ClientListener::sendHandler(), Client::submit(), submit_command_repeated(), test_complete_repartition_filtered_join(), test_complete_repartition_scan_join(), test_multiple_complete_repartition_filtered_join(), test_multiple_complete_repartition_scan_join(), test_multiple_no_repartition_filtered_join(), test_multiple_no_repartition_scan_join(), test_multiple_scan_filter_Scalar_Aggregation(), test_no_repartition_filtered_join(), test_no_repartition_scan_join(), test_scan_filter_Scalar_Aggregation(), and testServerClient()\&.
.SS "\fBSchema\fP* ResultSet::schema_"

.PP
Referenced by claims::physical_operator::ResultCollector::CollectResult(), print(), ResultSet(), ClientListener::sendHandler(), ClientListener::sendJsonPacket(), Client::submit(), testServerClient(), and ~ResultSet()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
