.TH "SchemaFix" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SchemaFix \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SchemaFix\&.h>\fP
.PP
Inherits \fBSchema\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSchemaFix\fP (const std::vector< \fBcolumn_type\fP > &\fBcolumns\fP)"
.br
.ti -1c
.RI "\fBSchemaFix\fP (const \fBSchemaFix\fP &r)"
.br
.ti -1c
.RI "\fBSchemaFix\fP ()"
.br
.ti -1c
.RI "virtual \fB~SchemaFix\fP ()"
.br
.ti -1c
.RI "unsigned \fBgetTupleMaxSize\fP () const "
.br
.ti -1c
.RI "unsigned \fBgetTupleActualSize\fP (void *tuple) const "
.br
.ti -1c
.RI "unsigned \fBingetTupleActualSize\fP (void *tuple) const "
.br
.ti -1c
.RI "unsigned \fBgetTupleSize\fP () const "
.br
.ti -1c
.RI "unsigned \fBcopy\fP (void *src, void *desc) const "
.br
.ti -1c
.RI "void \fBgetColumnValue\fP (unsigned index, void *src, void *desc)"
.br
.ti -1c
.RI "void * \fBgetColumnAddess\fP (const unsigned &index, const void *const &column_start) const \fB__attribute__\fP((always_inline))"
.br
.ti -1c
.RI "int \fBgetColumnOffset\fP (unsigned index) const "
.br
.ti -1c
.RI "unsigned \fBcopyTuple\fP (void *src, void *desc) const "
.br
.ti -1c
.RI "\fBSchema::schema_type\fP \fBgetSchemaType\fP () const "
.br
.ti -1c
.RI "\fBSchema\fP * \fBgetSubSchema\fP (std::vector< unsigned >) const "
.br
.ti -1c
.RI "\fBSchema\fP * \fBduplicateSchema\fP () const "
.br
.ti -1c
.RI "void \fBaddColumn\fP (\fBcolumn_type\fP ct, unsigned size)"
.br
.ti -1c
.RI "unsigned \fBgetColumnOffset\fP (unsigned index)"
.br
.ti -1c
.RI "void \fBtoValue\fP (std::string text_tuple, void *binary_tuple, const char attr_separator)"
.br
.ti -1c
.RI "void \fBshowAccum_off\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "template<class Archive > void \fBserialize\fP (Archive &ar, const unsigned int version)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBtotalsize\fP"
.br
.ti -1c
.RI "std::vector< unsigned > \fBaccum_offsets\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBboost::serialization::access\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SchemaFix::SchemaFix (const std::vector< \fBcolumn_type\fP > &columns)"

.PP
References accum_offsets, and totalsize\&.
.SS "SchemaFix::SchemaFix (const \fBSchemaFix\fP &r)"

.PP
References accum_offsets, and totalsize\&.
.SS "SchemaFix::SchemaFix ()\fC [inline]\fP"

.PP
Referenced by duplicateSchema(), and getSubSchema()\&.
.SS "SchemaFix::~SchemaFix ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void SchemaFix::addColumn (\fBcolumn_type\fPct, unsignedsize)\fC [virtual]\fP"

.PP
Reimplemented from \fBSchema\fP\&.
.PP
References accum_offsets, Schema::columns, and totalsize\&.
.SS "unsigned SchemaFix::copy (void *src, void *desc) const\fC [inline]\fP"

.PP
References totalsize\&.
.SS "unsigned SchemaFix::copyTuple (void *src, void *desc) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBSchema\fP\&.
.PP
References totalsize\&.
.SS "\fBSchema\fP * SchemaFix::duplicateSchema () const\fC [virtual]\fP"

.PP
Implements \fBSchema\fP\&.
.PP
References Schema::columns, and SchemaFix()\&.
.SS "void* SchemaFix::getColumnAddess (const unsigned &index, const void *const &column_start) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBSchema\fP\&.
.PP
References accum_offsets\&.
.SS "int SchemaFix::getColumnOffset (unsignedindex) const\fC [virtual]\fP"

.PP
Implements \fBSchema\fP\&.
.PP
References accum_offsets\&.
.SS "unsigned SchemaFix::getColumnOffset (unsignedindex)"

.PP
References accum_offsets\&.
.SS "void SchemaFix::getColumnValue (unsignedindex, void *src, void *desc)\fC [virtual]\fP"

.PP
Implements \fBSchema\fP\&.
.PP
References accum_offsets, and Schema::columns\&.
.SS "\fBSchema::schema_type\fP SchemaFix::getSchemaType () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBSchema\fP\&.
.PP
References Schema::fixed\&.
.SS "\fBSchema\fP * SchemaFix::getSubSchema (std::vector< unsigned >index) const\fC [virtual]\fP"

.PP
Implements \fBSchema\fP\&.
.PP
References Schema::columns, and SchemaFix()\&.
.SS "unsigned SchemaFix::getTupleActualSize (void *tuple) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBSchema\fP\&.
.PP
References totalsize\&.
.SS "unsigned SchemaFix::getTupleMaxSize () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBSchema\fP\&.
.PP
References totalsize\&.
.SS "unsigned SchemaFix::getTupleSize () const\fC [inline]\fP"

.PP
References totalsize\&.
.SS "unsigned SchemaFix::ingetTupleActualSize (void *tuple) const\fC [inline]\fP"

.PP
References totalsize\&.
.SS "template<class Archive > void SchemaFix::serialize (Archive &ar, const unsigned intversion)\fC [inline]\fP, \fC [private]\fP"

.PP
References accum_offsets, and totalsize\&.
.SS "void SchemaFix::showAccum_off ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBSchema\fP\&.
.PP
References accum_offsets\&.
.SS "void SchemaFix::toValue (std::stringtext_tuple, void *binary_tuple, const charattr_separator)\fC [virtual]\fP"

.PP
Reimplemented from \fBSchema\fP\&.
.PP
References accum_offsets, and Schema::columns\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class boost::serialization::access\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::vector<unsigned> SchemaFix::accum_offsets\fC [private]\fP"

.PP
Referenced by addColumn(), getColumnAddess(), getColumnOffset(), getColumnValue(), SchemaFix(), serialize(), showAccum_off(), and toValue()\&.
.SS "unsigned SchemaFix::totalsize\fC [private]\fP"

.PP
Referenced by addColumn(), copy(), copyTuple(), getTupleActualSize(), getTupleMaxSize(), getTupleSize(), ingetTupleActualSize(), SchemaFix(), and serialize()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
