.TH "Select_list" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Select_list \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sql_node_struct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnodetype\fP \fBtype\fP"
.br
.ti -1c
.RI "int \fBisall\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBargs\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBnext\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBNode\fP* Select_list::args"

.PP
Referenced by add_table_column(), CanCancelProject1(), CanCancelProject2(), expr_to_str_for_selectlist(), get_aggregation_args(), get_all_selectlist_expression_item(), get_copy_selectlist_from_subquery(), get_orderby_column_from_selectlist(), judge_selectlist_agg_has_or_in_expr(), newSelectList(), output(), select_where_from2logicalplan(), selectlist_analysis(), selectlist_expr_analysis(), selectlist_has_agg(), selectlist_has_column(), solve_insubquery(), and subquery_has_column()\&.
.SS "int Select_list::isall"

.PP
Referenced by CanCancelProject1(), get_all_selectlist_expression_item(), get_copy_selectlist_from_subquery(), judge_selectlist_agg_has_or_in_expr(), newSelectList(), output(), selectlist_analysis(), and selectlist_expr_analysis()\&.
.SS "\fBNode\fP* Select_list::next"

.PP
Referenced by add_all_table_column(), add_table_column(), CanCancelProject1(), CanCancelProject2(), expr_to_str_for_selectlist(), get_aggregation_args(), get_all_selectlist_expression_item(), get_copy_selectlist_from_subquery(), get_orderby_column_from_selectlist(), judge_selectlist_agg_has_or_in_expr(), newSelectList(), select_where_from2logicalplan(), selectlist_analysis(), selectlist_has_agg(), selectlist_has_column(), solve_insubquery(), and subquery_has_column()\&.
.SS "\fBnodetype\fP Select_list::type"

.PP
Referenced by newSelectList()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
