.TH "semaphore" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
semaphore \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsemaphore\fP (int initialValue=0)"
.br
.ti -1c
.RI "void \fBset_value\fP (int value)"
.br
.ti -1c
.RI "void \fBpost\fP (int times=1)"
.br
.ti -1c
.RI "void \fBwait\fP ()"
.br
.ti -1c
.RI "bool \fBtimed_wait\fP (int millisecond)"
.br
.ti -1c
.RI "bool \fBtry_wait\fP ()"
.br
.ti -1c
.RI "void \fBdestroy\fP ()"
.br
.ti -1c
.RI "int \fBget_value\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
