.TH "Show_stmt" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Show_stmt \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sql_node_struct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnodetype\fP \fBtype\fP"
.br
.ti -1c
.RI "bool \fBfull\fP"
.br
.ti -1c
.RI "int \fBshow_type\fP"
.br
.ti -1c
.RI "char * \fBdatabase_name\fP"
.br
.ti -1c
.RI "char * \fBlike_string\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char* Show_stmt::database_name"

.PP
Referenced by newShowStmt()\&.
.SS "bool Show_stmt::full"

.PP
Referenced by newShowStmt()\&.
.SS "char* Show_stmt::like_string"

.PP
Referenced by newShowStmt()\&.
.SS "int Show_stmt::show_type"

.PP
Referenced by newShowStmt(), and ShowTable()\&.
.SS "\fBnodetype\fP Show_stmt::type"

.PP
Referenced by newShowStmt()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
