.TH "StatisticOnTable" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StatisticOnTable \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Statistic\&.h>\fP
.PP
Inherits \fBHistogram\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStatisticOnTable\fP ()"
.br
.ti -1c
.RI "\fBStatisticOnTable\fP (unsigned bucketCnt)"
.br
.ti -1c
.RI "\fBHistogram\fP * \fBgetPartStat\fP (const \fBPartitionID\fP partID)"
.br
.ti -1c
.RI "void \fBdestory\fP ()"
.br
.ti -1c
.RI "virtual \fB~StatisticOnTable\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "boost::unordered_map
.br
< \fBPartitionID\fP, \fBHistogram\fP * > \fBm_partStat\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "StatisticOnTable::StatisticOnTable ()"

.SS "StatisticOnTable::StatisticOnTable (unsignedbucketCnt)"

.SS "StatisticOnTable::~StatisticOnTable ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void StatisticOnTable::destory ()"

.PP
References Histogram::destory(), and m_partStat\&.
.SS "\fBHistogram\fP * StatisticOnTable::getPartStat (const \fBPartitionID\fPpartID)"

.PP
References m_partStat\&.
.SH "Member Data Documentation"
.PP 
.SS "boost::unordered_map< \fBPartitionID\fP, \fBHistogram\fP* > StatisticOnTable::m_partStat\fC [private]\fP"

.PP
Referenced by destory(), and getPartStat()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
