.TH "StorageBudgetMessage" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StorageBudgetMessage \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Message\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStorageBudgetMessage\fP (const int &\fBdisk_budget\fP, const int &\fBmemory_budget\fP, const int &\fBnodeid\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBdisk_budget\fP"
.br
.ti -1c
.RI "int \fBmemory_budget\fP"
.br
.ti -1c
.RI "int \fBnodeid\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "StorageBudgetMessage::StorageBudgetMessage (const int &disk_budget, const int &memory_budget, const int &nodeid)\fC [inline]\fP, \fC [explicit]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int StorageBudgetMessage::disk_budget"

.PP
Referenced by ResourceManagerMaster::ResourceManagerMasterActor::ReceiveStorageBudgetReport()\&.
.SS "int StorageBudgetMessage::memory_budget"

.PP
Referenced by ResourceManagerMaster::ResourceManagerMasterActor::ReceiveStorageBudgetReport()\&.
.SS "int StorageBudgetMessage::nodeid"

.PP
Referenced by ResourceManagerMaster::ResourceManagerMasterActor::ReceiveStorageBudgetReport(), and BlockManagerMaster::BlockManagerMasterActor::workerRegister()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
