.TH "StreamBuffer" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StreamBuffer \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStreamBuffer\fP (unsigned length=10000)"
.br
.ti -1c
.RI "void \fBReorganize\fP ()"
.br
.ti -1c
.RI "void \fBMoveForwardEnd\fP (unsigned count)"
.br
.ti -1c
.RI "char * \fBGetCurrent\fP () const "
.br
.ti -1c
.RI "unsigned \fBGetFreedBufferCount\fP () const "
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "bool \fBIsEmpty\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
