.TH "StreamBuffer" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StreamBuffer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <StreamBuffer\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStreamBuffer\fP ()"
.br
.ti -1c
.RI "\fBStreamBuffer\fP (unsigned length=10000)"
.br
.ti -1c
.RI "\fB~StreamBuffer\fP ()"
.br
.ti -1c
.RI "void \fBReorganize\fP ()"
.br
.ti -1c
.RI "void \fBMoveForwardEnd\fP (unsigned count)"
.br
.ti -1c
.RI "char * \fBGetCurrent\fP () const "
.br
.ti -1c
.RI "unsigned \fBGetFreedBufferCount\fP () const "
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "bool \fBIsEmpty\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "char * \fBbuffer_\fP = \fBNULL\fP"
.br
.ti -1c
.RI "unsigned int \fBcur_\fP = 0"
.br
.ti -1c
.RI "unsigned int \fBend_\fP = 0"
.br
.ti -1c
.RI "unsigned int \fBlength_\fP = 0"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static \fBStreamBuffer\fP * \fBinstance_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "StreamBuffer::StreamBuffer ()"

.SS "StreamBuffer::StreamBuffer (unsignedlength = \fC10000\fP)\fC [inline]\fP"

.SS "StreamBuffer::~StreamBuffer ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void StreamBuffer::Clear ()\fC [inline]\fP"

.SS "char* StreamBuffer::GetCurrent () const\fC [inline]\fP"

.PP
Referenced by GetInputSQL()\&.
.SS "unsigned StreamBuffer::GetFreedBufferCount () const\fC [inline]\fP"

.PP
Referenced by GetInputSQL()\&.
.SS "bool StreamBuffer::IsEmpty ()\fC [inline]\fP"

.PP
Referenced by GetInputSQL()\&.
.SS "void StreamBuffer::MoveForwardEnd (unsignedcount)"

.PP
References cur_, ASTParserLogging::elog(), end_, length_, and Reorganize()\&.
.PP
Referenced by GetInputSQL()\&.
.SS "void StreamBuffer::Reorganize ()"

.PP
Referenced by MoveForwardEnd()\&.
.SH "Member Data Documentation"
.PP 
.SS "char* StreamBuffer::buffer_ = \fBNULL\fP\fC [private]\fP"

.SS "unsigned int StreamBuffer::cur_ = 0\fC [private]\fP"

.PP
Referenced by MoveForwardEnd()\&.
.SS "unsigned int StreamBuffer::end_ = 0\fC [private]\fP"

.PP
Referenced by MoveForwardEnd()\&.
.SS "\fBStreamBuffer\fP* StreamBuffer::instance_\fC [static]\fP, \fC [private]\fP"

.SS "unsigned int StreamBuffer::length_ = 0\fC [private]\fP"

.PP
Referenced by MoveForwardEnd()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
