.TH "Subquery" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Subquery \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sql_node_struct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnodetype\fP \fBtype\fP"
.br
.ti -1c
.RI "char * \fBquerystring\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBnext\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBNode\fP* Subquery::next"

.PP
Referenced by newSubquery()\&.
.SS "char* Subquery::querystring"

.PP
Referenced by newSubquery()\&.
.SS "\fBnodetype\fP Subquery::type"

.PP
Referenced by newSubquery()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
