.TH "SubTuple" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SubTuple \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TupleConvertor\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSubTuple\fP (\fBSchema\fP *srouce, \fBSchema\fP *target, std::vector< unsigned > index)"
.br
.ti -1c
.RI "void \fBgetSubTuple\fP (void *&tuple, void *&target)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBSchema\fP * \fBsource_schema_\fP"
.br
.ti -1c
.RI "\fBSchema\fP * \fBtarget_schema_\fP"
.br
.ti -1c
.RI "std::vector< unsigned > \fBindex_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SubTuple::SubTuple (\fBSchema\fP *srouce, \fBSchema\fP *target, std::vector< unsigned >index)"

.SH "Member Function Documentation"
.PP 
.SS "void SubTuple::getSubTuple (void *&tuple, void *&target)"

.PP
References Operate::assignment(), Schema::getcolumn(), Schema::getColumnAddess(), index_, column_type::operate, source_schema_, and target_schema_\&.
.PP
Referenced by sub_tuple_test()\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<unsigned> SubTuple::index_\fC [private]\fP"

.PP
Referenced by getSubTuple()\&.
.SS "\fBSchema\fP* SubTuple::source_schema_\fC [private]\fP"

.PP
Referenced by getSubTuple()\&.
.SS "\fBSchema\fP* SubTuple::target_schema_\fC [private]\fP"

.PP
Referenced by getSubTuple()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
