.TH "SubTuple" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SubTuple \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSubTuple\fP (\fBSchema\fP *srouce, \fBSchema\fP *target, std::vector< unsigned > index)"
.br
.ti -1c
.RI "void \fBgetSubTuple\fP (void *&tuple, void *&target)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
