.TH "Tablelist" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tablelist \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sql_node_struct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnodetype\fP \fBtype\fP"
.br
.ti -1c
.RI "char * \fBname1\fP"
.br
.ti -1c
.RI "char * \fBname2\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBnext\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char* Tablelist::name1"

.PP
Referenced by newTableList()\&.
.SS "char* Tablelist::name2"

.PP
Referenced by newTableList()\&.
.SS "\fBNode\fP* Tablelist::next"

.PP
Referenced by newTableList()\&.
.SS "\fBnodetype\fP Tablelist::type"

.PP
Referenced by newTableList()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
