.TH "Table" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Table \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sql_node_struct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnodetype\fP \fBtype\fP"
.br
.ti -1c
.RI "char * \fBdbname\fP"
.br
.ti -1c
.RI "char * \fBtablename\fP"
.br
.ti -1c
.RI "char * \fBastablename\fP"
.br
.ti -1c
.RI "int \fBissubquery\fP"
.br
.ti -1c
.RI "int \fBtable_id\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBsubquery\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBwhcdn\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char * Table::astablename"

.PP
Referenced by add_all_table_column(), fromlist_analysis(), fromlist_has_astablename(), fromlist_table_is_unique(), judgepos(), newTable(), output(), table_has_column(), and where_from2logicalplan()\&.
.SS "char* Table::dbname"

.PP
Referenced by newTable(), and output()\&.
.SS "int Table::issubquery"

.PP
Referenced by add_all_table_column(), fromlist_analysis(), fromlist_has_astablename(), newTable(), output(), table_has_column(), and where_from2logicalplan()\&.
.SS "\fBNode\fP* Table::subquery"

.PP
Referenced by add_all_table_column(), fromlist_analysis(), fromlist_has_astablename(), newTable(), output(), table_has_column(), and where_from2logicalplan()\&.
.SS "int Table::table_id"

.SS "char * Table::tablename"

.PP
Referenced by add_all_table_column(), fromlist_analysis(), fromlist_has_astablename(), newTable(), output(), table_has_column(), and where_from2logicalplan()\&.
.SS "\fBnodetype\fP Table::type"

.PP
Referenced by newTable()\&.
.SS "\fBNode\fP* Table::whcdn"

.PP
Referenced by newTable(), output(), setocposition(), setwcposition(), and where_from2logicalplan()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
