.TH "TableStatistic" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TableStatistic \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBaddAttributeStatistics\fP (const \fBAttributeID\fP &attr_id, \fBAttributeStatistics\fP *stat)"
.br
.ti -1c
.RI "\fBAttributeStatistics\fP * \fBgetAttributeStatistics\fP (const \fBAttributeID\fP &attr_id) const "
.br
.ti -1c
.RI "unsigned long \fBgetCardinality\fP () const "
.br
.ti -1c
.RI "void \fBprint\fP () const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned long \fBnumber_of_tuples_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
