.TH "ThreadSafe" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ThreadSafe \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ThreadSafe\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBThreadSafe\fP ()"
.br
.ti -1c
.RI "virtual \fB~ThreadSafe\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static hostent * \fBgethostbyname_ts\fP (hostent &v, const char *host)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static \fBSpineLock\fP \fBgethostbyname_lock_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ThreadSafe::ThreadSafe ()"

.SS "ThreadSafe::~ThreadSafe ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "static hostent* ThreadSafe::gethostbyname_ts (hostent &v, const char *host)\fC [inline]\fP, \fC [static]\fP"

.PP
References SpineLock::acquire(), gethostbyname_lock_, and SpineLock::release()\&.
.PP
Referenced by AdaptiveEndPoint::SayHelloToCoordinator()\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSpineLock\fP ThreadSafe::gethostbyname_lock_\fC [static]\fP, \fC [private]\fP"

.PP
Referenced by gethostbyname_ts()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
