.TH "ThreadPool" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ThreadPool \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBThread_Pool_init\fP (int thread_count_in_pool_)"
.br
.ti -1c
.RI "void * \fBthread_exec_with_cond\fP (void *arg)"
.br
.ti -1c
.RI "void \fBbind_cpu\fP ()"
.br
.ti -1c
.RI "void \fBadd_task\fP (void *(*)(void *), void *arg, bool e=false)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void * \fBthread_exec\fP (void *arg)"
.br
.ti -1c
.RI "static void \fBdestroy_pool\fP (\fBThreadPool\fP *tp)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
