.TH "ThreadContext" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ThreadContext \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBBlockStreamJoinIterator::join_thread_context\fP, \fBBlockStreamNestLoopJoinIterator::join_thread_context\fP, \fBBlockStreamProjectIterator::project_thread_context\fP, \fBExpandableBlockStreamFilter::filter_thread_context\fP, and \fBExpandableBlockStreamProjectionScan::scan_thread_context\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int32_t \fBget_locality_\fP () const "
.br
.ti -1c
.RI "void \fBset_locality_\fP (int32_t locality)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
