.TH "ThreadManager" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ThreadManager \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ThreadManager\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~ThreadManager\fP ()"
.br
.ti -1c
.RI "void \fBadd\fP (pthread_t t)"
.br
.ti -1c
.RI "void \fBremove\fP (pthread_t t)"
.br
.ti -1c
.RI "int \fBgetNumOfThreads\fP () const "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBThreadManager\fP * \fBgetInstance\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBThreadManager\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::set< pthread_t > \fBthreads_\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static \fBThreadManager\fP * \fBinstance_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ThreadManager::~ThreadManager ()\fC [virtual]\fP"

.SS "ThreadManager::ThreadManager ()\fC [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void ThreadManager::add (pthread_tt)"

.SS "static \fBThreadManager\fP* ThreadManager::getInstance ()\fC [static]\fP"

.SS "int ThreadManager::getNumOfThreads () const"

.SS "void ThreadManager::remove (pthread_tt)"

.SH "Member Data Documentation"
.PP 
.SS "\fBThreadManager\fP* ThreadManager::instance_\fC [static]\fP, \fC [private]\fP"

.SS "std::set<pthread_t> ThreadManager::threads_\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
