.TH "Truncate_stmt" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Truncate_stmt \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sql_node_struct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnodetype\fP \fBtype\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char* Truncate_stmt::name"

.PP
Referenced by newTruncateStmt()\&.
.SS "\fBnodetype\fP Truncate_stmt::type"

.PP
Referenced by newTruncateStmt()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
