.TH "ttmath::StopCalculating" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ttmath::StopCalculating \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ttmathtypes\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBWasStopSignal\fP () const volatile"
.br
.ti -1c
.RI "virtual \fB~StopCalculating\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
this simple class can be used in multithreading model (you can write your own class derived from this one)
.PP
for example: in some functions like Factorial() /at the moment only Factorial/ you can give a pointer to the 'stop object', if the method \fBWasStopSignal()\fP of this object returns true that means we should break the calculating and return 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ttmath::StopCalculating::~StopCalculating ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual bool ttmath::StopCalculating::WasStopSignal () const volatile\fC [inline]\fP, \fC [virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
