.TH "common/types/ttmath/ttmathuint.h" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common/types/ttmath/ttmathuint.h \- 
.PP
template class UInt<uint>  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include 'ttmathtypes\&.h'\fP
.br
\fC#include 'ttmathmisc\&.h'\fP
.br
\fC#include 'ttmathuint_x86\&.h'\fP
.br
\fC#include 'ttmathuint_x86_64\&.h'\fP
.br
\fC#include 'ttmathuint_noasm\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBttmath::UInt< value_size >\fP"
.br
.RI "\fI\fBUInt\fP implements a big integer value without a sign\&. \fP"
.ti -1c
.RI "class \fBttmath::UInt< 0 >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBttmath\fP"
.br
.RI "\fIa namespace for the TTMath library \fP"
.in -1c
.SH "Detailed Description"
.PP 
template class UInt<uint> 


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
