.TH "ttmath::UInt< 0 >" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ttmath::UInt< 0 > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ttmathuint\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBMul2Big\fP (const \fBUInt\fP< 0 > &, \fBUInt\fP< 0 > &)"
.br
.ti -1c
.RI "void \fBSetZero\fP ()"
.br
.ti -1c
.RI "\fBuint\fP \fBAddTwoInts\fP (\fBuint\fP, \fBuint\fP, \fBuint\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuint\fP \fBtable\fP [1]"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>class ttmath::UInt< 0 >"
this specialization is needed in order to not confused the compiler 'error: ISO C++ forbids zero-size array' when compiling Mul3Big2() method 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
