.TH "common/types/ttmath/ttmathint.h" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common/types/ttmath/ttmathint.h \- 
template class Int<uint>  

.SH SYNOPSIS
.br
.PP
\fC#include 'ttmathuint\&.h'\fP
.br
\fC#include 'boost/unordered_map\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBttmath::Int< value_size >\fP"
.br
.RI "\fI\fBInt\fP implements a big integer value with a sign\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBttmath\fP"
.br
.RI "\fIa namespace for the TTMath library \fP"
.in -1c
.SH "Detailed Description"
.PP 
template class Int<uint> 


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
