.TH "ttmath::ExceptionInfo" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ttmath::ExceptionInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ttmathtypes\&.h>\fP
.PP
Inherited by \fBttmath::ReferenceError\fP, and \fBttmath::RuntimeError\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExceptionInfo\fP ()"
.br
.ti -1c
.RI "\fBExceptionInfo\fP (const char *\fBf\fP, int l)"
.br
.ti -1c
.RI "std::string \fBWhere\fP () const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "const char * \fBfile\fP"
.br
.ti -1c
.RI "int \fBline\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
a small class which is useful when compiling with gcc
.PP
object of this type holds the name and the line of a file in which the macro TTMATH_ASSERT or TTMATH_REFERENCE_ASSERT was used 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ttmath::ExceptionInfo::ExceptionInfo ()\fC [inline]\fP"

.SS "ttmath::ExceptionInfo::ExceptionInfo (const char *f, intl)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "std::string ttmath::ExceptionInfo::Where () const\fC [inline]\fP"

.PP
References file, and line\&.
.PP
Referenced by ttmath::ReferenceError::Where(), and ttmath::RuntimeError::Where()\&.
.SH "Member Data Documentation"
.PP 
.SS "const char* ttmath::ExceptionInfo::file\fC [private]\fP"

.PP
Referenced by Where()\&.
.SS "int ttmath::ExceptionInfo::line\fC [private]\fP"

.PP
Referenced by Where()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
