.TH "ttmath::ExceptionInfo" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ttmath::ExceptionInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ttmathtypes\&.h>\fP
.PP
Inherited by \fBttmath::ReferenceError\fP, and \fBttmath::RuntimeError\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExceptionInfo\fP (const char *f, int l)"
.br
.ti -1c
.RI "std::string \fBWhere\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
a small class which is useful when compiling with gcc
.PP
object of this type holds the name and the line of a file in which the macro TTMATH_ASSERT or TTMATH_REFERENCE_ASSERT was used 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
