.TH "Tuple" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tuple \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBa1\fP"
.br
.ti -1c
.RI "char \fBname\fP [14]"
.br
.ti -1c
.RI "uint64_t \fBa2\fP"
.br
.ti -1c
.RI "int32_t \fBa3\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
