.TH "TupleConvertor" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TupleConvertor \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsub_tuple\fP (const \fBSchema\fP *&src_s, const \fBSchema\fP *&des_c, const void *const &tuple, void *desc, std::vector< unsigned > index)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
