.TH "Tuple" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tuple \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBa1\fP"
.br
.ti -1c
.RI "char \fBname\fP [14]"
.br
.ti -1c
.RI "uint64_t \fBa2\fP"
.br
.ti -1c
.RI "int32_t \fBa3\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int32_t Tuple::a1"

.PP
Referenced by sub_tuple_test()\&.
.SS "uint64_t Tuple::a2"

.PP
Referenced by sub_tuple_test()\&.
.SS "int32_t Tuple::a3"

.PP
Referenced by sub_tuple_test()\&.
.SS "char Tuple::name[14]"

.PP
Referenced by sub_tuple_test()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
