.TH "TypeCast" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TypeCast \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static TypeCastF \fBtype_cast_func\fP [DATA_TYPE_NUMBER][DATA_TYPE_NUMBER]"
.br
.ti -1c
.RI "static TypeCastFunction \fBtype_cast_functions\fP [DATA_TYPE_NUMBER][DATA_TYPE_NUMBER]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
