.TH "UniformRangePartitionFunction" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UniformRangePartitionFunction \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hash\&.h>\fP
.PP
Inherits \fBPartitionFunction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUniformRangePartitionFunction\fP ()"
.br
.ti -1c
.RI "\fBUniformRangePartitionFunction\fP (int min, int max, unsigned int k)"
.br
.ti -1c
.RI "\fB~UniformRangePartitionFunction\fP ()"
.br
.ti -1c
.RI "unsigned int \fBget_partition_value\fP (const int &value) const "
.br
.ti -1c
.RI "unsigned int \fBget_partition_value\fP (const unsigned long &value) const "
.br
.ti -1c
.RI "unsigned int \fBget_partition_value\fP (const double &value) const "
.br
.ti -1c
.RI "\fBPartitionStyle\fP \fBgetPartitionFashion\fP () const "
.br
.ti -1c
.RI "unsigned \fBgetNumberOfPartitions\fP () const "
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "template<class Archive > void \fBserialize\fP (Archive &ar, const unsigned int version)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBboost::serialization::access\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UniformRangePartitionFunction::UniformRangePartitionFunction ()\fC [inline]\fP"

.SS "UniformRangePartitionFunction::UniformRangePartitionFunction (intmin, intmax, unsigned intk)\fC [inline]\fP"

.SS "UniformRangePartitionFunction::~UniformRangePartitionFunction ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "unsigned int UniformRangePartitionFunction::get_partition_value (const int &value) const\fC [inline]\fP, \fC [virtual]\fP"
Returns the bucket number $n\in[0,k)$ for this \fIvalue\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvalue\fP Value to hash\&. Must be within bounds\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Bucket number\&. 
.RE
.PP

.PP
Implements \fBPartitionFunction\fP\&.
.PP
References PartitionFunction::k_, PartitionFunction::max_, and PartitionFunction::min_\&.
.SS "unsigned int UniformRangePartitionFunction::get_partition_value (const unsigned long &value) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBPartitionFunction\fP\&.
.PP
References PartitionFunction::k_, PartitionFunction::max_, and PartitionFunction::min_\&.
.SS "unsigned int UniformRangePartitionFunction::get_partition_value (const double &value) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBPartitionFunction\fP\&.
.PP
References PartitionFunction::k_, PartitionFunction::max_, and PartitionFunction::min_\&.
.SS "unsigned UniformRangePartitionFunction::getNumberOfPartitions () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBPartitionFunction\fP\&.
.PP
References PartitionFunction::k_\&.
.SS "\fBPartitionFunction::PartitionStyle\fP UniformRangePartitionFunction::getPartitionFashion () const\fC [virtual]\fP"

.PP
Implements \fBPartitionFunction\fP\&.
.PP
References PartitionFunction::range_f\&.
.SS "template<class Archive > void UniformRangePartitionFunction::serialize (Archive &ar, const unsigned intversion)\fC [inline]\fP, \fC [private]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class boost::serialization::access\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
