.TH "UniformInt" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UniformInt \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <data_distribution_generator\&.h>\fP
.PP
Inherits \fBColumnDistribution\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUniformInt\fP (int min=0, int max=1024 *1024, int seed=0)"
.br
.ti -1c
.RI "\fB~UniformInt\fP ()"
.br
.ti -1c
.RI "virtual void \fBgiveRandomValue\fP (void *column_addr)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::random_device \fBrd_\fP"
.br
.ti -1c
.RI "std::mt19937 \fBgen_\fP"
.br
.ti -1c
.RI "std::uniform_int_distribution \fBdis_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UniformInt::UniformInt (intmin = \fC0\fP, intmax = \fC1024*1024\fP, intseed = \fC0\fP)"

.PP
References gen_\&.
.SS "UniformInt::~UniformInt ()"

.SH "Member Function Documentation"
.PP 
.SS "void UniformInt::giveRandomValue (void *column_addr)\fC [virtual]\fP"

.PP
Reimplemented from \fBColumnDistribution\fP\&.
.PP
References dis_, and gen_\&.
.SH "Member Data Documentation"
.PP 
.SS "std::uniform_int_distribution UniformInt::dis_\fC [private]\fP"

.PP
Referenced by giveRandomValue()\&.
.SS "std::mt19937 UniformInt::gen_\fC [private]\fP"

.PP
Referenced by giveRandomValue(), and UniformInt()\&.
.SS "std::random_device UniformInt::rd_\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
