.TH "variable" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
variable \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBtable_column\fP"
.br
.ti -1c
.RI "const char * \fBtable_name\fP"
.br
.ti -1c
.RI "const char * \fBcolumn_name\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
