.TH "yy_trans_info" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
yy_trans_info \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBflex_int32_t\fP \fByy_verify\fP"
.br
.ti -1c
.RI "\fBflex_int32_t\fP \fByy_nxt\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBflex_int32_t\fP yy_trans_info::yy_nxt"

.SS "\fBflex_int32_t\fP yy_trans_info::yy_verify"


.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
