.TH "yy_trans_info" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
yy_trans_info \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "flex_int32_t \fByy_verify\fP"
.br
.ti -1c
.RI "flex_int32_t \fByy_nxt\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
