.TH "yyGLRStackItem" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
yyGLRStackItem \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fByyGLRState\fP \fByystate\fP"
.br
.ti -1c
.RI "\fByySemanticOption\fP \fByyoption\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Type of the items in the GLR stack\&. The yyisState field indicates which item of the union is valid\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
