.TH "yyGLRStack" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
yyGLRStack \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fByyerrState\fP"
.br
.ti -1c
.RI "int \fByyerrcnt\fP"
.br
.ti -1c
.RI "int \fByyrawchar\fP"
.br
.ti -1c
.RI "\fBYYSTYPE\fP \fByyval\fP"
.br
.ti -1c
.RI "YYJMP_BUF \fByyexception_buffer\fP"
.br
.ti -1c
.RI "\fByyGLRStackItem\fP * \fByyitems\fP"
.br
.ti -1c
.RI "\fByyGLRStackItem\fP * \fByynextFree\fP"
.br
.ti -1c
.RI "size_t \fByyspaceLeft\fP"
.br
.ti -1c
.RI "\fByyGLRState\fP * \fByysplitPoint\fP"
.br
.ti -1c
.RI "\fByyGLRState\fP * \fByylastDeleted\fP"
.br
.ti -1c
.RI "\fByyGLRStateSet\fP \fByytops\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
