.TH "yyGLRState" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
yyGLRState \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fByybool\fP \fByyisState\fP"
.br
.ti -1c
.RI "\fByybool\fP \fByyresolved\fP"
.br
.ti -1c
.RI "\fByyStateNum\fP \fByylrState\fP"
.br
.ti -1c
.RI "\fByyGLRState\fP * \fByypred\fP"
.br
.ti -1c
.RI "size_t \fByyposn\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fByySemanticOption\fP * \fByyfirstVal\fP"
.br
.ti -1c
.RI "   \fBYYSTYPE\fP \fByysval\fP"
.br
.ti -1c
.RI "} \fByysemantics\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fByySemanticOption\fP * \fByyfirstVal\fP"
.br
.ti -1c
.RI "   \fBYYSTYPE\fP \fByysval\fP"
.br
.ti -1c
.RI "} \fByysemantics\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fByySemanticOption\fP* yyGLRState::yyfirstVal"
First in a chain of alternative reductions producing the non-terminal corresponding to this state, threaded through yynext\&. 
.PP
Referenced by yyaddDeferredAction(), yydestroyGLRState(), yyexpandGLRStack(), yyglrShiftDefer(), yymergeOptionSets(), and yyresolveValue()\&.
.SS "\fByybool\fP yyGLRState::yyisState"
Type tag: always true\&. 
.PP
Referenced by yynewGLRStackItem()\&.
.SS "\fByyStateNum\fP yyGLRState::yylrState"
Number of corresponding LALR(1) machine state\&. 
.PP
Referenced by yydestroyGLRState(), yyglrReduce(), yyglrShift(), yyglrShiftDefer(), yyparse(), yyprocessOneStack(), yyrecoverSyntaxError(), yyreportSyntaxError(), and yyresolveValue()\&.
.SS "size_t yyGLRState::yyposn"
Source position of the first token produced by my symbol 
.PP
Referenced by yyglrReduce(), yyglrShift(), yyglrShiftDefer(), yyidenticalOptions(), yyparse(), and yyrecoverSyntaxError()\&.
.SS "\fByyGLRState\fP * yyGLRState::yypred"
Preceding state in this stack 
.PP
Referenced by yycompressStack(), yydestroyGLRState(), yydoAction(), yyexpandGLRStack(), yyfillin(), yyglrReduce(), yyglrShift(), yyglrShiftDefer(), yyidenticalOptions(), yymergeOptionSets(), yyparse(), yyrecoverSyntaxError(), yyresolveAction(), yyresolveStack(), and yyresolveStates()\&.
.SS "\fByybool\fP yyGLRState::yyresolved"
Type tag for yysemantics\&. If true, yysval applies, otherwise yyfirstVal applies\&. 
.PP
Referenced by yydestroyGLRState(), yyexpandGLRStack(), yyfillin(), yyglrShift(), yyglrShiftDefer(), yymergeOptionSets(), yyresolveStates(), and yyresolveValue()\&.
.SS "union { \&.\&.\&. }   yyGLRState::yysemantics"

.SS "union { \&.\&.\&. }   yyGLRState::yysemantics"

.PP
Referenced by yyaddDeferredAction(), yydestroyGLRState(), yyexpandGLRStack(), yyfillin(), yyglrShift(), yyglrShiftDefer(), yymergeOptionSets(), yyresolveValue(), and yyuserAction()\&.
.SS "\fBYYSTYPE\fP yyGLRState::yysval"
Semantic value for this state\&. 
.PP
Referenced by yydestroyGLRState(), yyfillin(), yyglrShift(), yymergeOptionSets(), yyresolveValue(), and yyuserAction()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
