.TH "yyGLRStackItem" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
yyGLRStackItem \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fByyGLRState\fP \fByystate\fP"
.br
.ti -1c
.RI "\fByySemanticOption\fP \fByyoption\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Type of the items in the GLR stack\&. The yyisState field indicates which item of the union is valid\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fByySemanticOption\fP yyGLRStackItem::yyoption"

.PP
Referenced by yyaddDeferredAction(), and yyexpandGLRStack()\&.
.SS "\fByyGLRState\fP yyGLRStackItem::yystate"

.PP
Referenced by yycompressStack(), yydoAction(), yyexpandGLRStack(), yyglrShift(), yyglrShiftDefer(), yynewGLRStackItem(), yyresolveAction(), and yyuserAction()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
