.TH "yyguts_t" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
yyguts_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBYY_EXTRA_TYPE\fP \fByyextra_r\fP"
.br
.ti -1c
.RI "FILE * \fByyin_r\fP"
.br
.ti -1c
.RI "FILE * \fByyout_r\fP"
.br
.ti -1c
.RI "size_t \fByy_buffer_stack_top\fP"
.br
.ti -1c
.RI "size_t \fByy_buffer_stack_max\fP"
.br
.ti -1c
.RI "\fBYY_BUFFER_STATE\fP * \fByy_buffer_stack\fP"
.br
.ti -1c
.RI "char \fByy_hold_char\fP"
.br
.ti -1c
.RI "\fByy_size_t\fP \fByy_n_chars\fP"
.br
.ti -1c
.RI "\fByy_size_t\fP \fByyleng_r\fP"
.br
.ti -1c
.RI "char * \fByy_c_buf_p\fP"
.br
.ti -1c
.RI "int \fByy_init\fP"
.br
.ti -1c
.RI "int \fByy_start\fP"
.br
.ti -1c
.RI "int \fByy_did_buffer_switch_on_eof\fP"
.br
.ti -1c
.RI "int \fByy_start_stack_ptr\fP"
.br
.ti -1c
.RI "int \fByy_start_stack_depth\fP"
.br
.ti -1c
.RI "int * \fByy_start_stack\fP"
.br
.ti -1c
.RI "\fByy_state_type\fP \fByy_last_accepting_state\fP"
.br
.ti -1c
.RI "char * \fByy_last_accepting_cpos\fP"
.br
.ti -1c
.RI "int \fByylineno_r\fP"
.br
.ti -1c
.RI "int \fByy_flex_debug_r\fP"
.br
.ti -1c
.RI "char * \fByytext_r\fP"
.br
.ti -1c
.RI "int \fByy_more_flag\fP"
.br
.ti -1c
.RI "int \fByy_more_len\fP"
.br
.ti -1c
.RI "\fBYYSTYPE\fP * \fByylval_r\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBYY_BUFFER_STATE\fP * yyguts_t::yy_buffer_stack"
Stack as an array\&. 
.PP
Referenced by yy_init_globals(), yyensure_buffer_stack(), and yylex_destroy()\&.
.SS "size_t yyguts_t::yy_buffer_stack_max"
capacity of stack\&. 
.PP
Referenced by yy_init_globals(), and yyensure_buffer_stack()\&.
.SS "size_t yyguts_t::yy_buffer_stack_top"
index of top of stack\&. 
.PP
Referenced by yy_init_globals(), yyensure_buffer_stack(), yypop_buffer_state(), and yypush_buffer_state()\&.
.SS "char * yyguts_t::yy_c_buf_p"

.PP
Referenced by input(), while(), yy_get_next_buffer(), yy_get_previous_state(), yy_init_globals(), yy_load_buffer_state(), yy_switch_to_buffer(), yy_try_NUL_trans(), yypush_buffer_state(), and yyunput()\&.
.SS "int yyguts_t::yy_did_buffer_switch_on_eof"

.PP
Referenced by input(), while(), yy_switch_to_buffer(), yypop_buffer_state(), and yypush_buffer_state()\&.
.SS "int yyguts_t::yy_flex_debug_r"

.SS "char yyguts_t::yy_hold_char"

.PP
Referenced by input(), while(), yy_load_buffer_state(), yy_switch_to_buffer(), yypush_buffer_state(), and yyunput()\&.
.SS "int yyguts_t::yy_init"

.PP
Referenced by if(), and yy_init_globals()\&.
.SS "char * yyguts_t::yy_last_accepting_cpos"

.PP
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans()\&.
.SS "\fByy_state_type\fP yyguts_t::yy_last_accepting_state"

.PP
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans()\&.
.SS "int yyguts_t::yy_more_flag"

.SS "int yyguts_t::yy_more_len"

.SS "\fByy_size_t\fP yyguts_t::yy_n_chars"

.PP
Referenced by input(), while(), yy_get_next_buffer(), yy_load_buffer_state(), yy_switch_to_buffer(), yypush_buffer_state(), and yyunput()\&.
.SS "int yyguts_t::yy_start"

.PP
Referenced by if(), while(), yy_get_previous_state(), and yy_init_globals()\&.
.SS "int * yyguts_t::yy_start_stack"

.PP
Referenced by yy_init_globals(), and yylex_destroy()\&.
.SS "int yyguts_t::yy_start_stack_depth"

.PP
Referenced by yy_init_globals()\&.
.SS "int yyguts_t::yy_start_stack_ptr"

.PP
Referenced by yy_init_globals()\&.
.SS "\fBYY_EXTRA_TYPE\fP yyguts_t::yyextra_r"

.SS "FILE * yyguts_t::yyin_r"

.SS "\fByy_size_t\fP yyguts_t::yyleng_r"

.SS "int yyguts_t::yylineno_r"

.SS "\fBYYSTYPE\fP * yyguts_t::yylval_r"

.SS "FILE * yyguts_t::yyout_r"

.SS "char * yyguts_t::yytext_r"


.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
