.TH "yyguts_t" 3 "Fri Oct 9 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
yyguts_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "YY_EXTRA_TYPE \fByyextra_r\fP"
.br
.ti -1c
.RI "FILE * \fByyin_r\fP"
.br
.ti -1c
.RI "FILE * \fByyout_r\fP"
.br
.ti -1c
.RI "size_t \fByy_buffer_stack_top\fP"
.br
.ti -1c
.RI "size_t \fByy_buffer_stack_max\fP"
.br
.ti -1c
.RI "\fBYY_BUFFER_STATE\fP * \fByy_buffer_stack\fP"
.br
.ti -1c
.RI "char \fByy_hold_char\fP"
.br
.ti -1c
.RI "yy_size_t \fByy_n_chars\fP"
.br
.ti -1c
.RI "yy_size_t \fByyleng_r\fP"
.br
.ti -1c
.RI "char * \fByy_c_buf_p\fP"
.br
.ti -1c
.RI "int \fByy_init\fP"
.br
.ti -1c
.RI "int \fByy_start\fP"
.br
.ti -1c
.RI "int \fByy_did_buffer_switch_on_eof\fP"
.br
.ti -1c
.RI "int \fByy_start_stack_ptr\fP"
.br
.ti -1c
.RI "int \fByy_start_stack_depth\fP"
.br
.ti -1c
.RI "int * \fByy_start_stack\fP"
.br
.ti -1c
.RI "yy_state_type \fByy_last_accepting_state\fP"
.br
.ti -1c
.RI "char * \fByy_last_accepting_cpos\fP"
.br
.ti -1c
.RI "int \fByylineno_r\fP"
.br
.ti -1c
.RI "int \fByy_flex_debug_r\fP"
.br
.ti -1c
.RI "char * \fByytext_r\fP"
.br
.ti -1c
.RI "int \fByy_more_flag\fP"
.br
.ti -1c
.RI "int \fByy_more_len\fP"
.br
.ti -1c
.RI "\fBYYSTYPE\fP * \fByylval_r\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBYY_BUFFER_STATE\fP* yyguts_t::yy_buffer_stack"
Stack as an array\&. 
.SS "size_t yyguts_t::yy_buffer_stack_max"
capacity of stack\&. 
.SS "size_t yyguts_t::yy_buffer_stack_top"
index of top of stack\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
