.TH "yySemanticOption" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
yySemanticOption \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fByybool\fP \fByyisState\fP"
.br
.ti -1c
.RI "\fByyRuleNum\fP \fByyrule\fP"
.br
.ti -1c
.RI "\fByyGLRState\fP * \fByystate\fP"
.br
.ti -1c
.RI "int \fByyrawchar\fP"
.br
.ti -1c
.RI "\fBYYSTYPE\fP \fByyval\fP"
.br
.ti -1c
.RI "\fByySemanticOption\fP * \fByynext\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fByybool\fP yySemanticOption::yyisState"
Type tag: always false\&. 
.SS "\fByySemanticOption\fP * yySemanticOption::yynext"
Next sibling in chain of options\&. To facilitate merging, options are chained in decreasing order by address\&. 
.PP
Referenced by yyaddDeferredAction(), yyexpandGLRStack(), yymergeOptionSets(), and yyresolveValue()\&.
.SS "int yySemanticOption::yyrawchar"
The lookahead for this reduction\&. 
.PP
Referenced by yyaddDeferredAction(), and yyresolveAction()\&.
.SS "\fByyRuleNum\fP yySemanticOption::yyrule"
Rule number for this reduction 
.PP
Referenced by yyaddDeferredAction(), yydestroyGLRState(), yyidenticalOptions(), yymergeOptionSets(), yypreference(), yyresolveAction(), and yyresolveValue()\&.
.SS "\fByyGLRState\fP * yySemanticOption::yystate"
The last RHS state in the list of states to be reduced\&. 
.PP
Referenced by yyaddDeferredAction(), yydestroyGLRState(), yyexpandGLRStack(), yyidenticalOptions(), yymergeOptionSets(), and yyresolveAction()\&.
.SS "\fBYYSTYPE\fP yySemanticOption::yyval"

.PP
Referenced by yyaddDeferredAction(), and yyresolveAction()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
