.TH "YYSTYPE" 3 "Thu Nov 12 2015" "Claims" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YYSTYPE \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sql\&.tab\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBintval\fP"
.br
.ti -1c
.RI "double \fBfloatval\fP"
.br
.ti -1c
.RI "char * \fBstrval\fP"
.br
.ti -1c
.RI "int \fBsubtok\fP"
.br
.ti -1c
.RI "struct \fBNode\fP * \fBast_node\fP"
.br
.ti -1c
.RI "class \fBAstNode\fP * \fBast_node\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBNode\fP* YYSTYPE::ast_node"

.SS "class \fBAstNode\fP* YYSTYPE::ast_node"

.SS "double YYSTYPE::floatval"

.SS "int YYSTYPE::intval"

.SS "char * YYSTYPE::strval"

.SS "int YYSTYPE::subtok"


.SH "Author"
.PP 
Generated automatically by Doxygen for Claims from the source code\&.
