################################################################################
# 自动生成的文件。不要编辑！
################################################################################

O_SRCS := 
CPP_SRCS := 
C_UPPER_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
CXX_SRCS := 
C++_SRCS := 
CC_SRCS := 
OBJS := 
C++_DEPS := 
C_DEPS := 
CC_DEPS := 
CPP_DEPS := 
EXECUTABLES := 
CXX_DEPS := 
C_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
utility \
utility/Test \
types/Test \
types \
try \
. \
storage \
iterator \
common \
Test \
Serialization \
Schema \
Schema/Test \
Scheduler/test \
Scheduler \
Resource \
PerformanceTest \
PerformanceMonitor \
Parsetree \
Parsetree/Test \
LogicalQueryPlan/Test \
LogicalQueryPlan \
Loader \
IndexManager \
Executor/Test \
Executor \
Default/utility \
Default/utility/Test \
Default/types/Test \
Default/types \
Default/try \
Default \
Default/storage \
Default/iterator \
Default/common \
Default/Test \
Default/Serialization \
Default/Schema \
Default/Schema/Test \
Default/Scheduler/test \
Default/Scheduler \
Default/Resource \
Default/PerformanceTest \
Default/PerformanceMonitor \
Default/Parsetree \
Default/Parsetree/Test \
Default/LogicalQueryPlan/Test \
Default/LogicalQueryPlan \
Default/Loader \
Default/IndexManager \
Default/Executor/Test \
Default/Executor \
Default/Daemon/Test \
Default/Daemon \
Default/Client/Test \
Default/Client \
Default/Catalog \
Default/Catalog/stat \
Default/Catalog/Test \
Default/BufferManager \
Default/BlockStreamIterator/ParallelBlockStreamIterator/Test \
Default/BlockStreamIterator/ParallelBlockStreamIterator \
Default/BlockStreamIterator \
Default/BlockIterator \
Default/Block \
Daemon/Test \
Daemon \
Client/Test \
Client \
Catalog \
Catalog/stat \
Catalog/Test \
BufferManager \
BlockStreamIterator/ParallelBlockStreamIterator/Test \
BlockStreamIterator/ParallelBlockStreamIterator \
BlockStreamIterator \
BlockIterator \
Block \

