Claims: BlockManager Class Reference
BlockManager Class Reference
#include <BlockManager.h>
Classes
struct BlockInfo
class BlockManagerWorkerActor
Public Types
enum storageLevel { memory, disk, offline }
Public Member Functions
MemoryChunkStore * getMemoryChunkStore () const
virtual ~BlockManager ()
void initialize ()
void registerToMaster (BlockManagerId *blockManagerId)
void heartBeat ()
void asyncReregister ()
void reregister ()
void reportAllBlocks ()
bool reportBlockStatus (string blockId)
bool tryToReportBlockStatus (string blockId)
void get (string blockId)
void * getLocal (string blockId)
ChunkInfo loadFromHdfs (string file_name)
int loadFromHdfs (const ChunkID &, void *const &desc, const unsigned &)
int loadFromDisk (const ChunkID &, void *const &desc, const unsigned &) const
bool put (string blockId, storageLevel level, void *value)
BlockManagerId * getId ()
string askForMatch (string filename, BlockManagerId bmi)
bool containsPartition (const PartitionID &part) const
bool addPartition (const PartitionID &, const unsigned &number_of_chunks, const StorageLevel &desirable_storage_level)
bool removePartition (const PartitionID &)
PartitionStorage * getPartitionHandle (const PartitionID &partition_id) const
Static Public Member Functions
static BlockManager * getInstance ()
Private Member Functions
BlockManager ()
Private Attributes
map< string, BlockInfo * > blockInfoPool_
BlockManagerWorkerActor * worker_
BlockManagerId * blockManagerId_
MemoryChunkStore * memstore_
DiskStore * diskstore_
map< string, string > file_proj_
Theron::Framework * framework_
Theron::Actor * actor_
boost::unordered_map
< PartitionID,
PartitionStorage * > partition_id_to_storage_
Logging * logging_
Lock lock
Static Private Attributes
static BlockManager * blockmanager_ =0
Friends
class BlockManagerWorkerActor
Member Enumeration Documentation
enum BlockManager::storageLevel
Enumerator
memory
disk
offline
Constructor & Destructor Documentation
BlockManager::~BlockManager () virtual
References actor_, blockmanager_, framework_, logging_, and memstore_.
BlockManager::BlockManager () private
References actor_, BlockManagerWorkerActor, framework_, Environment::getInstance(), MemoryChunkStore::getInstance(), Environment::getNodeID(), logging_, and memstore_.
Referenced by getInstance().
Member Function Documentation
bool BlockManager::addPartition (const PartitionID & partition_id, const unsigned & number_of_chunks, const StorageLevel & desirable_storage_level)
References PartitionID::getName(), Logging::log(), logging_, and partition_id_to_storage_.
string BlockManager::askForMatch (string filename, BlockManagerId bmi)
References BlockManager::BlockManagerWorkerActor::_askformatch(), file_proj_, and worker_.
void BlockManager::asyncReregister ()
Referenced by reportBlockStatus().
bool BlockManager::containsPartition (const PartitionID & part) const
References partition_id_to_storage_.
void BlockManager::get (string blockId)
References getLocal().
BlockManagerId * BlockManager::getId ()
References blockManagerId_.
BlockManager * BlockManager::getInstance () static
References BlockManager(), and blockmanager_.
Referenced by ChunkStorage::createChunkReaderIterator(), Environment::initializeStorage(), bottomLayerCollecting::Open(), claims::physical_operator::PhysicalProjectionScan::Open(), IndexScanIterator::Open(), and projection_scan().
void * BlockManager::getLocal (string blockId)
References blockInfoPool_, disk, MemoryChunkStore::getChunk(), ChunkInfo::hook, loadFromHdfs(), memory, memstore_, and put().
Referenced by get().
MemoryChunkStore * BlockManager::getMemoryChunkStore () const
References memstore_.
Referenced by ChunkStorage::createChunkReaderIterator().
PartitionStorage * BlockManager::getPartitionHandle (const PartitionID & partition_id) const
References partition_id_to_storage_.
Referenced by projection_scan().
void BlockManager::heartBeat ()
References BlockManager::BlockManagerWorkerActor::_sendHeartBeat(), reregister(), and worker_.
Referenced by initialize().
void BlockManager::initialize ()
the version written by zhanglei/////////////////////////////////
References blockManagerId_, disk, DISKDIR, diskstore_, BufferManager::getInstance(), Environment::getInstance(), MemoryChunkStore::getInstance(), Environment::getNodeID(), Environment::getResourceManagerSlave(), BufferManager::getStorageMemoryBudegeInMilibyte(), heartBeat(), memory, memstore_, registerToMaster(), and InstanceResourceManager::ReportStorageBudget().
Referenced by Environment::initializeStorage().
int BlockManager::loadFromDisk (const ChunkID & chunk_id, void *const & desc, const unsigned & length) const
References ChunkID::chunk_off, CHUNK_SIZE, Logging::elog(), FileClose(), FileOpen, PartitionID::getPathAndName(), Logging::log(), logging_, and ChunkID::partition_id.
Referenced by ChunkStorage::createChunkReaderIterator().
ChunkInfo BlockManager::loadFromHdfs (string file_name)
References CHUNK_SIZE, Config::hdfs_master_ip, Config::hdfs_master_port, and ChunkInfo::hook.
Referenced by ChunkStorage::createChunkReaderIterator(), and getLocal().
int BlockManager::loadFromHdfs (const ChunkID & chunk_id, void *const & desc, const unsigned & length)
References Lock::acquire(), ChunkID::chunk_off, CHUNK_SIZE, Logging::elog(), PartitionID::getPathAndName(), Config::hdfs_master_ip, Config::hdfs_master_port, lock, Logging::log(), logging_, ChunkID::partition_id, and Lock::release().
bool BlockManager::put (string blockId, storageLevel level, void * value)
References blockInfoPool_, disk, diskstore_, memory, memstore_, DiskStore::putValue(), MemoryChunkStore::putValue(), and reportBlockStatus().
Referenced by getLocal().
void BlockManager::registerToMaster (BlockManagerId * blockManagerId)
References BlockManager::BlockManagerWorkerActor::_reigisterToMaster(), and worker_.
Referenced by initialize().
bool BlockManager::removePartition (const PartitionID & partition_id)
References Logging::elog(), PartitionID::getName(), logging_, and partition_id_to_storage_.
void BlockManager::reportAllBlocks ()
Referenced by reregister().
bool BlockManager::reportBlockStatus (string blockId)
References asyncReregister(), and tryToReportBlockStatus().
Referenced by put().
void BlockManager::reregister ()
References reportAllBlocks().
Referenced by heartBeat().
bool BlockManager::tryToReportBlockStatus (string blockId)
References BlockManager::BlockManagerWorkerActor::_reportBlockStatus(), and worker_.
Referenced by reportBlockStatus().
Friends And Related Function Documentation
friend class BlockManagerWorkerActor friend
Referenced by BlockManager().
Member Data Documentation
Theron::Actor* BlockManager::actor_ private
Referenced by BlockManager(), and ~BlockManager().
map<string, BlockInfo*> BlockManager::blockInfoPool_ private
Referenced by getLocal(), and put().
BlockManager * BlockManager::blockmanager_ =0 static private
Referenced by getInstance(), and ~BlockManager().
BlockManagerId* BlockManager::blockManagerId_ private
Referenced by getId(), and initialize().
DiskStore* BlockManager::diskstore_ private
Referenced by initialize(), and put().
map<string, string> BlockManager::file_proj_ private
Referenced by askForMatch().
Theron::Framework* BlockManager::framework_ private
Referenced by BlockManager(), and ~BlockManager().
Lock BlockManager::lock private
Referenced by loadFromHdfs().
Logging* BlockManager::logging_ private
Referenced by addPartition(), BlockManager(), loadFromDisk(), loadFromHdfs(), removePartition(), and ~BlockManager().
MemoryChunkStore* BlockManager::memstore_ private
Referenced by BlockManager(), getLocal(), getMemoryChunkStore(), initialize(), put(), and ~BlockManager().
boost::unordered_map<PartitionID,PartitionStorage*> BlockManager::partition_id_to_storage_ private
Referenced by addPartition(), containsPartition(), getPartitionHandle(), and removePartition().
BlockManagerWorkerActor* BlockManager::worker_ private
Referenced by askForMatch(), heartBeat(), registerToMaster(), and tryToReportBlockStatus().
The documentation for this class was generated from the following files:
storage/BlockManager.h
storage/BlockManager.cpp