Claims: ClientLogging Class Reference
ClientLogging Class Reference
#include <Logging.h>
Static Public Member Functions
static void log (const char *format,...)
static void elog (const char *format,...)
Member Function Documentation
void ClientLogging::elog (const char * format, ...) static
References RawElog().
Referenced by ClientListener::checkFdValid(), ClientListener::generateSqlStmt(), and ClientListener::receiveHandler().
void ClientLogging::log (const char * format, ...) static
References RawLog().
Referenced by ClientListener::checkFdValid(), ClientListener::generateSqlStmt(), Client::receive(), ClientListener::receiveHandler(), ClientResponse::serialize(), Client::shutdown(), ClientListener::shutdown(), Client::submit(), Client::submitQuery(), and Daemon::worker().
The documentation for this class was generated from the following files:
common/Logging.h
common/Logging.cpp