Claims: DiskChunkReaderIteraror Class Reference
DiskChunkReaderIteraror Class Reference
#include <ChunkStorage.h>
Public Member Functions
DiskChunkReaderIteraror (const ChunkID &chunk_id, unsigned &chunk_size, const unsigned &block_size)
virtual ~DiskChunkReaderIteraror ()
bool nextBlock (BlockStreamBase *&block)
bool getNextBlockAccessor (block_accessor *&ba)
Public Member Functions inherited from ChunkReaderIterator
ChunkReaderIterator (const ChunkID &chunk_id, unsigned block_size, unsigned chunk_size, const unsigned &number_of_blocks=0)
bool nextBlock ()
virtual ~ChunkReaderIterator ()
Private Attributes
Block * block_buffer_
int fd_
Additional Inherited Members
Public Attributes inherited from ChunkReaderIterator
ChunkID chunk_id_
unsigned number_of_blocks_
unsigned cur_block_
Lock lock_
unsigned block_size_
unsigned chunk_size_
Constructor & Destructor Documentation
DiskChunkReaderIteraror::DiskChunkReaderIteraror (const ChunkID & chunk_id, unsigned & chunk_size, const unsigned & block_size)
References block_buffer_, ChunkReaderIterator::block_size_, ChunkReaderIterator::chunk_id_, ChunkID::chunk_off, CHUNK_SIZE, fd_, FileOpen, PartitionID::getName(), PartitionID::getPathAndName(), ChunkReaderIterator::number_of_blocks_, and ChunkID::partition_id.
DiskChunkReaderIteraror::~DiskChunkReaderIteraror () virtual
References block_buffer_, fd_, FileClose(), and Block::~Block().
Member Function Documentation
bool DiskChunkReaderIteraror::getNextBlockAccessor (block_accessor *& ba) virtual
Implements ChunkReaderIterator.
References Lock::acquire(), ChunkReaderIterator::block_size_, ChunkReaderIterator::chunk_id_, ChunkReaderIterator::chunk_size_, ChunkReaderIterator::cur_block_, ChunkReaderIterator::lock_, ChunkReaderIterator::number_of_blocks_, Lock::release(), ChunkReaderIterator::InDiskBlockAccessor::setBlockCur(), ChunkReaderIterator::block_accessor::setBlockSize(), and ChunkReaderIterator::InDiskBlockAccessor::setChunkId().
bool DiskChunkReaderIteraror::nextBlock (BlockStreamBase *& block) virtual
Implements ChunkReaderIterator.
References Lock::acquire(), block_buffer_, ChunkReaderIterator::block_size_, BlockStreamBase::constructFromBlock(), ChunkReaderIterator::cur_block_, fd_, Block::getBlock(), Block::getsize(), ChunkReaderIterator::lock_, ChunkReaderIterator::number_of_blocks_, and Lock::release().
Member Data Documentation
Block* DiskChunkReaderIteraror::block_buffer_ private
Referenced by DiskChunkReaderIteraror(), nextBlock(), and ~DiskChunkReaderIteraror().
int DiskChunkReaderIteraror::fd_ private
Referenced by DiskChunkReaderIteraror(), nextBlock(), and ~DiskChunkReaderIteraror().
The documentation for this class was generated from the following files:
storage/ChunkStorage.h
storage/ChunkStorage.cpp