Claims: SchemaVar Class Reference
SchemaVar Class Reference
#include <SchemaVar.h>
Public Member Functions
SchemaVar ()
virtual ~SchemaVar ()
SchemaVar (std::vector< column_type > columns)
virtual unsigned getTupleMaxSize () const
virtual unsigned getTupleActualSize (void *tuple) const
virtual unsigned copyTuple (void *src, void *desc) const
virtual Schema::schema_type getSchemaType () const
virtual void getColumnValue (unsigned index, void *src, void *desc)
int getColumnOffset (unsigned index) const
virtual Schema * getSubSchema (std::vector< unsigned >) const
Schema * duplicateSchema () const
virtual void * getColumnAddess (const unsigned &index, const void *const &column_start) const __attribute__((always_inline))
Public Member Functions inherited from Schema
Schema (const std::vector< column_type > &columns)
Schema (const Schema &r)
Schema ()
virtual ~Schema ()
unsigned getncolumns () const
const column_type & getcolumn (const unsigned index) const
virtual void addColumn (column_type ct, unsigned size)
virtual void displayTuple (const void *tuple_start_address, const char *spliter="|") const
virtual void toValue (std::string text_tuple, void *binary_tuple, const char attr_separator)
virtual void showAccum_off ()
bool hasSameSchema (Schema *schema)
virtual std::string getColumnValue (const void *tuple_start_address, int i)
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
unsigned var_attributes_
unsigned attributes_
Friends
class boost::serialization::access
Additional Inherited Members
Public Types inherited from Schema
enum schema_type { fixed, varaible }
Public Attributes inherited from Schema
std::vector< column_type > columns
Constructor & Destructor Documentation
SchemaVar::SchemaVar ()
Referenced by duplicateSchema().
SchemaVar::~SchemaVar () virtual
SchemaVar::SchemaVar (std::vector< column_type > columns)
References attributes_, t_string, and var_attributes_.
Member Function Documentation
unsigned SchemaVar::copyTuple (void * src, void * desc) const virtual
Implements Schema.
References getTupleActualSize().
Schema * SchemaVar::duplicateSchema () const virtual
Implements Schema.
References Schema::columns, and SchemaVar().
virtual void* SchemaVar::getColumnAddess (const unsigned & index, const void *const & column_start) const inline virtual
Implements Schema.
References t_string, and var_attributes_.
int SchemaVar::getColumnOffset (unsigned index) const inline virtual
Implements Schema.
virtual void SchemaVar::getColumnValue (unsigned index, void * src, void * desc) inline virtual
Implements Schema.
Schema::schema_type SchemaVar::getSchemaType () const virtual
Implements Schema.
References Schema::varaible.
virtual Schema* SchemaVar::getSubSchema (std::vector< unsigned >) const inline virtual
Implements Schema.
unsigned SchemaVar::getTupleActualSize (void * tuple) const virtual
Implements Schema.
References Schema::columns, t_string, and var_attributes_.
Referenced by copyTuple().
virtual unsigned SchemaVar::getTupleMaxSize () const inline virtual
Implements Schema.
template<class Archive > void SchemaVar::serialize (Archive & ar, const unsigned int version) inline private
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
unsigned SchemaVar::attributes_ private
Referenced by SchemaVar().
unsigned SchemaVar::var_attributes_ private
Referenced by getColumnAddess(), getTupleActualSize(), and SchemaVar().
The documentation for this class was generated from the following files:
common/Schema/SchemaVar.h
common/Schema/SchemaVar.cpp