Claims: OperateDecimal Class Reference
OperateDecimal Class Reference
#include <data_type.h>
Public Member Functions
OperateDecimal (unsigned number_of_decimal_digits=12, bool _nullable=true)
void assignment (const void *const &src, void *const &desc) const
std::string toString (void *value)
void toValue (void *target, const char *string)
bool equal (const void *const &a, const void *const &b) const
bool less (const void *&a, const void *&b) const
bool greate (const void *&a, const void *&b) const
int compare (const void *a, const void *b) const
void add (void *target, void *increment)
void multiple (void *target, void *increment)
fun GetADDFunction ()
fun GetMINFunction ()
fun GetMAXFunction ()
fun GetIncreateByOneFunction ()
fun GetAVGFunction ()
unsigned getPartitionValue (const void *key, const PartitionFunction *partition_function) const
unsigned getPartitionValue (const void *key) const
unsigned getPartitionValue (const void *key, const unsigned long &mod) const
Operate * duplicateOperator () const
bool setNull (void *value)
bool isNull (void *value) const
Public Member Functions inherited from Operate
Operate (bool _nullable=true)
virtual ~Operate ()
void ass (void *src, void *desc)
Static Public Member Functions
static std::string toString (const NValue v, unsigned n_o_d_d=12)
Public Attributes
unsigned number_of_decimal_digits_
Public Attributes inherited from Operate
void(* assign)(const void *const &src, void *const &desc)
bool nullable
Constructor & Destructor Documentation
OperateDecimal::OperateDecimal (unsigned number_of_decimal_digits = 12, bool _nullable = true) inline
Member Function Documentation
void OperateDecimal::add (void * target, void * increment) inline virtual
Implements Operate.
References ADD_FUNC< NValue * >().
void OperateDecimal::assignment (const void *const & src, void *const & desc) const inline virtual
Implements Operate.
int OperateDecimal::compare (const void * a, const void * b) const inline virtual
Implements Operate.
Operate* OperateDecimal::duplicateOperator () const inline virtual
Implements Operate.
bool OperateDecimal::equal (const void *const & a, const void *const & b) const inline virtual
Implements Operate.
fun OperateDecimal::GetADDFunction () inline virtual
Implements Operate.
References ADD_FUNC< NValue * >().
fun OperateDecimal::GetAVGFunction () inline virtual
Implements Operate.
References ADD_IncreaseByOne< NValue * >().
fun OperateDecimal::GetIncreateByOneFunction () inline virtual
Implements Operate.
References IncreaseByOne< NValue * >().
fun OperateDecimal::GetMAXFunction () inline virtual
Implements Operate.
References MAX< NValue * >().
fun OperateDecimal::GetMINFunction () inline virtual
Implements Operate.
References MIN< NValue * >().
unsigned OperateDecimal::getPartitionValue (const void * key, const PartitionFunction * partition_function) const inline virtual
Implements Operate.
References PartitionFunction::get_partition_value().
unsigned OperateDecimal::getPartitionValue (const void * key) const inline virtual
Implements Operate.
unsigned OperateDecimal::getPartitionValue (const void * key, const unsigned long & mod) const inline virtual
Implements Operate.
bool OperateDecimal::greate (const void *& a, const void *& b) const inline virtual
Implements Operate.
References decimal::NValue::op_equals(), and decimal::NValue::op_min().
bool OperateDecimal::isNull (void * value) const inline virtual
Implements Operate.
References compare(), and NULL_DECIMAL.
bool OperateDecimal::less (const void *& a, const void *& b) const inline virtual
Implements Operate.
References decimal::NValue::op_equals(), and decimal::NValue::op_min().
void OperateDecimal::multiple (void * target, void * increment) inline virtual
Implements Operate.
bool OperateDecimal::setNull (void * value) inline virtual
Implements Operate.
References NULL_DECIMAL.
std::string OperateDecimal::toString (void * value) inline virtual
Implements Operate.
References compare(), and NULL_DECIMAL.
Referenced by query_2().
static std::string OperateDecimal::toString (const NValue v, unsigned n_o_d_d = 12) inline static
void OperateDecimal::toValue (void * target, const char * string) inline virtual
Implements Operate.
References NULL_DECIMAL.
Member Data Documentation
unsigned OperateDecimal::number_of_decimal_digits_
The documentation for this class was generated from the following file:
common/data_type.h