My Project: claims::logical_operator::Requirement Class Reference
claims::logical_operator::Requirement Class Reference
Public Member Functions
void setRequiredPartitionkey (const Attribute partition_key)
Attribute getPartitionKey () const
bool hasReuiredPartitionKey () const
void setRequiredPartitionFucntion (PartitionFunction *partition)
PartitionFunction * getPartitionFunction () const
bool hasRequiredPartitionFunction () const
void setRequiredLocations (std::vector< NodeID > location_list)
std::vector< NodeID > getRequiredLocations () const
bool hasRequiredLocations () const
void setRequiredCost (const unsigned long cost)
NetworkTransfer requireNetworkTransfer (const PlanContext &plan_context) const
bool passLimits (const unsigned long cost) const
bool tryMerge (const Requirement req, Requirement &target) const
Member Function Documentation
NetworkTransfer claims::logical_operator::Requirement::requireNetworkTransfer (const PlanContext & plan_context) const
there is partition key requirement
Referenced by claims::logical_operator::LogicalScan::GetOptimalPhysicalPlan(), claims::logical_operator::LogicalFilter::GetOptimalPhysicalPlan(), and claims::logical_operator::LogicalQueryPlanRoot::GetOptimalPhysicalPlan().
bool claims::logical_operator::Requirement::tryMerge (const Requirement req, Requirement & target) const
try to merge the req if *this and req are compatible. return true if successful
Referenced by claims::logical_operator::LogicalQueryPlanRoot::GetOptimalPhysicalPlan().
The documentation for this class was generated from the following files:
logical_operator/Requirement.h
logical_operator/Requirement.cpp