Claims: PartitionStorage Class Reference
PartitionStorage Class Reference
#include <PartitionStorage.h>
Classes
class AtomicPartitionReaderIterator
class PartitionReaderItetaor
Public Member Functions
PartitionStorage (const PartitionID &partition_id, const unsigned &number_of_chunks, const StorageLevel &)
virtual ~PartitionStorage ()
void addNewChunk ()
void updateChunksWithInsertOrAppend (const PartitionID &partition_id, const unsigned &number_of_chunks, const StorageLevel &storage_level)
void removeAllChunks (const PartitionID &partition_id)
PartitionReaderItetaor * createReaderIterator ()
PartitionReaderItetaor * createAtomicReaderIterator ()
Protected Attributes
PartitionID partition_id_
unsigned number_of_chunks_
std::vector< ChunkStorage * > chunk_list_
StorageLevel desirable_storage_level_
Friends
class PartitionReaderItetaor
Constructor & Destructor Documentation
PartitionStorage::PartitionStorage (const PartitionID & partition_id, const unsigned & number_of_chunks, const StorageLevel & storage_level)
References BLOCK_SIZE, chunk_list_, desirable_storage_level_, number_of_chunks_, and partition_id_.
PartitionStorage::~PartitionStorage () virtual
References chunk_list_.
Member Function Documentation
void PartitionStorage::addNewChunk ()
References number_of_chunks_.
PartitionStorage::PartitionReaderItetaor * PartitionStorage::createAtomicReaderIterator ()
Referenced by bottomLayerCollecting::Open(), claims::physical_operator::PhysicalProjectionScan::Open(), IndexScanIterator::Open(), and projection_scan().
PartitionStorage::PartitionReaderItetaor * PartitionStorage::createReaderIterator ()
References PartitionReaderItetaor.
void PartitionStorage::removeAllChunks (const PartitionID & partition_id)
References chunk_list_, MemoryChunkStore::getInstance(), number_of_chunks_, and MemoryChunkStore::returnChunk().
void PartitionStorage::updateChunksWithInsertOrAppend (const PartitionID & partition_id, const unsigned & number_of_chunks, const StorageLevel & storage_level)
References BLOCK_SIZE, chunk_list_, MemoryChunkStore::getInstance(), HDFS, number_of_chunks_, and MemoryChunkStore::returnChunk().
Friends And Related Function Documentation
friend class PartitionReaderItetaor friend
Referenced by createReaderIterator().
Member Data Documentation
std::vector<ChunkStorage*> PartitionStorage::chunk_list_ protected
Referenced by PartitionStorage(), removeAllChunks(), updateChunksWithInsertOrAppend(), and ~PartitionStorage().
StorageLevel PartitionStorage::desirable_storage_level_ protected
Referenced by PartitionStorage().
unsigned PartitionStorage::number_of_chunks_ protected
Referenced by addNewChunk(), PartitionStorage::PartitionReaderItetaor::nextChunk(), PartitionStorage::AtomicPartitionReaderIterator::nextChunk(), PartitionStorage(), removeAllChunks(), and updateChunksWithInsertOrAppend().
PartitionID PartitionStorage::partition_id_ protected
Referenced by PartitionStorage().
The documentation for this class was generated from the following files:
storage/PartitionStorage.h
storage/PartitionStorage.cpp