Claims: OperateUSmallInt Class Reference
OperateUSmallInt Class Reference
#include <data_type.h>
Public Member Functions
OperateUSmallInt (bool _nullable=true)
void assignment (const void *const &src, void *const &desc) const
std::string toString (void *value)
void toValue (void *target, const char *string)
bool equal (const void *const &a, const void *const &b) const
bool less (const void *&a, const void *&b) const
bool greate (const void *&a, const void *&b) const
int compare (const void *a, const void *b) const
void add (void *target, void *increment)
void multiple (void *target, void *increment)
fun GetADDFunction ()
fun GetMINFunction ()
fun GetMAXFunction ()
fun GetIncreateByOneFunction ()
fun GetAVGFunction ()
unsigned getPartitionValue (const void *key, const PartitionFunction *partition_function) const
unsigned getPartitionValue (const void *key) const
unsigned getPartitionValue (const void *key, const unsigned long &mod) const
Operate * duplicateOperator () const
bool setNull (void *value)
bool isNull (void *value) const
Public Member Functions inherited from Operate
Operate (bool _nullable=true)
virtual ~Operate ()
void ass (void *src, void *desc)
Additional Inherited Members
Public Attributes inherited from Operate
void(* assign)(const void *const &src, void *const &desc)
bool nullable
Constructor & Destructor Documentation
OperateUSmallInt::OperateUSmallInt (bool _nullable = true) inline
Member Function Documentation
void OperateUSmallInt::add (void * target, void * increment) inline virtual
Implements Operate.
void OperateUSmallInt::assignment (const void *const & src, void *const & desc) const inline virtual
Implements Operate.
int OperateUSmallInt::compare (const void * a, const void * b) const inline virtual
Implements Operate.
Operate* OperateUSmallInt::duplicateOperator () const inline virtual
Implements Operate.
bool OperateUSmallInt::equal (const void *const & a, const void *const & b) const inline virtual
Implements Operate.
fun OperateUSmallInt::GetADDFunction () inline virtual
Implements Operate.
fun OperateUSmallInt::GetAVGFunction () inline virtual
Implements Operate.
fun OperateUSmallInt::GetIncreateByOneFunction () inline virtual
Implements Operate.
fun OperateUSmallInt::GetMAXFunction () inline virtual
Implements Operate.
fun OperateUSmallInt::GetMINFunction () inline virtual
Implements Operate.
unsigned OperateUSmallInt::getPartitionValue (const void * key, const PartitionFunction * partition_function) const inline virtual
Implements Operate.
References PartitionFunction::get_partition_value().
unsigned OperateUSmallInt::getPartitionValue (const void * key) const inline virtual
Implements Operate.
References hash_value().
unsigned OperateUSmallInt::getPartitionValue (const void * key, const unsigned long & mod) const inline virtual
Implements Operate.
References hash_value().
bool OperateUSmallInt::greate (const void *& a, const void *& b) const inline virtual
Implements Operate.
bool OperateUSmallInt::isNull (void * value) const inline virtual
Implements Operate.
References NULL_U_SMALL_INT.
bool OperateUSmallInt::less (const void *& a, const void *& b) const inline virtual
Implements Operate.
void OperateUSmallInt::multiple (void * target, void * increment) inline virtual
Implements Operate.
bool OperateUSmallInt::setNull (void * value) inline virtual
Implements Operate.
References NULL_U_SMALL_INT.
std::string OperateUSmallInt::toString (void * value) inline virtual
Implements Operate.
References NULL_U_SMALL_INT.
void OperateUSmallInt::toValue (void * target, const char * string) inline virtual
Implements Operate.
References NULL_U_SMALL_INT.
The documentation for this class was generated from the following file:
common/data_type.h