Claims: CCSBNode< T > Class Template Reference
CCSBNode< T > Class Template Reference
#include <CSBPlusTree.h>
Public Member Functions
CCSBNode ()
virtual ~CCSBNode ()
int getUsedKeys ()
virtual bool setUsedKeys (int count)
CCSBNode< T > * getFather ()
void setFather (CCSBNode< T > *father)
virtual data_offset< T > getElement (unsigned i)
virtual bool setElement (unsigned i, data_offset< T > value)
virtual bool setElement (unsigned i, T value)
virtual CCSBNodeGroup< T > * getPointer ()
virtual void setPointer (CCSBNodeGroup< T > *pointer)
virtual void DeleteChildren ()
virtual bool Insert (T key)
virtual bool Insert (data_offset< T > value)
virtual bool Delete (T value)
virtual T SplitInsert (CCSBNode< T > *pNode, T key)
virtual T SplitInsert (CCSBNode< T > *pNode, data_offset< T > data)
virtual bool Combine (CCSBNode< T > *pNode)
virtual bool serialize (FILE *filename)
virtual bool deserialize (FILE *filename)
Static Public Member Functions
static unsigned getMaxKeys ()
static unsigned getMaxDatas ()
Public Attributes
int used_keys
CCSBNode< T > * p_father
Constructor & Destructor Documentation
template<typename T > CCSBNode< T >::CCSBNode ()
template<typename T > CCSBNode< T >::~CCSBNode () virtual
References NULL.
Member Function Documentation
template<typename T> virtual bool CCSBNode< T >::Combine (CCSBNode< T > * pNode) inline virtual
Reimplemented in CCSBLeafNode< T >, and CCSBInternalNode< T >.
template<typename T> virtual bool CCSBNode< T >::Delete (T value) inline virtual
Reimplemented in CCSBLeafNode< T >, and CCSBInternalNode< T >.
template<typename T> virtual void CCSBNode< T >::DeleteChildren () inline virtual
Reimplemented in CCSBLeafNode< T >, and CCSBInternalNode< T >.
template<typename T> virtual bool CCSBNode< T >::deserialize (FILE * filename) inline virtual
Reimplemented in CCSBLeafNode< T >, and CCSBInternalNode< T >.
template<typename T> virtual data_offset<T> CCSBNode< T >::getElement (unsigned i) inline virtual
Reimplemented in CCSBLeafNode< T >, and CCSBInternalNode< T >.
Referenced by CSBPlusTree< T >::Insert(), CSBPlusTree< T >::rangeQuery(), CSBPlusTree< T >::Search(), CSBPlusTree< T >::SearchLeafNode(), CCSBInternalNodeGroup< T >::setNode(), CCSBLeafNodeGroup< T >::setNode(), CCSBInternalNode< T >::SplitInsert(), and CCSBLeafNode< T >::SplitInsert().
template<typename T> CCSBNode<T>* CCSBNode< T >::getFather () inline
Referenced by CSBPlusTree< T >::Insert(), CSBPlusTree< T >::rangeQuery(), CSBPlusTree< T >::Search(), CSBPlusTree< T >::SearchLeafNode(), CCSBInternalNodeGroup< T >::setNode(), and CCSBLeafNodeGroup< T >::setNode().
template<typename T> static unsigned CCSBNode< T >::getMaxDatas () inline static
References cacheline_size.
Referenced by CSBPlusTree< T >::CSBPlusTree().
template<typename T> static unsigned CCSBNode< T >::getMaxKeys () inline static
References cacheline_size.
Referenced by CSBPlusTree< T >::CSBPlusTree().
template<typename T> virtual CCSBNodeGroup<T>* CCSBNode< T >::getPointer () inline virtual
Reimplemented in CCSBLeafNode< T >, and CCSBInternalNode< T >.
Referenced by CSBPlusTree< T >::rangeQuery(), CSBPlusTree< T >::Search(), CSBPlusTree< T >::SearchLeafNode(), and CCSBInternalNodeGroup< T >::setNode().
template<typename T> int CCSBNode< T >::getUsedKeys () inline
Referenced by CSBPlusTree< T >::Insert(), CSBPlusTree< T >::rangeQuery(), CSBPlusTree< T >::Search(), CCSBInternalNodeGroup< T >::setNode(), and CCSBLeafNodeGroup< T >::setNode().
template<typename T> virtual bool CCSBNode< T >::Insert (T key) inline virtual
Reimplemented in CCSBInternalNode< T >.
Referenced by CSBPlusTree< T >::Insert(), CCSBInternalNode< T >::SplitInsert(), and CCSBLeafNode< T >::SplitInsert().
template<typename T> virtual bool CCSBNode< T >::Insert (data_offset< T > value) inline virtual
Reimplemented in CCSBLeafNode< T >.
template<typename T> virtual bool CCSBNode< T >::serialize (FILE * filename) inline virtual
Reimplemented in CCSBLeafNode< T >, and CCSBInternalNode< T >.
template<typename T> virtual bool CCSBNode< T >::setElement (unsigned i, data_offset< T > value) inline virtual
Reimplemented in CCSBLeafNode< T >.
Referenced by CCSBInternalNode< T >::SplitInsert(), and CCSBLeafNode< T >::SplitInsert().
template<typename T> virtual bool CCSBNode< T >::setElement (unsigned i, T value) inline virtual
Reimplemented in CCSBInternalNode< T >.
template<typename T> void CCSBNode< T >::setFather (CCSBNode< T > * father) inline
template<typename T> virtual void CCSBNode< T >::setPointer (CCSBNodeGroup< T > * pointer) inline virtual
Reimplemented in CCSBInternalNode< T >.
template<typename T> virtual bool CCSBNode< T >::setUsedKeys (int count) inline virtual
Reimplemented in CCSBLeafNode< T >, and CCSBInternalNode< T >.
Referenced by CCSBInternalNode< T >::SplitInsert(), and CCSBLeafNode< T >::SplitInsert().
template<typename T> virtual T CCSBNode< T >::SplitInsert (CCSBNode< T > * pNode, T key) inline virtual
Reimplemented in CCSBInternalNode< T >.
template<typename T> virtual T CCSBNode< T >::SplitInsert (CCSBNode< T > * pNode, data_offset< T > data) inline virtual
Reimplemented in CCSBLeafNode< T >.
Member Data Documentation
template<typename T> CCSBNode<T>* CCSBNode< T >::p_father
template<typename T> int CCSBNode< T >::used_keys
Referenced by CSBPlusTree< T >::rangeQuery(), and CSBPlusTree< T >::Search().
The documentation for this class was generated from the following files:
IndexManager/CSBPlusTree.h
IndexManager/CSBPlusTree.cpp