Claims: CPUResourceManager Class Reference
CPUResourceManager Class Reference
#include <CPUResource.h>
Classes
struct core
struct socket
Public Member Functions
CPUResourceManager ()
virtual ~CPUResourceManager ()
int tryApplyCore ()
int applyCore ()
void freeCore (int core_id=-1)
void print ()
Static Public Member Functions
static CPUResourceManager * getInstance ()
Private Attributes
semaphore sem_available_cores_
int number_of_sockets_
std::vector< socket > sockets_
Static Private Attributes
static CPUResourceManager * instance_ =0
Constructor & Destructor Documentation
CPUResourceManager::CPUResourceManager ()
References number_of_sockets_, semaphore::post(), sem_available_cores_, and sockets_.
Referenced by getInstance().
CPUResourceManager::~CPUResourceManager () virtual
Member Function Documentation
int CPUResourceManager::applyCore ()
apply for a core, return id of allocated core, blocked if no cores are available.
References number_of_sockets_, sem_available_cores_, sockets_, and semaphore::wait().
Referenced by cpu_resource_manager_test().
void CPUResourceManager::freeCore (int core_id = -1)
return the core to the Cpu resource core_id should be given if the caller is not running of the thread bound to the core.
References semaphore::post(), sem_available_cores_, and sockets_.
Referenced by cpu_resource_manager_test().
CPUResourceManager * CPUResourceManager::getInstance () static
References CPUResourceManager(), and instance_.
void CPUResourceManager::print ()
print the status of the cores in an array form.
References number_of_sockets_, and sockets_.
Referenced by cpu_resource_manager_test().
int CPUResourceManager::tryApplyCore ()
apply for a core available on any socket, this function returns the id of the core, or return -1 when there is not any core available.
References number_of_sockets_, sem_available_cores_, sockets_, and semaphore::try_wait().
Referenced by cpu_resource_manager_test().
Member Data Documentation
CPUResourceManager * CPUResourceManager::instance_ =0 static private
Referenced by getInstance().
int CPUResourceManager::number_of_sockets_ private
Referenced by applyCore(), CPUResourceManager(), print(), and tryApplyCore().
semaphore CPUResourceManager::sem_available_cores_ private
Referenced by applyCore(), CPUResourceManager(), freeCore(), and tryApplyCore().
std::vector<socket> CPUResourceManager::sockets_ private
Referenced by applyCore(), CPUResourceManager(), freeCore(), print(), and tryApplyCore().
The documentation for this class was generated from the following files:
Resource/CPUResource.h
Resource/CPUResource.cpp