Claims: Json::StyledStreamWriter Class Reference
Json::StyledStreamWriter Class Reference
Writes a Value in JSON format in a human friendly way, to a stream rather than to a string.
#include <json.h>
Public Member Functions
StyledStreamWriter (std::string indentation="\t")
~StyledStreamWriter ()
void write (std::ostream &out, const Value &root)
Serialize a Value in JSON format.
Private Types
typedef std::vector< std::string > ChildValues
Private Member Functions
void writeValue (const Value &value)
void writeArrayValue (const Value &value)
bool isMultineArray (const Value &value)
void pushValue (const std::string &value)
void writeIndent ()
void writeWithIndent (const std::string &value)
void indent ()
void unindent ()
void writeCommentBeforeValue (const Value &root)
void writeCommentAfterValueOnSameLine (const Value &root)
bool hasCommentForValue (const Value &value)
Static Private Member Functions
static std::string normalizeEOL (const std::string &text)
Private Attributes
ChildValues childValues_
std::ostream * document_
std::string indentString_
int rightMargin_
std::string indentation_
bool addChildValues_
Detailed Description
Writes a Value in JSON format in a human friendly way, to a stream rather than to a string.
The rules for line break and indent are as follow:
Object value:
if empty then print {} without indent and line break
if not empty the print '{', line break & indent, print one value per line and then unindent and line break and print '}'.
Array value:
if empty then print [] without indent and line break
if the array contains no object value, empty array or some other value types, and all the values fit on one lines, then print the array on a single line.
otherwise, it the values do not fit on one line, or the array contains object or non empty array, then print one value per line.
If the Value have comments then they are outputed according to their CommentPlacement.
Parameters
indentation Each level will be indented by this amount extra.
See Also
Reader, Value, Value::setComment()
Member Typedef Documentation
typedef std::vector<std::string> Json::StyledStreamWriter::ChildValues private
Constructor & Destructor Documentation
Json::StyledStreamWriter::StyledStreamWriter (std::string indentation = "\t")
Json::StyledStreamWriter::~StyledStreamWriter () inline
Member Function Documentation
bool Json::StyledStreamWriter::hasCommentForValue (const Value & value) private
References Json::commentAfter, Json::commentAfterOnSameLine, Json::commentBefore, and Json::Value::hasComment().
void Json::StyledStreamWriter::indent () private
References indentation_, and indentString_.
Referenced by writeArrayValue(), and writeValue().
bool Json::StyledStreamWriter::isMultineArray (const Value & value) private
References addChildValues_, childValues_, Json::Value::isArray(), Json::Value::isObject(), rightMargin_, Json::Value::size(), and writeValue().
Referenced by writeArrayValue().
std::string Json::StyledStreamWriter::normalizeEOL (const std::string & text) static private
Referenced by writeCommentAfterValueOnSameLine(), and writeCommentBeforeValue().
void Json::StyledStreamWriter::pushValue (const std::string & value) private
References addChildValues_, childValues_, and document_.
Referenced by writeArrayValue(), and writeValue().
void Json::StyledStreamWriter::unindent () private
References indentation_, and indentString_.
Referenced by writeArrayValue(), and writeValue().
void Json::StyledStreamWriter::write (std::ostream & out, const Value & root)
Serialize a Value in JSON format.
Parameters
out Stream to write to. (Can be ostringstream, e.g.)
root Value to serialize.
Note
There is no point in deriving from Writer, since write() should not return a value.
References addChildValues_, document_, indentString_, NULL, writeCommentAfterValueOnSameLine(), writeCommentBeforeValue(), and writeValue().
Referenced by Json::operator<<().
void Json::StyledStreamWriter::writeArrayValue (const Value & value) private
References childValues_, document_, indent(), isMultineArray(), pushValue(), Json::Value::size(), unindent(), writeCommentAfterValueOnSameLine(), writeCommentBeforeValue(), writeIndent(), writeValue(), and writeWithIndent().
Referenced by writeValue().
void Json::StyledStreamWriter::writeCommentAfterValueOnSameLine (const Value & root) private
References Json::commentAfter, Json::commentAfterOnSameLine, document_, Json::Value::getComment(), Json::Value::hasComment(), and normalizeEOL().
Referenced by write(), writeArrayValue(), and writeValue().
void Json::StyledStreamWriter::writeCommentBeforeValue (const Value & root) private
References Json::commentBefore, document_, Json::Value::getComment(), Json::Value::hasComment(), and normalizeEOL().
Referenced by write(), writeArrayValue(), and writeValue().
void Json::StyledStreamWriter::writeIndent () private
References document_, and indentString_.
Referenced by writeArrayValue(), and writeWithIndent().
void Json::StyledStreamWriter::writeValue (const Value & value) private
References Json::arrayValue, Json::Value::asBool(), Json::Value::asCString(), Json::Value::asDouble(), Json::Value::asLargestInt(), Json::Value::asLargestUInt(), Json::booleanValue, document_, Json::Value::getMemberNames(), indent(), Json::intValue, Json::nullValue, Json::objectValue, pushValue(), Json::realValue, Json::stringValue, Json::Value::type(), Json::uintValue, unindent(), Json::valueToQuotedString(), Json::valueToString(), writeArrayValue(), writeCommentAfterValueOnSameLine(), writeCommentBeforeValue(), and writeWithIndent().
Referenced by isMultineArray(), write(), and writeArrayValue().
void Json::StyledStreamWriter::writeWithIndent (const std::string & value) private
References document_, and writeIndent().
Referenced by writeArrayValue(), and writeValue().
Member Data Documentation
bool Json::StyledStreamWriter::addChildValues_ private
Referenced by isMultineArray(), pushValue(), and write().
ChildValues Json::StyledStreamWriter::childValues_ private
Referenced by isMultineArray(), pushValue(), and writeArrayValue().
std::ostream* Json::StyledStreamWriter::document_ private
Referenced by pushValue(), write(), writeArrayValue(), writeCommentAfterValueOnSameLine(), writeCommentBeforeValue(), writeIndent(), writeValue(), and writeWithIndent().
std::string Json::StyledStreamWriter::indentation_ private
Referenced by indent(), and unindent().
std::string Json::StyledStreamWriter::indentString_ private
Referenced by indent(), unindent(), write(), and writeIndent().
int Json::StyledStreamWriter::rightMargin_ private
Referenced by isMultineArray().
The documentation for this class was generated from the following files:
Client/json/json.h
Client/jsoncpp.cpp