Claims: CCSBInternalNode< T > Class Template Reference
CCSBInternalNode< T > Class Template Reference
#include <CSBPlusTree.h>
Public Member Functions
CCSBInternalNode ()
virtual ~CCSBInternalNode ()
bool setUsedKeys (int count)
data_offset< T > getElement (unsigned i)
bool setElement (unsigned i, T key)
CCSBNodeGroup< T > * getPointer ()
void setPointer (CCSBNodeGroup< T > *pointer)
bool Insert (T key)
bool Delete (T value)
T SplitInsert (CCSBNode< T > *pNode, T key)
bool Combine (CCSBNode< T > *pNode)
void DeleteChildren ()
bool serialize (FILE *filename)
bool deserialize (FILE *filename)
Public Member Functions inherited from CCSBNode< T >
CCSBNode ()
virtual ~CCSBNode ()
int getUsedKeys ()
CCSBNode< T > * getFather ()
void setFather (CCSBNode< T > *father)
virtual bool setElement (unsigned i, data_offset< T > value)
virtual bool Insert (data_offset< T > value)
virtual T SplitInsert (CCSBNode< T > *pNode, data_offset< T > data)
Public Attributes
T * node_keys
CCSBNodeGroup< T > * p_child_node_group
Public Attributes inherited from CCSBNode< T >
int used_keys
CCSBNode< T > * p_father
Additional Inherited Members
Static Public Member Functions inherited from CCSBNode< T >
static unsigned getMaxKeys ()
static unsigned getMaxDatas ()
Constructor & Destructor Documentation
template<typename T > CCSBInternalNode< T >::CCSBInternalNode ()
References INVALID, and NULL.
template<typename T > CCSBInternalNode< T >::~CCSBInternalNode () virtual
References NULL.
Member Function Documentation
template<typename T > bool CCSBInternalNode< T >::Combine (CCSBNode< T > * pNode) virtual
Reimplemented from CCSBNode< T >.
template<typename T > bool CCSBInternalNode< T >::Delete (T value) virtual
Reimplemented from CCSBNode< T >.
template<typename T > void CCSBInternalNode< T >::DeleteChildren () virtual
Reimplemented from CCSBNode< T >.
template<typename T > bool CCSBInternalNode< T >::deserialize (FILE * filename) virtual
Reimplemented from CCSBNode< T >.
Referenced by CCSBInternalNodeGroup< T >::deserialize().
template<typename T> data_offset<T> CCSBInternalNode< T >::getElement (unsigned i) inline virtual
Reimplemented from CCSBNode< T >.
References data_offset< T >::_block_off, data_offset< T >::_key, data_offset< T >::_tuple_off, and INVALID.
template<typename T> CCSBNodeGroup<T>* CCSBInternalNode< T >::getPointer () inline virtual
Reimplemented from CCSBNode< T >.
template<typename T > bool CCSBInternalNode< T >::Insert (T key) virtual
Reimplemented from CCSBNode< T >.
template<typename T > bool CCSBInternalNode< T >::serialize (FILE * filename) virtual
Reimplemented from CCSBNode< T >.
template<typename T> bool CCSBInternalNode< T >::setElement (unsigned i, T key) inline virtual
Reimplemented from CCSBNode< T >.
template<typename T> void CCSBInternalNode< T >::setPointer (CCSBNodeGroup< T > * pointer) inline virtual
Reimplemented from CCSBNode< T >.
template<typename T> bool CCSBInternalNode< T >::setUsedKeys (int count) inline virtual
Reimplemented from CCSBNode< T >.
template<typename T > T CCSBInternalNode< T >::SplitInsert (CCSBNode< T > * pNode, T key) virtual
Reimplemented from CCSBNode< T >.
References CCSBNode< T >::getElement(), CCSBNode< T >::Insert(), INVALID, CCSBNode< T >::setElement(), and CCSBNode< T >::setUsedKeys().
Member Data Documentation
template<typename T> T* CCSBInternalNode< T >::node_keys
template<typename T> CCSBNodeGroup<T>* CCSBInternalNode< T >::p_child_node_group
The documentation for this class was generated from the following files:
IndexManager/CSBPlusTree.h
IndexManager/CSBPlusTree.cpp