My Project: claims::logical_operator::LogicalEqualJoin Class Reference
claims::logical_operator::LogicalEqualJoin Class Reference
Generate equal join logical plan.
#include <logical_equal_join.h>
Classes
struct JoinPair
The JoinPair contains two attributes to be joined.
Public Types
enum JoinPolicy {
kNull, kNoRepartition, kLeftRepartition, kRightRepartition,
kCompleteRepartition
}
Public Member Functions
LogicalEqualJoin (std::vector< JoinPair >, LogicalOperator *left_input, LogicalOperator *right_input)
Method description:Create a EqualJoin implement.
PlanContext GetPlanContext ()
Method description: Get the child information.
BlockStreamIteratorBase * GetPhysicalPlan (const unsigned &blocksize)
bool GetOptimalPhysicalPlan (Requirement requirement, PhysicalPlanDescriptor &physical_plan_descriptor, const unsigned &block_size=4096 *1024)
Additional Inherited Members
Protected Member Functions inherited from claims::logical_operator::LogicalOperator
Schema * GetSchema (const std::vector< Attribute > &) const
Schema * GetSchema (const std::vector< Attribute > &, const std::vector< Attribute > &) const
std::vector< NodeID > GetInvolvedNodeID (const PlanPartitioner &) const
std::vector< NodeIP > ConvertNodeIDListToNodeIPList (const std::vector< NodeID > &) const
PhysicalPlanDescriptor GetBestPhysicalPlanDescriptor (const std::vector< PhysicalPlanDescriptor >) const
int GetIdInAttributeList (const std::vector< Attribute > &attributes, const Attribute &attribute) const
void set_operator_type (OperatorType operator_type)
Detailed Description
Generate equal join logical plan.
EqualJoin operator achieves the join statement tables.It requires equivalent conditions.As for implementation, one is to send all data to a same machine.But the generated table will be too big to store and it is inefficient.So we partition the data to several machines.Each of them does some join and return.
Constructor & Destructor Documentation
claims::logical_operator::LogicalEqualJoin::LogicalEqualJoin (std::vector< JoinPair > joinpair_list, LogicalOperator * left_input, LogicalOperator * right_input)
Method description:Create a EqualJoin implement.
Parameters
std::vector<JoinPair>
LogicalOperator* left_input
LogicalOperator* right_input
Member Function Documentation
bool claims::logical_operator::LogicalEqualJoin::GetOptimalPhysicalPlan (Requirement requirement, PhysicalPlanDescriptor & physical_plan_descriptor, const unsigned & block_size = 4096 * 1024) virtual
get the optimal Physical plan that meets the requirement.
Returns
true if find physical plan that meets the requirement and store the physical plan and its corresponding information in physical_plan_descriptor.
Reimplemented from claims::logical_operator::LogicalOperator.
BlockStreamIteratorBase * claims::logical_operator::LogicalEqualJoin::GetPhysicalPlan (const unsigned &) virtual
generate the iterator tree based on the computed plan_context. Hence, this function can only be called after the calling of GetPlanContext().
In the initial implementation, I set the bucket size to be up round to cache line size, e.g., 64Bytes. Finally, I realized that different from aggregation,the hash table bucket in the build phase of hash join is filled very quickly and hence a * a relatively large bucket size could reduce the number of overflowing buckets and avoid the random memory access caused by acceesing overflowing buckets.
Implements claims::logical_operator::LogicalOperator.
References claims::logical_operator::LogicalOperator::GetPhysicalPlan(), claims::logical_operator::LogicalOperator::GetPlanContext(), GetPlanContext(), and Config::initial_degree_of_parallelism.
PlanContext claims::logical_operator::LogicalEqualJoin::GetPlanContext () virtual
Method description: Get the child information.
The mostly important member is "property" and "attributes list". When getting data from child, we make some choices according to JoinPolice. JoinPolice is generated from canLeverageHashPartition(), isEqualCondition(), hasSamePartition(). If all of them is true, it means partition_key in the join_list and two partition_keys in the same join_pair.Besides, it they have partitioned to the same machine.So we don't need repartition, and JoinPolice = kNodeRepartition. If both canLeverageHashPartition()s are true, but isEqualCondition() or hasSamePartition() is false, the machine which has smaller data will send its data to another according to decideLeftOrRightRepartition(). If canLeverageHashPartition(left) is true but canLeverageHashPartition (right) is false, right nodes will be repartitioned. join_police_ = kRightRepartition If canLeverageHashPartition(left) is false but canLeverageHashPartition (right) is true, left nodes will be repartitioned. oin_police_ = kLeftRepartition If both canLeverageHashPartition()s are false, left and right nodes will be repartitioned. join_police_ = kCompleteRepartition
in the current implementation, only the hash join is considered
finally, construct the output data flow according to the join police
Use the left partitioner as the output dataflow partitioner. TODO(admin): In fact, the output dataflow partitioner should contains both left partitioner and right partitioner.
Set the generated data size. Currently, we assume the generated data size is the sum of input data volume. TODO(admin): Some reasonable output size estimation is needed.
set the generated data size
TODO(admin): the repartition strategy (e.g., the degree of parallelism and the partition function) in such case is not decided by any child data flow. Additional optimization can be made by adopting the partition strategy which benefits the remaining work.
Implements claims::logical_operator::LogicalOperator.
References claims::logical_operator::LogicalOperator::GetPlanContext(), and claims::logical_operator::PlanPartitioner::HasSamePartitionLocation().
Referenced by GetPhysicalPlan().
The documentation for this class was generated from the following files:
logical_operator/logical_equal_join.h
logical_operator/logical_equal_join.cpp