Claims: bottomLayerSorting Class Reference
bottomLayerSorting Class Reference
#include <CSBIndexBuilding.h>
Classes
struct compare_node
class State
Public Types
typedef struct
bottomLayerSorting::compare_node compare_node
Public Types inherited from claims::physical_operator::PhysicalOperator
enum context_reuse_mode { crm_no_reuse, crm_core_sensitive, crm_numa_sensitive, crm_anyway }
Public Member Functions
bottomLayerSorting ()
bottomLayerSorting (State state)
virtual ~bottomLayerSorting ()
bool Open (const PartitionOffset &partition_offset=0)
bool Next (BlockStreamBase *block)
bool Close ()
Public Member Functions inherited from claims::physical_operator::PhysicalOperator
PhysicalOperator (unsigned number_of_barrier=1, unsigned number_of_seriliazed_section=1)
virtual ~PhysicalOperator ()
virtual void Print ()
virtual ThreadContext * CreateContext ()
Public Member Functions inherited from claims::physical_operator::PhysicalOperatorBase
PhysicalOperatorBase ()
virtual ~PhysicalOperatorBase ()
virtual ResultSet * GetResultSet ()
Private Member Functions
template<typename T >
CSBPlusTree< T > * indexBuilding (vector< compare_node * > chunk_tuples)
void computeVectorSchema ()
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Static Private Member Functions
static bool compare (const compare_node *a, const compare_node *b)
Private Attributes
State state_
Schema * vector_schema_
std::map< ChunkOffset, vector
< compare_node * > > tuples_in_chunk_
PartitionID partition_id_
Friends
class boost::serialization::access
Additional Inherited Members
Static Public Member Functions inherited from claims::physical_operator::PhysicalOperatorBase
static PhysicalOperatorBase * createIterator (const string &IteratorName)
Protected Member Functions inherited from claims::physical_operator::PhysicalOperator
ThreadContext * CreateOrReuseContext (context_reuse_mode crm)
void InitExpandedStatus ()
bool TryEntryIntoSerializedSection (unsigned serialized_section_id=0)
void RegisterExpandedThreadToAllBarriers ()
void UnregisterExpandedThreadToAllBarriers (unsigned barrier_index=0)
void BarrierArrive (unsigned barrier_index=0)
void InitContext (ThreadContext *tc)
ThreadContext * GetContext ()
void DestoryAllContext ()
bool CheckTerminateRequest ()
void SetReturnStatus (bool ret)
bool GetReturnStatus () const
Protected Attributes inherited from claims::physical_operator::PhysicalOperator
unsigned number_of_registered_expanded_threads_
Member Typedef Documentation
typedef struct bottomLayerSorting::compare_node bottomLayerSorting::compare_node
Constructor & Destructor Documentation
bottomLayerSorting::bottomLayerSorting ()
References claims::physical_operator::PhysicalOperator::InitExpandedStatus().
bottomLayerSorting::bottomLayerSorting (State state)
References claims::physical_operator::PhysicalOperator::InitExpandedStatus().
bottomLayerSorting::~bottomLayerSorting () virtual
Member Function Documentation
bool bottomLayerSorting::Close () virtual
Reimplemented from claims::physical_operator::PhysicalOperator.
References bottomLayerSorting::State::child_, claims::physical_operator::PhysicalOperatorBase::Close(), claims::physical_operator::PhysicalOperator::InitExpandedStatus(), and state_.
bool bottomLayerSorting::compare (const compare_node * a, const compare_node * b) static private
References Schema::getColumnAddess(), Operate::less(), bottomLayerSorting::compare_node::op_, bottomLayerSorting::compare_node::tuple_, and bottomLayerSorting::compare_node::vector_schema_.
Referenced by Open().
void bottomLayerSorting::computeVectorSchema () private
References Schema::getcolumn(), bottomLayerSorting::State::schema_, state_, t_u_smallInt, and vector_schema_.
Referenced by Open().
template<typename T > CSBPlusTree< T > * bottomLayerSorting::indexBuilding (vector< compare_node * > chunk_tuples) private
for testing/ cout << "chunk data size: " << chunk_tuples.size() << endl << endl;
for testing/ cout << aray[i]._key << "\t" << aray[i]._block_off << "\t" << aray[i]._tuple_off << endl;
References data_offset< T >::_block_off, data_offset< T >::_key, data_offset< T >::_tuple_off, Schema::getColumnAddess(), and vector_schema_.
bool bottomLayerSorting::Next (BlockStreamBase * block) virtual
Reimplemented from claims::physical_operator::PhysicalOperator.
References ChunkID::chunk_off, Schema::getcolumn(), IndexManager::getInstance(), bottomLayerSorting::State::index_name_, IndexManager::insertIndexToList(), bottomLayerSorting::State::key_indexing_, ChunkID::partition_id, partition_id_, state_, t_int, tuples_in_chunk_, column_type::type, and vector_schema_.
bool bottomLayerSorting::Open (const PartitionOffset & part_off = 0) virtual
Because that boost::serialization will allocate an instance of this class when deserializing, and hence the following three virtual method cannot be pure.
for testing/ cout << "chunk id: " << *(unsigned short*)iter->first << endl;
Reimplemented from claims::physical_operator::PhysicalOperator.
References claims::physical_operator::PhysicalOperator::BarrierArrive(), bottomLayerSorting::State::block_size_, bottomLayerSorting::State::child_, compare(), computeVectorSchema(), Schema::copyTuple(), BlockStreamBase::createBlock(), BlockStreamBase::createIterator(), Operate::duplicateOperator(), column_type::get_length(), Schema::getcolumn(), Schema::getColumnValue(), claims::physical_operator::PhysicalOperator::GetReturnStatus(), Schema::getTupleMaxSize(), claims::physical_operator::PhysicalOperatorBase::Next(), BlockStreamBase::BlockStreamTraverseIterator::nextTuple(), NULL, bottomLayerSorting::compare_node::op_, claims::physical_operator::PhysicalOperatorBase::Open(), column_type::operate, partition_id_, PartitionID::partition_off, PartitionID::projection_id, bottomLayerSorting::State::projection_id_, bottomLayerSorting::State::schema_, BlockStreamBase::setEmpty(), claims::physical_operator::PhysicalOperator::SetReturnStatus(), state_, claims::physical_operator::PhysicalOperator::TryEntryIntoSerializedSection(), bottomLayerSorting::compare_node::tuple_, tuples_in_chunk_, bottomLayerSorting::compare_node::vector_schema_, and vector_schema_.
template<class Archive > void bottomLayerSorting::serialize (Archive & ar, const unsigned int version) inline private
References state_.
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
PartitionID bottomLayerSorting::partition_id_ private
Referenced by Next(), and Open().
State bottomLayerSorting::state_ private
Referenced by Close(), computeVectorSchema(), Next(), Open(), and serialize().
std::map<ChunkOffset, vector<compare_node*> > bottomLayerSorting::tuples_in_chunk_ private
Referenced by Next(), and Open().
Schema* bottomLayerSorting::vector_schema_ private
Referenced by computeVectorSchema(), indexBuilding(), Next(), and Open().
The documentation for this class was generated from the following files:
IndexManager/CSBIndexBuilding.h
IndexManager/CSBIndexBuilding.cpp