Claims: IteratorExecutorMaster Class Reference
IteratorExecutorMaster Class Reference
#include <IteratorExecutorMaster.h>
Public Member Functions
IteratorExecutorMaster ()
virtual ~IteratorExecutorMaster ()
bool ExecuteBlockStreamIteratorsOnSites (PhysicalOperatorBase *it, std::vector< std::string > ip_list)
bool ExecuteBlockStreamIteratorsOnSite (PhysicalOperatorBase *it, NodeID target_ip)
bool Propogation (const int, std::string target)
Static Public Member Functions
static IteratorExecutorMaster * getInstance ()
Private Attributes
Theron::EndPoint * endpoint
Theron::Framework * framework
Logging * logging_
Static Private Attributes
static IteratorExecutorMaster * _instance =0
Constructor & Destructor Documentation
IteratorExecutorMaster::IteratorExecutorMaster ()
References _instance, endpoint, framework, Environment::getEndPoint(), Environment::getInstance(), and logging_.
Referenced by getInstance().
IteratorExecutorMaster::~IteratorExecutorMaster () virtual
References _instance, and framework.
Member Function Documentation
bool IteratorExecutorMaster::ExecuteBlockStreamIteratorsOnSite (PhysicalOperatorBase * it, NodeID target_ip)
References IteratorExecutorSlave::createNewThreadAndRun(), PhysicalQueryPlan::deserialize4K(), framework, Environment::getInstance(), Environment::getIteratorExecutorSlave(), Logging::log(), logging_, and PhysicalQueryPlan::serialize4K().
Referenced by claims::physical_operator::ExchangeMerger::SerializeAndSendPlan().
bool IteratorExecutorMaster::ExecuteBlockStreamIteratorsOnSites (PhysicalOperatorBase * it, std::vector< std::string > ip_list)
References Logging::elog(), endpoint, framework, Logging::log(), logging_, PhysicalQueryPlan::serialize4K(), and TimeOutReceiver::TimeOutWait().
IteratorExecutorMaster * IteratorExecutorMaster::getInstance () static
References _instance, and IteratorExecutorMaster().
Referenced by IteratorExecutorSlave::ExecuteIteratorActor::progation(), claims::physical_operator::ExchangeMerger::SerializeAndSendPlan(), and testIteratorExecutor().
bool IteratorExecutorMaster::Propogation (const int count, std::string target)
References framework.
Referenced by IteratorExecutorSlave::ExecuteIteratorActor::progation(), and testIteratorExecutor().
Member Data Documentation
IteratorExecutorMaster * IteratorExecutorMaster::_instance =0 static private
Referenced by getInstance(), IteratorExecutorMaster(), and ~IteratorExecutorMaster().
Theron::EndPoint* IteratorExecutorMaster::endpoint private
Referenced by ExecuteBlockStreamIteratorsOnSites(), and IteratorExecutorMaster().
Theron::Framework* IteratorExecutorMaster::framework private
Referenced by ExecuteBlockStreamIteratorsOnSite(), ExecuteBlockStreamIteratorsOnSites(), IteratorExecutorMaster(), Propogation(), and ~IteratorExecutorMaster().
Logging* IteratorExecutorMaster::logging_ private
Referenced by ExecuteBlockStreamIteratorsOnSite(), ExecuteBlockStreamIteratorsOnSites(), and IteratorExecutorMaster().
The documentation for this class was generated from the following files:
Executor/IteratorExecutorMaster.h
Executor/IteratorExecutorMaster.cpp