Claims: Daemon Class Reference
Daemon Class Reference
#include <Daemon.h>
Public Member Functions
void addRemoteCommand (const remote_command &rc)
executed_result getExecutedResult ()
Static Public Member Functions
static Daemon * getInstance ()
static void * worker (void *)
Private Member Functions
Daemon ()
virtual ~Daemon ()
remote_command getRemoteCommand ()
void addExecutedResult (const executed_result &item)
Private Attributes
std::list< remote_command > remote_command_queue_
semaphore semaphore_command_queue_
std::list< executed_result > executed_result_queue_
semaphore semaphore_result_queue_
Lock lock_
Static Private Attributes
static Daemon * instance_ = 0
Constructor & Destructor Documentation
Daemon::Daemon () private
References NULL, WORK_THREAD_COUNT, and worker().
Referenced by getInstance().
Daemon::~Daemon () private virtual
Member Function Documentation
void Daemon::addExecutedResult (const executed_result & item) private
References Lock::acquire(), executed_result_queue_, lock_, semaphore::post(), Lock::release(), and semaphore_result_queue_.
Referenced by worker().
void Daemon::addRemoteCommand (const remote_command & rc)
References Lock::acquire(), lock_, semaphore::post(), Lock::release(), remote_command_queue_, and semaphore_command_queue_.
Referenced by ClientListener::receiveRequest().
executed_result Daemon::getExecutedResult ()
References Lock::acquire(), executed_result_queue_, lock_, Lock::release(), semaphore_result_queue_, and semaphore::wait().
Referenced by ClientListener::sendHandler().
Daemon * Daemon::getInstance () static
References Daemon(), and instance_.
Referenced by ClientListener::receiveRequest(), ClientListener::sendHandler(), and worker().
remote_command Daemon::getRemoteCommand () private
References Lock::acquire(), lock_, Lock::release(), remote_command_queue_, semaphore_command_queue_, and semaphore::wait().
Referenced by worker().
void * Daemon::worker (void * para) static
References addExecutedResult(), ClientListener::checkFdValid(), remote_command::cmd, executed_result::error_info, executed_result::fd, getInstance(), getRemoteCommand(), executed_result::info, ClientLogging::log(), NULL, executed_result::result, Executing::run_sql(), remote_command::socket_fd, and executed_result::status.
Referenced by Daemon().
Member Data Documentation
std::list<executed_result> Daemon::executed_result_queue_ private
Referenced by addExecutedResult(), and getExecutedResult().
Daemon * Daemon::instance_ = 0 static private
Referenced by getInstance().
Lock Daemon::lock_ private
Referenced by addExecutedResult(), addRemoteCommand(), getExecutedResult(), and getRemoteCommand().
std::list<remote_command> Daemon::remote_command_queue_ private
Referenced by addRemoteCommand(), and getRemoteCommand().
semaphore Daemon::semaphore_command_queue_ private
Referenced by addRemoteCommand(), and getRemoteCommand().
semaphore Daemon::semaphore_result_queue_ private
Referenced by addExecutedResult(), and getExecutedResult().
The documentation for this class was generated from the following files:
Daemon/Daemon.h
Daemon/Daemon.cpp