Claims: DynamicBlockBuffer::Iterator Class Reference
DynamicBlockBuffer::Iterator Class Reference
#include <DynamicBlockBuffer.h>
Public Member Functions
Iterator (const DynamicBlockBuffer *dbb)
Iterator (const Iterator &)
Iterator ()
BlockStreamBase * nextBlock ()
BlockStreamBase * atomicNextBlock ()
Private Attributes
unsigned cur_
const DynamicBlockBuffer * dbb_
Lock lock_
Constructor & Destructor Documentation
DynamicBlockBuffer::Iterator::Iterator (const DynamicBlockBuffer * dbb)
DynamicBlockBuffer::Iterator::Iterator (const Iterator & it)
References cur_, dbb_, lock_, and DynamicBlockBuffer::lock_.
DynamicBlockBuffer::Iterator::Iterator ()
Member Function Documentation
BlockStreamBase * DynamicBlockBuffer::Iterator::atomicNextBlock ()
References Lock::acquire(), DynamicBlockBuffer::lock_, and Lock::release().
Referenced by Analyzer::analyse(), Analyzer::computeHistogram(), insert_into_insert_optimized_hash_table(), query_2(), and ClientListener::sendHandler().
BlockStreamBase * DynamicBlockBuffer::Iterator::nextBlock ()
References Block::getBlock().
Referenced by Analyzer::compute_table_stat(), DynamicBlockBuffer::destory(), Analyzer::getDistinctCardinality(), DynamicBlockBuffer::getNumberOftuples(), claims::physical_operator::ResultCollector::GetNumberOftuples(), claims::physical_operator::PhysicalNestLoopJoin::Next(), ResultSet::print(), ClientListener::sendJsonPacket(), TEST(), TEST_F(), test_multiple_scan_filter_Scalar_Aggregation(), and test_scan_filter_Scalar_Aggregation().
Member Data Documentation
unsigned DynamicBlockBuffer::Iterator::cur_ private
Referenced by Iterator().
const DynamicBlockBuffer* DynamicBlockBuffer::Iterator::dbb_ private
Referenced by Iterator().
Lock DynamicBlockBuffer::Iterator::lock_ private
Referenced by Iterator().
The documentation for this class was generated from the following files:
common/Block/DynamicBlockBuffer.h
common/Block/DynamicBlockBuffer.cpp