Claims: IteratorExecutorSlave Class Reference
IteratorExecutorSlave Class Reference
#include <IteratorExecutorSlave.h>
Classes
class ExecuteIteratorActor
Public Member Functions
IteratorExecutorSlave ()
virtual ~IteratorExecutorSlave ()
void createNewThreadAndRun (PhysicalQueryPlan *)
Static Public Member Functions
static void executePhysicalQueryPlan (PhysicalQueryPlan plan)
Protected Attributes
Logging * logging_
Static Private Member Functions
static void * run_iterator (void *)
Private Attributes
ExecuteIteratorActor * execute_iterator_actor
Theron::Framework * framework
Theron::EndPoint * endpoint
std::string slave_id
SpineLock lock_
std::set< pthread_t > busy_thread_list_
Friends
class ExecuteIteratorActor
Constructor & Destructor Documentation
IteratorExecutorSlave::IteratorExecutorSlave ()
References endpoint, execute_iterator_actor, ExecuteIteratorActor, framework, Environment::getEndPoint(), Environment::getInstance(), Environment::getNodeID(), Logging::log(), and logging_.
IteratorExecutorSlave::~IteratorExecutorSlave () virtual
References execute_iterator_actor, framework, and logging_.
Member Function Documentation
void IteratorExecutorSlave::createNewThreadAndRun (PhysicalQueryPlan * it)
References SpineLock::acquire(), busy_thread_list_, lock_, Logging::log(), logging_, NULL, SpineLock::release(), and run_iterator().
Referenced by IteratorExecutorMaster::ExecuteBlockStreamIteratorsOnSite().
void IteratorExecutorSlave::executePhysicalQueryPlan (PhysicalQueryPlan plan) static
References PhysicalQueryPlan::run().
Referenced by query_1(), run_iterator(), test_complete_repartition_filtered_join(), test_complete_repartition_scan_join(), test_no_repartition_filtered_join(), test_no_repartition_scan_join(), test_scan_Aggregation_large_Groups(), test_scan_Aggregation_small_Groups(), test_scan_filter_Aggregation(), test_scan_filter_high_selectivity(), test_scan_filter_low_selectivity(), and test_scan_filter_Scalar_Aggregation().
void * IteratorExecutorSlave::run_iterator (void * arg) static private
References SpineLock::acquire(), busy_thread_list_, executePhysicalQueryPlan(), lock_, Logging::log(), logging_, and SpineLock::release().
Referenced by createNewThreadAndRun().
Friends And Related Function Documentation
friend class ExecuteIteratorActor friend
Referenced by IteratorExecutorSlave().
Member Data Documentation
std::set<pthread_t> IteratorExecutorSlave::busy_thread_list_ private
Referenced by createNewThreadAndRun(), and run_iterator().
Theron::EndPoint* IteratorExecutorSlave::endpoint private
Referenced by IteratorExecutorSlave().
ExecuteIteratorActor* IteratorExecutorSlave::execute_iterator_actor private
Referenced by IteratorExecutorSlave(), and ~IteratorExecutorSlave().
Theron::Framework* IteratorExecutorSlave::framework private
Referenced by IteratorExecutorSlave(), and ~IteratorExecutorSlave().
SpineLock IteratorExecutorSlave::lock_ private
Referenced by createNewThreadAndRun(), and run_iterator().
Logging* IteratorExecutorSlave::logging_ protected
Referenced by createNewThreadAndRun(), IteratorExecutorSlave(), run_iterator(), and ~IteratorExecutorSlave().
std::string IteratorExecutorSlave::slave_id private
The documentation for this class was generated from the following files:
Executor/IteratorExecutorSlave.h
Executor/IteratorExecutorSlave.cpp