Claims: TableStatistic Class Reference
TableStatistic Class Reference
#include <TableStatistic.h>
Public Member Functions
TableStatistic ()
virtual ~TableStatistic ()
void addAttributeStatistics (const AttributeID &attr_id, AttributeStatistics *stat)
AttributeStatistics * getAttributeStatistics (const AttributeID &attr_id) const
unsigned long getCardinality () const
void print () const
Public Attributes
unsigned long number_of_tuples_
Private Attributes
boost::unordered_map
< AttributeID,
AttributeStatistics * > att_stat_list_
Constructor & Destructor Documentation
TableStatistic::TableStatistic ()
TableStatistic::~TableStatistic () virtual
Member Function Documentation
void TableStatistic::addAttributeStatistics (const AttributeID & attr_id, AttributeStatistics * stat)
References att_stat_list_.
Referenced by Analyzer::compute_attribute_stat().
AttributeStatistics * TableStatistic::getAttributeStatistics (const AttributeID & attr_id) const
References att_stat_list_.
Referenced by Analyzer::compute_attribute_stat(), and StatManager::getAttributeStatistic().
unsigned long TableStatistic::getCardinality () const
References number_of_tuples_.
Referenced by claims::logical_operator::LogicalEqualJoin::PredictEqualJoinSelectivityOnSingleJoinAttributePair().
void TableStatistic::print () const
References number_of_tuples_.
Referenced by Analyzer::compute_table_stat().
Member Data Documentation
boost::unordered_map<AttributeID,AttributeStatistics*> TableStatistic::att_stat_list_ private
Referenced by addAttributeStatistics(), and getAttributeStatistics().
unsigned long TableStatistic::number_of_tuples_
Referenced by Analyzer::compute_attribute_stat(), Analyzer::compute_table_stat(), getCardinality(), and print().
The documentation for this class was generated from the following files:
Catalog/stat/TableStatistic.h
Catalog/stat/TableStatistic.cpp