Claims: BlockStreamFix Class Reference
BlockStreamFix Class Reference
#include <BlockStream.h>
Classes
struct tail_info
Public Member Functions
BlockStreamFix (unsigned block_size, unsigned tuple_size)
BlockStreamFix (unsigned block_size, unsigned tuple_size, void *start_addr, unsigned ntuples)
virtual ~BlockStreamFix ()
void * allocateTuple (unsigned bytes)
void setTuplesInBlock (unsigned n)
void setEmpty ()
void * getTuple (unsigned offset) const
bool Empty () const
bool Full () const
void * getBlockDataAddress ()
bool switchBlock (BlockStreamBase &block)
void copyBlock (void *addr, unsigned length)
bool insert (void *dest, void *src, unsigned bytes)
void deepCopy (const Block *block)
bool serialize (Block &block) const
bool deserialize (Block *block)
unsigned getSerializedBlockSize () const
unsigned getBlockCapacityInTuples () const
unsigned getTuplesInBlock () const
void constructFromBlock (const Block &block)
BlockStreamBase * createBlockAndDeepCopy ()
Public Member Functions inherited from BlockStreamBase
BlockStreamBase (unsigned block_size)
BlockStreamBase (unsigned block_size, void *start_addr)
virtual ~BlockStreamBase ()
BlockStreamTraverseIterator * createIterator ()
Public Member Functions inherited from Block
Block (unsigned BlockSize)
Block (const Block &block)
Block (const unsigned &size, const void *start)
virtual ~Block ()
void * getBlock () const
void setBlock (void *)
unsigned getsize () const
unsigned setsize (const unsigned &size)
bool isIsReference () const
void setIsReference (bool isReference)
Public Attributes
unsigned tuple_size_
char * free_
Friends
class BlockStreamBase
Additional Inherited Members
Static Public Member Functions inherited from BlockStreamBase
static BlockStreamBase * createBlock (const Schema *const &schema, unsigned block_size)
static BlockStreamBase * createBlockWithDesirableSerilaizedSize (Schema *schema, unsigned block_size)
Protected Attributes inherited from Block
unsigned BlockSize
char * start
Constructor & Destructor Documentation
BlockStreamFix::BlockStreamFix (unsigned block_size, unsigned tuple_size)
References free_, and Block::start.
Referenced by createBlockAndDeepCopy().
BlockStreamFix::BlockStreamFix (unsigned block_size, unsigned tuple_size, void * start_addr, unsigned ntuples)
BlockStreamFix::~BlockStreamFix () virtual
Member Function Documentation
void* BlockStreamFix::allocateTuple (unsigned bytes) inline virtual
Implements BlockStreamBase.
void BlockStreamFix::constructFromBlock (const Block & block) virtual
a remedy for the data loading bug...
Implements BlockStreamBase.
References Block::BlockSize, free_, Block::getBlock(), Block::getsize(), Block::start, and tuple_size_.
void BlockStreamFix::copyBlock (void * addr, unsigned length) virtual
Implements BlockStreamBase.
References Block::BlockSize, free_, and Block::start.
BlockStreamBase * BlockStreamFix::createBlockAndDeepCopy () virtual
Implements BlockStreamBase.
References Block::BlockSize, BlockStreamFix(), BlockStreamBase::deepCopy(), Block::getBlock(), getTuplesInBlock(), Block::isIsReference(), and tuple_size_.
void BlockStreamFix::deepCopy (const Block * block) virtual
deep copy from block, including block content and member variables that maintain the block status. the user should guarantee that rest block and desc block are of equal derived class type(e.g., both are BlockStreamFix), otherwise the copy may be incomplete.
Implements BlockStreamBase.
References Block::BlockSize, free_, Block::getBlock(), Block::getsize(), Block::start, and tuple_size_.
bool BlockStreamFix::deserialize (Block * block) virtual
Implements BlockStreamBase.
References Block::BlockSize, free_, Block::getBlock(), Block::getsize(), Block::start, and tuple_size_.
bool BlockStreamFix::Empty () const virtual
Implements BlockStreamBase.
References free_, and Block::start.
bool BlockStreamFix::Full () const inline virtual
Implements BlockStreamBase.
unsigned BlockStreamFix::getBlockCapacityInTuples () const virtual
Implements BlockStreamBase.
References Block::BlockSize, and tuple_size_.
void * BlockStreamFix::getBlockDataAddress () virtual
Implements BlockStreamBase.
References Block::start.
unsigned BlockStreamFix::getSerializedBlockSize () const virtual
Implements BlockStreamBase.
References Block::BlockSize.
void* BlockStreamFix::getTuple (unsigned offset) const inline virtual
Implements BlockStreamBase.
unsigned BlockStreamFix::getTuplesInBlock () const virtual
Implements BlockStreamBase.
References free_, Block::start, and tuple_size_.
Referenced by createBlockAndDeepCopy().
bool BlockStreamFix::insert (void * dest, void * src, unsigned bytes) virtual
Implements BlockStreamBase.
bool BlockStreamFix::serialize (Block & block) const virtual
Implements BlockStreamBase.
References Block::BlockSize, free_, Block::getBlock(), Block::getsize(), Block::start, BlockStreamFix::tail_info::tuple_count, and tuple_size_.
void BlockStreamFix::setEmpty () virtual
Implements BlockStreamBase.
References free_, and Block::start.
void BlockStreamFix::setTuplesInBlock (unsigned n) inline
bool BlockStreamFix::switchBlock (BlockStreamBase & block) virtual
Implements BlockStreamBase.
References Block::BlockSize, free_, and Block::start.
Friends And Related Function Documentation
friend class BlockStreamBase friend
Member Data Documentation
char* BlockStreamFix::free_
Referenced by BlockStreamFix(), constructFromBlock(), copyBlock(), deepCopy(), deserialize(), Empty(), getTuplesInBlock(), serialize(), setEmpty(), and switchBlock().
unsigned BlockStreamFix::tuple_size_
Referenced by constructFromBlock(), createBlockAndDeepCopy(), deepCopy(), deserialize(), getBlockCapacityInTuples(), getTuplesInBlock(), and serialize().
The documentation for this class was generated from the following files:
common/Block/BlockStream.h
common/Block/BlockStream.cpp