My Project: claims::logical_operator::LogicalProject Class Reference
claims::logical_operator::LogicalProject Class Reference
Public Member Functions
LogicalProject (LogicalOperator *child, vector< QNode * > expression_tree)
PlanContext GetPlanContext ()
Method description : construct a PlanContext from child.
BlockStreamIteratorBase * GetPhysicalPlan (const unsigned &kBlockSize)
Method description: generate a few physical operations according to this logical operation.
virtual bool GetOptimalPhysicalPlan (Requirement requirement, PhysicalPlanDescriptor &physical_plan_descriptor, const unsigned &kBlockSize=4096 *1024)
void Print (int level=0) const
Method description:Print the schema.
Additional Inherited Members
Protected Member Functions inherited from claims::logical_operator::LogicalOperator
Schema * GetSchema (const std::vector< Attribute > &) const
Schema * GetSchema (const std::vector< Attribute > &, const std::vector< Attribute > &) const
std::vector< NodeID > GetInvolvedNodeID (const PlanPartitioner &) const
std::vector< NodeIP > ConvertNodeIDListToNodeIPList (const std::vector< NodeID > &) const
PhysicalPlanDescriptor GetBestPhysicalPlanDescriptor (const std::vector< PhysicalPlanDescriptor >) const
int GetIdInAttributeList (const std::vector< Attribute > &attributes, const Attribute &attribute) const
void set_operator_type (OperatorType operator_type)
Member Function Documentation
virtual bool claims::logical_operator::LogicalProject::GetOptimalPhysicalPlan (Requirement requirement, PhysicalPlanDescriptor & physical_plan_descriptor, const unsigned & block_size = 4096 * 1024) inline virtual
get the optimal Physical plan that meets the requirement.
Returns
true if find physical plan that meets the requirement and store the physical plan and its corresponding information in physical_plan_descriptor.
Reimplemented from claims::logical_operator::LogicalOperator.
BlockStreamIteratorBase * claims::logical_operator::LogicalProject::GetPhysicalPlan (const unsigned & kBlockSize) virtual
Method description: generate a few physical operations according to this logical operation.
Parameters
block_size : give the size of block in physical plan
Returns
the total physical plan include the physical plan generated by child operation
Implements claims::logical_operator::LogicalOperator.
References claims::logical_operator::LogicalOperator::GetPhysicalPlan(), GetPlanContext(), and claims::logical_operator::LogicalOperator::GetPlanContext().
PlanContext claims::logical_operator::LogicalProject::GetPlanContext () virtual
Method description : construct a PlanContext from child.
Returns
: constructed plan_context
set commnication_cost and partitioner of the PlanContext to be returned from PlanContext of child
if the expression type is compare,then the new column will be boolean type, else will be it's actual type according to the variable
if the return type is a String value,then we have to calculate the length of the string else just construct a column having the same type as the return type
Implements claims::logical_operator::LogicalOperator.
References claims::logical_operator::LogicalOperator::GetPlanContext().
Referenced by GetPhysicalPlan().
void claims::logical_operator::LogicalProject::Print (int level = 0) const virtual
Method description:Print the schema.
Parameters
level:initialized to zero
Implements claims::logical_operator::LogicalOperator.
The documentation for this class was generated from the following files:
logical_operator/logical_project.h
logical_operator/logical_project.cpp