Claims: Json::Path Class Reference
Json::Path Class Reference
Experimental and untested: represents a "path" to access a node.
#include <json.h>
Public Member Functions
Path (const std::string &path, const PathArgument &a1=PathArgument(), const PathArgument &a2=PathArgument(), const PathArgument &a3=PathArgument(), const PathArgument &a4=PathArgument(), const PathArgument &a5=PathArgument())
const Value & resolve (const Value &root) const
Value resolve (const Value &root, const Value &defaultValue) const
Value & make (Value &root) const
Private Types
typedef std::vector< const
PathArgument * > InArgs
typedef std::vector< PathArgument > Args
Private Member Functions
void makePath (const std::string &path, const InArgs &in)
void addPathInArg (const std::string &path, const InArgs &in, InArgs::const_iterator &itInArg, PathArgument::Kind kind)
void invalidPath (const std::string &path, int location)
Private Attributes
Args args_
Detailed Description
Experimental and untested: represents a "path" to access a node.
Syntax:
"." => root node
".[n]" => elements at index 'n' of root node (an array value)
".name" => member named 'name' of root node (an object value)
".name1.name2.name3"
".[0][1][2].name1[3]"
".%" => member name is provided as parameter
".[%]" => index is provied as parameter
Member Typedef Documentation
typedef std::vector<PathArgument> Json::Path::Args private
typedef std::vector<const PathArgument*> Json::Path::InArgs private
Constructor & Destructor Documentation
Json::Path::Path (const std::string & path, const PathArgument & a1 = PathArgument(), const PathArgument & a2 = PathArgument(), const PathArgument & a3 = PathArgument(), const PathArgument & a4 = PathArgument(), const PathArgument & a5 = PathArgument())
References Json::in(), and makePath().
Member Function Documentation
void Json::Path::addPathInArg (const std::string & path, const InArgs & in, InArgs::const_iterator & itInArg, PathArgument::Kind kind) private
References args_.
Referenced by makePath().
void Json::Path::invalidPath (const std::string & path, int location) private
Referenced by makePath().
Value & Json::Path::make (Value & root) const
Creates the "path" to access the specified node and returns a reference on the node.
References args_, Json::PathArgument::index_, Json::Value::isArray(), Json::Value::isObject(), Json::PathArgument::key_, Json::PathArgument::kind_, Json::PathArgument::kindIndex, and Json::PathArgument::kindKey.
void Json::Path::makePath (const std::string & path, const InArgs & in) private
References addPathInArg(), args_, invalidPath(), Json::PathArgument::kindIndex, and Json::PathArgument::kindKey.
Referenced by Path().
const Value & Json::Path::resolve (const Value & root) const
References args_, Json::PathArgument::index_, Json::Value::isArray(), Json::Value::isObject(), Json::Value::isValidIndex(), Json::PathArgument::key_, Json::PathArgument::kind_, Json::PathArgument::kindIndex, Json::PathArgument::kindKey, and Json::Value::null.
Value Json::Path::resolve (const Value & root, const Value & defaultValue) const
References args_, Json::PathArgument::index_, Json::Value::isArray(), Json::Value::isObject(), Json::Value::isValidIndex(), Json::PathArgument::key_, Json::PathArgument::kind_, Json::PathArgument::kindIndex, Json::PathArgument::kindKey, and Json::Value::null.
Member Data Documentation
Args Json::Path::args_ private
Referenced by addPathInArg(), make(), makePath(), and resolve().
The documentation for this class was generated from the following files:
Client/json/json.h
Client/jsoncpp.cpp