Claims: bottomLayerCollecting Class Reference
bottomLayerCollecting Class Reference
#include <CSBIndexBuilding.h>
Classes
struct remaining_block
class State
Public Member Functions
bottomLayerCollecting ()
bottomLayerCollecting (State state)
virtual ~bottomLayerCollecting ()
bool Open (const PartitionOffset &partition_offset=0)
bool Next (BlockStreamBase *block)
bool Close ()
void Print ()
Public Member Functions inherited from claims::physical_operator::PhysicalOperator
PhysicalOperator (unsigned number_of_barrier=1, unsigned number_of_seriliazed_section=1)
virtual ~PhysicalOperator ()
virtual ThreadContext * CreateContext ()
Public Member Functions inherited from claims::physical_operator::PhysicalOperatorBase
PhysicalOperatorBase ()
virtual ~PhysicalOperatorBase ()
virtual ResultSet * GetResultSet ()
Private Member Functions
void atomicPushRemainingBlock (remaining_block rb)
bool atomicPopRemainingBlock (remaining_block &rb)
void AtomicPushBlockStream (BlockStreamBase *block)
BlockStreamBase * AtomicPopBlockStream ()
bool askForNextBlock (BlockStreamBase *&block, remaining_block &rb)
void computeOutputSchema ()
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
State state_
PartitionStorage::PartitionReaderItetaor * partition_reader_iterator_
ChunkReaderIterator * chunk_reader_iterator_
std::list< remaining_block > remaining_block_list_
std::list< BlockStreamBase * > block_stream_list_
Schema * output_schema_
ChunkOffset chunk_offset_
unsigned short block_offset_
Lock lock_
Friends
class boost::serialization::access
Additional Inherited Members
Public Types inherited from claims::physical_operator::PhysicalOperator
enum context_reuse_mode { crm_no_reuse, crm_core_sensitive, crm_numa_sensitive, crm_anyway }
Static Public Member Functions inherited from claims::physical_operator::PhysicalOperatorBase
static PhysicalOperatorBase * createIterator (const string &IteratorName)
Protected Member Functions inherited from claims::physical_operator::PhysicalOperator
ThreadContext * CreateOrReuseContext (context_reuse_mode crm)
void InitExpandedStatus ()
bool TryEntryIntoSerializedSection (unsigned serialized_section_id=0)
void RegisterExpandedThreadToAllBarriers ()
void UnregisterExpandedThreadToAllBarriers (unsigned barrier_index=0)
void BarrierArrive (unsigned barrier_index=0)
void InitContext (ThreadContext *tc)
ThreadContext * GetContext ()
void DestoryAllContext ()
bool CheckTerminateRequest ()
void SetReturnStatus (bool ret)
bool GetReturnStatus () const
Protected Attributes inherited from claims::physical_operator::PhysicalOperator
unsigned number_of_registered_expanded_threads_
Constructor & Destructor Documentation
bottomLayerCollecting::bottomLayerCollecting ()
References claims::physical_operator::PhysicalOperator::InitExpandedStatus().
bottomLayerCollecting::bottomLayerCollecting (State state)
References claims::physical_operator::PhysicalOperator::InitExpandedStatus().
bottomLayerCollecting::~bottomLayerCollecting () virtual
Member Function Documentation
bool bottomLayerCollecting::askForNextBlock (BlockStreamBase *& block, remaining_block & rb) private
References Lock::acquire(), bottomLayerCollecting::remaining_block::block_offset, block_offset_, bottomLayerCollecting::remaining_block::chunk_offset, chunk_offset_, chunk_reader_iterator_, lock_, ChunkReaderIterator::nextBlock(), PartitionStorage::PartitionReaderItetaor::nextChunk(), partition_reader_iterator_, Lock::release(), and bottomLayerCollecting::remaining_block::tuple_offset.
Referenced by Next().
BlockStreamBase * bottomLayerCollecting::AtomicPopBlockStream () private
References Lock::acquire(), block_stream_list_, lock_, and Lock::release().
Referenced by Next().
bool bottomLayerCollecting::atomicPopRemainingBlock (remaining_block & rb) private
References Lock::acquire(), lock_, Lock::release(), and remaining_block_list_.
Referenced by Next().
void bottomLayerCollecting::AtomicPushBlockStream (BlockStreamBase * block) private
References Lock::acquire(), block_stream_list_, lock_, and Lock::release().
Referenced by Next(), and Open().
void bottomLayerCollecting::atomicPushRemainingBlock (remaining_block rb) private
References Lock::acquire(), lock_, Lock::release(), and remaining_block_list_.
Referenced by Next().
bool bottomLayerCollecting::Close () virtual
Reimplemented from claims::physical_operator::PhysicalOperator.
References block_stream_list_, claims::physical_operator::PhysicalOperator::InitExpandedStatus(), partition_reader_iterator_, and remaining_block_list_.
void bottomLayerCollecting::computeOutputSchema () private
References Schema::getcolumn(), bottomLayerCollecting::State::key_indexing_, output_schema_, bottomLayerCollecting::State::schema_, state_, t_int, and t_u_smallInt.
Referenced by Open().
bool bottomLayerCollecting::Next (BlockStreamBase * block) virtual
Reimplemented from claims::physical_operator::PhysicalOperator.
References BlockStreamBase::allocateTuple(), askForNextBlock(), Operate::assignment(), AtomicPopBlockStream(), atomicPopRemainingBlock(), AtomicPushBlockStream(), atomicPushRemainingBlock(), bottomLayerCollecting::remaining_block::block, bottomLayerCollecting::remaining_block::block_offset, bottomLayerCollecting::remaining_block::chunk_offset, BlockStreamBase::createIterator(), BlockStreamBase::BlockStreamTraverseIterator::currentTuple(), BlockStreamBase::Empty(), Schema::getcolumn(), Schema::getColumnAddess(), Schema::getTupleMaxSize(), BlockStreamBase::BlockStreamTraverseIterator::increase_cur_(), bottomLayerCollecting::remaining_block::iterator, bottomLayerCollecting::State::key_indexing_, column_type::operate, output_schema_, bottomLayerCollecting::State::schema_, BlockStreamBase::setEmpty(), state_, and bottomLayerCollecting::remaining_block::tuple_offset.
bool bottomLayerCollecting::Open (const PartitionOffset & part_off = 0) virtual
Because that boost::serialization will allocate an instance of this class when deserializing, and hence the following three virtual method cannot be pure.
Reimplemented from claims::physical_operator::PhysicalOperator.
References AtomicPushBlockStream(), claims::physical_operator::PhysicalOperator::BarrierArrive(), bottomLayerCollecting::State::block_size_, computeOutputSchema(), PartitionStorage::createAtomicReaderIterator(), BlockStreamBase::createBlockWithDesirableSerilaizedSize(), BlockManager::getInstance(), PartitionID::getName(), claims::physical_operator::PhysicalOperator::GetReturnStatus(), partition_reader_iterator_, bottomLayerCollecting::State::projection_id_, bottomLayerCollecting::State::schema_, claims::physical_operator::PhysicalOperator::SetReturnStatus(), state_, and claims::physical_operator::PhysicalOperator::TryEntryIntoSerializedSection().
void bottomLayerCollecting::Print () inline virtual
Reimplemented from claims::physical_operator::PhysicalOperator.
template<class Archive > void bottomLayerCollecting::serialize (Archive & ar, const unsigned int version) inline private
References state_.
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
unsigned short bottomLayerCollecting::block_offset_ private
Referenced by askForNextBlock().
std::list<BlockStreamBase*> bottomLayerCollecting::block_stream_list_ private
Referenced by AtomicPopBlockStream(), AtomicPushBlockStream(), and Close().
ChunkOffset bottomLayerCollecting::chunk_offset_ private
Referenced by askForNextBlock().
ChunkReaderIterator* bottomLayerCollecting::chunk_reader_iterator_ private
Referenced by askForNextBlock().
Lock bottomLayerCollecting::lock_ private
Referenced by askForNextBlock(), AtomicPopBlockStream(), atomicPopRemainingBlock(), AtomicPushBlockStream(), and atomicPushRemainingBlock().
Schema* bottomLayerCollecting::output_schema_ private
Referenced by computeOutputSchema(), and Next().
PartitionStorage::PartitionReaderItetaor* bottomLayerCollecting::partition_reader_iterator_ private
Referenced by askForNextBlock(), Close(), and Open().
std::list<remaining_block> bottomLayerCollecting::remaining_block_list_ private
Referenced by atomicPopRemainingBlock(), atomicPushRemainingBlock(), and Close().
State bottomLayerCollecting::state_ private
Referenced by computeOutputSchema(), Next(), Open(), and serialize().
The documentation for this class was generated from the following files:
IndexManager/CSBIndexBuilding.h
IndexManager/CSBIndexBuilding.cpp