Claims: OperateInt Class Reference
OperateInt Class Reference
#include <data_type.h>
Public Member Functions
OperateInt (bool _nullable=true)
~OperateInt ()
void assignment (const void *const &src, void *const &desc) const
std::string toString (void *value)
void toValue (void *target, const char *string)
bool equal (const void *const &a, const void *const &b) const
bool less (const void *&a, const void *&b) const
bool greate (const void *&a, const void *&b) const
int compare (const void *a, const void *b) const
void add (void *target, void *increment)
void multiple (void *target, void *increment)
fun GetADDFunction ()
fun GetMINFunction ()
fun GetMAXFunction ()
fun GetIncreateByOneFunction ()
fun GetAVGFunction ()
unsigned getPartitionValue (const void *key, const PartitionFunction *partition_function) const
unsigned getPartitionValue (const void *key) const
unsigned getPartitionValue (const void *key, const unsigned long &mod) const
bool setNull (void *value)
bool isNull (void *value) const
Operate * duplicateOperator () const
Public Member Functions inherited from Operate
Operate (bool _nullable=true)
virtual ~Operate ()
void ass (void *src, void *desc)
Additional Inherited Members
Public Attributes inherited from Operate
void(* assign)(const void *const &src, void *const &desc)
bool nullable
Constructor & Destructor Documentation
OperateInt::OperateInt (bool _nullable = true) inline
OperateInt::~OperateInt () inline
Member Function Documentation
void OperateInt::add (void * target, void * increment) inline virtual
Implements Operate.
void OperateInt::assignment (const void *const & src, void *const & desc) const inline virtual
Implements Operate.
int OperateInt::compare (const void * a, const void * b) const inline virtual
Implements Operate.
Operate* OperateInt::duplicateOperator () const inline virtual
Implements Operate.
bool OperateInt::equal (const void *const & a, const void *const & b) const inline virtual
Implements Operate.
fun OperateInt::GetADDFunction () inline virtual
Implements Operate.
fun OperateInt::GetAVGFunction () inline virtual
Implements Operate.
fun OperateInt::GetIncreateByOneFunction () inline virtual
Implements Operate.
fun OperateInt::GetMAXFunction () inline virtual
Implements Operate.
fun OperateInt::GetMINFunction () inline virtual
Implements Operate.
unsigned OperateInt::getPartitionValue (const void * key, const PartitionFunction * partition_function) const inline virtual
Implements Operate.
References PartitionFunction::get_partition_value().
unsigned OperateInt::getPartitionValue (const void * key) const inline virtual
Implements Operate.
References hash_value().
unsigned OperateInt::getPartitionValue (const void * key, const unsigned long & mod) const inline virtual
Implements Operate.
References hash_value().
bool OperateInt::greate (const void *& a, const void *& b) const inline virtual
Implements Operate.
bool OperateInt::isNull (void * value) const inline virtual
Implements Operate.
References NULL_INT.
bool OperateInt::less (const void *& a, const void *& b) const inline virtual
Implements Operate.
void OperateInt::multiple (void * target, void * increment) inline virtual
Implements Operate.
bool OperateInt::setNull (void * value) inline virtual
Implements Operate.
References NULL_INT.
std::string OperateInt::toString (void * value) inline virtual
Implements Operate.
References NULL_INT.
void OperateInt::toValue (void * target, const char * string) inline virtual
Implements Operate.
References NULL_INT.
The documentation for this class was generated from the following file:
common/data_type.h