Claims: OperateFloat Class Reference
OperateFloat Class Reference
#include <data_type.h>
Public Member Functions
OperateFloat (bool _nullable=true)
~OperateFloat ()
void assignment (const void *const &src, void *const &desc) const
std::string toString (void *value)
void toValue (void *target, const char *string)
bool equal (const void *const &a, const void *const &b) const
bool less (const void *&a, const void *&b) const
bool greate (const void *&a, const void *&b) const
int compare (const void *a, const void *b) const
void add (void *target, void *increment)
void multiple (void *target, void *increment)
fun GetADDFunction ()
fun GetMINFunction ()
fun GetMAXFunction ()
fun GetIncreateByOneFunction ()
fun GetAVGFunction ()
unsigned getPartitionValue (const void *key, const PartitionFunction *partition_function) const
unsigned getPartitionValue (const void *key) const
unsigned getPartitionValue (const void *key, const unsigned long &mod) const
Operate * duplicateOperator () const
bool setNull (void *value)
bool isNull (void *value) const
Public Member Functions inherited from Operate
Operate (bool _nullable=true)
virtual ~Operate ()
void ass (void *src, void *desc)
Additional Inherited Members
Public Attributes inherited from Operate
void(* assign)(const void *const &src, void *const &desc)
bool nullable
Constructor & Destructor Documentation
OperateFloat::OperateFloat (bool _nullable = true) inline
OperateFloat::~OperateFloat () inline
Member Function Documentation
void OperateFloat::add (void * target, void * increment) inline virtual
Implements Operate.
void OperateFloat::assignment (const void *const & src, void *const & desc) const inline virtual
Implements Operate.
int OperateFloat::compare (const void * a, const void * b) const inline virtual
Implements Operate.
Operate* OperateFloat::duplicateOperator () const inline virtual
Implements Operate.
bool OperateFloat::equal (const void *const & a, const void *const & b) const inline virtual
Implements Operate.
fun OperateFloat::GetADDFunction () inline virtual
Implements Operate.
fun OperateFloat::GetAVGFunction () inline virtual
Implements Operate.
fun OperateFloat::GetIncreateByOneFunction () inline virtual
Implements Operate.
fun OperateFloat::GetMAXFunction () inline virtual
Implements Operate.
fun OperateFloat::GetMINFunction () inline virtual
Implements Operate.
unsigned OperateFloat::getPartitionValue (const void * key, const PartitionFunction * partition_function) const inline virtual
Implements Operate.
References PartitionFunction::get_partition_value().
unsigned OperateFloat::getPartitionValue (const void * key) const inline virtual
Implements Operate.
References hash_value().
unsigned OperateFloat::getPartitionValue (const void * key, const unsigned long & mod) const inline virtual
Implements Operate.
References hash_value().
bool OperateFloat::greate (const void *& a, const void *& b) const inline virtual
Implements Operate.
bool OperateFloat::isNull (void * value) const inline virtual
Implements Operate.
References NULL_FLOAT.
bool OperateFloat::less (const void *& a, const void *& b) const inline virtual
Implements Operate.
void OperateFloat::multiple (void * target, void * increment) inline virtual
Implements Operate.
bool OperateFloat::setNull (void * value) inline virtual
Implements Operate.
References NULL_FLOAT.
std::string OperateFloat::toString (void * value) inline virtual
Implements Operate.
References NULL_FLOAT.
void OperateFloat::toValue (void * target, const char * string) inline virtual
Implements Operate.
References NULL_FLOAT.
The documentation for this class was generated from the following file:
common/data_type.h