Claims: semaphore Class Reference
semaphore Class Reference
#include <lock.h>
Public Member Functions
semaphore (int initialValue=0)
void set_value (int value)
void post (int times=1)
void wait ()
bool timed_wait (int millisecond)
bool try_wait ()
void destroy ()
int get_value ()
Private Attributes
sem_t sem
Constructor & Destructor Documentation
semaphore::semaphore (int initialValue = 0) inline
References sem.
Member Function Documentation
void semaphore::destroy () inline
References sem.
Referenced by BlockStreamBuffer::~BlockStreamBuffer(), and claims::physical_operator::PhysicalOperator::~PhysicalOperator().
int semaphore::get_value () inline
References sem.
Referenced by BlockStreamBuffer::BlockStreamBuffer(), PartitionedBlockBuffer::getBlockInBuffer(), CPUResourceManager::socket::getNumberOfFreeCores(), PartitionedBlockBuffer::isEmpty(), and PartitionedBlockBuffer::~PartitionedBlockBuffer().
void semaphore::post (int times = 1) inline
References sem.
Referenced by Daemon::addExecutedResult(), Daemon::addRemoteCommand(), BlockStreamBuffer::BlockStreamBuffer(), claims::physical_operator::InOperator::Close(), claims::physical_operator::ResultCollector::CollectResult(), CPUResourceManager::CPUResourceManager(), CPUResourceManager::freeCore(), BlockStreamBuffer::getBlock(), PartitionedBlockBuffer::getBlock(), PartitionedBlockBuffer::insertBlockToPartitionedList(), and claims::physical_operator::ExchangeMerger::Receiver().
void semaphore::set_value (int value) inline
References sem.
Referenced by claims::physical_operator::ResultCollector::Close(), claims::physical_operator::PhysicalOperator::InitExpandedStatus(), claims::physical_operator::InOperator::InOperator(), PartitionedBlockBuffer::PartitionedBlockBuffer(), claims::physical_operator::ResultCollector::ResultCollector(), and CPUResourceManager::socket::socket().
bool semaphore::timed_wait (int millisecond) inline
References sem.
Referenced by claims::physical_operator::ExchangeMerger::Next().
bool semaphore::try_wait () inline
References sem.
Referenced by claims::physical_operator::ResultCollector::Open(), claims::physical_operator::InOperator::Open(), CPUResourceManager::tryApplyCore(), and claims::physical_operator::PhysicalOperator::TryEntryIntoSerializedSection().
void semaphore::wait () inline
References sem.
Referenced by CPUResourceManager::applyCore(), claims::physical_operator::Expander::CreateWorkingThread(), PartitionedBlockBuffer::getBlock(), Daemon::getExecutedResult(), Daemon::getRemoteCommand(), BlockStreamBuffer::insertBlock(), PartitionedBlockBuffer::insertBlockToPartitionedList(), and claims::physical_operator::ResultCollector::Open().
Member Data Documentation
sem_t semaphore::sem private
Referenced by destroy(), get_value(), post(), semaphore(), set_value(), timed_wait(), try_wait(), and wait().
The documentation for this class was generated from the following file:
utility/lock.h