Claims: IDsGenerator Class Reference
IDsGenerator Class Reference
#include <IDsGenerator.h>
Public Member Functions
virtual ~IDsGenerator ()
unsigned long long int generateUniqueExchangeID ()
ExpanderID getUniqueExpanderID ()
virtual ~IDsGenerator ()
unsigned long long int generateUniqueExchangeID ()
ExpanderID getUniqueExpanderID ()
Static Public Member Functions
static IDsGenerator * getInstance ()
static IDsGenerator * getInstance ()
Private Member Functions
IDsGenerator ()
IDsGenerator ()
Private Attributes
unsigned long long int exchange_id_cursor_
ExpanderID expander_id_cursor_
Lock lock_
Static Private Attributes
static IDsGenerator * instance_ =0
Constructor & Destructor Documentation
IDsGenerator::~IDsGenerator () virtual
IDsGenerator::IDsGenerator () private
References exchange_id_cursor_, and expander_id_cursor_.
Referenced by getInstance().
virtual IDsGenerator::~IDsGenerator () virtual
IDsGenerator::IDsGenerator () private
Member Function Documentation
unsigned long long int IDsGenerator::generateUniqueExchangeID ()
References Lock::acquire(), exchange_id_cursor_, lock_, and Lock::release().
Referenced by claims::logical_operator::LogicalCrossJoin::GenerateChildPhysicalQueryPlan(), claims::logical_operator::LogicalScan::GetOptimalPhysicalPlan(), claims::logical_operator::LogicalFilter::GetOptimalPhysicalPlan(), claims::logical_operator::LogicalQueryPlanRoot::GetOptimalPhysicalPlan(), claims::logical_operator::LogicalQueryPlanRoot::GetPhysicalPlan(), claims::logical_operator::LogicalEqualJoin::GetPhysicalPlan(), claims::logical_operator::LogicalSort::GetPhysicalPlan(), and claims::logical_operator::LogicalAggregation::GetPhysicalPlan().
unsigned long long int IDsGenerator::generateUniqueExchangeID ()
IDsGenerator * IDsGenerator::getInstance () static
References IDsGenerator(), and instance_.
Referenced by claims::logical_operator::LogicalCrossJoin::GenerateChildPhysicalQueryPlan(), claims::logical_operator::LogicalScan::GetOptimalPhysicalPlan(), claims::logical_operator::LogicalFilter::GetOptimalPhysicalPlan(), claims::logical_operator::LogicalQueryPlanRoot::GetOptimalPhysicalPlan(), claims::logical_operator::LogicalQueryPlanRoot::GetPhysicalPlan(), claims::logical_operator::LogicalEqualJoin::GetPhysicalPlan(), claims::logical_operator::LogicalSort::GetPhysicalPlan(), claims::logical_operator::LogicalAggregation::GetPhysicalPlan(), and ExpanderTracker::registerNewExpander().
static IDsGenerator* IDsGenerator::getInstance () static
ExpanderID IDsGenerator::getUniqueExpanderID ()
References Lock::acquire(), expander_id_cursor_, lock_, and Lock::release().
Referenced by ExpanderTracker::registerNewExpander().
ExpanderID IDsGenerator::getUniqueExpanderID ()
Member Data Documentation
unsigned long long int IDsGenerator::exchange_id_cursor_ private
Referenced by generateUniqueExchangeID(), and IDsGenerator().
ExpanderID IDsGenerator::expander_id_cursor_ private
Referenced by getUniqueExpanderID(), and IDsGenerator().
static IDsGenerator * IDsGenerator::instance_ =0 static private
Referenced by getInstance().
Lock IDsGenerator::lock_ private
Referenced by generateUniqueExchangeID(), and getUniqueExpanderID().
The documentation for this class was generated from the following files:
IDsGenerator.h
install/include/IDsGenerator.h
IDsGenerator.cpp