Claims: AttributeStatistics Class Reference
AttributeStatistics Class Reference
#include <AttributeStatistics.h>
Public Member Functions
AttributeStatistics ()
virtual ~AttributeStatistics ()
void setDistinctCardinality (unsigned long int value)
void setHistogram (Histogram *his)
Histogram * getHistogram () const
void print () const
unsigned long getDistinctCardinality () const
Private Attributes
unsigned long distinct_cardinality_
void * max_
void * min_
Histogram * histogram_
Constructor & Destructor Documentation
AttributeStatistics::AttributeStatistics ()
AttributeStatistics::~AttributeStatistics () virtual
Member Function Documentation
unsigned long AttributeStatistics::getDistinctCardinality () const
References distinct_cardinality_.
Referenced by claims::logical_operator::LogicalAggregation::EstimateGroupByCardinality(), and claims::logical_operator::LogicalEqualJoin::PredictEqualJoinSelectivityOnSingleJoinAttributePair().
Histogram * AttributeStatistics::getHistogram () const
References histogram_.
Referenced by Estimation::estEqualJoin(), StatManager::getHistogram(), and claims::logical_operator::LogicalEqualJoin::PredictEqualJoinSelectivityOnSingleJoinAttributePair().
void AttributeStatistics::print () const
References distinct_cardinality_.
Referenced by Analyzer::compute_attribute_stat().
void AttributeStatistics::setDistinctCardinality (unsigned long int value)
References distinct_cardinality_.
Referenced by Analyzer::compute_attribute_stat().
void AttributeStatistics::setHistogram (Histogram * his)
References histogram_.
Referenced by Analyzer::compute_attribute_stat().
Member Data Documentation
unsigned long AttributeStatistics::distinct_cardinality_ private
Referenced by getDistinctCardinality(), print(), and setDistinctCardinality().
Histogram* AttributeStatistics::histogram_ private
Referenced by getHistogram(), and setHistogram().
void* AttributeStatistics::max_ private
void* AttributeStatistics::min_ private
The documentation for this class was generated from the following files:
Catalog/stat/AttributeStatistics.h
Catalog/stat/AttributeStatistics.cpp