Claims: Coordinator Class Reference
Coordinator Class Reference
#include <Coordinator.h>
Classes
class CoordinateActor
Public Member Functions
Coordinator ()
virtual ~Coordinator ()
Private Member Functions
bool PrepareTheSocket ()
bool SetupTheTheron ()
bool CreateListeningThread ()
bool SendReadyNotificationToNewNode (int socket_new_node)
bool SendCoordinatorEndPointPort (int socket_new_node)
Static Private Member Functions
static void * ListeningNewNode (void *arg)
Private Attributes
int socket_fd
Theron::EndPoint * endpoint
Theron::Framework * framework
std::string EndPointPort
std::vector< std::pair
< std::string, std::string > > PeersIpPort
Logging * logging
pthread_t prochaseId
Constructor & Destructor Documentation
Coordinator::Coordinator ()
swap the order of SetupTheTheron and PreparetheSocket to provide more time to Theron::EndPoint initialization before other EndPoints connect to it.
References CreateListeningThread(), Logging::elog(), logging, PrepareTheSocket(), and SetupTheTheron().
Coordinator::~Coordinator () virtual
References endpoint, FileClose(), framework, prochaseId, and socket_fd.
Referenced by main234112234().
Member Function Documentation
bool Coordinator::CreateListeningThread () private
References ListeningNewNode(), Logging::log(), logging, NULL, and prochaseId.
Referenced by Coordinator().
void * Coordinator::ListeningNewNode (void * arg) static private
TODO: In the current version, the Coordinator will repeatedly send message to each NodeConnectionActor until the feedback is received which means the target node has conducted new connection based on message received. However, if the target node is dead, the message will be sent repeatedly and infinitely. Additional code is needed to handle the dead node.
References Logging::elog(), endpoint, FileClose(), framework, NodeConnectionMessage::ip, Logging::log(), logging, PeersIpPort, NodeConnectionMessage::port, SendCoordinatorEndPointPort(), SendReadyNotificationToNewNode(), NodeConnectionMessage::serialize(), socket_fd, TimeOutReceiver::TimeOutWait(), and TimeOutReceiver::~TimeOutReceiver().
Referenced by CreateListeningThread().
bool Coordinator::PrepareTheSocket () private
References Config::config_file, Logging::elog(), Logging::log(), logging, and socket_fd.
Referenced by Coordinator().
bool Coordinator::SendCoordinatorEndPointPort (int socket_new_node) private
References Logging::elog(), EndPointPort, Logging::log(), and logging.
Referenced by ListeningNewNode().
bool Coordinator::SendReadyNotificationToNewNode (int socket_new_node) private
References Logging::log(), and logging.
Referenced by ListeningNewNode().
bool Coordinator::SetupTheTheron () private
References PortManager::applyPort(), endpoint, EndPointPort, framework, PortManager::getInstance(), Environment::getInstance(), Environment::getIp(), Logging::log(), and logging.
Referenced by Coordinator().
Member Data Documentation
Theron::EndPoint* Coordinator::endpoint private
Referenced by ListeningNewNode(), SetupTheTheron(), and ~Coordinator().
std::string Coordinator::EndPointPort private
Referenced by SendCoordinatorEndPointPort(), and SetupTheTheron().
Theron::Framework* Coordinator::framework private
Referenced by ListeningNewNode(), SetupTheTheron(), and ~Coordinator().
Logging* Coordinator::logging private
Referenced by Coordinator(), CreateListeningThread(), ListeningNewNode(), PrepareTheSocket(), SendCoordinatorEndPointPort(), SendReadyNotificationToNewNode(), and SetupTheTheron().
std::vector<std::pair<std::string,std::string> > Coordinator::PeersIpPort private
Referenced by ListeningNewNode().
pthread_t Coordinator::prochaseId private
Referenced by CreateListeningThread(), and ~Coordinator().
int Coordinator::socket_fd private
Referenced by ListeningNewNode(), PrepareTheSocket(), and ~Coordinator().
The documentation for this class was generated from the following files:
Executor/Coordinator.h
Executor/Coordinator.cpp