Claims: InMemoryChunkReaderItetaor Class Reference
InMemoryChunkReaderItetaor Class Reference
#include <ChunkStorage.h>
Public Member Functions
InMemoryChunkReaderItetaor (void *const &start, const unsigned &chunk_size, const unsigned &number_of_blocks, const unsigned &block_size, const ChunkID &chunk_id)
virtual ~InMemoryChunkReaderItetaor ()
bool nextBlock (BlockStreamBase *&block)
bool getNextBlockAccessor (block_accessor *&ba)
Public Member Functions inherited from ChunkReaderIterator
ChunkReaderIterator (const ChunkID &chunk_id, unsigned block_size, unsigned chunk_size, const unsigned &number_of_blocks=0)
bool nextBlock ()
virtual ~ChunkReaderIterator ()
Private Attributes
void * start_
Additional Inherited Members
Public Attributes inherited from ChunkReaderIterator
ChunkID chunk_id_
unsigned number_of_blocks_
unsigned cur_block_
Lock lock_
unsigned block_size_
unsigned chunk_size_
Constructor & Destructor Documentation
InMemoryChunkReaderItetaor::InMemoryChunkReaderItetaor (void *const & start, const unsigned & chunk_size, const unsigned & number_of_blocks, const unsigned & block_size, const ChunkID & chunk_id)
InMemoryChunkReaderItetaor::~InMemoryChunkReaderItetaor () virtual
Member Function Documentation
bool InMemoryChunkReaderItetaor::getNextBlockAccessor (block_accessor *& ba) virtual
Implements ChunkReaderIterator.
References Lock::acquire(), ChunkReaderIterator::block_size_, ChunkReaderIterator::cur_block_, ChunkReaderIterator::lock_, ChunkReaderIterator::number_of_blocks_, Lock::release(), ChunkReaderIterator::block_accessor::setBlockSize(), ChunkReaderIterator::InMemeryBlockAccessor::setTargetBlockStartAddress(), and start_.
bool InMemoryChunkReaderItetaor::nextBlock (BlockStreamBase *& block) virtual
Implements ChunkReaderIterator.
References Lock::acquire(), ChunkReaderIterator::block_size_, BlockStreamBase::constructFromBlock(), ChunkReaderIterator::cur_block_, ChunkReaderIterator::lock_, ChunkReaderIterator::number_of_blocks_, Lock::release(), and start_.
Member Data Documentation
void* InMemoryChunkReaderItetaor::start_ private
Referenced by getNextBlockAccessor(), and nextBlock().
The documentation for this class was generated from the following files:
storage/ChunkStorage.h
storage/ChunkStorage.cpp