Claims: AdaptiveEndPoint Class Reference
AdaptiveEndPoint Class Reference
#include <AdaptiveEndPoint.h>
Inherits EndPoint.
Classes
class ConnectionActor
Public Member Functions
AdaptiveEndPoint (const char *name, std::string ip, std::string port)
virtual ~AdaptiveEndPoint ()
Protected Attributes
Theron::Framework * framework
Logging * logging_
Private Member Functions
bool SayHelloToCoordinator (std::string ip, std::string port)
int GetCoordinatorEndPointPort ()
bool WaitForReadySignalFromCoordinator ()
bool ConnectToCoordinateEndPoint (int port)
bool ConnectToRemoteEndPoint (std::string location)
Private Attributes
Theron::Actor * connectionActor
int socket_coor
std::string ip_coor
Friends
class ConnectionActor
Constructor & Destructor Documentation
AdaptiveEndPoint::AdaptiveEndPoint (const char * name, std::string ip, std::string port)
References connectionActor, ConnectionActor, ConnectToCoordinateEndPoint(), Logging::elog(), FileClose(), framework, GetCoordinatorEndPointPort(), Logging::log(), logging_, SayHelloToCoordinator(), socket_coor, and WaitForReadySignalFromCoordinator().
AdaptiveEndPoint::~AdaptiveEndPoint () virtual
References connectionActor, and framework.
Member Function Documentation
bool AdaptiveEndPoint::ConnectToCoordinateEndPoint (int port) private
References ConnectToRemoteEndPoint(), Logging::elog(), ip_coor, Logging::log(), and logging_.
Referenced by AdaptiveEndPoint().
bool AdaptiveEndPoint::ConnectToRemoteEndPoint (std::string location) private
Referenced by ConnectToCoordinateEndPoint().
int AdaptiveEndPoint::GetCoordinatorEndPointPort () private
References Logging::elog(), ip_coor, Logging::log(), logging_, and socket_coor.
Referenced by AdaptiveEndPoint().
bool AdaptiveEndPoint::SayHelloToCoordinator (std::string ip, std::string port) private
References Config::config_file, Logging::elog(), ThreadSafe::gethostbyname_ts(), ip_coor, logging_, and socket_coor.
Referenced by AdaptiveEndPoint().
bool AdaptiveEndPoint::WaitForReadySignalFromCoordinator () private
References Logging::elog(), Logging::log(), logging_, and socket_coor.
Referenced by AdaptiveEndPoint().
Friends And Related Function Documentation
friend class ConnectionActor friend
The Actor which receive the node states from the coordinator
Referenced by AdaptiveEndPoint().
Member Data Documentation
Theron::Actor* AdaptiveEndPoint::connectionActor private
Referenced by AdaptiveEndPoint(), and ~AdaptiveEndPoint().
Theron::Framework* AdaptiveEndPoint::framework protected
Referenced by AdaptiveEndPoint(), and ~AdaptiveEndPoint().
std::string AdaptiveEndPoint::ip_coor private
Referenced by ConnectToCoordinateEndPoint(), GetCoordinatorEndPointPort(), and SayHelloToCoordinator().
Logging* AdaptiveEndPoint::logging_ protected
Referenced by AdaptiveEndPoint(), ConnectToCoordinateEndPoint(), GetCoordinatorEndPointPort(), SayHelloToCoordinator(), and WaitForReadySignalFromCoordinator().
int AdaptiveEndPoint::socket_coor private
Referenced by AdaptiveEndPoint(), GetCoordinatorEndPointPort(), SayHelloToCoordinator(), and WaitForReadySignalFromCoordinator().
The documentation for this class was generated from the following files:
Executor/AdaptiveEndPoint.h
Executor/AdaptiveEndPoint.cpp