Claims: DynamicBlockBuffer Class Reference
DynamicBlockBuffer Class Reference
#include <DynamicBlockBuffer.h>
Classes
class Iterator
Public Member Functions
DynamicBlockBuffer ()
DynamicBlockBuffer (const DynamicBlockBuffer &r)
virtual ~DynamicBlockBuffer ()
bool appendNewBlock (BlockStreamBase *new_block)
bool atomicAppendNewBlock (BlockStreamBase *new_block)
BlockStreamBase * getBlock (unsigned index) const
Iterator createIterator () const
unsigned getNumberOfBlocks ()
void destory ()
unsigned long getNumberOftuples () const
Private Attributes
std::vector< BlockStreamBase * > block_list_
Lock lock_
Detailed Description
A container which buffers serialized blocks. The number of blocks in the buffer is not known when constructing and is growing dynamically on the fly.
Constructor & Destructor Documentation
DynamicBlockBuffer::DynamicBlockBuffer ()
DynamicBlockBuffer::DynamicBlockBuffer (const DynamicBlockBuffer & r)
References block_list_, and lock_.
DynamicBlockBuffer::~DynamicBlockBuffer () virtual
References block_list_.
Referenced by TEST().
Member Function Documentation
bool DynamicBlockBuffer::appendNewBlock (BlockStreamBase * new_block)
References block_list_.
Referenced by atomicAppendNewBlock(), Client::submit(), and testServerClient().
bool DynamicBlockBuffer::atomicAppendNewBlock (BlockStreamBase * new_block)
References Lock::acquire(), appendNewBlock(), lock_, and Lock::release().
Referenced by claims::physical_operator::ResultCollector::CollectResult(), claims::physical_operator::PhysicalNestLoopJoin::Open(), and claims::physical_operator::PhysicalSort::Open().
DynamicBlockBuffer::Iterator DynamicBlockBuffer::createIterator () const
Referenced by Analyzer::analyse(), Analyzer::compute_table_stat(), Analyzer::computeHistogram(), destory(), fill_insert_optimized_hash_table(), filter_test(), Analyzer::getDistinctCardinality(), getNumberOftuples(), claims::physical_operator::ResultCollector::GetNumberOftuples(), claims::physical_operator::PhysicalNestLoopJoin::Next(), claims::physical_operator::ResultCollector::Open(), ResultSet::print(), query_2(), ClientListener::sendHandler(), ClientListener::sendJsonPacket(), TEST(), TEST_F(), test_multiple_scan_filter_Scalar_Aggregation(), and test_scan_filter_Scalar_Aggregation().
void DynamicBlockBuffer::destory ()
References block_list_, createIterator(), and DynamicBlockBuffer::Iterator::nextBlock().
Referenced by Analyzer::analyse(), Analyzer::compute_table_stat(), Analyzer::computeHistogram(), and Analyzer::getDistinctCardinality().
BlockStreamBase * DynamicBlockBuffer::getBlock (unsigned index) const
References block_list_.
unsigned DynamicBlockBuffer::getNumberOfBlocks ()
References Lock::acquire(), block_list_, lock_, and Lock::release().
unsigned long DynamicBlockBuffer::getNumberOftuples () const
References createIterator(), BlockStreamBase::getTuplesInBlock(), and DynamicBlockBuffer::Iterator::nextBlock().
Referenced by Analyzer::analyse(), bulk_test_logical_index_scan(), Analyzer::computeHistogram(), lineitem_scan_aggregation(), ResultSet::print(), sb_scan_aggregation(), TEST(), test_complete_repartition_filtered_join(), test_complete_repartition_scan_join(), TEST_F(), test_multiple_complete_repartition_filtered_join(), test_multiple_complete_repartition_scan_join(), test_multiple_no_repartition_filtered_join(), test_multiple_no_repartition_scan_join(), test_no_repartition_filtered_join(), test_no_repartition_scan_join(), test_scan_Aggregation_large_Groups(), and test_scan_Aggregation_small_Groups().
Member Data Documentation
std::vector<BlockStreamBase*> DynamicBlockBuffer::block_list_ private
Referenced by appendNewBlock(), destory(), DynamicBlockBuffer(), getBlock(), getNumberOfBlocks(), and ~DynamicBlockBuffer().
Lock DynamicBlockBuffer::lock_ private
Referenced by atomicAppendNewBlock(), DynamicBlockBuffer::Iterator::atomicNextBlock(), DynamicBlockBuffer(), getNumberOfBlocks(), and DynamicBlockBuffer::Iterator::Iterator().
The documentation for this class was generated from the following files:
common/Block/DynamicBlockBuffer.h
common/Block/DynamicBlockBuffer.cpp