Claims: BlockStreamBase Class Reference
BlockStreamBase Class Reference abstract
#include <BlockStream.h>
Classes
class BlockStreamTraverseIterator
Public Member Functions
BlockStreamBase (unsigned block_size)
BlockStreamBase (unsigned block_size, void *start_addr)
virtual BlockStreamBase * createBlockAndDeepCopy ()=0
virtual ~BlockStreamBase ()
virtual void * allocateTuple (unsigned bytes)=0
virtual void setEmpty ()=0
virtual bool Empty () const =0
virtual bool Full () const =0
virtual void * getBlockDataAddress ()=0
virtual unsigned getTuplesInBlock () const =0
virtual unsigned getBlockCapacityInTuples () const =0
virtual void copyBlock (void *addr, unsigned length)=0
virtual bool insert (void *dest, void *src, unsigned bytes)=0
virtual void deepCopy (const Block *block)=0
virtual void constructFromBlock (const Block &block)=0
virtual bool switchBlock (BlockStreamBase &block)=0
virtual bool serialize (Block &block) const =0
virtual bool deserialize (Block *block)=0
virtual unsigned getSerializedBlockSize () const =0
BlockStreamTraverseIterator * createIterator ()
Public Member Functions inherited from Block
Block (unsigned BlockSize)
Block (const Block &block)
Block (const unsigned &size, const void *start)
virtual ~Block ()
void * getBlock () const
void setBlock (void *)
unsigned getsize () const
unsigned setsize (const unsigned &size)
bool isIsReference () const
void setIsReference (bool isReference)
Static Public Member Functions
static BlockStreamBase * createBlock (const Schema *const &schema, unsigned block_size)
static BlockStreamBase * createBlockWithDesirableSerilaizedSize (Schema *schema, unsigned block_size)
Protected Member Functions
virtual void * getTuple (unsigned offset) const =0
Friends
class BlockStreamTraverseIterator
Additional Inherited Members
Protected Attributes inherited from Block
unsigned BlockSize
char * start
Constructor & Destructor Documentation
BlockStreamBase::BlockStreamBase (unsigned block_size) inline
BlockStreamBase::BlockStreamBase (unsigned block_size, void * start_addr) inline
virtual BlockStreamBase::~BlockStreamBase () inline virtual
Referenced by claims::physical_operator::PerformanceMonitor::Close(), claims::physical_operator::ResultPrinter::Close(), claims::physical_operator::PhysicalLimit::Close(), and claims::physical_operator::ResultCollector::DeallocateBlockStream().
Member Function Documentation
virtual void* BlockStreamBase::allocateTuple (unsigned bytes) pure virtual
Implemented in BlockStreamVar, and BlockStreamFix.
Referenced by generate_BlockStreamBuffer(), generateBlockStreamBuffer(), generateVariableData_test(), initial_input_date(), mainasfasdf22(), bottomLayerCollecting::Next(), claims::physical_operator::PhysicalLimit::Next(), claims::physical_operator::CombineTuple::Next(), claims::physical_operator::PhysicalNestLoopJoin::Next(), claims::physical_operator::PhysicalAggregation::Next(), claims::physical_operator::InOperator::Next(), claims::physical_operator::PhysicalSort::Next(), IndexScanIterator::Next(), claims::physical_operator::PhysicalHashJoin::Next(), claims::physical_operator::PhysicalFilter::ProcessInLogic(), and claims::physical_operator::PhysicalProject::ProcessInLogic().
virtual void BlockStreamBase::constructFromBlock (const Block & block) pure virtual
Implemented in BlockStreamVar, and BlockStreamFix.
Referenced by ChunkReaderIterator::InMemeryBlockAccessor::getBlock(), InMemoryChunkReaderItetaor::nextBlock(), DiskChunkReaderIteraror::nextBlock(), and HDFSChunkReaderIterator::nextBlock().
virtual void BlockStreamBase::copyBlock (void * addr, unsigned length) pure virtual
Implemented in BlockStreamVar, and BlockStreamFix.
BlockStreamBase * BlockStreamBase::createBlock (const Schema *const & schema, unsigned block_size) static
References Schema::fixed, Schema::getSchemaType(), and Schema::getTupleMaxSize().
Referenced by BlockStreamBuffer::BlockStreamBuffer(), claims::physical_operator::PhysicalSort::CreateBlock(), claims::physical_operator::ResultCollector::CreateBlockStream(), claims::physical_operator::PhysicalNestLoopJoin::CreateBlockStream(), claims::physical_operator::PhysicalFilter::CreateContext(), claims::physical_operator::PhysicalHashJoin::CreateContext(), claims::physical_operator::PhysicalProject::CreateContext(), claims::physical_operator::Expander::ExpandedWork(), ClientResponse::getDataBlock(), HdfsLoader::HdfsLoader(), claims::physical_operator::PerformanceMonitor::Open(), claims::physical_operator::ResultPrinter::Open(), claims::physical_operator::PhysicalLimit::Open(), claims::physical_operator::ExchangeSenderMaterialized::Open(), claims::physical_operator::InOperator::Open(), claims::physical_operator::ExchangeSenderPipeline::Open(), claims::physical_operator::PhysicalAggregation::Open(), claims::physical_operator::ExchangeMerger::Open(), bottomLayerSorting::Open(), and test_block_construct().
virtual BlockStreamBase* BlockStreamBase::createBlockAndDeepCopy () pure virtual
Implemented in BlockStreamVar, and BlockStreamFix.
Referenced by InsertOptimizedHashTable::insertBlock().
BlockStreamBase * BlockStreamBase::createBlockWithDesirableSerilaizedSize (Schema * schema, unsigned block_size) static
:I add this function in order to end the chaos of setting the block size when initializing the BlockStream. -_-
References Schema::fixed, Schema::getSchemaType(), and Schema::getTupleMaxSize().
Referenced by generate_BlockStreamBuffer(), generateBlockStreamBuffer(), initial_input_date(), insert_into_hash_table(), insert_into_hash_table_from_projection(), bottomLayerCollecting::Open(), IndexScanIterator::Open(), and projection_scan().
BlockStreamTraverseIterator* BlockStreamBase::createIterator () inline
Referenced by Analyzer::analyse(), Analyzer::compute_table_stat(), Analyzer::computeHistogram(), claims::physical_operator::PhysicalFilter::CreateContext(), claims::physical_operator::PhysicalHashJoin::CreateContext(), claims::physical_operator::PhysicalProject::CreateContext(), filter_test(), Analyzer::getDistinctCardinality(), insert_into_hash_table(), insert_into_hash_table_from_projection(), insert_into_insert_optimized_hash_table(), mainasfasdf22(), claims::physical_operator::PerformanceMonitor::Next(), claims::physical_operator::ResultPrinter::Next(), bottomLayerCollecting::Next(), claims::physical_operator::PhysicalLimit::Next(), claims::physical_operator::ExchangeSenderMaterialized::Next(), claims::physical_operator::PhysicalNestLoopJoin::Next(), claims::physical_operator::InOperator::Next(), claims::physical_operator::ExchangeSenderPipeline::Next(), IndexScanIterator::Next(), claims::physical_operator::PhysicalFilter::Next(), claims::physical_operator::PhysicalHashJoin::Next(), claims::physical_operator::PhysicalProject::Next(), claims::physical_operator::PhysicalNestLoopJoin::Open(), claims::physical_operator::InOperator::Open(), claims::physical_operator::PhysicalAggregation::Open(), claims::physical_operator::PhysicalSort::Open(), claims::physical_operator::PhysicalHashJoin::Open(), bottomLayerSorting::Open(), ResultSet::print(), query_2(), ClientListener::sendJsonPacket(), TEST(), TEST_F(), test_multiple_scan_filter_Scalar_Aggregation(), and test_scan_filter_Scalar_Aggregation().
virtual void BlockStreamBase::deepCopy (const Block * block) pure virtual
deep copy from block, including block content and member variables that maintain the block status. the user should guarantee that rest block and desc block are of equal derived class type(e.g., both are BlockStreamFix), otherwise the copy may be incomplete.
Implemented in BlockStreamVar, and BlockStreamFix.
Referenced by BlockStreamFix::createBlockAndDeepCopy(), and BlockStreamBuffer::insertBlock().
virtual bool BlockStreamBase::deserialize (Block * block) pure virtual
Implemented in BlockStreamVar, and BlockStreamFix.
Referenced by claims::physical_operator::ExchangeMerger::Receiver().
virtual bool BlockStreamBase::Empty () const pure virtual
Implemented in BlockStreamVar, and BlockStreamFix.
Referenced by claims::physical_operator::Expander::ExpandedWork(), bottomLayerCollecting::Next(), claims::physical_operator::PhysicalLimit::Next(), claims::physical_operator::CombineTuple::Next(), claims::physical_operator::PhysicalNestLoopJoin::Next(), claims::physical_operator::PhysicalAggregation::Next(), claims::physical_operator::InOperator::Next(), IndexScanIterator::Next(), claims::physical_operator::PhysicalFilter::Next(), claims::physical_operator::PhysicalHashJoin::Next(), claims::physical_operator::PhysicalProject::Next(), and claims::physical_operator::ExchangeMerger::Receiver().
virtual bool BlockStreamBase::Full () const pure virtual
Implemented in BlockStreamVar, and BlockStreamFix.
Referenced by claims::physical_operator::PhysicalFilter::Next(), and claims::physical_operator::PhysicalProject::Next().
virtual unsigned BlockStreamBase::getBlockCapacityInTuples () const pure virtual
Implemented in BlockStreamVar, and BlockStreamFix.
Referenced by claims::physical_operator::PhysicalFilter::ProcessInLogic().
virtual void* BlockStreamBase::getBlockDataAddress () pure virtual
Implemented in BlockStreamVar, and BlockStreamFix.
virtual unsigned BlockStreamBase::getSerializedBlockSize () const pure virtual
Implemented in BlockStreamVar, and BlockStreamFix.
Referenced by ChunkReaderIterator::InMemeryBlockAccessor::getBlock(), claims::physical_operator::ExchangeSenderMaterialized::Materialize(), claims::physical_operator::ExchangeSenderMaterialized::Open(), claims::physical_operator::ExchangeSenderPipeline::Open(), and claims::physical_operator::ExchangeMerger::Open().
virtual void* BlockStreamBase::getTuple (unsigned offset) const protected pure virtual
Implemented in BlockStreamVar, and BlockStreamFix.
virtual unsigned BlockStreamBase::getTuplesInBlock () const pure virtual
Implemented in BlockStreamVar, and BlockStreamFix.
Referenced by claims::physical_operator::Expander::ExpandedWork(), DynamicBlockBuffer::getNumberOftuples(), claims::physical_operator::ResultCollector::GetNumberOftuples(), claims::physical_operator::PerformanceMonitor::Next(), and claims::physical_operator::PhysicalFilter::ProcessInLogic().
virtual bool BlockStreamBase::insert (void * dest, void * src, unsigned bytes) pure virtual
Implemented in BlockStreamVar, and BlockStreamFix.
Referenced by claims::physical_operator::PhysicalFilter::ProcessInLogic().
virtual bool BlockStreamBase::serialize (Block & block) const pure virtual
Implemented in BlockStreamVar, and BlockStreamFix.
Referenced by generateVariableData_test(), claims::physical_operator::ExchangeSenderMaterialized::Next(), claims::physical_operator::ExchangeSenderPipeline::Next(), and ClientListener::sendHandler().
virtual void BlockStreamBase::setEmpty () pure virtual
Implemented in BlockStreamVar, and BlockStreamFix.
Referenced by claims::physical_operator::Expander::ExpandedWork(), generate_BlockStreamBuffer(), generateBlockStreamBuffer(), initial_input_date(), mainasdfaf234(), claims::physical_operator::PerformanceMonitor::Next(), claims::physical_operator::ResultPrinter::Next(), bottomLayerCollecting::Next(), claims::physical_operator::ExchangeSenderMaterialized::Next(), claims::physical_operator::PhysicalNestLoopJoin::Next(), claims::physical_operator::InOperator::Next(), claims::physical_operator::ExchangeSenderPipeline::Next(), IndexScanIterator::Next(), claims::physical_operator::PhysicalFilter::Next(), claims::physical_operator::PhysicalHashJoin::Next(), claims::physical_operator::PhysicalProject::Next(), claims::physical_operator::PhysicalAggregation::Open(), claims::physical_operator::InOperator::Open(), claims::physical_operator::PhysicalHashJoin::Open(), bottomLayerSorting::Open(), claims::physical_operator::PhysicalFilter::ProcessInLogic(), and claims::physical_operator::PhysicalProject::ProcessInLogic().
virtual bool BlockStreamBase::switchBlock (BlockStreamBase & block) pure virtual
Implemented in BlockStreamVar, and BlockStreamFix.
Referenced by BlockStreamBuffer::getBlock(), and BlockStreamBuffer::insertBlock().
Friends And Related Function Documentation
friend class BlockStreamTraverseIterator friend
The documentation for this class was generated from the following files:
common/Block/BlockStream.h
common/Block/BlockStream.cpp