Claims: ChunkReaderIterator::block_accessor Class Reference
ChunkReaderIterator::block_accessor Class Reference
#include <ChunkStorage.h>
Public Member Functions
block_accessor ()
~block_accessor ()
virtual void getBlock (BlockStreamBase *&block) const
unsigned getBlockSize () const
void setBlockSize (unsigned blockSize)
Protected Attributes
unsigned block_size
Detailed Description
This structure maintains all the information needed to access a block in in-memory chunk, in-disk chunk, or in-hdfs chunk.
The underlying reason for using this structure is to.
Constructor & Destructor Documentation
ChunkReaderIterator::block_accessor::block_accessor () inline
ChunkReaderIterator::block_accessor::~block_accessor () inline
Member Function Documentation
virtual void ChunkReaderIterator::block_accessor::getBlock (BlockStreamBase *& block) const inline virtual
Reimplemented in ChunkReaderIterator::InHDFSBlockAccessor, ChunkReaderIterator::InDiskBlockAccessor, and ChunkReaderIterator::InMemeryBlockAccessor.
Referenced by claims::physical_operator::PhysicalProjectionScan::Next(), and PartitionStorage::AtomicPartitionReaderIterator::nextBlock().
unsigned ChunkReaderIterator::block_accessor::getBlockSize () const inline
References block_size.
Referenced by claims::physical_operator::PhysicalProjectionScan::Open().
void ChunkReaderIterator::block_accessor::setBlockSize (unsigned blockSize) inline
References block_size.
Referenced by InMemoryChunkReaderItetaor::getNextBlockAccessor(), DiskChunkReaderIteraror::getNextBlockAccessor(), and HDFSChunkReaderIterator::getNextBlockAccessor().
Member Data Documentation
unsigned ChunkReaderIterator::block_accessor::block_size protected
Referenced by ChunkReaderIterator::InMemeryBlockAccessor::getBlock(), getBlockSize(), and setBlockSize().
The documentation for this class was generated from the following file:
storage/ChunkStorage.h