Claims: LogicalCSBIndexBuilding Class Reference
LogicalCSBIndexBuilding Class Reference
#include <LogicalCSBIndexBuilding.h>
Public Member Functions
LogicalCSBIndexBuilding (ProjectionID projection_id, Attribute index_attr, std::string index_name)
virtual ~LogicalCSBIndexBuilding ()
PlanContext GetPlanContext ()
PhysicalOperatorBase * GetPhysicalPlan (const unsigned &)
bool GetOptimalPhysicalPlan (Requirement requirement, PhysicalPlanDescriptor &physical_plan_descriptor, const unsigned &block_size=4096 *1024)
Public Member Functions inherited from claims::logical_operator::LogicalOperator
LogicalOperator ()
LogicalOperator (OperatorType operator_type)
virtual ~LogicalOperator ()
Private Member Functions
void Print (int level=0) const
Private Attributes
ProjectionID projection_id_
Attribute index_attr_
std::string index_name_
ProjectionDescriptor * scan_projection_
PlanContext blc_dataflow_
PlanContext bls_dataflow_
Additional Inherited Members
Protected Member Functions inherited from claims::logical_operator::LogicalOperator
Schema * GetSchema (const std::vector< Attribute > &) const
Schema * GetSchema (const std::vector< Attribute > &, const std::vector< Attribute > &) const
std::vector< NodeID > GetInvolvedNodeID (const PlanPartitioner &) const
std::vector< NodeIP > ConvertNodeIDListToNodeIPList (const std::vector< NodeID > &) const
PhysicalPlanDescriptor GetBestPhysicalPlanDescriptor (const std::vector< PhysicalPlanDescriptor >) const
int GetIdInAttributeList (const std::vector< Attribute > &attributes, const Attribute &attribute) const
void set_operator_type (OperatorType operator_type)
Protected Attributes inherited from claims::logical_operator::LogicalOperator
Lock * lock_
Constructor & Destructor Documentation
LogicalCSBIndexBuilding::LogicalCSBIndexBuilding (ProjectionID projection_id, Attribute index_attr, std::string index_name)
References Catalog::getInstance(), TableDescriptor::getProjectoin(), Catalog::getTable(), index_attr_, projection_id_, ProjectionID::projection_off, scan_projection_, and Attribute::table_id_.
LogicalCSBIndexBuilding::~LogicalCSBIndexBuilding () virtual
Member Function Documentation
bool LogicalCSBIndexBuilding::GetOptimalPhysicalPlan (Requirement requirement, PhysicalPlanDescriptor & physical_plan_descriptor, const unsigned & block_size = 4096 * 1024) virtual
get the optimal Physical plan that meets the requirement.
Returns
true if find physical plan that meets the requirement and store the physical plan and its corresponding information in physical_plan_descriptor.
Reimplemented from claims::logical_operator::LogicalOperator.
PhysicalOperatorBase * LogicalCSBIndexBuilding::GetPhysicalPlan (const unsigned &) virtual
generate the iterator tree based on the computed plan_context. Hence, this function can only be called after the calling of GetPlanContext().
Implements claims::logical_operator::LogicalOperator.
References claims::logical_operator::PlanContext::attribute_list_, blc_dataflow_, block_size, bottomLayerCollecting::State::block_size_, bottomLayerSorting::State::block_size_, bottomLayerSorting::State::child_, Schema::getcolumn(), claims::logical_operator::LogicalOperator::GetSchema(), index_attr_, index_name_, bottomLayerSorting::State::index_name_, bottomLayerCollecting::State::key_indexing_, bottomLayerSorting::State::key_indexing_, projection_id_, bottomLayerCollecting::State::projection_id_, bottomLayerSorting::State::projection_id_, bottomLayerCollecting::State::schema_, bottomLayerSorting::State::schema_, t_int, and t_u_smallInt.
PlanContext LogicalCSBIndexBuilding::GetPlanContext () virtual
get the plan context which describes the property of the data after having executed corresponding operator.
Implements claims::logical_operator::LogicalOperator.
References ProjectionDescriptor::AllPartitionBound(), claims::logical_operator::PlanContext::attribute_list_, ProjectionBinding::BindingEntireProjection(), blc_dataflow_, claims::logical_operator::PlanContext::commu_cost_, DESIRIABLE_STORAGE_LEVEL, ProjectionDescriptor::getAttributeList(), Catalog::getBindingModele(), Catalog::getInstance(), ProjectionDescriptor::getPartitioner(), claims::logical_operator::PlanContext::plan_partitioner_, and scan_projection_.
void LogicalCSBIndexBuilding::Print (int level = 0) const private virtual
Implements claims::logical_operator::LogicalOperator.
References Catalog::getInstance(), ProjectionDescriptor::getProjectionID(), scan_projection_, and ProjectionID::table_id.
Member Data Documentation
PlanContext LogicalCSBIndexBuilding::blc_dataflow_ private
Referenced by GetPhysicalPlan(), and GetPlanContext().
PlanContext LogicalCSBIndexBuilding::bls_dataflow_ private
Attribute LogicalCSBIndexBuilding::index_attr_ private
Referenced by GetPhysicalPlan(), and LogicalCSBIndexBuilding().
std::string LogicalCSBIndexBuilding::index_name_ private
Referenced by GetPhysicalPlan().
ProjectionID LogicalCSBIndexBuilding::projection_id_ private
Referenced by GetPhysicalPlan(), and LogicalCSBIndexBuilding().
ProjectionDescriptor* LogicalCSBIndexBuilding::scan_projection_ private
Referenced by GetPlanContext(), LogicalCSBIndexBuilding(), and Print().
The documentation for this class was generated from the following files:
IndexManager/LogicalCSBIndexBuilding.h
IndexManager/LogicalCSBIndexBuilding.cpp