Claims: Json::Value Class Reference
Json::Value Class Reference
Represents a JSON value.
#include <json.h>
Classes
struct CommentInfo
class CZString
union ValueHolder
Public Types
typedef std::vector< std::string > Members
typedef ValueIterator iterator
typedef ValueConstIterator const_iterator
typedef Json::UInt UInt
typedef Json::Int Int
typedef Json::UInt64 UInt64
typedef Json::Int64 Int64
typedef Json::LargestInt LargestInt
typedef Json::LargestUInt LargestUInt
typedef Json::ArrayIndex ArrayIndex
typedef std::map< CZString, Value > ObjectValues
Public Member Functions
Value (ValueType type=nullValue)
Create a default Value of the given type.
Value (Int value)
Value (UInt value)
Value (Int64 value)
Value (UInt64 value)
Value (double value)
Value (const char *value)
Value (const char *beginValue, const char *endValue)
Value (const StaticString &value)
Constructs a value from a static string.
Value (const std::string &value)
Value (bool value)
Value (const Value &other)
~Value ()
Value & operator= (Value other)
void swap (Value &other)
ValueType type () const
bool operator< (const Value &other) const
bool operator<= (const Value &other) const
bool operator>= (const Value &other) const
bool operator> (const Value &other) const
bool operator== (const Value &other) const
bool operator!= (const Value &other) const
int compare (const Value &other) const
const char * asCString () const
std::string asString () const
Int asInt () const
UInt asUInt () const
Int64 asInt64 () const
UInt64 asUInt64 () const
LargestInt asLargestInt () const
LargestUInt asLargestUInt () const
float asFloat () const
double asDouble () const
bool asBool () const
bool isNull () const
bool isBool () const
bool isInt () const
bool isInt64 () const
bool isUInt () const
bool isUInt64 () const
bool isIntegral () const
bool isDouble () const
bool isNumeric () const
bool isString () const
bool isArray () const
bool isObject () const
bool isConvertibleTo (ValueType other) const
ArrayIndex size () const
Number of values in array or object.
bool empty () const
Return true if empty array, empty object, or null; otherwise, false.
bool operator! () const
Return isNull()
void clear ()
void resize (ArrayIndex size)
Value & operator[] (ArrayIndex index)
Value & operator[] (int index)
const Value & operator[] (ArrayIndex index) const
const Value & operator[] (int index) const
Value get (ArrayIndex index, const Value &defaultValue) const
bool isValidIndex (ArrayIndex index) const
Return true if index < size().
Value & append (const Value &value)
Append value to array at the end.
Value & operator[] (const char *key)
Access an object value by name, create a null member if it does not exist.
const Value & operator[] (const char *key) const
Value & operator[] (const std::string &key)
Access an object value by name, create a null member if it does not exist.
const Value & operator[] (const std::string &key) const
Value & operator[] (const StaticString &key)
Access an object value by name, create a null member if it does not exist.
Value get (const char *key, const Value &defaultValue) const
Return the member named key if it exist, defaultValue otherwise.
Value get (const std::string &key, const Value &defaultValue) const
Return the member named key if it exist, defaultValue otherwise.
Value removeMember (const char *key)
Remove and return the named member.
Value removeMember (const std::string &key)
Same as removeMember(const char*)
bool isMember (const char *key) const
Return true if the object has a member named key.
bool isMember (const std::string &key) const
Return true if the object has a member named key.
Members getMemberNames () const
Return a list of the member names.
void setComment (const char *comment, CommentPlacement placement)
Comments must be //... or /* ... */.
void setComment (const std::string &comment, CommentPlacement placement)
Comments must be //... or /* ... */.
bool hasComment (CommentPlacement placement) const
std::string getComment (CommentPlacement placement) const
Include delimiters and embedded newlines.
std::string toStyledString () const
const_iterator begin () const
const_iterator end () const
iterator begin ()
iterator end ()
void setOffsetStart (size_t start)
void setOffsetLimit (size_t limit)
size_t getOffsetStart () const
size_t getOffsetLimit () const
Static Public Attributes
static const Value & null = reinterpret_cast<const Value&>(kNullRef)
static const LargestInt minLargestInt = LargestInt(~(LargestUInt(-1) / 2))
Minimum signed integer value that can be stored in a Json::Value.
static const LargestInt maxLargestInt = LargestInt(LargestUInt(-1) / 2)
Maximum signed integer value that can be stored in a Json::Value.
static const LargestUInt maxLargestUInt = LargestUInt(-1)
Maximum unsigned integer value that can be stored in a Json::Value.
static const Int minInt = Int(~(UInt(-1) / 2))
Minimum signed int value that can be stored in a Json::Value.
static const Int maxInt = Int(UInt(-1) / 2)
Maximum signed int value that can be stored in a Json::Value.
static const UInt maxUInt = UInt(-1)
Maximum unsigned int value that can be stored in a Json::Value.
static const Int64 minInt64 = Int64(~(UInt64(-1) / 2))
Minimum signed 64 bits int value that can be stored in a Json::Value.
static const Int64 maxInt64 = Int64(UInt64(-1) / 2)
Maximum signed 64 bits int value that can be stored in a Json::Value.
static const UInt64 maxUInt64 = UInt64(-1)
Maximum unsigned 64 bits int value that can be stored in a Json::Value.
Private Member Functions
Value & resolveReference (const char *key, bool isStatic)
Private Attributes
union Json::Value::ValueHolder value_
ValueType type_: 8
int allocated_: 1
CommentInfo * comments_
size_t start_
size_t limit_
Friends
class ValueIteratorBase
Detailed Description
Represents a JSON value.
This class is a discriminated union wrapper that can represents a:
signed integer [range: Value::minInt - Value::maxInt]
unsigned integer (range: 0 - Value::maxUInt)
double
UTF-8 string
boolean
'null'
an ordered list of Value
collection of name/value pairs (javascript object)
The type of the held value is represented by a ValueType and can be obtained using type().
values of an objectValue or arrayValue can be accessed using operator[]() methods. Non const methods will automatically create the a nullValue element if it does not exist. The sequence of an arrayValue will be automatically resize and initialized with nullValue. resize() can be used to enlarge or truncate an arrayValue.
The get() methods can be used to obtanis default value in the case the required element does not exist.
It is possible to iterate over the list of a objectValue values using the getMemberNames() method.
Member Typedef Documentation
typedef Json::ArrayIndex Json::Value::ArrayIndex
typedef ValueConstIterator Json::Value::const_iterator
typedef Json::Int Json::Value::Int
typedef Json::Int64 Json::Value::Int64
typedef ValueIterator Json::Value::iterator
typedef Json::LargestInt Json::Value::LargestInt
typedef Json::LargestUInt Json::Value::LargestUInt
typedef std::vector<std::string> Json::Value::Members
typedef std::map<CZString, Value> Json::Value::ObjectValues
typedef Json::UInt Json::Value::UInt
typedef Json::UInt64 Json::Value::UInt64
Constructor & Destructor Documentation
Json::Value::Value (ValueType type = nullValue)
Create a default Value of the given type.
This is a very useful constructor.
To create an empty array, pass arrayValue.
To create an empty object, pass objectValue.
Another Value can then be set to this one by assignment.
This is useful since clear() and resize() will not alter types.
Examples:
Json::Value null_value; // null
Json::Value arr_value(Json::arrayValue); // []
Json::Value obj_value(Json::objectValue); // {}
References Json::arrayValue, Json::Value::ValueHolder::bool_, Json::booleanValue, Json::Value::ValueHolder::int_, Json::intValue, JSON_ASSERT_UNREACHABLE, Json::Value::ValueHolder::map_, Json::nullValue, Json::objectValue, Json::Value::ValueHolder::real_, Json::realValue, Json::Value::ValueHolder::string_, Json::stringValue, Json::uintValue, and value_.
Referenced by operator[](), resize(), and resolveReference().
Json::Value::Value (Int value)
References Json::Value::ValueHolder::int_, and value_.
Json::Value::Value (UInt value)
References Json::Value::ValueHolder::uint_, and value_.
Json::Value::Value (Int64 value)
References Json::Value::ValueHolder::int_, and value_.
Json::Value::Value (UInt64 value)
References Json::Value::ValueHolder::uint_, and value_.
Json::Value::Value (double value)
References Json::Value::ValueHolder::real_, and value_.
Json::Value::Value (const char * value)
References Json::duplicateStringValue(), Json::Value::ValueHolder::string_, and value_.
Json::Value::Value (const char * beginValue, const char * endValue)
References Json::duplicateStringValue(), Json::Value::ValueHolder::string_, and value_.
Json::Value::Value (const StaticString & value)
Constructs a value from a static string.
Like other value string constructor but do not duplicate the string for internal storage. The given string must remain alive after the call to this constructor. Example of usage:
* Json::Value aValue(StaticString("some text"));
*
References Json::StaticString::c_str(), Json::Value::ValueHolder::string_, and value_.
Json::Value::Value (const std::string & value)
References Json::duplicateStringValue(), Json::Value::ValueHolder::string_, and value_.
Json::Value::Value (bool value)
References Json::Value::ValueHolder::bool_, and value_.
Json::Value::Value (const Value & other)
References allocated_, Json::arrayValue, Json::booleanValue, Json::Value::CommentInfo::comment_, comments_, Json::duplicateStringValue(), Json::intValue, JSON_ASSERT_UNREACHABLE, Json::Value::ValueHolder::map_, Json::nullValue, Json::numberOfCommentPlacement, Json::objectValue, Json::realValue, Json::Value::CommentInfo::setComment(), Json::Value::ValueHolder::string_, Json::stringValue, type_, Json::uintValue, and value_.
Json::Value::~Value ()
References allocated_, Json::arrayValue, Json::booleanValue, comments_, Json::intValue, JSON_ASSERT_UNREACHABLE, Json::Value::ValueHolder::map_, Json::nullValue, Json::objectValue, Json::realValue, Json::releaseStringValue(), Json::Value::ValueHolder::string_, Json::stringValue, type_, Json::uintValue, and value_.
Member Function Documentation
Value & Json::Value::append (const Value & value)
Append value to array at the end.
Equivalent to jsonvalue[jsonvalue.size()] = value;
References size().
Referenced by ClientListener::sendJsonPacket().
bool Json::Value::asBool () const
References Json::Value::ValueHolder::bool_, Json::booleanValue, Json::Value::ValueHolder::int_, Json::intValue, JSON_FAIL_MESSAGE, Json::nullValue, Json::Value::ValueHolder::real_, Json::realValue, type_, Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Referenced by Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), and Json::StyledStreamWriter::writeValue().
const char * Json::Value::asCString () const
References JSON_ASSERT_MESSAGE, Json::Value::ValueHolder::string_, Json::stringValue, type_, and value_.
Referenced by Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), and Json::StyledStreamWriter::writeValue().
double Json::Value::asDouble () const
References Json::Value::ValueHolder::bool_, Json::booleanValue, Json::Value::ValueHolder::int_, Json::intValue, JSON_FAIL_MESSAGE, Json::nullValue, Json::Value::ValueHolder::real_, Json::realValue, type_, Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Referenced by isConvertibleTo(), Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), and Json::StyledStreamWriter::writeValue().
float Json::Value::asFloat () const
References Json::Value::ValueHolder::bool_, Json::booleanValue, Json::Value::ValueHolder::int_, Json::intValue, JSON_FAIL_MESSAGE, Json::nullValue, Json::Value::ValueHolder::real_, Json::realValue, type_, Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Value::Int Json::Value::asInt () const
References Json::Value::ValueHolder::bool_, Json::booleanValue, Json::InRange(), Json::Value::ValueHolder::int_, Json::intValue, isInt(), JSON_ASSERT_MESSAGE, JSON_FAIL_MESSAGE, maxInt, minInt, Json::nullValue, Json::Value::ValueHolder::real_, Json::realValue, type_, Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Referenced by asLargestInt().
Value::Int64 Json::Value::asInt64 () const
References Json::Value::ValueHolder::bool_, Json::booleanValue, Json::InRange(), Json::Value::ValueHolder::int_, Json::intValue, isInt64(), JSON_ASSERT_MESSAGE, JSON_FAIL_MESSAGE, maxInt64, minInt64, Json::nullValue, Json::Value::ValueHolder::real_, Json::realValue, type_, Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Referenced by asLargestInt().
LargestInt Json::Value::asLargestInt () const
References asInt(), and asInt64().
Referenced by Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), and Json::StyledStreamWriter::writeValue().
LargestUInt Json::Value::asLargestUInt () const
References asUInt(), and asUInt64().
Referenced by Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), and Json::StyledStreamWriter::writeValue().
std::string Json::Value::asString () const
References Json::Value::ValueHolder::bool_, Json::booleanValue, Json::Value::ValueHolder::int_, Json::intValue, JSON_FAIL_MESSAGE, Json::nullValue, Json::Value::ValueHolder::real_, Json::realValue, Json::Value::ValueHolder::string_, Json::stringValue, type_, Json::Value::ValueHolder::uint_, Json::uintValue, value_, and Json::valueToString().
Referenced by isConvertibleTo(), and Json::Reader::readObject().
Value::UInt Json::Value::asUInt () const
References Json::Value::ValueHolder::bool_, Json::booleanValue, Json::InRange(), Json::Value::ValueHolder::int_, Json::intValue, isUInt(), JSON_ASSERT_MESSAGE, JSON_FAIL_MESSAGE, maxUInt, Json::nullValue, Json::Value::ValueHolder::real_, Json::realValue, type_, Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Referenced by asLargestUInt().
Value::UInt64 Json::Value::asUInt64 () const
References Json::Value::ValueHolder::bool_, Json::booleanValue, Json::InRange(), Json::Value::ValueHolder::int_, Json::intValue, isUInt64(), JSON_ASSERT_MESSAGE, JSON_FAIL_MESSAGE, maxUInt64, Json::nullValue, Json::Value::ValueHolder::real_, Json::realValue, type_, Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Referenced by asLargestUInt().
Value::const_iterator Json::Value::begin () const
References Json::arrayValue, Json::Value::ValueHolder::map_, Json::objectValue, type_, and value_.
Value::iterator Json::Value::begin ()
References Json::arrayValue, Json::Value::ValueHolder::map_, Json::objectValue, type_, and value_.
void Json::Value::clear ()
Remove all object members and array elements.
Precondition
type() is arrayValue, objectValue, or nullValue
Postcondition
type() is unchanged
References Json::arrayValue, JSON_ASSERT_MESSAGE, limit_, Json::Value::ValueHolder::map_, Json::nullValue, Json::objectValue, start_, type_, and value_.
Referenced by resize().
int Json::Value::compare (const Value & other) const
bool Json::Value::empty () const
Return true if empty array, empty object, or null; otherwise, false.
References isArray(), isNull(), isObject(), and size().
Value::const_iterator Json::Value::end () const
References Json::arrayValue, Json::Value::ValueHolder::map_, Json::objectValue, type_, and value_.
Value::iterator Json::Value::end ()
References Json::arrayValue, Json::Value::ValueHolder::map_, Json::objectValue, type_, and value_.
Value Json::Value::get (ArrayIndex index, const Value & defaultValue) const
If the array contains at least index+1 elements, returns the element value, otherwise returns defaultValue.
References null.
Value Json::Value::get (const char * key, const Value & defaultValue) const
Return the member named key if it exist, defaultValue otherwise.
References null.
Value Json::Value::get (const std::string & key, const Value & defaultValue) const
Return the member named key if it exist, defaultValue otherwise.
std::string Json::Value::getComment (CommentPlacement placement) const
Include delimiters and embedded newlines.
References Json::Value::CommentInfo::comment_, comments_, and hasComment().
Referenced by Json::StyledWriter::writeCommentAfterValueOnSameLine(), Json::StyledStreamWriter::writeCommentAfterValueOnSameLine(), Json::StyledWriter::writeCommentBeforeValue(), and Json::StyledStreamWriter::writeCommentBeforeValue().
Value::Members Json::Value::getMemberNames () const
Return a list of the member names.
If null, return an empty list.
Precondition
type() is objectValue or nullValue
Postcondition
if type() was nullValue, it remains nullValue
References JSON_ASSERT_MESSAGE, Json::Value::ValueHolder::map_, Json::nullValue, Json::objectValue, type_, and value_.
Referenced by Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), and Json::StyledStreamWriter::writeValue().
size_t Json::Value::getOffsetLimit () const
References limit_.
size_t Json::Value::getOffsetStart () const
References start_.
bool Json::Value::hasComment (CommentPlacement placement) const
References Json::Value::CommentInfo::comment_, and comments_.
Referenced by getComment(), Json::StyledWriter::hasCommentForValue(), Json::StyledStreamWriter::hasCommentForValue(), Json::StyledWriter::writeCommentAfterValueOnSameLine(), Json::StyledStreamWriter::writeCommentAfterValueOnSameLine(), Json::StyledWriter::writeCommentBeforeValue(), and Json::StyledStreamWriter::writeCommentBeforeValue().
bool Json::Value::isArray () const
References Json::arrayValue, and type_.
Referenced by empty(), Json::StyledWriter::isMultineArray(), Json::StyledStreamWriter::isMultineArray(), Json::Path::make(), Json::Reader::parse(), and Json::Path::resolve().
bool Json::Value::isBool () const
References Json::booleanValue, and type_.
bool Json::Value::isConvertibleTo (ValueType other) const
References Json::arrayValue, asDouble(), asString(), Json::Value::ValueHolder::bool_, Json::booleanValue, Json::InRange(), Json::intValue, isInt(), isNumeric(), isUInt(), JSON_ASSERT_UNREACHABLE, Json::Value::ValueHolder::map_, maxInt, maxUInt, minInt, Json::nullValue, Json::objectValue, Json::Value::ValueHolder::real_, Json::realValue, Json::stringValue, type_, Json::uintValue, and value_.
bool Json::Value::isDouble () const
References isIntegral(), Json::realValue, and type_.
Referenced by isNumeric().
bool Json::Value::isInt () const
References Json::Value::ValueHolder::int_, Json::intValue, Json::IsIntegral(), maxInt, minInt, Json::Value::ValueHolder::real_, Json::realValue, type_, Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Referenced by asInt(), isConvertibleTo(), and isIntegral().
bool Json::Value::isInt64 () const
References Json::intValue, Json::IsIntegral(), maxInt64, minInt64, Json::Value::ValueHolder::real_, Json::realValue, type_, Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Referenced by asInt64(), and isIntegral().
bool Json::Value::isIntegral () const
References isInt(), isInt64(), isUInt(), and isUInt64().
Referenced by isDouble(), and isNumeric().
bool Json::Value::isMember (const char * key) const
Return true if the object has a member named key.
References null.
Referenced by isMember().
bool Json::Value::isMember (const std::string & key) const
Return true if the object has a member named key.
References isMember().
bool Json::Value::isNull () const
References Json::nullValue, and type_.
Referenced by empty(), and operator!().
bool Json::Value::isNumeric () const
References isDouble(), and isIntegral().
Referenced by isConvertibleTo().
bool Json::Value::isObject () const
References Json::objectValue, and type_.
Referenced by empty(), Json::StyledWriter::isMultineArray(), Json::StyledStreamWriter::isMultineArray(), Json::Path::make(), Json::Reader::parse(), and Json::Path::resolve().
bool Json::Value::isString () const
References Json::stringValue, and type_.
bool Json::Value::isUInt () const
References Json::Value::ValueHolder::int_, Json::intValue, Json::IsIntegral(), maxUInt, Json::Value::ValueHolder::real_, Json::realValue, type_, Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Referenced by asUInt(), isConvertibleTo(), and isIntegral().
bool Json::Value::isUInt64 () const
References Json::Value::ValueHolder::int_, Json::intValue, Json::IsIntegral(), Json::maxUInt64AsDouble, Json::Value::ValueHolder::real_, Json::realValue, type_, Json::uintValue, and value_.
Referenced by asUInt64(), and isIntegral().
bool Json::Value::isValidIndex (ArrayIndex index) const
Return true if index < size().
References size().
Referenced by Json::Path::resolve().
bool Json::Value::operator! () const
Return isNull()
References isNull().
bool Json::Value::operator!= (const Value & other) const
bool Json::Value::operator< (const Value & other) const
References Json::arrayValue, Json::Value::ValueHolder::bool_, Json::booleanValue, Json::Value::ValueHolder::int_, Json::intValue, JSON_ASSERT_UNREACHABLE, Json::Value::ValueHolder::map_, Json::nullValue, Json::objectValue, Json::Value::ValueHolder::real_, Json::realValue, Json::Value::ValueHolder::string_, Json::stringValue, type_, Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
bool Json::Value::operator<= (const Value & other) const
Value & Json::Value::operator= (Value other)
References swap().
bool Json::Value::operator== (const Value & other) const
References Json::arrayValue, Json::Value::ValueHolder::bool_, Json::booleanValue, Json::Value::ValueHolder::int_, Json::intValue, JSON_ASSERT_UNREACHABLE, Json::Value::ValueHolder::map_, Json::nullValue, Json::objectValue, Json::Value::ValueHolder::real_, Json::realValue, Json::Value::ValueHolder::string_, Json::stringValue, type_, Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
bool Json::Value::operator> (const Value & other) const
bool Json::Value::operator>= (const Value & other) const
Value & Json::Value::operator[] (ArrayIndex index)
Access an array element (zero based index). If the array contains less than index element, then null value are inserted in the array so that its size is index+1. (You may need to say 'value[0u]' to get your compiler to distinguish this from the operator[] which takes a string.)
References Json::arrayValue, JSON_ASSERT_MESSAGE, Json::Value::ValueHolder::map_, null, Json::nullValue, type_, Value(), and value_.
Value & Json::Value::operator[] (int index)
Access an array element (zero based index). If the array contains less than index element, then null value are inserted in the array so that its size is index+1. (You may need to say 'value[0u]' to get your compiler to distinguish this from the operator[] which takes a string.)
References JSON_ASSERT_MESSAGE.
const Value & Json::Value::operator[] (ArrayIndex index) const
Access an array element (zero based index) (You may need to say 'value[0u]' to get your compiler to distinguish this from the operator[] which takes a string.)
References Json::arrayValue, JSON_ASSERT_MESSAGE, Json::Value::ValueHolder::map_, null, Json::nullValue, type_, and value_.
const Value & Json::Value::operator[] (int index) const
Access an array element (zero based index) (You may need to say 'value[0u]' to get your compiler to distinguish this from the operator[] which takes a string.)
References JSON_ASSERT_MESSAGE.
Value & Json::Value::operator[] (const char * key)
Access an object value by name, create a null member if it does not exist.
References resolveReference().
const Value & Json::Value::operator[] (const char * key) const
Access an object value by name, returns null if there is no member with that name.
References JSON_ASSERT_MESSAGE, Json::Value::ValueHolder::map_, Json::Value::CZString::noDuplication, null, Json::nullValue, Json::objectValue, type_, and value_.
Value & Json::Value::operator[] (const std::string & key)
Access an object value by name, create a null member if it does not exist.
const Value & Json::Value::operator[] (const std::string & key) const
Access an object value by name, returns null if there is no member with that name.
Value & Json::Value::operator[] (const StaticString & key)
Access an object value by name, create a null member if it does not exist.
If the object as no entry for that name, then the member name used to store the new entry is not duplicated. Example of use:
* Json::Value object;
* static const StaticString code("code");
* object[code] = 1234;
*
References resolveReference().
Value Json::Value::removeMember (const char * key)
Remove and return the named member.
Do nothing if it did not exist.
Returns
the removed Value, or null.
Precondition
type() is objectValue or nullValue
Postcondition
type() is unchanged
References JSON_ASSERT_MESSAGE, Json::Value::ValueHolder::map_, Json::Value::CZString::noDuplication, null, Json::nullValue, Json::objectValue, type_, and value_.
Referenced by removeMember().
Value Json::Value::removeMember (const std::string & key)
Same as removeMember(const char*)
References removeMember().
void Json::Value::resize (ArrayIndex size)
Resize the array to size elements. New elements are initialized to null. May only be called on nullValue or arrayValue.
Precondition
type() is arrayValue or nullValue
Postcondition
type() is arrayValue
References Json::arrayValue, clear(), JSON_ASSERT_MESSAGE, Json::Value::ValueHolder::map_, Json::nullValue, size(), type_, Value(), and value_.
Value & Json::Value::resolveReference (const char * key, bool isStatic) private
References Json::Value::CZString::duplicateOnCopy, JSON_ASSERT_MESSAGE, Json::Value::ValueHolder::map_, Json::Value::CZString::noDuplication, null, Json::nullValue, Json::objectValue, type_, Value(), and value_.
Referenced by operator[]().
void Json::Value::setComment (const char * comment, CommentPlacement placement)
Comments must be //... or /* ... */.
References comments_, Json::numberOfCommentPlacement, and Json::Value::CommentInfo::setComment().
Referenced by Json::Reader::addComment(), Json::Reader::parse(), Json::Reader::readValue(), and setComment().
void Json::Value::setComment (const std::string & comment, CommentPlacement placement)
Comments must be //... or /* ... */.
References setComment().
void Json::Value::setOffsetLimit (size_t limit)
References limit_.
Referenced by Json::Reader::decodeDouble(), Json::Reader::decodeNumber(), Json::Reader::decodeString(), and Json::Reader::readValue().
void Json::Value::setOffsetStart (size_t start)
References start_.
Referenced by Json::Reader::decodeDouble(), Json::Reader::decodeNumber(), Json::Reader::decodeString(), Json::Reader::readArray(), Json::Reader::readObject(), and Json::Reader::readValue().
ArrayIndex Json::Value::size () const
Number of values in array or object.
References Json::arrayValue, Json::booleanValue, Json::intValue, JSON_ASSERT_UNREACHABLE, Json::Value::ValueHolder::map_, Json::nullValue, Json::objectValue, Json::realValue, Json::stringValue, type_, Json::uintValue, and value_.
Referenced by append(), empty(), Json::StyledWriter::isMultineArray(), Json::StyledStreamWriter::isMultineArray(), isValidIndex(), resize(), Json::StyledWriter::writeArrayValue(), Json::StyledStreamWriter::writeArrayValue(), and Json::FastWriter::writeValue().
void Json::Value::swap (Value & other)
Swap values.
Note
Currently, comments are intentionally not swapped, for both logic and efficiency.
References allocated_, limit_, start_, type_, and value_.
Referenced by Json::Value::CZString::operator=(), and operator=().
std::string Json::Value::toStyledString () const
References Json::StyledWriter::write().
ValueType Json::Value::type () const
References type_.
Referenced by Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), and Json::StyledStreamWriter::writeValue().
Friends And Related Function Documentation
friend class ValueIteratorBase friend
Member Data Documentation
int Json::Value::allocated_ private
Referenced by swap(), Value(), and ~Value().
CommentInfo* Json::Value::comments_ private
Referenced by getComment(), hasComment(), setComment(), Value(), and ~Value().
size_t Json::Value::limit_ private
Referenced by clear(), getOffsetLimit(), setOffsetLimit(), and swap().
const Int Json::Value::maxInt = Int(UInt(-1) / 2) static
Maximum signed int value that can be stored in a Json::Value.
Referenced by asInt(), Json::Reader::decodeNumber(), Json::duplicateStringValue(), isConvertibleTo(), and isInt().
const Int64 Json::Value::maxInt64 = Int64(UInt64(-1) / 2) static
Maximum signed 64 bits int value that can be stored in a Json::Value.
Referenced by asInt64(), and isInt64().
const LargestInt Json::Value::maxLargestInt = LargestInt(LargestUInt(-1) / 2) static
Maximum signed integer value that can be stored in a Json::Value.
const LargestUInt Json::Value::maxLargestUInt = LargestUInt(-1) static
Maximum unsigned integer value that can be stored in a Json::Value.
Referenced by Json::Reader::decodeNumber().
const UInt Json::Value::maxUInt = UInt(-1) static
Maximum unsigned int value that can be stored in a Json::Value.
Referenced by asUInt(), isConvertibleTo(), and isUInt().
const UInt64 Json::Value::maxUInt64 = UInt64(-1) static
Maximum unsigned 64 bits int value that can be stored in a Json::Value.
Referenced by asUInt64().
const Int Json::Value::minInt = Int(~(UInt(-1) / 2)) static
Minimum signed int value that can be stored in a Json::Value.
Referenced by asInt(), isConvertibleTo(), and isInt().
const Int64 Json::Value::minInt64 = Int64(~(UInt64(-1) / 2)) static
Minimum signed 64 bits int value that can be stored in a Json::Value.
Referenced by asInt64(), and isInt64().
const LargestInt Json::Value::minLargestInt = LargestInt(~(LargestUInt(-1) / 2)) static
Minimum signed integer value that can be stored in a Json::Value.
Referenced by Json::Reader::decodeNumber().
const Value & Json::Value::null = reinterpret_cast<const Value&>(kNullRef) static
Referenced by get(), isMember(), operator[](), removeMember(), Json::Path::resolve(), and resolveReference().
size_t Json::Value::start_ private
Referenced by clear(), getOffsetStart(), setOffsetStart(), and swap().
ValueType Json::Value::type_ private
Referenced by asBool(), asCString(), asDouble(), asFloat(), asInt(), asInt64(), asString(), asUInt(), asUInt64(), begin(), clear(), end(), getMemberNames(), isArray(), isBool(), isConvertibleTo(), isDouble(), isInt(), isInt64(), isNull(), isObject(), isString(), isUInt(), isUInt64(), operator<(), operator==(), operator[](), removeMember(), resize(), resolveReference(), size(), swap(), type(), Value(), and ~Value().
union Json::Value::ValueHolder Json::Value::value_ private
Referenced by asBool(), asCString(), asDouble(), asFloat(), asInt(), asInt64(), asString(), asUInt(), asUInt64(), begin(), clear(), end(), getMemberNames(), isConvertibleTo(), isInt(), isInt64(), isUInt(), isUInt64(), operator<(), operator==(), operator[](), removeMember(), resize(), resolveReference(), size(), swap(), Value(), and ~Value().
The documentation for this class was generated from the following files:
Client/json/json.h
Client/jsoncpp.cpp