Claims: Client Class Reference
Client Class Reference
#include <Client.h>
Public Types
enum query_result { result, error, message }
Public Member Functions
Client ()
void connection (std::string host, int port)
ClientResponse * submitQuery (std::string args)
query_result submit (std::string command, std::string &message, ResultSet &rt)
ClientResponse * receive ()
void shutdown ()
bool connected () const
virtual ~Client ()
Private Attributes
bool connected_
int m_clientFd
Member Enumeration Documentation
enum Client::query_result
Enumerator
result
error
message
Constructor & Destructor Documentation
Client::Client ()
References connected_, and m_clientFd.
Client::~Client () virtual
Member Function Documentation
bool Client::connected () const
References connected_.
void Client::connection (std::string host, int port)
References connected_, m_clientFd, and result.
Referenced by main(), ElasticIteratorModelTest::SetUp(), and testServerClient().
ClientResponse * Client::receive ()
References ClientResponse::deserialize(), ClientLogging::log(), m_clientFd, and NULL.
Referenced by submit(), and testServerClient().
void Client::shutdown ()
References ClientLogging::log(), and m_clientFd.
Referenced by main(), ElasticIteratorModelTest::TearDown(), and testServerClient().
Client::query_result Client::submit (std::string command, std::string & message, ResultSet & rt)
References DynamicBlockBuffer::appendNewBlock(), CHANGEDD, ResultSet::column_header_list_, ClientResponse::content, DATA, ClientResponse::deserialize(), ENDED, error, ERROR, ClientResponse::getAttributeName(), ClientResponse::getDataBlock(), ClientResponse::getMessage(), ClientResponse::getSchema(), HEADER, ColumnHeader::header_list, L, ClientLogging::log(), m_clientFd, message, OK, ResultSet::query_time_, receive(), result, ResultSet::schema_, SCHEMASS, and ClientResponse::status.
Referenced by submit_command(), and submit_command_repeated().
ClientResponse * Client::submitQuery (std::string args)
References ClientResponse::deserialize(), L, ClientLogging::log(), m_clientFd, and NULL.
Referenced by testServerClient().
Member Data Documentation
bool Client::connected_ private
Referenced by Client(), connected(), and connection().
int Client::m_clientFd private
Referenced by Client(), connection(), receive(), shutdown(), submit(), and submitQuery().
The documentation for this class was generated from the following files:
Client/Client.h
Client/Client.cpp