Claims: ChunkReaderIterator::InMemeryBlockAccessor Class Reference
ChunkReaderIterator::InMemeryBlockAccessor Class Reference
#include <ChunkStorage.h>
Public Member Functions
InMemeryBlockAccessor ()
~InMemeryBlockAccessor ()
void getBlock (BlockStreamBase *&block) const
void * getTargetBlockStartAddress () const
void setTargetBlockStartAddress (void *targetBlockStartAddress)
Public Member Functions inherited from ChunkReaderIterator::block_accessor
block_accessor ()
~block_accessor ()
unsigned getBlockSize () const
void setBlockSize (unsigned blockSize)
Private Attributes
void * target_block_start_address
Additional Inherited Members
Protected Attributes inherited from ChunkReaderIterator::block_accessor
unsigned block_size
Constructor & Destructor Documentation
ChunkReaderIterator::InMemeryBlockAccessor::InMemeryBlockAccessor () inline
References NULL, and target_block_start_address.
ChunkReaderIterator::InMemeryBlockAccessor::~InMemeryBlockAccessor () inline
Member Function Documentation
void ChunkReaderIterator::InMemeryBlockAccessor::getBlock (BlockStreamBase *& block) const virtual
Reimplemented from ChunkReaderIterator::block_accessor.
References ChunkReaderIterator::block_accessor::block_size, BlockStreamBase::constructFromBlock(), Block::getBlock(), BlockStreamBase::getSerializedBlockSize(), Block::setBlock(), Block::setIsReference(), and target_block_start_address.
void* ChunkReaderIterator::InMemeryBlockAccessor::getTargetBlockStartAddress () const inline
References target_block_start_address.
void ChunkReaderIterator::InMemeryBlockAccessor::setTargetBlockStartAddress (void * targetBlockStartAddress) inline
References target_block_start_address.
Referenced by InMemoryChunkReaderItetaor::getNextBlockAccessor().
Member Data Documentation
void* ChunkReaderIterator::InMemeryBlockAccessor::target_block_start_address private
Referenced by getBlock(), getTargetBlockStartAddress(), InMemeryBlockAccessor(), and setTargetBlockStartAddress().
The documentation for this class was generated from the following files:
storage/ChunkStorage.h
storage/ChunkStorage.cpp