Claims: DMLTestPOC1Partition Class Reference
DMLTestPOC1Partition Class Reference
#include <sql_query_test.h>
Inherits Test.
Static Protected Member Functions
static void SetUpTestCase ()
static void TearDownTestCase ()
Member Function Documentation
static void DMLTestPOC1Partition::SetUpTestCase () inline static protected
References create_poc_data_one_partitions(), and Environment::getInstance().
static void DMLTestPOC1Partition::TearDownTestCase () inline static protected
References Environment::getInstance(), and Environment::~Environment().
The documentation for this class was generated from the following file:
Test/TestSuit/sql_query_test.h