Claims: NodeConnectionMessage Class Reference
NodeConnectionMessage Class Reference
#include <Message.h>
Public Member Functions
NodeConnectionMessage ()
NodeConnectionMessage (std::string ip, std::string port)
Static Public Member Functions
static NodeConnectionMessage deserialize (Message256 message)
static Message256 serialize (NodeConnectionMessage input)
static NodeConnectionMessage deserialize4K (Message4K message)
static Message4K serialize4K (NodeConnectionMessage input)
Public Attributes
std::string ip
std::string port
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Constructor & Destructor Documentation
NodeConnectionMessage::NodeConnectionMessage () inline
NodeConnectionMessage::NodeConnectionMessage (std::string ip, std::string port) inline
Member Function Documentation
static NodeConnectionMessage NodeConnectionMessage::deserialize (Message256 message) inline static
Referenced by AdaptiveEndPoint::ConnectionActor::ReceiveNodeStatus256().
static NodeConnectionMessage NodeConnectionMessage::deserialize4K (Message4K message) inline static
template<class Archive > void NodeConnectionMessage::serialize (Archive & ar, const unsigned int version) inline private
References ip, and port.
Referenced by Coordinator::ListeningNewNode().
static Message256 NodeConnectionMessage::serialize (NodeConnectionMessage input) inline static
References input().
static Message4K NodeConnectionMessage::serialize4K (NodeConnectionMessage input) inline static
References input().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
std::string NodeConnectionMessage::ip
Referenced by Coordinator::ListeningNewNode(), AdaptiveEndPoint::ConnectionActor::ReceiveNodeStatus256(), and serialize().
std::string NodeConnectionMessage::port
Referenced by Coordinator::ListeningNewNode(), AdaptiveEndPoint::ConnectionActor::ReceiveNodeStatus256(), and serialize().
The documentation for this class was generated from the following file:
common/Message.h