Claims: ResourceManagerMaster::ResourceManagerMasterActor Class Reference
ResourceManagerMaster::ResourceManagerMasterActor Class Reference
#include <ResourceManagerMaster.h>
Inherits Actor.
Public Member Functions
ResourceManagerMasterActor (Theron::Framework *framework, ResourceManagerMaster *rmm)
~ResourceManagerMasterActor ()
Private Member Functions
void ReceiveStorageBudgetReport (const StorageBudgetMessage &message, const Theron::Address from)
void ReceiveNewNodeRegister (const NodeRegisterMessage &message, const Theron::Address from)
Private Attributes
ResourceManagerMaster * rmm_
Constructor & Destructor Documentation
ResourceManagerMaster::ResourceManagerMasterActor::ResourceManagerMasterActor (Theron::Framework * framework, ResourceManagerMaster * rmm)
References ReceiveNewNodeRegister(), and ReceiveStorageBudgetReport().
ResourceManagerMaster::ResourceManagerMasterActor::~ResourceManagerMasterActor () inline
Referenced by ResourceManagerMaster::~ResourceManagerMaster().
Member Function Documentation
void ResourceManagerMaster::ResourceManagerMasterActor::ReceiveNewNodeRegister (const NodeRegisterMessage & message, const Theron::Address from) private
References NodeRegisterMessage::get_ip(), NodeAddress::ip, NodeAddress::port, and NodeRegisterMessage::port.
Referenced by ResourceManagerMasterActor().
void ResourceManagerMaster::ResourceManagerMasterActor::ReceiveStorageBudgetReport (const StorageBudgetMessage & message, const Theron::Address from) private
References StorageBudgetMessage::disk_budget, StorageBudgetMessage::memory_budget, and StorageBudgetMessage::nodeid.
Referenced by ResourceManagerMasterActor().
Member Data Documentation
ResourceManagerMaster* ResourceManagerMaster::ResourceManagerMasterActor::rmm_ private
The documentation for this class was generated from the following files:
Resource/ResourceManagerMaster.h
Resource/ResourceManagerMaster.cpp