Claims: Comparator Class Reference
Comparator Class Reference
#include <Comparator.h>
Classes
struct Pair
Public Types
enum comparison {
L, LEQ, EQ, NEQ,
G, GEQ
}
Public Member Functions
Comparator (column_type x, column_type b, Comparator::comparison c)
Comparator ()
Comparator (const Comparator &r)
virtual ~Comparator ()
comparison getCompareType () const
Public Attributes
bool(* compare)(const void *, const void *)
Protected Attributes
Pair pair
comparison compareType
Private Member Functions
void iniatilize ()
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Static Private Member Functions
static void initialize_L ()
static void initialize_GEQ ()
static void initialize_EQ ()
static void initialize_NEQ ()
static void initialize_G ()
static void initialize_LEQ ()
Static Private Attributes
static std::map< Pair, comFun > funs_L
static std::map< Pair, comFun > funs_GEQ
static std::map< Pair, comFun > funs_EQ
static std::map< Pair, comFun > funs_NEQ
static std::map< Pair, comFun > funs_G
static std::map< Pair, comFun > funs_LEQ
static Lock lock_
Friends
class boost::serialization::access
Member Enumeration Documentation
enum Comparator::comparison
Enumerator
L
LEQ
EQ
NEQ
G
GEQ
Constructor & Destructor Documentation
Comparator::Comparator (column_type x, column_type b, Comparator::comparison c)
References compare, and iniatilize().
Comparator::Comparator () inline
Comparator::Comparator (const Comparator & r)
References compareType, iniatilize(), and pair.
Comparator::~Comparator () virtual
Member Function Documentation
comparison Comparator::getCompareType () const inline
References compareType.
void Comparator::iniatilize () private
References Lock::acquire(), compare, compareType, EQ, Comparator::Pair::first, funs_EQ, funs_G, funs_GEQ, funs_L, funs_LEQ, funs_NEQ, G, GEQ, initialize_EQ(), initialize_G(), initialize_GEQ(), initialize_L(), initialize_LEQ(), initialize_NEQ(), L, LEQ, lock_, NEQ, pair, Lock::release(), Comparator::Pair::second, and column_type::type.
Referenced by Comparator(), and serialize().
void Comparator::initialize_EQ () static private
References equal< char *, char * >(), equal< NValue *, NValue * >(), funs_EQ, t_date, t_datetime, t_decimal, t_float, t_int, t_string, t_time, and t_u_long.
Referenced by iniatilize().
void Comparator::initialize_G () static private
References funs_G, great< char *, char * >(), great< NValue *, NValue * >(), t_date, t_datetime, t_decimal, t_float, t_int, t_string, t_time, and t_u_long.
Referenced by iniatilize().
void Comparator::initialize_GEQ () static private
References funs_GEQ, t_date, t_datetime, t_decimal, t_float, t_int, t_string, t_time, and t_u_long.
Referenced by iniatilize().
void Comparator::initialize_L () static private
References funs_L, LESS< char *, char * >(), LESS< char *, float >(), LESS< char *, int >(), LESS< float, char * >(), LESS< int, char * >(), LESS< NValue *, NValue * >(), t_date, t_datetime, t_decimal, t_float, t_int, t_string, t_time, and t_u_long.
Referenced by iniatilize().
void Comparator::initialize_LEQ () static private
References funs_LEQ, t_date, t_datetime, t_decimal, t_float, t_int, t_string, t_time, and t_u_long.
Referenced by iniatilize().
void Comparator::initialize_NEQ () static private
References funs_NEQ, t_date, t_datetime, t_decimal, t_float, t_int, t_string, t_time, and t_u_long.
Referenced by iniatilize().
template<class Archive > void Comparator::serialize (Archive & ar, const unsigned int version) inline private
References compare, compareType, iniatilize(), and pair.
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
bool(* Comparator::compare)(const void *, const void *)
Referenced by AttributeComparator::AttributeComparator(), Comparator(), AttributeComparator::filter(), iniatilize(), AttributeComparator::serialize(), and serialize().
comparison Comparator::compareType protected
Referenced by Comparator(), getCompareType(), iniatilize(), and serialize().
std::map< Comparator::Pair, comFun > Comparator::funs_EQ static private
Referenced by iniatilize(), and initialize_EQ().
std::map< Comparator::Pair, comFun > Comparator::funs_G static private
Referenced by iniatilize(), and initialize_G().
std::map< Comparator::Pair, comFun > Comparator::funs_GEQ static private
Referenced by iniatilize(), and initialize_GEQ().
std::map< Comparator::Pair, comFun > Comparator::funs_L static private
Referenced by iniatilize(), and initialize_L().
std::map< Comparator::Pair, comFun > Comparator::funs_LEQ static private
Referenced by iniatilize(), and initialize_LEQ().
std::map< Comparator::Pair, comFun > Comparator::funs_NEQ static private
Referenced by iniatilize(), and initialize_NEQ().
Lock Comparator::lock_ static private
Referenced by iniatilize().
Pair Comparator::pair protected
Referenced by AttributeComparator::AttributeComparator(), Comparator(), iniatilize(), AttributeComparator::serialize(), and serialize().
The documentation for this class was generated from the following files:
common/Comparator.h
common/Comparator.cpp