Claims: IteratorExecutorSlave::ExecuteIteratorActor Class Reference
IteratorExecutorSlave::ExecuteIteratorActor Class Reference
#include <IteratorExecutorSlave.h>
Inherits Actor.
Public Member Functions
ExecuteIteratorActor (IteratorExecutorSlave *ies, Theron::Framework &framework, const char *const slaveID)
Private Member Functions
void Handler256 (const Message256 &message, const Theron::Address from)
void Handler4K (const Message4K &message, const Theron::Address from)
void progation (const int &message, const Theron::Address from)
Private Attributes
IteratorExecutorSlave * ies
Constructor & Destructor Documentation
IteratorExecutorSlave::ExecuteIteratorActor::ExecuteIteratorActor (IteratorExecutorSlave * ies, Theron::Framework & framework, const char *const slaveID)
References Handler256(), Handler4K(), and progation().
Member Function Documentation
void IteratorExecutorSlave::ExecuteIteratorActor::Handler256 (const Message256 & message, const Theron::Address from) private
References PhysicalQueryPlan::deserialize(), and PhysicalQueryPlan::run().
Referenced by ExecuteIteratorActor().
void IteratorExecutorSlave::ExecuteIteratorActor::Handler4K (const Message4K & message, const Theron::Address from) private
References PhysicalQueryPlan::deserialize4K().
Referenced by ExecuteIteratorActor().
void IteratorExecutorSlave::ExecuteIteratorActor::progation (const int & message, const Theron::Address from) private
References IteratorExecutorMaster::getInstance(), and IteratorExecutorMaster::Propogation().
Referenced by ExecuteIteratorActor().
Member Data Documentation
IteratorExecutorSlave* IteratorExecutorSlave::ExecuteIteratorActor::ies private
The documentation for this class was generated from the following files:
Executor/IteratorExecutorSlave.h
Executor/IteratorExecutorSlave.cpp