Claims: Connector Class Reference
Connector Class Reference abstract
#include <Connector.h>
Public Member Functions
Connector (vector< vector< string > > writepath)
virtual ~Connector ()
virtual bool openFiles (open_flag open_flag_)=0
virtual bool closeFiles ()=0
virtual int flush (unsigned projection_offset, unsigned partition_offset, void *source, unsigned length)=0
Protected Attributes
vector< vector< string > > writepath
Constructor & Destructor Documentation
Connector::Connector (vector< vector< string > > writepath) inline
virtual Connector::~Connector () inline virtual
Member Function Documentation
virtual bool Connector::closeFiles () pure virtual
Implemented in HdfsConnector, and LocalDiskConnector.
Referenced by HdfsLoader::append(), and HdfsLoader::load().
virtual int Connector::flush (unsigned projection_offset, unsigned partition_offset, void * source, unsigned length) pure virtual
Implemented in HdfsConnector, and LocalDiskConnector.
Referenced by HdfsLoader::append(), HdfsLoader::insertRecords(), and HdfsLoader::load().
virtual bool Connector::openFiles (open_flag open_flag_) pure virtual
Implemented in HdfsConnector, and LocalDiskConnector.
Referenced by HdfsLoader::append(), and HdfsLoader::load().
Member Data Documentation
vector<vector<string> > Connector::writepath protected
Referenced by HdfsConnector::assgin_open_file(), and LocalDiskConnector::openFiles().
The documentation for this class was generated from the following file:
Loader/Connector.h