Claims: OperateTime Class Reference
OperateTime Class Reference
#include <data_type.h>
Public Member Functions
OperateTime (bool _nullable=true)
void assignment (const void *const &src, void *const &desc) const
std::string toString (void *value)
void toValue (void *target, const char *string)
bool equal (const void *const &a, const void *const &b) const
bool less (const void *&a, const void *&b) const
bool greate (const void *&a, const void *&b) const
int compare (const void *a, const void *b) const
void add (void *target, void *increment)
void multiple (void *target, void *increment)
fun GetADDFunction ()
fun GetMINFunction ()
fun GetMAXFunction ()
fun GetIncreateByOneFunction ()
fun GetAVGFunction ()
unsigned getPartitionValue (const void *key, const PartitionFunction *partition_function) const
unsigned getPartitionValue (const void *key) const
unsigned getPartitionValue (const void *key, const unsigned long &mod) const
Operate * duplicateOperator () const
bool setNull (void *value)
bool isNull (void *value) const
Public Member Functions inherited from Operate
Operate (bool _nullable=true)
virtual ~Operate ()
void ass (void *src, void *desc)
Additional Inherited Members
Public Attributes inherited from Operate
void(* assign)(const void *const &src, void *const &desc)
bool nullable
Constructor & Destructor Documentation
OperateTime::OperateTime (bool _nullable = true) inline
Member Function Documentation
void OperateTime::add (void * target, void * increment) inline virtual
Implements Operate.
References ADD_FUNC< time_duration * >().
void OperateTime::assignment (const void *const & src, void *const & desc) const inline virtual
Implements Operate.
int OperateTime::compare (const void * a, const void * b) const inline virtual
Implements Operate.
Operate* OperateTime::duplicateOperator () const inline virtual
Implements Operate.
bool OperateTime::equal (const void *const & a, const void *const & b) const inline virtual
Implements Operate.
fun OperateTime::GetADDFunction () inline virtual
Implements Operate.
References ADD_FUNC< time_duration * >().
fun OperateTime::GetAVGFunction () inline virtual
Implements Operate.
fun OperateTime::GetIncreateByOneFunction () inline virtual
Implements Operate.
fun OperateTime::GetMAXFunction () inline virtual
Implements Operate.
fun OperateTime::GetMINFunction () inline virtual
Implements Operate.
unsigned OperateTime::getPartitionValue (const void * key, const PartitionFunction * partition_function) const inline virtual
Implements Operate.
unsigned OperateTime::getPartitionValue (const void * key) const inline virtual
Implements Operate.
References hash_value().
unsigned OperateTime::getPartitionValue (const void * key, const unsigned long & mod) const inline virtual
Implements Operate.
References hash_value().
bool OperateTime::greate (const void *& a, const void *& b) const inline virtual
Implements Operate.
bool OperateTime::isNull (void * value) const inline virtual
Implements Operate.
bool OperateTime::less (const void *& a, const void *& b) const inline virtual
Implements Operate.
void OperateTime::multiple (void * target, void * increment) inline virtual
Implements Operate.
bool OperateTime::setNull (void * value) inline virtual
Implements Operate.
References NULL_TIME.
std::string OperateTime::toString (void * value) inline virtual
Implements Operate.
void OperateTime::toValue (void * target, const char * string) inline virtual
Implements Operate.
The documentation for this class was generated from the following file:
common/data_type.h