Claims: ChunkStorage Class Reference
ChunkStorage Class Reference
#include <ChunkStorage.h>
Public Member Functions
ChunkStorage (const ChunkID &chunk_id, const unsigned &block_size, const StorageLevel &desirable_level)
virtual ~ChunkStorage ()
ChunkReaderIterator * createChunkReaderIterator ()
std::string printCurrentStorageLevel () const
ChunkID getChunkID ()
void setCurrentStorageLevel (const StorageLevel &current_level)
Private Attributes
unsigned block_size_
unsigned chunk_size_
StorageLevel desirable_storage_level_
StorageLevel current_storage_level_
ChunkID chunk_id_
Lock lock_
Constructor & Destructor Documentation
ChunkStorage::ChunkStorage (const ChunkID & chunk_id, const unsigned & block_size, const StorageLevel & desirable_level)
ChunkStorage::~ChunkStorage () virtual
Member Function Documentation
ChunkReaderIterator * ChunkStorage::createChunkReaderIterator ()
References Lock::acquire(), block_size_, chunk_id_, CHUNK_SIZE, chunk_size_, current_storage_level_, desirable_storage_level_, DISK, BlockManager::getInstance(), BlockManager::getMemoryChunkStore(), HDFS, HdfsBlock::hook, HdfsBlock::length, BlockManager::loadFromDisk(), BlockManager::loadFromHdfs(), Config::local_disk_mode, lock_, MEMORY, Lock::release(), MemoryChunkStore::returnChunk(), and MemoryChunkStore::updateChunkInfo().
ChunkID ChunkStorage::getChunkID () inline
References chunk_id_.
std::string ChunkStorage::printCurrentStorageLevel () const
void ChunkStorage::setCurrentStorageLevel (const StorageLevel & current_level) inline
References current_storage_level_.
Member Data Documentation
unsigned ChunkStorage::block_size_ private
Referenced by createChunkReaderIterator().
ChunkID ChunkStorage::chunk_id_ private
Referenced by createChunkReaderIterator(), and getChunkID().
unsigned ChunkStorage::chunk_size_ private
Referenced by createChunkReaderIterator().
StorageLevel ChunkStorage::current_storage_level_ private
Referenced by createChunkReaderIterator(), and setCurrentStorageLevel().
StorageLevel ChunkStorage::desirable_storage_level_ private
Referenced by createChunkReaderIterator().
Lock ChunkStorage::lock_ private
Referenced by createChunkReaderIterator().
The documentation for this class was generated from the following files:
storage/ChunkStorage.h
storage/ChunkStorage.cpp