Claims: Environment Class Reference
Environment Class Reference
#include <Environment.h>
Public Member Functions
virtual ~Environment ()
std::string getIp ()
unsigned getPort ()
AdaptiveEndPoint * getEndPoint ()
ExchangeTracker * getExchangeTracker ()
ResourceManagerMaster * getResourceManagerMaster ()
InstanceResourceManager * getResourceManagerSlave ()
NodeID getNodeID () const
Catalog * getCatalog () const
ThreadPool * getThreadPool () const
IteratorExecutorSlave * getIteratorExecutorSlave () const
Environment (bool ismaster=false)
virtual ~Environment ()
std::string getIp ()
unsigned getPort ()
AdaptiveEndPoint * getEndPoint ()
ExchangeTracker * getExchangeTracker ()
ResourceManagerMaster * getResourceManagerMaster ()
InstanceResourceManager * getResourceManagerSlave ()
NodeID getNodeID () const
Catalog * getCatalog () const
ThreadPool * getThreadPool () const
IteratorExecutorSlave * getIteratorExecutorSlave () const
Environment (bool ismaster=false)
Static Public Member Functions
static Environment * getInstance (bool ismaster=0)
static Environment * getInstance (bool ismaster=0)
Private Member Functions
void readConfigFile ()
void initializeEndPoint ()
void initializeCoordinator ()
void initializeStorage ()
void initializeResourceManager ()
void initializeBufferManager ()
void initializeIndexManager ()
void initializeClientListener ()
void initializeExpressionSystem ()
void destoryClientListener ()
bool initializeThreadPool ()
void readConfigFile ()
void initializeEndPoint ()
void initializeCoordinator ()
void initializeStorage ()
void initializeResourceManager ()
void initializeBufferManager ()
void initializeIndexManager ()
void initializeClientListener ()
void initializeExpressionSystem ()
void destoryClientListener ()
bool initializeThreadPool ()
Private Attributes
PortManager * portManager
AdaptiveEndPoint * endpoint
Coordinator * coordinator
std::string ip
unsigned port
IteratorExecutorSlave * iteratorExecutorSlave
IteratorExecutorMaster * iteratorExecutorMaster
ExchangeTracker * exchangeTracker
Logging * logging_
bool ismaster_
ResourceManagerMaster * resourceManagerMaster_
InstanceResourceManager * resourceManagerSlave_
Catalog * catalog_
NodeID nodeid
BlockManagerMaster * blockManagerMaster_
BlockManager * blockManager_
BufferManager * bufferManager_
IndexManager * indexManager_
ExpanderTracker * expander_tracker_
ClientListener * listener_
ThreadPool * thread_pool_
Static Private Attributes
static Environment * _instance = 0
Constructor & Destructor Documentation
Environment::~Environment () virtual
References _instance, blockManager_, blockManagerMaster_, bufferManager_, catalog_, coordinator, destoryClientListener(), endpoint, exchangeTracker, expander_tracker_, ismaster_, iteratorExecutorMaster, iteratorExecutorSlave, logging_, portManager, resourceManagerMaster_, and resourceManagerSlave_.
Referenced by in_segment_scalability_test_on_poc(), in_segment_scalability_test_on_tpch(), issue27_multi_node(), issue27_single_node(), issue27_sort_single_node(), issue27ing_single_node(), main(), scalability_test(), tcp_h_test_multi_nodes(), tcp_h_test_single_node(), DMLTestPOC1Partition::TearDownTestCase(), test_index_manager(), and test_load().
Environment::Environment (bool ismaster = false)
TODO: DO something in AdaptiveEndPoint such that the construction function does not return until the connection is completed. If so, the following sleep() dose not needed.
This is done in Aug.18 by Li :)
References _instance, catalog_, Logging::elog(), exchangeTracker, expander_tracker_, g_thread_pool_used, PortManager::getInstance(), Config::getInstance(), CodeGenerator::getInstance(), Catalog::getInstance(), ExpanderTracker::getInstance(), initializeBufferManager(), initializeClientListener(), initializeCoordinator(), initializeEndPoint(), initializeExpressionSystem(), initializeResourceManager(), initializeStorage(), initializeThreadPool(), iteratorExecutorMaster, iteratorExecutorSlave, Logging::log(), logging_, portManager, readConfigFile(), and Catalog::restoreCatalog().
Referenced by getInstance().
virtual Environment::~Environment () virtual
Environment::Environment (bool ismaster = false)
Member Function Documentation
void Environment::destoryClientListener () private
References listener_, and ClientListener::shutdown().
Referenced by ~Environment().
void Environment::destoryClientListener () private
Catalog * Environment::getCatalog () const
References catalog_.
Referenced by add_all_table_column(), add_table_column(), BindingTest(), create_poc_data_four_partitions(), create_poc_data_one_partitions(), CreateTable(), claims::stmt_handler::CreateTableExec::CreateTableExec(), execting_test(), claims::stmt_handler::LoadExec::Execute(), claims::stmt_handler::InsertExec::Execute(), claims::stmt_handler::CreateTableExec::Execute(), execute_sql_test(), ExecuteLogicalQueryPlan(), get_aggregation_args(), AstSelectStmt::GetLogicalPlanOfProject(), init_multi_node_tpc_h_envoriment_(), init_poc_environment(), init_single_node_tpc_h_envoriment_(), init_single_node_tpc_h_envoriment_ing(), init_single_node_tpc_h_envoriment_sort(), init_tt_environment(), insert_into_hash_table_from_projection(), InsertData(), claims::stmt_handler::InsertExec::InsertExec(), lineitem_scan_aggregation(), lineitem_scan_filter(), lineitem_scan_self_join(), load_tpc_h_4_partition(), loadData(), claims::stmt_handler::LoadExec::LoadExec(), oncondition_check(), orderby_analysis(), projection_scan(), query_1(), query_2(), query_3(), query_select_aggregation(), query_select_aggregation_ing(), query_select_fzh(), query_select_sort(), query_select_sort_string(), sb_scan_aggregation(), sb_scan_filter(), sb_scan_self_join(), selectlist_expr_analysis(), AstTable::SemanticAnalisys(), startup_catalog(), startup_mulitple_node_environment_of_poc(), startup_multiple_node_environment(), startup_multiple_node_environment_of_stock(), startup_multiple_node_environment_of_tpch(), startup_single_node_environment_of_tpch(), startup_single_node_one_partition_environment_of_tpch(), statistic_manager_test(), table_has_column(), test_block_construct(), test_CSBIndexBuilding(), test_index_scan_iterator(), test_logical_csb_index_building(), testServerClient(), variable_schema_test(), and wherecondition_check().
Catalog* Environment::getCatalog () const
AdaptiveEndPoint * Environment::getEndPoint ()
References endpoint.
Referenced by ExchangeTracker::ExchangeTracker(), IteratorExecutorMaster::IteratorExecutorMaster(), IteratorExecutorSlave::IteratorExecutorSlave(), and ResourceManagerMaster::ResourceManagerMaster().
AdaptiveEndPoint* Environment::getEndPoint ()
ExchangeTracker * Environment::getExchangeTracker ()
References exchangeTracker.
Referenced by claims::physical_operator::ExchangeMerger::Close(), claims::physical_operator::ExchangeSender::ConnectToUpper(), claims::physical_operator::ExchangeMerger::IsOtherMergersRegistered(), and claims::physical_operator::ExchangeMerger::RegisterExchange().
ExchangeTracker* Environment::getExchangeTracker ()
Environment * Environment::getInstance (bool ismaster = 0) static
References _instance, and Environment().
Referenced by add_all_table_column(), add_table_column(), ExchangeTracker::ExchangeTrackerActor::AskForConnectionInfo(), ProjectionBinding::BindingEntireProjection(), BindingTest(), BlockManager::BlockManager(), BlockManagerMaster::BlockManagerMaster(), claims::physical_operator::ExchangeMerger::Close(), claims::physical_operator::ExchangeSender::ConnectToUpper(), create_load_test(), create_poc_data_four_partitions(), create_poc_data_one_partitions(), CreateTable(), claims::stmt_handler::CreateTableExec::CreateTableExec(), claims::physical_operator::ExchangeSenderMaterialized::CreateWorkerThread(), claims::physical_operator::Expander::CreateWorkingThread(), ExchangeTracker::ExchangeTracker(), execting_test(), claims::stmt_handler::LoadExec::Execute(), claims::stmt_handler::InsertExec::Execute(), claims::stmt_handler::CreateTableExec::Execute(), execute_sql_test(), IteratorExecutorMaster::ExecuteBlockStreamIteratorsOnSite(), ExecuteLogicalQueryPlan(), fromlist_analysis(), get_aggregation_args(), AstTable::GetLogicalPlan(), AstSelectStmt::GetLogicalPlanOfProject(), in_segment_scalability_test_on_poc(), in_segment_scalability_test_on_tpch(), init_multi_node_tpc_h_envoriment_(), init_poc_environment(), init_single_node_tpc_h_envoriment_(), init_single_node_tpc_h_envoriment_ing(), init_single_node_tpc_h_envoriment_sort(), init_tt_environment(), BlockManager::initialize(), insert_into_hash_table_from_projection(), InsertData(), claims::stmt_handler::InsertExec::InsertExec(), InstanceResourceManager::InstanceResourceManager(), claims::physical_operator::ExchangeMerger::IsOtherMergersRegistered(), issue27_multi_node(), issue27_single_node(), issue27_sort_single_node(), issue27ing_single_node(), IteratorExecutorMaster::IteratorExecutorMaster(), IteratorExecutorSlave::IteratorExecutorSlave(), lineitem_scan_aggregation(), lineitem_scan_filter(), lineitem_scan_self_join(), load_tpc_h_4_partition(), loadData(), claims::stmt_handler::LoadExec::LoadExec(), main(), main234234(), main_aaa(), oncondition_check(), claims::physical_operator::ResultCollector::Open(), orderby_analysis(), projection_scan(), query_1(), query_2(), query_3(), query_select_aggregation(), query_select_aggregation_ing(), query_select_fzh(), query_select_sort(), query_select_sort_string(), InstanceResourceManager::Register(), claims::physical_operator::ExchangeMerger::RegisterExchange(), ResourceManagerMaster::ResourceManagerMaster(), sb_scan_aggregation(), sb_scan_filter(), sb_scan_self_join(), scalability_test(), selectlist_expr_analysis(), AstTable::SemanticAnalisys(), BlockManagerMaster::SendBindingMessage(), BlockManagerMaster::SendUnbindingMessage(), DMLTestPOC1Partition::SetUpTestCase(), Coordinator::SetupTheTheron(), startup_catalog(), startup_mulitple_node_environment_of_poc(), startup_multiple_node_environment(), startup_multiple_node_environment_of_stock(), startup_multiple_node_environment_of_tpch(), startup_single_node_environment_of_poc(), startup_single_node_environment_of_tpch(), startup_single_node_one_partition_environment_of_tpch(), statistic_manager_test(), table_has_column(), tcp_h_test_multi_nodes(), tcp_h_test_single_node(), DMLTestPOC1Partition::TearDownTestCase(), test_block_construct(), test_CSBIndexBuilding(), test_expanderFramework_single_node(), test_index_manager(), test_index_scan_iterator(), test_load(), test_logical_csb_index_building(), test_multiple_expanderFramework_single_node(), testIteratorExecutor(), testServerClient(), ProjectionBinding::UnbindingEntireProjection(), variable_schema_test(), where_from2logicalplan(), and wherecondition_check().
static Environment* Environment::getInstance (bool ismaster = 0) static
std::string Environment::getIp ()
References ip.
Referenced by InstanceResourceManager::Register(), and Coordinator::SetupTheTheron().
std::string Environment::getIp ()
IteratorExecutorSlave* Environment::getIteratorExecutorSlave () const
IteratorExecutorSlave * Environment::getIteratorExecutorSlave () const
References iteratorExecutorSlave.
Referenced by IteratorExecutorMaster::ExecuteBlockStreamIteratorsOnSite().
NodeID Environment::getNodeID () const
References nodeid.
Referenced by BlockManager::BlockManager(), ExchangeTracker::ExchangeTracker(), BlockManager::initialize(), and IteratorExecutorSlave::IteratorExecutorSlave().
NodeID Environment::getNodeID () const
unsigned Environment::getPort ()
unsigned Environment::getPort ()
References port.
Referenced by InstanceResourceManager::Register().
ResourceManagerMaster * Environment::getResourceManagerMaster ()
References resourceManagerMaster_.
Referenced by ProjectionBinding::BindingEntireProjection(), BindingTest(), create_poc_data_four_partitions(), create_poc_data_one_partitions(), execting_test(), ExecuteLogicalQueryPlan(), init_multi_node_tpc_h_envoriment_(), init_poc_environment(), init_single_node_tpc_h_envoriment_(), init_single_node_tpc_h_envoriment_ing(), init_single_node_tpc_h_envoriment_sort(), init_tt_environment(), load_tpc_h_4_partition(), loadData(), startup_catalog(), startup_mulitple_node_environment_of_poc(), startup_multiple_node_environment(), startup_multiple_node_environment_of_stock(), startup_multiple_node_environment_of_tpch(), startup_single_node_environment_of_tpch(), startup_single_node_one_partition_environment_of_tpch(), statistic_manager_test(), test_CSBIndexBuilding(), test_index_scan_iterator(), test_logical_csb_index_building(), testServerClient(), ProjectionBinding::UnbindingEntireProjection(), and variable_schema_test().
ResourceManagerMaster* Environment::getResourceManagerMaster ()
InstanceResourceManager* Environment::getResourceManagerSlave ()
InstanceResourceManager * Environment::getResourceManagerSlave ()
References resourceManagerSlave_.
Referenced by BlockManager::initialize().
ThreadPool* Environment::getThreadPool () const
ThreadPool * Environment::getThreadPool () const
References thread_pool_.
Referenced by claims::physical_operator::ExchangeSenderMaterialized::CreateWorkerThread(), claims::physical_operator::Expander::CreateWorkingThread(), and claims::physical_operator::ResultCollector::Open().
void Environment::initializeBufferManager () private
References bufferManager_, and BufferManager::getInstance().
Referenced by Environment().
void Environment::initializeBufferManager () private
void Environment::initializeClientListener () private
References Config::client_listener_port, ClientListener::configure(), and listener_.
Referenced by Environment().
void Environment::initializeClientListener () private
void Environment::initializeCoordinator () private
void Environment::initializeCoordinator () private
References coordinator.
Referenced by Environment().
void Environment::initializeEndPoint () private
void Environment::initializeEndPoint () private
References PortManager::applyPort(), Logging::elog(), endpoint, ip, Logging::log(), logging_, port, and portManager.
Referenced by Environment().
void Environment::initializeExpressionSystem () private
void Environment::initializeExpressionSystem () private
References claims::common::InitAggAvgDivide(), initialize_arithmetic_type_promotion_matrix(), initialize_operator_function(), initialize_type_cast_functions(), claims::common::InitOperatorFunc(), claims::common::InitTypeCastFunc(), and claims::common::InitTypeConversionMatrix().
Referenced by Environment().
void Environment::initializeIndexManager () private
References IndexManager::getInstance(), and indexManager_.
void Environment::initializeIndexManager () private
void Environment::initializeResourceManager () private
References ismaster_, nodeid, InstanceResourceManager::Register(), resourceManagerMaster_, and resourceManagerSlave_.
Referenced by Environment().
void Environment::initializeResourceManager () private
void Environment::initializeStorage () private
void Environment::initializeStorage () private
References blockManager_, blockManagerMaster_, BlockManagerMaster::getInstance(), BlockManager::getInstance(), BlockManagerMaster::initialize(), BlockManager::initialize(), and ismaster_.
Referenced by Environment().
bool Environment::initializeThreadPool () private
bool Environment::initializeThreadPool () private
References thread_pool_, and ThreadPool::Thread_Pool_init().
Referenced by Environment().
void Environment::readConfigFile () private
References Config::config_file, and ip.
Referenced by Environment().
void Environment::readConfigFile () private
Member Data Documentation
static Environment * Environment::_instance = 0 static private
Referenced by Environment(), getInstance(), and ~Environment().
BlockManager * Environment::blockManager_ private
Referenced by initializeStorage(), and ~Environment().
BlockManagerMaster * Environment::blockManagerMaster_ private
Referenced by initializeStorage(), and ~Environment().
BufferManager * Environment::bufferManager_ private
Referenced by initializeBufferManager(), and ~Environment().
Catalog * Environment::catalog_ private
Referenced by Environment(), getCatalog(), and ~Environment().
Coordinator * Environment::coordinator private
Referenced by initializeCoordinator(), and ~Environment().
AdaptiveEndPoint * Environment::endpoint private
Referenced by getEndPoint(), initializeEndPoint(), and ~Environment().
ExchangeTracker * Environment::exchangeTracker private
Referenced by Environment(), getExchangeTracker(), and ~Environment().
ExpanderTracker * Environment::expander_tracker_ private
Referenced by Environment(), and ~Environment().
IndexManager * Environment::indexManager_ private
Referenced by initializeIndexManager().
std::string Environment::ip private
Referenced by getIp(), initializeEndPoint(), and readConfigFile().
bool Environment::ismaster_ private
Referenced by initializeResourceManager(), initializeStorage(), and ~Environment().
IteratorExecutorMaster * Environment::iteratorExecutorMaster private
Referenced by Environment(), and ~Environment().
IteratorExecutorSlave * Environment::iteratorExecutorSlave private
Referenced by Environment(), getIteratorExecutorSlave(), and ~Environment().
ClientListener * Environment::listener_ private
Referenced by destoryClientListener(), and initializeClientListener().
Logging * Environment::logging_ private
Referenced by Environment(), initializeEndPoint(), and ~Environment().
NodeID Environment::nodeid private
Referenced by getNodeID(), and initializeResourceManager().
unsigned Environment::port private
Referenced by getPort(), and initializeEndPoint().
PortManager * Environment::portManager private
Referenced by Environment(), initializeEndPoint(), and ~Environment().
ResourceManagerMaster * Environment::resourceManagerMaster_ private
Referenced by getResourceManagerMaster(), initializeResourceManager(), and ~Environment().
InstanceResourceManager * Environment::resourceManagerSlave_ private
Referenced by getResourceManagerSlave(), initializeResourceManager(), and ~Environment().
ThreadPool * Environment::thread_pool_ private
Referenced by getThreadPool(), and initializeThreadPool().
The documentation for this class was generated from the following files:
Environment.h
install/include/Environment.h
Environment.cpp