Claims: PartitionedBlockBuffer Class Reference
PartitionedBlockBuffer Class Reference
#include <PartitionedBlockBuffer.h>
Public Member Functions
PartitionedBlockBuffer (unsigned nPartitions, unsigned block_size, unsigned nBlocks)
PartitionedBlockBuffer (unsigned nPartitions, unsigned block_size)
virtual ~PartitionedBlockBuffer ()
bool hasEmptyBlock () const
bool isEmpty ()
bool insertBlockToPartitionedList (Block *src, unsigned partition_id)
int getBlock (Block &desc)
bool getBlock (Block &desc, unsigned partition_id)
unsigned getBlockInBuffer ()
Public Attributes
unsigned inserted
unsigned removed
Private Member Functions
bool getBlockInPartitionedBlockList (Block &desc, unsigned partition_id)
unsigned getBlockNumberOfPartitionInBuffer (unsigned partition_id)
void destoryEmptyBlocks ()
Private Attributes
unsigned nPartitions
unsigned nBlocks
std::list< Block * > * blocks_in_partition_list
std::list< Block * > empty_block_list
Lock lock
semaphore empty_blocks
semaphore used_blocks
Constructor & Destructor Documentation
PartitionedBlockBuffer::PartitionedBlockBuffer (unsigned nPartitions, unsigned block_size, unsigned nBlocks)
References blocks_in_partition_list, empty_block_list, empty_blocks, inserted, nBlocks, nPartitions, removed, semaphore::set_value(), and used_blocks.
PartitionedBlockBuffer::PartitionedBlockBuffer (unsigned nPartitions, unsigned block_size)
References blocks_in_partition_list, empty_block_list, empty_blocks, inserted, nBlocks, nPartitions, removed, semaphore::set_value(), and used_blocks.
PartitionedBlockBuffer::~PartitionedBlockBuffer () virtual
References blocks_in_partition_list, destoryEmptyBlocks(), semaphore::get_value(), nPartitions, and used_blocks.
Member Function Documentation
void PartitionedBlockBuffer::destoryEmptyBlocks () private
References empty_block_list.
Referenced by ~PartitionedBlockBuffer().
int PartitionedBlockBuffer::getBlock (Block & desc)
References Lock::acquire(), blocks_in_partition_list, empty_blocks, getBlockInPartitionedBlockList(), lock, nPartitions, semaphore::post(), Lock::release(), used_blocks, and semaphore::wait().
Referenced by claims::physical_operator::ExchangeSenderMaterialized::Materialize(), and claims::physical_operator::ExchangeSenderPipeline::Sender().
bool PartitionedBlockBuffer::getBlock (Block & desc, unsigned partition_id)
References Lock::acquire(), empty_blocks, getBlockInPartitionedBlockList(), getBlockNumberOfPartitionInBuffer(), lock, semaphore::post(), Lock::release(), used_blocks, and semaphore::wait().
unsigned PartitionedBlockBuffer::getBlockInBuffer ()
References Lock::acquire(), semaphore::get_value(), lock, Lock::release(), and used_blocks.
Referenced by claims::physical_operator::ExchangeSenderMaterialized::debug(), and claims::physical_operator::ExchangeSenderMaterialized::Materialize().
bool PartitionedBlockBuffer::getBlockInPartitionedBlockList (Block & desc, unsigned partition_id) private
References blocks_in_partition_list, empty_block_list, Block::getBlock(), and Block::getsize().
Referenced by getBlock().
unsigned PartitionedBlockBuffer::getBlockNumberOfPartitionInBuffer (unsigned partition_id) private
References Lock::acquire(), blocks_in_partition_list, lock, and Lock::release().
Referenced by getBlock().
bool PartitionedBlockBuffer::hasEmptyBlock () const
References empty_block_list.
bool PartitionedBlockBuffer::insertBlockToPartitionedList (Block * src, unsigned partition_id)
'copy' a block into the corresponding partitioned block list. In fact, the swap of pointer is used rather than actually coping the content for performance concern.
References Lock::acquire(), blocks_in_partition_list, empty_block_list, empty_blocks, Block::getBlock(), Block::getsize(), inserted, lock, nPartitions, semaphore::post(), Lock::release(), used_blocks, and semaphore::wait().
Referenced by claims::physical_operator::ExchangeSenderMaterialized::Next(), and claims::physical_operator::ExchangeSenderPipeline::Next().
bool PartitionedBlockBuffer::isEmpty ()
References semaphore::get_value(), and used_blocks.
Referenced by claims::physical_operator::ExchangeSenderMaterialized::Next(), and claims::physical_operator::ExchangeSenderPipeline::Next().
Member Data Documentation
std::list<Block*>* PartitionedBlockBuffer::blocks_in_partition_list private
Referenced by getBlock(), getBlockInPartitionedBlockList(), getBlockNumberOfPartitionInBuffer(), insertBlockToPartitionedList(), PartitionedBlockBuffer(), and ~PartitionedBlockBuffer().
std::list<Block*> PartitionedBlockBuffer::empty_block_list private
Referenced by destoryEmptyBlocks(), getBlockInPartitionedBlockList(), hasEmptyBlock(), insertBlockToPartitionedList(), and PartitionedBlockBuffer().
semaphore PartitionedBlockBuffer::empty_blocks private
Referenced by getBlock(), insertBlockToPartitionedList(), and PartitionedBlockBuffer().
unsigned PartitionedBlockBuffer::inserted
Referenced by insertBlockToPartitionedList(), and PartitionedBlockBuffer().
Lock PartitionedBlockBuffer::lock private
Referenced by getBlock(), getBlockInBuffer(), getBlockNumberOfPartitionInBuffer(), and insertBlockToPartitionedList().
unsigned PartitionedBlockBuffer::nBlocks private
Referenced by PartitionedBlockBuffer().
unsigned PartitionedBlockBuffer::nPartitions private
Referenced by getBlock(), insertBlockToPartitionedList(), PartitionedBlockBuffer(), and ~PartitionedBlockBuffer().
unsigned PartitionedBlockBuffer::removed
Referenced by PartitionedBlockBuffer().
semaphore PartitionedBlockBuffer::used_blocks private
Referenced by getBlock(), getBlockInBuffer(), insertBlockToPartitionedList(), isEmpty(), PartitionedBlockBuffer(), and ~PartitionedBlockBuffer().
The documentation for this class was generated from the following files:
common/Block/PartitionedBlockBuffer.h
common/Block/PartitionedBlockBuffer.cpp