Claims: Lock Class Reference
Lock Class Reference
#include <lock.h>
Public Member Functions
Lock ()
~Lock ()
void acquire ()
bool try_acquire ()
void release ()
void destroy ()
Private Attributes
pthread_mutex_t m
Constructor & Destructor Documentation
Lock::Lock () inline
References m, and NULL.
Lock::~Lock () inline
References m.
Member Function Documentation
void Lock::acquire () inline
References m.
Referenced by Daemon::addExecutedResult(), claims::physical_operator::Expander::AddIntoCalledBackThreadList(), claims::physical_operator::Expander::AddIntoWorkingThreadList(), ExpanderTracker::addNewStageEndpoint(), Daemon::addRemoteCommand(), TableIDAllocator::allocate_unique_table_id(), MemoryChunkStore::applyChunk(), PortManager::applyPort(), BufferManager::applyStorageDedget(), bottomLayerCollecting::askForNextBlock(), DynamicBlockBuffer::atomicAppendNewBlock(), DynamicBlockBuffer::Iterator::atomicNextBlock(), bottomLayerCollecting::AtomicPopBlockStream(), IndexScanIterator::AtomicPopBlockStream(), claims::physical_operator::InOperator::AtomicPopFreeBlockStream(), claims::physical_operator::InOperator::AtomicPopFreeHtBlockStream(), claims::physical_operator::CombineTuple::AtomicPopRemainingBlock(), bottomLayerCollecting::atomicPopRemainingBlock(), claims::physical_operator::InOperator::AtomicPopRemainingBlock(), IndexScanIterator::atomicPopRemainingBlock(), bottomLayerCollecting::AtomicPushBlockStream(), IndexScanIterator::AtomicPushBlockStream(), claims::physical_operator::InOperator::AtomicPushFreeBlockStream(), claims::physical_operator::InOperator::AtomicPushFreeHtBlockStream(), claims::physical_operator::CombineTuple::AtomicPushRemainingBlock(), bottomLayerCollecting::atomicPushRemainingBlock(), claims::physical_operator::InOperator::AtomicPushRemainingBlock(), IndexScanIterator::atomicPushRemainingBlock(), BlockStreamBuffer::BlockStreamBuffer(), ExpanderTracker::callbackExpandedThread(), claims::physical_operator::Expander::ChildExhausted(), ChunkStorage::createChunkReaderIterator(), claims::physical_operator::Expander::CreateWorkingThread(), TableIDAllocator::decrease_table_id(), ExpanderTracker::deleteExpandedThreadStatus(), BlockStreamBuffer::Empty(), claims::physical_operator::Expander::ExpandedWork(), IDsGenerator::generateUniqueExchangeID(), BlockStreamBuffer::getBlock(), PartitionedBlockBuffer::getBlock(), BlockStreamBuffer::getBlockInBuffer(), PartitionedBlockBuffer::getBlockInBuffer(), PartitionedBlockBuffer::getBlockNumberOfPartitionInBuffer(), MemoryChunkStore::getChunk(), claims::physical_operator::PhysicalOperator::GetContext(), claims::physical_operator::Expander::GetDegreeOfParallelism(), Daemon::getExecutedResult(), InMemoryChunkReaderItetaor::getNextBlockAccessor(), DiskChunkReaderIteraror::getNextBlockAccessor(), HDFSChunkReaderIterator::getNextBlockAccessor(), DynamicBlockBuffer::getNumberOfBlocks(), ExpanderTracker::getPerformanceInfo(), claims::logical_operator::LogicalCrossJoin::GetPlanContext(), claims::logical_operator::LogicalSubquery::GetPlanContext(), claims::logical_operator::LogicalScan::GetPlanContext(), claims::logical_operator::LogicalProject::GetPlanContext(), claims::logical_operator::LogicalQueryPlanRoot::GetPlanContext(), claims::logical_operator::LogicalFilter::GetPlanContext(), claims::logical_operator::LogicalSort::GetPlanContext(), claims::logical_operator::LogicalEqualJoin::GetPlanContext(), claims::logical_operator::LogicalAggregation::GetPlanContext(), Daemon::getRemoteCommand(), IDsGenerator::getUniqueExpanderID(), Comparator::iniatilize(), claims::physical_operator::PhysicalOperator::InitContext(), BlockStreamBuffer::insertBlock(), PartitionedBlockBuffer::insertBlockToPartitionedList(), ExpanderTracker::isExpandedThreadCallBack(), BlockManager::loadFromHdfs(), CodeGenerator::lock(), ExchangeTracker::LogoutExchange(), ExpanderTracker::monitoringThread(), claims::physical_operator::CombineTuple::Next(), claims::physical_operator::PhysicalAggregation::Next(), claims::physical_operator::PhysicalSort::Next(), ChunkReaderIterator::nextBlock(), InMemoryChunkReaderItetaor::nextBlock(), DiskChunkReaderIteraror::nextBlock(), HDFSChunkReaderIterator::nextBlock(), claims::physical_operator::PhysicalSort::Open(), AllBlockInfo::put(), MemoryChunkStore::putChunk(), ExchangeTracker::RegisterExchange(), claims::physical_operator::PhysicalOperator::RegisterExpandedThreadToAllBarriers(), ExpanderTracker::registerNewExpandedThreadStatus(), ExpanderTracker::registerNewExpander(), claims::physical_operator::Expander::RemoveFromCalledBackThreadList(), claims::physical_operator::Expander::RemoveFromWorkingThreadList(), MemoryChunkStore::returnChunk(), PortManager::returnPort(), BufferManager::returnStorageBudget(), claims::physical_operator::Expander::Shrink(), claims::physical_operator::Expander::TerminateWorkingThread(), ExpanderTracker::unregisterExpander(), and MemoryChunkStore::updateChunkInfo().
void Lock::destroy () inline
References m.
void Lock::release () inline
References m.
Referenced by Daemon::addExecutedResult(), claims::physical_operator::Expander::AddIntoCalledBackThreadList(), claims::physical_operator::Expander::AddIntoWorkingThreadList(), ExpanderTracker::addNewStageEndpoint(), Daemon::addRemoteCommand(), TableIDAllocator::allocate_unique_table_id(), MemoryChunkStore::applyChunk(), PortManager::applyPort(), BufferManager::applyStorageDedget(), bottomLayerCollecting::askForNextBlock(), DynamicBlockBuffer::atomicAppendNewBlock(), DynamicBlockBuffer::Iterator::atomicNextBlock(), bottomLayerCollecting::AtomicPopBlockStream(), IndexScanIterator::AtomicPopBlockStream(), claims::physical_operator::InOperator::AtomicPopFreeBlockStream(), claims::physical_operator::InOperator::AtomicPopFreeHtBlockStream(), claims::physical_operator::CombineTuple::AtomicPopRemainingBlock(), bottomLayerCollecting::atomicPopRemainingBlock(), claims::physical_operator::InOperator::AtomicPopRemainingBlock(), IndexScanIterator::atomicPopRemainingBlock(), bottomLayerCollecting::AtomicPushBlockStream(), IndexScanIterator::AtomicPushBlockStream(), claims::physical_operator::InOperator::AtomicPushFreeBlockStream(), claims::physical_operator::InOperator::AtomicPushFreeHtBlockStream(), claims::physical_operator::CombineTuple::AtomicPushRemainingBlock(), bottomLayerCollecting::atomicPushRemainingBlock(), claims::physical_operator::InOperator::AtomicPushRemainingBlock(), IndexScanIterator::atomicPushRemainingBlock(), BlockStreamBuffer::BlockStreamBuffer(), ExpanderTracker::callbackExpandedThread(), claims::physical_operator::Expander::ChildExhausted(), ChunkStorage::createChunkReaderIterator(), claims::physical_operator::Expander::CreateWorkingThread(), TableIDAllocator::decrease_table_id(), ExpanderTracker::deleteExpandedThreadStatus(), BlockStreamBuffer::Empty(), claims::physical_operator::Expander::ExpandedWork(), IDsGenerator::generateUniqueExchangeID(), BlockStreamBuffer::getBlock(), PartitionedBlockBuffer::getBlock(), BlockStreamBuffer::getBlockInBuffer(), PartitionedBlockBuffer::getBlockInBuffer(), PartitionedBlockBuffer::getBlockNumberOfPartitionInBuffer(), MemoryChunkStore::getChunk(), claims::physical_operator::PhysicalOperator::GetContext(), claims::physical_operator::Expander::GetDegreeOfParallelism(), Daemon::getExecutedResult(), InMemoryChunkReaderItetaor::getNextBlockAccessor(), DiskChunkReaderIteraror::getNextBlockAccessor(), HDFSChunkReaderIterator::getNextBlockAccessor(), DynamicBlockBuffer::getNumberOfBlocks(), ExpanderTracker::getPerformanceInfo(), claims::logical_operator::LogicalCrossJoin::GetPlanContext(), claims::logical_operator::LogicalSubquery::GetPlanContext(), claims::logical_operator::LogicalScan::GetPlanContext(), claims::logical_operator::LogicalProject::GetPlanContext(), claims::logical_operator::LogicalQueryPlanRoot::GetPlanContext(), claims::logical_operator::LogicalFilter::GetPlanContext(), claims::logical_operator::LogicalSort::GetPlanContext(), claims::logical_operator::LogicalEqualJoin::GetPlanContext(), claims::logical_operator::LogicalAggregation::GetPlanContext(), Daemon::getRemoteCommand(), IDsGenerator::getUniqueExpanderID(), Comparator::iniatilize(), claims::physical_operator::PhysicalOperator::InitContext(), BlockStreamBuffer::insertBlock(), PartitionedBlockBuffer::insertBlockToPartitionedList(), ExpanderTracker::isExpandedThreadCallBack(), BlockManager::loadFromHdfs(), ExchangeTracker::LogoutExchange(), ExpanderTracker::monitoringThread(), claims::physical_operator::CombineTuple::Next(), claims::physical_operator::PhysicalAggregation::Next(), claims::physical_operator::PhysicalSort::Next(), ChunkReaderIterator::nextBlock(), InMemoryChunkReaderItetaor::nextBlock(), DiskChunkReaderIteraror::nextBlock(), HDFSChunkReaderIterator::nextBlock(), claims::physical_operator::PhysicalSort::Open(), AllBlockInfo::put(), MemoryChunkStore::putChunk(), ExchangeTracker::RegisterExchange(), claims::physical_operator::PhysicalOperator::RegisterExpandedThreadToAllBarriers(), ExpanderTracker::registerNewExpandedThreadStatus(), ExpanderTracker::registerNewExpander(), CodeGenerator::release(), claims::physical_operator::Expander::RemoveFromCalledBackThreadList(), claims::physical_operator::Expander::RemoveFromWorkingThreadList(), MemoryChunkStore::returnChunk(), PortManager::returnPort(), BufferManager::returnStorageBudget(), claims::physical_operator::Expander::Shrink(), claims::physical_operator::Expander::TerminateWorkingThread(), claims::physical_operator::PhysicalOperator::UnregisterExpandedThreadToAllBarriers(), ExpanderTracker::unregisterExpander(), and MemoryChunkStore::updateChunkInfo().
bool Lock::try_acquire () inline
References m.
Referenced by claims::physical_operator::Expander::CreateWorkingThread().
Member Data Documentation
pthread_mutex_t Lock::m private
Referenced by acquire(), destroy(), Lock(), release(), try_acquire(), and ~Lock().
The documentation for this class was generated from the following file:
utility/lock.h