My Project: claims::logical_operator::LogicalScan Class Reference
claims::logical_operator::LogicalScan Class Reference
Method description:This is the implementation of Scan operator in logical layer. Currently, we only choose the third of constructor functions. Through the method of LogicalScan, we can get data context and a physical operator.
#include <logical_scan.h>
Public Member Functions
LogicalScan (std::vector< Attribute > attribute_list)
LogicalScan (const TableID &)
LogicalScan (ProjectionDescriptor *projection, const float sample_rate_=1)
LogicalScan (const TableID &, const std::vector< unsigned > &selected_attribute_index_list)
PlanContext GetPlanContext ()
It can generate many projection. We need the smallest cost of projections, so we should choose the best one what we need with traversing scan_attribute_list_.
BlockStreamIteratorBase * GetPhysicalPlan (const unsigned &)
Set the value of class state and get instantiation of physical operator to transform logical operator. In the current implementation, all the attributes within the involved projection are read.
bool GetOptimalPhysicalPlan (Requirement requirement, PhysicalPlanDescriptor &physical_plan_descriptor, const unsigned &kBlock_size=4096 *1024)
Additional Inherited Members
Protected Member Functions inherited from claims::logical_operator::LogicalOperator
Schema * GetSchema (const std::vector< Attribute > &) const
Schema * GetSchema (const std::vector< Attribute > &, const std::vector< Attribute > &) const
std::vector< NodeID > GetInvolvedNodeID (const PlanPartitioner &) const
std::vector< NodeIP > ConvertNodeIDListToNodeIPList (const std::vector< NodeID > &) const
PhysicalPlanDescriptor GetBestPhysicalPlanDescriptor (const std::vector< PhysicalPlanDescriptor >) const
int GetIdInAttributeList (const std::vector< Attribute > &attributes, const Attribute &attribute) const
void set_operator_type (OperatorType operator_type)
Detailed Description
Method description:This is the implementation of Scan operator in logical layer. Currently, we only choose the third of constructor functions. Through the method of LogicalScan, we can get data context and a physical operator.
Member Function Documentation
bool claims::logical_operator::LogicalScan::GetOptimalPhysicalPlan (Requirement requirement, PhysicalPlanDescriptor & physical_plan_descriptor, const unsigned & block_size = 4096 * 1024) virtual
get the optimal Physical plan that meets the requirement.
Returns
true if find physical plan that meets the requirement and store the physical plan and its corresponding information in physical_plan_descriptor.
Currently, the join output size cannot be predicted due to the absence of data statistics. We just use the magic number as following
Reimplemented from claims::logical_operator::LogicalOperator.
References claims::logical_operator::PlanContext::GetAggregatedDatasize(), GetPlanContext(), and claims::logical_operator::Requirement::requireNetworkTransfer().
PlanContext claims::logical_operator::LogicalScan::GetPlanContext () virtual
It can generate many projection. We need the smallest cost of projections, so we should choose the best one what we need with traversing scan_attribute_list_.
build the PlanContext
Implements claims::logical_operator::LogicalOperator.
References ProjectionBinding::BindingEntireProjection(), and ProjectionDescriptor::getProjectionCost().
Referenced by GetOptimalPhysicalPlan().
The documentation for this class was generated from the following files:
logical_operator/logical_scan.h
logical_operator/logical_scan.cpp