My Project: claims::logical_operator::LogicalOperator Class Reference
claims::logical_operator::LogicalOperator Class Reference abstract
#include <logical_operator.h>
Public Member Functions
virtual PlanContext GetPlanContext ()=0
virtual BlockStreamIteratorBase * GetPhysicalPlan (const unsigned &)=0
virtual bool GetOptimalPhysicalPlan (Requirement requirement, PhysicalPlanDescriptor &physical_plan_descriptor, const unsigned &block_size=4096 *1024)
virtual void Print (int level=0) const =0
Protected Member Functions
Schema * GetSchema (const std::vector< Attribute > &) const
Schema * GetSchema (const std::vector< Attribute > &, const std::vector< Attribute > &) const
std::vector< NodeID > GetInvolvedNodeID (const PlanPartitioner &) const
std::vector< NodeIP > ConvertNodeIDListToNodeIPList (const std::vector< NodeID > &) const
PhysicalPlanDescriptor GetBestPhysicalPlanDescriptor (const std::vector< PhysicalPlanDescriptor >) const
int GetIdInAttributeList (const std::vector< Attribute > &attributes, const Attribute &attribute) const
void set_operator_type (OperatorType operator_type)
Detailed Description
LogicalOperator is the base class of all logical operator. GetPlanContext() aims at maintaining the property of the data after completing every operator of plan. the property contains the output attributes, partition key, cardinality and communication cost. GetPhysicalPlan() adds current physical operator into the whole plan, result into a plan tree.
Member Function Documentation
virtual bool claims::logical_operator::LogicalOperator::GetOptimalPhysicalPlan (Requirement requirement, PhysicalPlanDescriptor & physical_plan_descriptor, const unsigned & block_size = 4096 * 1024) inline virtual
get the optimal Physical plan that meets the requirement.
Returns
true if find physical plan that meets the requirement and store the physical plan and its corresponding information in physical_plan_descriptor.
Reimplemented in claims::logical_operator::LogicalSort, claims::logical_operator::LogicalEqualJoin, claims::logical_operator::LogicalQueryPlanRoot, claims::logical_operator::LogicalFilter, claims::logical_operator::LogicalProject, claims::logical_operator::LogicalScan, LogicalCSBIndexBuilding, and LogicalIndexScan.
Referenced by claims::logical_operator::LogicalFilter::GetOptimalPhysicalPlan(), and claims::logical_operator::LogicalQueryPlanRoot::GetOptimalPhysicalPlan().
virtual BlockStreamIteratorBase* claims::logical_operator::LogicalOperator::GetPhysicalPlan (const unsigned &) pure virtual
generate the iterator tree based on the computed plan_context. Hence, this function can only be called after the calling of GetPlanContext().
Implemented in claims::logical_operator::LogicalEqualJoin, claims::logical_operator::LogicalSort, claims::logical_operator::LogicalAggregation, claims::logical_operator::LogicalFilter, claims::logical_operator::LogicalQueryPlanRoot, claims::logical_operator::LogicalProject, claims::logical_operator::LogicalScan, claims::logical_operator::LogicalCrossJoin, LogicalCSBIndexBuilding, and LogicalIndexScan.
Referenced by claims::logical_operator::LogicalProject::GetPhysicalPlan(), claims::logical_operator::LogicalQueryPlanRoot::GetPhysicalPlan(), claims::logical_operator::LogicalFilter::GetPhysicalPlan(), claims::logical_operator::LogicalAggregation::GetPhysicalPlan(), claims::logical_operator::LogicalSort::GetPhysicalPlan(), and claims::logical_operator::LogicalEqualJoin::GetPhysicalPlan().
virtual PlanContext claims::logical_operator::LogicalOperator::GetPlanContext () pure virtual
get the plan context which describes the property of the data after having executed corresponding operator.
Implemented in claims::logical_operator::LogicalEqualJoin, claims::logical_operator::LogicalAggregation, claims::logical_operator::LogicalSort, claims::logical_operator::LogicalQueryPlanRoot, claims::logical_operator::LogicalFilter, claims::logical_operator::LogicalProject, claims::logical_operator::LogicalScan, claims::logical_operator::LogicalCrossJoin, LogicalCSBIndexBuilding, and LogicalIndexScan.
Referenced by claims::logical_operator::LogicalCrossJoin::GetPhysicalPlan(), claims::logical_operator::LogicalProject::GetPhysicalPlan(), claims::logical_operator::LogicalAggregation::GetPhysicalPlan(), claims::logical_operator::LogicalEqualJoin::GetPhysicalPlan(), claims::logical_operator::LogicalCrossJoin::GetPlanContext(), claims::logical_operator::LogicalProject::GetPlanContext(), claims::logical_operator::LogicalFilter::GetPlanContext(), claims::logical_operator::LogicalQueryPlanRoot::GetPlanContext(), claims::logical_operator::LogicalSort::GetPlanContext(), claims::logical_operator::LogicalAggregation::GetPlanContext(), and claims::logical_operator::LogicalEqualJoin::GetPlanContext().
The documentation for this class was generated from the following files:
logical_operator/logical_operator.h
logical_operator/logical_operator.cpp