Claims: OperateDatetime Class Reference
OperateDatetime Class Reference
#include <data_type.h>
Public Member Functions
OperateDatetime (bool _nullable=true)
void assignment (const void *const &src, void *const &desc) const
std::string toString (void *value)
void toValue (void *target, const char *string)
bool equal (const void *const &a, const void *const &b) const
bool less (const void *&a, const void *&b) const
bool greate (const void *&a, const void *&b) const
int compare (const void *a, const void *b) const
void add (void *target, void *increment)
void multiple (void *target, void *increment)
fun GetADDFunction ()
fun GetMINFunction ()
fun GetMAXFunction ()
fun GetIncreateByOneFunction ()
fun GetAVGFunction ()
unsigned getPartitionValue (const void *key, const PartitionFunction *partition_function) const
unsigned getPartitionValue (const void *key, const unsigned long &mod) const
unsigned getPartitionValue (const void *key) const
Operate * duplicateOperator () const
bool setNull (void *value)
bool isNull (void *value) const
Public Member Functions inherited from Operate
Operate (bool _nullable=true)
virtual ~Operate ()
void ass (void *src, void *desc)
Additional Inherited Members
Public Attributes inherited from Operate
void(* assign)(const void *const &src, void *const &desc)
bool nullable
Constructor & Destructor Documentation
OperateDatetime::OperateDatetime (bool _nullable = true) inline
Member Function Documentation
void OperateDatetime::add (void * target, void * increment) inline virtual
Implements Operate.
References ADD_FUNC< ptime * >().
void OperateDatetime::assignment (const void *const & src, void *const & desc) const inline virtual
Implements Operate.
int OperateDatetime::compare (const void * a, const void * b) const inline virtual
Implements Operate.
Operate* OperateDatetime::duplicateOperator () const inline virtual
Implements Operate.
bool OperateDatetime::equal (const void *const & a, const void *const & b) const inline virtual
Implements Operate.
fun OperateDatetime::GetADDFunction () inline virtual
Implements Operate.
References ADD_FUNC< ptime * >().
fun OperateDatetime::GetAVGFunction () inline virtual
Implements Operate.
fun OperateDatetime::GetIncreateByOneFunction () inline virtual
Implements Operate.
fun OperateDatetime::GetMAXFunction () inline virtual
Implements Operate.
fun OperateDatetime::GetMINFunction () inline virtual
Implements Operate.
unsigned OperateDatetime::getPartitionValue (const void * key, const PartitionFunction * partition_function) const inline virtual
Implements Operate.
unsigned OperateDatetime::getPartitionValue (const void * key, const unsigned long & mod) const inline virtual
Implements Operate.
References hash_value().
unsigned OperateDatetime::getPartitionValue (const void * key) const inline virtual
Implements Operate.
References hash_value().
bool OperateDatetime::greate (const void *& a, const void *& b) const inline virtual
Implements Operate.
bool OperateDatetime::isNull (void * value) const inline virtual
Implements Operate.
bool OperateDatetime::less (const void *& a, const void *& b) const inline virtual
Implements Operate.
void OperateDatetime::multiple (void * target, void * increment) inline virtual
Implements Operate.
bool OperateDatetime::setNull (void * value) inline virtual
Implements Operate.
References NULL_DATETIME.
std::string OperateDatetime::toString (void * value) inline virtual
Implements Operate.
void OperateDatetime::toValue (void * target, const char * string) inline virtual
Implements Operate.
The documentation for this class was generated from the following file:
common/data_type.h