Claims: decimal::NValue Class Reference
decimal::NValue Class Reference
#include <NValue.hpp>
Public Member Functions
NValue ()
void createDecimalFromString (const std::string &txt)
std::string createStringFromDecimal (unsigned number_of_fractinal_digits=12) const
NValue opMultiplyDecimals (const NValue &lhs, const NValue &rhs) const
NValue opDivideDecimals (const NValue lhs, const NValue rhs) const
bool isNull () const
void serializeToExport (ExportSerializeOutput &, void *para=0) const
NValue op_add (const NValue rhs) const
NValue op_subtract (const NValue rhs) const
NValue op_multiply (const NValue rhs) const
NValue op_divide (const NValue rhs) const
NValue op_max (const NValue rhs) const
NValue op_min (const NValue rhs) const
bool op_equals (const NValue rhs) const
bool op_not_equals (const NValue rhs) const
bool op_less (const NValue rhs) const
bool op_less_equals (const NValue rhs) const
bool op_great (const NValue rhs) const
bool op_great_equals (const NValue rhs) const
int compare (const NValue rhs) const
TTInt & getDecimal ()
const TTInt & getDecimal () const
NValue opAddDecimals (const NValue lhs, const NValue rhs) const
NValue opSubtractDecimals (const NValue lhs, const NValue rhs) const
int compareDecimalValue (const NValue rhs) const
Static Public Member Functions
static NValue getDecimalValueFromString (const std::string &value)
static NValue getDecimalValue (TTInt value)
Public Attributes
char m_data [16]
Static Public Attributes
static const int64_t kMaxScaleFactor = 1000000000000
static const uint16_t kMaxDecScale = 12
static TTInt s_maxDecimalValue
static TTInt s_minDecimalValue
Constructor & Destructor Documentation
decimal::NValue::NValue () inline
Member Function Documentation
int decimal::NValue::compare (const NValue rhs) const inline
int decimal::NValue::compareDecimalValue (const NValue rhs) const inline
Get the type of the value. This information is private to prevent code outside of NValue from branching based on the type of a value.
References getDecimal(), VALUE_COMPARE_EQUAL, VALUE_COMPARE_GREATERTHAN, and VALUE_COMPARE_LESSTHAN.
void decimal::NValue::createDecimalFromString (const std::string & txt)
set a decimal value from a serialized representation
Check for invalid characters
References ttmath::Int< value_size >::SetSign().
Referenced by getDecimalValueFromString(), and TEST_F().
std::string decimal::NValue::createStringFromDecimal (unsigned number_of_fractinal_digits = 12) const
Serialize sign and value using radix point (no exponent).
References ttmath::Int< value_size >::ChangeSign(), ttmath::Int< value_size >::IsSign(), and ttmath::Int< value_size >::ToString().
Referenced by opAddDecimals(), opDivideDecimals(), opMultiplyDecimals(), opSubtractDecimals(), test_add(), and test_multiple().
TTInt& decimal::NValue::getDecimal () inline
Referenced by compareDecimalValue(), getDecimalValue(), opAddDecimals(), opDivideDecimals(), opMultiplyDecimals(), and opSubtractDecimals().
const TTInt& decimal::NValue::getDecimal () const inline
static NValue decimal::NValue::getDecimalValue (TTInt value) inline static
References getDecimal().
static NValue decimal::NValue::getDecimalValueFromString (const std::string & value) inline static
References createDecimalFromString().
bool decimal::NValue::isNull () const inline
References OBJECT_NULL_BIT, and ttmath::Int< value_size >::SetMin().
Referenced by opAddDecimals(), opDivideDecimals(), opMultiplyDecimals(), and opSubtractDecimals().
NValue decimal::NValue::op_add (const NValue rhs) const inline
Referenced by add_in_same_type().
NValue decimal::NValue::op_divide (const NValue rhs) const inline
bool decimal::NValue::op_equals (const NValue rhs) const inline
References compare().
Referenced by compare_equal_in_same_type(), claims::common::decimal_to_boolean(), decimal_to_boolean(), great< NValue *, NValue * >(), OperateDecimal::greate(), OperateDecimal::less(), and NValueEqual().
bool decimal::NValue::op_great (const NValue rhs) const inline
References compare().
Referenced by compare_great_in_same_type(), and NValueGreat().
bool decimal::NValue::op_great_equals (const NValue rhs) const inline
References compare().
Referenced by compare_great_equal_in_same_type(), and NValueGreatEqual().
bool decimal::NValue::op_less (const NValue rhs) const inline
References compare().
Referenced by compare_less_in_same_type(), and NValueLess().
bool decimal::NValue::op_less_equals (const NValue rhs) const inline
References compare().
Referenced by compare_less_equal_in_same_type(), and NValueLessEqual().
NValue decimal::NValue::op_max (const NValue rhs) const inline
References compare().
Referenced by great< NValue *, NValue * >().
NValue decimal::NValue::op_min (const NValue rhs) const inline
References compare().
Referenced by OperateDecimal::greate(), and OperateDecimal::less().
NValue decimal::NValue::op_multiply (const NValue rhs) const inline
Referenced by muls_in_same_type().
bool decimal::NValue::op_not_equals (const NValue rhs) const inline
References compare().
Referenced by compare_not_equal_in_same_type(), get_boolean_expr(), and NValueNotEqual().
NValue decimal::NValue::op_subtract (const NValue rhs) const inline
Referenced by mins_in_same_type().
NValue decimal::NValue::opAddDecimals (const NValue lhs, const NValue rhs) const inline
References createStringFromDecimal(), getDecimal(), isNull(), and ttmath::Int< value_size >::SetMin().
NValue decimal::NValue::opDivideDecimals (const NValue lhs, const NValue rhs) const
References createStringFromDecimal(), ttmath::Int< value_size >::Div(), ttmath::Int< value_size >::FromInt(), getDecimal(), isNull(), ttmath::Int< value_size >::SetMin(), and ttmath::Int< value_size >::ToString().
NValue decimal::NValue::opMultiplyDecimals (const NValue & lhs, const NValue & rhs) const
References createStringFromDecimal(), ttmath::Int< value_size >::FromInt(), getDecimal(), isNull(), ttmath::Int< value_size >::SetMin(), and ttmath::Int< value_size >::ToString().
NValue decimal::NValue::opSubtractDecimals (const NValue lhs, const NValue rhs) const inline
References createStringFromDecimal(), getDecimal(), isNull(), and ttmath::Int< value_size >::SetMin().
void decimal::NValue::serializeToExport (ExportSerializeOutput & io, void * para = 0) const inline
References decimal::ExportSerializeOutput::writeBinaryString().
Member Data Documentation
const uint16_t decimal::NValue::kMaxDecScale = 12 static
const int64_t decimal::NValue::kMaxScaleFactor = 1000000000000 static
char decimal::NValue::m_data[16]
16 bytes of storage for NValue data.
TTInt decimal::NValue::s_maxDecimalValue static
TTInt decimal::NValue::s_minDecimalValue static
The documentation for this class was generated from the following files:
common/types/NValue.hpp
common/types/NValue.cpp