Claims: Block Class Reference
Block Class Reference
#include <Block.h>
Public Member Functions
Block (unsigned BlockSize)
Block (const Block &block)
Block (const unsigned &size, const void *start)
virtual ~Block ()
void * getBlock () const
void setBlock (void *)
unsigned getsize () const
unsigned setsize (const unsigned &size)
bool isIsReference () const
void setIsReference (bool isReference)
Protected Attributes
unsigned BlockSize
char * start
Private Attributes
bool isReference_
Constructor & Destructor Documentation
Block::Block (unsigned BlockSize)
References allocate, and start.
Block::Block (const Block & block)
References BlockSize, isReference_, and start.
Block::Block (const unsigned & size, const void * start)
Block::~Block () virtual
References allocate, isReference_, and start.
Referenced by DiskChunkReaderIteraror::~DiskChunkReaderIteraror(), and HDFSChunkReaderIterator::~HDFSChunkReaderIterator().
Member Function Documentation
void * Block::getBlock () const
References start.
Referenced by HdfsLoader::append(), BlockStreamFix::constructFromBlock(), BlockStreamVar::constructFromBlock(), BlockContainer::copy(), BlockStreamFix::createBlockAndDeepCopy(), BlockStreamFix::deepCopy(), BlockStreamFix::deserialize(), generateVariableData_test(), ChunkReaderIterator::InMemeryBlockAccessor::getBlock(), claims::physical_operator::ExchangeSenderMaterialized::GetBlockFromFile(), PartitionedBlockBuffer::getBlockInPartitionedBlockList(), PartitionedBlockBuffer::insertBlockToPartitionedList(), HdfsLoader::insertRecords(), HdfsLoader::load(), claims::physical_operator::ExchangeSenderMaterialized::Materialize(), DynamicBlockBuffer::Iterator::nextBlock(), DiskChunkReaderIteraror::nextBlock(), HDFSChunkReaderIterator::nextBlock(), claims::physical_operator::PhysicalFilter::ProcessInLogic(), claims::physical_operator::ExchangeMerger::Receiver(), claims::physical_operator::ExchangeSenderMaterialized::Send(), claims::physical_operator::ExchangeSenderPipeline::Sender(), BlockStreamFix::serialize(), BlockStreamVar::serialize(), ClientResponse::setDataBlock(), and BlockStreamVar::toDisk().
unsigned Block::getsize () const
References BlockSize.
Referenced by HdfsLoader::append(), BlockStreamFix::constructFromBlock(), BlockStreamVar::constructFromBlock(), BlockContainer::copy(), BlockStreamFix::deepCopy(), BlockStreamFix::deserialize(), claims::physical_operator::ExchangeSenderMaterialized::GetBlockFromFile(), PartitionedBlockBuffer::getBlockInPartitionedBlockList(), BlockContainer::GetMaxSize(), BlockContainer::GetRestSize(), BlockContainer::IncreaseActualSize(), PartitionedBlockBuffer::insertBlockToPartitionedList(), HdfsLoader::insertRecords(), HdfsLoader::load(), claims::physical_operator::ExchangeSenderMaterialized::Materialize(), DiskChunkReaderIteraror::nextBlock(), claims::physical_operator::ExchangeSenderMaterialized::Send(), BlockStreamFix::serialize(), BlockStreamVar::serialize(), and ClientResponse::setDataBlock().
bool Block::isIsReference () const inline
References isReference_.
Referenced by BlockStreamFix::createBlockAndDeepCopy(), and BlockStreamBuffer::insertBlock().
void Block::setBlock (void * addr)
References start.
Referenced by ChunkReaderIterator::InMemeryBlockAccessor::getBlock().
void Block::setIsReference (bool isReference)
References isReference_, and start.
Referenced by ChunkReaderIterator::InMemeryBlockAccessor::getBlock().
unsigned Block::setsize (const unsigned & size)
References BlockSize.
Member Data Documentation
unsigned Block::BlockSize protected
Referenced by Block(), BlockStreamFix::constructFromBlock(), BlockStreamVar::constructFromBlock(), BlockStreamFix::copyBlock(), BlockStreamFix::createBlockAndDeepCopy(), BlockStreamFix::deepCopy(), BlockStreamFix::deserialize(), BlockStreamFix::getBlockCapacityInTuples(), BlockStreamFix::getSerializedBlockSize(), getsize(), BlockStreamVar::getTuple(), BlockStreamFix::serialize(), BlockStreamVar::serialize(), setsize(), and BlockStreamFix::switchBlock().
bool Block::isReference_ private
Referenced by Block(), isIsReference(), setIsReference(), and ~Block().
char* Block::start protected
Referenced by Block(), BlockStreamFix::BlockStreamFix(), BlockStreamVar::BlockStreamVar(), BlockStreamFix::constructFromBlock(), BlockStreamVar::constructFromBlock(), BlockStreamFix::copyBlock(), BlockStreamFix::deepCopy(), BlockStreamFix::deserialize(), BlockStreamFix::Empty(), getBlock(), BlockStreamFix::getBlockDataAddress(), BlockStreamVar::getTuple(), BlockStreamFix::getTuplesInBlock(), BlockStreamVar::insert(), BlockStreamFix::serialize(), BlockStreamVar::serialize(), setBlock(), BlockStreamFix::setEmpty(), setIsReference(), BlockStreamFix::switchBlock(), and ~Block().
The documentation for this class was generated from the following files:
common/Block/Block.h
common/Block/Block.cpp