Claims: AttributeComparator Class Reference
AttributeComparator Class Reference
#include <AttributeComparator.h>
Public Member Functions
AttributeComparator (column_type x, column_type y, Comparator::comparison c, unsigned index, void *value)
AttributeComparator (column_type x, Comparator::comparison c, unsigned index, void *value)
AttributeComparator (const AttributeComparator &c_a)
AttributeComparator ()
~AttributeComparator ()
bool filter (void *x) const __attribute__((always_inline))
unsigned get_index () const
void * get_value () const
Public Member Functions inherited from Comparator
Comparator (column_type x, column_type b, Comparator::comparison c)
Comparator ()
Comparator (const Comparator &r)
virtual ~Comparator ()
comparison getCompareType () const
Protected Attributes
void * value_
unsigned index
Protected Attributes inherited from Comparator
Pair pair
comparison compareType
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::vector< char > valuebytes
Friends
class FilterIterator
class boost::serialization::access
Additional Inherited Members
Public Types inherited from Comparator
enum comparison {
L, LEQ, EQ, NEQ,
G, GEQ
}
Public Attributes inherited from Comparator
bool(* compare)(const void *, const void *)
Constructor & Destructor Documentation
AttributeComparator::AttributeComparator (column_type x, column_type y, Comparator::comparison c, unsigned index, void * value)
References Operate::assignment(), cacheline_size, Comparator::compare, column_type::get_length(), column_type::operate, and value_.
AttributeComparator::AttributeComparator (column_type x, Comparator::comparison c, unsigned index, void * value)
References Operate::assignment(), cacheline_size, Comparator::compare, column_type::get_length(), column_type::operate, and value_.
AttributeComparator::AttributeComparator (const AttributeComparator & c_a)
References Operate::assignment(), cacheline_size, Comparator::compare, column_type::get_length(), index, column_type::operate, Comparator::pair, Comparator::Pair::second, and value_.
AttributeComparator::AttributeComparator () inline
AttributeComparator::~AttributeComparator ()
References value_.
Member Function Documentation
bool AttributeComparator::filter (void * x) const inline
References Comparator::compare, and value_.
Referenced by filter_test().
unsigned AttributeComparator::get_index () const inline
References index.
void* AttributeComparator::get_value () const inline
References value_.
template<class Archive > void AttributeComparator::serialize (Archive & ar, const unsigned int version) inline private
References cacheline_size, Comparator::compare, column_type::get_length(), index, Comparator::pair, Comparator::Pair::second, value_, and valuebytes.
Friends And Related Function Documentation
friend class boost::serialization::access friend
friend class FilterIterator friend
Member Data Documentation
unsigned AttributeComparator::index protected
Referenced by AttributeComparator(), get_index(), and serialize().
void* AttributeComparator::value_ protected
Referenced by AttributeComparator(), filter(), get_value(), serialize(), and ~AttributeComparator().
std::vector<char> AttributeComparator::valuebytes private
a kind of ugly here. Because of the length of the value is unknown, we first store the value into the vector and then serialize the vector. TODO:
Referenced by serialize().
The documentation for this class was generated from the following files:
common/AttributeComparator.h
common/AttributeComparator.cpp