My Project: claims::logical_operator::LogicalCrossJoin Class Reference
claims::logical_operator::LogicalCrossJoin Class Reference
Public Member Functions
LogicalCrossJoin (LogicalOperator *left_child, LogicalOperator *right_child)
PlanContext GetPlanContext ()
Method description: return the output of the plan context of the dedicated operator.
BlockStreamIteratorBase * GetPhysicalPlan (const unsigned &blocksize)
Method description: get the sub physical execution plan of the current local operator.
void Print (int level=0) const
Public Member Functions inherited from claims::logical_operator::LogicalOperator
virtual bool GetOptimalPhysicalPlan (Requirement requirement, PhysicalPlanDescriptor &physical_plan_descriptor, const unsigned &block_size=4096 *1024)
Protected Types
enum JoinPolicy { kUninitialized, kLeftBroadcast, kRightBroadcast, kLocalJoin }
Protected Member Functions
int get_join_policy_ ()
Method description: get the decided join police.
Protected Member Functions inherited from claims::logical_operator::LogicalOperator
Schema * GetSchema (const std::vector< Attribute > &) const
Schema * GetSchema (const std::vector< Attribute > &, const std::vector< Attribute > &) const
std::vector< NodeID > GetInvolvedNodeID (const PlanPartitioner &) const
std::vector< NodeIP > ConvertNodeIDListToNodeIPList (const std::vector< NodeID > &) const
PhysicalPlanDescriptor GetBestPhysicalPlanDescriptor (const std::vector< PhysicalPlanDescriptor >) const
int GetIdInAttributeList (const std::vector< Attribute > &attributes, const Attribute &attribute) const
void set_operator_type (OperatorType operator_type)
Member Enumeration Documentation
enum claims::logical_operator::LogicalCrossJoin::JoinPolicy protected
The enum JoinPolicy is to enumerate the join policy used in the Cartesian product, it includes: KLocalJoin: local join which joined on the local node leftbroadcast: which broadcast the left table to the nodes which contains the partitions of the right table rightbroadcast: which broadcast the right table to the nodes which contains the partitions of the left table
Member Function Documentation
int claims::logical_operator::LogicalCrossJoin::get_join_policy_ () protected
Method description: get the decided join police.
Parameters
@return error no or the decided join police in the cross join
(additional)
BlockStreamIteratorBase * claims::logical_operator::LogicalCrossJoin::GetPhysicalPlan (const unsigned & block_size) virtual
Method description: get the sub physical execution plan of the current local operator.
Parameters
@return
(additional)
Implements claims::logical_operator::LogicalOperator.
References GetPlanContext(), and claims::logical_operator::LogicalOperator::GetPlanContext().
PlanContext claims::logical_operator::LogicalCrossJoin::GetPlanContext () virtual
Method description: return the output of the plan context of the dedicated operator.
Parameters
@return
(additional)
Implements claims::logical_operator::LogicalOperator.
References claims::logical_operator::PlanContext::GetAggregatedDatasize(), and claims::logical_operator::LogicalOperator::GetPlanContext().
Referenced by GetPhysicalPlan().
The documentation for this class was generated from the following files:
logical_operator/logical_cross_join.h
logical_operator/logical_cross_join.cpp