Claims: PartitionFunctionFactory Class Reference
PartitionFunctionFactory Class Reference
#include <hash.h>
Static Public Member Functions
static PartitionFunction * createGeneralModuloFunction (const int &range, const int &min=0, const int &skipbits=0)
static PartitionFunction * createModuloFunction (const int &range, const int &min=0, const int &skipbits=0)
static PartitionFunction * createUniformRangeHashFunction (const int &range, const int &min, const int &max)
static PartitionFunction * createRoundRobinPartitionHashFunction (int range)
static PartitionFunction * createBoostHashFunction (const int &range)
Member Function Documentation
static PartitionFunction* PartitionFunctionFactory::createBoostHashFunction (const int & range) inline static
Referenced by claims::logical_operator::LogicalEqualJoin::DecideOutputDataflowProperty(), fill_basic_hash_table(), claims::logical_operator::LogicalScan::GetOptimalPhysicalPlan(), claims::physical_operator::InOperator::Open(), claims::physical_operator::ExchangeSenderPipeline::Open(), claims::physical_operator::PhysicalHashJoin::Open(), and projection_scan().
PartitionFunction * PartitionFunctionFactory::createGeneralModuloFunction (const int & range, const int & min = 0, const int & skipbits = 0) static
Referenced by TableDescriptor::createHashPartitionedProjection(), TableDescriptor::createHashPartitionedProjectionOnAllAttribute(), and claims::physical_operator::PhysicalAggregation::Open().
PartitionFunction * PartitionFunctionFactory::createModuloFunction (const int & range, const int & min = 0, const int & skipbits = 0) static
PartitionFunction * PartitionFunctionFactory::createRoundRobinPartitionHashFunction (int range) static
PartitionFunction * PartitionFunctionFactory::createUniformRangeHashFunction (const int & range, const int & min, const int & max) static
The documentation for this class was generated from the following files:
common/hash.h
common/hash.cpp