Claims: OperateULong Class Reference
OperateULong Class Reference
#include <data_type.h>
Public Member Functions
OperateULong (bool _nullable=true)
~OperateULong ()
void assignment (const void *const &src, void *const &desc) const
std::string toString (void *value)
void toValue (void *target, const char *string)
bool equal (const void *const &a, const void *const &b) const
bool less (const void *&a, const void *&b) const
bool greate (const void *&a, const void *&b) const
int compare (const void *a, const void *b) const
void add (void *target, void *increment)
void multiple (void *target, void *increment)
fun GetADDFunction ()
fun GetMINFunction ()
fun GetMAXFunction ()
fun GetIncreateByOneFunction ()
fun GetAVGFunction ()
unsigned getPartitionValue (const void *key, const PartitionFunction *partition_function) const
unsigned getPartitionValue (const void *key) const
unsigned getPartitionValue (const void *key, const unsigned long &mod) const
Operate * duplicateOperator () const
bool setNull (void *value)
bool isNull (void *value) const
Public Member Functions inherited from Operate
Operate (bool _nullable=true)
virtual ~Operate ()
void ass (void *src, void *desc)
Additional Inherited Members
Public Attributes inherited from Operate
void(* assign)(const void *const &src, void *const &desc)
bool nullable
Constructor & Destructor Documentation
OperateULong::OperateULong (bool _nullable = true) inline
OperateULong::~OperateULong () inline
Member Function Documentation
void OperateULong::add (void * target, void * increment) inline virtual
Implements Operate.
void OperateULong::assignment (const void *const & src, void *const & desc) const inline virtual
Implements Operate.
int OperateULong::compare (const void * a, const void * b) const inline virtual
Implements Operate.
Operate* OperateULong::duplicateOperator () const inline virtual
Implements Operate.
bool OperateULong::equal (const void *const & a, const void *const & b) const inline virtual
Implements Operate.
fun OperateULong::GetADDFunction () inline virtual
Implements Operate.
fun OperateULong::GetAVGFunction () inline virtual
Implements Operate.
fun OperateULong::GetIncreateByOneFunction () inline virtual
Implements Operate.
fun OperateULong::GetMAXFunction () inline virtual
Implements Operate.
fun OperateULong::GetMINFunction () inline virtual
Implements Operate.
unsigned OperateULong::getPartitionValue (const void * key, const PartitionFunction * partition_function) const inline virtual
Implements Operate.
References PartitionFunction::get_partition_value().
unsigned OperateULong::getPartitionValue (const void * key) const inline virtual
Implements Operate.
References hash_value().
unsigned OperateULong::getPartitionValue (const void * key, const unsigned long & mod) const inline virtual
Implements Operate.
References hash_value().
bool OperateULong::greate (const void *& a, const void *& b) const inline virtual
Implements Operate.
bool OperateULong::isNull (void * value) const inline virtual
Implements Operate.
References NULL_U_LONG.
bool OperateULong::less (const void *& a, const void *& b) const inline virtual
Implements Operate.
void OperateULong::multiple (void * target, void * increment) inline virtual
Implements Operate.
bool OperateULong::setNull (void * value) inline virtual
Implements Operate.
References NULL_U_LONG.
std::string OperateULong::toString (void * value) inline virtual
Implements Operate.
References NULL_U_LONG.
void OperateULong::toValue (void * target, const char * string) inline virtual
Implements Operate.
References NULL_U_LONG.
The documentation for this class was generated from the following file:
common/data_type.h