Claims: BlockManagerMaster Class Reference
BlockManagerMaster Class Reference
#include <BlockManagerMaster.h>
Classes
struct BlockInfo
class BlockManagerMasterActor
Public Types
enum storageLevel { memory, disk }
Public Member Functions
virtual ~BlockManagerMaster ()
void initialize ()
void testForPoc ()
bool SendBindingMessage (const PartitionID &, const unsigned &number_of_chunks, const StorageLevel &, const NodeID &) const
bool SendUnbindingMessage (const PartitionID &partition_id, NodeID &target) const
Static Public Member Functions
static BlockManagerMaster * getInstance ()
Private Member Functions
BlockManagerMaster ()
std::string generateSlaveActorName (const NodeID &) const
Private Attributes
AllBlockInfo * abi_
BlanceMatcher * bm_
Theron::Framework * framework_
BlockManagerMasterActor * actor_
Logging * logging_
Static Private Attributes
static BlockManagerMaster * master_ =0
Member Enumeration Documentation
enum BlockManagerMaster::storageLevel
Enumerator
memory
disk
Constructor & Destructor Documentation
BlockManagerMaster::~BlockManagerMaster () virtual
References actor_, framework_, logging_, and master_.
BlockManagerMaster::BlockManagerMaster () private
References actor_, framework_, Environment::getInstance(), and logging_.
Referenced by getInstance().
Member Function Documentation
std::string BlockManagerMaster::generateSlaveActorName (const NodeID & node_id) const private
Referenced by SendBindingMessage(), and SendUnbindingMessage().
static BlockManagerMaster* BlockManagerMaster::getInstance () inline static
References BlockManagerMaster(), and master_.
Referenced by ProjectionBinding::BindingEntireProjection(), Environment::initializeStorage(), ProjectionBinding::UnbindingEntireProjection(), and Partitioner::UpdatePartitionWithNumberOfChunksToBlockManager().
void BlockManagerMaster::initialize ()
References abi_, AllBlockInfo::getInstance(), and testForPoc().
Referenced by Environment::initializeStorage().
bool BlockManagerMaster::SendBindingMessage (const PartitionID & partition_id, const unsigned & number_of_chunks, const StorageLevel & desirable_storage_level, const NodeID & target) const
References Logging::elog(), framework_, generateSlaveActorName(), NodeTracker::GetInstance(), Environment::getInstance(), Logging::log(), logging_, and TimeOutReceiver::TimeOutWait().
Referenced by ProjectionBinding::BindingEntireProjection(), and Partitioner::UpdatePartitionWithNumberOfChunksToBlockManager().
bool BlockManagerMaster::SendUnbindingMessage (const PartitionID & partition_id, NodeID & target) const
References Logging::elog(), framework_, generateSlaveActorName(), NodeTracker::GetInstance(), Environment::getInstance(), Logging::log(), logging_, and TimeOutReceiver::TimeOutWait().
Referenced by ProjectionBinding::UnbindingEntireProjection().
void BlockManagerMaster::testForPoc ()
References bm_, BlanceMatcher::getInstance(), and BlanceMatcher::projectsInput().
Referenced by initialize().
Member Data Documentation
AllBlockInfo* BlockManagerMaster::abi_ private
Referenced by initialize().
BlockManagerMasterActor* BlockManagerMaster::actor_ private
Referenced by BlockManagerMaster(), and ~BlockManagerMaster().
BlanceMatcher* BlockManagerMaster::bm_ private
Referenced by testForPoc().
Theron::Framework* BlockManagerMaster::framework_ private
Referenced by BlockManagerMaster(), SendBindingMessage(), SendUnbindingMessage(), and ~BlockManagerMaster().
Logging* BlockManagerMaster::logging_ private
Referenced by BlockManagerMaster(), SendBindingMessage(), SendUnbindingMessage(), and ~BlockManagerMaster().
BlockManagerMaster * BlockManagerMaster::master_ =0 static private
Referenced by getInstance(), and ~BlockManagerMaster().
The documentation for this class was generated from the following files:
storage/BlockManagerMaster.h
storage/BlockManagerMaster.cpp