Claims: CCSBLeafNodeGroup< T > Class Template Reference
CCSBLeafNodeGroup< T > Class Template Reference
#include <CSBPlusTree.h>
Public Member Functions
CCSBLeafNodeGroup ()
CCSBLeafNodeGroup (unsigned n)
~CCSBLeafNodeGroup ()
CCSBNodeGroup< T > * getHeaderNG ()
void setHeaderNG (CCSBNodeGroup< T > *header)
CCSBNodeGroup< T > * getTailerNG ()
void setTailerNG (CCSBNodeGroup< T > *tailer)
bool setUsedNodes (unsigned n)
CCSBNode< T > * getNode (unsigned i)
void setNode (unsigned i, CCSBNode< T > *node)
void DeleteChildren ()
bool serialize (FILE *filename)
bool deserialize (FILE *filename)
Public Member Functions inherited from CCSBNodeGroup< T >
CCSBNodeGroup ()
CCSBNodeGroup (unsigned n)
~CCSBNodeGroup ()
unsigned getUsedNodes ()
void nodeCountIncrement ()
virtual bool Insert (unsigned node_off, T key)
Public Attributes
CCSBNode< T > ** leaf_nodes
CCSBNodeGroup< T > * p_header
CCSBNodeGroup< T > * p_tailer
Public Attributes inherited from CCSBNodeGroup< T >
unsigned used_nodes
Constructor & Destructor Documentation
template<typename T> CCSBLeafNodeGroup< T >::CCSBLeafNodeGroup () inline
template<typename T > CCSBLeafNodeGroup< T >::CCSBLeafNodeGroup (unsigned n)
References NULL.
template<typename T > CCSBLeafNodeGroup< T >::~CCSBLeafNodeGroup ()
References NULL.
Member Function Documentation
template<typename T > void CCSBLeafNodeGroup< T >::DeleteChildren () virtual
Reimplemented from CCSBNodeGroup< T >.
template<typename T > bool CCSBLeafNodeGroup< T >::deserialize (FILE * filename) virtual
Reimplemented from CCSBNodeGroup< T >.
References CCSBLeafNode< T >::deserialize().
template<typename T> CCSBNodeGroup<T>* CCSBLeafNodeGroup< T >::getHeaderNG () inline virtual
Reimplemented from CCSBNodeGroup< T >.
template<typename T> CCSBNode<T>* CCSBLeafNodeGroup< T >::getNode (unsigned i) inline virtual
Reimplemented from CCSBNodeGroup< T >.
References NULL.
Referenced by CSBPlusTree< T >::Insert().
template<typename T> CCSBNodeGroup<T>* CCSBLeafNodeGroup< T >::getTailerNG () inline virtual
Reimplemented from CCSBNodeGroup< T >.
template<typename T > bool CCSBLeafNodeGroup< T >::serialize (FILE * filename) virtual
Reimplemented from CCSBNodeGroup< T >.
References boost::serialization::serialize().
template<typename T> void CCSBLeafNodeGroup< T >::setHeaderNG (CCSBNodeGroup< T > * header) inline virtual
Reimplemented from CCSBNodeGroup< T >.
Referenced by CSBPlusTree< T >::Insert().
template<typename T> void CCSBLeafNodeGroup< T >::setNode (unsigned i, CCSBNode< T > * node) inline virtual
Reimplemented from CCSBNodeGroup< T >.
References CCSBNode< T >::getElement(), CCSBNode< T >::getFather(), and CCSBNode< T >::getUsedKeys().
template<typename T> void CCSBLeafNodeGroup< T >::setTailerNG (CCSBNodeGroup< T > * tailer) inline virtual
Reimplemented from CCSBNodeGroup< T >.
Referenced by CSBPlusTree< T >::Insert().
template<typename T> bool CCSBLeafNodeGroup< T >::setUsedNodes (unsigned n) inline virtual
Reimplemented from CCSBNodeGroup< T >.
Member Data Documentation
template<typename T> CCSBNode<T>** CCSBLeafNodeGroup< T >::leaf_nodes
template<typename T> CCSBNodeGroup<T>* CCSBLeafNodeGroup< T >::p_header
template<typename T> CCSBNodeGroup<T>* CCSBLeafNodeGroup< T >::p_tailer
The documentation for this class was generated from the following files:
IndexManager/CSBPlusTree.h
IndexManager/CSBPlusTree.cpp