Claims: Catalog Class Reference
Catalog Class Reference
#include <Catalog.h>
Public Member Functions
virtual ~Catalog ()
unsigned allocate_unique_table_id ()
bool add_table (TableDescriptor *const &table)
TableDescriptor * getTable (const TableID &) const
TableDescriptor * getTable (const std::string &table_name) const
ProjectionDescriptor * getProjection (const ProjectionID &) const
ProjectionBinding * getBindingModele () const
unsigned getTableCount () const
void saveCatalog ()
void restoreCatalog ()
void outPut ()
bool isAttributeExist (const std::string &table_name, const std::string &attribute_name) const
vector< PartitionID > getPartitionIDList (const std::string &table_name, const std::string &attribute_name)
Static Public Member Functions
static Catalog * getInstance ()
Private Member Functions
Catalog ()
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
TableIDAllocator table_id_allocator
boost::unordered_map
< std::string, TableDescriptor * > name_to_table
boost::unordered_map< TableID,
TableDescriptor * > tableid_to_table
Logging * logging
ProjectionBinding * binding_
Static Private Attributes
static Catalog * instance_ =0
Friends
class boost::serialization::access
Constructor & Destructor Documentation
Catalog::~Catalog () virtual
References binding_, instance_, logging, and name_to_table.
Catalog::Catalog () private
References binding_, and logging.
Referenced by getInstance().
Member Function Documentation
bool Catalog::add_table (TableDescriptor *const & table)
References TableIDAllocator::decrease_table_id(), Logging::elog(), TableDescriptor::get_table_id(), TableDescriptor::getTableName(), Logging::log(), logging, name_to_table, table_id_allocator, and tableid_to_table.
Referenced by BindingTest(), create_poc_data_four_partitions(), create_poc_data_one_partitions(), CreateTable(), execting_test(), claims::stmt_handler::CreateTableExec::Execute(), init_multi_node_tpc_h_envoriment_(), init_poc_environment(), init_single_node_tpc_h_envoriment_(), init_single_node_tpc_h_envoriment_ing(), init_single_node_tpc_h_envoriment_sort(), init_tt_environment(), loadData(), startup_catalog(), startup_mulitple_node_environment_of_poc(), startup_multiple_node_environment(), startup_multiple_node_environment_of_stock(), startup_multiple_node_environment_of_tpch(), startup_single_node_environment_of_tpch(), startup_single_node_one_partition_environment_of_tpch(), statistic_manager_test(), TableDescriptor_test(), test_CSBIndexBuilding(), test_index_scan_iterator(), test_logical_csb_index_building(), and variable_schema_test().
unsigned Catalog::allocate_unique_table_id ()
References TableIDAllocator::allocate_unique_table_id(), and table_id_allocator.
Referenced by TableDescriptor_test().
ProjectionBinding * Catalog::getBindingModele () const
References binding_.
Referenced by LogicalCSBIndexBuilding::GetPlanContext(), LogicalIndexScan::GetPlanContext(), claims::logical_operator::LogicalScan::GetPlanContext(), and HdfsLoader::load().
Catalog * Catalog::getInstance () static
References Catalog(), and instance_.
Referenced by IndexManager::addIndexToList(), Analyzer::analyse(), Analyzer::analyse_on_project(), append_test(), bulk_test_logical_index_scan(), Analyzer::compute_attribute_stat(), Analyzer::compute_table_stat(), Analyzer::computeHistogram(), create_load_test(), Environment::Environment(), Estimation::estEqualJoin(), Estimation::estEqualOper(), Estimation::estRangeOper(), Analyzer::getDistinctCardinality(), LogicalIndexScan::GetPlanContext(), LogicalCSBIndexBuilding::GetPlanContext(), claims::logical_operator::LogicalScan::GetPlanContext(), inmemory_append_test(), IndexManager::insertIndexToList(), HdfsLoader::load(), LogicalCSBIndexBuilding::LogicalCSBIndexBuilding(), LogicalIndexScan::LogicalIndexScan(), claims::logical_operator::LogicalScan::LogicalScan(), LogicalCSBIndexBuilding::Print(), claims::logical_operator::LogicalScan::Print(), TableDescriptor_test(), test_complete_repartition_filtered_join(), test_complete_repartition_scan_join(), test_index_filter_performance(), test_logical_index_building(), test_logical_index_scan(), test_multiple_complete_repartition_filtered_join(), test_multiple_complete_repartition_scan_join(), test_multiple_no_repartition_filtered_join(), test_multiple_no_repartition_scan_join(), test_multiple_scan(), test_multiple_scan_filter_Aggregation(), test_multiple_scan_filter_high_selectivity(), test_multiple_scan_filter_low_selectivity(), test_multiple_scan_filter_Scalar_Aggregation(), test_no_repartition_filtered_join(), test_no_repartition_scan_join(), test_scan(), test_scan_Aggregation_large_Groups(), test_scan_Aggregation_small_Groups(), test_scan_filter_Aggregation(), test_scan_filter_high_selectivity(), test_scan_filter_low_selectivity(), test_scan_filter_performance(), and test_scan_filter_Scalar_Aggregation().
vector< PartitionID > Catalog::getPartitionIDList (const std::string & table_name, const std::string & attribute_name)
References TableDescriptor::getNumberOfProjection(), ProjectionDescriptor::getPartitioner(), Partitioner::getPartitionIDList(), TableDescriptor::getProjectoin(), getTable(), ProjectionDescriptor::isExist(), and NULL.
ProjectionDescriptor * Catalog::getProjection (const ProjectionID & pid) const
References TableDescriptor::getProjectoin(), getTable(), ProjectionID::projection_off, and ProjectionID::table_id.
Referenced by IndexManager::addIndexToList(), Analyzer::analyse_on_project(), and IndexManager::insertIndexToList().
TableDescriptor * Catalog::getTable (const TableID & target) const
References NULL, and tableid_to_table.
Referenced by add_all_table_column(), add_table_column(), Analyzer::analyse(), append_test(), BindingTest(), bulk_test_logical_index_scan(), Analyzer::compute_table_stat(), create_load_test(), create_poc_data_four_partitions(), create_poc_data_one_partitions(), CreateProjection(), CreateTable(), claims::stmt_handler::CreateTableExec::CreateTableExec(), Estimation::estEqualJoin(), Estimation::estEqualOper(), Estimation::estRangeOper(), execting_test(), get_aggregation_args(), AstSelectStmt::GetLogicalPlanOfProject(), getPartitionIDList(), claims::logical_operator::LogicalScan::GetPlanContext(), getProjection(), init_multi_node_tpc_h_envoriment_(), init_poc_environment(), init_single_node_tpc_h_envoriment_(), init_single_node_tpc_h_envoriment_ing(), init_single_node_tpc_h_envoriment_sort(), init_tt_environment(), inmemory_append_test(), insert_into_hash_table_from_projection(), InsertData(), claims::stmt_handler::InsertExec::InsertExec(), isAttributeExist(), lineitem_scan_aggregation(), lineitem_scan_filter(), lineitem_scan_self_join(), loadData(), LoadData(), claims::stmt_handler::LoadExec::LoadExec(), LogicalCSBIndexBuilding::LogicalCSBIndexBuilding(), LogicalIndexScan::LogicalIndexScan(), claims::logical_operator::LogicalScan::LogicalScan(), claims::logical_operator::LogicalScan::Print(), projection_scan(), query_1(), query_2(), query_3(), query_select_aggregation(), query_select_aggregation_ing(), query_select_fzh(), query_select_sort(), query_select_sort_string(), sb_scan_aggregation(), sb_scan_filter(), sb_scan_self_join(), AstTable::SemanticAnalisys(), ShowTable(), startup_catalog(), startup_mulitple_node_environment_of_poc(), startup_multiple_node_environment(), startup_multiple_node_environment_of_stock(), startup_multiple_node_environment_of_tpch(), startup_single_node_environment_of_tpch(), startup_single_node_one_partition_environment_of_tpch(), statistic_manager_test(), test_block_construct(), test_complete_repartition_filtered_join(), test_complete_repartition_scan_join(), test_CSBIndexBuilding(), test_index_filter_performance(), test_index_scan_iterator(), test_logical_csb_index_building(), test_logical_index_building(), test_logical_index_scan(), test_multiple_complete_repartition_filtered_join(), test_multiple_complete_repartition_scan_join(), test_multiple_no_repartition_filtered_join(), test_multiple_no_repartition_scan_join(), test_multiple_scan(), test_multiple_scan_filter_Aggregation(), test_multiple_scan_filter_high_selectivity(), test_multiple_scan_filter_low_selectivity(), test_multiple_scan_filter_Scalar_Aggregation(), test_no_repartition_filtered_join(), test_no_repartition_scan_join(), test_scan(), test_scan_Aggregation_large_Groups(), test_scan_Aggregation_small_Groups(), test_scan_filter_Aggregation(), test_scan_filter_high_selectivity(), test_scan_filter_low_selectivity(), test_scan_filter_performance(), test_scan_filter_Scalar_Aggregation(), and variable_schema_test().
TableDescriptor * Catalog::getTable (const std::string & table_name) const
References name_to_table, and NULL.
unsigned Catalog::getTableCount () const inline
References table_id_allocator, and TableIDAllocator::table_id_curosr.
Referenced by ShowTable().
bool Catalog::isAttributeExist (const std::string & table_name, const std::string & attribute_name) const
References getTable(), and TableDescriptor::isExist().
Referenced by oncondition_check(), orderby_analysis(), selectlist_expr_analysis(), table_has_column(), and wherecondition_check().
void Catalog::outPut ()
void Catalog::restoreCatalog ()
References Config::catalog_file, Logging::elog(), and logging.
Referenced by Environment::Environment(), and testServerClient().
void Catalog::saveCatalog ()
References Config::catalog_file.
Referenced by CreateProjection(), CreateTable(), claims::stmt_handler::LoadExec::Execute(), claims::stmt_handler::InsertExec::Execute(), claims::stmt_handler::CreateTableExec::Execute(), InsertData(), LoadData(), startup_multiple_node_environment_of_stock(), startup_multiple_node_environment_of_tpch(), and startup_single_node_environment_of_tpch().
template<class Archive > void Catalog::serialize (Archive & ar, const unsigned int version) inline private
References name_to_table, table_id_allocator, and tableid_to_table.
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
ProjectionBinding* Catalog::binding_ private
Referenced by Catalog(), getBindingModele(), and ~Catalog().
Catalog * Catalog::instance_ =0 static private
Referenced by getInstance(), and ~Catalog().
Logging* Catalog::logging private
Referenced by add_table(), Catalog(), restoreCatalog(), and ~Catalog().
boost::unordered_map<std::string,TableDescriptor*> Catalog::name_to_table private
Referenced by add_table(), getTable(), serialize(), and ~Catalog().
TableIDAllocator Catalog::table_id_allocator private
Referenced by add_table(), allocate_unique_table_id(), getTableCount(), and serialize().
boost::unordered_map<TableID,TableDescriptor*> Catalog::tableid_to_table private
Referenced by add_table(), getTable(), and serialize().
The documentation for this class was generated from the following files:
Catalog/Catalog.h
Catalog/Catalog.cpp