My Project: claims::logical_operator::PlanContext Class Reference
claims::logical_operator::PlanContext Class Reference
#include <plan_context.h>
Public Member Functions
PlanContext (const PlanContext &plan_context)
unsigned long GetAggregatedDatasize () const
unsigned long GetAggregatedDataCardinality () const
bool IsHashPartitioned () const
Schema * GetSchema () const
unsigned GetTupleSize () const
Attribute GetAttribute (std::string name) const
Attribute GetAttribute (std::string tbname, std::string colname) const
Public Attributes
std::vector< Attribute > attribute_list_
unsigned long commu_cost_
PlanPartitioner plan_partitioner_
Friends
class LogcalOperator
Detailed Description
maintain the data property of the plan after having completed current operator, mainly include the attribute_list_, commu_cost_ and plan_partitioner_. the PlanContext originates the leaf of the plan (i.e. scan operator), the PlanContext of current operator generates from it's children.
Member Function Documentation
unsigned long claims::logical_operator::PlanContext::GetAggregatedDatasize () const
after having executing current operator, the data size could be changed, the data size = total tuples * tuple size.
Referenced by claims::logical_operator::LogicalScan::GetOptimalPhysicalPlan(), claims::logical_operator::LogicalFilter::GetOptimalPhysicalPlan(), claims::logical_operator::LogicalQueryPlanRoot::GetOptimalPhysicalPlan(), claims::logical_operator::LogicalCrossJoin::GetPlanContext(), and claims::logical_operator::LogicalAggregation::GetPlanContext().
Schema * claims::logical_operator::PlanContext::GetSchema () const
Only fixed schema is supported now. TODO(wangli): support other schemas.
The documentation for this class was generated from the following files:
logical_operator/plan_context.h
logical_operator/plan_context.cpp