Claims: BasicHashTable::Iterator Class Reference
BasicHashTable::Iterator Class Reference
#include <hashtable.h>
Public Member Functions
Iterator ()
Iterator (const unsigned &buck_actual_size, const unsigned &tuplesize)
Iterator (const Iterator &r)
~Iterator ()
void * readnext ()
void * readCurrent () const
void increase_cur_ ()
Private Attributes
void * cur
void * free
void * next
int buck_actual_size
int tuplesize
Friends
class BasicHashTable
Constructor & Destructor Documentation
BasicHashTable::Iterator::Iterator ()
BasicHashTable::Iterator::Iterator (const unsigned & buck_actual_size, const unsigned & tuplesize)
BasicHashTable::Iterator::Iterator (const Iterator & r)
References buck_actual_size, cur, free, next, and tuplesize.
BasicHashTable::Iterator::~Iterator ()
Member Function Documentation
void BasicHashTable::Iterator::increase_cur_ () inline
Referenced by claims::physical_operator::PhysicalAggregation::Next(), claims::physical_operator::InOperator::Next(), claims::physical_operator::PhysicalHashJoin::Next(), and claims::physical_operator::PhysicalAggregation::Open().
void* BasicHashTable::Iterator::readCurrent () const inline
Referenced by claims::physical_operator::PhysicalAggregation::Next(), claims::physical_operator::InOperator::Next(), claims::physical_operator::PhysicalHashJoin::Next(), and claims::physical_operator::PhysicalAggregation::Open().
void* BasicHashTable::Iterator::readnext () inline
Referenced by claims::physical_operator::InOperator::Next(), and BasicHashTable::report_status().
Friends And Related Function Documentation
friend class BasicHashTable friend
Member Data Documentation
int BasicHashTable::Iterator::buck_actual_size private
Referenced by Iterator().
void* BasicHashTable::Iterator::cur private
Referenced by Iterator(), and BasicHashTable::placeIterator().
void* BasicHashTable::Iterator::free private
Referenced by Iterator(), and BasicHashTable::placeIterator().
void* BasicHashTable::Iterator::next private
Referenced by Iterator(), and BasicHashTable::placeIterator().
int BasicHashTable::Iterator::tuplesize private
Referenced by Iterator().
The documentation for this class was generated from the following files:
common/hashtable.h
common/hashtable.cpp