Claims: BlockStreamBuffer Class Reference
BlockStreamBuffer Class Reference
#include <BlockStreamBuffer.h>
Public Member Functions
BlockStreamBuffer (unsigned block_size, unsigned block_count, Schema *schema)
virtual ~BlockStreamBuffer ()
void insertBlock (BlockStreamBase *block)
bool getBlock (BlockStreamBase &block)
unsigned getBlockInBuffer ()
bool Empty ()
double getBufferUsage ()
long getReceivedDataSizeInKbytes ()
Public Member Functions inherited from MonitorableBuffer
MonitorableBuffer ()
virtual ~MonitorableBuffer ()
void setInputComplete ()
bool inputComplete () const
Private Attributes
std::list< BlockStreamBase * > block_stream_empty_list_
std::list< BlockStreamBase * > block_stream_used_list_
semaphore sema_empty_block_
Lock lock_
unsigned total_block_count_
unsigned block_size_
unsigned long received_block_count_
Constructor & Destructor Documentation
BlockStreamBuffer::BlockStreamBuffer (unsigned block_size, unsigned block_count, Schema * schema)
References Lock::acquire(), block_stream_empty_list_, BlockStreamBase::createBlock(), semaphore::get_value(), lock_, semaphore::post(), Lock::release(), and sema_empty_block_.
BlockStreamBuffer::~BlockStreamBuffer () virtual
References block_stream_empty_list_, block_stream_used_list_, semaphore::destroy(), and sema_empty_block_.
Referenced by fill_basic_hash_table().
Member Function Documentation
bool BlockStreamBuffer::Empty ()
References Lock::acquire(), block_stream_used_list_, lock_, and Lock::release().
Referenced by claims::physical_operator::Expander::ChildExhausted().
bool BlockStreamBuffer::getBlock (BlockStreamBase & block)
References Lock::acquire(), block_stream_empty_list_, block_stream_used_list_, lock_, semaphore::post(), Lock::release(), sema_empty_block_, and BlockStreamBase::switchBlock().
Referenced by insert_into_hash_table(), claims::physical_operator::Expander::Next(), and claims::physical_operator::ExchangeMerger::Next().
unsigned BlockStreamBuffer::getBlockInBuffer ()
References Lock::acquire(), block_stream_used_list_, lock_, and Lock::release().
Referenced by getBufferUsage().
double BlockStreamBuffer::getBufferUsage () virtual
Implements MonitorableBuffer.
References getBlockInBuffer(), and total_block_count_.
long BlockStreamBuffer::getReceivedDataSizeInKbytes () virtual
Implements MonitorableBuffer.
References block_size_, and received_block_count_.
Referenced by claims::physical_operator::Expander::Close().
void BlockStreamBuffer::insertBlock (BlockStreamBase * block)
References Lock::acquire(), block_stream_empty_list_, block_stream_used_list_, BlockStreamBase::deepCopy(), Block::isIsReference(), lock_, received_block_count_, Lock::release(), sema_empty_block_, BlockStreamBase::switchBlock(), and semaphore::wait().
Referenced by claims::physical_operator::Expander::ExpandedWork(), initial_input_date(), and claims::physical_operator::ExchangeMerger::Receiver().
Member Data Documentation
unsigned BlockStreamBuffer::block_size_ private
Referenced by getReceivedDataSizeInKbytes().
std::list<BlockStreamBase*> BlockStreamBuffer::block_stream_empty_list_ private
Referenced by BlockStreamBuffer(), getBlock(), insertBlock(), and ~BlockStreamBuffer().
std::list<BlockStreamBase*> BlockStreamBuffer::block_stream_used_list_ private
Referenced by Empty(), getBlock(), getBlockInBuffer(), insertBlock(), and ~BlockStreamBuffer().
Lock BlockStreamBuffer::lock_ private
Referenced by BlockStreamBuffer(), Empty(), getBlock(), getBlockInBuffer(), and insertBlock().
unsigned long BlockStreamBuffer::received_block_count_ private
Referenced by getReceivedDataSizeInKbytes(), and insertBlock().
semaphore BlockStreamBuffer::sema_empty_block_ private
Referenced by BlockStreamBuffer(), getBlock(), insertBlock(), and ~BlockStreamBuffer().
unsigned BlockStreamBuffer::total_block_count_ private
Referenced by getBufferUsage().
The documentation for this class was generated from the following files:
common/Block/BlockStreamBuffer.h
common/Block/BlockStreamBuffer.cpp