Claims: SpineLock Class Reference
SpineLock Class Reference
#include <lock.h>
Public Member Functions
SpineLock ()
void acquire ()
bool try_lock ()
int fakelock ()
int getvalue ()
void release ()
Private Member Functions
int tas (volatile char *lock)
Private Attributes
volatile char _l
Detailed Description
Non-recursive spinlock. Using xchg and ldstub as in PostgresSQL.
Constructor & Destructor Documentation
SpineLock::SpineLock () inline
Member Function Documentation
void SpineLock::acquire () inline
Call blocks and retunrs only when it has the lock.
References _l, and tas().
Referenced by BasicHashTable::allocate(), claims::physical_operator::input_dataset::AtomicGet(), claims::physical_operator::input_dataset::AtomicPut(), IteratorExecutorSlave::createNewThreadAndRun(), PerformanceInfo::getBlockSumInAllSlices(), ThreadSafe::gethostbyname_ts(), InsertOptimizedHashTable::insertBlock(), InsertOptimizedHashTable::insertEntry(), PerformanceInfo::processed_one_block(), PerformanceInfo::report_instance_performance_in_millibytes(), IteratorExecutorSlave::run_iterator(), and tas().
int SpineLock::fakelock () inline
References _l.
int SpineLock::getvalue () inline
void SpineLock::release () inline
Unlocks the lock object.
References _l.
Referenced by BasicHashTable::allocate(), claims::physical_operator::input_dataset::AtomicGet(), claims::physical_operator::input_dataset::AtomicPut(), IteratorExecutorSlave::createNewThreadAndRun(), PerformanceInfo::getBlockSumInAllSlices(), ThreadSafe::gethostbyname_ts(), InsertOptimizedHashTable::insertBlock(), InsertOptimizedHashTable::insertEntry(), PerformanceInfo::processed_one_block(), PerformanceInfo::report_instance_performance_in_millibytes(), and IteratorExecutorSlave::run_iterator().
int SpineLock::tas (volatile char * lock) inline private
References acquire().
Referenced by acquire(), and try_lock().
bool SpineLock::try_lock () inline
References _l, and tas().
Member Data Documentation
volatile char SpineLock::_l private
Referenced by acquire(), fakelock(), release(), and try_lock().
The documentation for this class was generated from the following file:
utility/lock.h