Claims: Operate Class Reference
Operate Class Reference abstract
#include <data_type.h>
Public Member Functions
Operate (bool _nullable=true)
virtual ~Operate ()
void ass (void *src, void *desc)
virtual void assignment (const void *const &src, void *const &desc) const =0
virtual unsigned getPartitionValue (const void *key, const PartitionFunction *partition_function) const =0
virtual unsigned getPartitionValue (const void *key, const unsigned long &mod) const =0
virtual unsigned getPartitionValue (const void *key) const =0
virtual std::string toString (void *value)=0
virtual void toValue (void *target, const char *string)=0
virtual bool equal (const void *const &a, const void *const &b) const =0
virtual bool less (const void *&a, const void *&b) const =0
virtual bool greate (const void *&a, const void *&b) const =0
virtual void add (void *target, void *increment)=0
virtual void multiple (void *target, void *increment)=0
virtual int compare (const void *a, const void *b) const =0
virtual fun GetADDFunction ()=0
virtual fun GetMINFunction ()=0
virtual fun GetMAXFunction ()=0
virtual fun GetIncreateByOneFunction ()=0
virtual fun GetAVGFunction ()=0
virtual Operate * duplicateOperator () const =0
virtual bool setNull (void *value)=0
virtual bool isNull (void *value) const =0
Public Attributes
void(* assign)(const void *const &src, void *const &desc)
bool nullable
Constructor & Destructor Documentation
Operate::Operate (bool _nullable = true) inline
virtual Operate::~Operate () inline virtual
Referenced by test_date_computation().
Member Function Documentation
virtual void Operate::add (void * target, void * increment) pure virtual
Implemented in OperateBool, OperateDecimal, OperateUSmallInt, OperateSmallInt, OperateDatetime, OperateTime, OperateDate, OperateString, OperateULong, OperateDouble, OperateFloat, and OperateInt.
Referenced by test_date_computation(), test_decimal_add(), test_decimal_add1(), and test_decimal_minus().
void Operate::ass (void * src, void * desc) inline
virtual void Operate::assignment (const void *const & src, void *const & desc) const inline pure virtual
Implemented in OperateBool, OperateDecimal, OperateUSmallInt, OperateSmallInt, OperateDatetime, OperateTime, OperateDate, OperateString, OperateULong, OperateDouble, OperateFloat, and OperateInt.
Referenced by AttributeComparator::AttributeComparator(), SubTuple::getSubTuple(), bottomLayerCollecting::Next(), claims::physical_operator::PhysicalAggregation::Open(), claims::physical_operator::InOperator::Open(), ratio(), and TupleConvertor::sub_tuple().
virtual int Operate::compare (const void * a, const void * b) const pure virtual
Implemented in OperateBool, OperateDecimal, OperateUSmallInt, OperateSmallInt, OperateDatetime, OperateTime, OperateDate, OperateString, OperateULong, OperateDouble, OperateFloat, and OperateInt.
Referenced by Estimation::estEqualOper(), Estimation::estRangeOper(), and ratio().
virtual Operate* Operate::duplicateOperator () const pure virtual
Implemented in OperateBool, OperateDecimal, OperateUSmallInt, OperateSmallInt, OperateDatetime, OperateTime, OperateDate, OperateString, OperateULong, OperateDouble, OperateFloat, and OperateInt.
Referenced by column_type::column_type(), claims::physical_operator::PhysicalHashJoin::Open(), bottomLayerSorting::Open(), and column_type::operator=().
virtual bool Operate::equal (const void *const & a, const void *const & b) const pure virtual
Implemented in OperateBool, OperateDecimal, OperateUSmallInt, OperateSmallInt, OperateDatetime, OperateTime, OperateDate, OperateString, OperateULong, OperateDouble, OperateFloat, and OperateInt.
Referenced by Estimation::estEqualOper(), Estimation::estRangeOper(), claims::physical_operator::PhysicalHashJoin::IsMatch(), claims::physical_operator::InOperator::Next(), and claims::physical_operator::PhysicalAggregation::Open().
virtual fun Operate::GetADDFunction () pure virtual
Implemented in OperateBool, OperateDecimal, OperateUSmallInt, OperateSmallInt, OperateDatetime, OperateTime, OperateDate, OperateString, OperateULong, OperateDouble, OperateFloat, and OperateInt.
virtual fun Operate::GetAVGFunction () pure virtual
Implemented in OperateBool, OperateDecimal, OperateUSmallInt, OperateSmallInt, OperateDatetime, OperateTime, OperateDate, OperateString, OperateULong, OperateDouble, OperateFloat, and OperateInt.
virtual fun Operate::GetIncreateByOneFunction () pure virtual
Implemented in OperateBool, OperateDecimal, OperateUSmallInt, OperateSmallInt, OperateDatetime, OperateTime, OperateDate, OperateString, OperateULong, OperateDouble, OperateFloat, and OperateInt.
virtual fun Operate::GetMAXFunction () pure virtual
Implemented in OperateBool, OperateDecimal, OperateUSmallInt, OperateSmallInt, OperateDatetime, OperateTime, OperateDate, OperateString, OperateULong, OperateDouble, OperateFloat, and OperateInt.
Referenced by ratio().
virtual fun Operate::GetMINFunction () pure virtual
Implemented in OperateBool, OperateDecimal, OperateUSmallInt, OperateSmallInt, OperateDatetime, OperateTime, OperateDate, OperateString, OperateULong, OperateDouble, OperateFloat, and OperateInt.
Referenced by ratio().
virtual unsigned Operate::getPartitionValue (const void * key, const PartitionFunction * partition_function) const pure virtual
Implemented in OperateBool, OperateDecimal, OperateUSmallInt, OperateSmallInt, OperateDatetime, OperateTime, OperateDate, OperateString, OperateULong, OperateDouble, OperateFloat, and OperateInt.
Referenced by claims::physical_operator::ExchangeSender::GetHashPartitionId(), claims::physical_operator::InOperator::Next(), claims::physical_operator::PhysicalHashJoin::Next(), claims::physical_operator::PhysicalAggregation::Open(), claims::physical_operator::InOperator::Open(), and claims::physical_operator::PhysicalHashJoin::Open().
virtual unsigned Operate::getPartitionValue (const void * key, const unsigned long & mod) const pure virtual
Implemented in OperateBool, OperateDecimal, OperateUSmallInt, OperateSmallInt, OperateDatetime, OperateTime, OperateDate, OperateString, OperateULong, OperateDouble, OperateFloat, and OperateInt.
virtual unsigned Operate::getPartitionValue (const void * key) const pure virtual
Implemented in OperateBool, OperateDecimal, OperateUSmallInt, OperateSmallInt, OperateDatetime, OperateTime, OperateDate, OperateString, OperateULong, OperateDouble, OperateFloat, and OperateInt.
virtual bool Operate::greate (const void *& a, const void *& b) const pure virtual
Implemented in OperateBool, OperateDecimal, OperateUSmallInt, OperateSmallInt, OperateDatetime, OperateTime, OperateDate, OperateString, OperateULong, OperateDouble, OperateFloat, and OperateInt.
virtual bool Operate::isNull (void * value) const inline pure virtual
Implemented in OperateBool, OperateDecimal, OperateUSmallInt, OperateSmallInt, OperateDatetime, OperateTime, OperateDate, OperateString, OperateULong, OperateDouble, OperateFloat, and OperateInt.
virtual bool Operate::less (const void *& a, const void *& b) const pure virtual
Implemented in OperateBool, OperateDecimal, OperateUSmallInt, OperateSmallInt, OperateDatetime, OperateTime, OperateDate, OperateString, OperateULong, OperateDouble, OperateFloat, and OperateInt.
Referenced by bottomLayerSorting::compare().
virtual void Operate::multiple (void * target, void * increment) pure virtual
Implemented in OperateBool, OperateDecimal, OperateUSmallInt, OperateSmallInt, OperateDatetime, OperateTime, OperateDate, OperateString, OperateULong, OperateDouble, OperateFloat, and OperateInt.
Referenced by test_decimal_add2().
virtual bool Operate::setNull (void * value) inline pure virtual
Implemented in OperateBool, OperateDecimal, OperateUSmallInt, OperateSmallInt, OperateDatetime, OperateTime, OperateDate, OperateString, OperateULong, OperateDouble, OperateFloat, and OperateInt.
Referenced by set_null_test().
virtual std::string Operate::toString (void * value) pure virtual
Implemented in OperateBool, OperateDecimal, OperateUSmallInt, OperateSmallInt, OperateDatetime, OperateTime, OperateDate, OperateString, OperateULong, OperateDouble, OperateFloat, and OperateInt.
Referenced by null_value_test(), ResultSet::print(), Histogram::Print(), set_null_test(), test_date_computation(), test_decimal_add(), test_decimal_add1(), test_decimal_add2(), test_decimal_minus(), test_decimal_to_string(), test_decimal_to_value1(), test_decimal_to_value2(), test_decimal_to_value3(), test_decimal_to_value4(), and test_decimal_to_value5().
virtual void Operate::toValue (void * target, const char * string) pure virtual
Implemented in OperateBool, OperateDecimal, OperateUSmallInt, OperateSmallInt, OperateDatetime, OperateTime, OperateDate, OperateString, OperateULong, OperateDouble, OperateFloat, and OperateInt.
Referenced by null_value_test(), test_date_computation(), and test_decimal_minus().
Member Data Documentation
void(* Operate::assign)(const void *const &src, void *const &desc)
Referenced by Analyzer::equiDepthAnalyse(), and Analyzer::mcvAnalyse().
bool Operate::nullable
The documentation for this class was generated from the following file:
common/data_type.h