Claims: DiskStore Class Reference
DiskStore Class Reference
#include <DiskStore.h>
Public Member Functions
DiskStore (string rootDirs)
virtual ~DiskStore ()
bool putValue (string blockId, void *value)
void * getChunk (string blockId)
bool remove (string blockId)
bool contains (string blockId)
unsigned getSize (string blockId)
bool getFile (string blockId)
bool createDirs (string rootDirs)
Private Attributes
string rootDirs_
Constructor & Destructor Documentation
DiskStore::DiskStore (string rootDirs)
References createDirs(), and rootDirs_.
DiskStore::~DiskStore () virtual
Member Function Documentation
bool DiskStore::contains (string blockId) inline
bool DiskStore::createDirs (string rootDirs)
Referenced by DiskStore().
void* DiskStore::getChunk (string blockId) inline
bool DiskStore::getFile (string blockId) inline
unsigned DiskStore::getSize (string blockId) inline
bool DiskStore::putValue (string blockId, void * value) inline
Referenced by BlockManager::put().
bool DiskStore::remove (string blockId) inline
Member Data Documentation
string DiskStore::rootDirs_ private
Referenced by DiskStore().
The documentation for this class was generated from the following files:
storage/DiskStore.h
storage/DiskStore.cpp