Claims: CodeGenerationTest Class Reference
CodeGenerationTest Class Reference
#include <codegen_test.h>
Inherits Test.
Static Protected Member Functions
static void SetUpTestCase ()
static void TearDownTestCase ()
Member Function Documentation
static void CodeGenerationTest::SetUpTestCase () inline static protected
References CodeGenerator::getInstance(), initialize_arithmetic_type_promotion_matrix(), initialize_operator_function(), and initialize_type_cast_functions().
static void CodeGenerationTest::TearDownTestCase () inline static protected
References CodeGenerator::getInstance().
The documentation for this class was generated from the following file:
codegen/codegen_test.h