Claims: ASTParserLogging Class Reference
ASTParserLogging Class Reference
#include <Logging.h>
Static Public Member Functions
static void log (const char *format,...)
static void elog (const char *format,...)
Member Function Documentation
void ASTParserLogging::elog (const char * format, ...) static
References RawElog().
Referenced by ExecuteLogicalQueryPlan(), StreamBuffer::MoveForwardEnd(), and ShowTable().
void ASTParserLogging::log (const char * format, ...) static
References RawLog().
Referenced by ExecuteLogicalQueryPlan(), InsertData(), and LoadData().
The documentation for this class was generated from the following files:
common/Logging.h
common/Logging.cpp