Claims: ProjectionBinding Class Reference
ProjectionBinding Class Reference
#include <ProjectionBinding.h>
Public Member Functions
ProjectionBinding ()
virtual ~ProjectionBinding ()
bool BindingEntireProjection (Partitioner *, const StorageLevel &desriable_storage_level=MEMORY)
bool UnbindingEntireProjection (Partitioner *part)
Constructor & Destructor Documentation
ProjectionBinding::ProjectionBinding ()
ProjectionBinding::~ProjectionBinding () virtual
Member Function Documentation
bool ProjectionBinding::BindingEntireProjection (Partitioner * part, const StorageLevel & desriable_storage_level = MEMORY)
TODO: OneToMany mode where one partition is allowed to be bound to multiple nodes.
References ResourceManagerMaster::ApplyDiskBuget(), ResourceManagerMaster::ApplyMemoryBuget(), Partitioner::bindPartitionToNode(), DISK, Partitioner::get_binding_mode_(), Environment::getInstance(), BlockManagerMaster::getInstance(), Partitioner::getNumberOfPartitions(), Partitioner::getPartitionChunks(), Partitioner::getPartitionDataSize(), Partitioner::getProejctionID(), Environment::getResourceManagerMaster(), ResourceManagerMaster::getSlaveIDList(), HDFS, MEMORY, OneToOne, and BlockManagerMaster::SendBindingMessage().
Referenced by BindingTest(), LogicalIndexScan::GetPlanContext(), LogicalCSBIndexBuilding::GetPlanContext(), claims::logical_operator::LogicalScan::GetPlanContext(), test_CSBIndexBuilding(), test_index_scan_iterator(), and variable_schema_test().
bool ProjectionBinding::UnbindingEntireProjection (Partitioner * part)
TODO: OneToMany mode where one partition is allowed to be bound to multiple nodes.
References DESIRIABLE_STORAGE_LEVEL, DISK, Partitioner::get_binding_mode_(), Environment::getInstance(), BlockManagerMaster::getInstance(), Partitioner::getNumberOfPartitions(), Partitioner::getPartitionDataSize(), Partitioner::getPartitionLocation(), Partitioner::getProejctionID(), Environment::getResourceManagerMaster(), MEMORY, OneToOne, ResourceManagerMaster::ReturnDiskBuget(), ResourceManagerMaster::ReturnMemoryBuget(), BlockManagerMaster::SendUnbindingMessage(), and Partitioner::unbindPartitionToNode().
Referenced by HdfsLoader::load().
The documentation for this class was generated from the following files:
Catalog/ProjectionBinding.h
Catalog/ProjectionBinding.cpp