Claims: ProjectionDescriptor Class Reference
ProjectionDescriptor Class Reference
#include <table.h>
Public Member Functions
ProjectionDescriptor ()
ProjectionDescriptor (ProjectionID)
ProjectionDescriptor (const string &name)
virtual ~ProjectionDescriptor ()
void addAttribute (Attribute attr)
bool hasAttribute (const Attribute &attr) const
void DefinePartitonier (const unsigned &number_of_partitions, const Attribute &partition_key, PartitionFunction *partition_functin)
Partitioner * getPartitioner () const
bool isExist (const string &name) const
void setProjectionID (const ProjectionID &pid)
map< string, set< string > > getFileLocations () const
ProjectionID getProjectionID () const
bool AllPartitionBound () const
std::vector< Attribute > getAttributeList () const
Schema * getSchema () const
int getAttributeIndex (const Attribute &att) const
int long getNumberOfTuplesOnPartition (const unsigned partition_off) const
unsigned int getProjectionCost () const
Method description:
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
ProjectionID projection_id_
vector< Column > column_list_
Partitioner * partitioner
map< string, set< string > > fileLocations
string hdfsFilePath
map< string, string > blkMemoryLocations
string Projection_name_
Friends
class TableDescriptor
class boost::serialization::access
Detailed Description
Attribute describes a column in type, name, position in the table. A projection is a combination of columns that belong to a single table and will be horizontally partitioned among storage instances. ProjectionDescriptor mainly contains two kinds of important information:
1). how many attributes there are in a projection and what are they.
2). how the projection is partitioned (e.g., hash partition, range partition). How many storage instances are involved.
Constructor & Destructor Documentation
ProjectionDescriptor::ProjectionDescriptor () inline
ProjectionDescriptor::ProjectionDescriptor (ProjectionID pid) explicit
ProjectionDescriptor::ProjectionDescriptor (const string & name) explicit
ProjectionDescriptor::~ProjectionDescriptor () virtual
Member Function Documentation
void ProjectionDescriptor::addAttribute (Attribute attr)
References column_list_, and projection_id_.
bool ProjectionDescriptor::AllPartitionBound () const
References Partitioner::allPartitionBound(), and partitioner.
Referenced by LogicalCSBIndexBuilding::GetPlanContext(), LogicalIndexScan::GetPlanContext(), and claims::logical_operator::LogicalScan::GetPlanContext().
void ProjectionDescriptor::DefinePartitonier (const unsigned & number_of_partitions, const Attribute & partition_key, PartitionFunction * partition_functin)
References partitioner, and projection_id_.
int ProjectionDescriptor::getAttributeIndex (const Attribute & att) const
References getAttributeList().
Referenced by HdfsLoader::HdfsLoader().
std::vector< Attribute > ProjectionDescriptor::getAttributeList () const
References column_list_.
Referenced by Analyzer::analyse_on_project(), getAttributeIndex(), LogicalCSBIndexBuilding::GetPlanContext(), LogicalIndexScan::GetPlanContext(), getSchema(), HdfsLoader::HdfsLoader(), and claims::logical_operator::LogicalScan::LogicalScan().
map<string, set<string> > ProjectionDescriptor::getFileLocations () const inline
long int ProjectionDescriptor::getNumberOfTuplesOnPartition (const unsigned partition_off) const
References Partitioner::getPartitionCardinality(), and partitioner.
Partitioner * ProjectionDescriptor::getPartitioner () const
References partitioner.
Referenced by HdfsLoader::append(), BindingTest(), create_poc_data_four_partitions(), create_poc_data_one_partitions(), CreateProjection(), execting_test(), Catalog::getPartitionIDList(), LogicalIndexScan::GetPlanContext(), LogicalCSBIndexBuilding::GetPlanContext(), claims::logical_operator::LogicalScan::GetPlanContext(), HdfsLoader::HdfsLoader(), init_multi_node_tpc_h_envoriment_(), init_poc_environment(), init_single_node_tpc_h_envoriment_(), init_single_node_tpc_h_envoriment_ing(), init_single_node_tpc_h_envoriment_sort(), init_tt_environment(), HdfsLoader::load(), loadData(), startup_catalog(), startup_mulitple_node_environment_of_poc(), startup_multiple_node_environment(), startup_multiple_node_environment_of_stock(), startup_multiple_node_environment_of_tpch(), startup_single_node_environment_of_tpch(), startup_single_node_one_partition_environment_of_tpch(), statistic_manager_test(), test_CSBIndexBuilding(), test_index_scan_iterator(), test_logical_csb_index_building(), and variable_schema_test().
unsigned int ProjectionDescriptor::getProjectionCost () const
Method description:
Returns
: the sum of all attribute's length in projection, as this projection's cost
References column_list_.
Referenced by claims::logical_operator::LogicalScan::GetPlanContext().
ProjectionID ProjectionDescriptor::getProjectionID () const inline
Referenced by bulk_test_logical_index_scan(), claims::logical_operator::LogicalScan::GetOptimalPhysicalPlan(), claims::logical_operator::LogicalScan::GetPhysicalPlan(), HdfsLoader::HdfsLoader(), LogicalCSBIndexBuilding::Print(), claims::logical_operator::LogicalScan::Print(), projection_scan(), test_CSBIndexBuilding(), test_index_filter_performance(), test_index_scan_iterator(), test_logical_csb_index_building(), test_logical_index_building(), test_logical_index_scan(), and variable_schema_test().
Schema * ProjectionDescriptor::getSchema () const
Only fixed schema is supported now. TODO: support other schema.
References getAttributeList().
Referenced by HdfsLoader::HdfsLoader(), insert_into_hash_table_from_projection(), projection_scan(), and test_block_construct().
bool ProjectionDescriptor::hasAttribute (const Attribute & attr) const
References column_list_, and Attribute::index.
Referenced by Analyzer::analyse(), Analyzer::computeHistogram(), and claims::logical_operator::LogicalScan::GetPlanContext().
bool ProjectionDescriptor::isExist (const string & name) const
References column_list_.
Referenced by Catalog::getPartitionIDList().
template<class Archive > void ProjectionDescriptor::serialize (Archive & ar, const unsigned int version) inline private
void ProjectionDescriptor::setProjectionID (const ProjectionID & pid) inline
Friends And Related Function Documentation
friend class boost::serialization::access friend
friend class TableDescriptor friend
Member Data Documentation
map<string, string> ProjectionDescriptor::blkMemoryLocations private
vector<Column> ProjectionDescriptor::column_list_ private
Referenced by addAttribute(), getAttributeList(), getProjectionCost(), hasAttribute(), and isExist().
map<string, set<string> > ProjectionDescriptor::fileLocations private
string ProjectionDescriptor::hdfsFilePath private
Partitioner* ProjectionDescriptor::partitioner private
Referenced by AllPartitionBound(), DefinePartitonier(), getNumberOfTuplesOnPartition(), and getPartitioner().
ProjectionID ProjectionDescriptor::projection_id_ private
Referenced by addAttribute(), and DefinePartitonier().
string ProjectionDescriptor::Projection_name_ private
The documentation for this class was generated from the following files:
Catalog/table.h
Catalog/table.cpp