Claims: MonitorableBuffer Class Reference
MonitorableBuffer Class Reference abstract
#include <MonitorableBuffer.h>
Public Member Functions
MonitorableBuffer ()
virtual ~MonitorableBuffer ()
virtual double getBufferUsage ()=0
virtual long getReceivedDataSizeInKbytes ()=0
void setInputComplete ()
bool inputComplete () const
Private Attributes
bool input_complete_
Constructor & Destructor Documentation
MonitorableBuffer::MonitorableBuffer ()
MonitorableBuffer::~MonitorableBuffer () virtual
Member Function Documentation
virtual double MonitorableBuffer::getBufferUsage () pure virtual
Implemented in BlockStreamBuffer.
Referenced by ExpanderTracker::decideExpandingOrShrinking(), and ExpanderTracker::getSegmentStatus().
virtual long MonitorableBuffer::getReceivedDataSizeInKbytes () pure virtual
Implemented in BlockStreamBuffer.
bool MonitorableBuffer::inputComplete () const
References input_complete_.
Referenced by ExpanderTracker::decideExpandingOrShrinking().
void MonitorableBuffer::setInputComplete ()
References input_complete_.
Referenced by claims::physical_operator::Expander::ExpandedWork(), and claims::physical_operator::ExchangeMerger::Receiver().
Member Data Documentation
bool MonitorableBuffer::input_complete_ private
Referenced by inputComplete(), and setInputComplete().
The documentation for this class was generated from the following files:
common/Block/MonitorableBuffer.h
common/Block/MonitorableBuffer.cpp