Claims: CodeGenerator Class Reference
CodeGenerator Class Reference
#include <CodeGenerator.h>
Public Member Functions
virtual ~CodeGenerator ()
const Module * getModule () const
llvm::IRBuilder * getBuilder () const
FunctionPassManager * getFunctionPassManager () const
ExecutionEngine * getExecutionEngine () const
void lock ()
void release ()
Static Public Member Functions
static CodeGenerator * getInstance ()
Private Member Functions
CodeGenerator ()
Private Attributes
Lock lock_
Static Private Attributes
static llvm::IRBuilder * builder_ =0
static Module * module_ =0
static FunctionPassManager * fpm_ =0
static CodeGenerator * instance_ =0
static ExecutionEngine * engine_ =0
Constructor & Destructor Documentation
CodeGenerator::~CodeGenerator () virtual
References builder_, fpm_, instance_, module_, and NULL.
CodeGenerator::CodeGenerator () private
References builder_, engine_, fpm_, and module_.
Referenced by getInstance().
Member Function Documentation
llvm::IRBuilder * CodeGenerator::getBuilder () const
References builder_.
Referenced by codegen_binary_op(), codegen_column(), codegen_const(), createAdd(), CreateDateCompareFunc(), createDivide(), createEqual(), createGreat(), createGreatEqual(), createLess(), createLessEqual(), createMinus(), createMod(), createMultiply(), createNotEqual(), CreateNValueCompareFunc(), getExprLLVMFucn(), getExprLLVMFuncForTwoTuples(), getFilterProcessFunc(), getMemcat(), getMemcpy(), storeTheReturnValue(), myllvm::test1(), test_call(), TEST_F(), test_reference(), and typePromotion().
ExecutionEngine * CodeGenerator::getExecutionEngine () const
References engine_.
Referenced by getExprFunc(), getExprFuncTwoTuples(), getFilterProcessFunc(), getMemcat(), getMemcpy(), myllvm::test(), myllvm::test1(), test_call(), TEST_F(), and test_reference().
FunctionPassManager * CodeGenerator::getFunctionPassManager () const
References fpm_.
Referenced by getExprLLVMFucn(), getExprLLVMFuncForTwoTuples(), getFilterProcessFunc(), getMemcat(), getMemcpy(), and test_reference().
CodeGenerator * CodeGenerator::getInstance () static
References CodeGenerator(), and instance_.
Referenced by codegen_binary_op(), codegen_column(), codegen_const(), createAdd(), CreateDateCompareFunc(), createDivide(), createEqual(), createGreat(), createGreatEqual(), createLess(), createLessEqual(), createMinus(), createMod(), createMultiply(), createNotEqual(), CreateNValueCompareFunc(), Environment::Environment(), get_another_one(), get_one(), getExprFunc(), getExprFuncTwoTuples(), getExprLLVMFucn(), getExprLLVMFuncForTwoTuples(), getFilterProcessFunc(), getMemcat(), getMemcpy(), CodeGenerationTest::SetUpTestCase(), storeTheReturnValue(), CodeGenerationTest::TearDownTestCase(), myllvm::test(), myllvm::test1(), test_call(), TEST_F(), test_reference(), and typePromotion().
const Module * CodeGenerator::getModule () const
References module_.
Referenced by CreateDateCompareFunc(), CreateNValueCompareFunc(), myllvm::test(), myllvm::test1(), and test_call().
void CodeGenerator::lock ()
References Lock::acquire(), and lock_.
Referenced by getExprFunc(), getExprFuncTwoTuples(), getFilterProcessFunc(), getMemcat(), and getMemcpy().
void CodeGenerator::release ()
References lock_, and Lock::release().
Referenced by getExprFunc(), getExprFuncTwoTuples(), getExprLLVMFucn(), getExprLLVMFuncForTwoTuples(), getFilterProcessFunc(), getMemcat(), and getMemcpy().
Member Data Documentation
llvm::IRBuilder * CodeGenerator::builder_ =0 static private
Referenced by CodeGenerator(), getBuilder(), and ~CodeGenerator().
ExecutionEngine * CodeGenerator::engine_ =0 static private
Referenced by CodeGenerator(), and getExecutionEngine().
FunctionPassManager * CodeGenerator::fpm_ =0 static private
Referenced by CodeGenerator(), getFunctionPassManager(), and ~CodeGenerator().
CodeGenerator * CodeGenerator::instance_ =0 static private
Referenced by getInstance(), and ~CodeGenerator().
Lock CodeGenerator::lock_ private
Referenced by lock(), and release().
Module * CodeGenerator::module_ =0 static private
Referenced by CodeGenerator(), getModule(), and ~CodeGenerator().
The documentation for this class was generated from the following files:
codegen/CodeGenerator.h
codegen/CodeGenerator.cpp