Claims: ClientListenerLogging Class Reference
ClientListenerLogging Class Reference
#include <Logging.h>
Static Public Member Functions
static void log (const char *format,...)
static void elog (const char *format,...)
Member Function Documentation
void ClientListenerLogging::elog (const char * format, ...) static
References RawElog().
void ClientListenerLogging::log (const char * format, ...) static
References RawLog().
Referenced by ClientListener::configure(), ClientListener::receiveHandler(), ClientListener::sendHandler(), and ClientListener::write().
The documentation for this class was generated from the following files:
common/Logging.h
common/Logging.cpp