Claims: BlockContainer Class Reference
BlockContainer Class Reference
#include <BlockContainer.h>
Public Member Functions
BlockContainer (unsigned size)
virtual ~BlockContainer ()
unsigned GetMaxSize () const
unsigned GetCurSize () const
unsigned GetRestSize () const
void reset ()
void IncreaseActualSize (unsigned size)
void copy (BlockContainer &block)
Public Member Functions inherited from Block
Block (unsigned BlockSize)
Block (const Block &block)
Block (const unsigned &size, const void *start)
virtual ~Block ()
void * getBlock () const
void setBlock (void *)
unsigned getsize () const
unsigned setsize (const unsigned &size)
bool isIsReference () const
void setIsReference (bool isReference)
Private Attributes
unsigned actual_size_
Additional Inherited Members
Protected Attributes inherited from Block
unsigned BlockSize
char * start
Constructor & Destructor Documentation
BlockContainer::BlockContainer (unsigned size)
BlockContainer::~BlockContainer () virtual
Member Function Documentation
void BlockContainer::copy (BlockContainer & block)
Copy the block content and the acutal_size_
References actual_size_, Block::getBlock(), GetCurSize(), and Block::getsize().
unsigned BlockContainer::GetCurSize () const
References actual_size_.
Referenced by copy(), claims::physical_operator::ExchangeMerger::Receiver(), and claims::physical_operator::ExchangeSenderPipeline::Sender().
unsigned BlockContainer::GetMaxSize () const
References Block::getsize().
unsigned BlockContainer::GetRestSize () const
References actual_size_, and Block::getsize().
Referenced by claims::physical_operator::ExchangeMerger::Receiver(), and claims::physical_operator::ExchangeSenderPipeline::Sender().
void BlockContainer::IncreaseActualSize (unsigned size)
References actual_size_, and Block::getsize().
Referenced by claims::physical_operator::ExchangeMerger::Receiver(), and claims::physical_operator::ExchangeSenderPipeline::Sender().
void BlockContainer::reset ()
References actual_size_.
Referenced by claims::physical_operator::ExchangeMerger::Receiver(), and claims::physical_operator::ExchangeSenderPipeline::Sender().
Member Data Documentation
unsigned BlockContainer::actual_size_ private
Referenced by copy(), GetCurSize(), GetRestSize(), IncreaseActualSize(), and reset().
The documentation for this class was generated from the following files:
common/Block/BlockContainer.h
common/Block/BlockContainer.cpp