Claims: HdfsLoader Class Reference
HdfsLoader Class Reference
#include <Hdfsloader.h>
Public Member Functions
HdfsLoader ()
HdfsLoader (TableDescriptor *tableDescriptor, const char c_separator= '|', const char r_separator= '\n', open_flag open_flag_=APPENDD)
HdfsLoader (const char c_separator, const char r_separator, std::vector< std::string > file_name, TableDescriptor *tableDescriptor, open_flag open_flag_=CREATEE)
virtual ~HdfsLoader ()
const char get_c_separator ()
const char get_r_separator ()
vector< string > get_file_list ()
bool insertRecords ()
bool load (double sample_rate=1)
bool append (std::string tuple_string)
Public Attributes
TableDescriptor * table_descriptor_
unsigned long row_id
vector< PartitionFunction * > partition_functin_list_
vector< int > partition_key_index
Private Attributes
Connector * connector_
unsigned block_size
const char col_separator
const char row_separator
std::vector< std::string > file_list
vector< vector< string > > writepath
Block * sblock
std::string s_record
vector< vector
< BlockStreamBase * > > pj_buffer
vector< vector< unsigned long > > blocks_per_partition
vector< vector< unsigned long > > tuples_per_partition
vector< SubTuple * > sub_tuple_generator
Schema * table_schema
vector< Schema * > projection_schema
open_flag open_flag_
Constructor & Destructor Documentation
HdfsLoader::HdfsLoader ()
HdfsLoader::HdfsLoader (TableDescriptor * tableDescriptor, const char c_separator = '|', const char r_separator = '\n', open_flag open_flag_ = APPENDD)
References APPENDD, BLOCK_SIZE, block_size, blocks_per_partition, BlockStreamBase::createBlock(), ProjectionDescriptor::getAttributeIndex(), ProjectionDescriptor::getAttributeList(), Partitioner::getNumberOfPartitions(), TableDescriptor::getNumberOfProjection(), Partitioner::getPartitionBlocks(), Partitioner::getPartitionCardinality(), ProjectionDescriptor::getPartitioner(), Partitioner::getPartitionFunction(), Partitioner::getPartitionKey(), ProjectionDescriptor::getProjectionID(), TableDescriptor::getProjectoin(), TableDescriptor::getRowNumber(), ProjectionDescriptor::getSchema(), TableDescriptor::getSchema(), partition_functin_list_, partition_key_index, pj_buffer, projection_schema, row_id, sblock, sub_tuple_generator, table_descriptor_, table_schema, tuples_per_partition, and writepath.
HdfsLoader::HdfsLoader (const char c_separator, const char r_separator, std::vector< std::string > file_name, TableDescriptor * tableDescriptor, open_flag open_flag_ = CREATEE)
References APPENDD, BLOCK_SIZE, block_size, blocks_per_partition, BlockStreamBase::createBlock(), ProjectionDescriptor::getAttributeIndex(), ProjectionDescriptor::getAttributeList(), Partitioner::getNumberOfPartitions(), TableDescriptor::getNumberOfProjection(), Partitioner::getPartitionBlocks(), Partitioner::getPartitionCardinality(), ProjectionDescriptor::getPartitioner(), Partitioner::getPartitionFunction(), Partitioner::getPartitionKey(), ProjectionDescriptor::getProjectionID(), TableDescriptor::getProjectoin(), TableDescriptor::getRowNumber(), ProjectionDescriptor::getSchema(), TableDescriptor::getSchema(), partition_functin_list_, partition_key_index, pj_buffer, projection_schema, row_id, sblock, sub_tuple_generator, table_descriptor_, table_schema, tuples_per_partition, and writepath.
HdfsLoader::~HdfsLoader () virtual
References connector_, file_list, row_id, table_descriptor_, and writepath.
Referenced by load_tpc_h_4_partition().
Member Function Documentation
bool HdfsLoader::append (std::string tuple_string)
References blocks_per_partition, Connector::closeFiles(), connector_, Connector::flush(), Block::getBlock(), Partitioner::getNumberOfPartitions(), TableDescriptor::getNumberOfProjection(), ProjectionDescriptor::getPartitioner(), TableDescriptor::getProjectoin(), Block::getsize(), insertRecords(), Config::local_disk_mode, open_flag_, Connector::openFiles(), pj_buffer, Partitioner::RegisterPartitionWithNumberOfBlocks(), row_id, s_record, sblock, TableDescriptor::setRowNumber(), table_descriptor_, Partitioner::UpdatePartitionWithNumberOfChunksToBlockManager(), and writepath.
Referenced by claims::stmt_handler::InsertExec::Execute(), and inmemory_append_test().
const char HdfsLoader::get_c_separator ()
References col_separator.
vector< string > HdfsLoader::get_file_list ()
References file_list.
const char HdfsLoader::get_r_separator ()
References row_separator.
bool HdfsLoader::insertRecords ()
for testing begin/
for testing end/
References blocks_per_partition, col_separator, connector_, Connector::flush(), Block::getBlock(), TableDescriptor::getNumberOfProjection(), Block::getsize(), Schema::getTupleMaxSize(), partition_functin_list_, partition_key_index, pj_buffer, projection_schema, row_id, s_record, sblock, sub_tuple_generator, t_u_long, table_descriptor_, table_schema, Schema::toValue(), and tuples_per_partition.
Referenced by append(), and load().
bool HdfsLoader::load (double sample_rate = 1)
for testing begin/
for testing end/
References Partitioner::allPartitionBound(), APPENDD, blocks_per_partition, Connector::closeFiles(), connector_, CREATEE, file_list, Connector::flush(), Catalog::getBindingModele(), Block::getBlock(), Catalog::getInstance(), Partitioner::getNumberOfPartitions(), TableDescriptor::getNumberOfProjection(), ProjectionDescriptor::getPartitioner(), TableDescriptor::getProjectoin(), Block::getsize(), insertRecords(), Config::local_disk_mode, open_flag_, Connector::openFiles(), pj_buffer, Partitioner::RegisterPartitionWithNumberOfBlocks(), row_id, row_separator, s_record, sblock, TableDescriptor::setRowNumber(), table_descriptor_, ProjectionBinding::UnbindingEntireProjection(), Partitioner::UpdatePartitionWithNumberOfChunksToBlockManager(), and writepath.
Referenced by append_test(), create_load_test(), claims::stmt_handler::LoadExec::Execute(), load_tpc_h_4_partition(), and LoadData().
Member Data Documentation
unsigned HdfsLoader::block_size private
Referenced by HdfsLoader().
vector<vector <unsigned long> > HdfsLoader::blocks_per_partition private
Referenced by append(), HdfsLoader(), insertRecords(), and load().
const char HdfsLoader::col_separator private
Referenced by get_c_separator(), and insertRecords().
Connector* HdfsLoader::connector_ private
Referenced by append(), insertRecords(), load(), and ~HdfsLoader().
std::vector<std::string> HdfsLoader::file_list private
Referenced by get_file_list(), load(), and ~HdfsLoader().
open_flag HdfsLoader::open_flag_ private
Referenced by append(), and load().
vector<PartitionFunction*> HdfsLoader::partition_functin_list_
Referenced by HdfsLoader(), and insertRecords().
vector<int> HdfsLoader::partition_key_index
Referenced by HdfsLoader(), and insertRecords().
vector< vector<BlockStreamBase*> > HdfsLoader::pj_buffer private
Referenced by append(), HdfsLoader(), insertRecords(), and load().
vector<Schema*> HdfsLoader::projection_schema private
Referenced by HdfsLoader(), and insertRecords().
unsigned long HdfsLoader::row_id
Referenced by append(), HdfsLoader(), insertRecords(), load(), and ~HdfsLoader().
const char HdfsLoader::row_separator private
Referenced by get_r_separator(), and load().
std::string HdfsLoader::s_record private
Referenced by append(), insertRecords(), and load().
Block* HdfsLoader::sblock private
Referenced by append(), HdfsLoader(), insertRecords(), and load().
vector<SubTuple*> HdfsLoader::sub_tuple_generator private
Referenced by HdfsLoader(), and insertRecords().
TableDescriptor* HdfsLoader::table_descriptor_
Referenced by append(), HdfsLoader(), insertRecords(), load(), and ~HdfsLoader().
Schema* HdfsLoader::table_schema private
Referenced by HdfsLoader(), and insertRecords().
vector<vector <unsigned long> > HdfsLoader::tuples_per_partition private
Referenced by HdfsLoader(), and insertRecords().
vector<vector<string> > HdfsLoader::writepath private
Referenced by append(), HdfsLoader(), load(), and ~HdfsLoader().
The documentation for this class was generated from the following files:
Loader/Hdfsloader.h
Loader/Hdfsloader.cpp