Claims: PartitionStorage::PartitionReaderItetaor Class Reference
PartitionStorage::PartitionReaderItetaor Class Reference
#include <PartitionStorage.h>
Public Member Functions
PartitionReaderItetaor (PartitionStorage *partition_storage)
virtual ~PartitionReaderItetaor ()
virtual ChunkReaderIterator * nextChunk ()
virtual bool nextBlock (BlockStreamBase *&block)
Protected Attributes
PartitionStorage * ps
unsigned chunk_cur_
ChunkReaderIterator * chunk_it_
Constructor & Destructor Documentation
PartitionStorage::PartitionReaderItetaor::PartitionReaderItetaor (PartitionStorage * partition_storage)
PartitionStorage::PartitionReaderItetaor::~PartitionReaderItetaor () virtual
Member Function Documentation
bool PartitionStorage::PartitionReaderItetaor::nextBlock (BlockStreamBase *& block) virtual
Reimplemented in PartitionStorage::AtomicPartitionReaderIterator.
Referenced by insert_into_hash_table_from_projection(), and claims::physical_operator::PhysicalProjectionScan::Next().
ChunkReaderIterator * PartitionStorage::PartitionReaderItetaor::nextChunk () virtual
Reimplemented in PartitionStorage::AtomicPartitionReaderIterator.
References PartitionStorage::number_of_chunks_.
Referenced by bottomLayerCollecting::askForNextBlock(), IndexScanIterator::askForNextBlock(), PartitionStorage::AtomicPartitionReaderIterator::nextBlock(), and claims::physical_operator::PhysicalProjectionScan::Open().
Member Data Documentation
unsigned PartitionStorage::PartitionReaderItetaor::chunk_cur_ protected
ChunkReaderIterator* PartitionStorage::PartitionReaderItetaor::chunk_it_ protected
PartitionStorage* PartitionStorage::PartitionReaderItetaor::ps protected
The documentation for this class was generated from the following files:
storage/PartitionStorage.h
storage/PartitionStorage.cpp