Claims: ExchangeTracker Class Reference
ExchangeTracker Class Reference
#include <exchange_tracker.h>
Classes
class ExchangeTrackerActor
Public Member Functions
ExchangeTracker ()
virtual ~ExchangeTracker ()
bool RegisterExchange (ExchangeID exchange_id, std::string port)
void LogoutExchange (const ExchangeID &exchange_id)
bool AskForSocketConnectionInfo (ExchangeID exchange_id, NodeID target_id, NodeAddress &node_addr)
void printAllExchangeId () const
Private Attributes
Theron::EndPoint * endpoint
Theron::Framework * framework
Theron::Actor * actor
boost::unordered_map
< ExchangeID, std::string > id_to_port
Logging * logging_
Lock lock_
Friends
class RegisterActor
Constructor & Destructor Documentation
ExchangeTracker::ExchangeTracker ()
References actor, endpoint, framework, Environment::getEndPoint(), Environment::getInstance(), Environment::getNodeID(), Logging::log(), and logging_.
ExchangeTracker::~ExchangeTracker () virtual
References actor, framework, and logging_.
Member Function Documentation
bool ExchangeTracker::AskForSocketConnectionInfo (ExchangeID exchange_id, NodeID target_id, NodeAddress & node_addr)
TODO: In current version, the request is only tried once. In the future, the request should be sent repeatedly until the reply is received or the times of timeouts exceeds some threshold.
References curtick(), endpoint, framework, NodeRegisterMessage::get_ip(), NodeAddress::ip, NodeRegisterMessage::ip, NodeAddress::port, NodeRegisterMessage::port, and TimeOutReceiver::~TimeOutReceiver().
Referenced by claims::physical_operator::ExchangeSender::ConnectToUpper(), and claims::physical_operator::ExchangeMerger::IsOtherMergersRegistered().
void ExchangeTracker::LogoutExchange (const ExchangeID & exchange_id)
References Lock::acquire(), id_to_port, lock_, Logging::log(), logging_, and Lock::release().
Referenced by claims::physical_operator::ExchangeMerger::Close().
void ExchangeTracker::printAllExchangeId () const
References id_to_port.
bool ExchangeTracker::RegisterExchange (ExchangeID exchange_id, std::string port)
References Lock::acquire(), id_to_port, lock_, Logging::log(), logging_, and Lock::release().
Referenced by claims::physical_operator::ExchangeMerger::RegisterExchange().
Friends And Related Function Documentation
friend class RegisterActor friend
RegisterActor
Member Data Documentation
Theron::Actor* ExchangeTracker::actor private
Referenced by ExchangeTracker(), and ~ExchangeTracker().
Theron::EndPoint* ExchangeTracker::endpoint private
Referenced by AskForSocketConnectionInfo(), and ExchangeTracker().
Theron::Framework* ExchangeTracker::framework private
Referenced by AskForSocketConnectionInfo(), ExchangeTracker(), and ~ExchangeTracker().
boost::unordered_map<ExchangeID,std::string> ExchangeTracker::id_to_port private
Referenced by LogoutExchange(), printAllExchangeId(), and RegisterExchange().
Lock ExchangeTracker::lock_ private
Referenced by LogoutExchange(), and RegisterExchange().
Logging* ExchangeTracker::logging_ private
Referenced by ExchangeTracker(), LogoutExchange(), RegisterExchange(), and ~ExchangeTracker().
The documentation for this class was generated from the following files:
Executor/exchange_tracker.h
Executor/exchange_tracker.cpp