Claims: CCSBNodeGroup< T > Class Template Reference
CCSBNodeGroup< T > Class Template Reference
#include <CSBPlusTree.h>
Public Member Functions
CCSBNodeGroup ()
CCSBNodeGroup (unsigned n)
~CCSBNodeGroup ()
unsigned getUsedNodes ()
void nodeCountIncrement ()
virtual CCSBNodeGroup< T > * getHeaderNG ()
virtual void setHeaderNG (CCSBNodeGroup< T > *header)
virtual CCSBNodeGroup< T > * getTailerNG ()
virtual void setTailerNG (CCSBNodeGroup< T > *tailer)
virtual bool setUsedNodes (unsigned n)
virtual CCSBNode< T > * getNode (unsigned i)
virtual void setNode (unsigned i, CCSBNode< T > *node)
virtual bool Insert (unsigned node_off, T key)
virtual void DeleteChildren ()
virtual bool serialize (FILE *filename)
virtual bool deserialize (FILE *filename)
Public Attributes
unsigned used_nodes
Constructor & Destructor Documentation
template<typename T> CCSBNodeGroup< T >::CCSBNodeGroup () inline
template<typename T> CCSBNodeGroup< T >::CCSBNodeGroup (unsigned n) inline
template<typename T> CCSBNodeGroup< T >::~CCSBNodeGroup () inline
Member Function Documentation
template<typename T> virtual void CCSBNodeGroup< T >::DeleteChildren () inline virtual
Reimplemented in CCSBLeafNodeGroup< T >, and CCSBInternalNodeGroup< T >.
template<typename T> virtual bool CCSBNodeGroup< T >::deserialize (FILE * filename) inline virtual
Reimplemented in CCSBLeafNodeGroup< T >, and CCSBInternalNodeGroup< T >.
template<typename T> virtual CCSBNodeGroup<T>* CCSBNodeGroup< T >::getHeaderNG () inline virtual
Reimplemented in CCSBLeafNodeGroup< T >.
Referenced by CSBPlusTree< T >::Insert(), and CSBPlusTree< T >::printDoubleLinkedList().
template<typename T> virtual CCSBNode<T>* CCSBNodeGroup< T >::getNode (unsigned i) inline virtual
Reimplemented in CCSBLeafNodeGroup< T >, and CCSBInternalNodeGroup< T >.
Referenced by CSBPlusTree< T >::BulkLoad(), CSBPlusTree< T >::deserialize(), CSBPlusTree< T >::Insert(), CSBPlusTree< T >::makeLeafNodeGroup(), CSBPlusTree< T >::printDoubleLinkedList(), CSBPlusTree< T >::rangeQuery(), CSBPlusTree< T >::Search(), and CSBPlusTree< T >::SearchLeafNode().
template<typename T> virtual CCSBNodeGroup<T>* CCSBNodeGroup< T >::getTailerNG () inline virtual
Reimplemented in CCSBLeafNodeGroup< T >.
Referenced by CSBPlusTree< T >::Insert(), CSBPlusTree< T >::printDoubleLinkedList(), CSBPlusTree< T >::rangeQuery(), CSBPlusTree< T >::Search(), and CSBPlusTree< T >::SearchLeafNode().
template<typename T> unsigned CCSBNodeGroup< T >::getUsedNodes () inline
Referenced by CSBPlusTree< T >::deserialize(), CSBPlusTree< T >::Insert(), CSBPlusTree< T >::makeInternalNodeGroup(), CSBPlusTree< T >::printDoubleLinkedList(), CSBPlusTree< T >::rangeQuery(), CSBPlusTree< T >::Search(), and CSBPlusTree< T >::SearchLeafNode().
template<typename T> virtual bool CCSBNodeGroup< T >::Insert (unsigned node_off, T key) inline virtual
Reimplemented in CCSBInternalNodeGroup< T >.
template<typename T> void CCSBNodeGroup< T >::nodeCountIncrement () inline
template<typename T> virtual bool CCSBNodeGroup< T >::serialize (FILE * filename) inline virtual
Reimplemented in CCSBLeafNodeGroup< T >, and CCSBInternalNodeGroup< T >.
template<typename T> virtual void CCSBNodeGroup< T >::setHeaderNG (CCSBNodeGroup< T > * header) inline virtual
Reimplemented in CCSBLeafNodeGroup< T >.
Referenced by CSBPlusTree< T >::BulkLoad(), CSBPlusTree< T >::deserialize(), CSBPlusTree< T >::Insert(), and CSBPlusTree< T >::makeLeafNodeGroup().
template<typename T> virtual void CCSBNodeGroup< T >::setNode (unsigned i, CCSBNode< T > * node) inline virtual
Reimplemented in CCSBLeafNodeGroup< T >, and CCSBInternalNodeGroup< T >.
Referenced by CSBPlusTree< T >::Insert().
template<typename T> virtual void CCSBNodeGroup< T >::setTailerNG (CCSBNodeGroup< T > * tailer) inline virtual
Reimplemented in CCSBLeafNodeGroup< T >.
Referenced by CSBPlusTree< T >::BulkLoad(), CSBPlusTree< T >::deserialize(), CSBPlusTree< T >::Insert(), and CSBPlusTree< T >::makeLeafNodeGroup().
template<typename T> virtual bool CCSBNodeGroup< T >::setUsedNodes (unsigned n) inline virtual
Reimplemented in CCSBLeafNodeGroup< T >, and CCSBInternalNodeGroup< T >.
Referenced by CSBPlusTree< T >::Insert().
Member Data Documentation
template<typename T> unsigned CCSBNodeGroup< T >::used_nodes
Referenced by CSBPlusTree< T >::BulkLoad(), and CSBPlusTree< T >::makeLeafNodeGroup().
The documentation for this class was generated from the following file:
IndexManager/CSBPlusTree.h