Claims: ExpressionCalculator Class Reference
ExpressionCalculator Class Reference
#include <ExpressionCalculator.h>
Public Member Functions
ExpressionCalculator ()
virtual ~ExpressionCalculator ()
Static Public Member Functions
static void calcuate (Expression &exp, ExpressionItem &result)
static void calcualte (Expression &exp, ExpressionItemStack &stack)
static void compute (ExpressionItem operator_item, ExpressionItemStack &stack)
static void computes (ExpressionItem operator_item, ExpressionItemStack &stack)
static data_type getOutputType (vector< ExpressionItem > &exp)
static column_type getOutputType_ (vector< ExpressionItem > &exp)
Static Private Member Functions
static bool isComposeOperator (op_type tp)
static void reverse_stack (ExpressionItemStack &stack)
Constructor & Destructor Documentation
ExpressionCalculator::ExpressionCalculator ()
ExpressionCalculator::~ExpressionCalculator () virtual
Member Function Documentation
static void ExpressionCalculator::calcualte (Expression & exp, ExpressionItemStack & stack) inline static
References compute(), isComposeOperator(), and ExpressionItem::operator_type.
Referenced by calcuate().
static void ExpressionCalculator::calcuate (Expression & exp, ExpressionItem & result) inline static
References calcualte().
Referenced by do_case(), test_add(), test_add_(), test_case_exp(), test_cast(), test_com_less(), test_multiple(), test_multiple_(), test_substring(), test_trim(), and test_upper().
void ExpressionCalculator::compute (ExpressionItem operator_item, ExpressionItemStack & stack) static
References add(), andop(), cast(), compare_equal(), compare_great(), compare_great_equal(), compare_less(), compare_less_equal(), compare_not_equal(), ExpressionItem::const_type, ExpressionItem::content, do_case(), mins(), mul(), notop(), ExpressionItem::op, express_operator::op_, op_add, op_and, op_case, op_cast, op_com_EQ, op_com_G, op_com_GEQ, op_com_L, op_com_LEQ, op_com_NEQ, op_mins, op_multiple, op_not, op_or, op_substring, op_trim, op_upper, orop(), reverse_stack(), substring(), trim(), ExpressionItem::type, and upper().
Referenced by calcualte().
void ExpressionCalculator::computes (ExpressionItem operator_item, ExpressionItemStack & stack) static
References adds(), ExpressionItem::const_type, ExpressionItem::content, do_case(), get_compare_return_type(), minss(), muls(), ExpressionItem::op, express_operator::op_, op_add, op_and, op_case, op_cast, op_com_EQ, op_com_G, op_com_GEQ, op_com_L, op_com_LEQ, op_com_NEQ, op_mins, op_multiple, op_not, op_or, op_substring, op_trim, op_upper, reverse_stack(), and ExpressionItem::type.
Referenced by getOutputType(), and getOutputType_().
data_type ExpressionCalculator::getOutputType (std::vector< ExpressionItem > & exp) static
References computes(), isComposeOperator(), and ExpressionItem::operator_type.
column_type ExpressionCalculator::getOutputType_ (std::vector< ExpressionItem > & exp) static
References computes(), isComposeOperator(), ExpressionItem::operator_type, and t_string.
static bool ExpressionCalculator::isComposeOperator (op_type tp) inline static private
Compose operator refers to a kind of operators, the number of input parameter of witch is decided by the semantic. e.g., CASE WHEN ... THEN... [WHEN ... THEN...][N] ELSE ..... END
References op_case.
Referenced by calcualte(), getOutputType(), and getOutputType_().
static void ExpressionCalculator::reverse_stack (ExpressionItemStack & stack) inline static private
Referenced by compute(), and computes().
The documentation for this class was generated from the following files:
common/ExpressionCalculator.h
common/ExpressionCalculator.cpp