My Project: claims::logical_operator::LogicalAggregation Class Reference
claims::logical_operator::LogicalAggregation Class Reference
class description: maintain operator property that results from executing aggregation operator, and generate corresponding physical operator.
#include <logical_aggregation.h>
Public Types
enum AggregationStyle { kAgg, kReparGlobalAgg, kLocalAggReparGlobalAgg }
Public Member Functions
LogicalAggregation (std::vector< Attribute > group_by_attribute_list, std::vector< Attribute > aggregation_attribute_list, std::vector< BlockStreamAggregationIterator::State::aggregation > aggregation_function_list, LogicalOperator *child)
Public Member Functions inherited from claims::logical_operator::LogicalOperator
virtual bool GetOptimalPhysicalPlan (Requirement requirement, PhysicalPlanDescriptor &physical_plan_descriptor, const unsigned &block_size=4096 *1024)
Protected Member Functions
PlanContext GetPlanContext ()
BlockStreamIteratorBase * GetPhysicalPlan (const unsigned &block_size)
Protected Member Functions inherited from claims::logical_operator::LogicalOperator
Schema * GetSchema (const std::vector< Attribute > &) const
Schema * GetSchema (const std::vector< Attribute > &, const std::vector< Attribute > &) const
std::vector< NodeID > GetInvolvedNodeID (const PlanPartitioner &) const
std::vector< NodeIP > ConvertNodeIDListToNodeIPList (const std::vector< NodeID > &) const
PhysicalPlanDescriptor GetBestPhysicalPlanDescriptor (const std::vector< PhysicalPlanDescriptor >) const
int GetIdInAttributeList (const std::vector< Attribute > &attributes, const Attribute &attribute) const
void set_operator_type (OperatorType operator_type)
Detailed Description
class description: maintain operator property that results from executing aggregation operator, and generate corresponding physical operator.
as for the implementation of avg() based on sum()/count(), so it's necessary to change the output_schema of private aggregation in kLocalAggReparGlobalAgg aggregation style. Note: kReparAndGlobalAgg node isn't implemented.
Member Enumeration Documentation
enum claims::logical_operator::LogicalAggregation::AggregationStyle
AggregationStyle describe the implementation of aggregation judged from whether the data distribution agrees with the group by attributes or the data is local.
Constructor & Destructor Documentation
claims::logical_operator::LogicalAggregation::LogicalAggregation (std::vector< Attribute > group_by_attribute_list, std::vector< Attribute > aggregation_attribute_list, std::vector< BlockStreamAggregationIterator::State::aggregation > aggregation_function_list, LogicalOperator * child)
This is the default construct method of Aggregation. This logical operator creates a new plan context. group_by_attribute can be empty if it is scalar aggregation. count(*) aggregation can be expressed as 'count' aggregation function along with Attribute(ATTRIBUTE_ANY)
Member Function Documentation
BlockStreamIteratorBase * claims::logical_operator::LogicalAggregation::GetPhysicalPlan (const unsigned & block_size) protected virtual
generate corresponding physical plan tree, mainly set necessary state.
Note: if group_by_attribute_list_ is empty, the partition key is ATTRIBUTE_NULL
scalar aggregation allows parallel partitions to be partitioned in any fashion. In the current implementation, we use the first aggregation attribute as the partition attribute.
Implements claims::logical_operator::LogicalOperator.
References claims::logical_operator::LogicalOperator::GetPhysicalPlan(), claims::logical_operator::LogicalOperator::GetPlanContext(), GetPlanContext(), and Config::initial_degree_of_parallelism.
PlanContext claims::logical_operator::LogicalAggregation::GetPlanContext () protected virtual
get plan context resulting from executing aggregation operator. including corresponding attribute_list and property with partition info and communication cost.
repartition aggregation is currently simplified.
Implements claims::logical_operator::LogicalOperator.
References claims::logical_operator::PlanContext::GetAggregatedDatasize(), and claims::logical_operator::LogicalOperator::GetPlanContext().
Referenced by GetPhysicalPlan().
The documentation for this class was generated from the following files:
logical_operator/logical_aggregation.h
logical_operator/logical_aggregation.cpp