Claims: NodeTracker Class Reference
NodeTracker Class Reference
#include <NodeTracker.h>
Public Member Functions
virtual ~NodeTracker ()
int RegisterNode (NodeAddress)
std::string GetNodeIP (const NodeID &) const
std::vector< NodeID > GetNodeIDList () const
Static Public Member Functions
static NodeTracker * GetInstance ()
Private Member Functions
NodeTracker ()
Private Attributes
boost::unordered_map
< NodeAddress, NodeID > address_to_id_
unsigned allocate_cur_
Static Private Attributes
static NodeTracker * instance_ =0
Constructor & Destructor Documentation
NodeTracker::~NodeTracker () virtual
Referenced by ResourceManagerMaster::~ResourceManagerMaster().
NodeTracker::NodeTracker () private
Referenced by GetInstance().
Member Function Documentation
NodeTracker * NodeTracker::GetInstance () static
References instance_, and NodeTracker().
Referenced by claims::logical_operator::LogicalOperator::ConvertNodeIDListToNodeIPList(), claims::logical_operator::LogicalEqualJoin::DecideOutputDataflowProperty(), claims::logical_operator::LogicalScan::GetOptimalPhysicalPlan(), claims::logical_operator::LogicalFilter::GetOptimalPhysicalPlan(), claims::logical_operator::LogicalQueryPlanRoot::GetOptimalPhysicalPlan(), claims::logical_operator::LogicalQueryPlanRoot::GetPhysicalPlan(), claims::logical_operator::LogicalEqualJoin::GetPhysicalPlan(), ResourceManagerMaster::ResourceManagerMaster(), BlockManagerMaster::SendBindingMessage(), and BlockManagerMaster::SendUnbindingMessage().
std::vector< NodeID > NodeTracker::GetNodeIDList () const
References address_to_id_.
Referenced by claims::logical_operator::LogicalEqualJoin::DecideOutputDataflowProperty(), claims::logical_operator::LogicalScan::GetOptimalPhysicalPlan(), claims::logical_operator::LogicalFilter::GetOptimalPhysicalPlan(), and claims::logical_operator::LogicalQueryPlanRoot::GetOptimalPhysicalPlan().
std::string NodeTracker::GetNodeIP (const NodeID & target) const
References address_to_id_, and NULL.
Referenced by claims::logical_operator::LogicalOperator::ConvertNodeIDListToNodeIPList().
int NodeTracker::RegisterNode (NodeAddress new_node_address)
References address_to_id_, and allocate_cur_.
Referenced by ResourceManagerMaster::RegisterNewSlave().
Member Data Documentation
boost::unordered_map<NodeAddress,NodeID> NodeTracker::address_to_id_ private
Referenced by GetNodeIDList(), GetNodeIP(), and RegisterNode().
unsigned NodeTracker::allocate_cur_ private
Referenced by RegisterNode().
NodeTracker * NodeTracker::instance_ =0 static private
Referenced by GetInstance().
The documentation for this class was generated from the following files:
Resource/NodeTracker.h
Resource/NodeTracker.cpp