Claims: Partitioner Class Reference
Partitioner Class Reference
#include <Partitioner.h>
Public Member Functions
Partitioner ()
Partitioner (ProjectionID projection_id, unsigned number_of_partitions, PartitionFunction *partition_functin)
Partitioner (ProjectionID projection_id, unsigned number_of_partitions, const Attribute &partition_key, PartitionFunction *partition_functin)
virtual ~Partitioner ()
unsigned getNumberOfPartitions () const
bool bindPartitionToNode (PartitionOffset partition_id, NodeID target_node)
void unbindPartitionToNode (PartitionOffset partition_id)
void RegisterPartition (unsigned partitoin_key, unsigned number_of_chunks)
void RegisterPartitionWithNumberOfBlocks (unsigned partitoin_key, unsigned long number_of_blocks)
void UpdatePartitionWithNumberOfChunksToBlockManager (unsigned partitoin_offset, unsigned long number_of_blocks)
unsigned getPartitionDataSize (unsigned partitoin_index) const
unsigned long getPartitionCardinality (unsigned partitoin_index) const
unsigned getPartitionBlocks (unsigned partitoin_index) const
unsigned getPartitionChunks (unsigned partition_index) const
NodeID getPartitionLocation (unsigned partition_offset) const
void print ()
bool hasSamePartitionLocation (const Partitioner &target_partition) const
binding_mode get_binding_mode_ () const
PartitionFunction::PartitionStyle getPartitionFashion () const
Attribute getPartitionKey () const
PartitionFunction * getPartitionFunction () const
ProjectionID getProejctionID () const
bool allPartitionBound () const
vector< PartitionID > getPartitionIDList ()
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
Attribute * partition_key_
PartitionFunction * partition_function_
unsigned number_of_partitions_
vector< PartitionInfo * > partition_info_list
binding_mode mode_
ProjectionID projection_id_
Friends
class boost::serialization::access
Constructor & Destructor Documentation
Partitioner::Partitioner () inline
Partitioner::Partitioner (ProjectionID projection_id, unsigned number_of_partitions, PartitionFunction * partition_functin)
Partitioner::Partitioner (ProjectionID projection_id, unsigned number_of_partitions, const Attribute & partition_key, PartitionFunction * partition_functin)
References partition_info_list, partition_key_, and projection_id_.
Partitioner::~Partitioner () virtual
Member Function Documentation
bool Partitioner::allPartitionBound () const
References number_of_partitions_, and partition_info_list.
Referenced by ProjectionDescriptor::AllPartitionBound(), and HdfsLoader::load().
bool Partitioner::bindPartitionToNode (PartitionOffset partition_id, NodeID target_node)
References partition_info_list.
Referenced by ProjectionBinding::BindingEntireProjection().
binding_mode Partitioner::get_binding_mode_ () const inline
Referenced by ProjectionBinding::BindingEntireProjection(), hasSamePartitionLocation(), and ProjectionBinding::UnbindingEntireProjection().
unsigned Partitioner::getNumberOfPartitions () const
References PartitionFunction::getNumberOfPartitions(), and partition_function_.
Referenced by HdfsLoader::append(), ProjectionBinding::BindingEntireProjection(), BindingTest(), create_poc_data_four_partitions(), create_poc_data_one_partitions(), CreateProjection(), execting_test(), hasSamePartitionLocation(), HdfsLoader::HdfsLoader(), init_multi_node_tpc_h_envoriment_(), init_poc_environment(), init_single_node_tpc_h_envoriment_(), init_single_node_tpc_h_envoriment_ing(), init_single_node_tpc_h_envoriment_sort(), init_tt_environment(), HdfsLoader::load(), loadData(), claims::logical_operator::PlanPartitioner::PlanPartitioner(), RegisterPartition(), RegisterPartitionWithNumberOfBlocks(), startup_catalog(), startup_mulitple_node_environment_of_poc(), startup_multiple_node_environment(), startup_multiple_node_environment_of_stock(), startup_multiple_node_environment_of_tpch(), startup_single_node_environment_of_tpch(), startup_single_node_one_partition_environment_of_tpch(), statistic_manager_test(), test_CSBIndexBuilding(), test_index_scan_iterator(), test_logical_csb_index_building(), ProjectionBinding::UnbindingEntireProjection(), UpdatePartitionWithNumberOfChunksToBlockManager(), and variable_schema_test().
unsigned Partitioner::getPartitionBlocks (unsigned partitoin_index) const
References partition_info_list.
Referenced by HdfsLoader::HdfsLoader().
unsigned long Partitioner::getPartitionCardinality (unsigned partitoin_index) const
References partition_info_list.
Referenced by ProjectionDescriptor::getNumberOfTuplesOnPartition(), HdfsLoader::HdfsLoader(), and claims::logical_operator::PlanPartitioner::PlanPartitioner().
unsigned Partitioner::getPartitionChunks (unsigned partition_index) const
References partition_info_list.
Referenced by ProjectionBinding::BindingEntireProjection().
unsigned Partitioner::getPartitionDataSize (unsigned partitoin_index) const
References BLOCKSIZE_IN_KB, and partition_info_list.
Referenced by ProjectionBinding::BindingEntireProjection(), and ProjectionBinding::UnbindingEntireProjection().
PartitionFunction::PartitionStyle Partitioner::getPartitionFashion () const
References PartitionFunction::getPartitionFashion(), and partition_function_.
Referenced by claims::logical_operator::LogicalEqualJoin::IsHashOnLeftKey().
PartitionFunction * Partitioner::getPartitionFunction () const
References partition_function_.
Referenced by HdfsLoader::HdfsLoader(), and claims::logical_operator::PlanPartitioner::PlanPartitioner().
vector< PartitionID > Partitioner::getPartitionIDList ()
References partition_info_list.
Referenced by Catalog::getPartitionIDList().
Attribute Partitioner::getPartitionKey () const
References partition_key_.
Referenced by HdfsLoader::HdfsLoader(), claims::logical_operator::LogicalEqualJoin::IsHashOnLeftKey(), and claims::logical_operator::PlanPartitioner::PlanPartitioner().
NodeID Partitioner::getPartitionLocation (unsigned partition_offset) const
References OneToOne, and partition_info_list.
Referenced by claims::logical_operator::PlanPartitioner::PlanPartitioner(), and ProjectionBinding::UnbindingEntireProjection().
ProjectionID Partitioner::getProejctionID () const
References projection_id_.
Referenced by ProjectionBinding::BindingEntireProjection(), and ProjectionBinding::UnbindingEntireProjection().
bool Partitioner::hasSamePartitionLocation (const Partitioner & target_partition) const
in the current version, any the location detection in OneToMany mode is ommited.
References get_binding_mode_(), getNumberOfPartitions(), mode_, OneToMany, and partition_info_list.
void Partitioner::print ()
void Partitioner::RegisterPartition (unsigned partitoin_key, unsigned number_of_chunks)
References getNumberOfPartitions(), and partition_info_list.
Referenced by BindingTest(), create_poc_data_four_partitions(), create_poc_data_one_partitions(), CreateProjection(), execting_test(), init_multi_node_tpc_h_envoriment_(), init_poc_environment(), init_single_node_tpc_h_envoriment_(), init_single_node_tpc_h_envoriment_ing(), init_single_node_tpc_h_envoriment_sort(), init_tt_environment(), loadData(), startup_catalog(), startup_mulitple_node_environment_of_poc(), startup_multiple_node_environment(), startup_multiple_node_environment_of_stock(), startup_multiple_node_environment_of_tpch(), startup_single_node_environment_of_tpch(), startup_single_node_one_partition_environment_of_tpch(), statistic_manager_test(), test_CSBIndexBuilding(), test_index_scan_iterator(), test_logical_csb_index_building(), and variable_schema_test().
void Partitioner::RegisterPartitionWithNumberOfBlocks (unsigned partitoin_key, unsigned long number_of_blocks)
References getNumberOfPartitions(), and partition_info_list.
Referenced by HdfsLoader::append(), and HdfsLoader::load().
template<class Archive > void Partitioner::serialize (Archive & ar, const unsigned int version) inline private
References NULL.
void Partitioner::unbindPartitionToNode (PartitionOffset partition_id)
References partition_info_list.
Referenced by ProjectionBinding::UnbindingEntireProjection().
void Partitioner::UpdatePartitionWithNumberOfChunksToBlockManager (unsigned partitoin_offset, unsigned long number_of_blocks)
References BlockManagerMaster::getInstance(), getNumberOfPartitions(), MEMORY, mode_, OneToOne, partition_info_list, and BlockManagerMaster::SendBindingMessage().
Referenced by HdfsLoader::append(), and HdfsLoader::load().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
binding_mode Partitioner::mode_ private
Referenced by hasSamePartitionLocation(), and UpdatePartitionWithNumberOfChunksToBlockManager().
unsigned Partitioner::number_of_partitions_ private
Referenced by allPartitionBound().
PartitionFunction* Partitioner::partition_function_ private
Referenced by getNumberOfPartitions(), getPartitionFashion(), and getPartitionFunction().
vector<PartitionInfo*> Partitioner::partition_info_list private
partition_info_list is a list, each element corresponds to a single partition and maintains the number of blocks in the partition as well as the binding location.
Referenced by allPartitionBound(), bindPartitionToNode(), getPartitionBlocks(), getPartitionCardinality(), getPartitionChunks(), getPartitionDataSize(), getPartitionIDList(), getPartitionLocation(), hasSamePartitionLocation(), Partitioner(), RegisterPartition(), RegisterPartitionWithNumberOfBlocks(), unbindPartitionToNode(), and UpdatePartitionWithNumberOfChunksToBlockManager().
Attribute* Partitioner::partition_key_ private
Referenced by getPartitionKey(), and Partitioner().
ProjectionID Partitioner::projection_id_ private
Referenced by getProejctionID(), and Partitioner().
The documentation for this class was generated from the following files:
Catalog/Partitioner.h
Catalog/Partitioner.cpp