Claims: InstanceResourceManager Class Reference
InstanceResourceManager Class Reference
#include <ResourceManagerSlave.h>
Public Member Functions
InstanceResourceManager ()
virtual ~InstanceResourceManager ()
NodeID Register ()
void ReportStorageBudget (StorageBudgetMessage &)
void setStorageBudget (unsigned long memory, unsigned long disk)
Private Attributes
Theron::Framework * framework_
Logging * logging_
CPUResourceManager cpu_resource_
Constructor & Destructor Documentation
InstanceResourceManager::InstanceResourceManager ()
References framework_, Environment::getInstance(), and logging_.
InstanceResourceManager::~InstanceResourceManager () virtual
References framework_, and logging_.
Member Function Documentation
NodeID InstanceResourceManager::Register ()
References Logging::elog(), framework_, Environment::getInstance(), Environment::getIp(), Environment::getPort(), Logging::log(), logging_, and TimeOutReceiver::TimeOutWait().
Referenced by Environment::initializeResourceManager().
void InstanceResourceManager::ReportStorageBudget (StorageBudgetMessage & message)
References framework_, and ResourceManagerMasterName.
Referenced by BlockManager::initialize().
void InstanceResourceManager::setStorageBudget (unsigned long memory, unsigned long disk)
Member Data Documentation
CPUResourceManager InstanceResourceManager::cpu_resource_ private
Theron::Framework* InstanceResourceManager::framework_ private
Referenced by InstanceResourceManager(), Register(), ReportStorageBudget(), and ~InstanceResourceManager().
Logging* InstanceResourceManager::logging_ private
Referenced by InstanceResourceManager(), Register(), and ~InstanceResourceManager().
The documentation for this class was generated from the following files:
Resource/ResourceManagerSlave.h
Resource/ResourceManagerSlave.cpp