Claims: ThreadPoolLogging Class Reference
ThreadPoolLogging Class Reference
#include <Logging.h>
Static Public Member Functions
static void log (const char *format,...)
static void elog (const char *format,...)
Member Function Documentation
void ThreadPoolLogging::elog (const char * format, ...) static
References RawElog().
Referenced by ThreadPool::bind_cpu().
void ThreadPoolLogging::log (const char * format, ...) static
References RawLog().
Referenced by ThreadPool::bind_cpu(), and ThreadPool::thread_exec().
The documentation for this class was generated from the following files:
common/Logging.h
common/Logging.cpp