Claims: BlanceMatcher Class Reference
BlanceMatcher Class Reference
#include <BlanceMatcher.h>
Public Member Functions
virtual ~BlanceMatcher ()
bool projectsInput (string filename, list< string > project)
string matcher (string filename, BlockManagerId bmi)
Static Public Member Functions
static BlanceMatcher * getInstance ()
Private Member Functions
BlanceMatcher ()
Private Attributes
map< string, list< string > > projects_
map< string, list< string > > coming_ip_
Static Private Attributes
static BlanceMatcher * blancematcher_ =0
Constructor & Destructor Documentation
BlanceMatcher::~BlanceMatcher () virtual
BlanceMatcher::BlanceMatcher () private
Member Function Documentation
static BlanceMatcher* BlanceMatcher::getInstance () inline static
Referenced by BlockManagerMaster::BlockManagerMasterActor::matcherReceiver(), and BlockManagerMaster::testForPoc().
string BlanceMatcher::matcher (string filename, BlockManagerId bmi)
References BlockManagerId::blockManagerId, coming_ip_, and projects_.
Referenced by BlockManagerMaster::BlockManagerMasterActor::matcherReceiver().
bool BlanceMatcher::projectsInput (string filename, list< string > project)
References projects_.
Referenced by BlockManagerMaster::testForPoc().
Member Data Documentation
BlanceMatcher * BlanceMatcher::blancematcher_ =0 static private
map<string, list<string> > BlanceMatcher::coming_ip_ private
Referenced by matcher().
map<string, list<string> > BlanceMatcher::projects_ private
Referenced by matcher(), and projectsInput().
The documentation for this class was generated from the following files:
storage/BlanceMatcher.h
storage/BlanceMatcher.cpp