Claims: CCSBInternalNodeGroup< T > Class Template Reference
CCSBInternalNodeGroup< T > Class Template Reference
#include <CSBPlusTree.h>
Public Member Functions
CCSBInternalNodeGroup ()
CCSBInternalNodeGroup (unsigned n)
~CCSBInternalNodeGroup ()
bool setUsedNodes (unsigned n)
CCSBNode< T > * getNode (unsigned i)
void setNode (unsigned i, CCSBNode< T > *node)
bool Insert (unsigned node_off, T key)
void DeleteChildren ()
bool serialize (FILE *filename)
bool deserialize (FILE *filename)
Public Member Functions inherited from CCSBNodeGroup< T >
CCSBNodeGroup ()
CCSBNodeGroup (unsigned n)
~CCSBNodeGroup ()
unsigned getUsedNodes ()
void nodeCountIncrement ()
virtual CCSBNodeGroup< T > * getHeaderNG ()
virtual void setHeaderNG (CCSBNodeGroup< T > *header)
virtual CCSBNodeGroup< T > * getTailerNG ()
virtual void setTailerNG (CCSBNodeGroup< T > *tailer)
Public Attributes
CCSBNode< T > ** internal_nodes
Public Attributes inherited from CCSBNodeGroup< T >
unsigned used_nodes
Constructor & Destructor Documentation
template<typename T> CCSBInternalNodeGroup< T >::CCSBInternalNodeGroup () inline
template<typename T > CCSBInternalNodeGroup< T >::CCSBInternalNodeGroup (unsigned n)
template<typename T > CCSBInternalNodeGroup< T >::~CCSBInternalNodeGroup ()
Member Function Documentation
template<typename T > void CCSBInternalNodeGroup< T >::DeleteChildren () virtual
Reimplemented from CCSBNodeGroup< T >.
template<typename T > bool CCSBInternalNodeGroup< T >::deserialize (FILE * filename) virtual
Reimplemented from CCSBNodeGroup< T >.
References CCSBInternalNode< T >::deserialize().
Referenced by CSBPlusTree< T >::deserialize().
template<typename T> CCSBNode<T>* CCSBInternalNodeGroup< T >::getNode (unsigned i) inline virtual
Reimplemented from CCSBNodeGroup< T >.
References NULL.
Referenced by CSBPlusTree< T >::BulkLoad(), and CSBPlusTree< T >::deserialize().
template<typename T > bool CCSBInternalNodeGroup< T >::Insert (unsigned node_off, T key) virtual
Reimplemented from CCSBNodeGroup< T >.
template<typename T > bool CCSBInternalNodeGroup< T >::serialize (FILE * filename) virtual
Reimplemented from CCSBNodeGroup< T >.
References boost::serialization::serialize().
template<typename T> void CCSBInternalNodeGroup< T >::setNode (unsigned i, CCSBNode< T > * node) inline virtual
Reimplemented from CCSBNodeGroup< T >.
References CCSBNode< T >::getElement(), CCSBNode< T >::getFather(), CCSBNode< T >::getPointer(), and CCSBNode< T >::getUsedKeys().
template<typename T> bool CCSBInternalNodeGroup< T >::setUsedNodes (unsigned n) inline virtual
Reimplemented from CCSBNodeGroup< T >.
Member Data Documentation
template<typename T> CCSBNode<T>** CCSBInternalNodeGroup< T >::internal_nodes
Referenced by CSBPlusTree< T >::BulkLoad().
The documentation for this class was generated from the following files:
IndexManager/CSBPlusTree.h
IndexManager/CSBPlusTree.cpp