Claims: AllBlockInfo Class Reference
AllBlockInfo Class Reference
#include <AllBlockInfo.h>
Public Member Functions
~AllBlockInfo ()
bool put (string blockmanagerId, string blockId)
Static Public Member Functions
static AllBlockInfo * getInstance ()
Private Member Functions
AllBlockInfo ()
Private Attributes
vector< string > vv_
Lock lock_
Static Private Attributes
static AllBlockInfo * abi_ =0
Constructor & Destructor Documentation
AllBlockInfo::~AllBlockInfo ()
AllBlockInfo::AllBlockInfo () private
Member Function Documentation
static AllBlockInfo* AllBlockInfo::getInstance () inline static
Referenced by BlockManagerMaster::BlockManagerMasterActor::blockStatusReceiver(), and BlockManagerMaster::initialize().
bool AllBlockInfo::put (string blockmanagerId, string blockId)
References Lock::acquire(), lock_, Lock::release(), and vv_.
Referenced by BlockManagerMaster::BlockManagerMasterActor::blockStatusReceiver().
Member Data Documentation
AllBlockInfo * AllBlockInfo::abi_ =0 static private
Lock AllBlockInfo::lock_ private
Referenced by put().
vector<string> AllBlockInfo::vv_ private
Referenced by put().
The documentation for this class was generated from the following files:
storage/AllBlockInfo.h
storage/AllBlockInfo.cpp