Claims: ClientListener Class Reference
ClientListener Class Reference
#include <ClaimsServer.h>
Public Member Functions
ClientListener (int port)
virtual ~ClientListener ()
void configure ()
void shutdown ()
Static Public Member Functions
static void checkFdValid (int fd)
Private Types
enum client_type { java, c }
Private Member Functions
int write (const int fd, const ClientResponse &res) const
int addClient (const int fd)
int removeClient (const int fd)
int receiveRequest (const int fd, const char *cmd)
bool isFull () const
Static Private Member Functions
static void restoreStd ()
static void * receiveHandler (void *)
static void * sendHandler (void *)
static void sendJsonPacket (ClientResponse &cr, executed_result &res)
static void generateSqlStmt (int type, char *&buf)
Private Attributes
int m_port
int m_fd
int * m_clientFds
int m_num
client_type client_type_
Static Private Attributes
static const int MAXCONN = 100
static int standard_input = dup(STDIN_FILENO)
static int standard_output = dup(STDOUT_FILENO)
static int standard_err = dup(STDERR_FILENO)
Member Enumeration Documentation
enum ClientListener::client_type private
Enumerator
java
c
Constructor & Destructor Documentation
ClientListener::ClientListener (int port)
References m_clientFds, m_fd, m_num, m_port, and MAXCONN.
ClientListener::~ClientListener () virtual
References m_clientFds.
Member Function Documentation
int ClientListener::addClient (const int fd) private
References m_clientFds, m_num, and MAXCONN.
Referenced by receiveHandler().
void ClientListener::checkFdValid (int fd) static
References ClientLogging::elog(), and ClientLogging::log().
Referenced by receiveHandler(), sendHandler(), Daemon::worker(), and write().
void ClientListener::configure ()
configure the socket parameter, bind to the specific ip/port startup the send/receive threads
References ClientListenerLogging::log(), m_fd, m_port, MAXCONN, NULL, receiveHandler(), and sendHandler().
Referenced by Environment::initializeClientListener().
void ClientListener::generateSqlStmt (int type, char *& buf) static private
References ClientLogging::elog(), ClientLogging::log(), NULL, and sql.
Referenced by receiveHandler().
bool ClientListener::isFull () const inline private
References m_num, and MAXCONN.
Referenced by receiveHandler().
void * ClientListener::receiveHandler (void * para) static private
redirect input/output to console
References addClient(), checkFdValid(), client_type_, ClientLogging::elog(), FileClose(), generateSqlStmt(), isFull(), ClientListenerLogging::log(), ClientLogging::log(), m_clientFds, m_fd, MAXCONN, NULL, receiveRequest(), removeClient(), and restoreStd().
Referenced by configure().
int ClientListener::receiveRequest (const int fd, const char * cmd) private
References Daemon::addRemoteCommand(), remote_command::cmd, Daemon::getInstance(), and remote_command::socket_fd.
Referenced by receiveHandler().
int ClientListener::removeClient (const int fd) private
References m_clientFds, m_num, and MAXCONN.
Referenced by receiveHandler().
void ClientListener::restoreStd () static private
References standard_err, standard_input, and standard_output.
Referenced by receiveHandler().
void * ClientListener::sendHandler (void * para) static private
References ColumnHeader::add_header(), DynamicBlockBuffer::Iterator::atomicNextBlock(), checkFdValid(), client_type_, ResultSet::column_header_list_, ClientResponse::content, DynamicBlockBuffer::createIterator(), executed_result::error_info, executed_result::fd, Daemon::getExecutedResult(), Daemon::getInstance(), executed_result::info, ClientResponse::length, ClientListenerLogging::log(), NULL, ResultSet::query_time_, executed_result::result, ResultSet::schema_, sendJsonPacket(), BlockStreamBase::serialize(), ClientResponse::setAttributeName(), ClientResponse::setChange(), ClientResponse::setDataBlock(), ClientResponse::setEnd(), ClientResponse::setError(), ClientResponse::setOk(), ClientResponse::setSchema(), executed_result::status, ClientResponse::status, and write().
Referenced by configure().
void ClientListener::sendJsonPacket (ClientResponse & cr, executed_result & res) static private
References Json::Value::append(), ResultSet::column_header_list_, DynamicBlockBuffer::createIterator(), BlockStreamBase::createIterator(), Schema::getColumnValue(), Schema::getncolumns(), DynamicBlockBuffer::Iterator::nextBlock(), BlockStreamBase::BlockStreamTraverseIterator::nextTuple(), NULL, executed_result::result, ResultSet::schema_, ClientResponse::setData(), executed_result::status, and Json::FastWriter::write().
Referenced by sendHandler().
void ClientListener::shutdown ()
Thread shut down the server when it receives "shut down" command from a client. shut down the server
References FileClose(), ClientLogging::log(), m_clientFds, m_fd, MAXCONN, standard_err, standard_input, and standard_output.
Referenced by Environment::destoryClientListener().
int ClientListener::write (const int fd, const ClientResponse & res) const private
References checkFdValid(), ClientResponse::content, ClientResponse::length, ClientListenerLogging::log(), ClientResponse::serialize(), and ClientResponse::status.
Referenced by sendHandler().
Member Data Documentation
client_type ClientListener::client_type_ private
Referenced by receiveHandler(), and sendHandler().
int* ClientListener::m_clientFds private
Referenced by addClient(), ClientListener(), receiveHandler(), removeClient(), shutdown(), and ~ClientListener().
int ClientListener::m_fd private
Referenced by ClientListener(), configure(), receiveHandler(), and shutdown().
int ClientListener::m_num private
Referenced by addClient(), ClientListener(), isFull(), and removeClient().
int ClientListener::m_port private
Referenced by ClientListener(), and configure().
const int ClientListener::MAXCONN = 100 static private
Referenced by addClient(), ClientListener(), configure(), isFull(), receiveHandler(), removeClient(), and shutdown().
int ClientListener::standard_err = dup(STDERR_FILENO) static private
Referenced by restoreStd(), and shutdown().
int ClientListener::standard_input = dup(STDIN_FILENO) static private
Referenced by restoreStd(), and shutdown().
int ClientListener::standard_output = dup(STDOUT_FILENO) static private
Referenced by restoreStd(), and shutdown().
The documentation for this class was generated from the following files:
Client/ClaimsServer.h
Client/ClaimsServer.cpp