Claims: OperateDouble Class Reference
OperateDouble Class Reference
#include <data_type.h>
Public Member Functions
OperateDouble (bool _nullable=true)
~OperateDouble ()
void assignment (const void *const &src, void *const &desc) const
std::string toString (void *value)
void toValue (void *target, const char *string)
bool equal (const void *const &a, const void *const &b) const
bool less (const void *&a, const void *&b) const
bool greate (const void *&a, const void *&b) const
int compare (const void *a, const void *b) const
void add (void *target, void *increment)
void multiple (void *target, void *increment)
fun GetADDFunction ()
fun GetMINFunction ()
fun GetMAXFunction ()
fun GetIncreateByOneFunction ()
fun GetAVGFunction ()
unsigned getPartitionValue (const void *key, const PartitionFunction *partition_function) const
unsigned getPartitionValue (const void *key) const
unsigned getPartitionValue (const void *key, const unsigned long &mod) const
Operate * duplicateOperator () const
bool setNull (void *value)
bool isNull (void *value) const
Public Member Functions inherited from Operate
Operate (bool _nullable=true)
virtual ~Operate ()
void ass (void *src, void *desc)
Additional Inherited Members
Public Attributes inherited from Operate
void(* assign)(const void *const &src, void *const &desc)
bool nullable
Constructor & Destructor Documentation
OperateDouble::OperateDouble (bool _nullable = true) inline
OperateDouble::~OperateDouble () inline
Member Function Documentation
void OperateDouble::add (void * target, void * increment) inline virtual
Implements Operate.
void OperateDouble::assignment (const void *const & src, void *const & desc) const inline virtual
Implements Operate.
int OperateDouble::compare (const void * a, const void * b) const inline virtual
Implements Operate.
Operate* OperateDouble::duplicateOperator () const inline virtual
Implements Operate.
bool OperateDouble::equal (const void *const & a, const void *const & b) const inline virtual
Implements Operate.
fun OperateDouble::GetADDFunction () inline virtual
Implements Operate.
fun OperateDouble::GetAVGFunction () inline virtual
Implements Operate.
fun OperateDouble::GetIncreateByOneFunction () inline virtual
Implements Operate.
fun OperateDouble::GetMAXFunction () inline virtual
Implements Operate.
fun OperateDouble::GetMINFunction () inline virtual
Implements Operate.
unsigned OperateDouble::getPartitionValue (const void * key, const PartitionFunction * partition_function) const inline virtual
Implements Operate.
References PartitionFunction::get_partition_value().
unsigned OperateDouble::getPartitionValue (const void * key) const inline virtual
Implements Operate.
References hash_value().
unsigned OperateDouble::getPartitionValue (const void * key, const unsigned long & mod) const inline virtual
Implements Operate.
References hash_value().
bool OperateDouble::greate (const void *& a, const void *& b) const inline virtual
Implements Operate.
bool OperateDouble::isNull (void * value) const inline virtual
Implements Operate.
References NULL_DOUBLE.
bool OperateDouble::less (const void *& a, const void *& b) const inline virtual
Implements Operate.
void OperateDouble::multiple (void * target, void * increment) inline virtual
Implements Operate.
bool OperateDouble::setNull (void * value) inline virtual
Implements Operate.
References NULL_DOUBLE.
std::string OperateDouble::toString (void * value) inline virtual
Implements Operate.
References NULL_DOUBLE.
void OperateDouble::toValue (void * target, const char * string) inline virtual
Implements Operate.
References NULL_DOUBLE.
The documentation for this class was generated from the following file:
common/data_type.h