Claims: LogicalIndexScan Class Reference
LogicalIndexScan Class Reference
#include <LogicalIndexScan.h>
Public Member Functions
LogicalIndexScan ()
LogicalIndexScan (ProjectionID projection_id, Attribute index_attr, vector< IndexScanIterator::query_range > q_range)
virtual ~LogicalIndexScan ()
PlanContext GetPlanContext ()
PhysicalOperatorBase * GetPhysicalPlan (const unsigned &blocksize)
bool GetOptimalPhysicalPlan (Requirement requirement, PhysicalPlanDescriptor &physical_plan_descriptor, const unsigned &block_size=4096 *1024)
void Print (int level=0) const
Public Member Functions inherited from claims::logical_operator::LogicalOperator
LogicalOperator ()
LogicalOperator (OperatorType operator_type)
virtual ~LogicalOperator ()
Private Attributes
ProjectionID projection_id_
Attribute index_attr_
vector
< IndexScanIterator::query_range > query_range_
ProjectionDescriptor * scan_projection_
PlanContext dataflow_
Additional Inherited Members
Protected Member Functions inherited from claims::logical_operator::LogicalOperator
Schema * GetSchema (const std::vector< Attribute > &) const
Schema * GetSchema (const std::vector< Attribute > &, const std::vector< Attribute > &) const
std::vector< NodeID > GetInvolvedNodeID (const PlanPartitioner &) const
std::vector< NodeIP > ConvertNodeIDListToNodeIPList (const std::vector< NodeID > &) const
PhysicalPlanDescriptor GetBestPhysicalPlanDescriptor (const std::vector< PhysicalPlanDescriptor >) const
int GetIdInAttributeList (const std::vector< Attribute > &attributes, const Attribute &attribute) const
void set_operator_type (OperatorType operator_type)
Protected Attributes inherited from claims::logical_operator::LogicalOperator
Lock * lock_
Constructor & Destructor Documentation
LogicalIndexScan::LogicalIndexScan ()
LogicalIndexScan::LogicalIndexScan (ProjectionID projection_id, Attribute index_attr, vector< IndexScanIterator::query_range > q_range)
References Catalog::getInstance(), TableDescriptor::getProjectoin(), Catalog::getTable(), index_attr_, projection_id_, ProjectionID::projection_off, scan_projection_, and Attribute::table_id_.
LogicalIndexScan::~LogicalIndexScan () virtual
Member Function Documentation
bool LogicalIndexScan::GetOptimalPhysicalPlan (Requirement requirement, PhysicalPlanDescriptor & physical_plan_descriptor, const unsigned & block_size = 4096 * 1024) virtual
get the optimal Physical plan that meets the requirement.
Returns
true if find physical plan that meets the requirement and store the physical plan and its corresponding information in physical_plan_descriptor.
Reimplemented from claims::logical_operator::LogicalOperator.
PhysicalOperatorBase * LogicalIndexScan::GetPhysicalPlan (const unsigned &) virtual
generate the iterator tree based on the computed plan_context. Hence, this function can only be called after the calling of GetPlanContext().
Implements claims::logical_operator::LogicalOperator.
References claims::logical_operator::PlanContext::attribute_list_, IndexScanIterator::State::block_size_, dataflow_, IndexManager::getIndexID(), IndexManager::getInstance(), claims::logical_operator::LogicalOperator::GetSchema(), index_attr_, IndexScanIterator::State::index_id_, projection_id_, IndexScanIterator::State::projection_id_, query_range_, IndexScanIterator::State::query_range_, and IndexScanIterator::State::schema_.
Referenced by test_logical_csb_index_building().
PlanContext LogicalIndexScan::GetPlanContext () virtual
get the plan context which describes the property of the data after having executed corresponding operator.
Implements claims::logical_operator::LogicalOperator.
References ProjectionDescriptor::AllPartitionBound(), claims::logical_operator::PlanContext::attribute_list_, ProjectionBinding::BindingEntireProjection(), claims::logical_operator::PlanContext::commu_cost_, dataflow_, DESIRIABLE_STORAGE_LEVEL, ProjectionDescriptor::getAttributeList(), Catalog::getBindingModele(), Catalog::getInstance(), ProjectionDescriptor::getPartitioner(), claims::logical_operator::PlanContext::plan_partitioner_, and scan_projection_.
void LogicalIndexScan::Print (int level = 0) const virtual
Implements claims::logical_operator::LogicalOperator.
Referenced by test_logical_csb_index_building().
Member Data Documentation
PlanContext LogicalIndexScan::dataflow_ private
Referenced by GetPhysicalPlan(), and GetPlanContext().
Attribute LogicalIndexScan::index_attr_ private
Referenced by GetPhysicalPlan(), and LogicalIndexScan().
ProjectionID LogicalIndexScan::projection_id_ private
Referenced by GetPhysicalPlan(), and LogicalIndexScan().
vector<IndexScanIterator::query_range> LogicalIndexScan::query_range_ private
Referenced by GetPhysicalPlan().
ProjectionDescriptor* LogicalIndexScan::scan_projection_ private
Referenced by GetPlanContext(), and LogicalIndexScan().
The documentation for this class was generated from the following files:
IndexManager/LogicalIndexScan.h
IndexManager/LogicalIndexScan.cpp