Claims: Json::BatchAllocator< AllocatedType, objectPerAllocation > Class Template Reference
Json::BatchAllocator< AllocatedType, objectPerAllocation > Class Template Reference
Classes
struct BatchInfo
Public Member Functions
BatchAllocator (unsigned int objectsPerPage=255)
~BatchAllocator ()
AllocatedType * allocate ()
void release (AllocatedType *object)
Private Member Functions
BatchAllocator (const BatchAllocator &)
void operator= (const BatchAllocator &)
Static Private Member Functions
static BatchInfo * allocateBatch (unsigned int objectsPerPage)
Private Attributes
BatchInfo * batches_
BatchInfo * currentBatch_
AllocatedType * freeHead_
Head of a single linked list within the allocated space of freeed object.
unsigned int objectsPerPage_
Constructor & Destructor Documentation
template<typename AllocatedType , const unsigned int objectPerAllocation> Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchAllocator (unsigned int objectsPerPage = 255) inline
References Json::BatchAllocator< AllocatedType, objectPerAllocation >::allocateBatch(), Json::BatchAllocator< AllocatedType, objectPerAllocation >::batches_, and Json::BatchAllocator< AllocatedType, objectPerAllocation >::currentBatch_.
template<typename AllocatedType , const unsigned int objectPerAllocation> Json::BatchAllocator< AllocatedType, objectPerAllocation >::~BatchAllocator () inline
References Json::BatchAllocator< AllocatedType, objectPerAllocation >::batches_, and Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchInfo::next_.
template<typename AllocatedType , const unsigned int objectPerAllocation> Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchAllocator (const BatchAllocator< AllocatedType, objectPerAllocation > &) private
Member Function Documentation
template<typename AllocatedType , const unsigned int objectPerAllocation> AllocatedType* Json::BatchAllocator< AllocatedType, objectPerAllocation >::allocate () inline
allocate space for an array of objectPerAllocation object.
Warning
it is the responsability of the caller to call objects constructors.
References Json::BatchAllocator< AllocatedType, objectPerAllocation >::allocateBatch(), Json::BatchAllocator< AllocatedType, objectPerAllocation >::batches_, Json::BatchAllocator< AllocatedType, objectPerAllocation >::currentBatch_, Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchInfo::end_, Json::BatchAllocator< AllocatedType, objectPerAllocation >::freeHead_, Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchInfo::next_, Json::BatchAllocator< AllocatedType, objectPerAllocation >::objectsPerPage_, and Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchInfo::used_.
template<typename AllocatedType , const unsigned int objectPerAllocation> static BatchInfo* Json::BatchAllocator< AllocatedType, objectPerAllocation >::allocateBatch (unsigned int objectsPerPage) inline static private
References Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchInfo::next_, and Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchInfo::used_.
Referenced by Json::BatchAllocator< AllocatedType, objectPerAllocation >::allocate(), and Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchAllocator().
template<typename AllocatedType , const unsigned int objectPerAllocation> void Json::BatchAllocator< AllocatedType, objectPerAllocation >::operator= (const BatchAllocator< AllocatedType, objectPerAllocation > &) private
template<typename AllocatedType , const unsigned int objectPerAllocation> void Json::BatchAllocator< AllocatedType, objectPerAllocation >::release (AllocatedType * object) inline
Release the object.
Warning
it is the responsability of the caller to actually destruct the object.
References Json::BatchAllocator< AllocatedType, objectPerAllocation >::freeHead_.
Member Data Documentation
template<typename AllocatedType , const unsigned int objectPerAllocation> BatchInfo* Json::BatchAllocator< AllocatedType, objectPerAllocation >::batches_ private
Referenced by Json::BatchAllocator< AllocatedType, objectPerAllocation >::allocate(), Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchAllocator(), and Json::BatchAllocator< AllocatedType, objectPerAllocation >::~BatchAllocator().
template<typename AllocatedType , const unsigned int objectPerAllocation> BatchInfo* Json::BatchAllocator< AllocatedType, objectPerAllocation >::currentBatch_ private
Referenced by Json::BatchAllocator< AllocatedType, objectPerAllocation >::allocate(), and Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchAllocator().
template<typename AllocatedType , const unsigned int objectPerAllocation> AllocatedType* Json::BatchAllocator< AllocatedType, objectPerAllocation >::freeHead_ private
Head of a single linked list within the allocated space of freeed object.
Referenced by Json::BatchAllocator< AllocatedType, objectPerAllocation >::allocate(), and Json::BatchAllocator< AllocatedType, objectPerAllocation >::release().
template<typename AllocatedType , const unsigned int objectPerAllocation> unsigned int Json::BatchAllocator< AllocatedType, objectPerAllocation >::objectsPerPage_ private
Referenced by Json::BatchAllocator< AllocatedType, objectPerAllocation >::allocate().
The documentation for this class was generated from the following file:
Client/jsoncpp.cpp