Claims: ThreadPool Class Reference
ThreadPool Class Reference
#include <ThreadPool.h>
Classes
struct Task
Public Member Functions
ThreadPool ()
virtual ~ThreadPool ()
bool Thread_Pool_init (int thread_count_in_pool_)
void * thread_exec_with_cond (void *arg)
void bind_cpu ()
void add_task (void *(*)(void *), void *arg, bool e=false)
Static Public Member Functions
static void * thread_exec (void *arg)
static void destroy_pool (ThreadPool *tp)
Private Attributes
sem_t undo_task_sem
pthread_t * thread_list_
queue< Task * > task_queue_
pthread_mutex_t task_queue_lock
int thread_count
int free_thread_count
pthread_mutex_t free_thread_count_lock
int task_count
int undo_task_count
pthread_mutex_t undo_task_count_lock
Constructor & Destructor Documentation
ThreadPool::ThreadPool ()
ThreadPool::~ThreadPool () virtual
Member Function Documentation
void ThreadPool::add_task (void * *)(void *, void * arg, bool e = false)
References task_queue_, task_queue_lock, and undo_task_sem.
Referenced by claims::physical_operator::ExchangeSenderMaterialized::CreateWorkerThread(), claims::physical_operator::Expander::CreateWorkingThread(), destroy_pool(), and claims::physical_operator::ResultCollector::Open().
void ThreadPool::bind_cpu ()
References ThreadPoolLogging::elog(), and ThreadPoolLogging::log().
Referenced by thread_exec().
void ThreadPool::destroy_pool (ThreadPool * tp) static
References add_task(), ThreadPool::Task::destroy_task(), free_thread_count_lock, NULL, task_queue_, task_queue_lock, thread_count, thread_list_, undo_task_count_lock, and undo_task_sem.
void * ThreadPool::thread_exec (void * arg) static
References ThreadPool::Task::arg, bind_cpu(), ThreadPool::Task::destroy_task(), ThreadPool::Task::end, ThreadPool::Task::func, ThreadPoolLogging::log(), NULL, task_queue_, task_queue_lock, and undo_task_sem.
Referenced by Thread_Pool_init().
void* ThreadPool::thread_exec_with_cond (void * arg)
bool ThreadPool::Thread_Pool_init (int thread_count_in_pool_)
References free_thread_count, free_thread_count_lock, NULL, task_queue_, task_queue_lock, thread_count, thread_exec(), thread_list_, undo_task_count, undo_task_count_lock, and undo_task_sem.
Referenced by Environment::initializeThreadPool().
Member Data Documentation
int ThreadPool::free_thread_count private
Referenced by Thread_Pool_init().
pthread_mutex_t ThreadPool::free_thread_count_lock private
Referenced by destroy_pool(), and Thread_Pool_init().
int ThreadPool::task_count private
queue<Task*> ThreadPool::task_queue_ private
Referenced by add_task(), destroy_pool(), thread_exec(), and Thread_Pool_init().
pthread_mutex_t ThreadPool::task_queue_lock private
Referenced by add_task(), destroy_pool(), thread_exec(), and Thread_Pool_init().
int ThreadPool::thread_count private
Referenced by destroy_pool(), and Thread_Pool_init().
pthread_t* ThreadPool::thread_list_ private
Referenced by destroy_pool(), and Thread_Pool_init().
int ThreadPool::undo_task_count private
Referenced by Thread_Pool_init().
pthread_mutex_t ThreadPool::undo_task_count_lock private
Referenced by destroy_pool(), and Thread_Pool_init().
sem_t ThreadPool::undo_task_sem private
Referenced by add_task(), destroy_pool(), thread_exec(), and Thread_Pool_init().
The documentation for this class was generated from the following files:
utility/ThreadPool.h
utility/ThreadPool.cpp