Claims: Executing Class Reference
Executing Class Reference
#include <Executing.h>
Public Member Functions
Executing ()
virtual ~Executing ()
Static Public Member Functions
static ResultSet * run_sql (std::string sql, std::string &error)
static void run_sql (const std::string &cmd, ResultSet *&result, bool &status, std::string &error_info, std::string &info, int fd)
Constructor & Destructor Documentation
Executing::Executing ()
Executing::~Executing () virtual
Member Function Documentation
ResultSet * Executing::run_sql (std::string sql, std::string & error) static
References claims::physical_operator::PhysicalOperatorBase::Close(), getparsetreeroot(), claims::logical_operator::LogicalOperator::GetPhysicalPlan(), claims::physical_operator::PhysicalOperatorBase::GetResultSet(), claims::physical_operator::PhysicalOperatorBase::Next(), claims::physical_operator::PhysicalOperatorBase::Open(), parsetree2logicalplan(), claims::physical_operator::PhysicalOperatorBase::Print(), claims::logical_operator::LogicalOperator::Print(), and claims::logical_operator::LogicalOperator::~LogicalOperator().
Referenced by execting_test(), and Daemon::worker().
void Executing::run_sql (const std::string & cmd, ResultSet *& result, bool & status, std::string & error_info, std::string & info, int fd) static
References ExecuteLogicalQueryPlan(), and NULL.
The documentation for this class was generated from the following files:
Daemon/Executing.h
Daemon/Executing.cpp