Claims: PortManager Class Reference
PortManager Class Reference
#include <PortManager.h>
Public Member Functions
PortManager ()
virtual ~PortManager ()
int applyPort ()
void returnPort (unsigned port)
Static Public Member Functions
static PortManager * getInstance ()
Private Member Functions
void getConfigure ()
void generateFreePorts ()
Private Attributes
unsigned start
unsigned end
std::vector< unsigned > free_ports
std::vector< unsigned > used_ports
Lock l
Static Private Attributes
static PortManager * _instance =0
Constructor & Destructor Documentation
PortManager::PortManager ()
References end, generateFreePorts(), getConfigure(), Logging_PortManager(), and start.
Referenced by getInstance().
PortManager::~PortManager () virtual
References _instance.
Member Function Documentation
int PortManager::applyPort ()
References Lock::acquire(), free_ports, l, and Lock::release().
Referenced by Environment::initializeEndPoint(), and Coordinator::SetupTheTheron().
void PortManager::generateFreePorts () private
References end, free_ports, and start.
Referenced by PortManager().
void PortManager::getConfigure () private
References Config::config_file, end, and start.
Referenced by PortManager().
PortManager * PortManager::getInstance () static
References _instance, and PortManager().
Referenced by claims::physical_operator::ExchangeMerger::CloseSocket(), Environment::Environment(), claims::physical_operator::ExchangeMerger::PrepareSocket(), and Coordinator::SetupTheTheron().
void PortManager::returnPort (unsigned port)
References Lock::acquire(), free_ports, l, and Lock::release().
Referenced by claims::physical_operator::ExchangeMerger::CloseSocket().
Member Data Documentation
PortManager * PortManager::_instance =0 static private
Referenced by getInstance(), and ~PortManager().
unsigned PortManager::end private
Referenced by generateFreePorts(), getConfigure(), and PortManager().
std::vector<unsigned> PortManager::free_ports private
Referenced by applyPort(), generateFreePorts(), and returnPort().
Lock PortManager::l private
Referenced by applyPort(), and returnPort().
unsigned PortManager::start private
Referenced by generateFreePorts(), getConfigure(), and PortManager().
std::vector<unsigned> PortManager::used_ports private
The documentation for this class was generated from the following files:
Executor/PortManager.h
Executor/PortManager.cpp