Claims: PhysicalQueryPlan Class Reference
PhysicalQueryPlan Class Reference
#include <Message.h>
Public Member Functions
PhysicalQueryPlan (PhysicalOperatorBase *it)
PhysicalQueryPlan (const PhysicalQueryPlan &r)
PhysicalQueryPlan ()
~PhysicalQueryPlan ()
void destory ()
void run ()
Static Public Member Functions
static PhysicalQueryPlan deserialize (Message256 message)
static Message256 serialize (PhysicalQueryPlan input)
static PhysicalQueryPlan deserialize4K (Message4K message)
static Message4K serialize4K (PhysicalQueryPlan &input)
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
PhysicalOperatorBase * block_stream_iterator_root_
Friends
class boost::serialization::access
Constructor & Destructor Documentation
PhysicalQueryPlan::PhysicalQueryPlan (PhysicalOperatorBase * it) inline
PhysicalQueryPlan::PhysicalQueryPlan (const PhysicalQueryPlan & r) inline
References block_stream_iterator_root_.
PhysicalQueryPlan::PhysicalQueryPlan () inline
PhysicalQueryPlan::~PhysicalQueryPlan () inline
Member Function Documentation
static PhysicalQueryPlan PhysicalQueryPlan::deserialize (Message256 message) inline static
Referenced by IteratorExecutorSlave::ExecuteIteratorActor::Handler256().
static PhysicalQueryPlan PhysicalQueryPlan::deserialize4K (Message4K message) inline static
Referenced by IteratorExecutorMaster::ExecuteBlockStreamIteratorsOnSite(), and IteratorExecutorSlave::ExecuteIteratorActor::Handler4K().
void PhysicalQueryPlan::destory () inline
References block_stream_iterator_root_, and claims::physical_operator::PhysicalOperatorBase::~PhysicalOperatorBase().
void PhysicalQueryPlan::run ()
Referenced by IteratorExecutorSlave::executePhysicalQueryPlan(), and IteratorExecutorSlave::ExecuteIteratorActor::Handler256().
static Message256 PhysicalQueryPlan::serialize (PhysicalQueryPlan input) inline static
References input().
template<class Archive > void PhysicalQueryPlan::serialize (Archive & ar, const unsigned int version) inline private
References block_stream_iterator_root_, Register_Block_Stream_Iterator(), and Register_Schemas().
static Message4K PhysicalQueryPlan::serialize4K (PhysicalQueryPlan & input) inline static
References input().
Referenced by IteratorExecutorMaster::ExecuteBlockStreamIteratorsOnSite(), and IteratorExecutorMaster::ExecuteBlockStreamIteratorsOnSites().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
PhysicalOperatorBase* PhysicalQueryPlan::block_stream_iterator_root_ private
Referenced by destory(), PhysicalQueryPlan(), and serialize().
The documentation for this class was generated from the following files:
common/Message.h
common/Message.cpp