Claims: OperateString Class Reference
OperateString Class Reference
#include <data_type.h>
Public Member Functions
OperateString (bool _nullable=true)
~OperateString ()
void assignment (const void *const &src, void *const &desc) const
std::string toString (void *value)
void toValue (void *target, const char *string)
bool equal (const void *const &a, const void *const &b) const
bool less (const void *&a, const void *&b) const
bool greate (const void *&a, const void *&b) const
int compare (const void *a, const void *b) const
void add (void *target, void *increment)
void multiple (void *target, void *increment)
fun GetADDFunction ()
fun GetMINFunction ()
fun GetMAXFunction ()
fun GetIncreateByOneFunction ()
fun GetAVGFunction ()
unsigned getPartitionValue (const void *key, const PartitionFunction *partition_function) const
unsigned getPartitionValue (const void *key) const
unsigned getPartitionValue (const void *key, const unsigned long &mod) const
Operate * duplicateOperator () const
bool setNull (void *value)
bool isNull (void *value) const
Public Member Functions inherited from Operate
Operate (bool _nullable=true)
virtual ~Operate ()
void ass (void *src, void *desc)
Additional Inherited Members
Public Attributes inherited from Operate
void(* assign)(const void *const &src, void *const &desc)
bool nullable
Constructor & Destructor Documentation
OperateString::OperateString (bool _nullable = true) inline
OperateString::~OperateString () inline
Member Function Documentation
void OperateString::add (void * target, void * increment) inline virtual
Implements Operate.
void OperateString::assignment (const void *const & src, void *const & desc) const inline virtual
Implements Operate.
int OperateString::compare (const void * a, const void * b) const inline virtual
Implements Operate.
Operate* OperateString::duplicateOperator () const inline virtual
Implements Operate.
bool OperateString::equal (const void *const & a, const void *const & b) const inline virtual
Implements Operate.
fun OperateString::GetADDFunction () inline virtual
Implements Operate.
References ADD_FUNC< char * >().
fun OperateString::GetAVGFunction () inline virtual
Implements Operate.
References ADD_IncreaseByOne< char * >().
fun OperateString::GetIncreateByOneFunction () inline virtual
Implements Operate.
References IncreaseByOne< char * >().
fun OperateString::GetMAXFunction () inline virtual
Implements Operate.
References MAX< char * >().
fun OperateString::GetMINFunction () inline virtual
Implements Operate.
References MIN< char * >().
unsigned OperateString::getPartitionValue (const void * key, const PartitionFunction * partition_function) const inline virtual
Implements Operate.
unsigned OperateString::getPartitionValue (const void * key) const inline virtual
Implements Operate.
References hash_value().
unsigned OperateString::getPartitionValue (const void * key, const unsigned long & mod) const inline virtual
Implements Operate.
References hash_value().
bool OperateString::greate (const void *& a, const void *& b) const inline virtual
Implements Operate.
bool OperateString::isNull (void * value) const inline virtual
Implements Operate.
References NULL_STRING.
bool OperateString::less (const void *& a, const void *& b) const inline virtual
The following function may return a wrong value
Implements Operate.
void OperateString::multiple (void * target, void * increment) inline virtual
Implements Operate.
bool OperateString::setNull (void * value) inline virtual
Implements Operate.
References NULL_STRING.
std::string OperateString::toString (void * value) inline virtual
Implements Operate.
References NULL_STRING, and trimSpecialCharactor().
void OperateString::toValue (void * target, const char * string) inline virtual
Implements Operate.
References NULL_STRING.
The documentation for this class was generated from the following file:
common/data_type.h