Claims: BlockManagerMaster::BlockManagerMasterActor Class Reference
BlockManagerMaster::BlockManagerMasterActor Class Reference
#include <BlockManagerMaster.h>
Inherits Actor.
Public Member Functions
BlockManagerMasterActor (Theron::Framework *framework, const char *name)
virtual ~BlockManagerMasterActor ()
void workerRegister (const StorageBudgetMessage &message, const Theron::Address from)
void heartbeatReceiver (const HeartBeatMessage &message, const Theron::Address from)
void blockStatusReceiver (const BlockStatusMessage &message, const Theron::Address from)
void matcherReceiver (const MatcherMessage &message, const Theron::Address from)
Friends
class BlockManagerMaster
Constructor & Destructor Documentation
BlockManagerMaster::BlockManagerMasterActor::BlockManagerMasterActor (Theron::Framework * framework, const char * name)
References blockStatusReceiver(), heartbeatReceiver(), matcherReceiver(), and workerRegister().
BlockManagerMaster::BlockManagerMasterActor::~BlockManagerMasterActor () virtual
Member Function Documentation
void BlockManagerMaster::BlockManagerMasterActor::blockStatusReceiver (const BlockStatusMessage & message, const Theron::Address from)
References AllBlockInfo::getInstance(), BlockStatusMessage::mText, and AllBlockInfo::put().
Referenced by BlockManagerMasterActor().
void BlockManagerMaster::BlockManagerMasterActor::heartbeatReceiver (const HeartBeatMessage & message, const Theron::Address from)
References HeartBeatMessage::mText.
Referenced by BlockManagerMasterActor().
void BlockManagerMaster::BlockManagerMasterActor::matcherReceiver (const MatcherMessage & message, const Theron::Address from)
References MatcherMessage::bmiText, MatcherMessage::filenameText, BlanceMatcher::getInstance(), and BlanceMatcher::matcher().
Referenced by BlockManagerMasterActor().
void BlockManagerMaster::BlockManagerMasterActor::workerRegister (const StorageBudgetMessage & message, const Theron::Address from)
References StorageBudgetMessage::nodeid.
Referenced by BlockManagerMasterActor().
Friends And Related Function Documentation
friend class BlockManagerMaster friend
The documentation for this class was generated from the following files:
storage/BlockManagerMaster.h
storage/BlockManagerMaster.cpp