Claims: ttmath::UInt< value_size > Class Template Reference
ttmath::UInt< value_size > Class Template Reference
UInt implements a big integer value without a sign.
#include <ttmathuint.h>
Public Member Functions
void hash (std::size_t &seed) const
template<class ostream_type >
void PrintTable (ostream_type &output) const
template<class char_type , class ostream_type >
void PrintLog (const char_type *msg, ostream_type &output) const
template<class char_type , class ostream_type >
void PrintLog (const char_type *msg, uint carry, ostream_type &output) const
uint Size () const
void SetZero ()
void SetOne ()
void SetMax ()
void SetMin ()
void SetFromTable (const uint *temp_table, uint temp_table_len)
uint AddOne ()
uint SubOne ()
uint Rcl (uint bits, uint c=0)
uint Rcr (uint bits, uint c=0)
uint CompensationToLeft ()
bool FindLeadingBit (uint &table_id, uint &index) const
uint GetBit (uint bit_index) const
uint SetBit (uint bit_index)
void BitAnd (const UInt< value_size > &ss2)
void BitOr (const UInt< value_size > &ss2)
void BitXor (const UInt< value_size > &ss2)
void BitNot ()
void BitNot2 ()
uint MulInt (uint ss2)
template<uint result_size>
void MulInt (uint ss2, UInt< result_size > &result) const
uint Mul (const UInt< value_size > &ss2, uint algorithm=100)
void MulBig (const UInt< value_size > &ss2, UInt< value_size *2 > &result, uint algorithm=100)
uint Mul1 (const UInt< value_size > &ss2)
void Mul1Big (const UInt< value_size > &ss2_, UInt< value_size *2 > &result)
uint Mul2 (const UInt< value_size > &ss2)
void Mul2Big (const UInt< value_size > &ss2, UInt< value_size *2 > &result)
uint Mul3 (const UInt< value_size > &ss2)
void Mul3Big (const UInt< value_size > &ss2, UInt< value_size *2 > &result)
uint MulFastest (const UInt< value_size > &ss2)
void MulFastestBig (const UInt< value_size > &ss2, UInt< value_size *2 > &result)
uint DivInt (uint divisor, uint *remainder=0)
uint DivInt (uint divisor, uint &remainder)
uint Div (const UInt< value_size > &divisor, UInt< value_size > *remainder=0, uint algorithm=3)
uint Div (const UInt< value_size > &divisor, UInt< value_size > &remainder, uint algorithm=3)
uint Div1 (const UInt< value_size > &divisor, UInt< value_size > *remainder=0)
uint Div2 (const UInt< value_size > &divisor, UInt< value_size > *remainder=0)
uint Div2 (const UInt< value_size > &divisor, UInt< value_size > &remainder)
uint Div3 (const UInt< value_size > &v, UInt< value_size > *remainder=0)
uint Pow (UInt< value_size > pow)
void Sqrt ()
void ClearFirstBits (uint n)
bool IsTheHighestBitSet () const
bool IsTheLowestBitSet () const
bool IsZero () const
template<uint argument_size>
uint FromUInt (const UInt< argument_size > &p)
void FromUInt (uint value)
template<uint argument_size>
UInt< value_size > & operator= (const UInt< argument_size > &p)
UInt< value_size > & operator= (const UInt< value_size > &p)
UInt< value_size > & operator= (uint i)
UInt (uint i)
UInt< value_size > & operator= (sint i)
UInt (sint i)
UInt (const char *s)
UInt (const wchar_t *s)
UInt (const std::string &s)
UInt (const std::wstring &s)
UInt ()
UInt (const UInt< value_size > &u)
template<uint argument_size>
UInt (const UInt< argument_size > &u)
~UInt ()
uint ToUInt () const
void ToString (std::string &result, uint b=10) const
void ToString (std::wstring &result, uint b=10) const
std::string ToString (uint b=10) const
std::wstring ToWString (uint b=10) const
uint FromString (const char *s, uint b=10, const char **after_source=0, bool *value_read=0)
uint FromString (const wchar_t *s, uint b=10, const wchar_t **after_source=0, bool *value_read=0)
uint FromString (const std::string &s, uint b=10)
uint FromString (const std::wstring &s, uint b=10)
UInt< value_size > & operator= (const char *s)
UInt< value_size > & operator= (const wchar_t *s)
UInt< value_size > & operator= (const std::string &s)
UInt< value_size > & operator= (const std::wstring &s)
bool CmpSmaller (const UInt< value_size > &l, sint index=-1) const
bool CmpBigger (const UInt< value_size > &l, sint index=-1) const
bool CmpEqual (const UInt< value_size > &l, sint index=-1) const
bool CmpSmallerEqual (const UInt< value_size > &l, sint index=-1) const
bool CmpBiggerEqual (const UInt< value_size > &l, sint index=-1) const
bool operator< (const UInt< value_size > &l) const
bool operator> (const UInt< value_size > &l) const
bool operator== (const UInt< value_size > &l) const
bool operator!= (const UInt< value_size > &l) const
bool operator<= (const UInt< value_size > &l) const
bool operator>= (const UInt< value_size > &l) const
UInt< value_size > operator- (const UInt< value_size > &p2) const
UInt< value_size > & operator-= (const UInt< value_size > &p2)
UInt< value_size > operator+ (const UInt< value_size > &p2) const
UInt< value_size > & operator+= (const UInt< value_size > &p2)
UInt< value_size > operator* (const UInt< value_size > &p2) const
UInt< value_size > & operator*= (const UInt< value_size > &p2)
UInt< value_size > operator/ (const UInt< value_size > &p2) const
UInt< value_size > & operator/= (const UInt< value_size > &p2)
UInt< value_size > operator% (const UInt< value_size > &p2) const
UInt< value_size > & operator%= (const UInt< value_size > &p2)
UInt< value_size > & operator++ ()
UInt< value_size > operator++ (int)
UInt< value_size > & operator-- ()
UInt< value_size > operator-- (int)
UInt< value_size > operator>> (int move)
UInt< value_size > & operator>>= (int move)
UInt< value_size > operator<< (int move)
UInt< value_size > & operator<<= (int move)
uint Add (const UInt< value_size > &ss2, uint c=0)
uint AddInt (uint value, uint index=0)
uint AddTwoInts (uint x2, uint x1, uint index)
uint Sub (const UInt< value_size > &ss2, uint c=0)
uint SubInt (uint value, uint index=0)
Static Public Member Functions
template<class char_type , class ostream_type >
static void PrintVectorLog (const char_type *msg, ostream_type &output, const uint *vector, uint vector_len)
template<class char_type , class ostream_type >
static void PrintVectorLog (const char_type *msg, uint carry, ostream_type &output, const uint *vector, uint vector_len)
static uint AddTwoWords (uint a, uint b, uint carry, uint *result)
static uint SubTwoWords (uint a, uint b, uint carry, uint *result)
static const char * LibTypeStr ()
static LibTypeCode LibType ()
static uint AddVector (const uint *ss1, const uint *ss2, uint ss1_size, uint ss2_size, uint *result)
static uint SubVector (const uint *ss1, const uint *ss2, uint ss1_size, uint ss2_size, uint *result)
static sint FindLeadingBitInWord (uint x)
static uint SetBitInWord (uint &value, uint bit)
static void MulTwoWords (uint a, uint b, uint *result_high, uint *result_low)
static void DivTwoWords (uint a, uint b, uint c, uint *r, uint *rest)
Public Attributes
uint table [value_size]
Private Member Functions
void RclMoveAllWords (uint &rest_bits, uint &last_c, uint bits, uint c)
void RcrMoveAllWords (uint &rest_bits, uint &last_c, uint bits, uint c)
template<uint ss_size>
void Mul2Big2 (const uint *ss1, const uint *ss2, UInt< ss_size *2 > &result)
template<uint ss_size>
void Mul2Big3 (const uint *ss1, const uint *ss2, UInt< ss_size *2 > &result, uint x1start, uint x1size, uint x2start, uint x2size)
template<uint ss_size>
void Mul3Big2 (const uint *ss1, const uint *ss2, uint *result)
template<uint first_size, uint second_size, uint result_size>
void Mul3Big3 (const uint *x1, const uint *x0, const uint *y1, const uint *y0, uint *result)
uint Div_StandardTest (const UInt< value_size > &v, uint &m, uint &n, UInt< value_size > *remainder=0)
uint Div_CalculatingSize (const UInt< value_size > &v, uint &m, uint &n)
uint Div1_Calculate (const UInt< value_size > &divisor, UInt< value_size > &rest)
uint Div2_Calculate (const UInt< value_size > &divisor, UInt< value_size > *remainder, uint &bits_diff)
uint Div2_FindLeadingBitsAndCheck (const UInt< value_size > &divisor, UInt< value_size > *remainder, uint &table_id, uint &index, uint &divisor_table_id, uint &divisor_index)
bool Div2_DivisorGreaterOrEqual (const UInt< value_size > &divisor, UInt< value_size > *remainder, uint table_id, uint index, uint divisor_index)
void Div3_Division (UInt< value_size > v, UInt< value_size > *remainder, uint m, uint n)
void Div3_MakeNewU (UInt< value_size+1 > &uu, uint j, uint n, uint u_max)
void Div3_CopyNewU (const UInt< value_size+1 > &uu, uint j, uint n)
void Div3_MakeBiggerV (const UInt< value_size > &v, UInt< value_size+1 > &vv)
uint Div3_Normalize (UInt< value_size > &v, uint n, uint &d)
void Div3_Unnormalize (UInt< value_size > *remainder, uint n, uint d)
uint Div3_Calculate (uint u2, uint u1, uint u0, uint v1, uint v0)
void Div3_MultiplySubtract (UInt< value_size+1 > &uu, const UInt< value_size+1 > &vv, uint &qp)
template<class string_type >
void ToStringBase (string_type &result, uint b=10) const
template<class char_type >
uint FromStringBase (const char_type *s, uint b=10, const char_type **after_source=0, bool *value_read=0)
uint Rcl2_one (uint c)
uint Rcr2_one (uint c)
uint Rcl2 (uint bits, uint c)
uint Rcr2 (uint bits, uint c)
Static Private Member Functions
template<class ostream_type , class string_type >
static ostream_type & OutputToStream (ostream_type &s, const UInt< value_size > &l)
template<class istream_type , class string_type , class char_type >
static istream_type & InputFromStream (istream_type &s, UInt< value_size > &l)
Friends
std::ostream & operator<< (std::ostream &s, const UInt< value_size > &l)
std::wostream & operator<< (std::wostream &s, const UInt< value_size > &l)
std::istream & operator>> (std::istream &s, UInt< value_size > &l)
std::wistream & operator>> (std::wistream &s, UInt< value_size > &l)
Detailed Description
template<uint value_size>
class ttmath::UInt< value_size >
UInt implements a big integer value without a sign.
value_size - how many bytes specify our value on 32bit platforms: value_size=1 -> 4 bytes -> 32 bits on 64bit platforms: value_size=1 -> 8 bytes -> 64 bits value_size = 1,2,3,4,5,6....
Constructor & Destructor Documentation
template<uint value_size> ttmath::UInt< value_size >::UInt (uint i) inline
a constructor for converting the uint to this class
References ttmath::UInt< value_size >::FromUInt().
template<uint value_size> ttmath::UInt< value_size >::UInt (sint i) inline
a constructor for converting the sint to this class
look at the description of UInt::operator=(sint)
References ttmath::UInt< value_size >::FromUInt().
template<uint value_size> ttmath::UInt< value_size >::UInt (const char * s) inline
a constructor for converting a string to this class (with the base=10)
References ttmath::UInt< value_size >::FromString().
template<uint value_size> ttmath::UInt< value_size >::UInt (const wchar_t * s) inline
a constructor for converting a string to this class (with the base=10)
References ttmath::UInt< value_size >::FromString().
template<uint value_size> ttmath::UInt< value_size >::UInt (const std::string & s) inline
a constructor for converting a string to this class (with the base=10)
References ttmath::UInt< value_size >::FromString().
template<uint value_size> ttmath::UInt< value_size >::UInt (const std::wstring & s) inline
a constructor for converting a string to this class (with the base=10)
References ttmath::UInt< value_size >::FromString().
template<uint value_size> ttmath::UInt< value_size >::UInt () inline
a default constructor
we don't clear the table
References ttmath::UInt< value_size >::table.
template<uint value_size> ttmath::UInt< value_size >::UInt (const UInt< value_size > & u) inline
a copy constructor
References ttmath::UInt< value_size >::table, and TTMATH_LOG.
template<uint value_size> template<uint argument_size> ttmath::UInt< value_size >::UInt (const UInt< argument_size > & u) inline
a template for producting constructors for copying from another types
References ttmath::UInt< value_size >::FromUInt().
template<uint value_size> ttmath::UInt< value_size >::~UInt () inline
a destructor
Member Function Documentation
template<uint value_size> uint ttmath::UInt< value_size >::Add (const UInt< value_size > & ss2, uint c = 0)
Referenced by ttmath::Int< value_size >::Add(), ttmath::UInt< value_size >::Div1_Calculate(), ttmath::UInt< value_size >::Div3_MultiplySubtract(), ttmath::UInt< value_size >::FromStringBase(), ttmath::UInt< value_size >::Mul1(), ttmath::UInt< value_size >::operator+(), ttmath::UInt< value_size >::operator+=(), and ttmath::UInt< value_size >::Sqrt().
template<uint value_size> uint ttmath::UInt< value_size >::AddInt (uint value, uint index = 0)
Referenced by ttmath::Int< value_size >::AddInt(), ttmath::UInt< value_size >::AddOne(), and ttmath::UInt< value_size >::MulInt().
template<uint value_size> uint ttmath::UInt< value_size >::AddOne () inline
basic mathematic functions
this method adds one to the existing value
References ttmath::UInt< value_size >::AddInt().
Referenced by ttmath::Int< value_size >::AddOne(), and ttmath::UInt< value_size >::operator++().
template<uint value_size> uint ttmath::UInt< value_size >::AddTwoInts (uint x2, uint x1, uint index)
Referenced by ttmath::Int< value_size >::AddTwoInts(), ttmath::UInt< value_size >::Mul2Big3(), and ttmath::UInt< value_size >::MulInt().
template<uint value_size> static uint ttmath::UInt< value_size >::AddTwoWords (uint a, uint b, uint carry, uint * result) static
template<uint value_size> static uint ttmath::UInt< value_size >::AddVector (const uint * ss1, const uint * ss2, uint ss1_size, uint ss2_size, uint * result) static
Referenced by ttmath::UInt< value_size >::Mul3Big3().
template<uint value_size> void ttmath::UInt< value_size >::BitAnd (const UInt< value_size > & ss2) inline
this method performs a bitwise operation AND
References ttmath::UInt< value_size >::table, and TTMATH_LOG.
template<uint value_size> void ttmath::UInt< value_size >::BitNot () inline
this method performs a bitwise operation NOT
References ttmath::UInt< value_size >::table, and TTMATH_LOG.
template<uint value_size> void ttmath::UInt< value_size >::BitNot2 () inline
this method performs a bitwise operation NOT but only on the range of <0, leading_bit>
for example: BitNot2(8) = BitNot2(1000(bin)) = 111(bin) = 7
References ttmath::UInt< value_size >::FindLeadingBit(), ttmath::UInt< value_size >::table, TTMATH_BITS_PER_UINT, TTMATH_LOG, and TTMATH_UINT_MAX_VALUE.
template<uint value_size> void ttmath::UInt< value_size >::BitOr (const UInt< value_size > & ss2) inline
this method performs a bitwise operation OR
References ttmath::UInt< value_size >::table, and TTMATH_LOG.
template<uint value_size> void ttmath::UInt< value_size >::BitXor (const UInt< value_size > & ss2) inline
this method performs a bitwise operation XOR
References ttmath::UInt< value_size >::table, and TTMATH_LOG.
template<uint value_size> void ttmath::UInt< value_size >::ClearFirstBits (uint n) inline
this method sets n first bits to value zero
For example: let n=2 then if there's a value 111 (bin) there'll be '100' (bin)
References ttmath::UInt< value_size >::SetZero(), ttmath::UInt< value_size >::table, TTMATH_BITS_PER_UINT, TTMATH_LOG, and TTMATH_UINT_MAX_VALUE.
template<uint value_size> bool ttmath::UInt< value_size >::CmpBigger (const UInt< value_size > & l, sint index = -1) const inline
this method returns true if 'this' is bigger than 'l'
'index' is an index of the first word from will be the comparison performed (note: we start the comparison from back - from the last word, when index is -1 /default/ it is automatically set into the last word)
I introduced it for some kind of optimization made in the second division algorithm (Div2)
References ttmath::UInt< value_size >::table.
Referenced by ttmath::UInt< value_size >::operator>().
template<uint value_size> bool ttmath::UInt< value_size >::CmpBiggerEqual (const UInt< value_size > & l, sint index = -1) const inline
this method returns true if 'this' is bigger than or equal 'l'
'index' is an index of the first word from will be the comparison performed (note: we start the comparison from back - from the last word, when index is -1 /default/ it is automatically set into the last word)
References ttmath::UInt< value_size >::table.
Referenced by ttmath::UInt< value_size >::Div2(), and ttmath::UInt< value_size >::operator>=().
template<uint value_size> bool ttmath::UInt< value_size >::CmpEqual (const UInt< value_size > & l, sint index = -1) const inline
this method returns true if 'this' is equal 'l'
'index' is an index of the first word from will be the comparison performed (note: we start the comparison from back - from the last word, when index is -1 /default/ it is automatically set into the last word)
References ttmath::UInt< value_size >::table.
Referenced by ttmath::UInt< value_size >::operator==().
template<uint value_size> bool ttmath::UInt< value_size >::CmpSmaller (const UInt< value_size > & l, sint index = -1) const inline
methods for comparing
this method returns true if 'this' is smaller than 'l'
'index' is an index of the first word from will be the comparison performed (note: we start the comparison from back - from the last word, when index is -1 /default/ it is automatically set into the last word) I introduced it for some kind of optimization made in the second division algorithm (Div2)
References ttmath::UInt< value_size >::table.
Referenced by ttmath::UInt< value_size >::Div2_Calculate(), and ttmath::UInt< value_size >::operator<().
template<uint value_size> bool ttmath::UInt< value_size >::CmpSmallerEqual (const UInt< value_size > & l, sint index = -1) const inline
this method returns true if 'this' is smaller than or equal 'l'
'index' is an index of the first word from will be the comparison performed (note: we start the comparison from back - from the last word, when index is -1 /default/ it is automatically set into the last word)
References ttmath::UInt< value_size >::table.
Referenced by ttmath::UInt< value_size >::operator<=().
template<uint value_size> uint ttmath::UInt< value_size >::CompensationToLeft () inline
this method moves all bits into the left side (it returns value how many bits have been moved)
References ttmath::UInt< value_size >::FindLeadingBitInWord(), ttmath::UInt< value_size >::Rcl(), ttmath::UInt< value_size >::table, TTMATH_BITS_PER_UINT, and TTMATH_LOG.
template<uint value_size> uint ttmath::UInt< value_size >::Div (const UInt< value_size > & divisor, UInt< value_size > * remainder = 0, uint algorithm = 3) inline
division this = this / ss2
return values: 0 - ok 1 - division by zero 'this' will be the quotient 'remainder' - remainder
References ttmath::UInt< value_size >::Div1(), ttmath::UInt< value_size >::Div2(), and ttmath::UInt< value_size >::Div3().
Referenced by ttmath::Int< value_size >::Div(), ttmath::UInt< value_size >::Div(), ttmath::UInt< value_size >::operator%(), ttmath::UInt< value_size >::operator%=(), ttmath::UInt< value_size >::operator/(), and ttmath::UInt< value_size >::operator/=().
template<uint value_size> uint ttmath::UInt< value_size >::Div (const UInt< value_size > & divisor, UInt< value_size > & remainder, uint algorithm = 3) inline
References ttmath::UInt< value_size >::Div().
template<uint value_size> uint ttmath::UInt< value_size >::Div1 (const UInt< value_size > & divisor, UInt< value_size > * remainder = 0) inline
the first division algorithm radix 2
References ttmath::UInt< value_size >::Div1_Calculate(), ttmath::UInt< value_size >::Div_StandardTest(), and myllvm::test().
Referenced by ttmath::UInt< value_size >::Div().
template<uint value_size> uint ttmath::UInt< value_size >::Div1_Calculate (const UInt< value_size > & divisor, UInt< value_size > & rest) inline private
References ttmath::UInt< value_size >::Add(), ttmath::UInt< value_size >::Rcl(), ttmath::UInt< value_size >::SetZero(), ttmath::UInt< value_size >::Sub(), TTMATH_BITS_PER_UINT, TTMATH_LOG, and TTMATH_REFERENCE_ASSERT.
Referenced by ttmath::UInt< value_size >::Div1().
template<uint value_size> uint ttmath::UInt< value_size >::Div2 (const UInt< value_size > & divisor, UInt< value_size > * remainder = 0) inline
the second division algorithm
return values: 0 - ok 1 - division by zero
References ttmath::UInt< value_size >::CmpBiggerEqual(), ttmath::UInt< value_size >::Div2_Calculate(), ttmath::UInt< value_size >::SetBit(), ttmath::UInt< value_size >::SetZero(), TTMATH_LOG, and TTMATH_REFERENCE_ASSERT.
Referenced by ttmath::UInt< value_size >::Div(), and ttmath::UInt< value_size >::Div2().
template<uint value_size> uint ttmath::UInt< value_size >::Div2 (const UInt< value_size > & divisor, UInt< value_size > & remainder) inline
References ttmath::UInt< value_size >::Div2().
template<uint value_size> uint ttmath::UInt< value_size >::Div2_Calculate (const UInt< value_size > & divisor, UInt< value_size > * remainder, uint & bits_diff) inline private
return values: 0 - we've calculated the division 1 - division by zero 2 - we have to still calculate
References ttmath::UInt< value_size >::CmpSmaller(), ttmath::UInt< value_size >::Div2_FindLeadingBitsAndCheck(), ttmath::UInt< value_size >::Rcl(), ttmath::UInt< value_size >::Rcr(), ttmath::UInt< value_size >::Sub(), and TTMATH_LOG.
Referenced by ttmath::UInt< value_size >::Div2().
template<uint value_size> bool ttmath::UInt< value_size >::Div2_DivisorGreaterOrEqual (const UInt< value_size > & divisor, UInt< value_size > * remainder, uint table_id, uint index, uint divisor_index) inline private
return values: true if divisor is equal or greater than 'this'
References ttmath::UInt< value_size >::SetOne(), ttmath::UInt< value_size >::SetZero(), ttmath::UInt< value_size >::table, and TTMATH_LOG.
Referenced by ttmath::UInt< value_size >::Div2_FindLeadingBitsAndCheck().
template<uint value_size> uint ttmath::UInt< value_size >::Div2_FindLeadingBitsAndCheck (const UInt< value_size > & divisor, UInt< value_size > * remainder, uint & table_id, uint & index, uint & divisor_table_id, uint & divisor_index) inline private
return values: 0 - we've calculated the division 1 - division by zero 2 - we have to still calculate
References ttmath::UInt< value_size >::Div2_DivisorGreaterOrEqual(), ttmath::UInt< value_size >::DivInt(), ttmath::UInt< value_size >::FindLeadingBit(), ttmath::UInt< value_size >::SetZero(), ttmath::UInt< value_size >::table, TTMATH_BITS_PER_UINT, and TTMATH_LOG.
Referenced by ttmath::UInt< value_size >::Div2_Calculate().
template<uint value_size> uint ttmath::UInt< value_size >::Div3 (const UInt< value_size > & v, UInt< value_size > * remainder = 0) inline
the third division algorithm
this algorithm is described in the following book: "The art of computer programming 2" (4.3.1 page 272) Donald E. Knuth
References ttmath::UInt< value_size >::Div3_Division(), ttmath::UInt< value_size >::Div_StandardTest(), ttmath::UInt< value_size >::DivInt(), ttmath::UInt< value_size >::table, myllvm::test(), TTMATH_LOG, and TTMATH_REFERENCE_ASSERT.
Referenced by ttmath::UInt< value_size >::Div().
template<uint value_size> uint ttmath::UInt< value_size >::Div3_Calculate (uint u2, uint u1, uint u0, uint v1, uint v0) inline private
References ttmath::UInt< value_size >::DivInt(), ttmath::UInt< value_size >::MulTwoWords(), ttmath::UInt< value_size >::SubOne(), ttmath::UInt< value_size >::table, TTMATH_ASSERT, and TTMATH_LOG.
Referenced by ttmath::UInt< value_size >::Div3_Division().
template<uint value_size> void ttmath::UInt< value_size >::Div3_CopyNewU (const UInt< value_size+1 > & uu, uint j, uint n) inline private
References ttmath::UInt< value_size >::table, and TTMATH_LOG.
Referenced by ttmath::UInt< value_size >::Div3_Division().
template<uint value_size> void ttmath::UInt< value_size >::Div3_Division (UInt< value_size > v, UInt< value_size > * remainder, uint m, uint n) inline private
References ttmath::UInt< value_size >::Div3_Calculate(), ttmath::UInt< value_size >::Div3_CopyNewU(), ttmath::UInt< value_size >::Div3_MakeBiggerV(), ttmath::UInt< value_size >::Div3_MakeNewU(), ttmath::UInt< value_size >::Div3_MultiplySubtract(), ttmath::UInt< value_size >::Div3_Normalize(), ttmath::UInt< value_size >::Div3_Unnormalize(), ttmath::UInt< value_size >::table, TTMATH_ASSERT, and TTMATH_LOG.
Referenced by ttmath::UInt< value_size >::Div3().
template<uint value_size> void ttmath::UInt< value_size >::Div3_MakeBiggerV (const UInt< value_size > & v, UInt< value_size+1 > & vv) inline private
we're making the new 'vv' the value is actually the same but the 'table' is bigger (value_size+1)
References ttmath::UInt< value_size >::table, and TTMATH_LOG.
Referenced by ttmath::UInt< value_size >::Div3_Division().
template<uint value_size> void ttmath::UInt< value_size >::Div3_MakeNewU (UInt< value_size+1 > & uu, uint j, uint n, uint u_max) inline private
References ttmath::UInt< value_size >::table, and TTMATH_LOG.
Referenced by ttmath::UInt< value_size >::Div3_Division().
template<uint value_size> void ttmath::UInt< value_size >::Div3_MultiplySubtract (UInt< value_size+1 > & uu, const UInt< value_size+1 > & vv, uint & qp) inline private
References ttmath::UInt< value_size >::Add(), ttmath::UInt< value_size >::MulInt(), ttmath::UInt< value_size >::Sub(), and TTMATH_LOG.
Referenced by ttmath::UInt< value_size >::Div3_Division().
template<uint value_size> uint ttmath::UInt< value_size >::Div3_Normalize (UInt< value_size > & v, uint n, uint & d) inline private
we're moving all bits from 'v' into the left side of the n-1 word (the highest bit at v.table[n-1] will be equal one, the bits from 'this' we're moving the same times as 'v')
return values: d - how many times we've moved return - the next-left value from 'this' (that after table[value_size-1])
References ttmath::UInt< value_size >::FindLeadingBitInWord(), ttmath::UInt< value_size >::Rcl(), ttmath::UInt< value_size >::table, TTMATH_BITS_PER_UINT, and TTMATH_LOG.
Referenced by ttmath::UInt< value_size >::Div3_Division().
template<uint value_size> void ttmath::UInt< value_size >::Div3_Unnormalize (UInt< value_size > * remainder, uint n, uint d) inline private
References ttmath::UInt< value_size >::Rcr(), ttmath::UInt< value_size >::table, and TTMATH_LOG.
Referenced by ttmath::UInt< value_size >::Div3_Division().
template<uint value_size> uint ttmath::UInt< value_size >::Div_CalculatingSize (const UInt< value_size > & v, uint & m, uint & n) inline private
return values: 0 - ok 'm' - is the index (from 0) of last non-zero word in table ('this') 'n' - is the index (from 0) of last non-zero word in v.table 1 - v is zero 2 - 'this' is zero 3 - 'this' is smaller than v 4 - 'this' is equal v
if the return value is different than zero the 'm' and 'n' are undefined
References ttmath::UInt< value_size >::table.
Referenced by ttmath::UInt< value_size >::Div_StandardTest().
template<uint value_size> uint ttmath::UInt< value_size >::Div_StandardTest (const UInt< value_size > & v, uint & m, uint & n, UInt< value_size > * remainder = 0) inline private
return values: 0 - none has to be done 1 - division by zero 2 - division should be made
References ttmath::UInt< value_size >::Div_CalculatingSize(), ttmath::UInt< value_size >::SetOne(), ttmath::UInt< value_size >::SetZero(), and TTMATH_LOG.
Referenced by ttmath::UInt< value_size >::Div1(), and ttmath::UInt< value_size >::Div3().
template<uint value_size> uint ttmath::UInt< value_size >::DivInt (uint divisor, uint * remainder = 0) inline
Division
division by one unsigned word
returns 1 when divisor is zero
References ttmath::UInt< value_size >::DivTwoWords(), ttmath::UInt< value_size >::SetZero(), ttmath::UInt< value_size >::table, and TTMATH_LOG.
Referenced by ttmath::UInt< value_size >::Div2_FindLeadingBitsAndCheck(), ttmath::UInt< value_size >::Div3(), ttmath::UInt< value_size >::Div3_Calculate(), ttmath::Int< value_size >::DivInt(), ttmath::UInt< value_size >::DivInt(), and ttmath::UInt< value_size >::ToStringBase().
template<uint value_size> uint ttmath::UInt< value_size >::DivInt (uint divisor, uint & remainder) inline
References ttmath::UInt< value_size >::DivInt().
template<uint value_size> static void ttmath::UInt< value_size >::DivTwoWords (uint a, uint b, uint c, uint * r, uint * rest) static
Referenced by ttmath::UInt< value_size >::DivInt().
template<uint value_size> bool ttmath::UInt< value_size >::FindLeadingBit (uint & table_id, uint & index) const inline
this method looks for the highest set bit
result: if 'this' is not zero: return value - true 'table_id' - the index of a word <0..value_size-1> 'index' - the index of this set bit in the word <0..31>
if 'this' is zero: return value - false both 'table_id' and 'index' are zero
References ttmath::UInt< value_size >::FindLeadingBitInWord(), and ttmath::UInt< value_size >::table.
Referenced by ttmath::UInt< value_size >::BitNot2(), and ttmath::UInt< value_size >::Div2_FindLeadingBitsAndCheck().
template<uint value_size> static sint ttmath::UInt< value_size >::FindLeadingBitInWord (uint x) static
Referenced by ttmath::UInt< value_size >::CompensationToLeft(), ttmath::UInt< value_size >::Div3_Normalize(), and ttmath::UInt< value_size >::FindLeadingBit().
template<uint value_size> uint ttmath::UInt< value_size >::FromString (const char * s, uint b = 10, const char ** after_source = 0, bool * value_read = 0) inline
this method converts a string into its value it returns carry=1 if the value will be too big or an incorrect base 'b' is given
string is ended with a non-digit value, for example: "12" will be translated to 12 as well as: "12foo" will be translated to 12 too
existing first white characters will be ommited
if the value from s is too large the rest digits will be skipped
after_source (if exists) is pointing at the end of the parsed string
value_read (if exists) tells whether something has actually been read (at least one digit)
References ttmath::UInt< value_size >::FromStringBase().
Referenced by ttmath::UInt< value_size >::FromString(), ttmath::UInt< value_size >::InputFromStream(), ttmath::UInt< value_size >::operator=(), and ttmath::UInt< value_size >::UInt().
template<uint value_size> uint ttmath::UInt< value_size >::FromString (const wchar_t * s, uint b = 10, const wchar_t ** after_source = 0, bool * value_read = 0) inline
this method converts a string into its value
References ttmath::UInt< value_size >::FromStringBase().
template<uint value_size> uint ttmath::UInt< value_size >::FromString (const std::string & s, uint b = 10) inline
this method converts a string into its value
(it returns carry=1 if the value will be too big or an incorrect base 'b' is given)
References ttmath::UInt< value_size >::FromString().
template<uint value_size> uint ttmath::UInt< value_size >::FromString (const std::wstring & s, uint b = 10) inline
this method converts a string into its value
(it returns carry=1 if the value will be too big or an incorrect base 'b' is given)
References ttmath::UInt< value_size >::FromString().
template<uint value_size> template<class char_type > uint ttmath::UInt< value_size >::FromStringBase (const char_type * s, uint b = 10, const char_type ** after_source = 0, bool * value_read = 0) inline private
an auxiliary method for converting from a string
References ttmath::UInt< value_size >::Add(), ttmath::Misc::CharToDigit(), ttmath::UInt< value_size >::Mul(), ttmath::UInt< value_size >::SetZero(), ttmath::Misc::SkipWhiteCharacters(), ttmath::UInt< value_size >::table, and TTMATH_LOGC.
Referenced by ttmath::UInt< value_size >::FromString().
template<uint value_size> template<uint argument_size> uint ttmath::UInt< value_size >::FromUInt (const UInt< argument_size > & p) inline
conversion methods
this method converts an UInt<another_size> type to this class
this operation has mainly sense if the value from p is equal or smaller than that one which is returned from UInt<value_size>::SetMax()
it returns a carry if the value 'p' is too big
References ttmath::UInt< value_size >::table, and TTMATH_LOGC.
Referenced by ttmath::UInt< value_size >::operator=(), and ttmath::UInt< value_size >::UInt().
template<uint value_size> void ttmath::UInt< value_size >::FromUInt (uint value) inline
this method converts the uint type to this class
References ttmath::UInt< value_size >::table, and TTMATH_LOG.
template<uint value_size> uint ttmath::UInt< value_size >::GetBit (uint bit_index) const inline
setting the 'bit_index' bit
bit_index bigger or equal zero
References ttmath::UInt< value_size >::SetBitInWord(), ttmath::UInt< value_size >::table, TTMATH_ASSERT, and TTMATH_BITS_PER_UINT.
template<uint value_size> void ttmath::UInt< value_size >::hash (std::size_t & seed) const inline
References ttmath::UInt< value_size >::table.
template<uint value_size> template<class istream_type , class string_type , class char_type > static istream_type& ttmath::UInt< value_size >::InputFromStream (istream_type & s, UInt< value_size > & l) inline static private
an auxiliary method for reading from standard streams
References ttmath::Misc::CharToDigit(), and ttmath::UInt< value_size >::FromString().
template<uint value_size> bool ttmath::UInt< value_size >::IsTheHighestBitSet () const inline
this method returns true if the highest bit of the value is set
References ttmath::UInt< value_size >::table.
Referenced by ttmath::Int< value_size >::IsSign().
template<uint value_size> bool ttmath::UInt< value_size >::IsTheLowestBitSet () const inline
this method returns true if the lowest bit of the value is set
References ttmath::UInt< value_size >::table.
template<uint value_size> bool ttmath::UInt< value_size >::IsZero () const inline
this method returns true if the value is equal zero
References ttmath::UInt< value_size >::table.
Referenced by ttmath::UInt< value_size >::Pow(), ttmath::UInt< value_size >::Sqrt(), and ttmath::UInt< value_size >::ToStringBase().
template<uint value_size> static LibTypeCode ttmath::UInt< value_size >::LibType () static
template<uint value_size> static const char* ttmath::UInt< value_size >::LibTypeStr () static
template<uint value_size> uint ttmath::UInt< value_size >::Mul (const UInt< value_size > & ss2, uint algorithm = 100) inline
the multiplication 'this' = 'this' * ss2
algorithm: 100 - means automatically choose the fastest algorithm
References ttmath::UInt< value_size >::Mul1(), ttmath::UInt< value_size >::Mul2(), ttmath::UInt< value_size >::Mul3(), and ttmath::UInt< value_size >::MulFastest().
Referenced by ttmath::UInt< value_size >::FromStringBase(), ttmath::UInt< value_size >::operator*(), ttmath::UInt< value_size >::operator*=(), and ttmath::UInt< value_size >::Pow().
template<uint value_size> uint ttmath::UInt< value_size >::Mul1 (const UInt< value_size > & ss2) inline
the first version of the multiplication algorithm
multiplication: this = this * ss2
it returns carry if it has been
References ttmath::UInt< value_size >::Add(), ttmath::UInt< value_size >::Rcl(), ttmath::UInt< value_size >::SetZero(), TTMATH_BITS_PER_UINT, TTMATH_LOGC, and TTMATH_REFERENCE_ASSERT.
Referenced by ttmath::UInt< value_size >::Mul(), and ttmath::UInt< value_size >::Mul1Big().
template<uint value_size> void ttmath::UInt< value_size >::Mul1Big (const UInt< value_size > & ss2_, UInt< value_size *2 > & result) inline
multiplication: result = this * ss2
result is twice bigger than 'this' and 'ss2' this method never returns carry
References ttmath::UInt< value_size >::Mul1(), ttmath::UInt< value_size >::table, and TTMATH_LOG.
Referenced by ttmath::UInt< value_size >::MulBig().
template<uint value_size> uint ttmath::UInt< value_size >::Mul2 (const UInt< value_size > & ss2) inline
the second version of the multiplication algorithm
this algorithm is similar to the 'schoolbook method' which is done by hand
multiplication: this = this * ss2
it returns carry if it has been
References ttmath::UInt< value_size >::Mul2Big(), ttmath::UInt< value_size >::table, and TTMATH_LOGC.
Referenced by ttmath::UInt< value_size >::Mul().
template<uint value_size> void ttmath::UInt< value_size >::Mul2Big (const UInt< value_size > & ss2, UInt< value_size *2 > & result) inline
multiplication: result = this * ss2
result is twice bigger than this and ss2 this method never returns carry
References ttmath::UInt< value_size >::table, and TTMATH_LOG.
Referenced by ttmath::UInt< value_size >::Mul2(), ttmath::UInt< value_size >::MulBig(), and ttmath::UInt< value_size >::MulFastestBig().
template<uint value_size> template<uint ss_size> void ttmath::UInt< value_size >::Mul2Big2 (const uint * ss1, const uint * ss2, UInt< ss_size *2 > & result) inline private
an auxiliary method for calculating the multiplication
arguments we're taking as pointers (this is to improve the Mul3Big2()- avoiding unnecessary copying objects), the result should be taken as a pointer too, but at the moment there is no method AddTwoInts() which can operate on pointers
template<uint value_size> template<uint ss_size> void ttmath::UInt< value_size >::Mul2Big3 (const uint * ss1, const uint * ss2, UInt< ss_size *2 > & result, uint x1start, uint x1size, uint x2start, uint x2size) inline private
an auxiliary method for calculating the multiplication
References ttmath::UInt< value_size >::AddTwoInts(), ttmath::UInt< value_size >::MulTwoWords(), and ttmath::UInt< value_size >::SetZero().
template<uint value_size> uint ttmath::UInt< value_size >::Mul3 (const UInt< value_size > & ss2) inline
multiplication: this = this * ss2
This is Karatsuba Multiplication algorithm, we're using it when value_size is greater than or equal to TTMATH_USE_KARATSUBA_MULTIPLICATION_FROM_SIZE macro (defined in ttmathuint.h). If value_size is smaller then we're using Mul2Big() instead.
Karatsuba multiplication: Assume we have: this = x = x1*B^m + x0 ss2 = y = y1*B^m + y0 where x0 and y0 are less than B^m the product from multiplication we can show as: x*y = (x1*B^m + x0)(y1*B^m + y0) = z2*B^(2m) + z1*B^m + z0 where z2 = x1*y1 z1 = x1*y0 + x0*y1 z0 = x0*y0 this is standard schoolbook algorithm with O(n^2), Karatsuba observed that z1 can be given in other form: z1 = (x1 + x0)*(y1 + y0) - z2 - z0 / z1 = (x1*y1 + x1*y0 + x0*y1 + x0*y0) - x1*y1 - x0*y0 = x1*y0 + x0*y1 / and to calculate the multiplication we need only three multiplications (with some additions and subtractions)
Our objects 'this' and 'ss2' we divide into two parts and by using recurrence we calculate the multiplication. Karatsuba multiplication has O(n^(ln(3)/ln(2)))
References ttmath::UInt< value_size >::Mul3Big(), ttmath::UInt< value_size >::table, and TTMATH_LOGC.
Referenced by ttmath::UInt< value_size >::Mul().
template<uint value_size> void ttmath::UInt< value_size >::Mul3Big (const UInt< value_size > & ss2, UInt< value_size *2 > & result) inline
multiplication: result = this * ss2
result is twice bigger than this and ss2, this method never returns carry, (Karatsuba multiplication)
References ttmath::UInt< value_size >::table, and TTMATH_LOG.
Referenced by ttmath::UInt< value_size >::Mul3(), ttmath::UInt< value_size >::MulBig(), and ttmath::UInt< value_size >::MulFastestBig().
template<uint value_size> template<uint ss_size> void ttmath::UInt< value_size >::Mul3Big2 (const uint * ss1, const uint * ss2, uint * result) inline private
an auxiliary method for calculating the Karatsuba multiplication
result_size is equal ss_size*2
References ttmath::UInt< value_size >::Mul3Big3(), ttmath::UInt< value_size >::MulTwoWords(), ttmath::UInt< value_size >::table, and TTMATH_USE_KARATSUBA_MULTIPLICATION_FROM_SIZE.
template<uint value_size> template<uint first_size, uint second_size, uint result_size> void ttmath::UInt< value_size >::Mul3Big3 (const uint * x1, const uint * x0, const uint * y1, const uint * y0, uint * result) inline private
an auxiliary method for calculating the Karatsuba multiplication
x = x1*B^m + x0 y = y1*B^m + y0
first_size - is the size of vectors: x0 and y0 second_size - is the size of vectors: x1 and y1 (can be either equal first_size or smaller about one from first_size)
x*y = (x1*B^m + x0)(y1*B^m + y0) = z2*B^(2m) + z1*B^m + z0 where z0 = x0*y0 z2 = x1*y1 z1 = (x1 + x0)*(y1 + y0) - z2 - z0
References ttmath::UInt< value_size >::AddVector(), ttmath::UInt< value_size >::SubVector(), ttmath::UInt< value_size >::table, and TTMATH_ASSERT.
Referenced by ttmath::UInt< value_size >::Mul3Big2().
template<uint value_size> void ttmath::UInt< value_size >::MulBig (const UInt< value_size > & ss2, UInt< value_size *2 > & result, uint algorithm = 100) inline
the multiplication 'result' = 'this' * ss2
since the 'result' is twice bigger than 'this' and 'ss2' this method never returns a carry
algorithm: 100 - means automatically choose the fastest algorithm
References ttmath::UInt< value_size >::Mul1Big(), ttmath::UInt< value_size >::Mul2Big(), ttmath::UInt< value_size >::Mul3Big(), and ttmath::UInt< value_size >::MulFastestBig().
template<uint value_size> uint ttmath::UInt< value_size >::MulFastest (const UInt< value_size > & ss2) inline
multiplication this = this * ss2
References ttmath::UInt< value_size >::MulFastestBig(), ttmath::UInt< value_size >::table, and TTMATH_LOGC.
Referenced by ttmath::UInt< value_size >::Mul().
template<uint value_size> void ttmath::UInt< value_size >::MulFastestBig (const UInt< value_size > & ss2, UInt< value_size *2 > & result) inline
multiplication result = this * ss2
this method is trying to select the fastest algorithm (in the future this method can be improved)
References ttmath::UInt< value_size >::Mul2Big(), ttmath::UInt< value_size >::Mul3Big(), ttmath::UInt< value_size >::SetZero(), ttmath::UInt< value_size >::table, TTMATH_LOG, and TTMATH_USE_KARATSUBA_MULTIPLICATION_FROM_SIZE.
Referenced by ttmath::UInt< value_size >::MulBig(), and ttmath::UInt< value_size >::MulFastest().
template<uint value_size> uint ttmath::UInt< value_size >::MulInt (uint ss2) inline
Multiplication
multiplication: this = this * ss2
it can return a carry
References ttmath::UInt< value_size >::AddInt(), ttmath::UInt< value_size >::AddTwoInts(), ttmath::UInt< value_size >::MulTwoWords(), ttmath::UInt< value_size >::SetZero(), ttmath::UInt< value_size >::table, and TTMATH_LOGC.
Referenced by ttmath::UInt< value_size >::Div3_MultiplySubtract().
template<uint value_size> template<uint result_size> void ttmath::UInt< value_size >::MulInt (uint ss2, UInt< result_size > & result) const inline
multiplication: result = this * ss2
we're using this method only when result_size is greater than value_size if so there will not be a carry
References ttmath::UInt< value_size >::AddTwoInts(), ttmath::UInt< value_size >::MulTwoWords(), ttmath::UInt< value_size >::SetZero(), ttmath::UInt< value_size >::table, TTMATH_ASSERT, and TTMATH_VECTOR_LOG.
template<uint value_size> static void ttmath::UInt< value_size >::MulTwoWords (uint a, uint b, uint * result_high, uint * result_low) static
Referenced by ttmath::UInt< value_size >::Div3_Calculate(), ttmath::UInt< value_size >::Mul2Big3(), ttmath::UInt< value_size >::Mul3Big2(), and ttmath::UInt< value_size >::MulInt().
template<uint value_size> bool ttmath::UInt< value_size >::operator!= (const UInt< value_size > & l) const inline
References ttmath::UInt< value_size >::operator==().
Referenced by ttmath::Int< value_size >::operator!=().
template<uint value_size> UInt<value_size> ttmath::UInt< value_size >::operator% (const UInt< value_size > & p2) const inline
References ttmath::UInt< value_size >::Div().
template<uint value_size> UInt<value_size>& ttmath::UInt< value_size >::operator%= (const UInt< value_size > & p2) inline
References ttmath::UInt< value_size >::Div(), and ttmath::UInt< value_size >::operator=().
template<uint value_size> UInt<value_size> ttmath::UInt< value_size >::operator* (const UInt< value_size > & p2) const inline
References ttmath::UInt< value_size >::Mul().
template<uint value_size> UInt<value_size>& ttmath::UInt< value_size >::operator*= (const UInt< value_size > & p2) inline
References ttmath::UInt< value_size >::Mul().
template<uint value_size> UInt<value_size> ttmath::UInt< value_size >::operator+ (const UInt< value_size > & p2) const inline
References ttmath::UInt< value_size >::Add().
template<uint value_size> UInt<value_size>& ttmath::UInt< value_size >::operator++ () inline
Prefix operator e.g ++variable
References ttmath::UInt< value_size >::AddOne().
template<uint value_size> UInt<value_size> ttmath::UInt< value_size >::operator++ (int) inline
Postfix operator e.g variable++
References ttmath::UInt< value_size >::AddOne().
template<uint value_size> UInt<value_size>& ttmath::UInt< value_size >::operator+= (const UInt< value_size > & p2) inline
References ttmath::UInt< value_size >::Add().
template<uint value_size> UInt<value_size> ttmath::UInt< value_size >::operator- (const UInt< value_size > & p2) const inline
standard mathematical operators
References ttmath::UInt< value_size >::Sub().
template<uint value_size> UInt<value_size>& ttmath::UInt< value_size >::operator-- () inline
References ttmath::UInt< value_size >::SubOne().
template<uint value_size> UInt<value_size> ttmath::UInt< value_size >::operator-- (int) inline
References ttmath::UInt< value_size >::SubOne().
template<uint value_size> UInt<value_size>& ttmath::UInt< value_size >::operator-= (const UInt< value_size > & p2) inline
References ttmath::UInt< value_size >::Sub().
template<uint value_size> UInt<value_size> ttmath::UInt< value_size >::operator/ (const UInt< value_size > & p2) const inline
References ttmath::UInt< value_size >::Div().
template<uint value_size> UInt<value_size>& ttmath::UInt< value_size >::operator/= (const UInt< value_size > & p2) inline
References ttmath::UInt< value_size >::Div().
template<uint value_size> bool ttmath::UInt< value_size >::operator< (const UInt< value_size > & l) const inline
References ttmath::UInt< value_size >::CmpSmaller().
template<uint value_size> UInt<value_size> ttmath::UInt< value_size >::operator<< (int move) inline
References ttmath::UInt< value_size >::Rcl().
template<uint value_size> UInt<value_size>& ttmath::UInt< value_size >::operator<<= (int move) inline
References ttmath::UInt< value_size >::Rcl().
template<uint value_size> bool ttmath::UInt< value_size >::operator<= (const UInt< value_size > & l) const inline
References ttmath::UInt< value_size >::CmpSmallerEqual().
template<uint value_size> template<uint argument_size> UInt<value_size>& ttmath::UInt< value_size >::operator= (const UInt< argument_size > & p) inline
this operator converts an UInt<another_size> type to this class
it doesn't return a carry
References ttmath::UInt< value_size >::FromUInt().
Referenced by ttmath::UInt< value_size >::operator%=().
template<uint value_size> UInt<value_size>& ttmath::UInt< value_size >::operator= (const UInt< value_size > & p) inline
the assignment operator
References ttmath::UInt< value_size >::table, and TTMATH_LOG.
template<uint value_size> UInt<value_size>& ttmath::UInt< value_size >::operator= (uint i) inline
this method converts the uint type to this class
References ttmath::UInt< value_size >::FromUInt().
template<uint value_size> UInt<value_size>& ttmath::UInt< value_size >::operator= (sint i) inline
this method converts the sint type to this class
we provide operator(sint) and the constructor(sint) in order to allow the programmer do that: UInt<..> type = 10;
above "10" constant has the int type (signed int), if we don't give such operators and constructors the compiler will not compile the program, because it has to make a conversion and doesn't know into which type (the UInt class has operator=(const char*), operator=(uint) etc.)
References ttmath::UInt< value_size >::FromUInt().
template<uint value_size> UInt<value_size>& ttmath::UInt< value_size >::operator= (const char * s) inline
this operator converts a string into its value (with base = 10)
References ttmath::UInt< value_size >::FromString().
template<uint value_size> UInt<value_size>& ttmath::UInt< value_size >::operator= (const wchar_t * s) inline
this operator converts a string into its value (with base = 10)
References ttmath::UInt< value_size >::FromString().
template<uint value_size> UInt<value_size>& ttmath::UInt< value_size >::operator= (const std::string & s) inline
this operator converts a string into its value (with base = 10)
References ttmath::UInt< value_size >::FromString().
template<uint value_size> UInt<value_size>& ttmath::UInt< value_size >::operator= (const std::wstring & s) inline
this operator converts a string into its value (with base = 10)
References ttmath::UInt< value_size >::FromString().
template<uint value_size> bool ttmath::UInt< value_size >::operator== (const UInt< value_size > & l) const inline
References ttmath::UInt< value_size >::CmpEqual().
Referenced by ttmath::UInt< value_size >::operator!=(), and ttmath::Int< value_size >::operator==().
template<uint value_size> bool ttmath::UInt< value_size >::operator> (const UInt< value_size > & l) const inline
References ttmath::UInt< value_size >::CmpBigger().
template<uint value_size> bool ttmath::UInt< value_size >::operator>= (const UInt< value_size > & l) const inline
References ttmath::UInt< value_size >::CmpBiggerEqual().
template<uint value_size> UInt<value_size> ttmath::UInt< value_size >::operator>> (int move) inline
References ttmath::UInt< value_size >::Rcr().
template<uint value_size> UInt<value_size>& ttmath::UInt< value_size >::operator>>= (int move) inline
References ttmath::UInt< value_size >::Rcr().
template<uint value_size> template<class ostream_type , class string_type > static ostream_type& ttmath::UInt< value_size >::OutputToStream (ostream_type & s, const UInt< value_size > & l) inline static private
input/output operators for standard streams
(they are very simple, in the future they should be changed)
an auxiliary method for outputing to standard streams
References ttmath::UInt< value_size >::ToString().
template<uint value_size> uint ttmath::UInt< value_size >::Pow (UInt< value_size > pow) inline
power this = this ^ pow binary algorithm (r-to-l)
return values: 0 - ok 1 - carry 2 - incorrect argument (0^0)
References ttmath::UInt< value_size >::IsZero(), ttmath::UInt< value_size >::Mul(), ttmath::UInt< value_size >::Rcr2_one(), ttmath::UInt< value_size >::SetOne(), ttmath::UInt< value_size >::table, and TTMATH_LOGC.
Referenced by ttmath::Int< value_size >::Pow2().
template<uint value_size> template<class char_type , class ostream_type > void ttmath::UInt< value_size >::PrintLog (const char_type * msg, ostream_type & output) const inline
this method is used when macro TTMATH_DEBUG_LOG is defined
References ttmath::UInt< value_size >::PrintVectorLog(), and ttmath::UInt< value_size >::table.
template<uint value_size> template<class char_type , class ostream_type > void ttmath::UInt< value_size >::PrintLog (const char_type * msg, uint carry, ostream_type & output) const inline
this method is used when macro TTMATH_DEBUG_LOG is defined
References ttmath::UInt< value_size >::PrintVectorLog(), and ttmath::UInt< value_size >::table.
template<uint value_size> template<class ostream_type > void ttmath::UInt< value_size >::PrintTable (ostream_type & output) const inline
some methods used for debugging purposes
this method is only for debugging purposes or when we want to make a table of a variable (constant) in ttmathbig.h
it prints the table in a nice form of several columns
References ttmath::UInt< value_size >::table.
template<uint value_size> template<class char_type , class ostream_type > static void ttmath::UInt< value_size >::PrintVectorLog (const char_type * msg, ostream_type & output, const uint * vector, uint vector_len) inline static
this method is used when macro TTMATH_DEBUG_LOG is defined
Referenced by ttmath::UInt< value_size >::PrintLog(), and ttmath::UInt< value_size >::PrintVectorLog().
template<uint value_size> template<class char_type , class ostream_type > static void ttmath::UInt< value_size >::PrintVectorLog (const char_type * msg, uint carry, ostream_type & output, const uint * vector, uint vector_len) inline static
this method is used when macro TTMATH_DEBUG_LOG is defined
References ttmath::UInt< value_size >::PrintVectorLog().
template<uint value_size> uint ttmath::UInt< value_size >::Rcl (uint bits, uint c = 0) inline
moving all bits into the left side 'bits' times return value <- this <- C
bits is from a range of <0, man * TTMATH_BITS_PER_UINT> or it can be even bigger then all bits will be set to 'c'
the value c will be set into the lowest bits and the method returns state of the last moved bit
References ttmath::UInt< value_size >::Rcl2(), ttmath::UInt< value_size >::Rcl2_one(), ttmath::UInt< value_size >::RclMoveAllWords(), TTMATH_BITS_PER_UINT, TTMATH_LOG, and TTMATH_LOGC.
Referenced by ttmath::UInt< value_size >::CompensationToLeft(), ttmath::UInt< value_size >::Div1_Calculate(), ttmath::UInt< value_size >::Div2_Calculate(), ttmath::UInt< value_size >::Div3_Normalize(), ttmath::UInt< value_size >::Mul1(), ttmath::UInt< value_size >::operator<<(), and ttmath::UInt< value_size >::operator<<=().
template<uint value_size> uint ttmath::UInt< value_size >::Rcl2 (uint bits, uint c) private
Referenced by ttmath::UInt< value_size >::Rcl().
template<uint value_size> uint ttmath::UInt< value_size >::Rcl2_one (uint c) private
Referenced by ttmath::UInt< value_size >::Rcl().
template<uint value_size> void ttmath::UInt< value_size >::RclMoveAllWords (uint & rest_bits, uint & last_c, uint bits, uint c) inline private
an auxiliary method for moving bits into the left hand side
this method moves only words
References ttmath::UInt< value_size >::table, TTMATH_BITS_PER_UINT, TTMATH_LOG, and TTMATH_UINT_MAX_VALUE.
Referenced by ttmath::UInt< value_size >::Rcl().
template<uint value_size> uint ttmath::UInt< value_size >::Rcr (uint bits, uint c = 0) inline
moving all bits into the right side 'bits' times c -> this -> return value
bits is from a range of <0, man * TTMATH_BITS_PER_UINT> or it can be even bigger then all bits will be set to 'c'
the value c will be set into the highest bits and the method returns state of the last moved bit
References ttmath::UInt< value_size >::Rcr2(), ttmath::UInt< value_size >::Rcr2_one(), ttmath::UInt< value_size >::RcrMoveAllWords(), TTMATH_BITS_PER_UINT, TTMATH_LOG, and TTMATH_LOGC.
Referenced by ttmath::UInt< value_size >::Div2_Calculate(), ttmath::UInt< value_size >::Div3_Unnormalize(), ttmath::UInt< value_size >::operator>>(), ttmath::UInt< value_size >::operator>>=(), and ttmath::UInt< value_size >::Sqrt().
template<uint value_size> uint ttmath::UInt< value_size >::Rcr2 (uint bits, uint c) private
Referenced by ttmath::UInt< value_size >::Rcr().
template<uint value_size> uint ttmath::UInt< value_size >::Rcr2_one (uint c) private
Referenced by ttmath::UInt< value_size >::Pow(), and ttmath::UInt< value_size >::Rcr().
template<uint value_size> void ttmath::UInt< value_size >::RcrMoveAllWords (uint & rest_bits, uint & last_c, uint bits, uint c) inline private
an auxiliary method for moving bits into the right hand side
this method moves only words
References ttmath::UInt< value_size >::table, TTMATH_BITS_PER_UINT, TTMATH_LOG, TTMATH_UINT_HIGHEST_BIT, and TTMATH_UINT_MAX_VALUE.
Referenced by ttmath::UInt< value_size >::Rcr().
template<uint value_size> uint ttmath::UInt< value_size >::SetBit (uint bit_index) inline
setting the 'bit_index' bit and returning the last state of the bit
bit_index bigger or equal zero
References ttmath::UInt< value_size >::SetBitInWord(), ttmath::UInt< value_size >::table, TTMATH_ASSERT, TTMATH_BITS_PER_UINT, and TTMATH_LOG.
Referenced by ttmath::UInt< value_size >::Div2().
template<uint value_size> static uint ttmath::UInt< value_size >::SetBitInWord (uint & value, uint bit) static
Referenced by ttmath::UInt< value_size >::GetBit(), and ttmath::UInt< value_size >::SetBit().
template<uint value_size> void ttmath::UInt< value_size >::SetFromTable (const uint * temp_table, uint temp_table_len) inline
this method copies the value stored in an another table (warning: first values in temp_table are the highest words – it's different from our table)
we copy as many words as it is possible
if temp_table_len is bigger than value_size we'll try to round the lowest word from table depending on the last not used bit in temp_table (this rounding isn't a perfect rounding – look at the description below)
and if temp_table_len is smaller than value_size we'll clear the rest words in the table
References ttmath::UInt< value_size >::table, TTMATH_LOG, TTMATH_UINT_HIGHEST_BIT, and TTMATH_UINT_MAX_VALUE.
template<uint value_size> void ttmath::UInt< value_size >::SetMax () inline
this method sets the max value which this class can hold (all bits will be one)
References ttmath::UInt< value_size >::table, TTMATH_LOG, and TTMATH_UINT_MAX_VALUE.
Referenced by ttmath::Int< value_size >::SetMax(), and ttmath::Int< value_size >::SetSignOne().
template<uint value_size> void ttmath::UInt< value_size >::SetMin () inline
this method sets the min value which this class can hold (for an unsigned integer value the zero is the smallest value)
References ttmath::UInt< value_size >::SetZero(), and TTMATH_LOG.
template<uint value_size> void ttmath::UInt< value_size >::SetOne () inline
this method sets one
References ttmath::UInt< value_size >::SetZero(), ttmath::UInt< value_size >::table, and TTMATH_LOG.
Referenced by ttmath::UInt< value_size >::Div2_DivisorGreaterOrEqual(), ttmath::UInt< value_size >::Div_StandardTest(), ttmath::Int< value_size >::Pow(), and ttmath::UInt< value_size >::Pow().
template<uint value_size> void ttmath::UInt< value_size >::SetZero () inline
this method sets zero
References ttmath::UInt< value_size >::table, and TTMATH_LOG.
Referenced by ttmath::Int< value_size >::ChangeSign(), ttmath::UInt< value_size >::ClearFirstBits(), ttmath::UInt< value_size >::Div1_Calculate(), ttmath::UInt< value_size >::Div2(), ttmath::UInt< value_size >::Div2_DivisorGreaterOrEqual(), ttmath::UInt< value_size >::Div2_FindLeadingBitsAndCheck(), ttmath::UInt< value_size >::Div_StandardTest(), ttmath::UInt< value_size >::DivInt(), ttmath::UInt< value_size >::FromStringBase(), ttmath::UInt< value_size >::Mul1(), ttmath::UInt< value_size >::Mul2Big3(), ttmath::UInt< value_size >::MulFastestBig(), ttmath::UInt< value_size >::MulInt(), ttmath::Int< value_size >::SetMin(), ttmath::UInt< value_size >::SetMin(), ttmath::UInt< value_size >::SetOne(), and ttmath::UInt< value_size >::Sqrt().
template<uint value_size> uint ttmath::UInt< value_size >::Size () const inline
this method returns the size of the table
template<uint value_size> void ttmath::UInt< value_size >::Sqrt () inline
square root e.g. Sqrt(9) = 3 ('digit-by-digit' algorithm)
References ttmath::UInt< value_size >::Add(), ttmath::UInt< value_size >::IsZero(), ttmath::UInt< value_size >::Rcr(), ttmath::UInt< value_size >::SetZero(), ttmath::UInt< value_size >::Sub(), ttmath::UInt< value_size >::table, and TTMATH_LOG.
template<uint value_size> uint ttmath::UInt< value_size >::Sub (const UInt< value_size > & ss2, uint c = 0)
Referenced by ttmath::UInt< value_size >::Div1_Calculate(), ttmath::UInt< value_size >::Div2_Calculate(), ttmath::UInt< value_size >::Div3_MultiplySubtract(), ttmath::UInt< value_size >::operator-(), ttmath::UInt< value_size >::operator-=(), ttmath::UInt< value_size >::Sqrt(), and ttmath::Int< value_size >::Sub().
template<uint value_size> uint ttmath::UInt< value_size >::SubInt (uint value, uint index = 0)
Referenced by ttmath::Int< value_size >::SubInt(), and ttmath::UInt< value_size >::SubOne().
template<uint value_size> uint ttmath::UInt< value_size >::SubOne () inline
this method subtracts one from the existing value
References ttmath::UInt< value_size >::SubInt().
Referenced by ttmath::UInt< value_size >::Div3_Calculate(), ttmath::UInt< value_size >::operator--(), and ttmath::Int< value_size >::SubOne().
template<uint value_size> static uint ttmath::UInt< value_size >::SubTwoWords (uint a, uint b, uint carry, uint * result) static
template<uint value_size> static uint ttmath::UInt< value_size >::SubVector (const uint * ss1, const uint * ss2, uint ss1_size, uint ss2_size, uint * result) static
Referenced by ttmath::UInt< value_size >::Mul3Big3().
template<uint value_size> void ttmath::UInt< value_size >::ToString (std::string & result, uint b = 10) const inline
this method converts the value to a string with a base equal 'b'
References ttmath::UInt< value_size >::ToStringBase().
Referenced by ttmath::UInt< value_size >::OutputToStream(), and ttmath::Int< value_size >::ToStringBase().
template<uint value_size> void ttmath::UInt< value_size >::ToString (std::wstring & result, uint b = 10) const inline
References ttmath::UInt< value_size >::ToStringBase().
template<uint value_size> std::string ttmath::UInt< value_size >::ToString (uint b = 10) const inline
References ttmath::UInt< value_size >::ToStringBase().
template<uint value_size> template<class string_type > void ttmath::UInt< value_size >::ToStringBase (string_type & result, uint b = 10) const inline private
an auxiliary method for converting to a string
References ttmath::Misc::DigitToChar(), ttmath::UInt< value_size >::DivInt(), and ttmath::UInt< value_size >::IsZero().
Referenced by ttmath::UInt< value_size >::ToString(), and ttmath::UInt< value_size >::ToWString().
template<uint value_size> uint ttmath::UInt< value_size >::ToUInt () const inline
this method returns the lowest value from table
we must be sure when we using this method whether the value will hold in an uint type or not (the rest value from the table must be zero)
References ttmath::UInt< value_size >::table.
template<uint value_size> std::wstring ttmath::UInt< value_size >::ToWString (uint b = 10) const inline
References ttmath::UInt< value_size >::ToStringBase().
Friends And Related Function Documentation
template<uint value_size> std::ostream& operator<< (std::ostream & s, const UInt< value_size > & l) friend
output to standard streams
template<uint value_size> std::wostream& operator<< (std::wostream & s, const UInt< value_size > & l) friend
output to standard streams
template<uint value_size> std::istream& operator>> (std::istream & s, UInt< value_size > & l) friend
input from standard streams
template<uint value_size> std::wistream& operator>> (std::wistream & s, UInt< value_size > & l) friend
input from standard streams
Member Data Documentation
template<uint value_size> uint ttmath::UInt< value_size >::table[value_size]
buffer for the integer value table[0] - the lowest word of the value
Referenced by ttmath::UInt< value_size >::BitAnd(), ttmath::UInt< value_size >::BitNot(), ttmath::UInt< value_size >::BitNot2(), ttmath::UInt< value_size >::BitOr(), ttmath::UInt< value_size >::BitXor(), ttmath::UInt< value_size >::ClearFirstBits(), ttmath::UInt< value_size >::CmpBigger(), ttmath::UInt< value_size >::CmpBiggerEqual(), ttmath::UInt< value_size >::CmpEqual(), ttmath::UInt< value_size >::CmpSmaller(), ttmath::UInt< value_size >::CmpSmallerEqual(), ttmath::UInt< value_size >::CompensationToLeft(), ttmath::UInt< value_size >::Div2_DivisorGreaterOrEqual(), ttmath::UInt< value_size >::Div2_FindLeadingBitsAndCheck(), ttmath::UInt< value_size >::Div3(), ttmath::UInt< value_size >::Div3_Calculate(), ttmath::UInt< value_size >::Div3_CopyNewU(), ttmath::UInt< value_size >::Div3_Division(), ttmath::UInt< value_size >::Div3_MakeBiggerV(), ttmath::UInt< value_size >::Div3_MakeNewU(), ttmath::UInt< value_size >::Div3_Normalize(), ttmath::UInt< value_size >::Div3_Unnormalize(), ttmath::UInt< value_size >::Div_CalculatingSize(), ttmath::UInt< value_size >::DivInt(), ttmath::UInt< value_size >::FindLeadingBit(), ttmath::UInt< value_size >::FromStringBase(), ttmath::UInt< value_size >::FromUInt(), ttmath::Int< value_size >::FromUIntOrInt(), ttmath::UInt< value_size >::GetBit(), ttmath::UInt< value_size >::hash(), ttmath::UInt< value_size >::IsTheHighestBitSet(), ttmath::UInt< value_size >::IsTheLowestBitSet(), ttmath::UInt< value_size >::IsZero(), ttmath::UInt< value_size >::Mul1Big(), ttmath::UInt< value_size >::Mul2(), ttmath::UInt< value_size >::Mul2Big(), ttmath::UInt< value_size >::Mul3(), ttmath::UInt< value_size >::Mul3Big(), ttmath::UInt< value_size >::Mul3Big2(), ttmath::UInt< value_size >::Mul3Big3(), ttmath::UInt< value_size >::MulFastest(), ttmath::UInt< value_size >::MulFastestBig(), ttmath::UInt< value_size >::MulInt(), ttmath::Int< value_size >::operator<(), ttmath::Int< value_size >::operator<=(), ttmath::UInt< value_size >::operator=(), ttmath::Int< value_size >::operator>(), ttmath::Int< value_size >::operator>=(), ttmath::UInt< value_size >::Pow(), ttmath::Int< value_size >::Pow2(), ttmath::UInt< value_size >::PrintLog(), ttmath::UInt< value_size >::PrintTable(), ttmath::UInt< value_size >::RclMoveAllWords(), ttmath::UInt< value_size >::RcrMoveAllWords(), ttmath::UInt< value_size >::SetBit(), ttmath::UInt< value_size >::SetFromTable(), ttmath::UInt< value_size >::SetMax(), ttmath::UInt< value_size >::SetOne(), ttmath::UInt< value_size >::SetZero(), ttmath::UInt< value_size >::Sqrt(), ttmath::UInt< value_size >::ToUInt(), and ttmath::UInt< value_size >::UInt().
The documentation for this class was generated from the following file:
common/types/ttmath/ttmathuint.h