Claims: TimeOutReceiver Class Reference
TimeOutReceiver Class Reference
#include <TimeOutReceiver.h>
Inherits Receiver.
Public Member Functions
TimeOutReceiver (Theron::EndPoint *endpoint)
TimeOutReceiver (Theron::EndPoint *endpoint, const char *name)
virtual ~TimeOutReceiver ()
unsigned TimeOutWait (unsigned expected_message_count, unsigned time_out_in_ms)
Constructor & Destructor Documentation
TimeOutReceiver::TimeOutReceiver (Theron::EndPoint * endpoint)
TimeOutReceiver::TimeOutReceiver (Theron::EndPoint * endpoint, const char * name)
TimeOutReceiver::~TimeOutReceiver () virtual
Referenced by ExchangeTracker::AskForSocketConnectionInfo(), and Coordinator::ListeningNewNode().
Member Function Documentation
unsigned TimeOutReceiver::TimeOutWait (unsigned expected_message_count, unsigned time_out_in_ms)
This function supports timeout Wait. The calling of this method will be blocked until one of the following conditions satisfied. (1) expected number of messages are received before the timeout. Then the return value is the number of expected messages. (2) The time is out before expected number of messages are received. Then the return value is the number of received messages. E.g., TimeOutWait(10,1000)==10 will return true if 10 messages are received within 1 second, and will false if less than 10 messages are received within 1 second.
References curtick(), and getMilliSecond().
Referenced by IteratorExecutorMaster::ExecuteBlockStreamIteratorsOnSites(), Coordinator::ListeningNewNode(), InstanceResourceManager::Register(), BlockManagerMaster::SendBindingMessage(), and BlockManagerMaster::SendUnbindingMessage().
The documentation for this class was generated from the following files:
common/TimeOutReceiver.h
common/TimeOutReceiver.cpp