Claims: BlockManager::BlockManagerWorkerActor Class Reference
BlockManager::BlockManagerWorkerActor Class Reference
#include <BlockManager.h>
Inherits Actor.
Public Member Functions
BlockManagerWorkerActor (Theron::Framework *framework, const char *name, BlockManager *bm)
virtual ~BlockManagerWorkerActor ()
bool _reigisterToMaster (BlockManagerId *bMId)
bool _sendHeartBeat ()
bool _reportBlockStatus (string blockId)
string _askformatch (string filename, BlockManagerId bmi)
Private Member Functions
void getBlock (const Message256 &message, const Theron::Address from)
void putBlock (const Message256 &message, const Theron::Address from)
void BindingPartition (const PartitionBindingMessage &message, const Theron::Address from)
void UnbindingPartition (const PartitionUnbindingMessage &message, const Theron::Address from)
Private Attributes
TimeOutReceiver * tor_
string receiverId_
BlockManager * bm_
Friends
class BlockManager
Constructor & Destructor Documentation
BlockManager::BlockManagerWorkerActor::BlockManagerWorkerActor (Theron::Framework * framework, const char * name, BlockManager * bm)
References BindingPartition(), getBlock(), putBlock(), and UnbindingPartition().
BlockManager::BlockManagerWorkerActor::~BlockManagerWorkerActor () virtual
Member Function Documentation
string BlockManager::BlockManagerWorkerActor::_askformatch (string filename, BlockManagerId bmi)
Referenced by BlockManager::askForMatch().
bool BlockManager::BlockManagerWorkerActor::_reigisterToMaster (BlockManagerId * bMId)
Referenced by BlockManager::registerToMaster().
bool BlockManager::BlockManagerWorkerActor::_reportBlockStatus (string blockId)
Referenced by BlockManager::tryToReportBlockStatus().
bool BlockManager::BlockManagerWorkerActor::_sendHeartBeat ()
Referenced by BlockManager::heartBeat().
void BlockManager::BlockManagerWorkerActor::BindingPartition (const PartitionBindingMessage & message, const Theron::Address from) private
References PartitionBindingMessage::number_of_chunks, PartitionBindingMessage::partition_id, and PartitionBindingMessage::storage_level.
Referenced by BlockManagerWorkerActor().
void BlockManager::BlockManagerWorkerActor::getBlock (const Message256 & message, const Theron::Address from) inline private
Referenced by BlockManagerWorkerActor().
void BlockManager::BlockManagerWorkerActor::putBlock (const Message256 & message, const Theron::Address from) inline private
Referenced by BlockManagerWorkerActor().
void BlockManager::BlockManagerWorkerActor::UnbindingPartition (const PartitionUnbindingMessage & message, const Theron::Address from) private
References PartitionUnbindingMessage::partition_id.
Referenced by BlockManagerWorkerActor().
Friends And Related Function Documentation
friend class BlockManager friend
Member Data Documentation
BlockManager* BlockManager::BlockManagerWorkerActor::bm_ private
string BlockManager::BlockManagerWorkerActor::receiverId_ private
TimeOutReceiver* BlockManager::BlockManagerWorkerActor::tor_ private
The documentation for this class was generated from the following files:
storage/BlockManager.h
storage/BlockManager.cpp