Claims: TableDescriptor Class Reference
TableDescriptor Class Reference
#include <table.h>
Public Member Functions
TableDescriptor ()
TableDescriptor (const string &name, const TableID table_id)
virtual ~TableDescriptor ()
void addAttribute (Attribute attr)
bool addAttribute (string attname, data_type dt, unsigned max_length=0, bool unique=false, bool can_be_null=true)
bool createHashPartitionedProjection (vector< ColumnOffset > column_list, ColumnOffset partition_key_index, unsigned number_of_partitions)
bool createHashPartitionedProjection (vector< ColumnOffset > column_list, std::string partition_attribute_name, unsigned number_of_partitions)
bool createHashPartitionedProjection (vector< Attribute > column_list, std::string partition_attribute_name, unsigned number_of_partitions)
bool createHashPartitionedProjectionOnAllAttribute (std::string partition_attribute_name, unsigned number_of_partitions)
bool isExist (const string &name) const
string getTableName () const
ColumnOffset getColumnID (const string &attrName) const
map< string, set< string > > getColumnLocations (const string &attrName) const
vector< Attribute > getAttributes () const
vector< Attribute > getAttributes (vector< unsigned > index_list) const
Attribute getAttribute (unsigned offset) const
Attribute getAttribute (const std::string &name) const
Attribute getAttribute2 (const std::string &name) const
void addColumn (ProjectionDescriptor *column)
string get_table_name () const
TableID get_table_id () const
ProjectionDescriptor * getProjectoin (ProjectionOffset) const
unsigned getNumberOfProjection () const
Schema * getSchema () const
void setRowNumber (unsigned long row_number)
unsigned long getRowNumber ()
unsigned long isEmpty ()
unsigned int getNumberOfAttribute ()
Protected Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Protected Attributes
string tableName
vector< Attribute > attributes
TableID table_id_
vector< ProjectionDescriptor * > projection_list_
unsigned long row_number_
Friends
class boost::serialization::access
Constructor & Destructor Documentation
TableDescriptor::TableDescriptor () inline
TableDescriptor::TableDescriptor (const string & name, const TableID table_id)
TableDescriptor::~TableDescriptor () virtual
Member Function Documentation
void TableDescriptor::addAttribute (Attribute attr)
References attributes.
Referenced by BindingTest(), create_load_test(), create_poc_data_four_partitions(), create_poc_data_one_partitions(), CreateTable(), execting_test(), claims::stmt_handler::CreateTableExec::Execute(), init_multi_node_tpc_h_envoriment_(), init_poc_environment(), init_single_node_tpc_h_envoriment_(), init_single_node_tpc_h_envoriment_ing(), init_single_node_tpc_h_envoriment_sort(), init_tt_environment(), load_tpc_h_4_partition(), loadData(), startup_catalog(), startup_mulitple_node_environment_of_poc(), startup_multiple_node_environment(), startup_multiple_node_environment_of_stock(), startup_multiple_node_environment_of_tpch(), startup_single_node_environment_of_tpch(), startup_single_node_one_partition_environment_of_tpch(), statistic_manager_test(), TableDescriptor_test(), test_CSBIndexBuilding(), test_index_scan_iterator(), test_logical_csb_index_building(), and variable_schema_test().
bool TableDescriptor::addAttribute (string attname, data_type dt, unsigned max_length = 0, bool unique = false, bool can_be_null = true)
References attributes, table_id_, and tableName.
void TableDescriptor::addColumn (ProjectionDescriptor * column)
bool TableDescriptor::createHashPartitionedProjection (vector< ColumnOffset > column_list, ColumnOffset partition_key_index, unsigned number_of_partitions)
References attributes, PartitionFunctionFactory::createGeneralModuloFunction(), projection_list_, and table_id_.
Referenced by BindingTest(), create_load_test(), create_poc_data_four_partitions(), create_poc_data_one_partitions(), CreateProjection(), execting_test(), init_poc_environment(), init_tt_environment(), loadData(), startup_catalog(), startup_mulitple_node_environment_of_poc(), startup_multiple_node_environment(), statistic_manager_test(), TableDescriptor_test(), test_CSBIndexBuilding(), test_index_scan_iterator(), test_logical_csb_index_building(), and variable_schema_test().
bool TableDescriptor::createHashPartitionedProjection (vector< ColumnOffset > column_list, std::string partition_attribute_name, unsigned number_of_partitions)
References attributes, PartitionFunctionFactory::createGeneralModuloFunction(), getAttribute(), projection_list_, and table_id_.
bool TableDescriptor::createHashPartitionedProjection (vector< Attribute > column_list, std::string partition_attribute_name, unsigned number_of_partitions)
References attributes, PartitionFunctionFactory::createGeneralModuloFunction(), getAttribute(), projection_list_, and table_id_.
bool TableDescriptor::createHashPartitionedProjectionOnAllAttribute (std::string partition_attribute_name, unsigned number_of_partitions)
References attributes, PartitionFunctionFactory::createGeneralModuloFunction(), getAttribute2(), projection_list_, and table_id_.
Referenced by init_multi_node_tpc_h_envoriment_(), init_single_node_tpc_h_envoriment_(), init_single_node_tpc_h_envoriment_ing(), init_single_node_tpc_h_envoriment_sort(), load_tpc_h_4_partition(), startup_multiple_node_environment_of_tpch(), startup_single_node_environment_of_tpch(), and startup_single_node_one_partition_environment_of_tpch().
TableID TableDescriptor::get_table_id () const inline
Referenced by Catalog::add_table(), create_load_test(), CreateProjection(), and statistic_manager_test().
string TableDescriptor::get_table_name () const inline
Attribute TableDescriptor::getAttribute (unsigned offset) const inline
Referenced by Analyzer::analyse(), bulk_test_logical_index_scan(), Analyzer::computeHistogram(), createHashPartitionedProjection(), CreateProjection(), Estimation::estEqualJoin(), Estimation::estEqualOper(), Estimation::estRangeOper(), claims::stmt_handler::InsertExec::Execute(), get_aggregation_args(), init_single_node_tpc_h_envoriment_ing(), InsertData(), claims::stmt_handler::InsertExec::InsertValueToStream(), InsertValueToStream(), lineitem_scan_aggregation(), lineitem_scan_filter(), lineitem_scan_self_join(), claims::logical_operator::LogicalScan::LogicalScan(), query_1(), query_2(), query_3(), query_select_aggregation(), query_select_fzh(), sb_scan_aggregation(), sb_scan_filter(), sb_scan_self_join(), test_complete_repartition_filtered_join(), test_complete_repartition_scan_join(), test_index_filter_performance(), test_logical_csb_index_building(), test_logical_index_building(), test_logical_index_scan(), test_multiple_complete_repartition_filtered_join(), test_multiple_complete_repartition_scan_join(), test_multiple_no_repartition_filtered_join(), test_multiple_no_repartition_scan_join(), test_multiple_scan(), test_multiple_scan_filter_Aggregation(), test_multiple_scan_filter_high_selectivity(), test_multiple_scan_filter_low_selectivity(), test_multiple_scan_filter_Scalar_Aggregation(), test_no_repartition_filtered_join(), test_no_repartition_scan_join(), test_scan(), test_scan_Aggregation_large_Groups(), test_scan_Aggregation_small_Groups(), test_scan_filter_Aggregation(), test_scan_filter_high_selectivity(), test_scan_filter_low_selectivity(), test_scan_filter_performance(), and test_scan_filter_Scalar_Aggregation().
Attribute TableDescriptor::getAttribute (const std::string & name) const
References attributes, and tableName.
Attribute TableDescriptor::getAttribute2 (const std::string & name) const
References attributes.
Referenced by createHashPartitionedProjectionOnAllAttribute().
vector<Attribute> TableDescriptor::getAttributes () const inline
Referenced by add_all_table_column(), add_table_column(), Analyzer::analyse(), AstSelectStmt::GetLogicalPlanOfProject(), getSchema(), claims::logical_operator::LogicalScan::LogicalScan(), and AstTable::SemanticAnalisys().
vector<Attribute> TableDescriptor::getAttributes (vector< unsigned > index_list) const inline
ColumnOffset TableDescriptor::getColumnID (const string & attrName) const
map<string, set<string> > TableDescriptor::getColumnLocations (const string & attrName) const
unsigned int TableDescriptor::getNumberOfAttribute () inline
Referenced by claims::stmt_handler::InsertExec::Execute(), and InsertData().
unsigned TableDescriptor::getNumberOfProjection () const
References projection_list_.
Referenced by Analyzer::analyse(), HdfsLoader::append(), Analyzer::computeHistogram(), CreateProjection(), Catalog::getPartitionIDList(), claims::logical_operator::LogicalScan::GetPlanContext(), HdfsLoader::HdfsLoader(), HdfsLoader::insertRecords(), and HdfsLoader::load().
ProjectionDescriptor * TableDescriptor::getProjectoin (ProjectionOffset pid) const
References NULL, and projection_list_.
Referenced by Analyzer::analyse(), HdfsLoader::append(), BindingTest(), bulk_test_logical_index_scan(), Analyzer::compute_table_stat(), Analyzer::computeHistogram(), create_poc_data_four_partitions(), create_poc_data_one_partitions(), CreateProjection(), execting_test(), Catalog::getPartitionIDList(), claims::logical_operator::LogicalScan::GetPlanContext(), Catalog::getProjection(), HdfsLoader::HdfsLoader(), init_multi_node_tpc_h_envoriment_(), init_poc_environment(), init_single_node_tpc_h_envoriment_(), init_single_node_tpc_h_envoriment_ing(), init_single_node_tpc_h_envoriment_sort(), init_tt_environment(), insert_into_hash_table_from_projection(), lineitem_scan_aggregation(), lineitem_scan_filter(), lineitem_scan_self_join(), HdfsLoader::load(), loadData(), LogicalCSBIndexBuilding::LogicalCSBIndexBuilding(), LogicalIndexScan::LogicalIndexScan(), projection_scan(), query_1(), query_2(), query_3(), query_select_aggregation(), query_select_aggregation_ing(), query_select_fzh(), query_select_sort(), query_select_sort_string(), sb_scan_aggregation(), sb_scan_filter(), sb_scan_self_join(), startup_catalog(), startup_mulitple_node_environment_of_poc(), startup_multiple_node_environment(), startup_multiple_node_environment_of_stock(), startup_multiple_node_environment_of_tpch(), startup_single_node_environment_of_tpch(), startup_single_node_one_partition_environment_of_tpch(), statistic_manager_test(), test_block_construct(), test_complete_repartition_filtered_join(), test_complete_repartition_scan_join(), test_CSBIndexBuilding(), test_index_filter_performance(), test_index_scan_iterator(), test_logical_csb_index_building(), test_logical_index_building(), test_logical_index_scan(), test_multiple_complete_repartition_filtered_join(), test_multiple_complete_repartition_scan_join(), test_multiple_no_repartition_filtered_join(), test_multiple_no_repartition_scan_join(), test_multiple_scan(), test_multiple_scan_filter_Aggregation(), test_multiple_scan_filter_high_selectivity(), test_multiple_scan_filter_low_selectivity(), test_multiple_scan_filter_Scalar_Aggregation(), test_no_repartition_filtered_join(), test_no_repartition_scan_join(), test_scan(), test_scan_Aggregation_large_Groups(), test_scan_Aggregation_small_Groups(), test_scan_filter_Aggregation(), test_scan_filter_high_selectivity(), test_scan_filter_low_selectivity(), test_scan_filter_performance(), test_scan_filter_Scalar_Aggregation(), and variable_schema_test().
unsigned long TableDescriptor::getRowNumber () inline
Referenced by append_test(), create_load_test(), HdfsLoader::HdfsLoader(), and inmemory_append_test().
Schema * TableDescriptor::getSchema () const
References attributes, and getAttributes().
Referenced by HdfsLoader::HdfsLoader().
string TableDescriptor::getTableName () const inline
Referenced by Catalog::add_table(), claims::stmt_handler::InsertExec::Execute(), InsertData(), and ShowTable().
unsigned long TableDescriptor::isEmpty () inline
bool TableDescriptor::isExist (const string & name) const
References attributes.
Referenced by CreateProjection(), and Catalog::isAttributeExist().
template<class Archive > void TableDescriptor::serialize (Archive & ar, const unsigned int version) inline protected
void TableDescriptor::setRowNumber (unsigned long row_number) inline
Referenced by HdfsLoader::append(), and HdfsLoader::load().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
vector<Attribute> TableDescriptor::attributes protected
Referenced by addAttribute(), createHashPartitionedProjection(), createHashPartitionedProjectionOnAllAttribute(), getAttribute(), getAttribute2(), getSchema(), and isExist().
vector<ProjectionDescriptor*> TableDescriptor::projection_list_ protected
Referenced by createHashPartitionedProjection(), createHashPartitionedProjectionOnAllAttribute(), getNumberOfProjection(), and getProjectoin().
unsigned long TableDescriptor::row_number_ protected
TableID TableDescriptor::table_id_ protected
Referenced by addAttribute(), createHashPartitionedProjection(), and createHashPartitionedProjectionOnAllAttribute().
string TableDescriptor::tableName protected
Referenced by addAttribute(), and getAttribute().
The documentation for this class was generated from the following files:
Catalog/table.h
Catalog/table.cpp