Claims: BufferManager Class Reference
BufferManager Class Reference
#include <BufferManager.h>
Public Member Functions
virtual ~BufferManager ()
bool applyStorageDedget (unsigned long size)
unsigned getStorageMemoryBudegeInMilibyte () const
void returnStorageBudget (unsigned long size)
Static Public Member Functions
static BufferManager * getInstance ()
Private Member Functions
BufferManager ()
unsigned long int getTotalUsed () const
Private Attributes
unsigned long int totol_capacity_
unsigned long int storage_budget_max_
unsigned long int storage_used_
unsigned long int storage_budget_min_
unsigned long int intermediate_buffer_budget_max_
unsigned long int intermediate_buffer_budget_min_
unsigned long int intermediate_buffer_used_
MemoryChunkStore * memory_storage_
Lock lock_
Logging * logging_
Static Private Attributes
static BufferManager * instance_ =0
Constructor & Destructor Documentation
BufferManager::~BufferManager () virtual
References instance_, and logging_.
BufferManager::BufferManager () private
References MemoryChunkStore::getInstance(), intermediate_buffer_budget_max_, intermediate_buffer_budget_min_, intermediate_buffer_used_, Logging::log(), logging_, memory_storage_, storage_budget_max_, storage_budget_min_, storage_used_, and totol_capacity_.
Referenced by getInstance().
Member Function Documentation
bool BufferManager::applyStorageDedget (unsigned long size)
References Lock::acquire(), lock_, Logging::log(), logging_, Lock::release(), storage_budget_max_, and storage_used_.
BufferManager * BufferManager::getInstance () static
References BufferManager(), and instance_.
Referenced by MemoryChunkStore::applyChunk(), BlockManager::initialize(), Environment::initializeBufferManager(), and MemoryChunkStore::returnChunk().
unsigned BufferManager::getStorageMemoryBudegeInMilibyte () const
References storage_budget_max_.
Referenced by BlockManager::initialize().
unsigned long int BufferManager::getTotalUsed () const private
References intermediate_buffer_used_, and storage_used_.
void BufferManager::returnStorageBudget (unsigned long size)
References Lock::acquire(), lock_, Lock::release(), and storage_used_.
Referenced by MemoryChunkStore::returnChunk().
Member Data Documentation
BufferManager * BufferManager::instance_ =0 static private
Referenced by getInstance(), and ~BufferManager().
unsigned long int BufferManager::intermediate_buffer_budget_max_ private
Referenced by BufferManager().
unsigned long int BufferManager::intermediate_buffer_budget_min_ private
Referenced by BufferManager().
unsigned long int BufferManager::intermediate_buffer_used_ private
Referenced by BufferManager(), and getTotalUsed().
Lock BufferManager::lock_ private
Referenced by applyStorageDedget(), and returnStorageBudget().
Logging* BufferManager::logging_ private
Referenced by applyStorageDedget(), BufferManager(), and ~BufferManager().
MemoryChunkStore* BufferManager::memory_storage_ private
Referenced by BufferManager().
unsigned long int BufferManager::storage_budget_max_ private
Referenced by applyStorageDedget(), BufferManager(), and getStorageMemoryBudegeInMilibyte().
unsigned long int BufferManager::storage_budget_min_ private
Referenced by BufferManager().
unsigned long int BufferManager::storage_used_ private
Referenced by applyStorageDedget(), BufferManager(), getTotalUsed(), and returnStorageBudget().
unsigned long int BufferManager::totol_capacity_ private
Referenced by BufferManager().
The documentation for this class was generated from the following files:
Resource/BufferManager.h
Resource/BufferManager.cpp