Claims: Schema Class Reference
Schema Class Reference abstract
#include <Schema.h>
Public Types
enum schema_type { fixed, varaible }
Public Member Functions
Schema (const std::vector< column_type > &columns)
Schema (const Schema &r)
Schema ()
virtual ~Schema ()
virtual unsigned getTupleMaxSize () const =0
virtual unsigned getTupleActualSize (void *tuple) const =0
virtual void getColumnValue (unsigned index, void *src, void *desc)=0
virtual int getColumnOffset (unsigned index) const =0
virtual void * getColumnAddess (const unsigned &index, const void *const &column_start) const __attribute__((always_inline))=0
virtual unsigned copyTuple (void *src, void *desc) const =0
unsigned getncolumns () const
virtual Schema * getSubSchema (std::vector< unsigned >) const =0
virtual Schema * duplicateSchema () const =0
const column_type & getcolumn (const unsigned index) const
virtual schema_type getSchemaType () const =0
virtual void addColumn (column_type ct, unsigned size)
virtual void displayTuple (const void *tuple_start_address, const char *spliter="|") const
virtual void toValue (std::string text_tuple, void *binary_tuple, const char attr_separator)
virtual void showAccum_off ()
bool hasSameSchema (Schema *schema)
virtual std::string getColumnValue (const void *tuple_start_address, int i)
Public Attributes
std::vector< column_type > columns
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Member Enumeration Documentation
enum Schema::schema_type
Enumerator
fixed
varaible
Constructor & Destructor Documentation
Schema::Schema (const std::vector< column_type > & columns)
Schema::Schema (const Schema & r)
References columns.
Schema::Schema () inline
Schema::~Schema () virtual
Referenced by fill_basic_hash_table(), projection_scan(), and TEST().
Member Function Documentation
virtual void Schema::addColumn (column_type ct, unsigned size) inline virtual
Reimplemented in SchemaFix.
virtual unsigned Schema::copyTuple (void * src, void * desc) const inline pure virtual
Implemented in SchemaFix, and SchemaVar.
Referenced by insert_into_hash_table(), insert_into_hash_table_from_projection(), claims::physical_operator::PhysicalLimit::Next(), claims::physical_operator::ExchangeSenderMaterialized::Next(), claims::physical_operator::PhysicalNestLoopJoin::Next(), claims::physical_operator::InOperator::Next(), claims::physical_operator::ExchangeSenderPipeline::Next(), IndexScanIterator::Next(), claims::physical_operator::PhysicalHashJoin::Next(), claims::physical_operator::PhysicalHashJoin::Open(), and bottomLayerSorting::Open().
void Schema::displayTuple (const void * tuple_start_address, const char * spliter = "|") const virtual
References columns, and getColumnAddess().
Referenced by claims::physical_operator::ResultPrinter::Next(), and sub_tuple_test().
virtual Schema* Schema::duplicateSchema () const pure virtual
Implemented in SchemaFix, and SchemaVar.
Referenced by claims::physical_operator::ResultCollector::CollectResult(), generateBlockStreamBuffer(), claims::physical_operator::PhysicalHashJoin::Open(), ResultSet::ResultSet(), and claims::physical_operator::ExchangeMerger::SerializeAndSendPlan().
const column_type& Schema::getcolumn (const unsigned index) const inline
References columns.
Referenced by bottomLayerCollecting::computeOutputSchema(), bottomLayerSorting::computeVectorSchema(), createEqualJoinExpression(), claims::physical_operator::ExchangeSender::GetHashPartitionId(), LogicalCSBIndexBuilding::GetPhysicalPlan(), SubTuple::getSubTuple(), hasSameSchema(), InitExprAtLogicalPlan(), claims::common::ExprColumn::InitExprAtLogicalPlan(), claims::physical_operator::PhysicalHashJoin::IsMatch(), bottomLayerCollecting::Next(), claims::physical_operator::InOperator::Next(), claims::physical_operator::PhysicalHashJoin::Next(), bottomLayerSorting::Next(), claims::physical_operator::PhysicalAggregation::Open(), claims::physical_operator::InOperator::Open(), claims::physical_operator::PhysicalHashJoin::Open(), bottomLayerSorting::Open(), ResultSet::print(), claims::physical_operator::PhysicalProject::ProcessInLogic(), TupleConvertor::sub_tuple(), and test_decimal_minus().
virtual void* Schema::getColumnAddess (const unsigned & index, const void *const & column_start) const inline pure virtual
Implemented in SchemaFix, and SchemaVar.
Referenced by bottomLayerSorting::compare(), displayTuple(), claims::common::ExprColumn::ExprEvaluate(), generateBlockStreamBuffer(), getcol(), getColumnValue(), claims::physical_operator::ExchangeSender::GetHashPartitionId(), SubTuple::getSubTuple(), bottomLayerSorting::indexBuilding(), claims::physical_operator::PhysicalHashJoin::IsMatch(), bottomLayerCollecting::Next(), claims::physical_operator::CombineTuple::Next(), claims::physical_operator::PhysicalAggregation::Next(), claims::physical_operator::InOperator::Next(), claims::physical_operator::PhysicalHashJoin::Next(), claims::physical_operator::InOperator::Open(), claims::physical_operator::PhysicalAggregation::Open(), claims::physical_operator::PhysicalHashJoin::Open(), ResultSet::print(), claims::physical_operator::PhysicalFilter::ProcessInLogic(), TupleConvertor::sub_tuple(), and TEST_F().
virtual int Schema::getColumnOffset (unsigned index) const pure virtual
Implemented in SchemaFix, and SchemaVar.
Referenced by codegen_column().
virtual void Schema::getColumnValue (unsigned index, void * src, void * desc) pure virtual
Implemented in SchemaFix, and SchemaVar.
Referenced by bottomLayerSorting::Open(), and ClientListener::sendJsonPacket().
std::string Schema::getColumnValue (const void * tuple_start_address, int i) virtual
References columns, and getColumnAddess().
unsigned Schema::getncolumns () const
References columns.
Referenced by BlockStreamVar::BlockStreamVar(), hasSameSchema(), ResultSet::print(), and ClientListener::sendJsonPacket().
virtual schema_type Schema::getSchemaType () const pure virtual
Implemented in SchemaFix, and SchemaVar.
Referenced by BlockStreamBase::createBlock(), BlockStreamBase::createBlockWithDesirableSerilaizedSize(), and hasSameSchema().
virtual Schema* Schema::getSubSchema (std::vector< unsigned >) const pure virtual
Implemented in SchemaFix, and SchemaVar.
Referenced by claims::physical_operator::InOperator::Open(), and sub_tuple_test().
virtual unsigned Schema::getTupleActualSize (void * tuple) const inline pure virtual
Implemented in SchemaVar, and SchemaFix.
Referenced by claims::physical_operator::PhysicalLimit::Next(), claims::physical_operator::ExchangeSenderMaterialized::Next(), claims::physical_operator::ExchangeSenderPipeline::Next(), and claims::physical_operator::PhysicalFilter::ProcessInLogic().
virtual unsigned Schema::getTupleMaxSize () const pure virtual
Implemented in SchemaVar, and SchemaFix.
Referenced by claims::physical_operator::PerformanceMonitor::Close(), BlockStreamBase::createBlock(), BlockStreamBase::createBlockWithDesirableSerilaizedSize(), fill_basic_hash_table(), generate_BlockStreamBuffer(), generateBlockStreamBuffer(), get_one(), getFilterProcessFunc(), initial_input_date(), insert_into_hash_table_from_projection(), HdfsLoader::insertRecords(), bottomLayerCollecting::Next(), claims::physical_operator::CombineTuple::Next(), claims::physical_operator::PhysicalNestLoopJoin::Next(), claims::physical_operator::PhysicalAggregation::Next(), claims::physical_operator::InOperator::Next(), claims::physical_operator::PhysicalSort::Next(), IndexScanIterator::Next(), claims::physical_operator::PhysicalHashJoin::Next(), claims::physical_operator::PhysicalProject::Next(), claims::physical_operator::PhysicalAggregation::Open(), claims::physical_operator::PhysicalHashJoin::Open(), bottomLayerSorting::Open(), claims::physical_operator::PhysicalProject::ProcessInLogic(), claims::physical_operator::PerformanceMonitor::ReportPerformance(), sub_tuple_test(), TEST(), and TEST_F().
bool Schema::hasSameSchema (Schema * schema)
References columns, getcolumn(), getncolumns(), and getSchemaType().
Referenced by TEST().
template<class Archive > void Schema::serialize (Archive & ar, const unsigned int version) inline private
References columns.
virtual void Schema::showAccum_off () inline virtual
Reimplemented in SchemaFix.
virtual void Schema::toValue (std::string text_tuple, void * binary_tuple, const char attr_separator) inline virtual
Reimplemented in SchemaFix.
Referenced by HdfsLoader::insertRecords().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
std::vector<column_type> Schema::columns
Referenced by SchemaFix::addColumn(), BlockStreamVar::BlockStreamVar(), displayTuple(), SchemaVar::duplicateSchema(), SchemaFix::duplicateSchema(), generate_BlockStreamBuffer(), getcolumn(), SchemaFix::getColumnValue(), getColumnValue(), getncolumns(), SchemaFix::getSubSchema(), SchemaVar::getTupleActualSize(), hasSameSchema(), initial_input_date(), insert_into_hash_table(), insert_into_hash_table_from_projection(), claims::physical_operator::CombineTuple::Next(), claims::physical_operator::PhysicalAggregation::Next(), Schema(), serialize(), and SchemaFix::toValue().
The documentation for this class was generated from the following files:
common/Schema/Schema.h
common/Schema/Schema.cpp