Claims: InsertOptimizedHashTable Class Reference
InsertOptimizedHashTable Class Reference
#include <InsertOptimizedHashTable.h>
Classes
struct bucket
class BucketIterator
struct entry
struct meta_data
Public Member Functions
InsertOptimizedHashTable (unsigned nbuckets)
void initialize ()
virtual ~InsertOptimizedHashTable ()
void insertBlock (BlockStreamBase *block)
void insertEntry (unsigned bn, entry &entry)
BucketIterator createBucketIterator (unsigned bn)
Protected Attributes
std::vector< BlockStreamBase * > block_list_
SpineLock block_list_lock_
bucket * buckets_
unsigned nbuckets_
const unsigned long hash_value_mask
Friends
class BucketIterator
Constructor & Destructor Documentation
InsertOptimizedHashTable::InsertOptimizedHashTable (unsigned nbuckets)
InsertOptimizedHashTable::~InsertOptimizedHashTable () virtual
References block_list_, buckets_, InsertOptimizedHashTable::bucket::head, nbuckets_, and InsertOptimizedHashTable::meta_data::next.
Member Function Documentation
BucketIterator InsertOptimizedHashTable::createBucketIterator (unsigned bn) inline
References BucketIterator, and buckets_.
Referenced by fill_insert_optimized_hash_table(), and TEST().
void InsertOptimizedHashTable::initialize ()
References buckets_, and nbuckets_.
Referenced by insert_into_insert_optimized_hash_table(), and TEST().
void InsertOptimizedHashTable::insertBlock (BlockStreamBase * block)
Insert a block stream into the hash table block list. It is the responsibility of hash table for possible space allocation and release. If the block is a reference, a new referenced block will be created. Otherwise, a new block will be allocated with desirable block size and apply deep copy to create a new block.
References SpineLock::acquire(), block_list_, block_list_lock_, BlockStreamBase::createBlockAndDeepCopy(), and SpineLock::release().
Referenced by insert_into_insert_optimized_hash_table(), and TEST().
void InsertOptimizedHashTable::insertEntry (unsigned bn, entry & entry)
References SpineLock::acquire(), InsertOptimizedHashTable::bucket::allocate_new_entry(), buckets_, InsertOptimizedHashTable::bucket::entrys, InsertOptimizedHashTable::bucket::has_space_for_new_entry(), InsertOptimizedHashTable::bucket::head, InsertOptimizedHashTable::meta_data::lock, InsertOptimizedHashTable::meta_data::next, SpineLock::release(), and InsertOptimizedHashTable::meta_data::tuple_count.
Referenced by insert_into_insert_optimized_hash_table(), and TEST().
Friends And Related Function Documentation
friend class BucketIterator friend
Referenced by createBucketIterator().
Member Data Documentation
std::vector<BlockStreamBase*> InsertOptimizedHashTable::block_list_ protected
Referenced by insertBlock(), and ~InsertOptimizedHashTable().
SpineLock InsertOptimizedHashTable::block_list_lock_ protected
Referenced by insertBlock().
bucket* InsertOptimizedHashTable::buckets_ protected
Referenced by createBucketIterator(), initialize(), insertEntry(), and ~InsertOptimizedHashTable().
const unsigned long InsertOptimizedHashTable::hash_value_mask protected
unsigned InsertOptimizedHashTable::nbuckets_ protected
Referenced by initialize(), and ~InsertOptimizedHashTable().
The documentation for this class was generated from the following files:
common/InsertOptimizedHashTable.h
common/InsertOptimizedHashTable.cpp