Claims: BlockStreamBase::BlockStreamTraverseIterator Class Reference
BlockStreamBase::BlockStreamTraverseIterator Class Reference
#include <BlockStream.h>
Public Member Functions
BlockStreamTraverseIterator (BlockStreamBase *block_stream_base)
~BlockStreamTraverseIterator ()
void * nextTuple ()
void * currentTuple () const
void * getTuple (unsigned tuple_off) const
void increase_cur_ ()
void reset ()
unsigned get_cur () const
void set_cur (unsigned c)
Private Attributes
BlockStreamBase * block_stream_base_
unsigned cur
Constructor & Destructor Documentation
BlockStreamBase::BlockStreamTraverseIterator::BlockStreamTraverseIterator (BlockStreamBase * block_stream_base) inline explicit
BlockStreamBase::BlockStreamTraverseIterator::~BlockStreamTraverseIterator () inline
Referenced by claims::physical_operator::PhysicalLimit::Next(), claims::physical_operator::PhysicalNestLoopJoin::Next(), claims::physical_operator::InOperator::Next(), query_2(), and TEST().
Member Function Documentation
void* BlockStreamBase::BlockStreamTraverseIterator::currentTuple () const inline
Referenced by bottomLayerCollecting::Next(), claims::physical_operator::PhysicalLimit::Next(), claims::physical_operator::PhysicalNestLoopJoin::Next(), claims::physical_operator::InOperator::Next(), claims::physical_operator::PhysicalFilter::Next(), claims::physical_operator::PhysicalHashJoin::Next(), claims::physical_operator::PhysicalProject::Next(), claims::physical_operator::PhysicalAggregation::Open(), claims::physical_operator::PhysicalFilter::ProcessInLogic(), claims::physical_operator::PhysicalProject::ProcessInLogic(), TEST_F(), test_multiple_scan_filter_Scalar_Aggregation(), and test_scan_filter_Scalar_Aggregation().
unsigned BlockStreamBase::BlockStreamTraverseIterator::get_cur () const inline
Referenced by claims::physical_operator::PhysicalFilter::ProcessInLogic().
void* BlockStreamBase::BlockStreamTraverseIterator::getTuple (unsigned tuple_off) const inline
Referenced by IndexScanIterator::Next().
void BlockStreamBase::BlockStreamTraverseIterator::increase_cur_ () inline
Referenced by bottomLayerCollecting::Next(), claims::physical_operator::PhysicalLimit::Next(), claims::physical_operator::PhysicalNestLoopJoin::Next(), claims::physical_operator::InOperator::Next(), claims::physical_operator::PhysicalHashJoin::Next(), claims::physical_operator::PhysicalAggregation::Open(), claims::physical_operator::PhysicalFilter::ProcessInLogic(), and claims::physical_operator::PhysicalProject::ProcessInLogic().
void* BlockStreamBase::BlockStreamTraverseIterator::nextTuple () inline
Referenced by Analyzer::analyse(), Analyzer::compute_table_stat(), Analyzer::computeHistogram(), filter_test(), Analyzer::getDistinctCardinality(), insert_into_hash_table(), insert_into_hash_table_from_projection(), insert_into_insert_optimized_hash_table(), mainasfasdf22(), claims::physical_operator::PerformanceMonitor::Next(), claims::physical_operator::ResultPrinter::Next(), claims::physical_operator::ExchangeSenderMaterialized::Next(), claims::physical_operator::ExchangeSenderPipeline::Next(), claims::physical_operator::InOperator::Open(), claims::physical_operator::PhysicalSort::Open(), claims::physical_operator::PhysicalHashJoin::Open(), bottomLayerSorting::Open(), ResultSet::print(), query_2(), ClientListener::sendJsonPacket(), TEST(), and TEST_F().
void BlockStreamBase::BlockStreamTraverseIterator::reset () inline
Referenced by claims::physical_operator::InOperator::Open(), and claims::physical_operator::PhysicalAggregation::Open().
void BlockStreamBase::BlockStreamTraverseIterator::set_cur (unsigned c) inline
Referenced by claims::physical_operator::PhysicalFilter::ProcessInLogic().
Member Data Documentation
BlockStreamBase* BlockStreamBase::BlockStreamTraverseIterator::block_stream_base_ private
unsigned BlockStreamBase::BlockStreamTraverseIterator::cur private
The documentation for this class was generated from the following file:
common/Block/BlockStream.h