Claims: CCSBLeafNode< T > Class Template Reference
CCSBLeafNode< T > Class Template Reference
#include <CSBPlusTree.h>
Public Member Functions
CCSBLeafNode ()
virtual ~CCSBLeafNode ()
bool setUsedKeys (int count)
data_offset< T > getElement (unsigned i)
bool setElement (unsigned i, data_offset< T > data)
CCSBNodeGroup< T > * getPointer ()
bool Insert (data_offset< T > value)
bool Delete (T value)
T SplitInsert (CCSBNode< T > *pNode, data_offset< T > data)
bool Combine (CCSBNode< T > *pNode)
void DeleteChildren ()
bool serialize (FILE *filename)
bool deserialize (FILE *filename)
Public Member Functions inherited from CCSBNode< T >
CCSBNode ()
virtual ~CCSBNode ()
int getUsedKeys ()
CCSBNode< T > * getFather ()
void setFather (CCSBNode< T > *father)
virtual bool setElement (unsigned i, T value)
virtual void setPointer (CCSBNodeGroup< T > *pointer)
virtual bool Insert (T key)
virtual T SplitInsert (CCSBNode< T > *pNode, T key)
Public Attributes
data_offset< T > * node_datas
Public Attributes inherited from CCSBNode< T >
int used_keys
CCSBNode< T > * p_father
Additional Inherited Members
Static Public Member Functions inherited from CCSBNode< T >
static unsigned getMaxKeys ()
static unsigned getMaxDatas ()
Constructor & Destructor Documentation
template<typename T > CCSBLeafNode< T >::CCSBLeafNode ()
References data_offset< T >::_block_off, data_offset< T >::_key, data_offset< T >::_tuple_off, and INVALID.
template<typename T > CCSBLeafNode< T >::~CCSBLeafNode () virtual
Member Function Documentation
template<typename T > bool CCSBLeafNode< T >::Combine (CCSBNode< T > * pNode) virtual
Reimplemented from CCSBNode< T >.
template<typename T > bool CCSBLeafNode< T >::Delete (T value) virtual
Reimplemented from CCSBNode< T >.
template<typename T > void CCSBLeafNode< T >::DeleteChildren () virtual
Reimplemented from CCSBNode< T >.
template<typename T > bool CCSBLeafNode< T >::deserialize (FILE * filename) virtual
Reimplemented from CCSBNode< T >.
Referenced by CCSBLeafNodeGroup< T >::deserialize().
template<typename T > data_offset<T> CCSBLeafNode< T >::getElement (unsigned i) inline virtual
Reimplemented from CCSBNode< T >.
References NULL.
template<typename T > CCSBNodeGroup<T>* CCSBLeafNode< T >::getPointer () inline virtual
Reimplemented from CCSBNode< T >.
References NULL.
template<typename T > bool CCSBLeafNode< T >::Insert (data_offset< T > value) virtual
Reimplemented from CCSBNode< T >.
References data_offset< T >::_key.
template<typename T > bool CCSBLeafNode< T >::serialize (FILE * filename) virtual
Reimplemented from CCSBNode< T >.
template<typename T > bool CCSBLeafNode< T >::setElement (unsigned i, data_offset< T > data) inline virtual
Reimplemented from CCSBNode< T >.
References data_offset< T >::_block_off, data_offset< T >::_key, and data_offset< T >::_tuple_off.
template<typename T > bool CCSBLeafNode< T >::setUsedKeys (int count) inline virtual
Reimplemented from CCSBNode< T >.
template<typename T > T CCSBLeafNode< T >::SplitInsert (CCSBNode< T > * pNode, data_offset< T > data) virtual
Reimplemented from CCSBNode< T >.
References data_offset< T >::_key, CCSBNode< T >::getElement(), CCSBNode< T >::Insert(), INVALID, CCSBNode< T >::setElement(), and CCSBNode< T >::setUsedKeys().
Member Data Documentation
template<typename T > data_offset<T>* CCSBLeafNode< T >::node_datas
The documentation for this class was generated from the following files:
IndexManager/CSBPlusTree.h
IndexManager/CSBPlusTree.cpp