Claims: Logging Class Reference
Logging Class Reference abstract
#include <Logging.h>
Public Member Functions
virtual void log (const char *format,...)=0
virtual void elog (const char *format,...)=0
virtual ~Logging ()
Constructor & Destructor Documentation
virtual Logging::~Logging () inline virtual
Member Function Documentation
virtual void Logging::elog (const char * format, ...) pure virtual
print the error information to stderr.
Implemented in PerformanceTopLogging, BlockStreamExpanderLogging, BufferManagerLogging, StorageManagerMasterLogging, StorageManagerLogging, ResourceManagerSlaveLogging, ResourceManagerMasterLogging, CatalogLogging, ExchangeIteratorSenderMaterialized, ExchangeIteratorEagerLowerLogging, ExchangeIteratorEagerLogging, ExpanderTrackerLogging, ExchangeTrackerLogging, CoordinatorLogging, AdaptiveEndPointLogging, EnvironmentLogging, IteratorExecutorSlaveLogging, and IteratorExecutorMasterLogging.
Referenced by AdaptiveEndPoint::AdaptiveEndPoint(), Catalog::add_table(), AdaptiveEndPoint::ConnectToCoordinateEndPoint(), Coordinator::Coordinator(), Environment::Environment(), IteratorExecutorMaster::ExecuteBlockStreamIteratorsOnSites(), AdaptiveEndPoint::GetCoordinatorEndPointPort(), Environment::initializeEndPoint(), Coordinator::ListeningNewNode(), BlockManager::loadFromDisk(), BlockManager::loadFromHdfs(), Coordinator::PrepareTheSocket(), InstanceResourceManager::Register(), ResourceManagerMaster::RegisterNewSlave(), BlockManager::removePartition(), Catalog::restoreCatalog(), AdaptiveEndPoint::SayHelloToCoordinator(), BlockManagerMaster::SendBindingMessage(), Coordinator::SendCoordinatorEndPointPort(), BlockManagerMaster::SendUnbindingMessage(), and AdaptiveEndPoint::WaitForReadySignalFromCoordinator().
virtual void Logging::log (const char * format, ...) pure virtual
Implemented in PerformanceTopLogging, BlockStreamExpanderLogging, BufferManagerLogging, StorageManagerMasterLogging, StorageManagerLogging, ResourceManagerSlaveLogging, ResourceManagerMasterLogging, CatalogLogging, ExchangeIteratorSenderMaterialized, ExchangeIteratorEagerLowerLogging, ExchangeIteratorEagerLogging, ExpanderTrackerLogging, ExchangeTrackerLogging, CoordinatorLogging, AdaptiveEndPointLogging, EnvironmentLogging, IteratorExecutorSlaveLogging, and IteratorExecutorMasterLogging.
Referenced by AdaptiveEndPoint::AdaptiveEndPoint(), Catalog::add_table(), BlockManager::addPartition(), BufferManager::applyStorageDedget(), BufferManager::BufferManager(), AdaptiveEndPoint::ConnectToCoordinateEndPoint(), Coordinator::CreateListeningThread(), IteratorExecutorSlave::createNewThreadAndRun(), ExpanderTracker::decideExpandingOrShrinking(), Environment::Environment(), ExchangeTracker::ExchangeTracker(), IteratorExecutorMaster::ExecuteBlockStreamIteratorsOnSite(), IteratorExecutorMaster::ExecuteBlockStreamIteratorsOnSites(), ExpanderTracker::ExpanderTracker(), AdaptiveEndPoint::GetCoordinatorEndPointPort(), Environment::initializeEndPoint(), IteratorExecutorSlave::IteratorExecutorSlave(), Coordinator::ListeningNewNode(), BlockManager::loadFromDisk(), BlockManager::loadFromHdfs(), ExchangeTracker::LogoutExchange(), ExpanderTracker::monitoringThread(), Coordinator::PrepareTheSocket(), InstanceResourceManager::Register(), ResourceManagerMaster::RegisterDiskBuget(), ExchangeTracker::RegisterExchange(), ResourceManagerMaster::RegisterMemoryBuget(), ExpanderTracker::registerNewExpander(), ResourceManagerMaster::RegisterNewSlave(), IteratorExecutorSlave::run_iterator(), BlockManagerMaster::SendBindingMessage(), Coordinator::SendCoordinatorEndPointPort(), Coordinator::SendReadyNotificationToNewNode(), BlockManagerMaster::SendUnbindingMessage(), Coordinator::SetupTheTheron(), and AdaptiveEndPoint::WaitForReadySignalFromCoordinator().
The documentation for this class was generated from the following file:
common/Logging.h