Claims: IndexScanIterator Class Reference
IndexScanIterator Class Reference
#include <IndexScanIterator.h>
Classes
struct query_range
struct remaining_block
class State
Public Member Functions
IndexScanIterator ()
IndexScanIterator (State state)
virtual ~IndexScanIterator ()
bool Open (const PartitionOffset &partition_off=0)
bool Next (BlockStreamBase *block)
bool Close ()
void Print ()
Public Member Functions inherited from claims::physical_operator::PhysicalOperator
PhysicalOperator (unsigned number_of_barrier=1, unsigned number_of_seriliazed_section=1)
virtual ~PhysicalOperator ()
virtual ThreadContext * CreateContext ()
Public Member Functions inherited from claims::physical_operator::PhysicalOperatorBase
PhysicalOperatorBase ()
virtual ~PhysicalOperatorBase ()
virtual ResultSet * GetResultSet ()
Private Member Functions
void atomicPushRemainingBlock (remaining_block rb)
bool atomicPopRemainingBlock (remaining_block &rb)
void AtomicPushBlockStream (BlockStreamBase *block)
BlockStreamBase * AtomicPopBlockStream ()
bool askForNextBlock (remaining_block &rb)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
State state_
PartitionStorage::PartitionReaderItetaor * partition_reader_iterator_
ChunkReaderIterator * chunk_reader_iterator_
std::map< ChunkID, void * > csb_index_list_
std::list< remaining_block > remaining_block_list_
std::list< BlockStreamBase * > block_stream_list_
Lock lock_
Friends
class boost::serialization::access
Additional Inherited Members
Public Types inherited from claims::physical_operator::PhysicalOperator
enum context_reuse_mode { crm_no_reuse, crm_core_sensitive, crm_numa_sensitive, crm_anyway }
Static Public Member Functions inherited from claims::physical_operator::PhysicalOperatorBase
static PhysicalOperatorBase * createIterator (const string &IteratorName)
Protected Member Functions inherited from claims::physical_operator::PhysicalOperator
ThreadContext * CreateOrReuseContext (context_reuse_mode crm)
void InitExpandedStatus ()
bool TryEntryIntoSerializedSection (unsigned serialized_section_id=0)
void RegisterExpandedThreadToAllBarriers ()
void UnregisterExpandedThreadToAllBarriers (unsigned barrier_index=0)
void BarrierArrive (unsigned barrier_index=0)
void InitContext (ThreadContext *tc)
ThreadContext * GetContext ()
void DestoryAllContext ()
bool CheckTerminateRequest ()
void SetReturnStatus (bool ret)
bool GetReturnStatus () const
Protected Attributes inherited from claims::physical_operator::PhysicalOperator
unsigned number_of_registered_expanded_threads_
Constructor & Destructor Documentation
IndexScanIterator::IndexScanIterator ()
References claims::physical_operator::PhysicalOperator::InitExpandedStatus().
IndexScanIterator::IndexScanIterator (State state)
References csb_index_list_, and claims::physical_operator::PhysicalOperator::InitExpandedStatus().
IndexScanIterator::~IndexScanIterator () virtual
Member Function Documentation
bool IndexScanIterator::askForNextBlock (remaining_block & rb) private
for testing/ unsigned long count = 0;
for testing/ cout << "Total count: " << count << endl;
References IndexScanIterator::remaining_block::block, IndexScanIterator::remaining_block::block_off, chunk_reader_iterator_, csb_index_list_, IndexManager::getIndexType(), IndexManager::getInstance(), IndexScanIterator::State::index_id_, IndexScanIterator::remaining_block::iter_result_map, IndexScanIterator::remaining_block::iter_result_vector, ChunkReaderIterator::nextBlock(), PartitionStorage::PartitionReaderItetaor::nextChunk(), partition_reader_iterator_, IndexScanIterator::State::query_range_, IndexScanIterator::remaining_block::result_set, state_, t_boolean, t_date, t_datetime, t_decimal, t_double, t_float, t_int, t_smallInt, t_string, t_time, t_u_long, and t_u_smallInt.
Referenced by Next().
BlockStreamBase * IndexScanIterator::AtomicPopBlockStream () private
References Lock::acquire(), block_stream_list_, lock_, and Lock::release().
Referenced by Next().
bool IndexScanIterator::atomicPopRemainingBlock (remaining_block & rb) private
References Lock::acquire(), lock_, Lock::release(), and remaining_block_list_.
Referenced by Next().
void IndexScanIterator::AtomicPushBlockStream (BlockStreamBase * block) private
References Lock::acquire(), block_stream_list_, lock_, and Lock::release().
Referenced by Next(), and Open().
void IndexScanIterator::atomicPushRemainingBlock (remaining_block rb) private
References Lock::acquire(), lock_, Lock::release(), and remaining_block_list_.
Referenced by Next().
bool IndexScanIterator::Close () virtual
Reimplemented from claims::physical_operator::PhysicalOperator.
References block_stream_list_, claims::physical_operator::PhysicalOperator::InitExpandedStatus(), partition_reader_iterator_, and remaining_block_list_.
bool IndexScanIterator::Next (BlockStreamBase * block) virtual
Reimplemented from claims::physical_operator::PhysicalOperator.
References BlockStreamBase::allocateTuple(), askForNextBlock(), AtomicPopBlockStream(), atomicPopRemainingBlock(), AtomicPushBlockStream(), atomicPushRemainingBlock(), IndexScanIterator::remaining_block::block, IndexScanIterator::remaining_block::block_off, Schema::copyTuple(), BlockStreamBase::createIterator(), BlockStreamBase::Empty(), BlockStreamBase::BlockStreamTraverseIterator::getTuple(), Schema::getTupleMaxSize(), IndexScanIterator::remaining_block::iter_result_map, IndexScanIterator::remaining_block::iter_result_vector, IndexScanIterator::remaining_block::iterator, IndexScanIterator::remaining_block::result_set, IndexScanIterator::State::schema_, BlockStreamBase::setEmpty(), and state_.
bool IndexScanIterator::Open (const PartitionOffset & part_off = 0) virtual
Because that boost::serialization will allocate an instance of this class when deserializing, and hence the following three virtual method cannot be pure.
Reimplemented from claims::physical_operator::PhysicalOperator.
References AtomicPushBlockStream(), claims::physical_operator::PhysicalOperator::BarrierArrive(), IndexScanIterator::State::block_size_, PartitionStorage::createAtomicReaderIterator(), BlockStreamBase::createBlockWithDesirableSerilaizedSize(), csb_index_list_, IndexManager::getAttrIndex(), IndexManager::getInstance(), BlockManager::getInstance(), PartitionID::getName(), claims::physical_operator::PhysicalOperator::GetReturnStatus(), IndexScanIterator::State::index_id_, partition_reader_iterator_, IndexScanIterator::State::projection_id_, IndexScanIterator::State::schema_, claims::physical_operator::PhysicalOperator::SetReturnStatus(), state_, and claims::physical_operator::PhysicalOperator::TryEntryIntoSerializedSection().
void IndexScanIterator::Print () inline virtual
Reimplemented from claims::physical_operator::PhysicalOperator.
template<class Archive > void IndexScanIterator::serialize (Archive & ar, const unsigned int version) inline private
References state_.
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
std::list<BlockStreamBase*> IndexScanIterator::block_stream_list_ private
Referenced by AtomicPopBlockStream(), AtomicPushBlockStream(), and Close().
ChunkReaderIterator* IndexScanIterator::chunk_reader_iterator_ private
Referenced by askForNextBlock().
std::map<ChunkID, void*> IndexScanIterator::csb_index_list_ private
Referenced by askForNextBlock(), IndexScanIterator(), and Open().
Lock IndexScanIterator::lock_ private
Referenced by AtomicPopBlockStream(), atomicPopRemainingBlock(), AtomicPushBlockStream(), and atomicPushRemainingBlock().
PartitionStorage::PartitionReaderItetaor* IndexScanIterator::partition_reader_iterator_ private
Referenced by askForNextBlock(), Close(), and Open().
std::list<remaining_block> IndexScanIterator::remaining_block_list_ private
Referenced by atomicPopRemainingBlock(), atomicPushRemainingBlock(), and Close().
State IndexScanIterator::state_ private
Referenced by askForNextBlock(), Next(), Open(), and serialize().
The documentation for this class was generated from the following files:
IndexManager/IndexScanIterator.h
IndexManager/IndexScanIterator.cpp