Claims: BoostHashFunctin Class Reference
BoostHashFunctin Class Reference
#include <hash.h>
Public Member Functions
BoostHashFunctin ()
BoostHashFunctin (const int &range)
~BoostHashFunctin ()
unsigned int get_partition_value (const int &value) const
unsigned int get_partition_value (const unsigned long &value) const
unsigned int get_partition_value (const double &value) const
unsigned int get_partition_value (const long &value) const
PartitionStyle getPartitionFashion () const
unsigned getNumberOfPartitions () const
Public Member Functions inherited from PartitionFunction
PartitionFunction ()
PartitionFunction (int min, int max, unsigned int k)
virtual ~PartitionFunction ()
bool equal (PartitionFunction *function_) const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
unsigned long range_
Friends
class boost::serialization::access
Additional Inherited Members
Public Types inherited from PartitionFunction
enum PartitionStyle { hash_f, range_f, round_robin_f }
Protected Member Functions inherited from PartitionFunction
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Protected Attributes inherited from PartitionFunction
int min_
int max_
unsigned long int k_
Constructor & Destructor Documentation
BoostHashFunctin::BoostHashFunctin () inline
BoostHashFunctin::BoostHashFunctin (const int & range) inline
BoostHashFunctin::~BoostHashFunctin () inline
Member Function Documentation
unsigned int BoostHashFunctin::get_partition_value (const int & value) const inline virtual
Returns the bucket number for this value.
Parameters
value Value to hash. Must be within bounds.
Returns
Bucket number.
Implements PartitionFunction.
References hash_value(), and range_.
unsigned int BoostHashFunctin::get_partition_value (const unsigned long & value) const inline virtual
Implements PartitionFunction.
References hash_value(), and range_.
unsigned int BoostHashFunctin::get_partition_value (const double & value) const inline virtual
Implements PartitionFunction.
References hash_value(), and range_.
unsigned int BoostHashFunctin::get_partition_value (const long & value) const inline
References hash_value(), and range_.
unsigned BoostHashFunctin::getNumberOfPartitions () const inline virtual
Implements PartitionFunction.
References range_.
PartitionStyle BoostHashFunctin::getPartitionFashion () const inline virtual
Implements PartitionFunction.
References PartitionFunction::hash_f.
template<class Archive > void BoostHashFunctin::serialize (Archive & ar, const unsigned int version) inline private
References range_.
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
unsigned long BoostHashFunctin::range_ private
Referenced by get_partition_value(), getNumberOfPartitions(), and serialize().
The documentation for this class was generated from the following file:
common/hash.h