Claims: StreamBuffer Class Reference
StreamBuffer Class Reference
#include <StreamBuffer.h>
Public Member Functions
StreamBuffer ()
StreamBuffer (unsigned length=10000)
~StreamBuffer ()
void Reorganize ()
void MoveForwardEnd (unsigned count)
char * GetCurrent () const
unsigned GetFreedBufferCount () const
void Clear ()
bool IsEmpty ()
Private Attributes
char * buffer_ = NULL
unsigned int cur_ = 0
unsigned int end_ = 0
unsigned int length_ = 0
Static Private Attributes
static StreamBuffer * instance_
Constructor & Destructor Documentation
StreamBuffer::StreamBuffer ()
StreamBuffer::StreamBuffer (unsigned length = 10000) inline
StreamBuffer::~StreamBuffer () inline
Member Function Documentation
void StreamBuffer::Clear () inline
char* StreamBuffer::GetCurrent () const inline
Referenced by GetInputSQL().
unsigned StreamBuffer::GetFreedBufferCount () const inline
Referenced by GetInputSQL().
bool StreamBuffer::IsEmpty () inline
Referenced by GetInputSQL().
void StreamBuffer::MoveForwardEnd (unsigned count)
References cur_, ASTParserLogging::elog(), end_, length_, and Reorganize().
Referenced by GetInputSQL().
void StreamBuffer::Reorganize ()
Referenced by MoveForwardEnd().
Member Data Documentation
char* StreamBuffer::buffer_ = NULL private
unsigned int StreamBuffer::cur_ = 0 private
Referenced by MoveForwardEnd().
unsigned int StreamBuffer::end_ = 0 private
Referenced by MoveForwardEnd().
StreamBuffer* StreamBuffer::instance_ static private
unsigned int StreamBuffer::length_ = 0 private
Referenced by MoveForwardEnd().
The documentation for this class was generated from the following files:
Parsetree/StreamBuffer.h
Parsetree/StreamBuffer.cpp