Claims: BasicHashTable Class Reference
BasicHashTable Class Reference
#include <hashtable.h>
Classes
class Iterator
Public Member Functions
BasicHashTable (unsigned nbuckets, unsigned bucksize, unsigned tuplesize, unsigned expected_number_of_visiting_thread=1)
~BasicHashTable ()
void * allocate (const unsigned &offset, unsigned thread_id=0)
void * atomicAllocate (const unsigned &offset, unsigned thread_id=0)
void UpdateTuple (unsigned int offset, void *loc, void *newvalue, fun func)
void atomicUpdateTuple (unsigned int offset, void *loc, void *newvalue, fun func)
void lockBlock (unsigned &bn)
void unlockBlock (unsigned &bn)
void report_status ()
BasicHashTable::Iterator CreateIterator () const
bool placeIterator (Iterator &it, const unsigned &offset)
unsigned getHashTableTupleSize ()
Static Public Member Functions
static unsigned getNumberOfInstances ()
Private Attributes
int nbuckets_
int bucksize_
int buck_actual_size_
int tuplesize_
void ** bucket_
int pagesize_
char * t_start_
int cur_MP_
std::vector< char * > mother_page_list_
SpineLock * lock_list_
unsigned * overflow_count_
unsigned long allocate_count
std::set< void * > allocated_buckets
SpineLock mother_page_lock_
pool * grandmother
Static Private Attributes
static unsigned number_of_instances_ =0
Constructor & Destructor Documentation
BasicHashTable::BasicHashTable (unsigned nbuckets, unsigned bucksize, unsigned tuplesize, unsigned expected_number_of_visiting_thread = 1)
create spinlocks, each of which corresponds to a single bucket
References allocate_count, buck_actual_size_, bucket_, bucksize_, cur_MP_, get_aligned_space(), grandmother, lock_list_, MAX, mother_page_list_, number_of_instances_, overflow_count_, PAGE_SIZE, pagesize_, and t_start_.
BasicHashTable::~BasicHashTable ()
References bucket_, grandmother, lock_list_, mother_page_list_, number_of_instances_, and overflow_count_.
Referenced by claims::physical_operator::InOperator::Close(), init_alloc_destory(), and init_and_destory().
Member Function Documentation
void * BasicHashTable::allocate (const unsigned & offset, unsigned thread_id = 0)
References SpineLock::acquire(), buck_actual_size_, bucket_, bucksize_, cur_MP_, grandmother, mother_page_list_, mother_page_lock_, overflow_count_, PAGE_SIZE, pagesize_, SpineLock::release(), and tuplesize_.
Referenced by init_insert_and_destroy(), and claims::physical_operator::PhysicalAggregation::Open().
void* BasicHashTable::atomicAllocate (const unsigned & offset, unsigned thread_id = 0) inline
References allocate.
Referenced by claims::physical_operator::InOperator::Open(), claims::physical_operator::PhysicalHashJoin::Open(), and performance_test().
void BasicHashTable::atomicUpdateTuple (unsigned int offset, void * loc, void * newvalue, fun func) inline
BasicHashTable::Iterator BasicHashTable::CreateIterator () const
References buck_actual_size_, and tuplesize_.
Referenced by claims::physical_operator::InOperator::Next(), claims::physical_operator::PhysicalHashJoin::Next(), claims::physical_operator::PhysicalAggregation::Open(), claims::physical_operator::PhysicalHashJoin::Open(), and report_status().
unsigned BasicHashTable::getHashTableTupleSize () inline
References tuplesize_.
unsigned BasicHashTable::getNumberOfInstances () static
References number_of_instances_.
void BasicHashTable::lockBlock (unsigned & bn) inline
Referenced by claims::physical_operator::PhysicalAggregation::Open().
bool BasicHashTable::placeIterator (Iterator & it, const unsigned & offset) inline
References buck_actual_size_, bucket_, BasicHashTable::Iterator::cur, BasicHashTable::Iterator::free, nbuckets_, and BasicHashTable::Iterator::next.
Referenced by claims::physical_operator::PhysicalAggregation::Next(), claims::physical_operator::InOperator::Next(), claims::physical_operator::PhysicalHashJoin::Next(), claims::physical_operator::PhysicalAggregation::Open(), and report_status().
void BasicHashTable::report_status ()
References bucksize_, CreateIterator(), nbuckets_, overflow_count_, placeIterator(), BasicHashTable::Iterator::readnext(), and tuplesize_.
void BasicHashTable::unlockBlock (unsigned & bn) inline
Referenced by claims::physical_operator::PhysicalAggregation::Open().
void BasicHashTable::UpdateTuple (unsigned int offset, void * loc, void * newvalue, fun func) inline
Member Data Documentation
unsigned long BasicHashTable::allocate_count private
Referenced by BasicHashTable().
std::set<void*> BasicHashTable::allocated_buckets private
int BasicHashTable::buck_actual_size_ private
Referenced by allocate(), BasicHashTable(), CreateIterator(), and placeIterator().
void** BasicHashTable::bucket_ private
Referenced by allocate(), BasicHashTable(), placeIterator(), and ~BasicHashTable().
int BasicHashTable::bucksize_ private
Referenced by allocate(), BasicHashTable(), and report_status().
int BasicHashTable::cur_MP_ private
Referenced by allocate(), and BasicHashTable().
pool* BasicHashTable::grandmother private
Referenced by allocate(), BasicHashTable(), and ~BasicHashTable().
SpineLock* BasicHashTable::lock_list_ private
Referenced by BasicHashTable(), and ~BasicHashTable().
std::vector<char*> BasicHashTable::mother_page_list_ private
Referenced by allocate(), BasicHashTable(), and ~BasicHashTable().
SpineLock BasicHashTable::mother_page_lock_ private
Referenced by allocate().
int BasicHashTable::nbuckets_ private
Referenced by placeIterator(), and report_status().
unsigned BasicHashTable::number_of_instances_ =0 static private
Referenced by BasicHashTable(), getNumberOfInstances(), and ~BasicHashTable().
unsigned* BasicHashTable::overflow_count_ private
Referenced by allocate(), BasicHashTable(), report_status(), and ~BasicHashTable().
int BasicHashTable::pagesize_ private
Referenced by allocate(), and BasicHashTable().
char* BasicHashTable::t_start_ private
Referenced by BasicHashTable().
int BasicHashTable::tuplesize_ private
Referenced by allocate(), CreateIterator(), getHashTableTupleSize(), and report_status().
The documentation for this class was generated from the following files:
common/hashtable.h
common/hashtable.cpp