My Project: claims::logical_operator::LogicalQueryPlanRoot Class Reference
claims::logical_operator::LogicalQueryPlanRoot Class Reference
Public Types
enum OutputStyle { kPrint, kPerformance, kResultCollector }
Public Member Functions
LogicalQueryPlanRoot (NodeID collecter_node_id, LogicalOperator *child, const OutputStyle &fashion=kPerformance, LimitConstraint limit_constraint=LimitConstraint())
Method description:
PlanContext GetPlanContext ()
BlockStreamIteratorBase * GetPhysicalPlan (const unsigned &)
Method description: generate a few physical operators according to this logical operator.
bool GetOptimalPhysicalPlan (Requirement requirement, PhysicalPlanDescriptor &physical_plan_descriptor, const unsigned &block_size=4096 *1024)
Method description: NOT USED NOW !!! get the optimal physical plan.
void Print (int level=0) const
Method description: print the limit info and call child to print their logical operator info.
Additional Inherited Members
Protected Member Functions inherited from claims::logical_operator::LogicalOperator
Schema * GetSchema (const std::vector< Attribute > &) const
Schema * GetSchema (const std::vector< Attribute > &, const std::vector< Attribute > &) const
std::vector< NodeID > GetInvolvedNodeID (const PlanPartitioner &) const
std::vector< NodeIP > ConvertNodeIDListToNodeIPList (const std::vector< NodeID > &) const
PhysicalPlanDescriptor GetBestPhysicalPlanDescriptor (const std::vector< PhysicalPlanDescriptor >) const
int GetIdInAttributeList (const std::vector< Attribute > &attributes, const Attribute &attribute) const
void set_operator_type (OperatorType operator_type)
Member Enumeration Documentation
enum claims::logical_operator::LogicalQueryPlanRoot::OutputStyle
three styles decide which one the top physical operator is: 1) BlockStreamPrint: print result on console directly 2) BlockStreamPerformanceMonitorTop: calculate the real-time performance and print 3) BlockStreamResultCollector : collect result and store it in block buffer, then return to client
Constructor & Destructor Documentation
claims::logical_operator::LogicalQueryPlanRoot::LogicalQueryPlanRoot (NodeID collecter_node_id, LogicalOperator * child, const OutputStyle & fashion = kPerformance, LimitConstraint limit_constraint = LimitConstraint())
Method description:
Parameters
collecter_node_id : specify the id of node that return result to client, which is called master
child : the child logical operator of this operator
fashion : decide the top physical operator (BlockStreamPrint,BlockStreamPerformanceMonitorTop,BlockStreamResultCollector) generated from this logical operator limit_constraint : apply the necessary info about limit, default value is no limit
Member Function Documentation
bool claims::logical_operator::LogicalQueryPlanRoot::GetOptimalPhysicalPlan (Requirement requirement, PhysicalPlanDescriptor & physical_plan_descriptor, const unsigned & block_size = 4096 * 1024) virtual
Method description: NOT USED NOW !!! get the optimal physical plan.
no requirement
with requirement
Reimplemented from claims::logical_operator::LogicalOperator.
References claims::logical_operator::PlanContext::GetAggregatedDatasize(), claims::logical_operator::LogicalOperator::GetOptimalPhysicalPlan(), claims::logical_operator::Requirement::requireNetworkTransfer(), and claims::logical_operator::Requirement::tryMerge().
BlockStreamIteratorBase * claims::logical_operator::LogicalQueryPlanRoot::GetPhysicalPlan (const unsigned & block_size) virtual
Method description: generate a few physical operators according to this logical operator.
Parameters
block_size : give the size of block in physical plan
Returns
the total physical plan include the physical plan generated by child operator
get PlanContext and child physical plan from child , consider PlanContext's partitioner's location and collector, decide whether add expander and exchange operator in physical plan.
choose one of three top physical operators depend on fashion_, return complete physical plan
If the number of partitions in the child PlanContext is 1 and the the location is right in the collector, then exchange is not necessary.
Implements claims::logical_operator::LogicalOperator.
References claims::logical_operator::LogicalOperator::GetPhysicalPlan(), GetPlanContext(), and Config::initial_degree_of_parallelism.
PlanContext claims::logical_operator::LogicalQueryPlanRoot::GetPlanContext () virtual
get PlanContext from child and return
Implements claims::logical_operator::LogicalOperator.
References claims::logical_operator::LogicalOperator::GetPlanContext().
Referenced by GetPhysicalPlan().
void claims::logical_operator::LogicalQueryPlanRoot::Print (int level = 0) const virtual
Method description: print the limit info and call child to print their logical operator info.
Parameters
level : specify the level of this operator, the top level is 0. so this class's level is always 0. level means level*8 space indentation at the begin of line
Returns
void
Implements claims::logical_operator::LogicalOperator.
The documentation for this class was generated from the following files:
logical_operator/logical_query_plan_root.h
logical_operator/logical_query_plan_root.cpp