Claims: MemoryChunkStore Class Reference
MemoryChunkStore Class Reference
#include <MemoryStore.h>
Public Member Functions
MemoryChunkStore ()
virtual ~MemoryChunkStore ()
bool putValue (string chunkId, void *value)
bool applyChunk (ChunkID chunk_id, void *&start_address)
void returnChunk (const ChunkID &chunk_id)
bool updateChunkInfo (const ChunkID &chunk_id, const HdfsInMemoryChunk &chunk_info)
void * getChunk (string blockId)
bool getChunk (const ChunkID &chunk_id, HdfsInMemoryChunk &chunk_info)
bool putChunk (const ChunkID &chunk_id, HdfsInMemoryChunk &chunk_info)
bool remove (string blockId)
bool contains (string blockId)
unsigned getSize (string blockId)
bool tryToPut (string chunkId, void *value)
bool ensureFreeSpace ()
vector< string > getFileLocation (string partition_file_name)
Static Public Member Functions
static MemoryChunkStore * getInstance ()
Private Attributes
map< string, HdfsBlock > bufferpool_
boost::unordered_map< ChunkID,
HdfsInMemoryChunk > chunk_list_
long maxMemory_
long currentMemory_
Lock lock_
pool chunk_pool_
pool block_pool_
Static Private Attributes
static MemoryChunkStore * instance_ =0
Constructor & Destructor Documentation
MemoryChunkStore::MemoryChunkStore ()
Referenced by getInstance().
MemoryChunkStore::~MemoryChunkStore () virtual
References block_pool_, and chunk_pool_.
Member Function Documentation
bool MemoryChunkStore::applyChunk (ChunkID chunk_id, void *& start_address)
References Lock::acquire(), chunk_list_, ChunkID::chunk_off, chunk_pool_, CHUNK_SIZE, BufferManager::getInstance(), lock_, and Lock::release().
bool MemoryChunkStore::contains (string blockId) inline
bool MemoryChunkStore::ensureFreeSpace () inline
void* MemoryChunkStore::getChunk (string blockId) inline
Referenced by BlockManager::getLocal().
bool MemoryChunkStore::getChunk (const ChunkID & chunk_id, HdfsInMemoryChunk & chunk_info)
References Lock::acquire(), chunk_list_, lock_, and Lock::release().
vector<string> MemoryChunkStore::getFileLocation (string partition_file_name) inline
MemoryChunkStore * MemoryChunkStore::getInstance () static
References instance_, and MemoryChunkStore().
Referenced by BlockManager::BlockManager(), BufferManager::BufferManager(), BlockManager::initialize(), PartitionStorage::removeAllChunks(), and PartitionStorage::updateChunksWithInsertOrAppend().
unsigned MemoryChunkStore::getSize (string blockId) inline
bool MemoryChunkStore::putChunk (const ChunkID & chunk_id, HdfsInMemoryChunk & chunk_info)
References Lock::acquire(), chunk_list_, lock_, and Lock::release().
bool MemoryChunkStore::putValue (string chunkId, void * value) inline
Referenced by BlockManager::put().
bool MemoryChunkStore::remove (string blockId) inline
void MemoryChunkStore::returnChunk (const ChunkID & chunk_id)
References Lock::acquire(), chunk_list_, chunk_pool_, BufferManager::getInstance(), HdfsBlock::hook, HdfsBlock::length, lock_, Lock::release(), and BufferManager::returnStorageBudget().
Referenced by ChunkStorage::createChunkReaderIterator(), PartitionStorage::removeAllChunks(), and PartitionStorage::updateChunksWithInsertOrAppend().
bool MemoryChunkStore::tryToPut (string chunkId, void * value) inline
References CHUNK_SIZE, HdfsBlock::hook, and HdfsBlock::length.
bool MemoryChunkStore::updateChunkInfo (const ChunkID & chunk_id, const HdfsInMemoryChunk & chunk_info)
References Lock::acquire(), chunk_list_, lock_, and Lock::release().
Referenced by ChunkStorage::createChunkReaderIterator().
Member Data Documentation
pool MemoryChunkStore::block_pool_ private
Referenced by ~MemoryChunkStore().
map<string, HdfsBlock> MemoryChunkStore::bufferpool_ private
boost::unordered_map<ChunkID,HdfsInMemoryChunk> MemoryChunkStore::chunk_list_ private
Referenced by applyChunk(), getChunk(), putChunk(), returnChunk(), and updateChunkInfo().
pool MemoryChunkStore::chunk_pool_ private
Referenced by applyChunk(), returnChunk(), and ~MemoryChunkStore().
long MemoryChunkStore::currentMemory_ private
MemoryChunkStore * MemoryChunkStore::instance_ =0 static private
Referenced by getInstance().
Lock MemoryChunkStore::lock_ private
Referenced by applyChunk(), getChunk(), putChunk(), returnChunk(), and updateChunkInfo().
long MemoryChunkStore::maxMemory_ private
The documentation for this class was generated from the following files:
storage/MemoryStore.h
storage/MemoryStore.cpp