Claims: ResourceManagerMaster Class Reference
ResourceManagerMaster Class Reference
#include <ResourceManagerMaster.h>
Classes
class ResourceManagerMasterActor
Public Member Functions
ResourceManagerMaster ()
virtual ~ResourceManagerMaster ()
NodeID RegisterNewSlave (NodeAddress)
bool RegisterDiskBuget (NodeID report_node_id, unsigned size_in_mb)
bool RegisterMemoryBuget (NodeID report_node_id, unsigned size_in_mb)
std::vector< NodeID > getSlaveIDList ()
bool ApplyDiskBuget (NodeID target, unsigned size_in_mb)
bool ReturnDiskBuget (NodeID target, unsigned size_in_mb)
bool ApplyMemoryBuget (NodeID target, unsigned size_in_mb)
bool ReturnMemoryBuget (NodeID target, unsigned size_in_mb)
Private Attributes
boost::unordered_map< NodeID,
InstanceResourceInfo * > node_to_resourceinfo_
NodeTracker * node_tracker_
Logging * logging_
Theron::EndPoint * endpoint_
Theron::Framework * framework
ResourceManagerMasterActor * acter_
Constructor & Destructor Documentation
ResourceManagerMaster::ResourceManagerMaster ()
References acter_, endpoint_, framework, Environment::getEndPoint(), NodeTracker::GetInstance(), Environment::getInstance(), logging_, and node_tracker_.
ResourceManagerMaster::~ResourceManagerMaster () virtual
References acter_, framework, node_tracker_, NodeTracker::~NodeTracker(), and ResourceManagerMaster::ResourceManagerMasterActor::~ResourceManagerMasterActor().
Member Function Documentation
bool ResourceManagerMaster::ApplyDiskBuget (NodeID target, unsigned size_in_mb)
References node_to_resourceinfo_.
Referenced by ProjectionBinding::BindingEntireProjection().
bool ResourceManagerMaster::ApplyMemoryBuget (NodeID target, unsigned size_in_mb)
References node_to_resourceinfo_.
Referenced by ProjectionBinding::BindingEntireProjection().
std::vector< NodeID > ResourceManagerMaster::getSlaveIDList ()
References node_to_resourceinfo_.
Referenced by ProjectionBinding::BindingEntireProjection().
bool ResourceManagerMaster::RegisterDiskBuget (NodeID report_node_id, unsigned size_in_mb)
References Logging::log(), logging_, and node_to_resourceinfo_.
bool ResourceManagerMaster::RegisterMemoryBuget (NodeID report_node_id, unsigned size_in_mb)
References Logging::log(), logging_, and node_to_resourceinfo_.
NodeID ResourceManagerMaster::RegisterNewSlave (NodeAddress new_slave_address)
References Logging::elog(), NodeAddress::ip, Logging::log(), logging_, node_to_resourceinfo_, node_tracker_, NodeAddress::port, and NodeTracker::RegisterNode().
bool ResourceManagerMaster::ReturnDiskBuget (NodeID target, unsigned size_in_mb)
References node_to_resourceinfo_.
Referenced by ProjectionBinding::UnbindingEntireProjection().
bool ResourceManagerMaster::ReturnMemoryBuget (NodeID target, unsigned size_in_mb)
References node_to_resourceinfo_.
Referenced by ProjectionBinding::UnbindingEntireProjection().
Member Data Documentation
ResourceManagerMasterActor* ResourceManagerMaster::acter_ private
Referenced by ResourceManagerMaster(), and ~ResourceManagerMaster().
Theron::EndPoint* ResourceManagerMaster::endpoint_ private
Referenced by ResourceManagerMaster().
Theron::Framework* ResourceManagerMaster::framework private
Referenced by ResourceManagerMaster(), and ~ResourceManagerMaster().
Logging* ResourceManagerMaster::logging_ private
Referenced by RegisterDiskBuget(), RegisterMemoryBuget(), RegisterNewSlave(), and ResourceManagerMaster().
boost::unordered_map<NodeID,InstanceResourceInfo*> ResourceManagerMaster::node_to_resourceinfo_ private
Referenced by ApplyDiskBuget(), ApplyMemoryBuget(), getSlaveIDList(), RegisterDiskBuget(), RegisterMemoryBuget(), RegisterNewSlave(), ReturnDiskBuget(), and ReturnMemoryBuget().
NodeTracker* ResourceManagerMaster::node_tracker_ private
Referenced by RegisterNewSlave(), ResourceManagerMaster(), and ~ResourceManagerMaster().
The documentation for this class was generated from the following files:
Resource/ResourceManagerMaster.h
Resource/ResourceManagerMaster.cpp