Claims: StatManager Class Reference
StatManager Class Reference
#include <StatManager.h>
Public Member Functions
virtual ~StatManager ()
Histogram * getHistogram (const AttributeID attID)
Histogram * getStat (const AttributeID attID, const PartitionID partID)
void addStat (const AttributeID attId, Histogram *stat)
void addStat (const AttributeID attId, const PartitionID partId, const Histogram *stat)
TableStatistic * getTableStatistic (const TableID &table_id) const
AttributeStatistics * getAttributeStatistic (const AttributeID &attrId) const
AttributeStatistics * getAttributeStatistic (const Attribute &attr) const
void setTableStatistic (const TableID &table_id, TableStatistic *tab_stat)
Static Public Member Functions
static StatManager * getInstance ()
Private Member Functions
StatManager ()
Private Attributes
boost::unordered_map< TableID,
TableStatistic * > tab_stat_list_
Static Private Attributes
static StatManager * m_singleton = 0
Constructor & Destructor Documentation
StatManager::~StatManager () virtual
StatManager::StatManager () private
Referenced by getInstance().
Member Function Documentation
void StatManager::addStat (const AttributeID attId, Histogram * stat)
void StatManager::addStat (const AttributeID attId, const PartitionID partId, const Histogram * stat)
AttributeStatistics * StatManager::getAttributeStatistic (const AttributeID & attrId) const
References TableStatistic::getAttributeStatistics(), getTableStatistic(), and AttributeID::table_id.
Referenced by Estimation::estEqualJoin(), claims::logical_operator::LogicalAggregation::EstimateGroupByCardinality(), getHistogram(), and claims::logical_operator::LogicalEqualJoin::PredictEqualJoinSelectivityOnSingleJoinAttributePair().
AttributeStatistics * StatManager::getAttributeStatistic (const Attribute & attr) const
References TableStatistic::getAttributeStatistics(), Attribute::getID(), getTableStatistic(), and Attribute::table_id_.
Histogram * StatManager::getHistogram (const AttributeID attID)
References getAttributeStatistic(), and AttributeStatistics::getHistogram().
Referenced by Estimation::estEqualOper(), and Estimation::estRangeOper().
StatManager * StatManager::getInstance () static
References m_singleton, and StatManager().
Referenced by Analyzer::analyse(), Analyzer::analyse_on_project(), Analyzer::compute_attribute_stat(), Analyzer::compute_table_stat(), Estimation::estEqualJoin(), Estimation::estEqualOper(), claims::logical_operator::LogicalAggregation::EstimateGroupByCardinality(), Estimation::estRangeOper(), and claims::logical_operator::LogicalEqualJoin::PredictEqualJoinSelectivityOnSingleJoinAttributePair().
Histogram * StatManager::getStat (const AttributeID attID, const PartitionID partID)
TableStatistic * StatManager::getTableStatistic (const TableID & table_id) const
References tab_stat_list_.
Referenced by Analyzer::analyse(), Analyzer::analyse_on_project(), Analyzer::compute_attribute_stat(), getAttributeStatistic(), and claims::logical_operator::LogicalEqualJoin::PredictEqualJoinSelectivityOnSingleJoinAttributePair().
void StatManager::setTableStatistic (const TableID & table_id, TableStatistic * tab_stat)
References tab_stat_list_.
Referenced by Analyzer::compute_table_stat().
Member Data Documentation
StatManager * StatManager::m_singleton = 0 static private
Referenced by getInstance().
boost::unordered_map<TableID,TableStatistic*> StatManager::tab_stat_list_ private
Referenced by getTableStatistic(), and setTableStatistic().
The documentation for this class was generated from the following files:
Catalog/stat/StatManager.h
Catalog/stat/StatManager.cpp