My Project: claims::logical_operator::LogicalFilter Class Reference
claims::logical_operator::LogicalFilter Class Reference
Method description: Logical Operator "filter", is used to screen out the info we don't need, so as to lessen time cost.
#include <logical_filter.h>
Public Member Functions
LogicalFilter (LogicalOperator *child, vector< QNode * > qual)
Method description: Construction.
virtual ~LogicalFilter ()
Method description: Destruction.
PlanContext GetPlanContext ()
Method description: To get the plan context from its child logical operator, operates on it, thus give it to its father logical operator.
BlockStreamIteratorBase * GetPhysicalPlan (const unsigned &blocksize)
Method description: To get the Iterator Tree from its child logical operator, generates a state for establishing a physical execution plan, finally give it to its father logical operator.
bool GetOptimalPhysicalPlan (Requirement requirement, PhysicalPlanDescriptor &physical_plan_descriptor, const unsigned &block_size=4096 *1024)
void Print (int level=0) const
Method description: To print information of qual_.
Additional Inherited Members
Protected Member Functions inherited from claims::logical_operator::LogicalOperator
Schema * GetSchema (const std::vector< Attribute > &) const
Schema * GetSchema (const std::vector< Attribute > &, const std::vector< Attribute > &) const
std::vector< NodeID > GetInvolvedNodeID (const PlanPartitioner &) const
std::vector< NodeIP > ConvertNodeIDListToNodeIPList (const std::vector< NodeID > &) const
PhysicalPlanDescriptor GetBestPhysicalPlanDescriptor (const std::vector< PhysicalPlanDescriptor >) const
int GetIdInAttributeList (const std::vector< Attribute > &attributes, const Attribute &attribute) const
void set_operator_type (OperatorType operator_type)
Detailed Description
Method description: Logical Operator "filter", is used to screen out the info we don't need, so as to lessen time cost.
Constructor & Destructor Documentation
claims::logical_operator::LogicalFilter::LogicalFilter (LogicalOperator * child, vector< QNode * > qual)
Method description: Construction.
Parameters
child : Its child logical operator.
qual,: Pointing to the root of the expression tree.
Member Function Documentation
bool claims::logical_operator::LogicalFilter::GetOptimalPhysicalPlan (Requirement requirement, PhysicalPlanDescriptor & physical_plan_descriptor, const unsigned & block_size = 4096 * 1024) virtual
get the optimal Physical plan that meets the requirement.
Returns
true if find physical plan that meets the requirement and store the physical plan and its corresponding information in physical_plan_descriptor.
The input plan context should be transfered in the network to meet the requirement. TODO(wangli): Implement OneToOne Exchange
Reimplemented from claims::logical_operator::LogicalOperator.
References claims::logical_operator::PlanContext::GetAggregatedDatasize(), claims::logical_operator::LogicalOperator::GetOptimalPhysicalPlan(), GetPlanContext(), and claims::logical_operator::Requirement::requireNetworkTransfer().
BlockStreamIteratorBase * claims::logical_operator::LogicalFilter::GetPhysicalPlan (const unsigned & blocksize) virtual
Method description: To get the Iterator Tree from its child logical operator, generates a state for establishing a physical execution plan, finally give it to its father logical operator.
Parameters
blocksize,: The size of block in the CLAIMS project.
Returns
BlockStreamIteratorBase*: A block stream iterator pointer, pointing to the root node of filter's iterator tree.
Implements claims::logical_operator::LogicalOperator.
References claims::logical_operator::LogicalOperator::GetPhysicalPlan(), and GetPlanContext().
PlanContext claims::logical_operator::LogicalFilter::GetPlanContext () virtual
Method description: To get the plan context from its child logical operator, operates on it, thus give it to its father logical operator.
Returns
PlanContext
In the currently implementation, we assume that the boolean operator between each AttributeComparator is "AND".
Should predict the volume of data that passes the filter. TODO(wangli): A precious prediction is needed based on the statistic of the input data, which may be maintained in the catalog module.
Implements claims::logical_operator::LogicalOperator.
References claims::logical_operator::LogicalOperator::GetPlanContext().
Referenced by GetOptimalPhysicalPlan(), and GetPhysicalPlan().
void claims::logical_operator::LogicalFilter::Print (int level = 0) const virtual
Method description: To print information of qual_.
Parameters
level,: As an index.
Implements claims::logical_operator::LogicalOperator.
The documentation for this class was generated from the following files:
logical_operator/logical_filter.h
logical_operator/logical_filter.cpp