Claims: CSBPlusTree< T > Class Template Reference
CSBPlusTree< T > Class Template Reference
#include <CSBPlusTree.h>
Public Member Functions
CSBPlusTree ()
virtual ~CSBPlusTree ()
void BulkLoad (data_offset< T > *aray, unsigned arayNo)
map< index_offset, vector
< index_offset > * > * Search (T key)
map< index_offset, vector
< index_offset > * > * rangeQuery (T lower_key, T upper_key)
map< index_offset, vector
< index_offset > * > * rangeQuery (T lower_key, comparison comp_lower, T upper_key, comparison comp_upper)
bool Insert (data_offset< T > data)
bool Delete (T key)
bool serialize (FILE *filename)
bool deserialize (FILE *filename)
void printTree ()
void printDoubleLinkedList ()
template<>
~CSBPlusTree ()
Public Attributes
CCSBNodeGroup< T > * leaf_header
CCSBNodeGroup< T > * leaf_tailer
CCSBNode< T > * csb_root
unsigned csb_depth
Private Member Functions
int makeLeafNodeGroup (data_offset< T > *aray, unsigned aray_num, CCSBNodeGroup< T > **leaf, T *internal_key_array)
int makeInternalNodeGroup (T *internalAray, int iArayNo, CCSBNodeGroup< T > **internal, int leafNGNo, T *in2Aray, CCSBNodeGroup< T > **leaf)
CCSBNode< T > * SearchLeafNode (T data)
bool InsertInternalNode (CCSBInternalNode< T > *pNode, T key, CCSBNode< T > *pRightSon)
bool DeleteInternalNode (CCSBInternalNode< T > *pNode, T key)
void ClearTree ()
Private Attributes
unsigned max_keys
unsigned max_datas
Constructor & Destructor Documentation
template<typename T> CSBPlusTree< T >::CSBPlusTree () inline
References CCSBNode< T >::getMaxDatas(), and CCSBNode< T >::getMaxKeys().
template<typename T > CSBPlusTree< T >::~CSBPlusTree () virtual
template<> CSBPlusTree< int >::~CSBPlusTree ()
Member Function Documentation
template<typename T > void CSBPlusTree< T >::BulkLoad (data_offset< T > * aray, unsigned arayNo)
References CCSBNodeGroup< T >::getNode(), CCSBInternalNodeGroup< T >::getNode(), CCSBInternalNodeGroup< T >::internal_nodes, NULL, CCSBNodeGroup< T >::setHeaderNG(), CCSBNodeGroup< T >::setTailerNG(), and CCSBNodeGroup< T >::used_nodes.
Referenced by cheak_com().
template<typename T > void CSBPlusTree< T >::ClearTree () private
References NULL.
template<typename T > bool CSBPlusTree< T >::Delete (T key)
template<typename T> bool CSBPlusTree< T >::DeleteInternalNode (CCSBInternalNode< T > * pNode, T key) private
template<typename T > bool CSBPlusTree< T >::deserialize (FILE * filename)
References CCSBInternalNodeGroup< T >::deserialize(), CCSBNodeGroup< T >::getNode(), CCSBInternalNodeGroup< T >::getNode(), CCSBNodeGroup< T >::getUsedNodes(), NULL, CCSBNodeGroup< T >::setHeaderNG(), and CCSBNodeGroup< T >::setTailerNG().
Referenced by cheak_com(), and IndexManager::deserialize().
template<typename T > bool CSBPlusTree< T >::Insert (data_offset< T > data)
References data_offset< T >::_key, CCSBNode< T >::getElement(), CCSBNode< T >::getFather(), CCSBNodeGroup< T >::getHeaderNG(), CCSBNodeGroup< T >::getNode(), CCSBLeafNodeGroup< T >::getNode(), CCSBNodeGroup< T >::getTailerNG(), CCSBNode< T >::getUsedKeys(), CCSBNodeGroup< T >::getUsedNodes(), CCSBNode< T >::Insert(), NULL, CCSBNodeGroup< T >::setHeaderNG(), CCSBLeafNodeGroup< T >::setHeaderNG(), CCSBNodeGroup< T >::setNode(), CCSBNodeGroup< T >::setTailerNG(), CCSBLeafNodeGroup< T >::setTailerNG(), and CCSBNodeGroup< T >::setUsedNodes().
Referenced by cheak_com().
template<typename T> bool CSBPlusTree< T >::InsertInternalNode (CCSBInternalNode< T > * pNode, T key, CCSBNode< T > * pRightSon) private
template<typename T > int CSBPlusTree< T >::makeInternalNodeGroup (T * internalAray, int iArayNo, CCSBNodeGroup< T > ** internal, int leafNGNo, T * in2Aray, CCSBNodeGroup< T > ** leaf) private
References CCSBNodeGroup< T >::getUsedNodes().
template<typename T > int CSBPlusTree< T >::makeLeafNodeGroup (data_offset< T > * aray, unsigned aray_num, CCSBNodeGroup< T > ** leaf, T * internal_key_array) private
References data_offset< T >::_key, CCSBNodeGroup< T >::getNode(), NULL, CCSBNodeGroup< T >::setHeaderNG(), CCSBNodeGroup< T >::setTailerNG(), and CCSBNodeGroup< T >::used_nodes.
template<typename T > void CSBPlusTree< T >::printDoubleLinkedList ()
References CCSBNodeGroup< T >::getHeaderNG(), CCSBNodeGroup< T >::getNode(), CCSBNodeGroup< T >::getTailerNG(), CCSBNodeGroup< T >::getUsedNodes(), and NULL.
Referenced by cheak_com().
template<typename T > void CSBPlusTree< T >::printTree ()
References NULL.
Referenced by cheak_com().
template<typename T > map< index_offset, vector< index_offset > * > * CSBPlusTree< T >::rangeQuery (T lower_key, T upper_key)
References CCSBNode< T >::getElement(), CCSBNode< T >::getFather(), CCSBNodeGroup< T >::getNode(), CCSBNode< T >::getPointer(), CCSBNodeGroup< T >::getTailerNG(), CCSBNode< T >::getUsedKeys(), CCSBNodeGroup< T >::getUsedNodes(), NULL, and CCSBNode< T >::used_keys.
Referenced by cheak_com().
template<typename T > map< index_offset, vector< index_offset > * > * CSBPlusTree< T >::rangeQuery (T lower_key, comparison comp_lower, T upper_key, comparison comp_upper)
References EQ, G, GEQ, CCSBNode< T >::getElement(), CCSBNode< T >::getFather(), CCSBNodeGroup< T >::getNode(), CCSBNode< T >::getPointer(), CCSBNodeGroup< T >::getTailerNG(), CCSBNode< T >::getUsedKeys(), CCSBNodeGroup< T >::getUsedNodes(), L, LEQ, NULL, and CCSBNode< T >::used_keys.
template<typename T > map< index_offset, vector< index_offset > * > * CSBPlusTree< T >::Search (T key)
References CCSBNode< T >::getElement(), CCSBNode< T >::getFather(), CCSBNodeGroup< T >::getNode(), CCSBNode< T >::getPointer(), CCSBNodeGroup< T >::getTailerNG(), CCSBNode< T >::getUsedKeys(), CCSBNodeGroup< T >::getUsedNodes(), NULL, and CCSBNode< T >::used_keys.
Referenced by cheak_com().
template<typename T > CCSBNode< T > * CSBPlusTree< T >::SearchLeafNode (T data) private
References CCSBNode< T >::getElement(), CCSBNode< T >::getFather(), CCSBNodeGroup< T >::getNode(), CCSBNode< T >::getPointer(), CCSBNodeGroup< T >::getTailerNG(), CCSBNodeGroup< T >::getUsedNodes(), and NULL.
template<typename T > bool CSBPlusTree< T >::serialize (FILE * filename)
References NULL.
Referenced by cheak_com().
Member Data Documentation
template<typename T> unsigned CSBPlusTree< T >::csb_depth
template<typename T> CCSBNode<T>* CSBPlusTree< T >::csb_root
template<typename T> CCSBNodeGroup<T>* CSBPlusTree< T >::leaf_header
template<typename T> CCSBNodeGroup<T>* CSBPlusTree< T >::leaf_tailer
template<typename T> unsigned CSBPlusTree< T >::max_datas private
template<typename T> unsigned CSBPlusTree< T >::max_keys private
The documentation for this class was generated from the following files:
IndexManager/CSBPlusTree.h
IndexManager/CSBPlusTree.cpp