Claims: ExpanderTracker Class Reference
ExpanderTracker Class Reference
#include <expander_tracker.h>
Classes
struct ExpandedThreadStatus
struct ExpanderStatus
Public Member Functions
virtual ~ExpanderTracker ()
bool registerNewExpandedThreadStatus (expanded_thread_id id, ExpanderID exp_id)
bool deleteExpandedThreadStatus (expanded_thread_id id)
bool isExpandedThreadCallBack (expanded_thread_id id)
bool callbackExpandedThread (expanded_thread_id id)
bool addNewStageEndpoint (expanded_thread_id, LocalStageEndPoint)
PerformanceInfo * getPerformanceInfo (expanded_thread_id)
ExpanderID registerNewExpander (MonitorableBuffer *buffer, ExpandabilityShrinkability *expand_shrink)
void unregisterExpander (ExpanderID expander_id)
bool trackExpander (ExpanderID id) const
Static Public Member Functions
static ExpanderTracker * getInstance ()
static segment_status getSegmentStatus (local_stage &)
Public Attributes
std::map< expanded_thread_id,
ExpandedThreadStatus > id_to_status_
Logging * log_
pthread_t monitor_thread_id_
Private Types
enum segment_status { seg_no_producing, seg_normal_producing, seg_over_producing, seg_under_producing }
Private Member Functions
ExpanderTracker ()
int decideExpandingOrShrinking (local_stage &current_stage, unsigned int current_degree_of_parallelism, bool print=true)
int expandeIfNotExceedTheMaxDegreeOfParallelism (int current_degree_of_parallelism) const
int shrinkIfNotExceedTheMinDegreeOfParallelims (int current_degree_of_parallelism) const
void printStatus ()
Static Private Member Functions
static void * monitoringThread (void *arg)
Private Attributes
Lock lock_
boost::unordered_map
< expanded_thread_id,
ExpanderID > thread_id_to_expander_id_
boost::unordered_map
< ExpanderID, ExpanderStatus * > expander_id_to_status_
boost::unordered_map
< ExpanderID,
ExpandabilityShrinkability * > expander_id_to_expand_shrink_
Static Private Attributes
static ExpanderTracker * instance_ = 0
Member Enumeration Documentation
enum ExpanderTracker::segment_status private
Enumerator
seg_no_producing
seg_normal_producing
seg_over_producing
seg_under_producing
Constructor & Destructor Documentation
ExpanderTracker::~ExpanderTracker () virtual
References instance_, log_, and monitor_thread_id_.
ExpanderTracker::ExpanderTracker () private
References Logging::log(), log_, monitor_thread_id_, and monitoringThread().
Referenced by getInstance().
Member Function Documentation
bool ExpanderTracker::addNewStageEndpoint (expanded_thread_id tid, LocalStageEndPoint endpoint)
References Lock::acquire(), expander_id_to_status_, lock_, Lock::release(), and thread_id_to_expander_id_.
Referenced by claims::physical_operator::PhysicalNestLoopJoin::Open(), claims::physical_operator::PhysicalAggregation::Open(), claims::physical_operator::ExchangeMerger::Open(), claims::physical_operator::PhysicalProjectionScan::Open(), and claims::physical_operator::PhysicalHashJoin::Open().
bool ExpanderTracker::callbackExpandedThread (expanded_thread_id id)
References Lock::acquire(), id_to_status_, lock_, and Lock::release().
Referenced by claims::physical_operator::Expander::TerminateWorkingThread().
int ExpanderTracker::decideExpandingOrShrinking (local_stage & current_stage, unsigned int current_degree_of_parallelism, bool print = true) private
In the initial implementation, if all expanded threads are shrunk and the condition for expanding will never be triggered due to the exhaust of input data-flow, then the remaining work will never be done.
To avoid this problem, we should first check whether the dataflow is exhausted. If so, we should guarantee that there is at least one expanded threads to process the remaining data in buffer.
Currently, for the stage without synchronization all_merged_data_buffer_, the workload is not known and hence maximum degree of parallelism is used.
References local_stage::buffer_to_buffer, local_stage::dataflow_desc_, local_stage::dataflow_src_, DECISION_EXPAND, DECISION_KEEP, DECISION_SHRINK, expandeIfNotExceedTheMaxDegreeOfParallelism(), local_stage::from_buffer, MonitorableBuffer::getBufferUsage(), local_stage::incomplete, MonitorableBuffer::inputComplete(), Logging::log(), log_, Config::max_degree_of_parallelism, LocalStageEndPoint::monitorable_buffer, local_stage::no_buffer, shrinkIfNotExceedTheMinDegreeOfParallelims(), SWITCHER, THRESHOLD_EMPTY, THRESHOLD_FULL, local_stage::to_buffer, and local_stage::type_.
Referenced by monitoringThread().
bool ExpanderTracker::deleteExpandedThreadStatus (expanded_thread_id id)
References Lock::acquire(), id_to_status_, lock_, Lock::release(), and thread_id_to_expander_id_.
Referenced by claims::physical_operator::Expander::ExpandedWork().
int ExpanderTracker::expandeIfNotExceedTheMaxDegreeOfParallelism (int current_degree_of_parallelism) const private
References DECISION_EXPAND, DECISION_KEEP, and Config::max_degree_of_parallelism.
Referenced by decideExpandingOrShrinking().
ExpanderTracker * ExpanderTracker::getInstance () static
References ExpanderTracker(), and instance_.
Referenced by claims::physical_operator::PhysicalOperator::CheckTerminateRequest(), claims::physical_operator::Expander::Close(), claims::physical_operator::ExchangeMerger::CreatePerformanceInfo(), Environment::Environment(), claims::physical_operator::Expander::ExpandedWork(), claims::physical_operator::PhysicalAggregation::Next(), claims::physical_operator::PhysicalProjectionScan::Next(), claims::physical_operator::Expander::Open(), claims::physical_operator::PhysicalNestLoopJoin::Open(), claims::physical_operator::PhysicalAggregation::Open(), claims::physical_operator::ExchangeMerger::Open(), claims::physical_operator::PhysicalProjectionScan::Open(), claims::physical_operator::PhysicalHashJoin::Open(), and claims::physical_operator::Expander::TerminateWorkingThread().
PerformanceInfo * ExpanderTracker::getPerformanceInfo (expanded_thread_id tid)
References Lock::acquire(), expander_id_to_status_, lock_, Lock::release(), and thread_id_to_expander_id_.
Referenced by claims::physical_operator::ExchangeMerger::CreatePerformanceInfo(), claims::physical_operator::PhysicalAggregation::Open(), and claims::physical_operator::PhysicalProjectionScan::Open().
ExpanderTracker::segment_status ExpanderTracker::getSegmentStatus (local_stage & current_stage) static
References local_stage::buffer_to_buffer, local_stage::dataflow_desc_, local_stage::dataflow_src_, local_stage::from_buffer, MonitorableBuffer::getBufferUsage(), local_stage::incomplete, LocalStageEndPoint::monitorable_buffer, local_stage::no_buffer, refine, seg_no_producing, seg_normal_producing, seg_over_producing, seg_under_producing, THRESHOLD_EMPTY, THRESHOLD_FULL, local_stage::to_buffer, and local_stage::type_.
bool ExpanderTracker::isExpandedThreadCallBack (expanded_thread_id id)
References Lock::acquire(), id_to_status_, lock_, and Lock::release().
Referenced by claims::physical_operator::PhysicalOperator::CheckTerminateRequest().
void * ExpanderTracker::monitoringThread (void * arg) static private
References Lock::acquire(), curtick(), decideExpandingOrShrinking(), DECISION_EXPAND, DECISION_SHRINK, Config::enable_expander_adaptivity, Config::expander_adaptivity_check_frequency, expander_id_to_expand_shrink_, expander_id_to_status_, lock_, Logging::log(), log_, Lock::release(), and SWITCHER.
Referenced by ExpanderTracker().
void ExpanderTracker::printStatus () private
References expander_id_to_expand_shrink_, expander_id_to_status_, id_to_status_, and thread_id_to_expander_id_.
bool ExpanderTracker::registerNewExpandedThreadStatus (expanded_thread_id id, ExpanderID exp_id)
References Lock::acquire(), ExpanderTracker::ExpandedThreadStatus::call_back_, expander_id_to_expand_shrink_, id_to_status_, lock_, Lock::release(), and thread_id_to_expander_id_.
Referenced by claims::physical_operator::Expander::ExpandedWork().
ExpanderID ExpanderTracker::registerNewExpander (MonitorableBuffer * buffer, ExpandabilityShrinkability * expand_shrink)
References Lock::acquire(), expander_id_to_expand_shrink_, expander_id_to_status_, IDsGenerator::getInstance(), IDsGenerator::getUniqueExpanderID(), lock_, Logging::log(), log_, Lock::release(), and stage_desc.
Referenced by claims::physical_operator::Expander::Open().
int ExpanderTracker::shrinkIfNotExceedTheMinDegreeOfParallelims (int current_degree_of_parallelism) const private
References DECISION_KEEP, and DECISION_SHRINK.
Referenced by decideExpandingOrShrinking().
bool ExpanderTracker::trackExpander (ExpanderID id) const
References expander_id_to_expand_shrink_, and expander_id_to_status_.
void ExpanderTracker::unregisterExpander (ExpanderID expander_id)
References Lock::acquire(), expander_id_to_expand_shrink_, expander_id_to_status_, lock_, Lock::release(), and thread_id_to_expander_id_.
Referenced by claims::physical_operator::Expander::Close().
Member Data Documentation
boost::unordered_map<ExpanderID,ExpandabilityShrinkability*> ExpanderTracker::expander_id_to_expand_shrink_ private
Referenced by monitoringThread(), printStatus(), registerNewExpandedThreadStatus(), registerNewExpander(), trackExpander(), and unregisterExpander().
boost::unordered_map<ExpanderID,ExpanderStatus*> ExpanderTracker::expander_id_to_status_ private
Referenced by addNewStageEndpoint(), getPerformanceInfo(), monitoringThread(), printStatus(), registerNewExpander(), trackExpander(), and unregisterExpander().
std::map<expanded_thread_id,ExpandedThreadStatus> ExpanderTracker::id_to_status_
Referenced by callbackExpandedThread(), deleteExpandedThreadStatus(), isExpandedThreadCallBack(), printStatus(), and registerNewExpandedThreadStatus().
ExpanderTracker * ExpanderTracker::instance_ = 0 static private
Ideally, this should be guaranteed by resource manager.
Referenced by getInstance(), and ~ExpanderTracker().
Lock ExpanderTracker::lock_ private
Referenced by addNewStageEndpoint(), callbackExpandedThread(), deleteExpandedThreadStatus(), getPerformanceInfo(), isExpandedThreadCallBack(), monitoringThread(), registerNewExpandedThreadStatus(), registerNewExpander(), and unregisterExpander().
Logging* ExpanderTracker::log_
Referenced by decideExpandingOrShrinking(), ExpanderTracker(), monitoringThread(), registerNewExpander(), and ~ExpanderTracker().
pthread_t ExpanderTracker::monitor_thread_id_
Referenced by ExpanderTracker(), and ~ExpanderTracker().
boost::unordered_map<expanded_thread_id,ExpanderID> ExpanderTracker::thread_id_to_expander_id_ private
Referenced by addNewStageEndpoint(), deleteExpandedThreadStatus(), getPerformanceInfo(), printStatus(), registerNewExpandedThreadStatus(), and unregisterExpander().
The documentation for this class was generated from the following files:
Executor/expander_tracker.h
Executor/expander_tracker.cpp