Claims: Analyzer Class Reference
Analyzer Class Reference
#include <Analyzer.h>
Public Types
enum analysis_level { a_l_table, a_l_attribute }
Public Member Functions
Analyzer ()
virtual ~Analyzer ()
Static Public Member Functions
static void analyse (const AttributeID &attrID)
static void analyse (TableID tableID, analysis_level level=a_l_table)
static void analyse_on_project (ProjectionID projection_id)
static void compute_histogram (const AttributeID &attr_id)
static void compute_attribute_stat (const AttributeID &attr_id)
static void compute_table_stat (const TableID &tab_id)
Static Private Member Functions
static void mcvAnalyse (void **list, const unsigned long size, const Attribute &attr, Histogram *stat)
static void equiDepthAnalyse (void **list, const unsigned long size, const Attribute &attr, Histogram *stat)
static unsigned long getDistinctCardinality (const AttributeID &attr_id)
static bool isBeneficalFromHistrogram (unsigned distinct_values, unsigned cardinality)
static Histogram * computeHistogram (const AttributeID &attr, const unsigned nbuckets=20)
static unsigned decideNumberOfBucketsForHistogram (const int distinct_cardinality, const int cardinality)
Member Enumeration Documentation
enum Analyzer::analysis_level
Enumerator
a_l_table
a_l_attribute
Constructor & Destructor Documentation
Analyzer::Analyzer ()
Analyzer::~Analyzer () virtual
Member Function Documentation
void Analyzer::analyse (const AttributeID & attrID) static
References DynamicBlockBuffer::Iterator::atomicNextBlock(), Attribute::attrType, claims::physical_operator::PhysicalOperatorBase::Close(), compare(), DynamicBlockBuffer::createIterator(), BlockStreamBase::createIterator(), DynamicBlockBuffer::destory(), TableDescriptor::getAttribute(), getFrequency(), StatManager::getInstance(), Catalog::getInstance(), TableDescriptor::getNumberOfProjection(), DynamicBlockBuffer::getNumberOftuples(), claims::logical_operator::LogicalOperator::GetPhysicalPlan(), TableDescriptor::getProjectoin(), claims::physical_operator::PhysicalOperatorBase::GetResultSet(), Catalog::getTable(), StatManager::getTableStatistic(), ProjectionDescriptor::hasAttribute(), claims::logical_operator::LogicalQueryPlanRoot::kResultCollector, claims::physical_operator::PhysicalOperatorBase::Next(), BlockStreamBase::BlockStreamTraverseIterator::nextTuple(), NULL, AttributeID::offset, claims::physical_operator::PhysicalOperatorBase::Open(), column_type::operate, Histogram::setTupleCount(), Histogram::setValueCount(), and AttributeID::table_id.
Referenced by statistic_manager_test().
void Analyzer::analyse (TableID tableID, analysis_level level = a_l_table) static
References TableDescriptor::getAttributes(), StatManager::getInstance(), Catalog::getInstance(), Catalog::getTable(), and StatManager::getTableStatistic().
void Analyzer::analyse_on_project (ProjectionID projection_id) static
First make sure that the table statistic is available, and then make attribute-level-analyze on each attribute within this projection.
References ProjectionDescriptor::getAttributeList(), StatManager::getInstance(), Catalog::getInstance(), Catalog::getProjection(), StatManager::getTableStatistic(), and ProjectionID::table_id.
void Analyzer::compute_attribute_stat (const AttributeID & attr_id) static
for attribute that has UNIQUE property, gathering the number of distinct values is unnecessary.
References TableStatistic::addAttributeStatistics(), computeHistogram(), TableStatistic::getAttributeStatistics(), getDistinctCardinality(), StatManager::getInstance(), Catalog::getInstance(), StatManager::getTableStatistic(), isBeneficalFromHistrogram(), TableStatistic::number_of_tuples_, AttributeID::offset, AttributeStatistics::print(), Histogram::Print(), AttributeStatistics::setDistinctCardinality(), AttributeStatistics::setHistogram(), and AttributeID::table_id.
void Analyzer::compute_histogram (const AttributeID & attr_id) static
void Analyzer::compute_table_stat (const TableID & tab_id) static
References ATTRIBUTE_ANY, claims::physical_operator::PhysicalOperatorBase::Close(), DynamicBlockBuffer::createIterator(), BlockStreamBase::createIterator(), DynamicBlockBuffer::destory(), StatManager::getInstance(), Catalog::getInstance(), claims::logical_operator::LogicalOperator::GetPhysicalPlan(), TableDescriptor::getProjectoin(), claims::physical_operator::PhysicalOperatorBase::GetResultSet(), Catalog::getTable(), claims::logical_operator::LogicalQueryPlanRoot::kResultCollector, claims::physical_operator::PhysicalOperatorBase::Next(), DynamicBlockBuffer::Iterator::nextBlock(), BlockStreamBase::BlockStreamTraverseIterator::nextTuple(), TableStatistic::number_of_tuples_, claims::physical_operator::PhysicalOperatorBase::Open(), TableStatistic::print(), StatManager::setTableStatistic(), and claims::logical_operator::LogicalOperator::~LogicalOperator().
Histogram * Analyzer::computeHistogram (const AttributeID & attr, const unsigned nbuckets = 20) static private
get histogram if any, otherwise compute it.
References DynamicBlockBuffer::Iterator::atomicNextBlock(), Attribute::attrType, claims::physical_operator::PhysicalOperatorBase::Close(), compare(), DynamicBlockBuffer::createIterator(), BlockStreamBase::createIterator(), DynamicBlockBuffer::destory(), TableDescriptor::getAttribute(), getFrequency(), Catalog::getInstance(), TableDescriptor::getNumberOfProjection(), DynamicBlockBuffer::getNumberOftuples(), claims::logical_operator::LogicalOperator::GetPhysicalPlan(), TableDescriptor::getProjectoin(), claims::physical_operator::PhysicalOperatorBase::GetResultSet(), ProjectionDescriptor::hasAttribute(), claims::logical_operator::LogicalQueryPlanRoot::kResultCollector, claims::physical_operator::PhysicalOperatorBase::Next(), BlockStreamBase::BlockStreamTraverseIterator::nextTuple(), NULL, AttributeID::offset, claims::physical_operator::PhysicalOperatorBase::Open(), column_type::operate, Histogram::setTupleCount(), Histogram::setValueCount(), and AttributeID::table_id.
Referenced by compute_attribute_stat().
unsigned Analyzer::decideNumberOfBucketsForHistogram (const int distinct_cardinality, const int cardinality) static private
void Analyzer::equiDepthAnalyse (void ** list, const unsigned long size, const Attribute & attr, Histogram * stat) static private
References Operate::assign, Attribute::attrType, column_type::get_length(), Histogram::getBucketCnt(), getFrequency(), Histogram::getTupleCount(), column_type::operate, and Histogram::setEquithDepthBound().
unsigned long Analyzer::getDistinctCardinality (const AttributeID & attr_id) static private
References ATTRIBUTE_ANY, claims::physical_operator::PhysicalOperatorBase::Close(), DynamicBlockBuffer::createIterator(), BlockStreamBase::createIterator(), DynamicBlockBuffer::destory(), Catalog::getInstance(), claims::logical_operator::LogicalOperator::GetPhysicalPlan(), claims::physical_operator::PhysicalOperatorBase::GetResultSet(), claims::logical_operator::LogicalQueryPlanRoot::kResultCollector, claims::physical_operator::PhysicalOperatorBase::Next(), DynamicBlockBuffer::Iterator::nextBlock(), BlockStreamBase::BlockStreamTraverseIterator::nextTuple(), AttributeID::offset, claims::physical_operator::PhysicalOperatorBase::Open(), AttributeID::table_id, claims::logical_operator::LogicalOperator::~LogicalOperator(), and claims::physical_operator::PhysicalOperatorBase::~PhysicalOperatorBase().
Referenced by compute_attribute_stat().
bool Analyzer::isBeneficalFromHistrogram (unsigned distinct_values, unsigned cardinality) static private
Referenced by compute_attribute_stat().
void Analyzer::mcvAnalyse (void ** list, const unsigned long size, const Attribute & attr, Histogram * stat) static private
References Operate::assign, Attribute::attrType, column_type::get_length(), Histogram::getBucketCnt(), getFrequency(), Histogram::getTupleCount(), column_type::operate, and Histogram::setMostCommonValues().
The documentation for this class was generated from the following files:
Catalog/stat/Analyzer.h
Catalog/stat/Analyzer.cpp