Claims: Estimation Class Reference
Estimation Class Reference
#include <Estimation.h>
Public Member Functions
Estimation ()
virtual ~Estimation ()
Static Public Member Functions
static unsigned long estEqualOper (AttributeID attrID, void *para)
static unsigned long estRangeOper (AttributeID attrID, void *lowPara, void *upperPara)
static unsigned long estEqualJoin (AttributeID attrID1, AttributeID attrID2)
Constructor & Destructor Documentation
Estimation::Estimation ()
Estimation::~Estimation () virtual
Member Function Documentation
unsigned long Estimation::estEqualJoin (AttributeID attrID1, AttributeID attrID2) static
References Attribute::attrType, TableDescriptor::getAttribute(), StatManager::getAttributeStatistic(), AttributeStatistics::getHistogram(), StatManager::getInstance(), Catalog::getInstance(), Catalog::getTable(), Histogram::m_bucketCnt, Histogram::m_staCount, Histogram::m_staNumbers1, Histogram::m_staValues1, AttributeID::offset, product(), AttributeID::table_id, and column_type::type.
unsigned long Estimation::estEqualOper (AttributeID attrID, void * para) static
如果找到最小的 i 满足 para < valueList[i]，那么para必然落在i-1号bucket中。 如果始终找不到，那么para必然是最大值，落在最后一个bucket中。
最大值，属于上一个边界。因为，唯独最后一个bucket两边都是闭区间。
References Attribute::attrType, Operate::compare(), Operate::equal(), TableDescriptor::getAttribute(), StatManager::getHistogram(), StatManager::getInstance(), Catalog::getInstance(), Catalog::getTable(), Histogram::getTupleCount(), Histogram::m_bucketCnt, Histogram::m_staNumbers1, Histogram::m_staNumbers2, Histogram::m_staValues1, Histogram::m_staValues2, AttributeID::offset, column_type::operate, and AttributeID::table_id.
unsigned long Estimation::estRangeOper (AttributeID attrID, void * lowPara, void * upperPara) static
assume both lowPara and upperPara is legal lowPara: upperPara: range is used with < and >, instead of = for <=, it decomposed into < and =
References Attribute::attrType, Operate::compare(), Operate::equal(), TableDescriptor::getAttribute(), StatManager::getHistogram(), StatManager::getInstance(), Catalog::getInstance(), Catalog::getTable(), Histogram::m_bucketCnt, Histogram::m_staCount, Histogram::m_staNumbers1, Histogram::m_staValues1, AttributeID::offset, column_type::operate, ratio(), and AttributeID::table_id.
The documentation for this class was generated from the following files:
Catalog/stat/Estimation.h
Catalog/stat/Estimation.cpp