Claims: PartitionFunction Class Reference
PartitionFunction Class Reference abstract
#include <hash.h>
Public Types
enum PartitionStyle { hash_f, range_f, round_robin_f }
Public Member Functions
PartitionFunction ()
PartitionFunction (int min, int max, unsigned int k)
virtual ~PartitionFunction ()
virtual PartitionStyle getPartitionFashion () const =0
virtual unsigned int get_partition_value (const int &value) const =0
virtual unsigned int get_partition_value (const double &value) const =0
virtual unsigned int get_partition_value (const unsigned long &) const =0
virtual unsigned int getNumberOfPartitions () const =0
bool equal (PartitionFunction *function_) const
Protected Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Protected Attributes
int min_
int max_
unsigned long int k_
Friends
class boost::serialization::access
Member Enumeration Documentation
enum PartitionFunction::PartitionStyle
Enumerator
hash_f
range_f
round_robin_f
Constructor & Destructor Documentation
PartitionFunction::PartitionFunction () inline
Creates a new hashing object, rounding the number of buckets k to the next power of two. Formally k will become
Parameters
min Minimum hash value
max Maximum hash value
k Number of buckets. Value will be rounded to the next higher power of two.
PartitionFunction::PartitionFunction (int min, int max, unsigned int k)
References getlogarithm(), and k_.
virtual PartitionFunction::~PartitionFunction () inline virtual
Member Function Documentation
bool PartitionFunction::equal (PartitionFunction * function_) const
References getNumberOfPartitions(), and getPartitionFashion().
Referenced by claims::logical_operator::Requirement::requireNetworkTransfer().
virtual unsigned int PartitionFunction::get_partition_value (const int & value) const pure virtual
Returns the bucket number for this value.
Parameters
value Value to hash. Must be within bounds.
Returns
Bucket number.
Implemented in BoostHashFunctin, GeneralModuloFunction, ModuloHashFunction, UniformRangePartitionFunction, and RoundRobinPartitionFunction.
Referenced by OperateInt::getPartitionValue(), OperateFloat::getPartitionValue(), OperateDouble::getPartitionValue(), OperateULong::getPartitionValue(), OperateSmallInt::getPartitionValue(), OperateUSmallInt::getPartitionValue(), OperateDecimal::getPartitionValue(), and OperateBool::getPartitionValue().
virtual unsigned int PartitionFunction::get_partition_value (const double & value) const pure virtual
Implemented in BoostHashFunctin, GeneralModuloFunction, ModuloHashFunction, UniformRangePartitionFunction, and RoundRobinPartitionFunction.
virtual unsigned int PartitionFunction::get_partition_value (const unsigned long &) const pure virtual
Implemented in BoostHashFunctin, GeneralModuloFunction, ModuloHashFunction, UniformRangePartitionFunction, and RoundRobinPartitionFunction.
virtual unsigned int PartitionFunction::getNumberOfPartitions () const pure virtual
Implemented in BoostHashFunctin, GeneralModuloFunction, ModuloHashFunction, UniformRangePartitionFunction, and RoundRobinPartitionFunction.
Referenced by equal(), Partitioner::getNumberOfPartitions(), claims::logical_operator::LogicalScan::GetOptimalPhysicalPlan(), claims::logical_operator::LogicalFilter::GetOptimalPhysicalPlan(), claims::logical_operator::LogicalQueryPlanRoot::GetOptimalPhysicalPlan(), insert_into_hash_table(), and insert_into_hash_table_from_projection().
virtual PartitionStyle PartitionFunction::getPartitionFashion () const pure virtual
Implemented in BoostHashFunctin, GeneralModuloFunction, ModuloHashFunction, UniformRangePartitionFunction, and RoundRobinPartitionFunction.
Referenced by equal(), Partitioner::getPartitionFashion(), and claims::logical_operator::PlanPartitioner::GetPartitionStyle().
template<class Archive > void PartitionFunction::serialize (Archive & ar, const unsigned int version) inline protected
References k_, max_, and min_.
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
unsigned long int PartitionFunction::k_ protected
, where is number of buckets
Referenced by UniformRangePartitionFunction::get_partition_value(), ModuloHashFunction::get_partition_value(), UniformRangePartitionFunction::getNumberOfPartitions(), ModuloHashFunction::getNumberOfPartitions(), ModuloHashFunction::ModuloHashFunction(), PartitionFunction(), and serialize().
int PartitionFunction::max_ protected
Referenced by UniformRangePartitionFunction::get_partition_value(), and serialize().
int PartitionFunction::min_ protected
Referenced by UniformRangePartitionFunction::get_partition_value(), ModuloHashFunction::get_partition_value(), and serialize().
The documentation for this class was generated from the following files:
common/hash.h
common/hash.cpp