Claims: IndexManager Class Reference
IndexManager Class Reference
#include <IndexManager.h>
Public Member Functions
virtual ~IndexManager ()
bool addIndexToList (unsigned key_indexing, map< ChunkID, void * > attr_index)
bool insertIndexToList (std::string index_name, unsigned key_indexing, map< ChunkID, void * > attr_index)
template<typename T >
std::map< ChunkID, CSBPlusTree
< T > * > getIndexList (Attribute attribute)
template<typename T >
std::map< ChunkID, CSBPlusTree
< T > * > getIndexList (unsigned long attr_index_id)
std::map< ChunkID, void * > getAttrIndex (unsigned long attr_index_id)
template<typename T >
bool deleteIndexFromList (unsigned long index_id)
data_type getIndexType (unsigned long index_id)
bool isIndexExist (Attribute attr)
bool isIndexExist (unsigned long index_id)
unsigned long getIndexID (Attribute attr)
bool serialize (std::string file_name)
bool deserialize (std::string file_name)
Static Public Member Functions
static IndexManager * getInstance ()
Private Member Functions
IndexManager ()
Private Attributes
map< unsigned long,
attr_index_list * > csb_index_
unsigned long attr_index_id_
map< Attribute, unsigned long > column_attribute_to_id
map< unsigned long, Attribute > id_to_column_attribute
Static Private Attributes
static IndexManager * instance_ = 0
Constructor & Destructor Documentation
IndexManager::~IndexManager () virtual
IndexManager::IndexManager () private
References attr_index_id_, column_attribute_to_id, csb_index_, and id_to_column_attribute.
Referenced by getInstance().
Member Function Documentation
bool IndexManager::addIndexToList (unsigned key_indexing, map< ChunkID, void * > attr_index)
References attr_index_id_, column_attribute_to_id, csb_index_, attr_index_list::csb_tree_list, Catalog::getInstance(), Catalog::getProjection(), and id_to_column_attribute.
template<typename T > bool IndexManager::deleteIndexFromList (unsigned long index_id)
References column_attribute_to_id, csb_index_, attr_index_list::csb_tree_list, and id_to_column_attribute.
bool IndexManager::deserialize (std::string file_name)
References attr_index_id_, attr_index_list::attr_index_name, attr_index_list::attribute, Attribute::attrName, Attribute::attrType, column_attribute_to_id, csb_index_, attr_index_list::csb_tree_list, CSBPlusTree< T >::deserialize(), id_to_column_attribute, Attribute::index, NULL, t_int, Attribute::table_id_, column_type::type, and Attribute::unique.
Referenced by test_deserialize().
std::map< ChunkID, void * > IndexManager::getAttrIndex (unsigned long attr_index_id)
References csb_index_.
Referenced by IndexScanIterator::Open().
unsigned long IndexManager::getIndexID (Attribute attr)
References Attribute::attrName, column_attribute_to_id, and isIndexExist().
Referenced by LogicalIndexScan::GetPhysicalPlan().
template<typename T > std::map< ChunkID, CSBPlusTree< T > * > IndexManager::getIndexList (Attribute attribute)
References Attribute::attrName, column_attribute_to_id, and csb_index_.
Referenced by cheak_com_index().
template<typename T > std::map< ChunkID, CSBPlusTree< T > * > IndexManager::getIndexList (unsigned long attr_index_id)
References csb_index_.
data_type IndexManager::getIndexType (unsigned long index_id)
References id_to_column_attribute.
Referenced by IndexScanIterator::askForNextBlock().
IndexManager * IndexManager::getInstance () static
References IndexManager(), and instance_.
Referenced by IndexScanIterator::askForNextBlock(), cheak_com_index(), LogicalIndexScan::GetPhysicalPlan(), Environment::initializeIndexManager(), bottomLayerSorting::Next(), IndexScanIterator::Open(), test_deserialize(), and test_serialize().
bool IndexManager::insertIndexToList (std::string index_name, unsigned key_indexing, map< ChunkID, void * > attr_index)
References attr_index_id_, Attribute::attrName, column_attribute_to_id, csb_index_, attr_index_list::csb_tree_list, Catalog::getInstance(), Catalog::getProjection(), and id_to_column_attribute.
Referenced by bottomLayerSorting::Next().
bool IndexManager::isIndexExist (Attribute attr)
References column_attribute_to_id.
Referenced by getIndexID().
bool IndexManager::isIndexExist (unsigned long index_id)
References csb_index_.
bool IndexManager::serialize (std::string file_name)
References attr_index_id_, attr_index_list::attr_index_name, attr_index_list::attribute, Attribute::attrName, Attribute::attrType, csb_index_, attr_index_list::csb_tree_list, Attribute::index, NULL, t_int, Attribute::table_id_, column_type::type, and Attribute::unique.
Referenced by test_serialize().
Member Data Documentation
unsigned long IndexManager::attr_index_id_ private
Referenced by addIndexToList(), deserialize(), IndexManager(), insertIndexToList(), and serialize().
map<Attribute, unsigned long > IndexManager::column_attribute_to_id private
Referenced by addIndexToList(), deleteIndexFromList(), deserialize(), getIndexID(), getIndexList(), IndexManager(), insertIndexToList(), and isIndexExist().
map<unsigned long, attr_index_list*> IndexManager::csb_index_ private
Referenced by addIndexToList(), deleteIndexFromList(), deserialize(), getAttrIndex(), getIndexList(), IndexManager(), insertIndexToList(), isIndexExist(), and serialize().
map<unsigned long, Attribute> IndexManager::id_to_column_attribute private
Referenced by addIndexToList(), deleteIndexFromList(), deserialize(), getIndexType(), IndexManager(), and insertIndexToList().
IndexManager * IndexManager::instance_ = 0 static private
Referenced by getInstance().
The documentation for this class was generated from the following files:
IndexManager/IndexManager.h
IndexManager/IndexManager.cpp