Claims: Json Namespace Reference
Json Namespace Reference
JSON (JavaScript Object Notation).
Classes
class Features
Configuration passed to reader and writer. This configuration object can be used to force the Reader or Writer to behave in a standard conforming way.
class StaticString
Lightweight wrapper to tag static string.
class Value
Represents a JSON value.
class PathArgument
Experimental and untested: represents an element of the "path" to access a node.
class Path
Experimental and untested: represents a "path" to access a node.
class ValueIteratorBase
base class for Value iterators.
class ValueConstIterator
const iterator for object and array value.
class ValueIterator
Iterator for object and array value.
class Reader
Unserialize a JSON document into a Value.
class Writer
Abstract class for writers.
class FastWriter
Outputs a Value in JSON format without formatting (not human friendly).
class StyledWriter
Writes a Value in JSON format in a human friendly way.
class StyledStreamWriter
Writes a Value in JSON format in a human friendly way, to a stream rather than to a string.
class BatchAllocator
Typedefs
typedef int Int
typedef unsigned int UInt
typedef long long int Int64
typedef unsigned long long int UInt64
typedef Int64 LargestInt
typedef UInt64 LargestUInt
typedef unsigned int ArrayIndex
typedef char UIntToStringBuffer [uintToStringBufferSize]
Enumerations
enum ValueType {
nullValue = 0, intValue, uintValue, realValue,
stringValue, booleanValue, arrayValue, objectValue
}
Type of the value held by a Value object.
enum CommentPlacement { commentBefore = 0, commentAfterOnSameLine, commentAfter, numberOfCommentPlacement }
enum { uintToStringBufferSize = 3 * sizeof(LargestUInt) + 1 }
Functions
JSON_API std::istream & operator>> (std::istream &, Value &)
Read from 'sin' into 'root'.
std::string JSON_API valueToString (Int value)
std::string JSON_API valueToString (UInt value)
std::string JSON_API valueToString (LargestInt value)
std::string JSON_API valueToString (LargestUInt value)
std::string JSON_API valueToString (double value)
std::string JSON_API valueToString (bool value)
std::string JSON_API valueToQuotedString (const char *value)
JSON_API std::ostream & operator<< (std::ostream &, const Value &root)
Output using the StyledStreamWriter.
static std::string codePointToUTF8 (unsigned int cp)
Converts a unicode code-point to UTF-8.
static bool isControlCharacter (char ch)
Returns true if ch is a control character (in range [0,32[).
static void uintToString (LargestUInt value, char *&current)
static void fixNumericLocale (char *begin, char *end)
static bool in (Reader::Char c, Reader::Char c1, Reader::Char c2, Reader::Char c3, Reader::Char c4)
static bool in (Reader::Char c, Reader::Char c1, Reader::Char c2, Reader::Char c3, Reader::Char c4, Reader::Char c5)
static bool containsNewLine (Reader::Location begin, Reader::Location end)
static const unsigned char ALIGNAS (8) kNull[sizeof(Value)]
template<typename T , typename U >
static bool InRange (double d, T min, U max)
static char * duplicateStringValue (const char *value, unsigned int length=unknown)
static void releaseStringValue (char *value)
static bool IsIntegral (double d)
static bool containsControlCharacter (const char *str)
Variables
const unsigned char & kNullRef = kNull[0]
static const double maxUInt64AsDouble = 18446744073709551615.0
static const unsigned int unknown = (unsigned)-1
Unknown size marker.
Detailed Description
JSON (JavaScript Object Notation).
Typedef Documentation
typedef unsigned int Json::ArrayIndex
typedef int Json::Int
typedef long long int Json::Int64
typedef Int64 Json::LargestInt
typedef UInt64 Json::LargestUInt
typedef unsigned int Json::UInt
typedef unsigned long long int Json::UInt64
typedef char Json::UIntToStringBuffer[uintToStringBufferSize]
Enumeration Type Documentation
anonymous enum
Enumerator
uintToStringBufferSize
Constant that specify the size of the buffer that must be passed to uintToString.
enum Json::CommentPlacement
Enumerator
commentBefore
a comment placed on the line before a value
commentAfterOnSameLine
a comment just after a value on the same line
commentAfter
a comment on the line after a value (only make sense for
numberOfCommentPlacement
root value)
enum Json::ValueType
Type of the value held by a Value object.
Enumerator
nullValue
'null' value
intValue
signed integer value
uintValue
unsigned integer value
realValue
double value
stringValue
UTF-8 string value.
booleanValue
bool value
arrayValue
array value (ordered list)
objectValue
object value (collection of name/value pairs).
Function Documentation
static const unsigned char Json::ALIGNAS (8) static
static std::string Json::codePointToUTF8 (unsigned int cp) inline static
Converts a unicode code-point to UTF-8.
Referenced by Json::Reader::decodeString().
static bool Json::containsControlCharacter (const char * str) static
References isControlCharacter().
Referenced by valueToQuotedString().
static bool Json::containsNewLine (Reader::Location begin, Reader::Location end) static
Referenced by Json::Reader::readComment().
static char* Json::duplicateStringValue (const char * value, unsigned int length = unknown) inline static
Duplicates the specified string value.
Parameters
value Pointer to the string to duplicate. Must be zero-terminated if length is "unknown".
length Length of the value. if equals to unknown, then it will be computed using strlen(value).
Returns
Pointer on the duplicate instance of string.
References JSON_ASSERT_MESSAGE, Json::Value::maxInt, and unknown.
Referenced by Json::Value::CommentInfo::setComment(), and Json::Value::Value().
static void Json::fixNumericLocale (char * begin, char * end) inline static
Change ',' to '.' everywhere in buffer.
We had a sophisticated way, but it did not work in WinCE.
See Also
https://github.com/open-source-parsers/jsoncpp/pull/9
Referenced by valueToString().
static bool Json::in (Reader::Char c, Reader::Char c1, Reader::Char c2, Reader::Char c3, Reader::Char c4) inline static
Referenced by bulk_test_logical_index_scan(), Json::Reader::decodeNumber(), Json::Path::Path(), and Json::Reader::readNumber().
static bool Json::in (Reader::Char c, Reader::Char c1, Reader::Char c2, Reader::Char c3, Reader::Char c4, Reader::Char c5) inline static
template<typename T , typename U > static bool Json::InRange (double d, T min, U max) inline static
Referenced by Json::Value::asInt(), Json::Value::asInt64(), Json::Value::asUInt(), Json::Value::asUInt64(), and Json::Value::isConvertibleTo().
static bool Json::isControlCharacter (char ch) inline static
Returns true if ch is a control character (in range [0,32[).
Referenced by containsControlCharacter(), and valueToQuotedString().
static bool Json::IsIntegral (double d) static
Referenced by Json::Value::isInt(), Json::Value::isInt64(), Json::Value::isUInt(), and Json::Value::isUInt64().
std::ostream & Json::operator<< (std::ostream & sout, const Value & root)
Output using the StyledStreamWriter.
See Also
Json::operator>>()
References Json::StyledStreamWriter::write().
std::istream & Json::operator>> (std::istream & sin, Value & root)
Read from 'sin' into 'root'.
Always keep comments from the input JSON.
This can be used to read a file into a particular sub-object. For example:
Json::Value root;
cin >> root["dir"]["file"];
cout << root;
Result:
{
"dir": {
    "file": {
    // The input stream JSON would be nested here.
    }
}
}
Exceptions
std::exception on parse error.
See Also
Json::operator<<()
References Json::Reader::getFormattedErrorMessages(), JSON_FAIL_MESSAGE, and Json::Reader::parse().
static void Json::releaseStringValue (char * value) inline static
Free the string duplicated by duplicateStringValue().
Referenced by Json::Value::CommentInfo::setComment(), Json::Value::CommentInfo::~CommentInfo(), Json::Value::CZString::~CZString(), and Json::Value::~Value().
static void Json::uintToString (LargestUInt value, char *& current) inline static
Converts an unsigned integer to string.
Parameters
value Unsigned interger to convert to string
current Input/Output string buffer. Must have at least uintToStringBufferSize chars free.
Referenced by valueToString().
std::string Json::valueToQuotedString (const char * value)
References containsControlCharacter(), isControlCharacter(), and NULL.
Referenced by Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), and Json::StyledStreamWriter::writeValue().
std::string Json::valueToString (Int value)
Referenced by Json::Value::asString(), valueToString(), Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), and Json::StyledStreamWriter::writeValue().
std::string Json::valueToString (UInt value)
References valueToString().
std::string Json::valueToString (LargestInt value)
References uintToString().
std::string Json::valueToString (LargestUInt value)
References uintToString().
std::string Json::valueToString (double value)
References fixNumericLocale().
std::string Json::valueToString (bool value)
Variable Documentation
const unsigned char& Json::kNullRef = kNull[0]
const double Json::maxUInt64AsDouble = 18446744073709551615.0 static
Referenced by Json::Value::isUInt64().
const unsigned int Json::unknown = (unsigned)-1 static
Unknown size marker.
Referenced by duplicateStringValue().