Claims: partition_schema Struct Reference
partition_schema Struct Reference
#include <partition_functions.h>
Public Types
enum partition_mode { hash, broadcase, range }
Public Member Functions
bool isHashPartition () const
bool isBoardcastPartition () const
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Static Public Member Functions
static partition_schema set_hash_partition (int _partition_key_index=0)
static partition_schema set_broadcast_partition ()
static partition_schema set_range_partition (int _number_of_ranges)
Public Attributes
partition_mode mode
unsigned partition_key_index
Friends
class boost::serialization::access
Member Enumeration Documentation
enum partition_schema::partition_mode
Enumerator
hash
broadcase
range
Member Function Documentation
bool partition_schema::isBoardcastPartition () const inline
References broadcase, and mode.
Referenced by claims::physical_operator::ExchangeSenderMaterialized::Next(), and claims::physical_operator::ExchangeSenderPipeline::Next().
bool partition_schema::isHashPartition () const inline
References hash, and mode.
Referenced by claims::physical_operator::ExchangeSenderMaterialized::Next(), and claims::physical_operator::ExchangeSenderPipeline::Next().
template<class Archive > void partition_schema::serialize (Archive & ar, const unsigned int version) inline
References mode, and partition_key_index.
static partition_schema partition_schema::set_broadcast_partition () inline static
References broadcase, mode, and partition_key_index.
Referenced by claims::logical_operator::LogicalCrossJoin::GenerateChildPhysicalQueryPlan().
static partition_schema partition_schema::set_hash_partition (int _partition_key_index = 0) inline static
References hash, mode, and partition_key_index.
Referenced by claims::logical_operator::LogicalScan::GetOptimalPhysicalPlan(), claims::logical_operator::LogicalFilter::GetOptimalPhysicalPlan(), claims::logical_operator::LogicalQueryPlanRoot::GetOptimalPhysicalPlan(), claims::logical_operator::LogicalQueryPlanRoot::GetPhysicalPlan(), claims::logical_operator::LogicalEqualJoin::GetPhysicalPlan(), claims::logical_operator::LogicalSort::GetPhysicalPlan(), and claims::logical_operator::LogicalAggregation::GetPhysicalPlan().
static partition_schema partition_schema::set_range_partition (int _number_of_ranges) inline static
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
partition_mode partition_schema::mode
Referenced by isBoardcastPartition(), isHashPartition(), claims::physical_operator::ExchangeMerger::Print(), serialize(), set_broadcast_partition(), and set_hash_partition().
unsigned partition_schema::partition_key_index
Referenced by claims::physical_operator::ExchangeMerger::ExchangeMerger(), claims::physical_operator::ExchangeSenderPipeline::ExchangeSenderPipeline(), claims::physical_operator::ExchangeSenderMaterialized::Next(), claims::physical_operator::ExchangeSenderPipeline::Next(), claims::physical_operator::ExchangeMerger::Print(), serialize(), set_broadcast_partition(), and set_hash_partition().
The documentation for this struct was generated from the following file:
common/partition_functions.h