Claims: input_struct Struct Reference
input_struct Struct Reference
#include <command_line.h>
Public Member Functions
input_struct ()
void reset ()
bool append (const char *str)
bool append_til (const char *str, char target, bool &target_match)
Public Attributes
char string [string_length]
int index
Constructor & Destructor Documentation
input_struct::input_struct ()
References string_length.
Member Function Documentation
bool input_struct::append (const char * str)
References index, and string_length.
Referenced by get_one_command(), and recovery_history().
bool input_struct::append_til (const char * str, char target, bool & target_match)
References index, and string_length.
Referenced by get_one_command(), and recovery_history().
void input_struct::reset ()
References index, and string_length.
Referenced by recovery_history().
Member Data Documentation
int input_struct::index
Referenced by append(), append_til(), and reset().
char input_struct::string[string_length]
Referenced by get_one_command(), and recovery_history().
The documentation for this struct was generated from the following files:
utility/command_line.h
utility/command_line.cpp