Claims: TableIDAllocator Struct Reference
TableIDAllocator Struct Reference
#include <Catalog.h>
Public Member Functions
TableIDAllocator ()
unsigned allocate_unique_table_id ()
void decrease_table_id ()
template<class Archive >
void serialize (Archive &ar, const unsigned int file_version)
Public Attributes
Lock lock_
unsigned table_id_curosr
Friends
class boost::serialization::access
Constructor & Destructor Documentation
TableIDAllocator::TableIDAllocator () inline
References table_id_curosr.
Member Function Documentation
unsigned TableIDAllocator::allocate_unique_table_id () inline
References Lock::acquire(), lock_, Lock::release(), and table_id_curosr.
Referenced by Catalog::allocate_unique_table_id().
void TableIDAllocator::decrease_table_id () inline
References Lock::acquire(), lock_, Lock::release(), and table_id_curosr.
Referenced by Catalog::add_table().
template<class Archive > void TableIDAllocator::serialize (Archive & ar, const unsigned int file_version) inline
References table_id_curosr.
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
Lock TableIDAllocator::lock_
Referenced by allocate_unique_table_id(), and decrease_table_id().
unsigned TableIDAllocator::table_id_curosr
Referenced by allocate_unique_table_id(), decrease_table_id(), Catalog::getTableCount(), serialize(), and TableIDAllocator().
The documentation for this struct was generated from the following file:
Catalog/Catalog.h