Claims: PerformanceInfo Struct Reference
PerformanceInfo Struct Reference
#include <ExpandedThreadTracker.h>
Classes
struct entry
Public Member Functions
PerformanceInfo ()
PerformanceInfo (ExpandabilityShrinkability *expand_shrink)
~PerformanceInfo ()
void processed_one_block ()
double report_instance_performance_in_millibytes ()
void initialize ()
void eclipseTimeSlices (unsigned offset)
void hitCurrentSlice ()
void updateTimeSlicesToCurrentTicks ()
unsigned long getBlockSumInAllSlices ()
Public Attributes
ticks current_time_slice_start_
unsigned long nblocks_in_current_slice_
SpineLock lock_
unsigned * slices
unsigned long long int init_ticks_
std::vector< entry > scalability_vector_
ExpandabilityShrinkability * expand_shrink_
timestamp last_update_
Constructor & Destructor Documentation
PerformanceInfo::PerformanceInfo () inline
PerformanceInfo::PerformanceInfo (ExpandabilityShrinkability * expand_shrink)
References current_time_slice_start_, curtick(), get_time_slice_start, Config::getInstance(), Config::max_degree_of_parallelism, NUMOFSLICES, scalability_vector_, and slices.
PerformanceInfo::~PerformanceInfo ()
Member Function Documentation
void PerformanceInfo::eclipseTimeSlices (unsigned offset)
References NUMOFSLICES, and slices.
Referenced by updateTimeSlicesToCurrentTicks().
unsigned long PerformanceInfo::getBlockSumInAllSlices ()
References SpineLock::acquire(), lock_, NUMOFSLICES, SpineLock::release(), and slices.
Referenced by report_instance_performance_in_millibytes().
void PerformanceInfo::hitCurrentSlice ()
References NUMOFSLICES, and slices.
Referenced by processed_one_block().
void PerformanceInfo::initialize ()
References current_time_slice_start_, curtick(), init_ticks_, last_update_, and nblocks_in_current_slice_.
Referenced by claims::physical_operator::ExchangeMerger::CreatePerformanceInfo(), claims::physical_operator::PhysicalAggregation::Open(), and claims::physical_operator::PhysicalProjectionScan::Open().
void PerformanceInfo::processed_one_block ()
References SpineLock::acquire(), current_time_slice_start_, curtick(), expand_shrink_, get_time_slice_start, ExpandabilityShrinkability::GetDegreeOfParallelism(), Config::getInstance(), hitCurrentSlice(), last_update_, lock_, Config::max_degree_of_parallelism, MONITOR_FRECY, SpineLock::release(), report_instance_performance_in_millibytes(), scalability_vector_, and updateTimeSlicesToCurrentTicks().
Referenced by claims::physical_operator::PhysicalAggregation::Next(), claims::physical_operator::ExchangeMerger::Next(), and claims::physical_operator::PhysicalProjectionScan::Next().
double PerformanceInfo::report_instance_performance_in_millibytes ()
References SpineLock::acquire(), BLOCK_SIZE, convertCyclesToSecond(), current_time_slice_start_, curtick(), get_time_slice_start, getBlockSumInAllSlices(), getSecond(), getSecondDuratoin(), init_ticks_, lock_, NUMOFSLICES, SpineLock::release(), TIME_SLICE, and updateTimeSlicesToCurrentTicks().
Referenced by processed_one_block().
void PerformanceInfo::updateTimeSlicesToCurrentTicks ()
References current_time_slice_start_, curtick(), eclipseTimeSlices(), get_time_slice_start, and TIME_SLICE.
Referenced by processed_one_block(), and report_instance_performance_in_millibytes().
Member Data Documentation
ticks PerformanceInfo::current_time_slice_start_
Referenced by initialize(), PerformanceInfo(), processed_one_block(), report_instance_performance_in_millibytes(), and updateTimeSlicesToCurrentTicks().
ExpandabilityShrinkability* PerformanceInfo::expand_shrink_
Referenced by processed_one_block().
unsigned long long int PerformanceInfo::init_ticks_
Referenced by initialize(), and report_instance_performance_in_millibytes().
timestamp PerformanceInfo::last_update_
Referenced by initialize(), and processed_one_block().
SpineLock PerformanceInfo::lock_
Referenced by getBlockSumInAllSlices(), processed_one_block(), and report_instance_performance_in_millibytes().
unsigned long PerformanceInfo::nblocks_in_current_slice_
Referenced by initialize().
std::vector<entry> PerformanceInfo::scalability_vector_
Referenced by PerformanceInfo(), and processed_one_block().
unsigned* PerformanceInfo::slices
Referenced by eclipseTimeSlices(), getBlockSumInAllSlices(), hitCurrentSlice(), and PerformanceInfo().
The documentation for this struct was generated from the following files:
common/ExpandedThreadTracker.h
common/ExpandedThreadTracker.cpp