Claims: InsertOptimizedHashTable::bucket Struct Reference
InsertOptimizedHashTable::bucket Struct Reference
#include <InsertOptimizedHashTable.h>
Public Member Functions
bool has_space_for_new_entry ()
bool allocate_new_entry (unsigned &new_entry_index)
Public Attributes
meta_data head
entry entrys [(Bucket_Size-sizeof(head))/sizeof(entry)]
Member Function Documentation
bool InsertOptimizedHashTable::bucket::allocate_new_entry (unsigned & new_entry_index) inline
References head, and InsertOptimizedHashTable::meta_data::tuple_count.
Referenced by InsertOptimizedHashTable::insertEntry().
bool InsertOptimizedHashTable::bucket::has_space_for_new_entry () inline
References Bucket_Capacity, head, and InsertOptimizedHashTable::meta_data::tuple_count.
Referenced by InsertOptimizedHashTable::insertEntry().
Member Data Documentation
entry InsertOptimizedHashTable::bucket::entrys[(Bucket_Size-sizeof(head))/sizeof(entry)]
Referenced by InsertOptimizedHashTable::insertEntry(), and InsertOptimizedHashTable::BucketIterator::nextTuple().
meta_data InsertOptimizedHashTable::bucket::head
Referenced by allocate_new_entry(), has_space_for_new_entry(), InsertOptimizedHashTable::insertEntry(), InsertOptimizedHashTable::BucketIterator::nextTuple(), and InsertOptimizedHashTable::~InsertOptimizedHashTable().
The documentation for this struct was generated from the following file:
common/InsertOptimizedHashTable.h