Claims: PartitionID Struct Reference
PartitionID Struct Reference
#include <ids.h>
Public Member Functions
PartitionID (ProjectionID projection_id, PartitionOffset off)
PartitionID ()
bool operator== (const PartitionID &r) const
bool operator< (const PartitionID &r) const
PartitionID (const PartitionID &r)
std::string getName () const
std::string getPathAndName () const
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Public Attributes
ProjectionID projection_id
PartitionOffset partition_off
Friends
class boost::serialization::access
Detailed Description
PartitionID: a partition corresponds to one projection.
Constructor & Destructor Documentation
PartitionID::PartitionID (ProjectionID projection_id, PartitionOffset off) inline
PartitionID::PartitionID () inline
PartitionID::PartitionID (const PartitionID & r) inline
References partition_off, and projection_id.
Member Function Documentation
std::string PartitionID::getName () const inline
References partition_off, projection_id, ProjectionID::projection_off, and ProjectionID::table_id.
Referenced by BlockManager::addPartition(), DiskChunkReaderIteraror::DiskChunkReaderIteraror(), HDFSChunkReaderIterator::HDFSChunkReaderIterator(), bottomLayerCollecting::Open(), claims::physical_operator::PhysicalProjectionScan::Open(), IndexScanIterator::Open(), and BlockManager::removePartition().
std::string PartitionID::getPathAndName () const
References Config::data_dir, partition_off, projection_id, ProjectionID::projection_off, and ProjectionID::table_id.
Referenced by DiskChunkReaderIteraror::DiskChunkReaderIteraror(), BlockManager::loadFromDisk(), and BlockManager::loadFromHdfs().
bool PartitionID::operator< (const PartitionID & r) const inline
References partition_off, and projection_id.
bool PartitionID::operator== (const PartitionID & r) const inline
References partition_off, and projection_id.
template<class Archive > void PartitionID::serialize (Archive & ar, const unsigned int version) inline
References partition_off, and projection_id.
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
PartitionOffset PartitionID::partition_off
Referenced by getName(), getPathAndName(), hash_value(), bottomLayerSorting::Open(), operator<(), operator==(), PartitionID(), and serialize().
ProjectionID PartitionID::projection_id
Referenced by getName(), getPathAndName(), hash_value(), bottomLayerSorting::Open(), operator<(), operator==(), PartitionID(), and serialize().
The documentation for this struct was generated from the following files:
common/ids.h
common/ids.cpp